### ISSUE TITLE
Low contrast betwean "triangle" and its background in Thunderbird

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#1016]
Ubuntu 18.04, Thunderbird 60.2.1.
I'm not sure about the correct name of that "triangle" I'm talking about, but it is the one to show/hide subfolders. I don't remember how it looked in the older version of Thunderbird but now it bugs me for some reason.

This is how it looks:
![zrzut ekranu z 2018-12-04 10-04-36](https://user-images.githubusercontent.com/1629120/49435063-9c63f700-f7ad-11e8-9e7e-75182e5ffd48.png)

And this is how it looks on mouse hover:
![zrzut ekranu z 2018-12-04 10-07-03](https://user-images.githubusercontent.com/1629120/49435106-b3a2e480-f7ad-11e8-8bf5-fcbf4f04bd65.png)

**Comment by mivoligo** [comment]
Just checked and it is like:
![2](https://user-images.githubusercontent.com/1629120/49436074-17c6a800-f7b0-11e8-86ed-f813d9a89c05.png)
and on hover:
![1](https://user-images.githubusercontent.com/1629120/49436099-1e551f80-f7b0-11e8-8365-2f5e2a382992.png)

Looks good to me but now I've noticed that the "triangles" which are not focused are going "lighter" on hover, whereas those focused going "darker" on hover. Not sure if that is intentional.

**Comment by mivoligo** [comment]
Just checked in Adwaita. In both cases: focused and not focused, the triangles go less transparent on hover.

**Comment by Feichtmeier** [comment]
Okay thanks!
I bet then we can do something for this
Treeview > row > image
Probably, let's see

**Comment by Feichtmeier** [comment]
Yup it is the same in the widget factory. I think @clobrano  worked on these treeview assets once, could you help here Carlo?
