### ISSUE TITLE
'Today' and 'Tomorrow' buttons in gnome-weather are insensitive

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1021]
## Expected Behavior

'Today' and 'Tomorrow' buttons in gnome-weather should be different when one is selected.

## Actual Behavior

'Today' and 'Tomorrow' buttons in gnome-weather are the same regardless which one is selected.

## Steps to Reproduce the Problem

  1. Install gnome-weather (sudo apt install gnome-weather)
  2. Open gnome-weather
  3. Press on 'Today' and 'Tomorrow' buttons

## Specifications

~$ snap info communitheme

snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: today at 11:05 CET
channels:                          
  stable:    0.1 (1364) 18MB - <
  candidate: ↑                 
  beta:      ↑                 
  edge:      0.1 (1421) 18MB - 
installed:   0.1 (1364) 18MB -

Software that presents the issue:
- Name: gnome-weather
- Version: 3.26.0

Thanks!

**Comment by clobrano** [comment]
>Edit: I think we need to re-investigate our osd-buttons 

Yeah, probably we have less chances to test osd buttons
