### ISSUE TITLE
Design Discussion: What should an automatically created icon look like?

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1022]
Hello, Yaru contributors! I wanted to discuss the design of automatically created icons for applications without Suru icon.

There are three variants:

- **With dark background**
It blend good with dock.
- **With light background**
It blend bad with dock.
- **With icon color**

![example](https://user-images.githubusercontent.com/40228953/49599172-c24def00-f999-11e8-87f0-2a576d49cbd1.png) ![example2](https://user-images.githubusercontent.com/40228953/49599173-c24def00-f999-11e8-9e93-fd3be5e9fd49.png) ![example3](https://user-images.githubusercontent.com/40228953/49599174-c2e68580-f999-11e8-8c03-2399cc9f3c87.png)

I'm waiting for your opinion

**Comment by clobrano** [comment]
Could you please use the forum for such discussion? Here it'll be invisible for many people that do not partecipate in development. Moreover the forum has a poll feature
