### ISSUE TITLE
[Missing icon] Backup file

### ISSUE THREAD

**Issue by vitalkanev** [ubuntu/yaru#1025]
MIME Type: `application/x-trash`

```
$ git describe && lsb_release -rci
18.10.7-180-g038e0c1a
Distributor ID:	Ubuntu
Release:	18.04
Codename:	bionic
```
![2018-12-07 17-53-17](https://user-images.githubusercontent.com/18398761/49663567-30f58000-fa60-11e8-840d-df11ff15dbb6.png)

**Comment by Feichtmeier** [comment]
@ubuntujaggers @eaglersdeveloper :D

**Comment by clobrano** [comment]
This is Awdaita

![screenshot from 2018-12-08 11-12-44](https://user-images.githubusercontent.com/2883614/49684885-545d1100-fada-11e8-99a6-e0fc04409b7f.png)

**Comment by eaglersdeveloper** [comment]
https://github.com/snwh/suru-icon-theme/issues/110

**Comment by meetdilip** [comment]
Do you guys like something like this instead of a plain text icon ?

https://www.iconfinder.com/icons/383184/backup_icon

**Comment by ubuntujaggers** [comment]
Is the answer just to clone the normal (Suru) icon to this position, like Adwaita does?  I'm not sure I understand the symbolic logic of the one on Filefinder...?

**Comment by Feichtmeier** [comment]
Hmmm maybe the same icon but with @meetdilip 's glyph

**Comment by clobrano** [comment]
Sorry @meetdilip, but I don't think that icon would be nice in suru. Is there any example from most used icons set?

**Comment by clobrano** [comment]
Consider that this files are usually hidden. I'd say that we can even keep it as it is

**Comment by Feichtmeier** [comment]
I think he means only the shape as a glyph

Like this icon but instead of the (C) that backup icon but in "suru" style (thinner)
![image](https://user-images.githubusercontent.com/15329494/49691975-c2dbb680-fb4e-11e8-9124-f15dc8aa5a27.png)

**Comment by meetdilip** [comment]
I meant the above. The file background and a time indicator glyph instead of the copyright symbol in the icon by @Feichtmeier 

@clobrano Attached what Papirus does

[application-x-trash.zip](https://github.com/ubuntu/yaru/files/2660184/application-x-trash.zip)

**Comment by meetdilip** [comment]
I thought the icon should say that it is a document, from an older time. Here is a mockup

![application-x-trash 2x](https://user-images.githubusercontent.com/6965443/49692859-2afbbe00-fb8a-11e8-981d-29f8e7c6d6e7.png)

**Comment by meetdilip** [comment]
If you like it white 

![application-x-trash 3x](https://user-images.githubusercontent.com/6965443/49692900-0fdd7e00-fb8b-11e8-8474-1116f448a915.png)

**Comment by vitalkanev** [comment]
Maybe we could "steal" design from Breeze icons

[application-x-trash.svg from Neon (I guess bionic)](https://github.com/ubuntu/yaru/files/2660453/application-x-trash.zip)

**Comment by ubuntujaggers** [comment]
I think putting a "turn back the clock" glyph on the mimetype for a normal document would be really easy, happy to do that in the coming week?

**Comment by eaglersdeveloper** [comment]
Easy to confuse with the thumbnail loading icon.

**Comment by vitalkanev** [comment]
Maybe we can use the recycle icon? See my comment above понедельник, 10 декабря 2018г., 12:58 +03:00 от Eaglers  notifications@github.com :

**Comment by Feichtmeier** [comment]
We could also make a glyph out of one of these icons:
https://github.com/ubuntu/yaru/blob/master/icons/src/scalable/source-symbolic.svg

For example the floppy symbolic is pretty common for "saved" or "safe" (even if the kids don't even know what that floppy is ;D )

**Comment by madsrh** [comment]
> ...a "turn back the clock" glyph on the mimetype...

+1 for the "turn back the clock" idea. A quick Google search also implies that it's the most common used one.

https://www.google.com/search?tbm=isch&q=backup+icon

**Comment by ubuntujaggers** [comment]
The mimetypes seem mostly very simple - just a glyph on a white "rectircle":

![copying](https://user-images.githubusercontent.com/38893390/49869353-14629a80-fe08-11e8-8fd1-4bd1e4e4e0f6.png)

So maybe it should be as simple as:

![backup](https://user-images.githubusercontent.com/38893390/49869367-1d536c00-fe08-11e8-8d4c-457225eaf63b.png)

?

**Comment by ubuntujaggers** [comment]
Okay, I'll do a PR today  :)

**Comment by meetdilip** [comment]
Is the circle a bit asymmetric ? The bottom part seems to be stretched and long. Or is it just an illusion ?

**Comment by eaglersdeveloper** [comment]
I prefer make as in Humanity: make the file icon translucent.

**Comment by ubuntujaggers** [comment]
@meetdillip It is long - I thought it best to copy exactly the dimensions of the circle from the existing Copying icon shown above - what does everyone think?

**Comment by ubuntujaggers** [comment]
Oh, maybe the hands of the clock could be lower, is that what you mean?

**Comment by meetdilip** [comment]
@ubuntujaggers I meant the partial circle with arrow. It looks a bit stretched at the bottom. Oval than a circle. 

![backup icon oval](https://user-images.githubusercontent.com/6965443/50008977-bbe3f680-ffdb-11e8-8a8e-2142a06bb5f3.png)

**Comment by ubuntujaggers** [comment]
Oh yeah, it's definitely an oval, happy to redraw that if people don't like it.  I literally took/edited the "circle" (really an oval) from the existing icon.

**Comment by clobrano** [comment]
To show mockups I prefer a PR :) the bug is more for describing the problem

**Comment by ubuntujaggers** [comment]
Ah, okay, I've been doing it wrong lol. I'll make a PR as soon as I get chance, having a bit of drama today with a leaky roof!

**Comment by Feichtmeier** [comment]
Fixed with #1061

**Comment by clobrano** [comment]
![image](https://user-images.githubusercontent.com/2883614/50587818-bd3c6c80-0e7f-11e9-9402-66724124810d.png)

**Comment by clobrano** [comment]
My bad, I had old `application-x-trash.png` images that where the one working. I'll propose a patch right away
