### ISSUE TITLE
Treeview header misses a border-top

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1028]
![image](https://user-images.githubusercontent.com/15329494/49699726-f7925100-fbd4-11e8-908b-4df56a3d136b.png)

@clobrano do you know why we never added a border here? For example because it would cause a double border in some circumstances or something like that?

I think it would look more complete with a border-top
![image](https://user-images.githubusercontent.com/15329494/49699770-84d5a580-fbd5-11e8-878f-83b6250880f5.png)

It's here: https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.20/_common.scss#L2216

**Comment by Paz-it** [comment]
> because it would cause a double border in some circumstances or something like that?
YES! that's exactly the reason.

**Comment by Feichtmeier** [comment]
@Paz-it could you show me an example app?
I think no border looks far more broken than a double border :man_shrugging:

**Comment by Paz-it** [comment]
Open widget factory and see for yourself. in most apps it is having the the header bar border on top
or the border of the window it seats on top of it.

**Comment by clobrano** [comment]
In fact, in widget factory all the treeview headers have a top border, however even Nautilus doesn't have it

![image](https://user-images.githubusercontent.com/2883614/49727594-ee56c200-fc70-11e8-8226-78d8c35420d2.png)

**Comment by Feichtmeier** [comment]
They "have" only a top border when the table is put in a container which has a border itself but it's not their border, it's the border of the container

**Comment by clobrano** [comment]
Yes of course, however if you add a proper top-border, this would be doubled when in a container, unless we can avoid that

**Comment by Feichtmeier** [comment]
If you two guys think it's not an issue then I'm fine. However I think this looks very unusual. I think some might even think that something looks broken there because they don't know the reasoning. Especially when I look at the screenshot of the table inside the tab. It looks like - if UI elements where fluid - something could float inside that opened border. :D
I think arc dodges this by adding a small margin to the left and right border of those header buttons, resulting in a look that is opened at all edges of the header buttons and no only on three sides

Adwaita has that

**Comment by clobrano** [comment]
I agree that doesn't look good this way. Adwaita I think does not have it, it just has a darker color above the treeview usually , which works as border. Probably I have a holder version of Arc, in 16.04 it looks this way

![image](https://user-images.githubusercontent.com/2883614/49747479-cf255800-fca3-11e8-9119-4b5d5460c6ab.png)

**Comment by clobrano** [comment]
This is how it looks adding a top-bar (not good either)
![image](https://user-images.githubusercontent.com/2883614/49813651-2f7dcd80-fd68-11e8-8f3d-8e1c42f29d9f.png)
![image](https://user-images.githubusercontent.com/2883614/49813668-39073580-fd68-11e8-9650-69d3ce4a0198.png)

**Comment by Feichtmeier** [comment]
Ah never mind then. I don't know what's a less common: table in a tab or table without a box
Let's close this
