### ISSUE TITLE
combobox entry border wrong error/warning color

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1031]
The border between entry and button in a combobox does not take the right color when the entry has a class `.error` or `.warning`.

This border is styled here

https://github.com/ubuntu/yaru/blob/7cc63d96f0b8bc55d5db7517c574bd9fec22d9d0/gtk/src/light/gtk-3.20/_common.scss#L385

This is really visible in Yaru-dark, where the "non-focus" color is 35% darker

![image](https://user-images.githubusercontent.com/2883614/49726749-fe6da200-fc6e-11e8-85bc-7ab48eced24b.png)

Apparently there is no difference in this regards between Adwaita and Yaru, still only Yaru has this issue

**Comment by Feichtmeier** [comment]
We explicitly make that left button border orange but then make the entry border red
I would say we need to make it red too when we focus that entry in the same are were the PR was

**Comment by clobrano** [comment]
Yes, however there is no trace of such code in Adwaita and still it works

**Comment by monday15** [comment]
@clobrano is it gedit's searchbar? there is some code, recently added:  
https://gitlab.gnome.org/GNOME/gtk/merge_requests/315
parent issue  
https://gitlab.gnome.org/GNOME/gtk/issues/1304

**Comment by clobrano** [comment]
This is evince, but as I get at home I'll check the links, thanks!

**Comment by clobrano** [comment]
This is exactly the same issue :D thanks @monday15!
