### ISSUE TITLE
Icon for Thunderbird inc. mockup

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1035]
Hi all,

Before I do a PR, how about something like:

![suru thunderbirdpng](https://user-images.githubusercontent.com/38893390/49826734-92c72a00-fd7f-11e8-8c88-fd461d143104.png)

![image](https://user-images.githubusercontent.com/38893390/49826630-44199000-fd7f-11e8-87c0-9e1098f9d88f.png)

?

**Comment by ubuntujaggers** [comment]
...or maybe lighter blue to minimise clash with LibreOffice Writer:

![suru thunderbird lighter](https://user-images.githubusercontent.com/38893390/49827034-3ca6b680-fd80-11e8-860f-28ffff2d76f0.png)

![image](https://user-images.githubusercontent.com/38893390/49827023-331d4e80-fd80-11e8-9704-3357725ee6ed.png)

?

**Comment by ubuntujaggers** [comment]
First probably looks better tbh.

**Comment by Feichtmeier** [comment]
That's a very good BG!
Is this already the new icon from Thunderbird?

**Comment by ubuntujaggers** [comment]
It's the 2018 version on Wikipedia: https://en.wikipedia.org/wiki/Mozilla_Thunderbird#/media/File:Thunderbird_Logo,_2018.svg

I note it's Creative Commons by Attribution - as it's the normal icon, I presume it's attributed somewhere in the installation of the app itself?

**Comment by Feichtmeier** [comment]
I would prefer the second lighter BG as the contrast to the logo is higher

And yes you are using the correct icon
![screenshot_20181211-211133_samsung internet](https://user-images.githubusercontent.com/15329494/49827451-a081ad00-fd89-11e8-8276-dd2729518cc7.jpg)

**Comment by ubuntujaggers** [comment]
Any more comments on Thunderbird or should I PR today?

**Comment by clobrano** [comment]
To me, the last one was very good :+1:

**Comment by eaglersdeveloper** [comment]
Can you make the background of the same color as the background of the Firefox icon?

**Comment by Feichtmeier** [comment]
@eaglersdeveloper consider that firefox and thunderbird are placed directly beside each other on a fresh ubuntu install

**Comment by eaglersdeveloper** [comment]
And not only because of this. Thunderbird is a product by Mozilla. It recently received a new icon, Proton UI and Quantum engine like Firefox. Need a single style.

**Comment by techmedixx** [comment]
Both are excellent. The second one works well with dark environment themes. The first one does too but really fits best with the light themes. The Yaru/Saru icons are a welcome addition. I love the uniformity of them and they look great with every desktop environment I have tried. In fact, your work inspired me to attempt creating some of my own to fill in the gaps.
