### ISSUE TITLE
GtkToolbar button styling problems

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1036]
1) the hover effect differs between the dark and the light variant (light is basically the normal buttons hover, but dark is flat and almost black)
![peek 2018-12-12 10-16](https://user-images.githubusercontent.com/15329494/49859106-08baa800-fdf7-11e8-9e9c-50cb42657aba.gif)

2) the dark background hover is very strong (if we end up with a flat hovering or not, the dark backdrop looks like you teleport the backdrop button to the foreground :D )
![peek 2018-12-12 10-08](https://user-images.githubusercontent.com/15329494/49859145-1708c400-fdf7-11e8-8dae-ceeb0d9f190d.gif)

3) Maybe we should compare it to the active effect in both variants

**Comment by Paz-it** [comment]
Those hover thick borders on the Dark in your screenshot above dose not look like that in  Dark version unless I'm not aware of recent changes.... and now it's my turn to say I don't understand what you are talking about ?!? 
![screenshot from 2018-12-12 23-58-15](https://user-images.githubusercontent.com/37431503/49901601-473d7a80-fe6a-11e8-8636-7e7a09ea51ad.png)

**Comment by clobrano** [comment]
I believe the purpose is to make dark variant look more like light one,
which has this border effect on hover.
I think that having 3D toolbar buttons in normal state would make the
toolbar messier

**Comment by Feichtmeier** [comment]
No I have no purpose or strong opinion. 
1) is just a fact that the backdrop hover of the dark theme is completely different than the foreground hover 
And when we adapt the backdrop hover for the dark theme we could also lower it a little bit without changing the style

**Comment by clobrano** [comment]
Looking at the css, we are not making the toolbar flat on purpose, it's the button toolbar that has a .flat class, so we are actually following designer decision

**Comment by Feichtmeier** [comment]
Okay! Let's keep it this way!

But the backdrop:hover for the light theme's toolbar is different than
the backdrop:hover for the dark theme

**Comment by clobrano** [comment]
You are right, I am trying to fix that without affecting the normal buttons
