### ISSUE TITLE
Ensure GNOME shell and/or GTK 3.32+ compatibility

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1041]
Changes that are either WIP or already in 3.32 which we need to check or eventually correct in our code, let's keep this opened until 19.04. And let's check if we need a different branch for this. (We jumped over the branch-problem once more with nautilus 3.26/3.30 styling but maybe this is over now)
Maybe the list extends, maybe not:

- [x] replace calendar assets with (s)css + the icon theme's icons
Gnome changes on gitlab: https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/301
Yaru issue: https://github.com/ubuntu/yaru/issues/1203

- [x] replace close button with (s)css + the icon theme's icons
Gnome changes on gitlab: https://gitlab.gnome.org/GNOME/gnome-shell/issues/782
Yaru issue: https://github.com/ubuntu/yaru/issues/1202

- [x] replace shell app grid page indicator with scss
Gnome changes on gitlab: https://gitlab.gnome.org/GNOME/gnome-shell/commit/27c660d2a9204bf423103bc83dc8e2f162b4474b
Yaru issue: https://github.com/ubuntu/yaru/issues/1204

- [x] Adjust user icon
Gnome changes on gitlab: https://gitlab.gnome.org/GNOME/gnome-shell/commit/33e05f591256276d98ebff28c89861f00c537e0c
Yaru issue: https://github.com/ubuntu/yaru/issues/1241

**Comment by Feichtmeier** [comment]
@clobrano I saw that our current asset+css approach still works in disco but I don't know if they already updated the shell code. 
If it would still work, we could keep it like this and dodge once again a separate version branch for 18.4/18.10 and 19.4 - do you agree?

**Comment by clobrano** [comment]
My understanding is that we can't have several branches, we can only provide snap or default installation (so .deb). If it still works it's fine, just we can still keep an eye on it in case of problems.
 
I didn't try, but basically replacing with CSS should work in each version, shouldn't it?

**Comment by Feichtmeier** [comment]
Doh, you are right :man_facepalming:

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru/pull/1234
