### ISSUE TITLE
New icons for Software Center, Software Updater and Software & Updates

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1051]
Software Center and Software Updater icons are difficult distinguished by users.

![2018-12-18 18-28-48](https://user-images.githubusercontent.com/40228953/50160659-505b9b00-02f3-11e9-9ead-88e93799d58a.png) ![2018-12-18 18-29-24](https://user-images.githubusercontent.com/40228953/50160664-52bdf500-02f3-11e9-97ca-0035ddb5fa70.png)

Did you guessed what the application, if app name was removed?

![2018-12-18 18-30-47](https://user-images.githubusercontent.com/40228953/50160879-b811e600-02f3-11e9-9ba7-e9c92a66c015.png)

What if we create icons with the A letter, but with different pictograms and background?

![software-icons](https://user-images.githubusercontent.com/40228953/50160897-c52ed500-02f3-11e9-919c-2579ba926dd3.png)

**Comment by Feichtmeier** [comment]
agreed!However I would not use that A at all for the software updater

The icon set Suru++ got it right imho. Cant link it atm but it s basically only the refresh arrow

**Comment by Feichtmeier** [comment]
and the reason to drop the A would be, that the A stands for APPS but the software updater does only update Apps. Mostly packages that are not directly "apps"

**Comment by Feichtmeier** [comment]
hm on the other side those three A''s toggether look great. 

Would love to see that in color
And I agree that that globe is pretty bad :)

**Comment by eaglersdeveloper** [comment]
I still need an opinion of others.

**Comment by Feichtmeier** [comment]
Then tag them :)
@madsh @clobrano @ubuntujaggers

**Comment by clobrano** [comment]
I think it's a good Idea :+1:, could we take this chance to fix the problem advised by mpt about the fact that a typographic A (uppercase A) has the think leg on the left side instead that on the right one? :)

**Comment by ubuntujaggers** [comment]
Great idea :) the only thing I would suggest is (as per previous discussions) not incorporating a pretend progress bar into one of the designs.

What's the actual difference between Software Updater and Software & Updates?  If Software & Updates is basically your software update settings (I can't check because I'm not on Ubuntu just now), then the cog is a great glyph and you can nick the cog from the existing settings icon for maximum consistency  :)

The circle arrow seems to be standard for refresh, update, so that's a good one too.  And then maybe the software centre can just be an "A" without a progress bar?

The globe is unintuitive, and it's also not really consistent Suru style (because it's a symbol of a globe rather than a fully composed pictogram).  I like this "A" concept better for the family of icons  :)

**Comment by clobrano** [comment]
> the only thing I would suggest is (as per previous discussions) not incorporating a pretend progress bar into one of the designs.

+1 on this, absolutely

**Comment by madsrh** [comment]
> What's the actual difference between Software Updater and Software & Updates?

+1 This **really** is confusing for new users (and @ubuntujaggers 🤣 )

Anyway Googling for App / software / center / store returns these (in totally random order) for "inspiration":

![image](https://user-images.githubusercontent.com/3986894/50190387-566c6e80-0329-11e9-95dc-1443460e3214.png)

I was actually surprised to learn that the shoppingbag (which [Ubuntu started using almost ten years ago](https://aozoeky4dglp5sh0-zippykid.netdna-ssl.com/wp-content/uploads/2013/03/omg.jpg) is still so widely used (Chrome, Playstation, Microsoft and[ until recently](https://www.theverge.com/2017/5/11/15624990/google-updated-play-store-icon) Android)

**Comment by clobrano** [comment]
When gnome-software loads for the first time, for a split second the logo appears on the window view. Does anybody knows if the logo is taken from the Application itself or from the icon set (I believe the first)?

**Comment by eaglersdeveloper** [comment]
You like this?

![software-properties](https://user-images.githubusercontent.com/40228953/50219962-506aa200-03aa-11e9-9d0a-3567f1251915.png)

**Comment by madsrh** [comment]
@eaglersdeveloper 
I would like to see the gear centered so the padding is the same on both sides. I've illustrated it with red below: (Sorry for the quality of the image, but hopefully you understand what I mean)
![image](https://user-images.githubusercontent.com/3986894/50221110-6b321c00-0394-11e9-9c21-10d1b8e3b8f9.png)

Also, a white and gray icon on a light gray background looks a bit pale IMHO - perhaps another background color would work better 🤷‍♂️

**Comment by meetdilip** [comment]
I had this displayed on another issue. My own design and very recent. Just adding here for discussion

Software updater

![update 1x](https://user-images.githubusercontent.com/6965443/50223710-02619880-03c2-11e9-99cb-dd61bb305d73.png)
![update 2x](https://user-images.githubusercontent.com/6965443/50223712-02fa2f00-03c2-11e9-8d04-962906db2c67.png)

I can provide the SVG if required. I think it clearly defines / indicates an app, update and, Ubuntu reference colour. Suggestions are welcome.

**Comment by meetdilip** [comment]
> Did you guessed what the application, if app name was removed?
> 
> ![2018-12-18 18-30-47](https://user-images.githubusercontent.com/40228953/50160879-b811e600-02f3-11e9-9ba7-e9c92a66c015.png)

It is either network or network settings. Widely used for internet as well.

**Comment by eaglersdeveloper** [comment]
It doesn't look very perfect.

![software-properties2](https://user-images.githubusercontent.com/40228953/50224088-6e3e0400-03b6-11e9-85ab-dc323e17ead3.png)

**Comment by eaglersdeveloper** [comment]
> It is either network or network settings. Widely used for internet as well.

This is Software & Updates icon, so I decided to create new icons.

**Comment by ubuntujaggers** [comment]
@eaglersdeveloper, might be worth trying a colour background to make the gear stand out?

**Comment by clobrano** [comment]
> could we take this chance to fix the problem advised by mpt about the fact that a typographic A (uppercase A) has the think leg on the left side instead that on the right one? :)

please? :smile:

**Comment by ubuntujaggers** [comment]
@eaglersdeveloper , it's just a case of flipping the "A", we somehow ended up with a backwards one in Ubuntu that we've been using for years:

![image](https://user-images.githubusercontent.com/38893390/50226602-90765880-039b-11e9-8288-08a2a950b5e9.png)

Versus:

![image](https://user-images.githubusercontent.com/38893390/50226634-a552ec00-039b-11e9-8fee-585a6e7e6eb8.png)

As @clobrano notes when you have thick and thin strokes (rather than uniform) the thick one should be on the right.

**Comment by taciturasa** [comment]
> I think it's a good Idea , could we take this chance to fix the problem advised by mpt about the fact that a typographic A (uppercase A) has the think leg on the left side instead that on the right one? :)

Honestly I don't think the thin line ends up scaling well and would be in favor of making both of the strokes symmetrically thick.

**Comment by clobrano** [comment]
That's also a possible solution of course, the main point is not have the
thin leg on the wrong side

**Comment by ubuntujaggers** [comment]
Yep, I'm also happy with two thick legs, I remember I didn't like the thin leg when it was introduced.  Originally the A-for-apps had uniform thicknesses:

![image](https://user-images.githubusercontent.com/38893390/50233365-32ea0800-03ab-11e9-95df-e88ee683c2bb.png)

Also, having two identical legs would nullify the debate around the gear being centred relative to the icon or the legs  :)

**Comment by taciturasa** [comment]
Yes!!!

**Comment by eaglersdeveloper** [comment]
What about thinner letter?

![software-store2](https://user-images.githubusercontent.com/40228953/50238067-e1a43d80-03d7-11e9-9890-c7ace68080a2.png)

**Comment by Feichtmeier** [comment]
I'd prefer the fat

**Comment by Feichtmeier** [comment]
I also agree with @madsrh that we should not use gray on every app. It almost annoys me (hihi). Suru or not too much gray is boring as hell

**Comment by eaglersdeveloper** [comment]
Meet new icons!

![software-store](https://user-images.githubusercontent.com/40228953/50266321-95d7af80-043c-11e9-88b3-31ad0523e83f.png)
![software-updater](https://user-images.githubusercontent.com/40228953/50266327-996b3680-043c-11e9-81cb-5c3447301917.png)
![software-properties](https://user-images.githubusercontent.com/40228953/50266330-9bcd9080-043c-11e9-8f0f-fc39371f0ddc.png)

**Comment by taciturasa** [comment]
I love these! Though I think we need to decide on a new signifier for the store itself. The progress bar def. results in confusion even when it isn't partially filled.

**Comment by clobrano** [comment]
I like them :+1: 
I had the same impression on the progress bar, but it reminds the old icon enough to be recognizable I believe. The last icon needs color as well, IMO, the gear details are lost otherwise

**Comment by Feichtmeier** [comment]
That green is too bright imho :)
And the gray is too gray :D
Other than that, really nice work

**Comment by Feichtmeier** [comment]
@eaglersdeveloper could you darken the gray a bit and then make a pull request with those three?

**Comment by mivoligo** [comment]
IMO the best icon for updates I've ever seen was the one on webOS. It shows the idea of updates being something good and special and not just a tusk one needs to do every now and then.
![update_webos](https://user-images.githubusercontent.com/1629120/50958696-3c055b00-14b9-11e9-86a9-49578f18c390.png)

**Comment by mivoligo** [comment]
@eaglersdeveloper, probably only if the user first know that this icon goes with this application. Which, I guess, is true with almost all applications.

**Comment by madsrh** [comment]
> could you darken the gray a bit and then make a pull request with those three?

Any progress with this @eaglersdeveloper ?

**Comment by ubuntujaggers** [comment]
@eaglersdeveloper Can you please commit these svgs to a branch so we can get our hands on them  :)

**Comment by Feichtmeier** [comment]
Closing this since the recent direction of out icon theme :)
Current progress can be seen here: https://github.com/ubuntu/yaru/issues/1180
and here: https://github.com/ubuntu/yaru/pull/1209

**Comment by fitojb** [comment]
> Current progress can be seen here: #1180
> and here: #1209

Those PRs don’t seem to include the updated “A” with uniform-width stems. Were they lost?

**Comment by clobrano** [comment]
Sorry, by stem do you mean the "legs" of the character "A"?

**Comment by fitojb** [comment]
Yes, of course :) https://www.fontsmith.com/blog/2016/06/29/the-a-z-of-typographic-terms

**Comment by clobrano** [comment]
They look uniform to me

![image](https://user-images.githubusercontent.com/2883614/54591229-1d2bc380-4a2a-11e9-82c9-2cc727b27d62.png)

**Comment by fitojb** [comment]
I had a local issue, very sorry for the noise.
