### ISSUE TITLE
Missing fullcolor battery icon

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1053]
![screenshot-20181219100927-1920x1080](https://user-images.githubusercontent.com/15329494/50218891-c280be00-038d-11e9-97b2-1c39aa1e2858.png)

@ubuntujaggers if you find time :) Would be a nice addition

**Comment by eaglersdeveloper** [comment]
I prefer to change icons to symbolic.

**Comment by Feichtmeier** [comment]
I fear that would mean a change in the app itself which is out of the scope of this project here so let's provide a coloured icon for now

**Comment by ubuntujaggers** [comment]
Is this one a similar case to printer (i.e., going to symbolic anyway) or is it still required?  I can do this one next if so...

**Comment by Feichtmeier** [comment]
The only place I found it was in that app
So we either tag it as low prio or we just close the issue :)
There are other more important things to do for you two guys :) like symbolic icons of all our all icons / update them
