### ISSUE TITLE
Firefox Nightly shows solid white checkboxes on dark theme, rendering them invisible on white web page backgrounds

### ISSUE THREAD

**Issue by kode54** [ubuntu/yaru#1054]
Thank you for contributing to **Yaru**, the next Ubuntu default Theme made by the community.

If you found a bug please consider to fill below information, this will help us to understand the problem and we don't bother you with other questions :)

If you're filing an issue for a missing icon, look for **Icon Request** section below.

Thanks a lot!

------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior

I installed this theme, and switched my Yaru session to the Yaru-dark theme. Then I ran Firefox Nightly. I expected checkboxes to at least have an outline on them, so they show up in web pages that have a white background, as so darn many do, voiding my theme preference.

## Actual Behavior

Firefox rendered all checkboxes as white, with no outline, so they are completely invisible on a web page with a white background.

## Steps to Reproduce the Problem

  1. Log into Yaru Wayland session.
  2. Switch theme to Yaru-dark.
  3. Open Firefox Nightly.
  4. Browse to any web form with checkbox controls.

## Specifications

Software installed from Arch User Repository, which makes no patches against the Git source tree, only picks a specific version tag (`18.10.7`, in this case) and installs all of the contents in the right places, splitting the theme into sub-packages for sound, gtk, gnome-shell, icon, and session.

Software that presents the issue:
- Name: Firefox Nightly
- Version: 66.0a1.20181218-1

Please let me know if this is an issue with out of date theme version, so that I may inform the packager, and/or contribute my own updated packaging configuration.

**Comment by clobrano** [comment]
Hi @kode54, thanks for taking time to report this

Does this issue happen on not-nightly Firefox?

**Comment by Feichtmeier** [comment]
I can confirm this on regular Firefox well

**Comment by clobrano** [comment]
I am afraid we can't do much in this case, unless there's some css target that let us know which background color the page has...

**Comment by clobrano** [comment]
Yeah, we used a transparent bg some time ago to cope with different panel bg, but inside the theme the panels might not have the same color, but  at least are all dark. In white pages we cannot allow that
