### ISSUE TITLE
Add proper style for selected text in Evince

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1069]
see https://gitlab.gnome.org/GNOME/evince/issues/1043 for more information

important extract from the link above

> Having said that, have you tried adding Evince support in Yaru itself? After looking at Yaru source, I think the following should work (not tested):
>
>     /* Override Evince text selection */
>     evview.content-view:selected {
>       @extend %selected_text;
>     }

**Comment by monday15** [comment]
> ```
> /* Override Evince text selection */
> evview.content-view:selected {
>   @extend %selected_text;
> }
> ```

This stuff should not work. Application css styles has higher priority than theme styles, so [this code](https://gitlab.gnome.org/GNOME/evince/blob/master/shell/evince.css#L23-25) will change selection background to @theme_selected_bg_color anyway.

**Comment by clobrano** [comment]
I rebuild Evince without the css part underlined by @monday15, and the result is bad as well

![image](https://user-images.githubusercontent.com/2883614/50592635-47430000-0e95-11e9-8ef0-f009b4840c1b.png)

what is most important is that Adwaita results to be broken as well. In the end, we might need to consider a comeback to orange as text selection color, since it is working only in Gedit so far

@madsrh , @Feichtmeier

**Comment by Feichtmeier** [comment]
Oh what a nice idea to double check that!
Yes it's a mess. Only entries, textview and chrome work. Firefox, libre office, evince don't work
I think gtk is currently not really supporting different selection colours

**Comment by madsrh** [comment]
@clobrano I think it's a good decision after all this trouble - what a journey!

**Comment by clobrano** [comment]
closing this since it is not technically possible right now
