### ISSUE TITLE
nautilus 3.30 not styled properly

### ISSUE THREAD

**Issue by iainlane** [ubuntu/yaru#1086]
This should have been fixed in https://github.com/ubuntu/yaru/pull/982, but it's not working for me with yaru master.

![yarunautilus330](https://user-images.githubusercontent.com/321014/50772916-37f1f700-1287-11e9-9eb9-772bc5a6d358.png)

Part of the problem is that the path bar isn't "`linked`" (any more? I didn't see when it was, must have been when the PR was being developed though). If I use the inspector to add that class to the widget, it's better but some things still don't work properly like underlining on mouseover.

To test this, you can install `nautilus`, `ubuntu-settings` and `gnome-shell-extension-desktop-icons` from disco-proposed. Take those packages only, and be sure to disable disco-proposed straight away after installing.

cc @Feichtmeier

**Comment by iainlane** [comment]
No! I'm saying that it is *broken* when I clone git and run nautilus with that yaru

**Comment by Feichtmeier** [comment]
Oh... Uhm, this is strange. 

I installed nautilus 3.30 + tracker in my 18.10 installation via https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging
Works very fine there. Are the packages different in disco proposed and gnome staging>cosmic  repos?

**Comment by iainlane** [comment]
Yeah, one difference is that this is 3.30.4 and not 3.30.0.

Ahh, it looks like it's https://gitlab.gnome.org/GNOME/nautilus/commit/07d4876563ea7e032d4467742df2133eb3058dda :(

**Comment by Feichtmeier** [comment]
Ah alrighty, I will fix that, thank you!
