### ISSUE TITLE
Missing Builder icon (?)

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1095]
[Builder](https://wiki.gnome.org/Apps/Builder) is IDE by GNOME

![2019-01-09 18-47-56](https://user-images.githubusercontent.com/40228953/50906921-94981200-143f-11e9-8ab8-04711e10a37a.png)

On the one hand, this is a GNOME core application. On the other hand, application named given name, it can be considered third-party app.

I want to create the icon like Xcode logo (Apple's IDE), but with pictogram from Software Center icon.

![](https://developer.apple.com/assets/elements/icons/xcode6/Xcode6-128x128_2x.png)

**Comment by clobrano** [comment]
Builder is not pre-installed, moreover the original Gnome icon is too different from the one you want to use as reference. I would give a -1 fort this

**Comment by Feichtmeier** [comment]
So on one issue you say extending our icon set to me gnome apps like gimp or inkscape would suddenly make Ubuntu become a bad distribution but then you open an icon request for gnome builder? What weird logic is that?

**Comment by ubuntujaggers** [comment]
Funnily enough, I thought Builder was one of the icons that worked really well in @clobrano's script screenshots:

![image](https://user-images.githubusercontent.com/38893390/50908537-cd28f300-1421-11e9-9ec4-d50109f405ac.png)

![image](https://user-images.githubusercontent.com/38893390/50908578-df0a9600-1421-11e9-855a-35dcd8acbee3.png)

**Comment by eaglersdeveloper** [comment]
@Feichtmeier,

> On the one hand, this is a GNOME core application. On the other hand, application named given name, it can be considered third-party app.

**Comment by Feichtmeier** [comment]
Yes the same can be applied to all gnome applications that are not pre installed

So what logic is that?

If you just agreed that it is no problem to make Yaru icons for popular gnome apps like gimp, inkscape or whatever it would make sense.

**Comment by madsrh** [comment]
IF it should have a new icon, I'm +1 for [the script one](https://user-images.githubusercontent.com/3986894/50934311-8e6a5b80-1468-11e9-920a-3a1b4223412c.png) @ubuntujaggers suggested. 

Changing it to something completely different like Xcode, would be very confusing for people coming from other distros (and icon themes) IMO

**Comment by Feichtmeier** [comment]
I think we could try a real Suru icons for most gnome apps (including builder) which respect the main idea of the app icon. Like @ubuntujaggers did with the shotwell icon
The script could then fill the gaps of none gnome apps (when I say gnome apps I only mean those currently being actively developed/maintained gtk3 apps)

**Comment by eaglersdeveloper** [comment]
I'm closing this issue, because Builder is a third-party app.

**Comment by Feichtmeier** [comment]
If you would come up with an idea that represents the new icon from
http://jimmac.musichall.cz/stuff/icon-revolution/
In a Suru style, like @ubuntujaggers did for shotwell, I think that would be the way I personally prefer to the OSX inspiration
