### ISSUE TITLE
imagine-missing.svg

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1102]
![image](https://user-images.githubusercontent.com/15329494/50982527-ae982a00-14fd-11e9-9f56-06e85732c0cc.png)

There is no Suru/Yaru icon for this one. Would be nice to have it :)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/50983611-1c455580-1500-11e9-8d8c-a9b619327fbc.png)

First idea. :man_shrugging:

**Comment by eaglersdeveloper** [comment]
Count on me!

**Comment by madsrh** [comment]
I looks good @Feichtmeier 👍 
![image](https://user-images.githubusercontent.com/3986894/51004987-4bc68300-153d-11e9-90c2-a680e9fbb892.png)

What is that "frame" in the current icon? Is it a screen?
![image](https://user-images.githubusercontent.com/3986894/51005044-8cbe9780-153d-11e9-8aa8-2a7b1002c408.png)
