### ISSUE TITLE
EOG with no dark theme plugin

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#1104]
Hi,

When running this config of eog, the next-previous and rotate arrows become unreadable (light gray square) when hovered. There is no such issue with Adwaita or Materia, e.g.

Ubuntu Disco dev + Yaru 19.04

**Comment by madsrh** [comment]
> ...with no dark theme plugin

What _dark theme_ plugin are you referring to? 

I can't reproduce this issue.

**Comment by fthx** [comment]
"**no** dark theme" plugin ;-) 
This (official) one : 
```
eog-plugin-disable-dark-theme/disco,now 3.26.3-2 amd64  [installé]
  Disable Dark Theme plugin for GNOME Image Viewer
```
With eog default (dark theme) when the right arrow is hovered : 
![image](https://user-images.githubusercontent.com/23138504/51021081-cebcfd00-1580-11e9-9591-d75030828ce1.png)

With eog dark theme disabled (through official plugin) when the right arrow is hovered : 
![image](https://user-images.githubusercontent.com/23138504/51021178-13e12f00-1581-11e9-89aa-3a3df68cd24d.png)

**Adwaita** with eog dark theme disabled (through plugin) when the right arrow is hovered : 
![image](https://user-images.githubusercontent.com/23138504/51021326-7f2b0100-1581-11e9-820f-d6a8c54df8c8.png)

**Comment by Feichtmeier** [comment]
Hmhm, I guess that's because we use a relative color for OSD buttons, right @clobrano ?

**Comment by clobrano** [comment]
It's possible, but this means that those buttons do not work at all in light variant

**Comment by Feichtmeier** [comment]
I think osd buttons should look the same in both light and dark in adwaita. That's where those osd variables come from. They also use osd styling for app notifications both looking the same in light and dark (transparent black). I'm not saying we should do it too, just for the context. :)

**Comment by clobrano** [comment]
> I think osd buttons should look the same in both light and dark in adwaita

I agree. If the error comes from variables that changes in light/dark mode we have two scenarios:

1. the variant is correctly set to light by this plugin, then we have the problem in light variant only
2. the plugin does not change the variant correctly and some colors are mixed/broken

**Comment by clobrano** [comment]
The problem is that we use button_bg color, that changes with light/dark variant instead that osd_ colors. Working on the fix
