### ISSUE TITLE
19.04 release doesn't have yaru-dark theme folder

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#1106]
yaru version 19.04 on Ubuntu 19.04 Alpha doesn't have the Yaru-dark directory in `/usr/share/themes/`

I think this release is supposed to officially offer the dark theme.

**Comment by clobrano** [comment]
Hi @jbicha,

both the snap and the compiled-from-source versions have the Yaru-dark folder, I wonder if there's something we should add for the deb one?

**Comment by clobrano** [comment]
Okay, I wonder why my search for "yaru-dark" inside the folder project did not get me there :smile: 
Thanks a lot, the fix should be easy then

**Comment by clobrano** [comment]
Let's see if it works

![image](https://user-images.githubusercontent.com/2883614/51084374-b4be1e80-1728-11e9-93bc-a5c70485b430.png)
