### ISSUE TITLE
Changing volume with scroll wheel result is distorted sound

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1111]
When you're using the shortcut keys on the keyboard to change volume, it creates a distorted sound.

[🔈](https://www.dropbox.com/s/og7schra771luak/t_voice5202110345065267720.ogg) [This]() is the issue!

This was reported by @Feichtmeier - for some reason, he is using the **bell.ogg** sound and not the **audio-volume-change.ogg** sound 🤷‍♂️ but it doesn't matter because the issue is still there.

[This ](https://www.dropbox.com/s/y26y9kd176tfl8i/audio-volume-change_mads_ogg.ogg)is what it sounds like on my box: [🔈](https://www.dropbox.com/s/y26y9kd176tfl8i/audio-volume-change_mads_ogg.ogg)
As you can hear, the issue is barely noticeable here. Can anyone else reproduce Feichtmeiers issue? @clobrano 

And [here ](https://www.dropbox.com/s/g1ps3tdfe9gs0t4/audio-volume-change-freedesktop.ogg)is what the Freedesktop audio-volume-change sounds like: [🔈](https://www.dropbox.com/s/g1ps3tdfe9gs0t4/audio-volume-change-freedesktop.ogg) 

Okay! So, my theory is that the glitches occurs because our sound is too long. This means that when the sound is looped (or rapidly repeated) the whole sound isn't played entirely. If the cut isn't done at a [zero crossing](https://en.wikipedia.org/wiki/Zero_crossing) (where the waveform is at 0) it creates clicks (glitches).

Comparing the files between Yaru and Freedesktop:
![auido](https://user-images.githubusercontent.com/3986894/51087390-f6fc5580-1752-11e9-9180-279e81e6fd3f.jpg)

Possible solutions:
1. Ignore this issue because it's a rare use case.
2. Create a shorter sound (this has proven to be difficult)
3. Use the Freedesktop sound

**EDIT:** Wow this is issue #1111 😄 Now I'm really looking forward to #1234 🤣

**Comment by clobrano** [comment]
On my system the sound looks fine :/

**Comment by Feichtmeier** [comment]
@clobrano hover with your mouse above the volume indicator in the gnome panel
Then use your mouse wheel quiet fast
Doesn't your sound overdrive?

**Comment by madsrh** [comment]
@Feichtmeier ? 🤔

**Comment by Feichtmeier** [comment]
It's still present but I wonder if it's rather a gnome issue. I try once more soon, if I fail again lets close it
