### ISSUE TITLE
Infobar buttons have "invisible" text in backdrop

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1112]
I came across this in 19.04

![image](https://user-images.githubusercontent.com/3986894/51089531-11442c80-176f-11e9-9c48-61bb97077eb2.png)

I haven't installed any updates this week so this might already be fixed, but I just wanted to report it now so I don't forget 😄

**Comment by Feichtmeier** [comment]
No that's not fixed. Was prbly too rushed back then. I'll fix that
