### ISSUE TITLE
Missing window border in Thunderbird

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1117]
The window border is missing as you see below. 

Yaru:
![image](https://user-images.githubusercontent.com/3986894/51214526-7b4f0400-191e-11e9-8861-e6610ca39f34.png)

Adwaita:
![image](https://user-images.githubusercontent.com/3986894/51214520-75592300-191e-11e9-9218-b9cd92992553.png)

**Comment by Feichtmeier** [comment]
I can confirm that the reason for this is:

Adwaita has a transparent black window border for all kind of Windows, including dialogues (the same border I've added to the menus in the PR).
We could try to add it to the dialogues only
