### ISSUE TITLE
Missing icons in software updater

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1121]
(Please edit the title of the issue if it's wrongly names)

@eaglersdeveloper or @ubuntujaggers 😉 I just came across these! 

This icon looks like the _update-notifier_ icon:
![image](https://user-images.githubusercontent.com/3986894/51285618-d69cf700-19ef-11e9-8012-38ca47054d52.png)

Also missing:
![image](https://user-images.githubusercontent.com/3986894/51285643-f2a09880-19ef-11e9-8801-ad9792920717.png)

Edit from @Feichtmeier 
And the checkmarks
![grafik](https://user-images.githubusercontent.com/15329494/64693110-d4b00880-d496-11e9-871f-a69bb363e39e.png)

Battery
![no-suru-battery-icon](https://user-images.githubusercontent.com/45657128/53259616-cef7fe80-36cf-11e9-8f55-97a7139698c3.png)

**Comment by Feichtmeier** [comment]
The package icon should be providing in the latest theme with aptdaemon-download.svg  Hmmm Stange

**Comment by madsrh** [comment]
> The package icon should be providing in the latest theme with aptdaemon-download.svg Hmmm Strange

Okay, that has landed in the snap but perhaps not yet in 19.04?

**Comment by Feichtmeier** [comment]
Shouldn't be that way :/ strange it should be in 19.04 
19.04=master from two weeks ago

**Comment by madsrh** [comment]
Can I close this @Feichtmeier / @ubuntujaggers ?

**Comment by Feichtmeier** [comment]
The icons are still missing :) I think we could keep it opened and see when Stuart finds time

**Comment by Feichtmeier** [comment]
Would be neat if we could this into 20.04 as well @ubuntujaggers or @madsrh :angel:

**Comment by ubuntujaggers** [comment]
Maybe something like this:

![aptdaemon-delete](https://user-images.githubusercontent.com/38893390/75615095-a18e2e00-5b37-11ea-8ba6-f1b6d08474b4.png)
![aptdaemon-add](https://user-images.githubusercontent.com/38893390/75615096-a2bf5b00-5b37-11ea-835d-1897b89b4733.png)
![aptdaemon-download](https://user-images.githubusercontent.com/38893390/75615098-a2bf5b00-5b37-11ea-9646-971a30de81a4.png)
![aptdaemon-setup](https://user-images.githubusercontent.com/38893390/75615099-a357f180-5b37-11ea-820d-735f4f052658.png)

??

**Comment by Feichtmeier** [comment]
That's nice! Very nice

**Comment by madsrh** [comment]
👌 Spot on!
