### ISSUE TITLE
Dark theme: incorrect highlight in nautilus rename popup

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#1122]
There's an issue with the text highlighting in the Nautilus file-rename popup in the dark theme.

## Expected Behavior

The text should be highlighted orange like it is in the light theme:

![image](https://user-images.githubusercontent.com/1044087/51294111-7dc56280-19df-11e9-8a04-150870181abc.png)

## Actual Behavior

The text is highlighted in a colour very similar to the background colour and so is barely distinguishable from not being highlighted at all (it really is highlighted in this screenshot, if you squint you can see the text of the file extension is a slightly different shade as it is not selected):

![image](https://user-images.githubusercontent.com/1044087/51294141-a0f01200-19df-11e9-8fc9-38c8e1c5c532.png)

## Steps to Reproduce the Problem

  1. Use Yaru-dark
  2. Select a file in Nautilus and tap F2
  3. Notice the text in the popup does not look highlighted
  4. Type something or drag the mouse or tap ctrl-A to convince yourself it is in fact highlighted

## Specifications

I installed Yaru from the Arch Linux AUR. I switched to the "git" versions of the AUR package, which installs yaru directly from github. git-describe in the build directory for it gives: `r27-29-g305a4d0a` which looks like current master. I am using the yaru session this time, so it's not like #1018.

Software that presents the issue:
- Name: Nautilus/Gnome Files
- Version: 3.30.5-769665bd3

**Comment by madsrh** [comment]
Again, a very thorough but report @chrisjbillington - thank you!
