### ISSUE TITLE
New Toolbar Icons for Evolution.

### ISSUE THREAD

**Issue by snydox** [ubuntu/yaru#1125]
I noticed that the toolbar icons on Evolution Mail are the same as Ambiance. Other theme projects like Adapta, and Suru++ (See image below) have updated their icons to look flat and modern. I was wondering if those icons could be updated in Yaru(Suru) as well.

![suru](https://user-images.githubusercontent.com/13590875/51354354-5c1cb780-1a81-11e9-95ad-ed56065b1caf.png)
![suruplus](https://user-images.githubusercontent.com/13590875/51354358-5e7f1180-1a81-11e9-8c54-f01254492954.png)

**Comment by Feichtmeier** [comment]
Hi, yes that's indeed missing
We had several issues about that and even a target in our project. But it was me who had forgot about this. So great that you opened this issue so we can keep track!

**Comment by madsrh** [comment]
@Feichtmeier 
Is it possible to change the color of the icon in the sidebar here to something like Inkstone?
![image](https://user-images.githubusercontent.com/3986894/52596573-e83bb800-2e50-11e9-9a3f-b529c73fa70c.png)

Could we simply grab the suru++ icons? Asking them nicely ofcourse 👼 

Another comparison:
![untitled-1](https://user-images.githubusercontent.com/3986894/52596642-1b7e4700-2e51-11e9-942b-ee8a4d46add9.gif)

**Comment by Feichtmeier** [comment]
I would not target this since suru-plus is basically overwriting the small icons with symbolic icons. But the gtk theme is requesting full color icons. That should be requested in evolution instead since we already have those symbolic icons :) Geary for example uses them

**Comment by Feichtmeier** [comment]
Planing on summing the issue up here for all legacy icons that are missing: https://github.com/ubuntu/yaru/issues/1468
Thus closing this one
