### ISSUE TITLE
Bring the blue highlighting colour back, please

### ISSUE THREAD

**Issue by dasnorsep** [ubuntu/yaru#1128]
Hullo! 

Recently the text highlighting and the Firefox tab highlighting colour has changed from blue to orange. I find the new colour to be very distracting :( There's plenty of orange in the Ubuntu/Yaru theme already... Would you kindly bring the blue colour to where it was before the last update? (Maybe consider forking the theme a bit moar: Team Red and Team ~Green~ Blue?)

This is how it used to be:
![xmas-is-over-man-realizes](https://user-images.githubusercontent.com/46845234/51428420-89e63580-1c14-11e9-80a4-a004b6e30144.png)
![good-old-tab-zoomed](https://user-images.githubusercontent.com/46845234/51428462-ef3a2680-1c14-11e9-991b-39a5305643d1.png)

And now it's the same colour as you can see in, say, Nautilus (I couldn't capture the actual highlighting colour because it turns to grey when I try to make a screenshot):
![screenshot from 2019-01-19 17-56-15](https://user-images.githubusercontent.com/46845234/51428423-92d70700-1c14-11e9-9e69-90d8c6728ba4.png)

Please, please, please, bring the blue colour back. It was easy on the eyes and dwelt only in few places of UI, and it looked very good.

**Comment by clobrano** [comment]
Hi @dasnorsep,

I am with you in this. I believe the blue selection was really good, unfortunately most of the applications default to selected background color for text selection, that is orange, and there is no standard way to enforce our text selection color, so we had to drop that.

**Comment by Feichtmeier** [comment]
The problem was that we can only set the colours of pre-defined gtk classes.
When apps have their own classes and then must use a custom CSS file to theme those classes appropriate to adwaita they use specific colour variables. 
Adding a second accent colour to those would mean to change adwaita since it's the default theme of gtk
We all loved the blue text selection but it's not possible

Or did you mean to change the Orange to blue?

**Comment by dasnorsep** [comment]
> (currently)

Are you aware of soon coming changes to the dev workflow that would make it easier for you to handle stuff like this?

---
> Or did you mean to change the Orange to blue?

No, I like orange as the main accent colour. And blue was great as a secondary accent colour.

By the way, somehow it's still present in drop-down menu in the top right corner:
![screenshot from 2019-01-19 21-12-13](https://user-images.githubusercontent.com/46845234/51430727-44376600-1c30-11e9-911b-65e01ce559b0.png)

**Comment by clobrano** [comment]
> Are you aware of soon coming changes to the dev workflow that would make it easier for you to handle stuff like this?

which changes?

**Comment by dasnorsep** [comment]
@clobrano I'm sorry it looked like I know of some coming changes. No, I was just asking, because of Feichtmeier's "currently": thought maybe he knew that something is on the horizon and soon I'll have my beloved blue highlighting back.

**Comment by clobrano** [comment]
Ah, sorry I misread :E 
No, no changes expected in a near future

**Comment by Feichtmeier** [comment]
Blue stays for "activities" like progress bars and sliders. The rest will stay orange until ... prbly forever :D 
Only the textcolor is orange again since adwaita does not support a difference there (and thus no gtk app supports this)
Thanks for the heads up though and best regards!

**Comment by dasnorsep** [comment]
Okay, last comment from me: consider changing the contrast of the colour or whatever. Default Ubuntu orange is easier on the eyes:
![screenshot from 2019-01-19 22-41-30](https://user-images.githubusercontent.com/46845234/51431589-1c4dff80-1c3c-11e9-8fab-492acf606e32.png)
![screenshot from 2019-01-19 22-46-15](https://user-images.githubusercontent.com/46845234/51431590-1ce69600-1c3c-11e9-8a21-82050f07d07e.png)
I think it's important to change the colour, because it's what users look at for much of their time interacting with the system. It's a major bummer that having that blue colour costs much human-hours to maintain.

Anyways, thanks for your answers and for the theme itself :3
