### ISSUE TITLE
Missing icon: Inkscape

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1129]
Arguably not the world's best timing  😝   but how about:

![image](https://user-images.githubusercontent.com/38893390/51432618-5e724380-1c32-11e9-8e54-628fb7ce0d6a.png)

![image](https://user-images.githubusercontent.com/38893390/51432616-48fd1980-1c32-11e9-8171-47e0ef531e12.png)

**Comment by ubuntujaggers** [comment]
Does the team object to me contacting Inkscape on our collective behalf?  They might like it, to be fair?

**Comment by ubuntujaggers** [comment]
I might even add something like, _"You can also see that the default launcher and wallpaper are dark, so I believe the black icon would be harder to see if it didn't have the light background."_

**Comment by ubuntujaggers** [comment]
Good news, @Feichtmeier, @madsrh, @clobrano: I heard back from a lawyer at the non-profit organisation which holds the rights to Inkscape's trademarks on behalf of Inkscape.  They confirmed that they are _"happy for Ubuntu to continue moving forward with this theme and using the Inkscape logo as you depicted it in the attached mockup,"_ which was:

![image](https://user-images.githubusercontent.com/38893390/51561762-f87afb80-1e7f-11e9-9ce5-fc4d33a9bf67.png)

🍾 🍾 🍾 🍾  😃

**Comment by madsrh** [comment]
Given the recent change in direction, should we close this issue? 🤔

**Comment by techmedixx** [comment]
It is a nicely done icon regardless. Very impressive.

**Comment by Feichtmeier** [comment]
Closing this since the recent direction of out icon theme :)
Current progress can be seen here: https://github.com/ubuntu/yaru/issues/1180
and here: https://github.com/ubuntu/yaru/pull/1209
