### ISSUE TITLE
Icons consistency question

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#1130]
Hi,

In the Ubuntu's French forum Disco thread, we are a few (not everybody of course !) to find that the choice of squared new icons does not look good, with full gratitude to the big work already done : 

1- There are some squared apps but not all, this is not visually consistent : 
![image](https://user-images.githubusercontent.com/23138504/51437124-ef303a00-1c99-11e9-99d8-476c6004e96d.png)
Ok, some work can be done again. But is it possible to do such a hard work for ALL apps ? The old Ubuntu icon theme does change some apps icons but the feeling is consistent.

2- I don't know if it has been discussed, but we are a few to find that the Firefox (e.g.) icon is too small in its squared container : 
![image](https://user-images.githubusercontent.com/23138504/51437166-a75de280-1c9a-11e9-9155-88452a092e19.png)

**Comment by dawidpotocki** [comment]
There was some discussion on https://github.com/ubuntu/yaru/issues/1083. I think that going with Suru is pretty bad idea, of course some scripts can be created or whatever, it is like going around issue that you created yourself and this "fix" will have another issues.

New Adwaita icons are looking pretty good now and they look pretty consistent with 3rd party apps and won't probably look out of place with Yaru theme.

**Comment by fthx** [comment]
Poll : 
https://doodle.com/poll/4rgpigz9kes36izb

**Comment by fthx** [comment]
Ok if a poll is not welcome, I remove it.

**Comment by madsrh** [comment]
> 2- I don't know if it has been discussed, but we are a few to find that the Firefox (e.g.) icon is too small in its squared container :

The icon in the screenshot isn't the latest version. [The new version](https://github.com/ubuntu/yaru/pull/1115) is slightly larger.

> 1- There are some squared apps but not all, this is not visually consistent :

Not only is this being discussed - it is a hot potato atm.

**Comment by Feichtmeier** [comment]
Np!
We are currently discussing the whole topic and will certainly come up with the best decision for the Ubuntu users in some days/weeks! Thus I'm closing this here but thanks for reporting issues!
