### ISSUE TITLE
White text on white background in Evolution

### ISSUE THREAD

**Issue by isantop** [ubuntu/yaru#1143]
Thank you for contributing to **Yaru**, the next Ubuntu default Theme made by the community.

If you found a bug please consider to fill below information, this will help us to understand the problem and we don't bother you with other questions :)

If you're filing an issue for a missing icon, look for **Icon Request** section below.

Thanks a lot!

------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior

Read Email in Evolution, links and email addresses can be seen against the white background.

## Actual Behavior

Text which is a link or an email address in the header area appears white, rendering it invisible.

## Steps to Reproduce the Problem

  1. Install/Open Evolution
  1. Open an email
  1. Email addresses in headers can not be read.

## Specifications

Yaru installed via apt. Output of `apt policy yaru-theme-gtk`:

```
yaru-theme-gtk:
  Installed: 18.10.6
  Candidate: 18.10.6
  Version table:
 *** 18.10.6 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
```

Software that presents the issue:
- Name: Evolution
- Version: 3.30.1-1build1

![screenshot from 2019-01-29 17-22-26](https://user-images.githubusercontent.com/5883565/51949621-7bed9d00-23ea-11e9-863a-76297057e1f9.png)

Thanks!

**Comment by clobrano** [comment]
It doesn't seem to be reproducible when installing from sources both from master and tagged version 18.10.6

![image](https://user-images.githubusercontent.com/2883614/51983210-6afb6500-2498-11e9-87be-33e27fbe39f1.png)

**Comment by PaulVanSchayck** [comment]
@isantop I've hit the same issue. Have you managed to fix it?
