### ISSUE TITLE
view-more-horizontal-symbolic icon is missing

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1144]
There are those vertical dots used in rhythm box which yaru doesn't provide

![image](https://user-images.githubusercontent.com/15329494/52017839-dcfb9a80-24e8-11e9-9c22-c853cd5bbcda.png)

That's from an icon theme called "flat-remix" :)

Yaru falls back to adwaita, thus the bulky squared-dots:
![image](https://user-images.githubusercontent.com/15329494/52017889-fac8ff80-24e8-11e9-882d-834d6e35fb3a.png)

@ubuntujaggers would be a nice little addition :) They should fit under "actions"

**Comment by ubuntujaggers** [comment]
And I just forgot this one, lol.  Will do some work now.

**Comment by Feichtmeier** [comment]
Fixed with #1162 thanks for @ubuntujaggers
