### ISSUE TITLE
gnome shell switches look different than gtk switches

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1147]
![screenshot from 2019-02-01 08-08-50](https://user-images.githubusercontent.com/15329494/52107986-d4928500-25f8-11e9-94a5-7dd35acc481d.png)

That's a gtk switch in headerbars (without top highlight so it is closer to the shell switch)
![image](https://user-images.githubusercontent.com/15329494/52108167-584c7180-25f9-11e9-8ac1-f8b4112b683e.png)

@ubuntujaggers could you try to adapt the shell switches a little bit? :)

This
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/toggle-on.svg
and this
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/toggle-off.svg

**Comment by ubuntujaggers** [comment]
Argh, sorry, I've just seen I have some issues assigned to me.  Somehow missed that in Github.

**Comment by ubuntujaggers** [comment]
To check I understand the issue correctly - am I editing this:

![image](https://user-images.githubusercontent.com/38893390/52512364-5b002580-2bfc-11e9-95a6-b997f62557eb.png)

...to make it have the same shape/proportions as this:

![image](https://user-images.githubusercontent.com/38893390/52512374-65baba80-2bfc-11e9-8aaa-9b4bd649aad5.png)

?

**Comment by clobrano** [comment]
Yes, exactly :+1:

**Comment by Feichtmeier** [comment]
Invadid with new upstream refresh, thus closing for master branch/target 19.10
