### ISSUE TITLE
Missing image icon in small size looks bad

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1150]
![2019-02-03 15-24-38](https://user-images.githubusercontent.com/40228953/52176196-b24f6180-27c8-11e9-8e10-8c096d69c496.png)

**Comment by Feichtmeier** [comment]
Yes that's why I asked you to draw a symbolic icon for it on the PR where you answered like 1 time in 2 weeks

**Comment by eaglersdeveloper** [comment]
Sometimes I'm lazy.

**Comment by madsrh** [comment]
How about something like this:
![image](https://user-images.githubusercontent.com/3986894/52521138-cdabe800-2c72-11e9-9287-5464f9d1067f.png)

**Comment by clobrano** [comment]
Could you try inverting the empty spaces with the full ones?

**Comment by madsrh** [comment]
> Could you try inverting the empty spaces with the full ones?

Do you mean like this?

![image](https://user-images.githubusercontent.com/3986894/52523169-a95e0480-2c8e-11e9-94c8-9bb570418a88.png)

**Comment by Feichtmeier** [comment]
Maybe he meant a the symbolic icon only with filled white

**Comment by clobrano** [comment]
This isn't bad, but I meant all gray with the symbol black

**Comment by madsrh** [comment]
> all gray with the symbol black

![image](https://user-images.githubusercontent.com/3986894/52525274-6197a700-2ca7-11e9-95a7-e633babd3e73.png)

**Comment by clobrano** [comment]
Okay, I was wrong :)

**Comment by Feichtmeier** [comment]
I think just the circle with the line would be enough for the symbolic icon

**Comment by madsrh** [comment]
> I think just the circle with the line would be enough for the symbolic icon

Okay, so only this:
![image](https://user-images.githubusercontent.com/3986894/53350697-f218ed00-391f-11e9-909e-1b50b2033b58.png)

**Comment by Feichtmeier** [comment]
Yes in white like all the other icons in that big source-symbolic.svg

**Comment by madsrh** [comment]
Isn't this fix by https://github.com/ubuntu/yaru/pull/1245 ?

**Comment by clobrano** [comment]
Not yet. The correct icon is in the symbolic icon set, but it is not used (gnome 3.32 uses a grey version of the fullcolor icon)

**Comment by ubuntujaggers** [comment]
Not sure why the full colour icon looks bad at 16px in Eagler's screenshot because it's actually nice and clear in the files:

![image](https://user-images.githubusercontent.com/38893390/64637446-b8ab5900-d3fb-11e9-837d-84f1a65ef80f.png)

![image](https://user-images.githubusercontent.com/38893390/64637480-cb259280-d3fb-11e9-81e6-a5b0719d6c0a.png)

Looks like the screenshot has a scaled-down version of the 256px icon or something?!

**Comment by Feichtmeier** [comment]
Maybe because the symbolic icon is missing? If it's there then it's a bug with the shell I guess and we could close this issue

**Comment by Feichtmeier** [comment]
I noticed that this also happens with the adwaita icon theme

So the question remains if this is still our problem since we have a symbolic icon for this or if this is a gnome shell problem

**Comment by madsrh** [comment]
With a bit of self-awareness I've now come to the conclusion that the 256 days since I was self-assigned to this issue, is too slow. It doesn't even qualify as WIP 🤦‍♂ 

Can you work your magic here @ubuntujaggers ?

**Comment by Feichtmeier** [comment]
I am quiet sure this is nothing we can fix from our side

With the Adwaita icon theme selected this also happens here:
![grafik](https://user-images.githubusercontent.com/15329494/68526927-5e3a5600-02e1-11ea-99d7-919d8ce7c196.png)

I think this is something happening in the shell
