### ISSUE TITLE
Scrollbar size 

### ISSUE THREAD

**Issue by kaggapogyla** [ubuntu/yaru#1152]
gtk.css etc.

  scrollbar.horizontal slider {
    min-width: 40px; }
  scrollbar.vertical slider {
    min-height: 40px; }

should be:

  scrollbar.horizontal slider {
    min-height: 40px; }
  scrollbar.vertical slider {
    min-width: 40px; }

then the size can change. the size is by default very thin. 40 is too mutch  :-)
Ubuntu 18.10.

**Comment by clobrano** [comment]
Hi @kaggapogyla, thanks for taking time to contribute.
I am not sure about what your goal is. What is the dimension you consider "too much"? The length of the bar or the thickness?

**Comment by clobrano** [comment]
Closing this now, I tested the change proposed and it's not acceptable. Feel free to keep discussing here anyway if you think this is not right.
