### ISSUE TITLE
Missing 7z icon

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1155]
I created dark icon based on RAR icon, because 7zip logo is black.

![](https://www.7-zip.org/7ziplogo.png)

![application-z-7z-compressed](https://user-images.githubusercontent.com/40228953/52329932-748f4a80-2a0d-11e9-9c4f-b9bf14c70c4a.png)

Do you like this icon? If yes, I will create PR.

**Comment by madsrh** [comment]
I like it @eaglersdeveloper 😃 

Just to be sure, I'll tag @ubuntujaggers here so he can confirm that this fits with the "new direction" 👍

**Comment by ubuntujaggers** [comment]
I think this is proposed as a mimetype (is it?) but it would also make a great app icon in a non-uniform Suru icon set!

**Comment by eaglersdeveloper** [comment]
Yes! I meant the archive type, not the archiver.

**Comment by meetdilip** [comment]
I somehow got used to brown as archive colour. A habit since the days of Winzip :)

**Comment by eaglersdeveloper** [comment]
I made the icon more bright so that it looks good in dark theme.

![application-x-7z-compressed](https://user-images.githubusercontent.com/40228953/52342440-d3b18700-2a2e-11e9-9887-30a4c051aae7.png)

**Comment by meetdilip** [comment]
@eaglersdeveloper Which software do you use to display icons of all sizes in the order above ? Do you do it manually ?

**Comment by madsrh** [comment]
@meetdilip that is the icon template: https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/App%20Icon%20Template.svg

**Comment by meetdilip** [comment]
So we need to add icons to it manually ? I always thought it was something like `icon preview`.
