### ISSUE TITLE
Is there a way to update the Suru icon pack on Ubuntu 18.10?

### ISSUE THREAD

**Issue by snydox** [ubuntu/yaru#1157]
Long story short, I had Ubuntu 18.04, and I installed Yaru via snap. Last week, I suddenly got new icons for Firefox, and LibreOffice. Yesterday I performed a fresh installation of Ubuntu 18.10 and I haven't gotten the new icons yet. I don't use Flatpaks or Snaps for my apps, so the icon theme should work without problems.

Note: I don't remember if I added the Yaru ppa as well.

![screenshot from 2019-02-05 17-07-54](https://user-images.githubusercontent.com/13590875/52353878-6802f600-29fd-11e9-9299-54f34ed073d4.png)

**Comment by clobrano** [comment]
Unfortunately this is the drawback of snap/apt. On snap, each new commit is available in edge first and then in stable channel, while in 18.10 only some snapshots (no pun intended) are updated.

**Comment by madsrh** [comment]
It won't be long before you can have the latest and greatest by upgrading to 19.04 😁

I'm sorry that we can't provide a bit of solution. Are you ok with me closing this issue @snydox?

**Comment by Feichtmeier** [comment]
You can still use this to build it from src and log out and log in into "Yaru" session:

# Needed before install
sudo apt install libgtk-3-dev git meson sassc
# Download the repository from github
git clone https://github.com/ubuntu/yaru.git
cd yaru
# Initialize build system (only required once per repo)
meson build
cd build
# Build and install
sudo ninja install

**Comment by snydox** [comment]
> It won't be long before you can have the latest and greatest by upgrading to 19.04 grin
> 
> I'm sorry that we can't provide a better solution. Are you ok with me closing this issue @snydox?

Sure, you can go ahead and close it. It was more a question than an Issue. :)

Thank you for the fast replies guys.
