### ISSUE TITLE
[Missing, maybe wrong, icon] application/x-theme

### ISSUE THREAD

**Issue by vitalkanev** [ubuntu/yaru#1159]
MIME type (just in case): `application/x-theme` (`-` after `application` was from file name)
## Expected Behavior

Correct icon should be shown

![2019-02-07 14-02-46](https://user-images.githubusercontent.com/18398761/52407454-66126300-2ae1-11e9-845a-fe44852da98c.png)

## Actual Behavior

Package icon used

![2019-02-07 13-52-33](https://user-images.githubusercontent.com/18398761/52407474-762a4280-2ae1-11e9-9ffd-cd87bac80eac.png)

## Steps to Reproduce the Problem

  1. Click "Other places" on Nautilus left bar
  2. Choose "Computer"
  3. Go to `usr/share/icons/Yaru`
  4. Observe an icon for `index.theme` or `cursor.theme` file

## Specifications

```sh
$ git describe && echo && lsb_release -a
r27-70-g37df4fa4 # not sure about this

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

Software that presents the issue:
- Name: Nautilus
- Version: 3.26.4

**Comment by clobrano** [comment]
Hi @vitalkanev, thanks for taking time to contribute, awesome bug report :+1:

Basically, we don't have an icon for this mimetype. Could you rename the bug title (smth like "Missing mimetype `application-x-theme`)?

**Comment by madsrh** [comment]
Can we use this issue to brainstorm some ideas? These are not suggestion, but merely to help us decide on which metaphor we want. Any ideas @ubuntujaggers ?

Some oldschool ideas:

![image](https://user-images.githubusercontent.com/3986894/52431954-9241da00-2b09-11e9-908d-80c2725b8429.png)

![image](https://user-images.githubusercontent.com/3986894/52431970-9a017e80-2b09-11e9-96cf-ee380f7f55e9.png)

Similar idea but a more modern icon:
![image](https://user-images.githubusercontent.com/3986894/52432193-24e27900-2b0a-11e9-9c13-8ed4baf83686.png)

This one is from [here ](https://www.xda-developers.com/hide-x-substratum-theme-hides-the-disabled-data-and-roaming-icon-in-the-status-bar/)and is similar to [Samsung ](https://youtu.be/Cdtw5eSBk6s?t=7) has. I like this one although it's the same metaphor as [Sam's Paper icon set](https://snwh.org/paper) user for [preferences](https://raw.githubusercontent.com/snwh/paper-icon-theme/master/Paper/512x512/apps/preferences-desktop-theme.png).
![image](https://user-images.githubusercontent.com/3986894/52432278-58250800-2b0a-11e9-83de-e848963186cc.png)

Some use [the suit](https://www.iconspng.com/images/matticonsapplicationxtheme/matticonsapplicationxtheme.jpg) and this one is a funny take on that:
![image](https://user-images.githubusercontent.com/3986894/52432688-69badf80-2b0b-11e9-885c-61362e3ebfff.png)

More paint:
![image](https://user-images.githubusercontent.com/3986894/52432838-d46c1b00-2b0b-11e9-8f9a-607e110805ec.png)

**Comment by ubuntujaggers** [comment]
I really like the rainbow paint roller  :)

**Comment by eaglersdeveloper** [comment]
But index.theme file when opening doesn't allow to install a theme. It is just information about a theme.

**Comment by madsrh** [comment]
![image](https://user-images.githubusercontent.com/3986894/52463681-28144e00-2b78-11e9-9fdd-2ecf4517530d.png)
@eaglersdeveloper true. Maybe doing what Humanity does above is better 🤷‍♂️ Elementary just symlinks a plain text file.

**Comment by madsrh** [comment]
What about using this one the suru++ guys created?

![image](https://user-images.githubusercontent.com/3986894/52525869-92c8a500-2cb0-11e9-9cc2-bc5c4fa2c920.png)

**Comment by ubuntujaggers** [comment]
It's a lovely roller - do we think the rainbow would be a bit excessive in a Suru context?

**Comment by madsrh** [comment]
> It's a lovely roller - do we think the rainbow would be a bit excessive in a Suru context?

I don't know. We could give it a try (with the suru color palette ofc)

**Comment by clobrano** [comment]
Being a mime type for a text file, I much appreciate the suru++ approach. Should we ask them about this, or we can draw our own?

**Comment by Feichtmeier** [comment]
@gusbemacbe do you have time to make a pull request for this item?

**Comment by gusbemacbe** [comment]
@Feichtmeier 

Yes, I do. I am still a contributor of Suru++ Ubuntu and author of Suru++ 30. I accept contributing and following the rules of Ubuntu. 

Just an observation. That icon of two colours (white and blue) with tie, taken from the internet, belongs to @fabianalexisinostroza's Antü.

**Comment by gusbemacbe** [comment]
Can I draw it the afternoon today? I am going to bed.

**Comment by vitalkanev** [comment]
Why not  воскресенье, 12 мая 2019г., 12:29 +03:00 от Gustavo Reis  notifications@github.com :

**Comment by gusbemacbe** [comment]
Привет Виталий (@vitalkanev), because during the whole night I have been solving the VSCode extension, but I was done. I was about going to bed, but I received@Feichtmeier, then I answered and I accepted. :-)

**Comment by Feichtmeier** [comment]
Ha ofc! Take your time and thanks for contributing

**Comment by gusbemacbe** [comment]
I am ready. I will be preparing.

**Comment by gusbemacbe** [comment]
Ready. I have just made a PR.

**Comment by Feichtmeier** [comment]
Thank you!
