### ISSUE TITLE
Missing gz icon (archive)

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1163]
Like other archive icons, I painted in logo's color:
![gzip-icon](https://user-images.githubusercontent.com/40228953/52518331-98979980-2c62-11e9-84dd-863e173e65c1.png)
Do you like this icon?

**Comment by madsrh** [comment]
Three things:
1. Nice work @eaglersdeveloper :tada: - I like it, but...
2. There's so many archive colors now that perhaps we should add a label here too (like below). Let's hear what the other guys think.
3. You really should, if possible, finish [unresolved ](https://github.com/ubuntu/yaru/issues/1150)issues before starting a new 😉

![image](https://user-images.githubusercontent.com/3986894/52520896-588ae380-2c6f-11e9-841b-69048ac4ef3c.png)

**Comment by madsrh** [comment]
@eaglersdeveloper can you create a PR for the gz icon?

This is what it would look like - I think it's nice: @Feichtmeier @clobrano ?

![image](https://user-images.githubusercontent.com/3986894/52524873-2a72c700-2ca2-11e9-9d80-edd19c518de9.png)

**Comment by madsrh** [comment]
@eaglersdeveloper can you create a PR for the gz icon?

**Comment by madsrh** [comment]
@eaglersdeveloper I'm closing this issue for now, but we still very much want your icon. Just create a PR with the final icon(s)
