### ISSUE TITLE
Alert Sound UI in Ubuntu 19.04

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#1175]
gnome-control-center 3.31.90 (currently in disco-proposed) has a new Sound panel which promotes 4 different options for Alert Sound themes. Yaru isn't one of the choices but maybe it ought to be.

I filed https://launchpad.net/bugs/1815504 for the gnome-control-center Ubuntu side of this issue.

3.30
-----
![gnome-control-center-sound-330](https://user-images.githubusercontent.com/876259/52586218-f237c980-2e04-11e9-869f-94737bac22ed.png)

3.31.90
----------
![gnome-control-center-sound-331](https://user-images.githubusercontent.com/876259/52586234-fc59c800-2e04-11e9-9a84-c0d0924f3d4f.png)

**Comment by Feichtmeier** [comment]
Thanks for reporting!
Also that separator needs a fix

**Comment by madsrh** [comment]
@Feichtmeier ...and 'System Volume' is missing a border

**Comment by jbicha** [comment]
The implementation is interesting. If you select one of the choices (none are selected by default), it creates a __custom sound theme in `~/.local/share/sounds/` . The custom theme derives from your current sound theme (so Yaru) and it just overrides the alert sounds. So there isn't any coordination needed there.

GNOME is looking for help in updating their event sounds so Yaru contributors might like to help out:
https://gitlab.gnome.org/GNOME/gnome-control-center/issues/264

Feel free to close this issue since my original concern doesn't apply once I looked into what the Sound panel was doing. And maybe we don't need an issue here to track the GNOME request for help.

**Comment by jbicha** [comment]
I added the frame (border) in 1:3.31.90-1ubuntu3 but I didn't see an obvious reason why there isn't a border or separator between the system volume slider list row and the Over-Amplification list row.

**Comment by Feichtmeier** [comment]
@jbicha the separator is a theming issue :) fix incoming in that pr

**Comment by galgalesh** [comment]
Ubuntu 19.04 was released today with this setup.

![image](https://user-images.githubusercontent.com/1492981/56381729-fb368400-6215-11e9-9b07-c721737dbd2a.png)

On a default install, none of the alert sounds is selected and the alert sound you hear is the yaru one. From the moment you choose an alert sound in this menu, you're stuck to the options in the menu.

**Comment by mezeipetister** [comment]
> Ubuntu 19.04 was released today with this setup. It looks super good and works like a charm. Nice work @jbicha !
> 
> Yaru isn't one of the options yet. On a default install, none of the alert sounds are selected and the alert sound you hear is the Yaru one. From the moment you choose an alert sound in this menu, you're stuck to the options in the menu, no easy way to go back to Yaru.
> 
> ![image](https://user-images.githubusercontent.com/1492981/56381729-fb368400-6215-11e9-9b07-c721737dbd2a.png)

Same for me. How can I set Yaru back? Its annoying a bit.

**Comment by Feichtmeier** [comment]
You can set it back with
```bash
gsettings set org.gnome.desktop.sound theme-name Yaru
```

**Comment by mezeipetister** [comment]
> You can set it back with
> 
> ```shell
> gsettings set org.gnome.desktop.sound theme-name Yaru
> ```

Thank you! It worked for me!

**Comment by madsrh** [comment]
Can we close this?
