### ISSUE TITLE
window-new-symbolic.svg is missing

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1177]
![image](https://user-images.githubusercontent.com/15329494/52644721-a3ab2d80-2edf-11e9-8a32-c72d3bfb3d62.png)

There is a new button in nautilus 3.319 for creating a new window inside the menu popover.

I luckily guessed that the icon is called
window-new-symbolic.svg and made a test symlink from folder-new-symbolic.svg just to check

![image](https://user-images.githubusercontent.com/15329494/52644818-d9e8ad00-2edf-11e9-8892-d0b74885e41b.png)

So that's quiet important now since a missing/fallback icon looks pretty broken
@ubuntujaggers @eaglersdeveloper @madsrh anyone of you please make an icon for that

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/52663821-c6e9d300-2f07-11e9-93df-db8e6983d12d.png)
(left symbol)

Is that enough/ok/fitting for window-new ? @madsrh @clobrano ?

**Comment by madsrh** [comment]
Yes, I would say it is 👍

**Comment by madsrh** [comment]
What is that icon called? I think the + looks a bit stretched

**Comment by madsrh** [comment]
What about this one?

![image](https://user-images.githubusercontent.com/3986894/52665010-c3a41680-2f0a-11e9-8b18-680cc852580a.png)

**Comment by clobrano** [comment]
+1 for this one

**Comment by Feichtmeier** [comment]
That's better! Sry I was watching spider man @.@ You make a PR?

**Comment by Feichtmeier** [comment]
Fixed by @madsrh with #1178
