### ISSUE TITLE
Update Yaru with non-uniform icons and remove third-party app icons

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1180]
This issue is for organization only and communication between contributors! 
Any **off-topic** comments will be **REMOVED**

_____________________________________________________________________________________
_App Name | icon name | list | of | symlink-names | ..._

Remove Yaru icons for these preinstalled third-party apps:

- [x] Firefox | firefox
- [x] Thunderbird | thunderbird
- [x] Libreoffice Writer
- [x] Libreoffice Base
- [x] Libreoffice Calc
- [x] Libreoffice Draw
- [x] Libreoffice Impress

Remove system icons that have other issues
- [x] welcome-app

Remove Yaru icons for these non-preinstalled third-party apps:
- [x] Polari | polari | org.gnome.Polari

Update these Yaru icons with non-uniform baseplates for gnome "coreapps" which are pre-installed in the default Ubuntu installation:

- [x] AisleRiot Solitare
- [x] Alerts <-- doesn't show up in app grid but appears on launcher and currently has a Suru squircle
- [x] Amazon
- [x] Calculator
- [x] Calendar
- [x] Cheese
- [x] Document Viewer
- [x] e-Book Reader <-- has an upstream Suru icon
- [x] Files
- [x] Input Method <-- I think this one's already non-uniform, it's the keyboard?
- [x] Language Support
- [x] Mahjongg
- [x] Mines
- [x] Power Statistics
- [x] Remmina
- [x] Rhythmbox
- [x] Settings
- [x] Shotwell
- [x] Simple Scan
- [x] Software & Updates
- [x] Software Updater
- [x] Startup Applications
- [x] Startup Disk Creator
- [x] Sudoku
- [x] System Monitor
- [x] Text Editor
- [x] To Do
- [x] Transmission <-- do we want our own icon for this, I think it was one of the controversial ones?
- [x] Ubuntu Software Center
- [x] Videos
- [x] Archive Manager
- [x] Backups
- [x] Characters
- [x] Disk Usage Analyzer
- [x] Disks
- [x] Fonts
- [x] Help
- [x] Image Viewer
- [x] Logs
- [x] Passwords and Keys
- [x] Screenshot
- [x] Terminal
- [x] Live-Patch
- [x] Apport
- [x] photps-app  + symlinks
- [x] messaging-app + symlinks
- [x] ubiquity
- [x] notes-app + symlinks
- [x] clocks

**Comment by ubuntujaggers** [comment]
I've ticked some of the boxes.  Do we want a "stretch goal" section to include Gnome apps that don't happen to be shipped with Ubuntu by default?  E.g., Ubuntu only includes two three games, but there's about a dozen in that family.  Also I've done some that aren't in Ubuntu by default just because there was a Suru icon for it already (e.g. I had to install address-book-app to test it).

**Comment by madsrh** [comment]
IMVHO we want the "stretched goal". The issue, as we all know, is snaps. Are [core Gnome apps](https://gitlab.gnome.org/GNOME/Initiatives/issues/2) likely to get snapped? We will _always_ have, and cannot avoid, a mix of icons - but where do we draw the line?
I guess it would be an odd experience to have beautiful icons for all installed Gnome apps, but if the user installs Dconf, [Tweaks ](https://gitlab.gnome.org/GNOME/gnome-tweaks/blob/afc14a009dd84c16b8f11e8539411d924fa53559/logo.png), [2048 ](https://gitlab.gnome.org/GNOME/gnome-2048/raw/bc0e7a5ebcc8fe28707bbcbcb59711de7b9af745/data/icons/hicolor/256x256/gnome-2048.png)or [Chess](https://gitlab.gnome.org/GNOME/gnome-chess/raw/f0f900bc10baf544ad44c9879f60206587e4502d/data/icons/hicolor/512x512/apps/org.gnome.Chess.png) those apps would use the upstream icons.

When I realized that because of the snap/flatpack icon issue we could never have a 100% suru desktop even if we spend everyday crafting 3rd party icons, I was slowly coming to terms with us shipping upstream icons and having NO maintenance at all. BUT see this work by @ubuntujaggers and at the same time, some of the upstream icons landing in 19.04, I'm now convinced that this is the right direction and that the Ubuntu desktop would have been a sad place without this.

**Comment by ubuntujaggers** [comment]
> the Ubuntu desktop would have been a sad place without this.

Thanks you @madsrh  :)

**Comment by Feichtmeier** [comment]
Some snaps have a hard path in their desktop file some don't.

**Comment by Feichtmeier** [comment]
As long as we keep track of what gnome calls core apps and we not we could be golden an independent from preinstalled or not can someone link that gnome list in here?

**Comment by madsrh** [comment]
+1 @Feichtmeier see my comment above ;)

**Comment by eaglersdeveloper** [comment]
Podcasts is official GNOME app. Why you want to remove it?

**Comment by Feichtmeier** [comment]
It's a core app? I guess then we can keep it

**Comment by eaglersdeveloper** [comment]
Yes, since 3.30

**Comment by ubuntujaggers** [comment]
Icons to have a more radical redesign:

- Software centre
- E-book reader (another docs-looking app with no clue about how it's different to other docs-looking apps - can we make an icon of a physical e-book reader)

Any others?

**Comment by madsrh** [comment]
> Icons to have a more radical redesign: Software centre

+1 As far as I know upstream is still using the bag metaphor, which Humanity also had,. Also discussed in https://github.com/ubuntu/yaru/issues/1051

**Comment by fitojb** [comment]
Sad to read you’re planning to remove LibreOffice icons (which I, as a member of [@LibreOfficeDesign](https://t.me/LibreOfficeDesign) liked very much) — I was about to report that Yaru was missing icons for LibreOffice Math…

**Comment by ubuntujaggers** [comment]
Thanks for the vote of confidence @fitojb  :)  Great to hear that you liked the design

Maybe we could keep the LibreOffice icons on the new square backplate (looks hopefully at @Feichtmeier, @madsrh and @clobrano)?  Heck, I'd even throw in a Maths  ;)

**Comment by Feichtmeier** [comment]
It's more of a political drama dodge than anything else since we all liked your LO icons. If we theme LO we may think of theming Mozilla and so on. We already made that journey once and i would prefer to not make it again :D

**Comment by clobrano** [comment]
The political drama came from our enthusiasm in making the icons by our own, without interacting with the maintainers first. Considering this, I think that we can still keep the door open for new icons if a proposal or blessing come from them in the first place.

**Comment by Feichtmeier** [comment]
True. How about: we this route until this or its successor branch is done and we made it through the checklist, then see what we do with LO? 
But if we don't have the desire to squircle every icon anymore with this 5-baseshape-approach, why should we modify the LO icons in the first place?

**Comment by clobrano** [comment]
If LO likes the new approach we or them can make the new icon

**Comment by fitojb** [comment]
Are you going to keep at least the symbolic icons for the top bar?

**Comment by ubuntujaggers** [comment]
> Are you going to keep at least the symbolic icons for the top bar?

One weird thing: it doesn't seem to like it if your theme includes a symbolic without a full colour.  If there's any icon in the theme for an app, even if it's only the symbolic one, it tries to use it instead of the default one.  So when I deleted Thunderbird but tried to keep the symbolic, it was using the symbolic in the app grid.

One workaround would be to make a copy of the upstream icon and include it in Yaru, but with our symbolic icon.

Alternatively, I don't know whether upstream LO already has 16px symbolic icons of its own?

**Comment by madsrh** [comment]
Oh boy, this is the neverending discussion. It almost makes selecting a text color seem easy 😆 

> It's more of a political drama dodge than anything else since we all liked your LO icons. If we theme LO we may think of theming Mozilla and so on. We already made that journey once and i would prefer to not make it again :D

Although @Feichtmeier is the voice of reason and logic here, I have to admit that this solution really doesn't feel right.

> But if we don't have the desire to squircle every icon anymore with this 5-baseshape-approach...

We **still** have that desire 😃 Especially with @ubuntujaggers burning thought the list above in no time :tada:

> ...why should we modify the LO icons in the first place?

- Because it's a preinstalled application
- Because we want a beautiful desktop
- Because LibreOfficeDesign wants us to

> How about: we _follow_ this route until this or its successor branch is done and we made it through the checklist, then see what we do with LO?

+1

If you ask me (_you didn't, but I'll post my comment anyway_) we will **always** end up with mixed icons, so why not ship as many beautiful icons - that upstream app maintainers have approved/requested - as possible? And with this new approach, it's not all or nothing at all; we can ship Suru LO and e.g. Thunderbird, but leave Firefox untouched. With the "old" squircle approach this would have looked out of place.

**Comment by clobrano** [comment]
> One weird thing: it doesn't seem to like it if your theme includes a symbolic without a full colour. If there's any icon in the theme for an app, even if it's only the symbolic one, it tries to use it instead of the default one. So when I deleted Thunderbird but tried to keep the symbolic, it was using the symbolic in the app grid.

weird indeed, we need to investigate more on this

**Comment by eaglersdeveloper** [comment]
> If you ask me ( you didn't, but I'll post my comment anyway ) we will always end up with mixed icons, so why not ship as many beautiful icons - that upstream app maintainers have approved/requested - as possible?

Then what's the point of reducing Suru shape?

**Comment by clobrano** [comment]
> Then what's the point of reducing Suru shape?

To reduce/avoid shape conflicts

**Comment by Feichtmeier** [comment]
@antenore would you green-light a Yaru-styled icon for the default Ubuntu installation? Currently there is no modified version of your upstream icon but since Remmina is pre-installed in Ubuntu, it would be nice if we could draw an icon for Ubuntu.

**Comment by antenore** [comment]
No issues on my side but let's see what @giox069 think about it as well.

**Comment by Feichtmeier** [comment]
Thanks for the reply - if it is green-lightes let's see when @ubuntujaggers finds time for it, but if you like the outcome we could alternatively contribute it upstream instead/additionally

**Comment by antenore** [comment]
@Feichtmeier That means that you will create a yaru folder with your icons (plus the CMakke files update)?

**Comment by Feichtmeier** [comment]
I didn't really understand you :(

We ship an icon set additionally to the gtk, shell and sound theme in the Yaru package which is pre installed in Ubuntu now.
In that icon theme we now mostly include gnome core app icons. But if you and @giox069 would agree we could also include a yaru-styled remmina icon alongside the other icons. But alternatively we could make a merge request at your git lab repo and don't include the new icon in Yaru (or do both in a transition phase)

**Comment by antenore** [comment]
@Feichtmeier sorry :-P later I'll expand/explain it better.

**Comment by antenore** [comment]
@Feichtmeier The Remmina desktop icons are under https://gitlab.com/Remmina/Remmina/blob/master/data/desktop/scalable/apps , do you want to replace those icons or do you want to add new ones, in a dedicated folders tree?
Our icons are installed as it should, under the hicolor folders, what I understand is that you want to create new icons to be placed under /usr/share/icons/yaru.
So maybe we have to reorganize a bit our folder tree, like .../data/desktop/hicolor/scalable/apps, and than we will have to adapt the build scripts.

Well, I hope it's a bit more clear, in any case we have nothing against storing the icons, let's find the solution that better suite everybody. The above mentioned Remmina icon is quite loved by our community ;-)

cc: @giox069

**Comment by Feichtmeier** [comment]
@antenore 
> do you want to replace those icons or do you want to add new ones, in a dedicated folders tree?

Well, there is still no icon drawn so I can't ask you if you like it :D but if you would, I would tend to replace your upstream icon.

But! if your community loves the current icon, which is understandable since it is not a bad or dated icon (it just does not fit to the current paper-approach we are using in yar) let's wait for @giox069 green-light, and if that is happening, we will add it to yaru/ubuntu. 
So your upstream icon stays untouched and our icon will probably be the same but with one of the round baseplates you can see here https://github.com/ubuntu/yaru/pull/1209 but 95% your logo/pictogram ( at least that's my idea of it, but sadly I miss the drawing skills and am dependent on @ubuntujaggers  :) )

**Comment by madsrh** [comment]
There's a difference between a good logo and a good icon. The Remmina logo is fantastic. As an icon it doesn't fit with the Suru icons and it "drowns" in the app grid. Maybe ubuntujaggers has a great idea, but if not, I would suggest keeping the logo as it is but simply adding a background.
To illustrate what I mean (but **not** a suggestion):
![remedia](https://user-images.githubusercontent.com/3986894/53413634-c0119480-39cc-11e9-88f9-ab9f6baccd05.gif)

**Comment by antenore** [comment]
Yes, I see.
As I said we are open to discussion, and by the way, THANKS SO MUCH FOR WHAT YOU ARE DOING!! :-) (shouting with pleasure and kindness) 

cc: @madsrh @Feichtmeier

**Comment by Feichtmeier** [comment]
@antenore thanks for your kind words! :)

@ubuntujaggers updated the list with some icons to add/change and 1 to remove (welcome-app, since it is already a circle in vanilla ubuntu, and there were some problems to let the welcome app suck up the yaru icon, let's just remove it from yaru)

**Comment by Feichtmeier** [comment]
@ubuntujaggers the symbolic icon A needs an update :dancer: 
Posting this here instead of creating a new issue
![image](https://user-images.githubusercontent.com/15329494/53490943-04e80a80-3a63-11e9-846e-f000f36b0771.png)

**Comment by ubuntujaggers** [comment]
Guys, is everyone 100% happy with the general appearance of the icons on the app grid? I wonder if they're definitely as sharp as the squircle versions?

**Comment by Feichtmeier** [comment]
I am very happy with it!
Only some symbolic app icon sync is needed then "we" are done :) Thank you @ubuntujaggers !

Also, had finally a chance to see the new error/alert icon ;) in action!
![image](https://user-images.githubusercontent.com/15329494/53904410-47eb4480-4046-11e9-848e-88117257c2dd.png)

**Comment by Feichtmeier** [comment]
We missed 1 symlink
![Screenshot from 2019-03-13 17-13-28](https://user-images.githubusercontent.com/15329494/54295457-593ad080-45b3-11e9-830a-5b5ae8a45b90.png)

@ubuntujaggers 
Just to keep track, I post it in this issue here. Let's see if this is worth a SRU

**Comment by Feichtmeier** [comment]
@ubuntujaggers about live patch: in this case launchpad and canonical are upstream so we could decide to change the icon there instead of in yaru

**Comment by Feichtmeier** [comment]
Last icon left on the list (I really can hardly believe you burned through the whole list @ubuntujaggers /bow ) is transmission - transmission devs didnt respond to github tagging, other ideas to contact them?

**Comment by Feichtmeier** [comment]
@mikedld would it be okay for you if Ubuntu would include a version of your logo that fits into our new icon style?

**Comment by mikedld** [comment]
@Feichtmeier, is it the icon in #1209 that you're asking us about (per your https://github.com/ubuntu/yaru/issues/1180#issuecomment-466942768)? If it's the one, I can hardly see the difference so I don't mind; otherwise please clarify.

**Comment by Feichtmeier** [comment]
@mikedld ah thanks for replying!

There is currently no icon drawn because we made ourselves the "rule" to ask third party apps first if they are generally okay with us making an icon.

@ubuntujaggers do you have any icon ideas for a Yaru transmission icon?

**Comment by tsymbalenkovlad** [comment]
What about gnome-font-viewer?
![image](https://user-images.githubusercontent.com/7062595/61185391-939ba380-a661-11e9-812e-9479eb81b44c.png)

**Comment by Feichtmeier** [comment]
It's there, it's just the snap that doesn't suck the right icon. But canonical is working on this

**Comment by tsymbalenkovlad** [comment]
But i have no snaps installed ( :
`No snaps are installed yet. Try 'snap install hello-world'.`

**Comment by Feichtmeier** [comment]
Oh! Maybe it's a missing symlink

I'll check, thanks for reporting

**Comment by ubuntujaggers** [comment]
> @Feichtmeier, is it the icon in #1209 that you're asking us about (per your [#1180 (comment)](https://github.com/ubuntu/yaru/issues/1180#issuecomment-466942768))? If it's the one, I can hardly see the difference so I don't mind; otherwise please clarify.

Hi @mikedld (and @Feichtmeier, @madsrh, @clobrano),

Sorry this took forever.  Here's a concept for a Transmission icon to use in the Yaru theme, using the same style as the other pre-installed apps:

![image](https://user-images.githubusercontent.com/38893390/61897908-12b99300-af10-11e9-94ba-5afb59a585da.png)

![image](https://user-images.githubusercontent.com/38893390/61897934-1f3deb80-af10-11e9-9b0b-cab3868bc81b.png)

![image](https://user-images.githubusercontent.com/38893390/61897943-24029f80-af10-11e9-9c6e-d7499e333f19.png)

I'm also going to try a square version of the icon this week for comparison.  But, in general, would upstream be happy for us to use an icon like this in the Yaru theme?  If so, I have maybe half an hour more work to do on the smallest sizes.  If not, I'll save myself half an hour  :)

**Comment by Feichtmeier** [comment]
Yay we can finally close it :clinking_glasses: 
Thank you Stuart!!!
