### ISSUE TITLE
Fix checkboxes in gnome-music selection-mode

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1185]
![peek 2019-02-17 23-21](https://user-images.githubusercontent.com/15329494/52920281-22063600-330b-11e9-82db-981ca720a67d.gif)

**Comment by clobrano** [comment]
What's the issue?

**Comment by Feichtmeier** [comment]
The boxes have not the green background :)

**Comment by Feichtmeier** [comment]
I think this could eventually be a bug in gnome-music

This is also a treeview and the checkboxes work as expected:
![image](https://user-images.githubusercontent.com/15329494/54110494-d9a9d780-43e1-11e9-98aa-3f4420b72738.png)

**Comment by Feichtmeier** [comment]
Aha, here is the upstream issue for this: https://gitlab.gnome.org/GNOME/gtk/issues/28

And here is the fix: https://gitlab.gnome.org/GNOME/gtk/merge_requests/625/diffs?commit_id=1f0656d03016c6e508532b03a988604651e49450

**Comment by Feichtmeier** [comment]
Invadid with new upstream refresh, thus closing for master branch/target 19.10
