### ISSUE TITLE
Synaptic not properly themed

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#1193]
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: today at 17:58 IST
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-02-17 (1666) 19MB -
installed:   0.1            (1666) 19MB -
$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
![screenshot from 2019-02-17 17-52-45](https://user-images.githubusercontent.com/37431503/52915765-98da0980-32e0-11e9-819f-7b8c1fc8196d.png)

**Comment by Feichtmeier** [comment]
I fear that's rather a snapcraft topic

**Comment by Paz-it** [comment]
OK. Just to be accurate, the Synaptic is a .deb app. Do you suggest  me to report it on snapcraft.io site?

**Comment by Feichtmeier** [comment]
oO you said that's a snap installation you even posted the snap I'd
How can it be a Deb and a snap at the same time?

**Comment by clobrano** [comment]
The snap is yaru I believe. Which is the synaptic version?

**Comment by Paz-it** [comment]
Yes! Yaru snap o.c, and Synaptic version is 0.84.3ubuntu1(bionic)

**Comment by Paz-it** [comment]
@clobrano , Now, something is really funny and strange. I selected communitheme(not dark) in tweaks, logged out/in and ....surprise surprise :fearful: 
![screenshot from 2019-02-18 05-28-43](https://user-images.githubusercontent.com/37431503/52926595-1b91b180-333f-11e9-8eb1-5790835786bb.png)
Can someone reproduce it?

**Comment by clobrano** [comment]
I confirm the problem and on VM I cannot even "fix it" as you did. I believe it's a special case since synaptic starts with superuser, better report this on snapcraft first though

**Comment by clobrano** [comment]
Sorry, I forgot this.
@jhenstridge, do you think that the fact that `synaptic` falls back to adwaita, when Yaru is installed as snap, might be due to synaptic running as root?

**Comment by Feichtmeier** [comment]
I think didier said at some point that running apps as root is no longer "supported" or recommended. Same happens if you run any other app for example gedit with sudo. I think he even said that it is not fixable. If yes we should close this

**Comment by clobrano** [comment]
He was probably talking about wayland. Alright, closing this
