### ISSUE TITLE
gnome-terminal changes size when changing tabs

### ISSUE THREAD

**Issue by jhenstridge** [ubuntu/yaru#1196]
This report is based on https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1816436

## Expected Behavior

Running Ubuntu 19.04's gnome-terminal, I expect the window to remain the same size when switching tabs.

## Actual Behavior

The window reduces in size by one line each time I switch tabs.

## Steps to Reproduce the Problem

  1. On an up to date Ubuntu 19.04 system, ensure the Yaru theme is selected
  2. Run `gsettings set org.gnome.desktop.interface text-scaling-factor 1.5` to increase text size.
  3. Open a gnome-terminal window and add a second tab.
  4. Switch tabs in the window repeatedly (mouse or keyboard shortcuts make no difference).

## Specifications

Relevant versions are:

yaru-theme-gtk 19.04
gnome-terminal 3.31.90-1ubuntu1
libgtk-3-0 3.24.5-1ubuntu1

**Comment by jhenstridge** [comment]
One difference I note between Adwaita and Yaru: on Yaru, the cross in the notebook close button appears to move up one pixel when a notebook tab becomes active.  On Adwaita, I don't see any movement.

One other difference is that Yaru changes the font weight for active vs inactive tabs while Adwaita doesn't.  Maybe that is the cause of the size change?

**Comment by clobrano** [comment]
The main issue was the orange border, but I'll double check the font size.

@Feichtmeier, do not merge the PR yet, please

**Comment by jhenstridge** [comment]
I am probably just being paranoid about the bold/normal font weight issue: while it is theoretically possible for the two fonts to have different line height, it would be a pretty bad idea for related fonts.

If you've got one bold word in a paragraph of text, it'd look really ugly for the one line containing that word to have a different height to the surrounding lines.  In contrast, differing width is fine and doesn't affect sizing in this case due to long tab labels being truncated.

**Comment by clobrano** [comment]
Correct, I confirm that the font weight does not affect resize when changing tabs, but I agree that the effect is not too pleasant

**Comment by clobrano** [comment]
Changing font weight on tab selection does not seem to cause resize issues
