### ISSUE TITLE
seahorse has changed its icon name

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#1198]
The Passwords & Keys app _seahorse_ has changed its app icon filename from `seahorse.png` to `org.gnome.seahorse.Application.svg`

The new version of seahorse will probably be synced to Ubuntu 19.04 Alpha from Debian experimental later today.

https://gitlab.gnome.org/GNOME/seahorse/commit/12eadc206a

**Comment by Feichtmeier** [comment]
Thank you very much for this kind of pinging! Very helpful!
