### ISSUE TITLE
adwaita-icon-theme 3.31.91

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#1200]
I was asked to ping y'all when there are Ubuntu uploads that have a high change of affecting theming.

I just uploaded [adwaita-icon-theme 3.31.91](https://launchpad.net/ubuntu/+source/adwaita-icon-theme/3.31.91-1ubuntu1).

There were [a lot of changes](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commits/master) this development cycle as part of the Adwaita theme refresh.

**Comment by clobrano** [comment]
Thanks @jbicha!

**Comment by Feichtmeier** [comment]
Thanks !
Thanks to your previous pings, I think we fixed all the name changes and should be safe, since gnome UI freeze was some days ago, right?

**Comment by jbicha** [comment]
adwaita-icon-theme shouldn't change for the 3.32/Disco series.

I had to ping the maintainer to get an adwaita-icon-theme release this week! :smile:

**Comment by clobrano** [comment]
closing this since #1234 is merged
