### ISSUE TITLE
Calendar arrows are unstyled

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1203]
## Expected Behavior
![image](https://user-images.githubusercontent.com/2883614/53244899-7400e000-36ac-11e9-9a7e-93072ed9f299.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/2883614/53244881-68151e00-36ac-11e9-9c87-9272733f7db9.png)

## Steps to Reproduce the Problem
Update to gnome shell to 3.31.90
 
## Specifications
Yaru from master
Gnome-shell: 3.31.90

**Comment by Feichtmeier** [comment]
I think that needs an icon theme symlink, but I don't know how the adwaita icon is called...
the icon in yaru is called go-next-symbolic.svg but we need the symlink target name

**Comment by clobrano** [comment]
I looked into shell commit, there's also a chage in the javascript part, which programmatically sets `pan-start-symbolic` and `pan-end-symbolic`, then the CSS only styles the icon size. I will try to add the new CSS code from upstream and see if that could work in any ubuntu version.

**Comment by Feichtmeier** [comment]
Yeah... Same thing was made with the dash close button. I fear when that addActor() method is used in JS we can't just change the scss for old shell versions

**Comment by clobrano** [comment]
I fear the same

**Comment by Feichtmeier** [comment]
Size is fixed with https://github.com/ubuntu/yaru/pull/1234
But the symbol is not, yet we agreed on accepting the new icon, right?

**Comment by clobrano** [comment]
The icon is set in JS code now, so there isn't much we can do to use our icons

**Comment by clobrano** [comment]
fixed by #1234
