### ISSUE TITLE
No Suru icon for the small battery in update-manager when laptop is on battery

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1206]
## Steps to Reproduce the Problem
1. Run a laptop on battery
2. Run update-manager with available updates
3. Look at the small battery icon beside the notice to connect the computer to mains power before updating
That battery icon is not Suru.

![no-suru-battery-icon](https://user-images.githubusercontent.com/45657128/53259616-cef7fe80-36cf-11e9-8f55-97a7139698c3.png)

## Specifications
~$ snap info communitheme
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: today at 18:09 CET
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-02-20 (1684) 19MB -
installed:   0.1            (1593) 19MB -

Software that presents the issue:
- Name: update-manager
- Version: Any

**Comment by Feichtmeier** [comment]
There was a similar issue before.
This is relevant for 18.04 snap installations
For 19.4 the app uses the symbolic icon for some reason :D

**Comment by madsrh** [comment]
> ...For 19.4 the app uses the symbolic icon for some reason :D

I believe, if the icon doesn't exist, it inherits it from Humanity. 
But if the Humanity icon theme isn't shipped with 19.04 it has to fallback to the symbolic icon.

> There was a similar issue before.

Yes, Humanity is VERY "complete" and not having that around to pull / inherit from, is really bad and will result in new issues.

@ubuntujaggers how would a Suru/Yaru styled battery look? 🔋

**Comment by Feichtmeier** [comment]
Added this to https://github.com/ubuntu/yaru/issues/1121
So we can close it
