### ISSUE TITLE
The app list of Pamac is missing with Yaru GTK theme.

### ISSUE THREAD

**Issue by laichiaheng** [ubuntu/yaru#1208]
## Expected Behavior

Works well with Pamac

## Actual Behavior

The app list is missing

## Steps to Reproduce the Problem

  1. search apps in Pamac
  2. double click the application to view the description
  3. go back to the app list
  4. click on the app list
![2019-02-24 14-49-59](https://user-images.githubusercontent.com/9532105/53296093-7a759000-3843-11e9-9049-72ae42e60584.png)

## Specifications

Software that presents the issue:
- Name: yaru-gtk-theme (AUR)
- Version: 19.04-2

**Comment by madsrh** [comment]
Thanks for taking the time to report this issue @laichiaheng

Can you tell me if the app list is also missing with the Adwaita theme?

**Comment by laichiaheng** [comment]
@madsrh No.

**Comment by laichiaheng** [comment]
@madsrh It only happens to the AUR app list.

**Comment by clobrano** [comment]
It looks more a system problem, yaru only shows the results

**Comment by laichiaheng** [comment]
@clobrano But other GTK themes don't have this problem.

**Comment by clobrano** [comment]
I understand, but Yaru on AUR is kind of experimental. I really can't understand how a theme (installed properly) can discard a list of items to display. I can only think of weird behavior when every element of this list is white on white, or transparent.

**Comment by Feichtmeier** [comment]
@laichiaheng could you please post a screenshot of your app using adwaita?

We officially only support Ubuntu but if it's easy to fix for other distros we can maybe do something. But I don't have time to set up an arch VM to debug this, I didnt even know this app exists

**Comment by laichiaheng** [comment]
![2019-05-03 16-22-25 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57126477-aa9b5b00-6dbf-11e9-9700-62474dee5a6b.png)
It still happens if I build it myself, there is no libgtk-3-dev in arch though.

**Comment by Feichtmeier** [comment]
@laichiaheng thanks!

Could you check with the gtk inspector which widget hierarchy had been used there? Or just post a screenshot of your gtk inspector?

You can enable it with 
https://github.com/ubuntu/yaru/blob/master/CONTRIBUTING.md#quick-testing-in-the-gtk-inspector

**Comment by laichiaheng** [comment]
@Feichtmeier What should I do after I open the widget factory and the inspector?

**Comment by laichiaheng** [comment]
@Feichtmeier Or this?
![2019-05-03 17-04-19 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57128294-86db1380-6dc5-11e9-9dde-d259925612d9.png)

**Comment by Feichtmeier** [comment]
Ah nice - you need to

1) open that pamac app
2) open the inspector with that hotkey
3) click that crosshair/bullseye symbol in the top left and then select the bugged element of the pamac app
4) select the combobox in the top left corner (under the corsshair/bullseye symbol) and select "CSS Nodes" (in chinese ;D )
5) make a good screenshot of the hierarchy like for example here:

![image](https://user-images.githubusercontent.com/15329494/57128433-b2dda100-6d93-11e9-9792-d2e2036988f3.png)

**Comment by laichiaheng** [comment]
![2019-05-03 17-13-22 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57128690-cb1ae380-6dc6-11e9-9379-da7b1ea158e8.png)

**Comment by Feichtmeier** [comment]
Thanks we're almost there

could you please drag that right side of the gtk inspector to become smaller? so we can see the style classes of the selected widget in the left part of the window?

**Comment by laichiaheng** [comment]
![2019-05-03 17-17-43 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57128884-6613bd80-6dc7-11e9-8781-5e38751fab06.png)

**Comment by Feichtmeier** [comment]
Could you please test this with the new master branch?
Best regards

**Comment by laichiaheng** [comment]
@Feichtmeier It seems to work now.

**Comment by Feichtmeier** [comment]
Thank you for reporting back! Closing it then
