### ISSUE TITLE
Emblem lcons feedback and small issue 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#1218]
I'm following quietly lately, when I have free time. Not much of it as before, sorry! :disappointed:
Nit picking a bit if I may : when looking at the emblems the only one that stand out is the symbolic-link arrow that is not fitting so well in the circle. maybe a bit smaller arrow will be better.
seeing it together with all the new icons in 100% size may emphasize it :
![screenshot from 2019-02-26 17-29-36](https://user-images.githubusercontent.com/37431503/53425762-4b4f5200-39ee-11e9-9adb-0ce8bc94ea31.png)
Otherwise, great work here @madsrh :+1:

_Originally posted by @Paz-it in https://github.com/ubuntu/yaru/pull/1191#issuecomment-467492449_

**Comment by madsrh** [comment]
Sorry @Paz-it, I saw your comment, but forgot to reply 😞 
Anyway, this is only a tiny bit smaller, but does this look better?

![image](https://user-images.githubusercontent.com/3986894/53602817-24d91480-3bb0-11e9-8157-4c5b939d7602.png)

The current line of the arrow is exactly the same length as the line is the X (unreadable).
@Feichtmeier @clobrano the arrow is perfectly centered, so the uncentered issue is an optical illusion (or it's just because it's unbalanced).

**Comment by Paz-it** [comment]
Hi @madsrh , it is indeed look better  although, as you said it's hard to compare the new in relations with the other emblem-icons and to see it live is the best :sweat_smile: 
Thanks!

**Comment by clobrano** [comment]
can we close this?

**Comment by Paz-it** [comment]
> can we close this?

It's up to you guys! @madsrh ...?

**Comment by madsrh** [comment]
> It's up to you guys! @madsrh ...?

Just be avoid misunderstandings, @eaglersdeveloper actually did most of these icons, but maybe you're just asking for my opinion @Paz-it 😉 

@eaglersdeveloper?

**Comment by Paz-it** [comment]
Oh my :man_facepalming:  Sorry for miss-crediting @eaglersdeveloper . 
I stand corrected, thanks @madsrh

**Comment by clobrano** [comment]
@madsrh, can you push a PR with the new emblem for symbolic link?

**Comment by madsrh** [comment]
Do you mean[ this one](https://github.com/ubuntu/yaru/issues/1218#issuecomment-468464813)? It's not perfect, so I was kind of hoping that @ubuntujaggers or @eaglersdeveloper would fix this.

**Comment by ubuntujaggers** [comment]
How about...

Before:

![image](https://user-images.githubusercontent.com/38893390/56697709-515c6900-66e7-11e9-9241-85ad99815a26.png)

After:

![image](https://user-images.githubusercontent.com/38893390/56697733-66d19300-66e7-11e9-95ca-4ccb050ca32f.png)

Full colour svg:

![image](https://user-images.githubusercontent.com/38893390/56697750-76e97280-66e7-11e9-90dc-d57ed8b3bb89.png)

I understand the logic in cloning the diagonal line from the "X".  The "X" goes very near the edge of the circle which means the arrow head is very close to the edge.  On another emblem, the diagonal lines of the tick ("check mark") don't follow the "X" exactly, so I think we can depart from it here if the result is a more balanced arrow?
