### ISSUE TITLE
Symbolic icons need (another) refresh?

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1221]
Apps - we need to desquircle some of them.  Also, now I'm living with them, I can see some room for improvement to some of them.

Mimetypes - do we want to make these more closely resemble the icons?  E.g., the document symbol is very square and has the dog-eared bottom right corner.  This would be a bigger task because it requires folders to be redone as well, once (if) the symbols are changed.

App icons **might** be a goer before the UI freeze, mimetypes might be too ambitious?  Or is the whole issue too ambitious for 19.04?

**Comment by clobrano** [comment]
About mimetypes, I think it's better to keep the difference from the app

**Comment by Feichtmeier** [comment]
I think some symbolic icons could use and improvement with after the recent big work you've done. But let's do that next cycle, or do it in the next 13 days^^

**Comment by ubuntujaggers** [comment]
@clobrano @Feichtmeier @madsrh 

I've been working on the app icons and making them more like the new icons, so we'll see if we like these better when they're finished.

Also, I think I've learned some lessons now I'm seeing the app symbols every day.  Solid symbols with cutout glyphs (e.g. current terminal) don't look great IMO when the icons are inverted because it's a block of white.  So, if you try to represent a dark icon with a solid symbol you end up with it being white  :)

Also, adding details in 50% opacity looks good in source-symbolic but (again) not when the colours are inverted on a black background.  I feel like I was over-relying on that when it might have been better to just include less detail.

Here's what I've got so far - very much a work in progress and always up for discussion:

![image](https://user-images.githubusercontent.com/38893390/53923823-8813ec80-4071-11e9-9f48-3f528a18f9e0.png)

**Comment by Feichtmeier** [comment]
Thank you!
You can remove the welcome app btw, I removed the full colour one as well

**Comment by ubuntujaggers** [comment]
Okay, I think these are looking better/simpler/clearer:

![image](https://user-images.githubusercontent.com/38893390/53984811-0031ef00-4112-11e9-86c1-29eb8b3185e7.png)

![image](https://user-images.githubusercontent.com/38893390/53984824-0758fd00-4112-11e9-8720-d1ebabd26464.png)

![image](https://user-images.githubusercontent.com/38893390/53984845-117afb80-4112-11e9-9b64-7ce09ea4d099.png)

![image](https://user-images.githubusercontent.com/38893390/53984858-18a20980-4112-11e9-80ef-4b23efd3a1b3.png)

![image](https://user-images.githubusercontent.com/38893390/53984870-20fa4480-4112-11e9-9c72-8b59840d4951.png)

![image](https://user-images.githubusercontent.com/38893390/53984891-2d7e9d00-4112-11e9-8e64-1d3b6fd6ebe1.png)

![image](https://user-images.githubusercontent.com/38893390/53984904-35d6d800-4112-11e9-8f86-0a365b438f7e.png)

![image](https://user-images.githubusercontent.com/38893390/53984914-3d967c80-4112-11e9-9484-75ad8e0b55df.png)

![image](https://user-images.githubusercontent.com/38893390/53984924-45eeb780-4112-11e9-9460-e7a55492b88a.png)

![image](https://user-images.githubusercontent.com/38893390/53984937-4c7d2f00-4112-11e9-8bcd-ae874090f8fe.png)

![image](https://user-images.githubusercontent.com/38893390/53984944-530ba680-4112-11e9-9dd8-a959e03a3768.png)

![image](https://user-images.githubusercontent.com/38893390/53984956-5acb4b00-4112-11e9-824c-6cfddf7c7ff4.png)

![image](https://user-images.githubusercontent.com/38893390/53984964-60289580-4112-11e9-8d28-f69134139f24.png)

**Comment by Feichtmeier** [comment]
Awesome!

**Comment by madsrh** [comment]
Nice! Please make a PR for this @ubuntujaggers 

The only one I'm not thrilled about is Photos

**Comment by ubuntujaggers** [comment]
@madsrh @Feichtmeier @clobrano Pushed, have a go...

**Comment by Feichtmeier** [comment]
THanks @ubuntujaggers !!!
