### ISSUE TITLE
Icon request gparted

### ISSUE THREAD

**Issue by pgera** [ubuntu/yaru#1226]
Testing the disco dingo nightly image, gparted's icon in the launcher looks out of place.

![screenshot from 2019-03-02 21-22-45](https://user-images.githubusercontent.com/5542855/53690108-3f3afb80-3d32-11e9-99de-869360535ea9.png)

Edit: I don't know if gparted is considered first-party/pre-installed, but it is shipped in the live image.

**Comment by dylanmtaylor** [comment]
I agree that this looks out of place. From the same screenshot, Characters looks pretty bad as well.

**Comment by clobrano** [comment]
Icon set is about to change, so that image is not a good reference anymore

**Comment by clobrano** [comment]
Closing this since the icon set has changed. If you feel the icon is out of place again, feel free to reopen (even if in that case you should really contact the maintainers and ask for a new icon :D)

**Comment by pgera** [comment]
To be clear, do you mean this is the intended icon for gparted ? Even with a more recent nightly image, gparted's icon is the same although other icons have changed.

**Comment by Feichtmeier** [comment]
We could ask the gparted Devs if they are okay with us making a yaru icon for it. Any github handle we could tagg?
