### ISSUE TITLE
Refuse 48px, 32px and 24px fullcolor icons

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1227]
We discussed about this several times.
But we didn’t take any action, because some applications still use small fullcolor icons.

I propose to remove only 48, 32 and 24px and leave 256 and 16px fullcolor icons.

**Comment by Feichtmeier** [comment]
I don't think we should use another issue for this, I kept the other one opened: https://github.com/ubuntu/yaru/issues/1040

**Comment by clobrano** [comment]
Btw 48px is the most troublesome size, as we discussed

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, @clobrano, @madsrh
