### ISSUE TITLE
CD/DVD drive icon is inconsistent 

### ISSUE THREAD

**Issue by dylanmtaylor** [ubuntu/yaru#1231]
On 19.04 daily build, the CD/DVD drive icon does not match the style of the Hard Disk icon at all. 
![selection_118](https://user-images.githubusercontent.com/277927/53700892-262f5a80-3dc5-11e9-960e-86bc7be16b2d.png)

**Comment by madsrh** [comment]
Thanks for taking the time to report this issue @dylanmtaylor 👍 

We want to fix the inconsistency for all device icons, so I'll closed this issue and created a new one for all device icons. I hope that is okay with you 😃
