### ISSUE TITLE
Yaru icons are not being used for Characters, Disks and Terminal in 19.04

### ISSUE THREAD

**Issue by dylanmtaylor** [ubuntu/yaru#1232]
I noticed that these icons are present in the Yaru theme but the default icons appear to be used instead on the Ubuntu 19.04 live images.

![image](https://user-images.githubusercontent.com/277927/53700952-16644600-3dc6-11e9-9c43-2a9d06114e9a.png)

**Comment by madsrh** [comment]
Hi @dylanmtaylor 
As mentioned [here ](https://github.com/ubuntu/yaru/issues/1226#issuecomment-469057575)by @clobrano there's an update to the icons coming soon 😃 

BTW **Characters** is "unfixable" (because it's a snap)
