### ISSUE TITLE
Redo/refresh device icons

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1233]
The Suru device icons are confusing and the set is incomplete (CD-Rom icon is missing resulting in fallback to symbolic icons - https://github.com/ubuntu/yaru/issues/1231). 
I want to propose a makeover/refresh. I don't really have a plan, but a starting point could be to use the style of @ubuntujaggers hard drive as seen below. I'm not suggesting pushing this now! We want a complete set and a coherent look for all devices. It's a huge task, so perhaps this should be a target for 19.10?

![image](https://user-images.githubusercontent.com/3986894/53701221-0581f780-3dfb-11e9-9048-9cc7576bd598.png)

This may result in a new icons for Disks and Disk Usage Analyser too.

**Comment by Feichtmeier** [comment]
One icon is for gnome-disks, which is an app, and the other icon is for a device, in this case a HDD.

I agree that they are incomplete! We could make a list

**Comment by Feichtmeier** [comment]
Closing this after ack from @madsrh
