### ISSUE TITLE
Software icon has strange corners

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1238]
The front sheet of the bag seems cut.

![4a23a8ba-ed2a-47f6-932f-e90460968573 01](https://user-images.githubusercontent.com/40228953/53883710-2896ec00-4033-11e9-9c37-bfc1ba82dfd3.png)

**Comment by Feichtmeier** [comment]
I am pretty happy with this icon. You think to preserve the "shopping bag look" one would need to reduce the border-radius of the top edges to 0?

**Comment by Feichtmeier** [comment]
Woops sorry misclicked

**Comment by clobrano** [comment]
I like this one too

**Comment by eaglersdeveloper** [comment]
I also like it. Just different angles behind and in front.

I propose to round off on front bag sheet as behind.

**Comment by ubuntujaggers** [comment]
Yep, I don't think it looks bad at the sizes we use it, but we could probably improve the top of the bag - maybe in next cycle? (unless you're fast  :) ).

**Comment by eaglersdeveloper** [comment]
Let's solve it now.

**Comment by ubuntujaggers** [comment]
Have a go :) I'm not precious about it, if we can improve it before next week I'm all for it.

**Comment by clobrano** [comment]
I assume this will be for the next cycle :)

**Comment by ubuntujaggers** [comment]
Should we close this?  It's still a lunch box  :)  but it no longer has the open bag effect at the top.

**Comment by eaglersdeveloper** [comment]
Now it looks like suitcase and the handle looks like in Peppa Pig.
I don't know why editor of OMG! Ubuntu saw lunchbox in it. This is simple paper bag.

![Снимок экрана в 2019-06-01 10-48-42](https://user-images.githubusercontent.com/40228953/58744953-d8290200-845a-11e9-8c38-95fb25d734b7.png)

**Comment by Feichtmeier** [comment]
+.-
Peppa 🐖 cartoon?
I think it looks good and it closes this issue.
Can we focus on important things for now? Like missing icons?
We miss your PRs by the way eaglers
