### ISSUE TITLE
Embrace upstream GNOME's new icons in Yaru

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1240]
This issue is actually an opinion and a complaint at the same time :smile:

Am I the only one who does not like the current icon theme in Yaru? Especially the visual inconsistencies between Suru icons and third-parties? For example, install Geary and then search for mail in GNOME Shell and observe the visual inconsistencies.

I really like and prefer GNOME's new icons, both core-gnome (nautilus, gedit, totem, etc.) and world-gnome (deja-dup, geary, gnome-mpv, etc.), and I suggest adopting them in Yaru and redirect the focus into only filling the gaps (e.g. emblems) to accomplish a complete icon theme, like Humanity once was, is.

~$ snap info communitheme
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 12 days ago, at 18:09 CET
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-03-04 (1725) 17MB -
installed:   0.1            (1593) 19MB -

**Comment by Feichtmeier** [comment]
We already provide a solution for the inconstancy between squircles and third party apps by using more shapes than only one.
You could use them when refreshing your snap from edge or wait for 19.4

Thanks for the feedback

**Comment by clobrano** [comment]
Gnome icons will be available anyway, you can select them using gnome tweaks
