### ISSUE TITLE
User icon in system menu needs updates as per 3.31.92

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/yaru#1241]
This is what happens right now (bottom side, ignore the panel icons distortion :)).

![immagine](https://user-images.githubusercontent.com/345675/53899601-dbb71380-403a-11e9-93f2-32eba74dc962.png)

There have been [upstream changes](https://gitlab.gnome.org/GNOME/gnome-shell/commit/33e05f591256276d98ebff28c89861f00c537e0c) which need to be synced in yaru for 19.04.

**Comment by Feichtmeier** [comment]
Thank you for the poke!

**Comment by clobrano** [comment]
Today I enabled proposed repo on my Disco VM and updated to 3.31.92, how can I get 3.32.92?

**Comment by 3v1n0** [comment]
Sorry, was a typo... I meant 3.31.92 :)
