### ISSUE TITLE
App icon in top panel prefers symbolic over full-colour

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1242]
## Steps to Reproduce the Problem
1. Start Firefox and look at the icon in top panel
2. Firefox ships a symbolic icon
3. Start Thunderbird and look again
4. Thunderbird doesn't ship a symbolic icon, so it's full-colour

In Ubuntu 18.04, gnome-shell in ubuntu-session defaults to always prefer full-colour icons in the top panel to preserve the consistency.

## Specifications
:~$ snap info communitheme
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: today at 06:20 CET
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-03-06 (1737) 17MB -
installed:   0.1            (1737) 17MB -

**Comment by clobrano** [comment]
New Gnome shell is moving towards symbolic icons however. We could make a symbolic icon for Thunderbird, what do you think?

**Comment by Feichtmeier** [comment]
Yes we could but then we also need a full colour icon, otherwise the symbolic version is used everywhere.

We could copy paste the original upstream icon into full colour.

Orrrr one could all the Thunderbird Devs to provide a symbolic icon.
I think this would be the best solution for all Linux users

**Comment by Amr-Ibra** [comment]
Upstream gnome-shell has always preferred symbolic icons in the top panel, just use the vanilla gnome-session in Ubuntu 18.04.
I could list over 10 third-party apps, a dozen of java apps and Qt apps that don't ship symbolic icons. So I don't think creating symbolic icons for each one of them is feasible. And that's why gnome-shell in ubuntu-session defaults to full-colour icons.
For example, I have these affected apps: Thunderbird, Chromium, LibreOffice, VLC, VM-Manager, Lyx, mkvinfo, Meld, Gparted, Jabref, Octave, Scilab, Spyder, Converseen, Gaupol, Kid3, ... and the list goes on.

**Comment by Feichtmeier** [comment]
Yes true. Would be awesome if someone would create symbolic icons for those popular Linux apps upstream!

Ah, also: with gnome shell 3.32 it looks like they suck out colours of the icons automatically so they look black and white. Check disco daily with proposed channel!

Closing this here
