### ISSUE TITLE
Missing icon: evolution background processes

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1244]
## Steps to Reproduce the Problem
1. Start System Monitor
2. Go to Processes
3. Look at the small icon beside gnome-shell (generic-binary icon) and evolution* (mail icon)
4. They are not Yaru icons

Edit by @Feichtmeier 
![image](https://user-images.githubusercontent.com/15329494/54271319-92f2e380-4581-11e9-9fda-5905b46f16d8.png)

## Specifications
:~$ snap info communitheme
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: today at 06:20 CET
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-03-07 (1740) 17MB -
installed:   0.1            (1737) 17MB -

**Comment by Feichtmeier** [comment]
Hi thanks for contributing to Yaru!

I think we should not theme every background process availible. I think I already created an issue (#1210 ) by providing an icon for "update-notifier"

Thus I would prefer not providing an icon for all evolution background-processes or for any background-processes at all. @clobrano @madsrh @ubuntujaggers ?
