### ISSUE TITLE
preferences-system-power-symbolic.svg and preferences-desktop-online-accounts-symbolic.svg not being used

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1259]
I think this might be worth getting into 19.04 with that SRU stuff, agreed @clobrano @madsrh ?

18.04:
![image](https://user-images.githubusercontent.com/15329494/54238577-204e1d80-4519-11e9-8b65-ad7a756d2f4e.png)

19.04:
![Screenshot from 2019-03-13 10-56-12](https://user-images.githubusercontent.com/15329494/54269986-b1a3ab00-457e-11e9-981f-2efa842b4175.png)

**Comment by madsrh** [comment]
> I think this might be worth getting into 19.04 with that SRU stuff

+1

**Comment by clobrano** [comment]
fixed by #1262
