### ISSUE TITLE
Better Ubiquity icon

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1261]
Using emblems on icons on the same position as gtk puts real emblems is  not really working well:

![photo_2019-03-13_11-09-36](https://user-images.githubusercontent.com/15329494/54270835-95a10900-4580-11e9-8c9f-b784ecc85af7.jpg)

**Comment by matthewpaulthomas** [comment]
A simple solution would be to move the built-in arrow to the bottom left. But that would cover most of the actuator, making the disk even less recognisable than it is now.

Another solution would be to stop using an arrow altogether. Some ideas:
- a computer overlaid by a magic wand with sparkles
- an Ubuntu logo in the style of an architectural drawing that’s part-way through being coloured
- a release-specific logo, e.g. a dingo for 19.04 (but with some low-level visual consistency between releases)

**Comment by clobrano** [comment]
> an Ubuntu logo in the style of an architectural drawing that’s part-way through being coloured

+1 on this

**Comment by Feichtmeier** [comment]
I like that ubuntu logo idea

**Comment by ubuntujaggers** [comment]
Let me have a go. I hosed my Ubuntu install but I've got Inkscape on Windows :)

**Comment by ubuntujaggers** [comment]
First attempt is actually a bit crap, but at least I can show I'm doing some work tonight:

![image](https://user-images.githubusercontent.com/38893390/54848685-e380e400-4cd9-11e9-935a-12cec3dbb33c.png)

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/54856761-091ae700-4cf4-11e9-856c-f77fbacfcf29.png)

**Comment by matthewpaulthomas** [comment]
That’s the idea!

Probably it would need a lot less coloured area, though, and more visible guidelines, to avoid any possibility of being interpreted as just a rendering glitch. Something like this (very rough sketch):
![ubiquity-icon-sketch](https://user-images.githubusercontent.com/19801137/54907240-e566c500-4edc-11e9-8397-24cf62d0311f.png)

**Comment by ubuntujaggers** [comment]
Should we close this one and replace with a more general "better Ubiquity" issue?

**Comment by Feichtmeier** [comment]
Ok :)

**Comment by matthewpaulthomas** [comment]
This has been closed for a week, but there doesn’t seem to be any replacement “better Ubiquity” issue, nor any replacement “better USB Creator” issue.

**Comment by friendlyapple** [comment]
@matthewpaulthomas @ubuntujaggers Your icons are really cool :)

**Comment by ubuntujaggers** [comment]
Not as detailed as the mockup, but how about this:

![C: Users sblav Pictures ubiquity](https://user-images.githubusercontent.com/38893390/72683117-632f3900-3acc-11ea-8e96-5bf31747bd95.png)

@Feichtmeier @madsrh @clobrano @mpt?

**Comment by ubuntujaggers** [comment]
The small ones look a bit "messy"  :thinking:  maybe something simple like:

![simple ubiquity](https://user-images.githubusercontent.com/38893390/72683382-c1f5b200-3ace-11ea-9f37-f7eacfc4f9ef.png)

**Comment by Feichtmeier** [comment]
> Not as detailed as the mockup, but how about this:
> 
> ![image](https://user-images.githubusercontent.com/38893390/72683130-81953480-3acc-11ea-918f-1b76c74f17a2.png)
> 
> @Feichtmeier @madsrh @clobrano @matthewpaulthomas
> 
> EDIT: Or with white background:
> 
> ![ubiquity 2](https://user-images.githubusercontent.com/38893390/72683217-46473580-3acd-11ea-83b1-564294ab0402.png)

Nice! This is a nice one
I like the one with the white background

Any idea to get the Ubuntu glyph more paper like looking?

**Comment by ubuntujaggers** [comment]
Was trying this before I saw your reply - can't remember if we tried anything with CoF + disk:

![ubiquity disk 1](https://user-images.githubusercontent.com/38893390/72683744-d38c8900-3ad1-11ea-9882-277e65a4f64a.png)

![ubiquity disk 2](https://user-images.githubusercontent.com/38893390/72683743-d38c8900-3ad1-11ea-8f6d-30588bf67224.png)

**Comment by Feichtmeier** [comment]
I think the disk looks even better than the painting stuff, though  the painting idea maybe only needs some finish 
The only concern could be that the ISO often comes from a usb dongle nowadays :)

**Comment by clobrano** [comment]
Great work @ubuntujaggers! I like the idea and the icon, my only concern is whether the meaning is clear enough, considering that is likely that some people see this the very first time they try to install Ubuntu

**Comment by ubuntujaggers** [comment]
> Great work @ubuntujaggers! I like the idea and the icon, my only concern is whether the meaning is clear enough, considering that is likely that some people see this the very first time they try to install Ubuntu

Yeah, good point.  The most unambiguous solution might be an Ubuntu logo and a disk together:

![unambiguous ubiquity](https://user-images.githubusercontent.com/38893390/72686128-3d645d00-3ae9-11ea-8ea5-334b7ec2b10e.png)

**Comment by Feichtmeier** [comment]
I'd stick with the half painted CoF then :D

**Comment by ubuntujaggers** [comment]
> I'd stick with the half painted CoF then :D

I think the problem also applies to that...  it's hard to come up with a (flat) design where someone will instantly think, "Ah, that'll be the button to put Ubuntu on the PC"  :thinking:

**Comment by Feichtmeier** [comment]
> > I'd stick with the half painted CoF then :D
> 
> I think the problem also applies to that... it's hard to come up with a (flat) design where someone will instantly think, "Ah, that'll be the button to put Ubuntu on the PC"

But it is opened anyways

1) The user inserts his USB stick into the computer
2) reboots and boots into ubuntu
3) selects install ubuntu
4) Ubiquity is launched now without the user launching anything

or

1) The user inserts his USB stick into the computer
2) reboots and boots into ubuntu
3) selects test ubuntu
4) Ubiquity on the desktop and it's pretty obvious an ubuntu logo, which I think will be no problem to be found as "install" ubuntu - also the label beneath is pretty much saying "install ubuntu"
![image](https://user-images.githubusercontent.com/15329494/72686639-288ec600-3af7-11ea-8bb6-b716bdf3c7de.png)

 
:D

**Comment by ubuntujaggers** [comment]
Oh lol, it's labelled :)

**Comment by ubuntujaggers** [comment]
I think my favourite is disk plus pen?

**Comment by Feichtmeier** [comment]
I like both, half coloured and disk+pen :)
Can't really say what's my fav until both are done (are they done? :D )

**Comment by friendlyapple** [comment]
@ubuntujaggers All your suggestions are beautiful... it's difficult to choose :)

I keep a preference for the first logo:
![54856761-091ae700-4cf4-11e9-856c-f77fbacfcf29](https://user-images.githubusercontent.com/59767069/72687604-d00ff680-3aff-11ea-9d45-ce753de20d02.png)

This one is not bad either but it is too "cloudy" and may not be enough "paint":
![72683217-46473580-3acd-11ea-83b1-564294ab0402](https://user-images.githubusercontent.com/59767069/72687645-38f76e80-3b00-11ea-890a-cfdcbd65cae9.png)

**Comment by ubuntujaggers** [comment]
![pencil ubiquity](https://user-images.githubusercontent.com/38893390/72687734-b4edb880-3af8-11ea-9027-1f25ade77f75.png)

Hmm :thinking: 

You know, given the clear label telling you what the icon does, I almost wonder if we should just have a CoF?

**Comment by madsrh** [comment]
As @friendlyapple said, all your suggestions are really beautifully executed 💪 

I hate to be that guy again, but I find that - especially for the small icons - it lacks some contrast. What do you think about something like this? 

![image](https://user-images.githubusercontent.com/3986894/72688403-30eefd00-3b07-11ea-814a-01736ce54f74.png)

**Comment by friendlyapple** [comment]
> As @friendlyapple said, all your suggestions are really beautifully executed 💪
> 
> I hate to be that guy again, but I find that - especially for the small icons - it lacks some contrast. What do you think about something like this?
> 
> ![image](https://user-images.githubusercontent.com/3986894/72689022-3c452700-3b0d-11ea-90d3-fb5da95a1d6d.png)

I find that the orange color is not harmonious with the blue of the pencil (too much contrast). I prefer the original icon proposed by @ubuntujaggers.

**Comment by Feichtmeier** [comment]
@ubuntujaggers how about

Instead of displaying the "not done yet" state by missing paint

We could rather...

Display it by a layer of packaging which covers half of the circle? A origami packaging or packaging for chocolate?

**Comment by ubuntujaggers** [comment]
@Feichtmeier, work in progress:

![image](https://user-images.githubusercontent.com/38893390/72755979-c5b73080-3bc3-11ea-8ad8-5545e31e877a.png)

?

**Comment by Feichtmeier** [comment]
Nice that you are working on this, I hope we are not the only two that like the idea :D

I would try (if I would be able to use inkscape) to make the paper less uneven and super even / geometrical / more like some super accurate Japanese ritual of unfolding a present out of an origami envelope :)

**Comment by Feichtmeier** [comment]
@ubuntujaggers just one more concept - this time by my wife :smile_cat: 
She said that it might be difficult to draw paper on this size. So her Idea of a positive, progression from not-fully-installed-ubuntu to fully-installed-ubuntu-icon could be this:

![photo_2020-01-20_21-56-35](https://user-images.githubusercontent.com/15329494/72757313-ee452780-3bcf-11ea-9a9b-2a509305c026.jpg)

**Comment by ubuntujaggers** [comment]
That's also nice  :)

Something else I tried, because it was quick, is putting the CoF in a traditional envelope:

![image](https://user-images.githubusercontent.com/38893390/72757696-91923e80-3bc8-11ea-8253-c2272cd94267.png)

**Comment by ubuntujaggers** [comment]
Hey, I like this!

![image](https://user-images.githubusercontent.com/38893390/72758538-05354b00-3bcb-11ea-98a1-5ec205e25a8a.png)

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/72760261-0fa61380-3bd0-11ea-9ed7-8b52f6c81779.png)

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/72761406-cd7ed100-3bd3-11ea-868e-a83728b72880.png)

![image](https://user-images.githubusercontent.com/38893390/72761334-a1635000-3bd3-11ea-81f1-54fdf04e6256.png)

**Comment by clobrano** [comment]
> That's also nice :)
> 
> Something else I tried, because it was quick, is putting the CoF in a traditional envelope:
> 
> ![image](https://user-images.githubusercontent.com/38893390/72757696-91923e80-3bc8-11ea-8253-c2272cd94267.png)

this is insteresting, but I'd see it more inside a standard box than an envelope. Like you are unpacking your new shiny Ubuntu :D

**Comment by clobrano** [comment]
xx

> ![image](https://user-images.githubusercontent.com/38893390/72761406-cd7ed100-3bd3-11ea-868e-a83728b72880.png)
> 
> ![image](https://user-images.githubusercontent.com/38893390/72761334-a1635000-3bd3-11ea-81f1-54fdf04e6256.png)

+1 for the pixels coming from the top :)

**Comment by ubuntujaggers** [comment]
I think that's three votes for pixels coming from the top, so I'll finish the icon so we can at least try it for real 👍

**Comment by Feichtmeier** [comment]
Nice! Could you, when your are at it, add a little bit "unevenness" to the cutted edge? Like the pixels are not floating into an even edge but into an uneven edge?

**Comment by ubuntujaggers** [comment]
@Feichtmeier 

How about this, the pixels are a bit less even:

![image](https://user-images.githubusercontent.com/38893390/72832690-4a19ba00-3c7d-11ea-904f-3751a9c047a2.png)

**Comment by Feichtmeier** [comment]
I Love it :D very nice

**Comment by madsrh** [comment]
:tada: Closed https://github.com/ubuntu/yaru/pull/1770
