### ISSUE TITLE
late GNOME 3.32 icon name changes

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#1274]
There were some GNOME 3.32 app releases yesterday (with no previous 3.31 releases) that changed the app icon name.

- preferences-desktop-font → org.gnome.font-viewer
- gnome-characters → org.gnome.Characters
- applets-screenshooter → org.gnome.Screenshot

Except for gnome-screenshot, these releases also adapt to the new GNOME menu guidelines so I think we do need to do these updates.

I have pushed the updated package versions for these apps to Debian experimental. We should land the Yaru update in Disco before we sync those app updates to Disco so that the apps continue to have their intended app icons.

/cc @seb128

**Comment by clobrano** [comment]
Thanks @jbicha, we can add new symlinks for those

**Comment by jbicha** [comment]
I found another one:

- baobab → org.gnome.baobab
