### ISSUE TITLE
Yaru Dark theme: Google Chrome bottom downloads bar text not visible

### ISSUE THREAD

**Issue by prashu20** [ubuntu/yaru#1277]
Thank you for contributing to **Yaru**, the next Ubuntu default Theme made by the community.

If you found a bug please consider to fill below information, this will help us to understand the problem and we don't bother you with other questions :)

If you're filing an issue for a missing icon, look for **Icon Request** section below.

Thanks a lot!

------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior

Text should be visible in the bottom bar of chrome

## Actual Behavior
Can not see any text only icons  of the files visible
(What happened instead)

## Steps to Reproduce the Problem

  1. Open Google Chrome Stable version
  2. Download any file
  3.  Please look at the bottom bar.

## Specifications

Installed Yaru theme via the synaptic package manager

Repository: http://ppa.launchpad.net/communitheme/ppa/ubuntu bionic InRelease 

Software that presents the issue:
- Name: Google Chrome
- Version: 73.0.3683.75 (Official Build) (64-bit)

## In Google chrome bottom bar Text not visible

![bug_yarudark](https://user-images.githubusercontent.com/640513/54481686-366d1e00-4838-11e9-974b-b10708b4211e.png)

Thanks!
Prashant

**Comment by clobrano** [comment]
Hi @prashu20, thanks for taking time to contribute to Yaru!

Unfortunately we have limited power on Chrome/Chromium. In this case it seems that the browser takes only the text color from our palette, but not the background color of the button, which is causing the error.

**Comment by prashu20** [comment]
Hi @clobrano,
Thanks for taking time in replying. I really enjoy the yaru dark theme. Is there anything which I can do at my end ? Should I wait in future the chrome browser may fix this bug. Anyways thanks for your time. Should I close this issue?

**Comment by chrisjbillington** [comment]
I am pretty sure this changed for me in the last week, corresponding to a chrome update. Prior to that, the downloads bar was light text on a dark background. 

I also noticed chrome has previously cleaned up other aspects of their interface to make it better on yaru and yaru-dark, so it seems like they have their eye on it. Presumably they will fix this issue given a little time. You might want to report it against chromium if it is not already reported.

**Comment by prashu20** [comment]
Thanks everyone. As far as I can understand this issue is at chromium end. I will wait for future chrome updates. I am closing this bug now.

**Comment by clobrano** [comment]
Thanks @prashu20, we'll keep a look on this problem anyway :)
