### ISSUE TITLE
Libreoffice snap uses Adwaita instead of Yaru-dark

### ISSUE THREAD

**Issue by Eskander** [ubuntu/yaru#1278]
## Expected Behavior

Libreoffice 6.2 snap should use Yaru-dark for its interface when it's used systemwide.

![image](https://user-images.githubusercontent.com/11521400/54560216-1a958380-49c2-11e9-9407-23210ceee63b.png)

## Actual Behavior

Libreoffice 6.2 snap falls back to Adwaita theme.

![image](https://user-images.githubusercontent.com/11521400/54560246-31d47100-49c2-11e9-8601-3b11f580e624.png)

### Notes:
Libreoffice 6.2 snap with Yaru works as expected.
Libreoffice 6.2 deb with Yaru-dark works as expected.

## Steps to Reproduce the Problem

  1. Install Libreoffice snap package. (`snap install libreoffice`)
  1. Install latest Yaru from GitHub repo.
  1. Select Yaru-dark in GNOME Tweaks.

## Specifications

git describe: `r29-45-g065dd123`

Software that presents the issue:
- Name: Libreoffice Snap
- Version: 6.2.1.2

**Comment by fitojb** [comment]
The right place to file this issue is https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues (the glue snap-packaged applications use to render with GTK themes; it doesn’t seem to include Yaru Dark yet). This isn’t an issue with the codebase of Yaru proper.

**Comment by clobrano** [comment]
@jhenstridge does this make sense to you? Is there something we can do to help?

**Comment by jhenstridge** [comment]
@clobrano: the gtk-common-themes snap is explicitly not including Yaru-dark, likely because the debian packaging used to exclude it too.  We just haven't gotten around to syncing up.

I've put together [MR !13](https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/merge_requests/13), which should help.  It'll need to be merged and a new build published to stable before this is properly resolved.

**Comment by jhenstridge** [comment]
A test snap is available here:

https://gitlab.gnome.org/jamesh/gtk-common-themes/-/jobs/249632/artifacts/browse

**Comment by clobrano** [comment]
sorry for not testing this @jhenstridge. In my VM 18.04 the dark variant is even more broken than this for libreoffice (transparent menus and no style at all), I am not sure why, but this prevent me to test the link above

**Comment by clobrano** [comment]
And now I'm late

![image](https://user-images.githubusercontent.com/2883614/54866980-8e95aa00-4d7b-11e9-8860-69a578747361.png)

**Comment by clobrano** [comment]
It is fixed now, thanks!

![image](https://user-images.githubusercontent.com/2883614/57191669-7abb9700-6f28-11e9-899b-a2cb7af57907.png)
