### ISSUE TITLE
Trying to establish a fork

### ISSUE THREAD

**Issue by mzur** [ubuntu/yaru#1285]
First of all, thanks to all the maintainers for this really nice theme. After using Numix for a long time, Yaru finally convinced me to try something new and I love it!

But.

I can't bring myself to like the orange primary color. To me it looks too much like an error color and seems too "loud" as a background color for larger elements. With "Night Light" switched on, the color gets even more intense. Anyway, I had the same issue with Numix, which also uses orange as a primary color. This is why I [forked it](https://github.com/mzur/Numix-Complement) and made a variant that uses the complementary (blue) color of the Numix orange. So this is what I wanted to do with Yaru, too. Changing the color and building the theme for testing was easy enough:

<p align="center">
<img src="https://user-images.githubusercontent.com/2457311/54871060-06c99300-4daf-11e9-9b8f-38aa69977453.png" height="250">
</p>

I even managed to build and install a local snap that includes my changes and gives the theme a new name (Baru, how imaginative). But now I'm stuck because the new theme does not appear as an option on the login screen. I'm sure that the `snap/session` file has something to do with it but the file does not seem to create the option for the login screen.  Did I miss any build steps (other than the first half of the `prepare-build-snap` script)?

This brings me to my second point. I saw that the `gtk-common-themes` snap is rebuilt alongside `communitheme`. Obviously I can't do this with my fork. Does this mean that other applications that were installed as snaps won't work with my fork?

I'd really appreciate any help you can give me with this!

**Comment by clobrano** [comment]
Hi @mzur, 

> But now I'm stuck because the new theme does not appear as an option on the login screen. I'm sure that the `snap/session` file has something to do with it but the file does not seem to create the option for the login screen

It's `session` folder actually, but the gnome-session is more than just selecting the theme, so you don't need that. I would suggest you to just install gnome-tweaks and if your theme appears in `Appareance` tab, you are done.

> This brings me to my second point. I saw that the `gtk-common-themes` snap is rebuilt alongside `communitheme`. Obviously I can't do this with my fork. Does this mean that other applications that were installed as snaps won't work with my fork?

this is the support for other *snap* applications, that require special support for theme due to their sandboxed nature. You can contact the snapcraft team to ask for support.

Closing this since it's not really a bug, if you need more support try on the [Community HUB](https://discourse.ubuntu.com/c/desktop) :wink:

**Comment by mzur** [comment]
Thanks, I finally managed it. If anyone is interested you can find the fork [here](https://github.com/mzur/baru).
