### ISSUE TITLE
"Live Patch" could use a non-uniform Suru icon

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1287]
Current:

![image](https://user-images.githubusercontent.com/38893390/54872065-2dd79300-4db6-11e9-88bf-6f8c534dc535.png)

Suggestion:

![image](https://user-images.githubusercontent.com/38893390/54872050-fa950400-4db5-11e9-95b5-8e4d9740b0cc.png)

**Comment by Feichtmeier** [comment]
Wow that looks so much better!
