### ISSUE TITLE
"Remmina" could possibly use a non-uniform Suru icon

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1288]
Current:

![image](https://user-images.githubusercontent.com/38893390/54872685-b7d82980-4dbf-11e9-82a0-32e5ef23927a.png)

Upstream might be amenable to Yaru having the following, which puts the official logo on a neutral backplate:

![image](https://user-images.githubusercontent.com/38893390/54872687-d9391580-4dbf-11e9-9787-bde2572e39fe.png)

??

**Comment by Feichtmeier** [comment]
@antenore would this be okay for you?

And thanks @ubuntujaggers

**Comment by antenore** [comment]
@Feichtmeier @ubuntujaggers wow! Fantastastic!

Yes, I like a lot :-)

**Comment by antenore** [comment]
@Feichtmeier what about the upstream PR? We are very much open to accept it ;-)

**Comment by ubuntujaggers** [comment]
@antenore, apologies I haven't submitted anything upstream - I had a look at your project a while ago and wasn't sure how to proceed (I'm a Github novice and only really know my way around the Yaru repo) and then I had a busy month.  Is it enough for me to simply raise an issue and include the svgs?

**Comment by antenore** [comment]
@ubuntujaggers yes, of course, don't worry, an issue will be enough.
Include also any copyright/license info if any
