### ISSUE TITLE
19.04 dailies: logs and system-monitor are suddenly upsteam Gnome icons

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1290]
Think there might have been a package name change or something?  I'll keep an eye on this and see if it changes back to Yaru.

The new Gnome icons are good and the effect isn't jarring, so that proves the wisdom of desquircling our icons (because they can co-exist with the new Gnome ones):

![image](https://user-images.githubusercontent.com/38893390/54877847-277c0200-4e1c-11e9-86ea-1fca6442d1b1.png)

![image](https://user-images.githubusercontent.com/38893390/54877852-32369700-4e1c-11e9-94ab-fb649fe2d60c.png)

...but we do have nice theme icons for these apps, so maybe we need to update the symlinks or something?

**Comment by ubuntujaggers** [comment]
Argh, and calculator too!  It blended so beautifully with our house icons that I didn't even notice this one, lol:

![image](https://user-images.githubusercontent.com/38893390/54878258-16ce8a80-4e22-11e9-8ad6-fd4661fad667.png)

**Comment by Feichtmeier** [comment]
:thinking: could you check which icon is being used in the .desktop file?

Check with 
```bash
nano /usr/share/applications/org.gnome.Calulator
```

somewhere there is a line with
```bash
icon=...
```

**Comment by ubuntujaggers** [comment]
Oh, weird.  Nano creates a new file when I do that.

If I navigate to the folder in Files and search for "calc", the only file in there is the one for LibreOffice.  Doesn't seem to be a file for Calculator.

I'm running Disco Dingo which I installed clean yesterday after knackering my laptop a bit.

**Comment by Feichtmeier** [comment]
maybe it is named gnome-calculator.desktop?

```bash
ls /usr/share/applications | grep gnome
```

**Comment by ubuntujaggers** [comment]
Nope, it's vanished!

gnome-applications-panel.desktop
gnome-background-panel.desktop
gnome-bluetooth-panel.desktop
gnome-color-panel.desktop
gnome-control-center.desktop
gnome-datetime-panel.desktop
gnome-default-apps-panel.desktop
gnome-disk-image-mounter.desktop
gnome-disk-image-writer.desktop
gnome-display-panel.desktop
gnome-info-overview-panel.desktop
gnome-initial-setup.desktop
gnome-keyboard-panel.desktop
gnome-language-selector.desktop
gnome-mouse-panel.desktop
gnome-network-panel.desktop
gnome-notifications-panel.desktop
gnome-online-accounts-panel.desktop
gnome-power-panel.desktop
gnome-printers-panel.desktop
gnome-privacy-panel.desktop
gnome-region-panel.desktop
gnome-removable-media-panel.desktop
gnome-search-panel.desktop
gnome-session-properties.desktop
gnome-sharing-panel.desktop
gnome-shell-extension-prefs.desktop
gnome-software-local-file.desktop
gnome-sound-panel.desktop
gnome-thunderbolt-panel.desktop
gnome-ubuntu-panel.desktop
gnome-universal-access-panel.desktop
gnome-user-accounts-panel.desktop
gnome-wacom-panel.desktop
gnome-wifi-panel.desktop
org.gnome.baobab.desktop
org.gnome.Calendar.desktop
org.gnome.Cheese.desktop
org.gnome.DejaDup.desktop
org.gnome.DiskUtility.desktop
org.gnome.Evince.desktop
org.gnome.Evince-previewer.desktop
org.gnome.Evolution-alarm-notify.desktop
org.gnome.FileRoller.desktop
org.gnome.font-viewer.desktop
org.gnome.gedit.desktop
org.gnome.Mahjongg.desktop
org.gnome.Mines.desktop
org.gnome.Nautilus.desktop
org.gnome.PowerStats.desktop
org.gnome.Screenshot.desktop
org.gnome.seahorse.Application.desktop
org.gnome.Shell.desktop
org.gnome.Shell.PortalHelper.desktop
org.gnome.Software.desktop
org.gnome.Software.Editor.desktop
org.gnome.Sudoku.desktop
org.gnome.Terminal.desktop
org.gnome.Todo.desktop
org.gnome.Totem.desktop
org.gnome.tweaks.desktop
remmina-gnome.desktop

**Comment by Feichtmeier** [comment]
Ahhh it's a snap

**Comment by ubuntujaggers** [comment]
Good diagnosis.

@jhenstridge @popeydc: for core snaps that ship with Ubuntu by default, when Yaru has an icon for the app, would it be possible to build it into the snap?

**Comment by ubuntujaggers** [comment]
Ahhh, I believe ImageMagick is also a snap?  I was trying to test this work in progress:

![image](https://user-images.githubusercontent.com/38893390/54883510-194ed580-4e5e-11e9-84ab-08d2a1fd56b7.png)

...but it didn't pick up the new icon when I did ninja install and I can't see ImageMagick in the folder above.

**Comment by Feichtmeier** [comment]
@kenvandine @jhenstridge is it possible to bake in the yaru icon for these gnome snaps?

**Comment by jhenstridge** [comment]
There's no easy automatic way to push these icons into the snaps, and doing so doesn't really fix the problem: they might look better on one set of desktops, but will now be out of place on a different set of desktops.

There's currently no way to properly use icon names (rather than full file names) in snap .desktop files, which would be the right way to make the icons themeable.  I don't think we've got a good plan for that yet: it brings up similar namespacing issues to various other desktop related features (e.g. we don't want the gnome-calculator snap to be able to provide a themed icon for gedit).

**Comment by Feichtmeier** [comment]
@jhenstridge of that's sad news :(
We, especially @ubuntujaggers, spent a lot of time into creating these icons and now it looks like they won't be used.
Couldn't ubuntu ship with the deb versions of these apps? I don't think it's that important for the user to receive updates via snap at these quiet common desktop tools.
Alternatively: aren't those snaps only preinstalled on the Standart ubuntu? If yes, it would make more sense to me to use the yaru icons instead of the upstream icons.

**Comment by ubuntujaggers** [comment]
@jhenstridge 

> There's no easy automatic way to push these icons into the snaps, and doing so doesn't really fix the problem: they might look better on one set of desktops, but will now be out of place on a different set of desktops.

But some of the desktops are Ubuntu ones :)

This is a limitation of snaps currently, they come with their own non-themeable icon which means they can only match one theme at most. But in this case, if the snaps are made by Ubuntu collaborators and ship with Ubuntu as core apps, IMO it's better for them to match the default Ubuntu theme until they can adapt to the user's chosen one.  It's like we get to choose just one theme for a snap but have chosen a non-Ubuntu one in these cases, which seems strange.

I fully accept it would be unwise to put our original icons in these snaps, but the removal of squircles makes Yaru icons more suitable for general use IMO. When an app doesn't match it's neighbours because it's a snap, I don't think a current Yaru icon is worse than a Gnome one. And in this scenario, at least the subset of desktops where the snaps *do* match perfectly, is our own userbase. I would say one advantage of the new non-squircle icons (which weren't my idea) is that they work better outside their intended context, and that makes them suitable contenders for snaps. For instance: we have a new Yaru icon for Remmina, and upstream have actually asked us to submit a PR for it to be the upstream icon too. I don't think our design would have worked as a non-theme icon if we were still using squircles, but now it does.

Alternatively: is there a halfway house where a snap can ship with just two icons: the Yaru one for users of Yaru, and the default one for everyone else?

**Comment by Feichtmeier** [comment]
@kenvandine @jhenstridge 

maybe we could vote for "please stop to deliver gnome snaps pre-installed" - problem solved. it's not like i need the bleeding edge updates of gnome calculator .... it just ruins the visual consistency (we hardly worked on several months now) without any benefit

**Comment by jhenstridge** [comment]
@Feichtmeier, @ubuntujaggers: I'd prefer to get the proper icon theme support working.  We're not just missing out on Yaru icons with the current status quo: we're also missing out on icon choice based on size.

**Comment by Feichtmeier** [comment]
@jhenstridge also symbolic icons are missing. Which looks strange in gnome shell and many gtk apps

**Comment by clobrano** [comment]
@jhenstridge is there an ongoing discussion about this topic we can follow and, hopefully, contribute to in order to complete the theme support?

**Comment by ubuntujaggers** [comment]
Hi guys,

Unfortunately, these icons landing on Ubuntu desktop does seem to confirm the fact that they don't shine on the Ubuntu launcher (this isn't a fault of the new Gnome icons - they're simply not designed for 48px and don't claim to be):

![image](https://user-images.githubusercontent.com/38893390/55024087-0f5fda80-4ff6-11e9-944e-c47f09ef9e8c.png)

It's a bit of an anti-aliasing festival at this size:

![image](https://user-images.githubusercontent.com/38893390/55024160-34544d80-4ff6-11e9-8496-709853b4c745.png)

Is there a lot of pressure to include these for 19.04, and will any more be added at this late stage?  It's not just us in Yaru...  a lot of Ubuntu users prefer icon themes like Papirus, Moka, etc., and these sore-thumb snaps are going to be an annoyance for anyone who uses a theme.

**Comment by ubuntujaggers** [comment]
@jhenstridge @clobrano @madsrh @Feichtmeier 

I've just been using tweaks tool to look at the Adwaita icon set now that lots of the new icons are part of it.  I would say my personal position has hardened.  If we don't want a big, visible drop-off in the quality of the desktop, I don't think it's a sensible option to use icons that are optimised for 32px and 64px only for core default apps, when a 48px launcher plays such a large part in Ubuntu's workflow and first impression on new users.

This isn't a mockup, I've applied Adwaita as my icon theme.

![image](https://user-images.githubusercontent.com/38893390/55081819-71711c00-5098-11e9-9746-0418a7b5cd02.png)

These are well-executed designs but appear very fuzzy when rendered at 48px, which wouldn't matter too much for some styles, but is a deal-breaker for this one.  Chunky, geometric icons with high contrast on the background need to be sharp.  These are not sharp on the Ubuntu launcher  :(

For comparison, here's how Yaru (which is optimised for 48px too) looks in the same context:

![image](https://user-images.githubusercontent.com/38893390/55081965-ba28d500-5098-11e9-81d3-48e45e23bbac.png)

Sharp!  Here's another comparison.  Gnome calendar:

![image](https://user-images.githubusercontent.com/38893390/55082271-4b984700-5099-11e9-86e2-8f6893d5e873.png)

Yaru calendar:

![image](https://user-images.githubusercontent.com/38893390/55082289-5226be80-5099-11e9-8ee1-d20425505f1c.png)

IMO, at 48px, there's no comparison.  Every time we lose a Yaru icon to a Gnome icon because Ubuntu ships a snap before the icon thing is resolved, there will be a loss of quality.  Not just in terms of visual consistency but also in terms of objective image quality.

**If** Ubuntu makes a political decision to retire house icons and use Gnome icons, that's fine, but then there's an important job to either **a)** rethink the Ubuntu desktop to not use 48px icons by default, or **b)** pixel fit the Gnome svgs so we have a version for each that works at 48px (which, tbh, I could do if Ubuntu chose that path).  But using Gnome icons isn't something we get for free.  It's something we would have to prepare for and adapt to.  Their icons weren't designed for Ubuntu and, worse, were actually designed with assumptions that Ubuntu doesn't share.  So we can't just throw 'em in without hurting the visual quality of the desktop.

**Comment by ubuntujaggers** [comment]
Here's a quick side-by-side showing the current Gnome icons I screenshotted above, next to tweaked versions of the Gnome svgs tweaked for 48px (noting that the svg I used for EoG isn't identical to the one in the screenshot - I don't know whether the one I found was earlier or later but the lens is different).  Current icons are on the left, optimised are on the right:

![image](https://user-images.githubusercontent.com/38893390/55089567-83a58700-50a5-11e9-8670-618641e53e22.png)

**Comment by jhenstridge** [comment]
> @jhenstridge is there an ongoing discussion about this topic we can follow and, hopefully, contribute to in order to complete the theme support?

I had some thoughts about this, and put together a proposal on the Snapcraft forum here:

https://forum.snapcraft.io/t/proposal-support-the-icon-theme-spec-for-desktop-icons/10676?u=jamesh

I am not sure when I'll get a chance to work on this, but I think it would cover the use cases mentioned here:

1. use icon names that can be overriden by themes like Yaru
2. install all the icons provided by the app: multiple sizes, symbolic version, etc.

**Comment by clobrano** [comment]
@jhenstridge, thanks!

**Comment by Feichtmeier** [comment]
@jhenstridge awesome thanks so far! So since it's snap this is not bound to any ubuntu release cycle right?

**Comment by clobrano** [comment]
Closing this since it's up to the snap to allow the theme icon to be used
