### ISSUE TITLE
Icon for some options in Calendar looks like Software centre icon

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#1295]
Ubuntu 18.04, Yaru from stable snap

Just noticed that the icon in the Calendar app looks like icons associated with Software center or updater. The **A** icon
![calendar_icon_suru](https://user-images.githubusercontent.com/1629120/55233310-19fdb800-5220-11e9-83b2-16cefa5af36b.png)

**Comment by Feichtmeier** [comment]
That's because the icon is missing in calendar so it falls back to xapplicationexecutable or sth
How does it look with adwaita icon theme selected?

**Comment by mivoligo** [comment]
![calendar_icon_adwaita](https://user-images.githubusercontent.com/1629120/55237388-fd667d80-5229-11e9-9ce5-2615d3522d00.png)

**Comment by Feichtmeier** [comment]
Yup that's the application x executable

**Comment by mivoligo** [comment]
So the real issue is with the Calendar app?

**Comment by Feichtmeier** [comment]
Hmmm we first discovered it in gnome software because the new row "applications" was added there. I think even though taking x-application-runnable as an icon for this row was not a good idea, we could prbly change that A for the icon to something more generic.
But gnome calendar has prbly a bug here too. What happens if you click it?

**Comment by mivoligo** [comment]
After clicking a menu appears:
![calendar_icon_clicked](https://user-images.githubusercontent.com/1629120/55314425-06419400-5462-11e9-8a35-9e200b07c5ee.png)

**Comment by clobrano** [comment]
It's the appmenu, moved from the top panel to the application headerbar

**Comment by clobrano** [comment]
> we could prbly change that A for the icon to something more generic (not the Software-updater or gnome software symbolic icon).

what about something in between "A" and upstream icon with the gear?

/cc @ubuntujaggers

**Comment by ubuntujaggers** [comment]
Yep, it looks a bit weird currently.

**Comment by Feichtmeier** [comment]
Sorry about that, was a bit of a short-termin solution without realising what we change there :/
I see if I could make some small icon for this, seems easy enough for me to handle (prbly it isn't ... but I'll try)

**Comment by Feichtmeier** [comment]
@ubuntujaggers 

Does this already fit?
![image](https://user-images.githubusercontent.com/15329494/57580145-1a87a080-74a6-11e9-8122-eac12cfd8f9e.png)

That is the already existing full-color icon
![image](https://user-images.githubusercontent.com/15329494/57580156-35f2ab80-74a6-11e9-809c-cff1fa5d275e.png)

**Comment by Feichtmeier** [comment]
Oh this one was fixed by @ubuntujaggers
