### ISSUE TITLE
I think Sudoku icon needs to be improved

### ISSUE THREAD

**Issue by gusbemacbe** [ubuntu/yaru#1298]
Hello developers and deisgners,

I think the sudoku icon needs to be improved, because somebody will think sudoki is a game of hashes, therefore, it does not contain numbers. Give a look at images at DuckDuckGo site.

**Comment by clobrano** [comment]
Hi @gusbemacbe, thanks for taking time to contribute to the project.
This is the Yaru icon and I think you're right


![image](https://user-images.githubusercontent.com/2883614/55292428-40238380-53eb-11e9-820f-02f6654c0c54.png)

**Comment by gusbemacbe** [comment]
Yes, both Suru and Yaru icons look like more hash game than sudoku game. So the common users will think it is a hash game.

**Comment by gusbemacbe** [comment]
In reference to hash game: https://en.wikipedia.org/wiki/Tic-tac-toe

**Comment by madsrh** [comment]
I'm sure @ubuntujaggers has something great up his sleeve 😉

**Comment by ubuntujaggers** [comment]
No probs - we inherited the pictogram from Suru and just added the missing detail to the smaller sizes. I can have a go at some designs including numbers :)
