### ISSUE TITLE
Missing Snap Store icon

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1300]
Snap Store is official application by Canonical.

![Снимок экрана от 2019-04-14 15-12-45](https://user-images.githubusercontent.com/40228953/56092017-c4840500-5ec7-11e9-865a-868c32f972a4.png)

**Comment by ubuntujaggers** [comment]
When I look at the Snap Store app in Ubuntu Software, it says "Source: Snap Store".  I think that means it's a snap itself and won't pick up any theme icons yet?

**Comment by Feichtmeier** [comment]
@ubuntujaggers correct! Apart from that, it's already an origami icon. Do we really need to change this?

**Comment by eaglersdeveloper** [comment]
This icon don't looks in Yaru style.

**Comment by clobrano** [comment]
I understand this point of view, but this is also designed by Canonical already

**Comment by Feichtmeier** [comment]
Agreed! We should either ask canonical to adapt to the Yaru icons, or leave it as it is

**Comment by didrocks** [comment]
I don't really know TBH, I think for everything snap related, try with @kenvandine who would know who to get in touch with.

**Comment by kenvandine** [comment]
Might be worth asking design to update it to match Yaru, I'll do that.

**Comment by Feichtmeier** [comment]
Discussion went over to https://github.com/ubuntu/yaru/issues/1433
Thus, closing this one
