### ISSUE TITLE
Yaru Dark + Mozilla: White text on white background  

### ISSUE THREAD

**Issue by sabrekke** [ubuntu/yaru#1301]
I love the Yaru dark theme, but I have a recurring problem of white text appearing on a white background in Mozilla applications, namely Thunderbird and Firefox, on 19.10. In FireFox it appears to happen in text fields, while it happens in an apparently random selection of E-mails in Thunderbird. 

I should add that the Firefox-issues cannot be reproduced in Chromium - everything looks fine there.

### How to reproduce ###
In Firefox, the bug can easily reproduced (on my system, at least) by:
1. Go to google.com, search for something prompting the in-search Google Translate function, eg. "Fish German". The text fields showing the English word will display a bright grey text on a white background, while the German translation is displayed black on white.
2. Go to reddit.com, press "log in". Both the username and password fields display the same colour combinations as explained above, rendering them impossible to read.

In Mozilla Thunderbird, I have found no great logic to when e-mails in my inbox appear all in white - they can come from different senders, and they will all look completely normal in the standard theme. Some have rich text or HTML formatting, others do not. The only pattern I've found is that it seems to affect replies, not the first E-mail in a chain. That could be random, though. The bright grey on a white background is the same as in Firefox.

I use the standard Yaru Dark theme that ships with the 19.10 beta.

---- 
Finally, thanks for developing such a great theme! I've been following the development of the communitheme from the sidelines, and I'm super impressed by your work. It's highly appreciated!

**Comment by clobrano** [comment]
Hi @sabrekke, thank you for the support and for reporting this issue.

I double-checked the issue on reddit and I can confirm that, however is up to Firefox to adapt the colors in this case. All text fields in Yaru-dark are dark with bright text, in this case it seems that Firefox (or more probably this is due to reddit website) is displaying the entry background white without adapting the text color accordingly.
