### ISSUE TITLE
Nautilius - odd look to headerbar

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/yaru#1304]
## Expected Behavior

Resized naultilus window, and expected the "Home" button to stay far left, and the search button far right.

## Actual Behavior

When you resize nautilus, it looks like it has a max width for the pathbar+search icon and so tries to center these if the window is too wide. This looks OK with Adwaita, but **horrible** with Yaru.

Yaru:
![Screenshot from 2019-04-18 19-26-06](https://user-images.githubusercontent.com/1141694/56382814-31710500-6210-11e9-9db0-202e555b2da2.png)

Adwaita:
![Screenshot from 2019-04-18 19-29-52](https://user-images.githubusercontent.com/1141694/56382885-63826700-6210-11e9-802c-84702cb72f8a.png)

With adwaita, when the path bar is centered the background of the whole widget is drawn. With Yaru, it appears as if the "Home" and "search" icons are just placed randomly. There should at least be a border drawn to connect the two.

## Steps to Reproduce the Problem

  1. Open nautilus
  1. Resize to sufficient width/

## Specifications

Yaru, and Ubuntu session, are from an upgraded 18.10 -> 19.04 install.

**Comment by clobrano** [comment]
Hi @CDrummond, you're right, we probably need to bring back pathbar background to fix this

**Comment by Feichtmeier** [comment]
There is a style class for the expanded mode... Or a state. Need to ninja the code from adwaita :)

**Comment by Feichtmeier** [comment]
it's .width-maxized

Tried different stylings with bg and borders but ended up with this solution :man_shrugging: 
![image](https://user-images.githubusercontent.com/15329494/56462810-b05d6d80-63c9-11e9-90e4-dd3f39560cef.png)

Adwaita has a different padding/margin of buttons so there is still space left
Any other ideas very welcome

**Comment by clobrano** [comment]
Not sure about this solution. This new vertical line looks like the usual separator (like in gedit or settings) but isn't aligned (and it can't be aligned). Il propose something in the next days

**Comment by Feichtmeier** [comment]
The problem with a background is that the pathbar is much bigger than the buttons. Resulting in a big surface being highlighted, which completely ruins the minimalistic and clean look we have now.
The style class .width-maxmized is attached to the pathbar, not the buttons inside the pathbar. : /

**Comment by clobrano** [comment]
What about this?

![image](https://user-images.githubusercontent.com/2883614/56526706-e545fd80-654c-11e9-8fbc-730840ce110b.png)

This means to go back to pathbar in buttonbox style, because otherwise the underline effect will clash with the `path-bar-box` border, but it doesn't seem too bad to me

![image](https://user-images.githubusercontent.com/2883614/56526907-2e964d00-654d-11e9-8673-37eebf8bcbd4.png)
![image](https://user-images.githubusercontent.com/2883614/56526941-39e97880-654d-11e9-8c99-2dbf31db6f89.png)

**Comment by Feichtmeier** [comment]
This would also bring 100% consistency to the headerbar buttons no matter where they are in. It looks just as good as the Strafgericht lstackswitcher. It's sad to see the underline go but this makes just sense

**Comment by Feichtmeier** [comment]
But the double layered BG look strange. I think a border should be enough

**Comment by Feichtmeier** [comment]
Update: (sorry for auto-closing)

Thanks to @clobrano we now have the same look of buttonbox linked buttons and stackswitcher .linked buttons for the pathbar .linked buttons!
Sadly the border around the pathbar produces some bug so we've cut this part

I am not 100% sure but I think adwaitas latest release also removed the border around the whole pathbar

**Comment by Feichtmeier** [comment]
Closing this as it is not happening anymore with new master branch (refreshed from upstream)
In bionic this can't happened with that old nautilus version (except someone installs a flatpak)
