### ISSUE TITLE
Top-Panel Volume Slider resets on restart

### ISSUE THREAD

**Issue by sudhirdhumal289** [ubuntu/yaru#1305]
## Expected Behavior
When I increase volume from top-bar / top-panel from X % to 100% (over amplification is disabled) it should persist the user setting even after restart.

## Actual Behavior
I did increase the volume from top-bar / top-panel from X % to 100% then restarted the machine and now volume is at X % again. Ubuntu is resetting the user setting to default one.

**Comment by clobrano** [comment]
HI @sudhirdhumal289, thanks for taking time to report this.
Yaru is "just" the graphic theme, we have no part in saving the settings between restarts. I am not sure which component is really responsible, however you can probably start asking in gnome-shell https://gitlab.gnome.org/GNOME/gnome-shell
