### ISSUE TITLE
The orange folder icon in Yaru is too intense to watch, it should be toned down a bit

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1312]
The nice short title is [taken from the hub](https://community.ubuntu.com/t/the-orange-folder-icon-in-yaru-is-too-intense-to-watch-it-should-be-toned-down-a-bit/).

> That intense orange is mostly suitable for small things (like selections, underlines).
>
> It’s very flashy and it’s OK for kids, but for an employee who works 8 hours with Nautilus in full screen (and with many folders) it is the predominant color on the entire screen and it is really hard to look at for a long time.

As much as I agree with this, I think we should keep the orange folders (unless someone has a good alternative), BUT tone down the color _slightly_.

**Current:**
![image](https://user-images.githubusercontent.com/3986894/56694119-51a83480-66e6-11e9-8f52-0f6cf7911ae1.png)

**Suggestion:**
![image](https://user-images.githubusercontent.com/3986894/56694154-61277d80-66e6-11e9-9a13-8a598fc2a499.png)

**Alternative suggestion:**
![image](https://user-images.githubusercontent.com/3986894/56695069-84532c80-66e8-11e9-8320-6a9b98acba1b.png)

_Note:_ These are quick mockups, so I've simply added a color overlay which means that the white symbolic icon is colored too. These would ofc be crystal clear in the final version.

**EDIT:** I forgot to add the "orange stab" sidebar for comparison
![image](https://user-images.githubusercontent.com/3986894/56696346-d6e21800-66eb-11e9-8834-64528b9016b1.png)

**Comment by ubuntujaggers** [comment]
@madsrh 

![image](https://user-images.githubusercontent.com/38893390/56699990-ce8bdc00-66ef-11e9-9ce5-ea7c6c7d2c13.png)

?

**Comment by madsrh** [comment]
Looks great @ubuntujaggers :tada:
There's a ton of different folder icons - do you have time to create a PR with this color change (if @clobrano also approves)?

You are targeting the "suggestion" mockup, right? Would you say that the "Alternative suggestion" is too much? I think that it might be better because it's more neutral 🤷‍♂️Perhaps too yellowish

**Comment by ubuntujaggers** [comment]
Yep, I pipetted colours from the first mockup for starters - we could try that in a test PR and then try the second one too?

**Comment by madsrh** [comment]
Yes! +1 Let's do that

**Comment by tomkra** [comment]
I don't agree. Suggested colors looks faded and ugly to look at. Current color is so much better and I've never had problem with It's intensity so I downvote for this one change.

**Comment by clobrano** [comment]
> Suggested colors looks faded and ugly to look at

I think that "faded" was the goal of the change, I don't agree about the "ugliness", which is an unnecessary word other than rather subjective.

**Comment by madsrh** [comment]
Closed by https://github.com/ubuntu/yaru/pull/1316
