### ISSUE TITLE
Maximized nautilus needs refinement

### ISSUE THREAD

**Issue by otavioschwanck** [ubuntu/yaru#1314]
Maximzed adwaita:
![image](https://user-images.githubusercontent.com/9551316/56704083-228fc400-66e2-11e9-84ec-d641a11e95f5.png)

Maximized Yaru:
![image](https://user-images.githubusercontent.com/9551316/56704099-2facb300-66e2-11e9-9dc5-249b5104e93c.png)

The yaru needs another color on pathbar, otherwise, the search icon seems lost.

**Comment by Feichtmeier** [comment]
Hi thanks for reporting issue
There's already an issue about this :) 
https://github.com/ubuntu/yaru/issues/1304
Closing this
