### ISSUE TITLE
Small Remmina icon issues

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1329]
edit: 
working now ~~1) the full color icon is not being used in disco because it now uses the new gnome icon name convention of Icon=org.remmina.Remmina~~

2) the symbolic icon is missing and instead the new remmina icon is being used
![image](https://user-images.githubusercontent.com/15329494/57012310-1043e780-6c06-11e9-8b63-c882d1a95fcd.png)

**Comment by ubuntujaggers** [comment]
Should the symbolic follow the same name with -symbolic at the end?

**Comment by Feichtmeier** [comment]
I think yes :thinking: 

But there are also "remmina-panel" icons in my bionic installation. could you check in disco how they are named? They should be in /usr/share/icons/hicolor

**Comment by ubuntujaggers** [comment]
They're named the same in Disco.  Weirdly the one that appears for Remmina at the top right isn't 16px either, I think it's the 24px.  Whatever they are it doesn't seem to be using them  :\

**Comment by ubuntujaggers** [comment]
I've got the symbolic and the symlink working in my branch but can't work out how to do the panel icon.  Do we need a new icons folder in Yaru called "hicolor", alongside apps, status, etc.?  Or would hicolor go at the level of fullcolor versus symbolic?

**Comment by ubuntujaggers** [comment]
I can experiment, but if anyone already knows then that would be helpful  :)

**Comment by Feichtmeier** [comment]
@ubuntujaggers when a deb is installed it installs it's icons into hicolor. It is no real icon set it is somehow connected to how the .deb / freedesktop standard works I think :thinking: 

Could could push your branch and I check if I find the correct name for the panel icon? I don't have an idea neither currently :( only trial and error could help

**Comment by ubuntujaggers** [comment]
NP, I'll push it this evening :)

**Comment by Feichtmeier** [comment]
Half of the issue is fixed, only the panel icon issue is still there @ubuntujaggers

**Comment by Feichtmeier** [comment]
Since your icon has been accepted upstream, can't we drop it in Yaru?
https://gitlab.com/Remmina/Remmina/blob/master/data%2Fdesktop%2Fscalable%2Fapps%2Forg.remmina.Remmina.svg

I think then the symbolic icons should work again for the panel icon
