### ISSUE TITLE
Screenshield clock text shadow might be too low

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1333]
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/gnome-shell-sass/_common.scss#L2100

reported on reddit O.o

https://www.reddit.com/r/Ubuntu/comments/bjtbzo/hey_ubuntu_devs_when_you_choose_a_white/

**Comment by Feichtmeier** [comment]
@madsrh @clobrano @ubuntujaggers @galgalesh (tagging because I saw you on reddit ;) )

With the super extreme white wallpaper
![image](https://user-images.githubusercontent.com/15329494/57128179-e23fde00-6d92-11e9-8858-8fed9b6c6b46.png)



With the default wallpaper
![image](https://user-images.githubusercontent.com/15329494/57128238-15826d00-6d93-11e9-832f-1b65c2d7e3ec.png)

Is this okay?

**Comment by ubuntujaggers** [comment]
Good point, it's not very legible. Agree it's worth trying a darker shadow here.

**Comment by eaglersdeveloper** [comment]
Or we can make background darker.
