### ISSUE TITLE
Ubuntu 19.10 yaru-dark lock screen not themed

### ISSUE THREAD

**Issue by StructByLightning** [ubuntu/yaru#1338]
## Expected Behavior

When using yaru-dark, the lock screen's password input field, profile icon (head + shoulders) and cancel button should all be dark. 

## Actual Behavior

The input field, icon, and button are all bright white, unchanged from the default (light) yaru theme. 

## Steps to Reproduce the Problem
  1. Install gnome-tweak-tool.
  2. Change your theme to yaru-dark.
  3. Press winkey + L, or click the row of icons (brightness, wifi, sound, battery) in the top left and then click the lock at the bottom of the popup panel.
  4. Press space after the screen locks to dispel the wallpaper and bring up the login screen.

## Specifications

Yaru came with my OS, and I haven't installed a different version or edited any files. This is a freshly installed copy of Ubuntu, with default settings.

Software that presents the issue:
- Name: Ubuntu
- Version: 19.10

**Comment by Feichtmeier** [comment]
The shell theme can not have light/dark variants for the login screen because it is somehow backed into the session.

Thanks for reporting please don't hesitate to open any further issues
