### ISSUE TITLE
Get a better boot screen

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1341]
I think those orange dots are not bad, but we use blue for progress bars and so on.

Any good ideas for a nice plymouth screen?
@madsrh @mpt @ubuntujaggers @clobrano

Some inspiration and/or possible contacts:

https://www.gnome-look.org/p/1111249/
![image](https://user-images.githubusercontent.com/15329494/57214358-0ba67700-6fea-11e9-851a-59abc358d00e.png)

https://www.gnome-look.org/p/1009320/
![image](https://user-images.githubusercontent.com/15329494/57214407-2d9ff980-6fea-11e9-9aef-57822bf7d83d.png)
(ofc... not with the apple ... but i like the simple line)

**Comment by madsrh** [comment]
Unless someone comes up with something brilliant, elegant and simple, I vote for keeping the current dots.

The three color mix is odd IMHO:
![image](https://user-images.githubusercontent.com/3986894/57359694-a208a300-7178-11e9-9bc2-5f8a074b8ee7.png)

**Comment by Feichtmeier** [comment]
How about a blue line, withot the gray/white unfilled area?
like with an invisible trough

**Comment by meetdilip** [comment]
I think we should check whether we can use the Ubuntu flower which was designed for Ubuntu Phone. Glowing petals and rotating flower would look awesome.

**Comment by madsrh** [comment]
> I think we should check whether we can use the Ubuntu flower which was designed for Ubuntu Phone. Glowing petals and rotating flower would look awesome.

I was considering that too, but this might increase the file sizes and loading time for plymouth because it's much more complicated than just a simple dot.

![image](https://user-images.githubusercontent.com/3986894/57533924-23119700-733f-11e9-801b-b16f37a9685c.png)

**Comment by meetdilip** [comment]
Perhaps just petal glowing animation as in dots.

**Comment by Feichtmeier** [comment]
Found the Darwin repo
https://github.com/yucefsourani/arfedora-plymouth-theme

**Comment by eaglersdeveloper** [comment]
Reopen and pin please.
We should create new design of [boot screen with vendor logo](https://discourse.ubuntu.com/t/testing-flickerfree-boot/11854).

**Comment by clobrano** [comment]
> We should create new design of [boot screen with vendor logo](https://discourse.ubuntu.com/t/testing-flickerfree-boot/11854).

Are you going to propose your design?

**Comment by Feichtmeier** [comment]
I can't really see how we can insert and design in this.
It's a black screen with a vendor logo and and a spinner

The only thing we could talk about is the colour of the spinner
