### ISSUE TITLE
Suggestion: Login screen password box

### ISSUE THREAD

**Issue by Dragon8oy** [ubuntu/yaru#1342]
The white in the password box and cancel button doesn't really fit with the rest of the login screen or the topbar, the dark box as seen in Ubuntu 18.04 without Yaru fits MUCH better.

Current:
![alt text](https://i.stack.imgur.com/oq50m.png)

Dark boxes, like 18.04:
![alt text](https://vitux.com/wp-content/uploads/2018/08/word-image-86-1024x576.png)

**Comment by clobrano** [comment]
Hi @Dragon8oy, it is an interesting idea, we will try, thanks!

**Comment by clobrano** [comment]
So, before making any PR, I'll present some mockups here.

First is simply the default dark entry in our shell

![image](https://user-images.githubusercontent.com/2883614/57240448-bccf0080-702e-11e9-8492-81ede1b40642.png)

There are some observation from my side
- the flat entry does not give the same nice effect 18.04 showed
- the orange selection in this even darker context does not fit well

Mainly for the second point, I tested also a purple selection (that will be used only for this specific context)  
![image](https://user-images.githubusercontent.com/2883614/57240696-762dd600-702f-11e9-9a69-86031ef5869f.png)

This way it makes a bit more sense, but it's not a clear win over the current login for me.

What do you think?

**Comment by Dragon8oy** [comment]
That's exactly what I meant, to me it looks way better than what's currently in Yaru.

**Comment by Feichtmeier** [comment]
I think the whole composition is a bit chaotic now. I would suggest to make the button also dark
Also increasing the brightness of the purple is a must then, since the contrast is really poor

**Comment by Feichtmeier** [comment]
Some ideas, first inkstone background, transparent black entry, red destructive button (seen on telegram)
![image](https://user-images.githubusercontent.com/15329494/57242631-50570000-7034-11e9-9a39-d6e42d14c574.png)
![image](https://user-images.githubusercontent.com/15329494/57242666-69f84780-7034-11e9-955a-43c38e5a997f.png)
which has a very good contrast but could look a bit "boring"

Same bg color but with the noise texture from upstream
![image](https://user-images.githubusercontent.com/15329494/57242852-e854e980-7034-11e9-8d90-6606b93860b4.png)

Not-so-super-dark purple with the noise texture
![image](https://user-images.githubusercontent.com/15329494/57242986-42ee4580-7035-11e9-8b3b-e6c715916afe.png)

Same bg, dark gray button
![image](https://user-images.githubusercontent.com/15329494/57243157-ad06ea80-7035-11e9-999a-ff9fbb1c013c.png)

**Comment by Dragon8oy** [comment]
Definitely one of the purple backgrounds, I think I prefer the red button as then it's like green and read to unlock and cancel, like launch and abort buttons, etc. Either is better than the white Cancel button though

**Comment by clobrano** [comment]
I'm not convinced by the red button, it's not a destructive action

**Comment by Dragon8oy** [comment]
I think the red works well because it contrasts well with the green and you often see green and red having opposite actions (Stop, Go - Cancel, Continue).

May I ask what happened to the Ubuntu logo at the bottom of the purple images?

**Comment by Feichtmeier** [comment]
I like the bright red just for the lolz
But I agree it makes not so much sense, because the user's eye jumps back and forth between 
Succeed! Destroy! Succeed! Destroy!
:)

**Comment by Dragon8oy** [comment]
Ok, whatever you guys want. I was just suggesting that the password box and cancel button be styled to fit, which has been achieved. Whatever comes from here, I probably don't mind.

**Comment by Paz-it** [comment]
+1 for @Feichtmeier last mock-up with the dark Gray button

**Comment by Feichtmeier** [comment]
Hmmm i am still not convinced that these are better than the current one though the current one is far from perfect
Let's see if we can come up with something else, also would be nice if we could wait until @madsrh is back in town

**Comment by madsrh** [comment]
I think this is [the ](https://user-images.githubusercontent.com/15329494/57243157-ad06ea80-7035-11e9-999a-ff9fbb1c013c.png)best one

> Same bg, dark gray button

There's an old issue where @godlyranchdressing did some mockups and I believe the red button is a no-go because it isn't a destructive action.

**Comment by clobrano** [comment]
> +1 The current is great for accessibility

this is an important observation. If we're not convinced this is a real improvement, I'd say let's keep the current state

**Comment by Feichtmeier** [comment]
We could keep the level of usability/accessibility of we carefully set the contrast of the elements with the dark login screen.

Contrast between popups/BG
Entry/BG
Button/BG
Focus border / button
Focus border / entry

**Comment by Feichtmeier** [comment]
What about this @clobrano @madsrh  @ubuntujaggers 

![Screenshot from 2019-05-08 17-52-27](https://user-images.githubusercontent.com/15329494/57389351-4232ec00-71ba-11e9-891e-03501020fcec.png)

![Screenshot from 2019-05-08 17-52-52](https://user-images.githubusercontent.com/15329494/57389350-4232ec00-71ba-11e9-9505-bd4c5c416c57.png)

**Comment by clobrano** [comment]
Updated #1348 with brighter background. I have a problem with the VM so I cannot provide a screenshot right now, I'll try again later

**Comment by Feichtmeier** [comment]
Yes I tried your branch. Why did you change the focus colour to be inkstone? :D

**Comment by clobrano** [comment]
It looks way better than purple for me

**Comment by Feichtmeier** [comment]
I meant the focus color, not normal border color :)

**Comment by clobrano** [comment]
Ah, I don't know, I didn't on purpose and I wasn't able to change it

**Comment by clobrano** [comment]
> I meant the focus color, not normal border color :)
> [e9e05a9#diff-bd1d59deea6a6eeba80285784fae338bR1975](https://github.com/ubuntu/yaru/commit/e9e05a9473b14fa58351462b7a6fc4823a10da52#diff-bd1d59deea6a6eeba80285784fae338bR1975)

basically because in "focus" state $fc is used only for the border

> And the purple is still a bit too dark imho, the contrast is not high enough.

ok

**Comment by clobrano** [comment]
Slightly brighter purple and cancel button

![image](https://user-images.githubusercontent.com/2883614/57457427-d14e0b80-726f-11e9-9eda-0804f562b46a.png)

**Comment by clobrano** [comment]
Also, I find the default user-icon a bit lost in space, what about this instead?

![Screenshot from 2019-05-09 15-39-11](https://user-images.githubusercontent.com/2883614/57458203-38b88b00-7271-11e9-9c6f-40821f0fa4a3.png)

here with a non-default icon
![Screenshot from 2019-05-09 15-39-47](https://user-images.githubusercontent.com/2883614/57458229-440bb680-7271-11e9-8e27-6dde3a068f25.png)

**Comment by Feichtmeier** [comment]
The contrast should be high enough now
I have no strong opinion on the circle
But I think the colour combinations could be harmonized a little. Gray button, black entry, white circle. It looks a tiny bit unorganized now. Let's wait for the others or make more suggestions

> basically because in "focus" state $fc is used only for the border

Yes, but why don't we leave the focus border orange like with all other entries?

**Comment by clobrano** [comment]
> Yes, but why don't we leave the focus border orange like with all other entries?

Because I think that a thin orange line in a wide purple background does not fit very well, and the example of 18.04 without the orange border looks good, but it might be just my opinion.

**Comment by Feichtmeier** [comment]
Could you show a picture with the button as dark as the entry?

**Comment by clobrano** [comment]
Cancel button is fully flat, there's no box-shadow, just a slightly brighter (1%) border that can eventually be removed.

Here is the cancel button in inkstone, but IMO it is too similar to the entry

![image](https://user-images.githubusercontent.com/2883614/57514336-8b954f80-7310-11e9-9961-e66bef2ec18e.png)

**Comment by Feichtmeier** [comment]
Okay that looks bad, nvm.

Yeah the border. Fine, then let's finish the styling and I'll do a little code refactoring without a style change after we finished this here

**Comment by clobrano** [comment]
What kind of refactoring you had in mind?

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/commit/08fe505124e557d902576fb631da5cda1fc15f75

**Comment by Feichtmeier** [comment]
Hm, i am still not sure about this.
Tried your branch and I don't really like the colour combinations :(

**Comment by clobrano** [comment]
We can even keep the same white entry and cancel button we have now, but now that I worked more on it, I would still ship the white circle and the focus border change

**Comment by Feichtmeier** [comment]
Thought about further reducing the amount of colors. What about this @madsrh @clobrano @ubuntujaggers : 

![Screenshot from 2019-05-10 15-00-48](https://user-images.githubusercontent.com/15329494/57529194-982b9f00-7334-11e9-9dbb-f43a1eb0b230.png)

- slightly transparent entry, like in the shell overview
- green success button
- purple noise bg
- purple cancel button

(circle around the avatar is excluded just because I am very neutral on that :) )

**Comment by madsrh** [comment]
I like the slightly transparent entry, but I'm not sure about the purple cancel button - it looks good but will it be confusing?

Are you both +1 for the noise bg? I'm asking for a friend ;)

**Comment by Feichtmeier** [comment]
Lol! xD Who is that friend? NusiNusi? :O 
I like the noise bg, and I have no idea why I did not like it back then. It reduces the "terror of the purple" a bit.

**Comment by clobrano** [comment]
> Are you both +1 for the noise bg? I'm asking for a friend ;)

I've always been :D, but not as much to fight for it

**Comment by Dragon8oy** [comment]
I think the dark grey cancel worked better, shows 18.04 and works with the password box better.

**Comment by meetdilip** [comment]
Why not use a wallpaper ? I used to have one after editing Ubunut.css . I looked great.

**Comment by Feichtmeier** [comment]
Because wallpapers can be strechtched by different resolutions or float around not centered. That texture is one solution that works on every screen

**Comment by ubuntujaggers** [comment]
Sorry I've been busy lately! I never liked the noise much but happy to be outvoted, it's not like it'll bother me :)

**Comment by ubuntujaggers** [comment]
I like those colours btw.

**Comment by meetdilip** [comment]
Isn't circle for user avatar the trend these days ?

**Comment by clobrano** [comment]
White border was in previous version, but the shape was a squircle. When upstream moved to rounded avatars we tried for a bit and then drop ip because the border was too close to the default user icon. Now I tried to add some space and IMO it doesn't look bad. I prefer how it looks with the avatar pic, but without it the default user icon seems drop in the middle of nower

**Comment by Feichtmeier** [comment]
@clobrano tbh you are right, purple and orange does not look perfect. 
How about white as the border color for the whole login screen?

![image](https://user-images.githubusercontent.com/15329494/57566949-a16b4900-73d2-11e9-91de-39eb42c434d8.png)
![image](https://user-images.githubusercontent.com/15329494/57566953-acbe7480-73d2-11e9-8e14-6e0a45017aaa.png)

Or slightly transparent white
![image](https://user-images.githubusercontent.com/15329494/57566976-e1323080-73d2-11e9-9efd-070c65c56351.png)
![image](https://user-images.githubusercontent.com/15329494/57566981-e7281180-73d2-11e9-949d-8bfbd9d319ec.png)

**Comment by clobrano** [comment]
The last one is better and looks good

**Comment by Dragon8oy** [comment]
What about with the cancel as some shade of grey? I feel it might look better but if not, that seems good.

**Comment by Feichtmeier** [comment]
@Dragon8oy it is very subjective at this point, but the gray, black, purple combination were kind busy in terms of amount of colors

WHat about the user selection @clobrano  ? That is also orange on purple
Maybe this works instead ?

![image](https://user-images.githubusercontent.com/15329494/57570458-713b9e80-7402-11e9-85d1-8ef7fbd493c1.png)
![image](https://user-images.githubusercontent.com/15329494/57570480-b8c22a80-7402-11e9-9c57-85ab67d45a16.png)

**Comment by clobrano** [comment]
I am not in favor of the purple for selection, even more if combined with the color of the cancel button (someone could think that both widgets are selected)

**Comment by Dragon8oy** [comment]
Yeah same, I don't think the purple button works on the purple background very well, it's too much of the same colour IMO.

**Comment by Feichtmeier** [comment]
True. Hm so just leave it orange?

**Comment by Feichtmeier** [comment]
@clobrano what about this?
![image](https://user-images.githubusercontent.com/15329494/57572728-0c427180-741f-11e9-8105-f2ab212c9200.png)

**Comment by clobrano** [comment]
I don't really like the purple circle actually, and the highlight looks too bright

**Comment by Feichtmeier** [comment]
@clobrano what about an inkstone circle?
![image](https://user-images.githubusercontent.com/15329494/57572845-8c1d0b80-7420-11e9-92fa-84cd620d1066.png)

And base_hover_color for the selection
![Peek 2019-05-11 19-12](https://user-images.githubusercontent.com/15329494/57572859-aeaf2480-7420-11e9-9a97-2be597c46630.gif)

**Comment by Feichtmeier** [comment]
Or with a 2px fg color border

![image](https://user-images.githubusercontent.com/15329494/57572894-0fd6f800-7421-11e9-9162-c455e397ef7d.png)

**Comment by clobrano** [comment]
I like the white border, but not the background. It seems a bit too heavy

**Comment by Feichtmeier** [comment]
$slate ?

![image](https://user-images.githubusercontent.com/15329494/57572951-aacfd200-7421-11e9-9a8c-545c295b4e62.png)

**Comment by clobrano** [comment]
What's the reason to use a background at all?

**Comment by Feichtmeier** [comment]
I thought it might fit when you compare it to the other icons that you receive when you create more users in gnome-control-center

**Comment by clobrano** [comment]
I see, but to me transparent bg is the best option

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/57573090-7d842380-7423-11e9-904c-356aef8b9863.png)

![image](https://user-images.githubusercontent.com/15329494/57573098-9a205b80-7423-11e9-996f-990f523a99a5.png)

You like the 2px focus border for the entry?

**Comment by clobrano** [comment]
I should see it on the pc, but I'm AFK now

**Comment by Feichtmeier** [comment]
Okay, I'll commit it and you can test it if you want

**Comment by clobrano** [comment]
Okay, IMO it is better with

* 1px entry border
* 1px user icon border
* orange selection for user

**Comment by Feichtmeier** [comment]
No the user icon border becomes fuzzy at the in that circle when it is without a BG. Similar to the system shut down icon.
I think the cleanest look was the one with just a BG, because the other user circles have a BG disk hardcoded.
And the milky user selection fits from the design logic of making things milky/white/gray on hover (clone window border, popover elements)

**Comment by Dragon8oy** [comment]
On paper, I agree with @clobrano, but I don't know how that looks in reality

**Comment by clobrano** [comment]
A little fuzzy is better than bold thick line where all our UI is thin. Small icons are different because of the size the fuzzyness is more visible. Also, I don't agree on the milky highlight, sorry

**Comment by Feichtmeier** [comment]
Then let's just leave the line at choose a neutral BG colour. The other user circles have a bg, too

**Comment by clobrano** [comment]
Otherwise, let's wait for the rest of the team to express its opinion? @ubuntujaggers was already not convinced by the border

**Comment by clobrano** [comment]
I changed my mind on the user icon border: 2px is actually ok

**Comment by ubuntujaggers** [comment]
I definitely prefer the border when there's a background :) It makes it look like a little badge. A glyph in a circle with background showing through feels a bit cheap-looking to me, but that might be a personal bias. It reminds me of when you're trying to draw something for a design and you can't, and then in desperation you stick a wingding or Unicode character in or something.

**Comment by Feichtmeier** [comment]
Alright, so bg + 1px border it is @ubuntujaggers ?

**Comment by ubuntujaggers** [comment]
I think my favourite so far is this which might be 2px border? https://github.com/ubuntu/yaru/issues/1342#issuecomment-491529137 Happy as always with majority verdict!

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/57613413-1a0b0a80-7577-11e9-8f1c-e2c92fbf081f.png)
This is a little bit darker slate and the 2px border

![image](https://user-images.githubusercontent.com/15329494/57613574-82f28280-7577-11e9-9304-5882a2862cbe.png)
That's slate

**Comment by clobrano** [comment]
I prefer the slate one

**Comment by Feichtmeier** [comment]
Okay that one is commited, and improved the insenstive effect a bit, I cant post a screenshot of this because you only see that effect for 1-2 secs after you log out and log in
