### ISSUE TITLE
Path bar style issues on light background

### ISSUE THREAD

**Issue by joshas** [ubuntu/yaru#1351]
## Expected Behavior
Path bar (HBox with .linked and .path-bar classes with RadioButtons inside it) styling should work on light backgrounds too. Text should remain legible.

## Actual Behavior
Yaru styles presume that path bar always will be on dark background and sets active item text color to white and inactive to light grey. Here's what I get with Yaru theme:
![yaru](https://user-images.githubusercontent.com/79141/57474913-ed67a200-729b-11e9-81fd-c94178ab8090.png)

And with Adwaita:
![adwaita](https://user-images.githubusercontent.com/79141/57474939-007a7200-729c-11e9-8ef2-2a9d12e823c6.png)

I know, that removing .path-bar class will fix issue on Yaru theme and won't have big difference on Adwaita, but I'd like to use .path-bar because other themes provide nicer custom styling to it: removing button boxes and displaying underline on hover.

## Steps to Reproduce the Problem

  1. Run this demo on Ubuntu 19.04: https://gist.github.com/joshas/43fcbf070c62ba163ac05b0353308a4c

## Specifications

Using Ubuntu 19.04 with latest updates. yaru-theme-gnome-shell version 19.04.2

**Comment by clobrano** [comment]
Hi @joshas, thanks for taking time to report this issue. 
Might ask you what is the reason to use a pathbar here? The widget looks like a buttonbox to me, more than a pathbar.

**Comment by joshas** [comment]
In my custom program I'm building pathbar-like element - breadcrumbs. Thought it would be nice to use style like in Nautilus, but it ended up on light background, as it is not placed in header bar.
Could Yaru theme set text colors only for known cases where path-bar appears on dark background (like Nautilus) and leave base path-bar style colors unchanged?

**Comment by clobrano** [comment]
Let me double check. We already have a dynamic pathbar in filechooser

**Comment by joshas** [comment]
Filechooser path-bar has very specific overrides: https://github.com/ubuntu/yaru/blob/31b2d808074be39913cb016b8bae18f53f2d4275/gtk/src/light/gtk-3.20/_common.scss#L3927

**Comment by clobrano** [comment]
I had time to double check and actually there's some work to be done. The path-bar used in Nautilus is `nautilus-path-bar` (and it is going to change a little in the future), while `path-bar` isn't/shouldn't be tied to the headerbar and dark background. I'll try to fix it :+1:

**Comment by clobrano** [comment]
The fix will be very easy after #1307 is merged, but the look and feel would really be the same as using `buttonbox` class in your application

![image](https://user-images.githubusercontent.com/2883614/57536077-bcdb4300-7343-11e9-8b97-5954b58852a7.png)

![image](https://user-images.githubusercontent.com/2883614/57536111-cd8bb900-7343-11e9-94cc-ab0fba41c60e.png)

**Comment by Feichtmeier** [comment]
I think, when you look into that app issue, they really want to have the pathbar widget because they use it as a pathbar
So we need some if/else for hbcolor and light/dark here

**Comment by clobrano** [comment]
I agree, we already have the code for pathbar. Currently is mixed up with Nautilus header bar, but, as said, that PR is merged, the separation will be easy. 
About the look and feel, if adwaita is fine, I think also our pathbar will be

**Comment by Feichtmeier** [comment]
Fixed with master upstream refresh
