### ISSUE TITLE
Minor changes for some Yaru icons

### ISSUE THREAD

**Issue by Night-Train-666** [ubuntu/yaru#1356]
Hi Guys,

I wanted to report some minor chan

ges to your theme.
(yaru-theme - 19.04.2+201905081934+31b2d80~ubuntu18.04.1 from your ppa https://launchpad.net/~communitheme/+archive/ubuntu/ppa on Ubuntu Desktop 18.04.2 LTS)

(see attached files in example.zip)

- Diodon (clipboard manager) - icon=diodon
 --> before applying yaru theme the icon was diodon-before.svg;
 --> after applying the yaru theme the icon changes to diodon-after.svg;
I believe the most elegant choice is diodon-before.svg.

- uGet (download manager) - icon=uget-icon
 --> the uGet icon is green;
 --> a fix in Trusty Tahr changed the icons to fit the panel;
I believe the most elegant choice is uget-fix.

- qpdfview (pdf document viewer) - icon=qpdfview
 --> the problem is in the display of the icons in the toolbar, more precisely they are not displayed correctly:
Open;
Save as;
Print.
(in the "Menu - File" also Save ...)
Obviously, before applying Yaru Theme, the visualization was correct.

Is it possible to intervene to correct?

Thank you so much

Antonio
[example.zip](https://github.com/ubuntu/yaru/files/3170224/example.zip)

**Comment by clobrano** [comment]
Hi @Night-Train-666,

thank you for taking time to contribute to Yaru!

As premise, in the future please open 1 discussion for each issue, instead that merging more issues in the same one.

There is a list of requests we make to help understand the problem, could you please reply?

- which version of Ubuntu
- how did you installed Yaru: did you get it with 19.04, installed from snap (e.g. in 18.04) or from source?

Moreover, what do you mean by "after applying yaru"? Does it mean that on gnome-session the issue is not reproducible?

Thanks a lot

**Comment by Night-Train-666** [comment]
Hi clobrano,

first of all thanks to you for having responded.

By "after applying yaru" I mean that I install ubuntu 18.04, add your ppa, and with Gnome Tweak I select Yaru for icons and applications.

Generally, I prefer to use PPAs when available.
In the first installation of Bionic Beaver I had installed the Communitheme via Snap, but when I restored the pc I added the ppa, so I had the same result without having to choose a session ... at least I think I get the same result.

**Comment by clobrano** [comment]
> so I had the same result without having to choose a session

The session is part of the Yaru theme and it doesn't depend on how you install it. Without choosing Yaru session you might have a partially working theme, at least in the Shell part.

The problems you are facing are probably similar to #1294, at least for qpdfview

**Comment by Night-Train-666** [comment]
I have completely removed the packages from the ppa:
yaru-theme-gnome-shell
yaru-theme-gtk
yaru-theme-icon
yaru-theme-sound
gnome-shell-theme-communitheme
gtk-theme-communitheme
icon-theme-communitheme
sound-theme-communitheme

Then I installed the snap:
sudo snap install communitheme --edge

I rebooted the PC and chose the Communitheme session.

In fact the graphic of the environment has changed, now it is the same as your screenshots, but to change the theme for applications and icons I had to intervene through Gnome Tweaks choosing Communitheme for both.

What I've noticed is that the windows opened as an administrator (Nautilus, Gedit, Synaptic, etc.) keep the Adwaita theme for the window, regardless of the theme choices for applications and icons (which change regularly).

The font for the window title is "Ubuntu" 11 in bold by default, but Gedit, Gnome Tweaks and the top bar don't have bold.

Nothing unbearable, apart from the background of the notifications, the window for the administrator password request and ending session / restart / shutdown, which are now clear but which are more elegant darker as before ... IMHO.

I also tried to launch the commands:
sudo snap refresh communitheme --edge
is
sudo snap refresh gtk-common-themes --edge
(which was not installed)
but nothing has changed.

The things reported in the first post remained the same.

As for qpdfview, I will try to report the problem to the developer.

Thank you

**Comment by clobrano** [comment]
Thanks for trying and reporting this.

About the trayicons, Yaru does not explicitly select one icon or another. I'll try to dig into this more, but I suggest you to contact the developers to have a faster response. If it's in our power, will try to do something.

> What I've noticed is that the windows opened as an administrator (Nautilus, Gedit, Synaptic, etc.) keep the Adwaita theme for the window, regardless of the theme choices for applications and icons (which change regularly).

This is a known problem with the snap system

> The font for the window title is "Ubuntu" 11 in bold by default, but Gedit, Gnome Tweaks and the top bar don't have bold.

In my system, font for windows title is called "legacy windows title", which let me think that newer applications won't change accordingly, but I might be wrong here. Yaru sets the title font non-bold explicitly, so this is probably the reason (and as said above, there is probably no API in place to change that)

**Comment by Feichtmeier** [comment]
I think nothing about those issues was caused by the yaru gtk, shell and icon theme.
The sizing of icons could have happened because of the gnome extension "appindicator".
