### ISSUE TITLE
1px gap in gnome control center sidebar

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1363]
There is a 1px gap between the row right side and the edge of the sidebar in Yaru

Yaru:
![image](https://user-images.githubusercontent.com/15329494/57707170-70f00d00-7667-11e9-9b28-a8a571086cef.png)

Adwaita:
![image](https://user-images.githubusercontent.com/15329494/57707202-7f3e2900-7667-11e9-8459-c1dfb720eae3.png)

Maybe I introduced this with that hdyleaflet stuff... maybe not.
It is not happening in nautilus or tweaks
@clobrano  any idea?

**Comment by clobrano** [comment]
I'll look into it

**Comment by clobrano** [comment]
I have no gap, are you using master?

![image](https://user-images.githubusercontent.com/2883614/57755568-84e05100-76f1-11e9-8e00-95316ea3418d.png)

**Comment by Feichtmeier** [comment]
Okay that is strange. Yes master. (Not "yes, my master!" XD)

I guess it has something to do with my disco installation. 
I check what version I use and if I updated from beta or sth

**Comment by Feichtmeier** [comment]
Hm it also happens on my other VM Which I installed from the disco release image:

![Screenshot from 2019-05-17 13-46-39](https://user-images.githubusercontent.com/15329494/57925989-5659a600-78aa-11e9-9a84-d37886a9f960.png)

**Comment by clobrano** [comment]
Even weirder, I was testing on 18.04 from source, but on 19.04 I confirm the issue, so - again - I'll have a look :D
