### ISSUE TITLE
Create ubuntu/disco branch

### ISSUE THREAD

**Issue by iainlane** [ubuntu/yaru#1370]
I can't do this by a PR because it's about making a new branch, sadly.

We need to release an update to disco, mainly to fix [LP: #1829699](https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1829699). In my fork I've [made an `ubuntu/disco` branch](https://github.com/iainlane/yaru/tree/ubuntu/disco).

  * Can this branch be merged into the main repository? (Check the name; it can be updated if necessary, just use `git rebase -i` to amend d1fedef226ebe323e398d6019e423d3a59b6050a).
  * Are there any further *bug fix* changes that could be included in the stable update?
    * If so, after the branch is pushed here, cherry pick PRs can be opened in the normal way.
    * They will each need a Launchpad bug (open one if it doesn't exist).

@clobrano @Feichtmeier @3v1n0

**Comment by Feichtmeier** [comment]
This comes to my mind, since it is not a design change and tagger rather a fix of unreadable text:
https://github.com/ubuntu/yaru/pull/1335
I update this post of I find more

**Comment by iainlane** [comment]
@Feichtmeier please push my branch as a *new branch* to the yaru repository. something like

```
  $ git remote add laney git@github.com:iainlane/yaru.git --fetch
  $ git checkout -b ubuntu/disco remotes/laney/ubuntu/disco
  $ git push --dry-run origin ubuntu/disco # check this is doing the right thing (making a new branch)
  $ git push origin ubuntu/disco
```

and then there will be a new branch here that you can open PRs against, e.g. by:

```
  $ git checkout ubuntu/disco # if not on it already
  $ git cherry-pick -x c84d0ba
  $ git push <somewhere> ubuntu/disco
  < use the github UI to open a PR with the target of ubuntu/disco >
```

**Comment by clobrano** [comment]
Other fixes

- #1368 
- #1282  

less sure the following can be considered bug fixes
- #1302

**Comment by Feichtmeier** [comment]
@iainlane https://github.com/ubuntu/yaru/tree/ubuntu/disco
Worked except me not using ssh for git so i needed to use the https url 
But the PR doesn't make much sense since I could already push into this branch after the cherry-pick
I hope this is what you meant, thanks for the instructions!

**Comment by iainlane** [comment]
thx, doing a PR makes sense or not depending on whether fixes to this branch need to be reviewed (project policy)

**Comment by Feichtmeier** [comment]
Ah, okay sorry didn't get that! :D
I meant "sense to me"

**Comment by iainlane** [comment]
Let's include Carlo's fixes by PRs and then look to release this. I think this issue can be closed.

**Comment by iainlane** [comment]
@clobrano as far as I can see #1282 is in disco already

```
laney@disco (ubuntu/disco|✔)> git tag --contains e163bf9e0                                                                                                 
19.04.2
```
