### ISSUE TITLE
Missing icon: wine

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1371]
![image_2019-05-22_11-32-13](https://user-images.githubusercontent.com/15329494/58165800-c8eecb00-7c88-11e9-880f-8f52c0e80ccd.png)

Named "wine windows program loader"
which is actually the only of the many wine links that successfully opens the apps :)

**Comment by Feichtmeier** [comment]
And we really need to do something about the menu padding. For some reason it is completely asymmetrical (left much more space than right)

**Comment by eaglersdeveloper** [comment]
A little offtopic.
See what I found: https://stopthemingmy.app

![Screenshot_2019-05-22-16-13-11~01](https://user-images.githubusercontent.com/40228953/58173586-cbfbb280-7cac-11e9-93e5-6d5466c795f0.png)

**Comment by Feichtmeier** [comment]
Yeah... Just a little...

**Comment by madsrh** [comment]
Do you know where this icon is stored @Feichtmeier ?

**Comment by Feichtmeier** [comment]
Nooo why did you tag me into this issue :cry: No I see how awesome the flat headerbar looked!!!! Stop!!! :laughing: 

I'll check at home :)

**Comment by Feichtmeier** [comment]
Confirmed to be still valid.

**Comment by Feichtmeier** [comment]
Papirus provides this icon:
![grafik](https://user-images.githubusercontent.com/15329494/95437297-1d194e80-0955-11eb-8a58-d8a564ca5c58.png)

and it looks like this icon is just called
"wine" inside "apps"

**Comment by Jupiter007-43** [comment]
A proposal icon:

![Capture d’écran du 2020-10-09 18-30-22](https://user-images.githubusercontent.com/36476595/95608916-27733f80-0a5e-11eb-9464-fc247997283e.png)
![Capture d’écran de 2020-10-09 18-34-47](https://user-images.githubusercontent.com/36476595/95608975-3fe35a00-0a5e-11eb-8012-18f9fd022c4b.png)

**Comment by Feichtmeier** [comment]
Wow that's really nice
