### ISSUE TITLE
Icons for application/x-java-archive and application/x-java is same. 

### ISSUE THREAD

**Issue by the1derer** [ubuntu/yaru#1374]
## Icon Request

If you're filing an issue for a missing icon provide the following in your request:

Request to Change file icon type for 'Java-Archive(jar)' files.
Icons for 'application/x-java' and 'application/x-java-archive' files and same. It would be better if 'application/x-java-archive' have some kind of differentiation to indicate it is an archive.

Thanks!

**Comment by madsrh** [comment]
How about something like this? Perhaps without the text since non of the other archives have text? @ubuntujaggers WDYT?

![test2](https://user-images.githubusercontent.com/3986894/71562850-20cd8b80-2a3b-11ea-80f8-a57a691f7e3d.png)

**Comment by Feichtmeier** [comment]
Looks good!
Can you make a PR? :D

**Comment by ubuntujaggers** [comment]
Seconded!

**Comment by Feichtmeier** [comment]
Copied from the PR:

One thing, as a java dev IRL, that bums me is that you can not say from the icon that it is related to java.
There are java archives but there are also java archive you can run as an "app" (java -jar filename)
So it would be neat if you could get the java glyph somehow inside the icon 🙈
