### ISSUE TITLE
Disable backdrop dim

### ISSUE THREAD

**Issue by lol768** [ubuntu/yaru#1375]
Is it possible to disable the functionality whereby inactive windows are dimmed?

I use two monitors with the LHS monitor often displaying rendered TeX documents. Really not a fan of this behaviour, it makes the documents grey instead of white and hard to read.

-----

c.f.

![image](https://user-images.githubusercontent.com/2552726/58385463-e4d7d100-7fe8-11e9-93b9-d2c8b471b817.png)

![image](https://user-images.githubusercontent.com/2552726/58385461-dbe6ff80-7fe8-11e9-817e-e143e0c89c64.png)

**Comment by clobrano** [comment]
Hi @lol768, 
"backdrop" effect is important to show which app is in focus, but it shouldn't make the dimmed window hard to read. I'll look if the grey color for text is something Yaru can make better or it is hard coded into the pdf viewer

**Comment by lol768** [comment]
So is this an issue with evince?

**Comment by clobrano** [comment]
No, it seems Yaru does this only in its dark variant. I believe that Evince is taking some color from Yaru palette that in the light variant is white and in the dark one is gray. I'll look into it

**Comment by Feichtmeier** [comment]
Yeah our backdrop has something weird to it.
I lutris the buttons in the scrolled window become transparent in the backdrop
And the headerbar border becomes blurry

**Comment by Feichtmeier** [comment]
@lol768 are you using bionic, 19.04 or did you built from master?
If the latter, could you check if this is still relevant after you pulled the latest changes in master?

**Comment by clobrano** [comment]
I tried with master, the backdrop dim is barely noticeable now, if you all agree, we can close this

**Comment by lol768** [comment]
I'll try with latest `master` when I get home - thanks both

**Comment by adee** [comment]
The concept of the backdrop effect relies on the assumption that the user can focus more easily on the active app if all other windows are visibly different/desaturated. This assumption is wrong, unfortunately. It breaks down in multi-monitor situations. I routinely use multiple external monitors with fullscreen VMs. There you have more than one window active to the user's focus (glance over the other monitors). It's incredibly distracting to see those VM windows change color on window focus change (and bring the same readability issues outlined here). It's not an accident that Adwaita doesn't do this.

**Comment by Feichtmeier** [comment]
Since we use 100% backdrop from upstream now, I think this is the wrong place to discuss about this now. Previously we had our own backdrop mixins but not anymore. So please wait for the next Ubuntu release to see the upstream backdrop with Ubuntu colours.
