### ISSUE TITLE
Hdyleaflet selection mode not styled

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1380]
![image](https://user-images.githubusercontent.com/15329494/58616799-dcb8b380-82be-11e9-87a2-06ecf649fd97.png)

We need to dig more into that hdyleaflet stuff and check how adwaita does it, since more and more gnome apps are going to have that desktop/mobile interface

**Comment by madsrh** [comment]
Off-topic: can anything be done about that avatar?

**Comment by Feichtmeier** [comment]
I hope xD can't say right now but I'm optimistic!

**Comment by Feichtmeier** [comment]
I think we only have to add
hdyleaflet titlebar 
to the selection mode styling we have currently
It's one more container on top

**Comment by Feichtmeier** [comment]
Fixed with master upstream refresh, not relevant for bionic
