### ISSUE TITLE
The window title doesn't look like a title.

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1381]
I don't know about you, but I often confuse the title with menu buttons because of the regular weight. For me, middle weight was better. Again, opinions may differ.

![Снимок экрана в 2019-05-31 13-09-25](https://user-images.githubusercontent.com/40228953/58695005-5c20b280-83a5-11e9-94ab-fe5516791a5f.png)

**Comment by clobrano** [comment]
I see your point, at least regarding those windows that still have menubar

**Comment by eaglersdeveloper** [comment]
We will fix this problem?

**Comment by ubuntujaggers** [comment]
Tbh I think I slightly prefer the old bold titles too.  No strong feeling though.

**Comment by Feichtmeier** [comment]
Okay we can revert it :) This way or... the other ;)

**Comment by fitojb** [comment]
The fact that the “classic” decoration is too tall also contributes to the window title looking like a label… the title bar should be thin as in old Ambiance.

**Comment by clobrano** [comment]
If it were thinner it wouldn't have enough space for the same control buttons (minimize, close, etc.) we have in headerbars. While if the control buttons where smaller, they would look too small inside the headerbar.

**Comment by clobrano** [comment]
Fixed by latest rebase
