### ISSUE TITLE
Invisible toolbar with Yaru theme (light) in Ubuntu 19.04

### ISSUE THREAD

**Issue by SenaidaHdez** [ubuntu/yaru#1383]
## Expected Behavior

I recently updated to Ubuntu 19-04 and I encounteer problems with the toolbar in different applications, such as Skype or Atom. I would expect the applications toolbar appear okey, regardless of the application.

## Actual Behavior

The particular problem is that the color for toolbar text and background are the same colour. Due to this I cannot actually see the toolbar.
I know the problem is Yaru, because it gets solved by changing the theme. However, I do like the theme.

## Steps to Reproduce the Problem

  1. Have an Ubuntu 19.04 with default settings and Yaru theme for applications.
  2. Install Skype or Atom.
  3. Open the application.

## Specifications

It was installed by default in Ubuntu 19.04

Software that presents the issue:
- Name: Ubuntu
- Version: 19.04

![atom_invisible_toolbar_1](https://user-images.githubusercontent.com/26250834/58704938-aa20c080-837b-11e9-882e-d76c69b08b39.png)
![atom_invisible_toolbar_2](https://user-images.githubusercontent.com/26250834/58704941-abea8400-837b-11e9-853d-1972c8b3f816.png)
![skype_invisible_toolbar](https://user-images.githubusercontent.com/26250834/58704949-b278fb80-837b-11e9-8317-fc62fb6749ca.png)

**Comment by Feichtmeier** [comment]
That's an old electron bug and should be fixed with newer versions
In vscode you don't have this problem

**Comment by madsrh** [comment]
Can we close this issue if there's already a fix?

**Comment by Feichtmeier** [comment]
I think we can :(
Ofc I'd like to help @SenaidaHdez but I think from our side everything is fine.
It is an electron bug and atom is build with electron. Newer versions of electron have this fixed, test vscode for example and thanks for opening issues
