### ISSUE TITLE
Nemo issues

### ISSUE THREAD

**Issue by DragoCubed** [ubuntu/yaru#1389]
## Expected Behavior

When an item on the left is highlighted by the keyboard, there shouldn't be a weird outline.

The active tab in the breadcrumb navigation shouldn't have white text on a white background

## Actual Behavior

The active item on the left has a weird outline

The active tab in the breadcrumb navigation has white text on a white background
![nemo yaru](https://user-images.githubusercontent.com/39782755/58957893-0143ec80-87e5-11e9-958b-9484980b6468.png)

I opened Gnome Tweaks and tested Adwaita and there were no issues there.

Edit: to clarify, I added a white box over my name 

## Steps to Reproduce the Problem

  1. Launch Nemo
  2. Double click on a folder like Desktop

## Specifications

Software that presents the issue:
- Name: Ubuntu 19.04
- Version: Not sure but software updater doesn't show any updates

**Comment by clobrano** [comment]
Hi @DragoCubed, 

thanks for reporting this issue, I just edited the message to highlight the actual content.

Is your system a clean Ubuntu 19.04 install? Yaru comes preinstalled with 19.04, you shouldn't need to installing it via store.

**Comment by DragoCubed** [comment]
Thank you for editing it! 

Yep. It's a clean install. I did install Chrome and GIMP as well. They wouldn't affect Yaru, right?

It's awesome to see the path bar box issue fixed! I feel stupid for calling it a breadcrumb.

**Comment by clobrano** [comment]
Pathbar fixed in latest master

![image](https://user-images.githubusercontent.com/2883614/59555031-b11b1600-8fac-11e9-8df0-cc3eae53c40d.png)

**Comment by Feichtmeier** [comment]
Maybe because of the grey selected row?
