### ISSUE TITLE
Chromium dark with Yaru dark: ugly white line 

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1390]
## Actual Behavior

There is a weird white line when using chromium in dark mode and yaru dark:

![image](https://user-images.githubusercontent.com/2845433/59059575-ad351880-8875-11e9-8ffa-6097727f83ac.png)

## Expected Behavior

No white line there, I assume this is not intentional.

## Steps to Reproduce the Problem

  1. Install chromium 74.0.3729.169 from the ubuntu repos.
  2. Set yaru dark theme from Tweaks.
  3. Launch chromium with `--force-dark-mode --enable-features=WebUIDarkMode` (chromium must be using the gtk theme, of course)

## Software that presents the issue:

- Name: chromium  
- Version: 74.0.3729.169

## Additional observations

This isn't happening with Adwaita dark nor with Materia dark.

**Comment by memeplex** [comment]
I think this has to do with the fact that the Ubuntu Chromium package sets "Show bookmarks bar" to false. I had tested Materia and Adwaita in Arch, so that might be the reason this artifact wasn't showing there. This doesn't seem to be a problem in Yaru, the other themes show the same white line when setting "Show bookmarks bar" to false. So I'm closing the issue.

**Comment by clobrano** [comment]
hey @memeplex, thank you so much for analysis and testing!

**Comment by memeplex** [comment]
When I closed this I was in the "new tab" window so I toggled the "show bookmarks bar" and the only effect was to remove the ugly artifact. But it clearly isn't a solution because that shows the bookmarks bar globally, I shouldn't have closed the report. So, even if this is happening with other themes, you probably would like to fix it in Yaru-dark if that's possible. Or at least to diagnose the cause.

**Comment by Feichtmeier** [comment]
Could you show picture of adwaita dark?

**Comment by DragoCubed** [comment]
IIRC Chrome 75 now makes the bookmark bar look the same as when shown everywhere. It's a terrible change on Google's part but may solve this I guess?

**Comment by Feichtmeier** [comment]
@memeplex could you test this with recent master?

**Comment by clobrano** [comment]
Tested with current master, I don't see the white line anymore, if @memeplex can confirm, we can close this.

**Comment by memeplex** [comment]
It works for me, thanks!
