### ISSUE TITLE
Selecting folders makes emblems indistinguishable 

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1395]
## Expected Behavior

Distinctive folder emblems shouldn't be obfuscated by the theme, specially for folders selected for action.  

## Actual Behavior

It's very difficult to spot the emblem of selected folders. I've tested this using both Yaru and Papirus icon sets.

![image](https://user-images.githubusercontent.com/2845433/59150696-f021f800-89fd-11e9-9633-9afd92396b3c.png)

## Steps to Reproduce the Problem

  1. Open Nautilus
  1. Go to you Home directory
  1. Select a couple of special xdg folders there

## Specifications

- Name: Ubuntu
- Version: 19.04

**Comment by memeplex** [comment]
As a more general observation I would say that the color is too dark orange and plays really bad with non-orange icons (for example, default Papirus folders are blue and selected folders look more like "disabled" folders). By highlighting the text of selected folders but leaving the icon alone (or slightly modifying the color) you will both make emblems visible and better behave with other icon sets.

**Comment by Feichtmeier** [comment]
We could insert more app styling for nautilus or rather ask on the gitlab repo for a change. I did so some months ago and it's still opened. Cant find the look to the issue right now but I'll attach it here when I find it

**Comment by memeplex** [comment]
I see @Feichtmeier . Still, don't you think lowering a bit the "oranginess" of the selection would improve contrast and also make things look better, consider this:

![image](https://user-images.githubusercontent.com/2845433/59168273-809a2e80-8b0b-11e9-803c-c21f4b777a28.png)

I like the personality of Yaru but I find this too much, don't you?

**Comment by Feichtmeier** [comment]
We modified nautilus in bionic do only the label is selected. That's not possible anymore since cosmic sadly.

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/59185840-bb36b200-8b71-11e9-96ce-cc1a47ba2dd6.png)
That's bionic - nice isn't it? Sadly we did not manage to reproduce this fix for cosmic and disco
So I opened this issue:
https://gitlab.gnome.org/GNOME/nautilus/issues/786
