### ISSUE TITLE
Adwaita/Yaru: allow to change shell theme disregarding the session type

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1398]
## Expected and Actual Behavior

In an ubuntu session the default shell theme is Yaru. In a vanilla gnome session the default shell theme is Adwaita. In both cases, there is no way to pick the other shell theme. Of course, I agree with the defaults, but arguably one might be interested in using Yaru in a vanilla gnome session and viceversa. Plus, the ability to change the gtk theme to Adwaita in an ubuntu session is crippled by the inability to also change the shell theme in a consistent way (and viceversa).

## Steps to Reproduce the Problem

  1. Login in an Ubuntu session
  1. Open Tweaks
  1. In the Appearance section try to select Adwaita

**Comment by memeplex** [comment]
I assume this is more of a packaging issue. Please let me know if I should report this to ubuntu launchpad instead.

**Comment by Feichtmeier** [comment]
This is really the wrong place for such a wish
Please open this on launchpad

**Comment by memeplex** [comment]
Ok, thanks for letting me know, here it is with a suggested simple fix (creating a couple of symlinks): https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1832137
