### ISSUE TITLE
Buttons become transparent in backdrop

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1402]
![grafik](https://user-images.githubusercontent.com/15329494/59200372-593d7300-8b98-11e9-8cd7-f7703ed753f9.png)

Does not happen with adwaita
![grafik](https://user-images.githubusercontent.com/15329494/59200411-707c6080-8b98-11e9-8b9b-f7068464c8a5.png)

**Comment by clobrano** [comment]
Do you mean this buttons here?

![image](https://user-images.githubusercontent.com/2883614/59269929-76357d00-8c50-11e9-8f6b-868da4fcc9c0.png)

If they are "insensitive", the drawing section should be "backdrop-insensitive", not just "insensitive", so the code applied should be this one

https://github.com/ubuntu/yaru/blob/67cd850a5d83d2d6340d7c85e57b59424b401d28/gtk/src/light/gtk-3.20/_drawing.scss#L456

Does transparency look like a bug?

**Comment by Feichtmeier** [comment]
No they are not insensitive. I could press that button and it would start the game. Did you mean this?

**Comment by clobrano** [comment]
Ah OK, so I don't get why you think that this line should affect the transparency

https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.20/_drawing.scss#L329

This section is for "insensitive" buttons (not in backdrop). Normal buttons in backdrop are styled with this https://github.com/ubuntu/yaru/blob/67cd850a5d83d2d6340d7c85e57b59424b401d28/gtk/src/light/gtk-3.20/_drawing.scss#L384

**Comment by Feichtmeier** [comment]
Oh sorry. /selffacepalm
I'll update the OP

**Comment by clobrano** [comment]
No problem, but my main question is "do you think this is a bug?". I can see it as a style choice, as long as it's consistent.

**Comment by Feichtmeier** [comment]
I never saw a transparent button before in the light theme. So I consider it to be not wanted. But I could be totally wrong :D

**Comment by clobrano** [comment]
They might be all transparent, but nowhere there's a picture behind them to show it :D

**Comment by fitojb** [comment]
The semitransparency doesn’t necessarily look wrong to me…
