### ISSUE TITLE
Create symbolic app-indicators for common apps

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1404]
## Expected Behavior

Appindicators for common applications look consistent (in style, size, shape and colors) with the rest of the top bar.

## Actual Behavior

Compare insync and qbittorrent in papirus:

![image](https://user-images.githubusercontent.com/2845433/59320586-4c5a7580-8ca5-11e9-854c-5192a0b4050e.png)

With this mess of shapes, sizes and colors in yaru:

![image](https://user-images.githubusercontent.com/2845433/59320633-6f852500-8ca5-11e9-8611-3ec9eb50384a.png)

## Steps to Reproduce the Problem

  1. Install qbittorrent and run.
  1. Install insync and run.
 
## Icon Request

Look for panel icons here:

insync: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/search?q=insync&unscoped_q=insync

qbittorrent: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/search?q=qbittorrent&unscoped_q=qbittorrent

**Comment by Feichtmeier** [comment]
I agree that the size is an issue
But it's caused by wrong sizing in the Ubuntu app indicator extension
Would be great if you could open an issue on their repo

About Yaru providing third party icons: only if we have the explicit OK by the app devs we can do it
