### ISSUE TITLE
Missing selected item on listbox in popover

### ISSUE THREAD

**Issue by Exalm** [ubuntu/yaru#1406]
## Expected Behavior

![Screenshot from 2019-06-12 03-41-32](https://user-images.githubusercontent.com/1510457/59338257-979a7580-8cf1-11e9-81f2-1f87f4f72979.png)

## Actual Behavior

![Screenshot from 2019-06-12 03-41-43](https://user-images.githubusercontent.com/1510457/59338271-9cf7c000-8cf1-11e9-9008-19685dd1d11f.png)

![Screenshot from 2019-06-12 03-41-46](https://user-images.githubusercontent.com/1510457/59338287-a1bc7400-8cf1-11e9-9c98-d0d036a2a259.png)

The item only has selected color in backdrop window.

## Steps to Reproduce the Problem

  1. Run a Nintendo DS game in GNOME Games
  2. Open screen layout selector popover

## Specifications

The version: whatever `org.gtk.Gtk3theme.Yaru` is on Flathub.

The widget layout: https://gitlab.gnome.org/GNOME/gnome-games/blob/master/plugins/nintendo-ds/data/ui/nintendo-ds-layout-switcher.ui https://gitlab.gnome.org/GNOME/gnome-games/blob/master/plugins/nintendo-ds/data/ui/nintendo-ds-layout-item.ui

Some more details: 

Software that presents the issue:
- Name: gnome-games
- Version: nightly builds

**Comment by clobrano** [comment]
Hi @Exalm, thanks a lot!

**Comment by clobrano** [comment]
> The version: whatever org.gtk.Gtk3theme.Yaru is on Flathub.

From the pictures, it looks like the app forces the dark version, is that so?

**Comment by Exalm** [comment]
> From the pictures, it looks like the app forces the dark version, is that so?

Yes.

**Comment by clobrano** [comment]
Alright, so we have a problem. The flathub repo is https://github.com/flathub/org.gtk.Gtk3theme.Yaru-dark and the maintainer is vanished. There is also an old PR still waiting to be accepted

**Comment by Exalm** [comment]
No, it's not. I don't have `org.gtk.Gtk3theme.Yaru-dark` here, it's `org.gtk.Gtk3theme.Yaru`, dark variant.

**Comment by clobrano** [comment]
Okay, so, my understanding of flatpak-ed applications is that `org.gtk.Gtk3theme.Yaru-dark` should be picked up. I don't understand how `org.gtk.Gtk3theme.Yaru` could serve the dark variant (and this might even be the actual problem, since Yaru is the light variant).

I do have to update `org.gtk.Gtk3theme.Yaru` as well (this is my fault), but I expect `org.gtk.Gtk3theme.Yaru-dark` to be used here

**Comment by Exalm** [comment]
>  I don't understand how org.gtk.Gtk3theme.Yaru could serve the dark variant

`gtk-dark.css`.

**Comment by clobrano** [comment]
Is it the same for Adwaita? Is it not Adwayta-dark used in case of prefer dark theme is true?

**Comment by Exalm** [comment]
Of course. In fact, dark variants existed long before Adwaita-dark.

**Comment by clobrano** [comment]
I see, thanks then

**Comment by Exalm** [comment]
https://developer.gnome.org/gtk3/3.2/GtkSettings.html#GtkSettings--gtk-application-prefer-dark-theme

**Comment by Feichtmeier** [comment]
It's the jet popover wildcard :/
Which doesn't hit the backdrop, thus selection works there

**Comment by Feichtmeier** [comment]
Hey @Exalm I do not have any Nitendo game isos? at hand
Could you be so kind and try this branch?
https://github.com/ubuntu/yaru/tree/GtkTheme_killjetpopovers
Or give me a tip how to fake a nintendo game?

**Comment by Exalm** [comment]
@Feichtmeier https://www.zophar.net/pdroms/nintendods.html there are some public domain roms here. For example, https://www.zophar.net/pdroms/nintendods/powder-107.html run the .nds file there with the app.

**Comment by Feichtmeier** [comment]
@Exalm thanks for the link
any other thing i need to install?
![grafik](https://user-images.githubusercontent.com/15329494/59366146-1c10e680-8d3a-11e9-95b8-51efc9ff53b6.png)
![grafik](https://user-images.githubusercontent.com/15329494/59366178-292dd580-8d3a-11e9-914f-d5fc737d97f8.png)

**Comment by Exalm** [comment]
Ah, I guess Ubuntu doesn't package the necessary core? We only recommend to use flatpak, and the switcher was added after 3.32 anyway, so use https://gitlab.gnome.org/GNOME/gnome-games/-/jobs/320528/artifacts/raw/gnome-games-git.flatpak

**Comment by Feichtmeier** [comment]
right! flatpak :S But okay - I am installing that

**Comment by Exalm** [comment]
Well, you can build the latest retro-gtk, libmanette, libhandy and gnome-games on Ubuntu without Flatpak. If desmume2015 core is packaged, it will work. If not, then not :p

Not having the cores is one of the reason we only support Flatpak. Ubuntu does build some of them, but not all of them, and doesn't include metadaat for some, so it's really a guesswork if a particular platform works or not, while with Flatpak we just bundle the well-working cores and can be sure that the games run out of the box.

**Comment by Feichtmeier** [comment]
how can I switch the channel to nightly/edge? my god cant't you make a snap? :dancer:

**Comment by Exalm** [comment]
See the link above, that is the current master branch bundle. You should be able to just install that file.

**Comment by Feichtmeier** [comment]
@Exalm please test it if you have time, should be fixed now
