### ISSUE TITLE
[Question] How are Yaru and upstream Adwaita related/coordinated?

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1409]
After seeing there are upstream checkouts in Yaru's repo, both for gtk and gnome-shell, I was curious about the development/building model you're following, but was unable to infer anything more than "they were checked out at the beginning and that's all" from your building files. Nevertheless, the gnome-shell upstream directory was updated 25 days ago, so I'm really intrigued and confused about that. Are you working in a "diff" branch? How do you keep track of updates in Adwaita after having heavily patched its sources? Thanks in advance for any detail.

**Comment by Feichtmeier** [comment]
We currently manually add changes from both gtk and upstream to our yaru master. Feature updates and bugfixes.
Next shell rebase will be after I finished the shell refresh upstream here https://gitlab.gnome.org/frederik.feichtmeier/gnome-shell/commits/wip/frederik/lightshell
Gtk is currently being discussed in "private"

Thanks for your contribution but please try to open such questions on the community hub
