### ISSUE TITLE
Login screen: Ubuntu logo not quite centred relative to login entry box

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1413]
Just a minor issue - can't screenshot because it's not in the actual desktop environment!

**Comment by clobrano** [comment]
phone pic? :smile:

**Comment by Feichtmeier** [comment]
I Can't really confirm this. But if it's real it could be fixed in the shell theme I think

**Comment by Feichtmeier** [comment]
Closing after discussion on telegram :)
