### ISSUE TITLE
Color of Location of Pointer is hardly seeable in dark theme

### ISSUE THREAD

**Issue by j3ypi** [ubuntu/yaru#1417]
The _Location of Pointer_ when you press `crtl` after enabling this feature in gnome-tweaks is colored black in both the light and the dark version of the theme making it rather difficult to see it in the dark version. 

I think it would be better to color it orange like in the Ambiance theme. 

I use communitheme on 18.04.02.

**Comment by clobrano** [comment]
Hi @j3ypi, thank you for contributing!
I didn't see anything referencing this widget so far and also Adwaita-dark has the same black color, but we'll have a look

**Comment by clobrano** [comment]
I believe this come from upstream, even if on Fedora 30 pointer location doesn't seem to work, but in 19.10 pointer location is orange and so visible in dark variant too :)
