### ISSUE TITLE
Buttons change size on click

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#1419]
Ubuntu 18.04, Yaru from snap stable.

Just noticed in Files when copying images. When I try to copy the same image, the confirmation dialog appears. After pressing "Pomiń" (Skip), all the buttons change their size. 
Screenshots before and after pressing left mouse button:
![button-resize](https://user-images.githubusercontent.com/1629120/60021987-e39ed000-968a-11e9-88df-deba61598c97.png)

**Comment by Feichtmeier** [comment]
Thanks for reporting, I'll see if we can do anything for this for bionic

**Comment by Feichtmeier** [comment]
@mivoligo before I invest time in this, this does not happen with Adwaita or Ambiance in 18.04, right?

**Comment by mivoligo** [comment]
@Feichtmeier I've just tested with Adwaita and it looks like it also have this strange behavior:
 https://youtu.be/HbTGZlGeCqg

**Comment by clobrano** [comment]
This is different then. If Adwaita is affected, the bug is to be reported upstream, probably in Nautilus (Files) first

**Comment by mivoligo** [comment]
That's right. Sorry for the troubles,

**Comment by Feichtmeier** [comment]
Np! Thanks for checking back! I think this is rather some Gtk thing then! Best regards
