### ISSUE TITLE
Shell theme: gnome-screenshot area to grab not highlighted

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#1420]
## Expected Behavior

When taking a screenshot of an area of the screen using gnome-screenshot, the area being selected should be highlighted. Here is a gif of taking a screenshot when using the default gnome shell theme:

![gnome-screenshot-default](https://user-images.githubusercontent.com/1044087/60178251-0810be80-97e9-11e9-8907-9897eab33882.gif)

## Actual Behavior

When using the Yaru gnome shell theme (via logging into a Yaru session from GDM), the area is not highlighted:

![gnome-screenshot-yaru](https://user-images.githubusercontent.com/1044087/60178282-1b238e80-97e9-11e9-8be8-9cbcc356f726.gif)

## Steps to Reproduce the Problem

  1. Run gnome-screenshot (`gnome-screenshot -i` from a terminal)
  2. Choose "select area to grab" and click "take screenshot:
  3. Click and drag an area of the screen to screenshot

## Specifications

I'm on Arch Linux, fully updated, with gnome-shell 3.32.2. This issue did not occur in the past, and may have started to occur with the release of gnome 3.32, though I am not sure.

I have Yaru 19.04.2, [installed via the Arch Linux AUR](https://aur.archlinux.org/packages/yaru-gnome-shell-theme/). I'm using Xorg, but verified that the same issue occurs on Wayland.

Software that presents the issue:
- Name: gnome-screenshot
- Version: 3.32

# Other information

The same issue has been seen by a Manjaro user, described here:

https://gitlab.gnome.org/GNOME/gnome-screenshot/issues/35

It looks like it was caused in that case by a custom GDM theme. May or may not be a clue for the cause in the case of the Yaru gnome-shell theme.

**Comment by clobrano** [comment]
Hi @chrisjbillington,

I cannot reproduce this in Ubuntu 19.04, at least with Yaru installed from source.

**Comment by chrisjbillington** [comment]
Ah, I should have tested with master before reporting the bug.

This does not appear to be an issue on master, it must have been fixed already since the last released version.

Apologies for the time wastage!

**Comment by clobrano** [comment]
This is great, thanks for testing!
