### ISSUE TITLE
Logout sound

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#1421]
## Expected Behavior

Hoping for a logout sound

## Actual Behavior

No logout sound

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

    `$ snap info communitheme`

I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`
50:/usr/share/themes/Yaru$ git describe
fatal: not a git repository (or any of the parent directories): .git

I used the commands from contribuding.md and built the theme on 18.04. I use " Yaru session " while login. Everything works fine for me.

Software that presents the issue:
- Name: Ubuntu
- Version: 18.04

Thanks!

**Comment by clobrano** [comment]
Looking for some info (and mostly here https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/214370) it seems that the feature has been removed from GNOME itself.

**Comment by meetdilip** [comment]
Ok. Thanks.
