### ISSUE TITLE
Login sound not working

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#1422]
Thank you for contributing to **Yaru**, the next Ubuntu default Theme made by the community.

If you found a bug please consider to fill below information, this will help us to understand the problem and we don't bother you with other questions :)

If you're filing an issue for a missing icon, look for **Icon Request** section below.

Thanks a lot!

------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior
Sound plays during login
(What you were trying to do)

## Actual Behavior
It worked a couple of times when I tried this

> 
> > Testing desktop-login sound
> 
> Type in a terminal gnome-session-properties. It'll give you the list of starting applications. Click on "add", and type the following informations in the dialog shown :
> 
>     Name: GNOME Login Sound
> 
>     Command: /usr/bin/canberra-gtk-play --id="desktop-login" --description="GNOME Login"
> 
>     Comment: Plays a sound whenever you log in

(What happened instead)
After 2-3 times, it stopped. I still have the startup item without any result
## Steps to Reproduce the Problem

  1. Shutdown and restart the PC
  1.
  1.

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

    `$ snap info communitheme`

I built from the repo. Using Yaru theme session

I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

0:/usr/share/themes/Yaru$ git describe
fatal: not a git repository (or any of the parent directories): .git

Software that presents the issue:
- Name: Ubuntu
- Version: 18.04

## Icon Request

If you're filing an issue for a missing icon provide the following in your request:

- If it is an application, the file name of the icon used (can be found in the `Icon=` field in an app's `.desktop` file)
- If it is a file type icon, such as "JSON icon" please include its media type (can be found in a file's Properties dialog, e.g. `text/x-css`)
- If possible provide a screenshot, link-to, or copy of a related icon or logo.

Thanks!

**Comment by clobrano** [comment]
Hi @meetdilip, 

this doesn't seem a Yaru issue actually, it has something to do with the solution you've tried to get the login sound.

**Comment by meetdilip** [comment]
Thanks for the reply. All I did was add the startup item.

**Comment by clobrano** [comment]
I see, but there's nothing Yaru related here, unless the problem does not occur in a vanilla gnome-session

**Comment by meetdilip** [comment]
I got this answer from AskUbuntu which helped 

`gsettings set org.gnome.desktop.sound theme-name 'Yaru'`
