### ISSUE TITLE
Nautilus no right border on button to the right of top navigation bar

### ISSUE THREAD

**Issue by cavillagomez** [ubuntu/yaru#1424]
## Expected Behavior
Nautilus looks great

## Actual Behavior
Graphic issues on top navigation buttons

## Steps to Reproduce the Problem

  1.Open files in **Home** folder
  2.Double click on **Documents**
  3.Click **Home** on top bar

![Screenshot from 2019-07-11 11-18-26](https://user-images.githubusercontent.com/52009322/61071177-a72edc00-a3cd-11e9-8181-0fd0c4a379e3.png)

***No right border in button to the right (Documents)

## Specifications

Yaru theme installed in 18.04 by ppa

**Comment by Feichtmeier** [comment]
PPA is no longer supported
PPA purge it and install the snap
Best regards
