### ISSUE TITLE
Idea for LibreOffice icons, if LO permits it

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1430]
We already have some lovely LibreOffice mimetypes that take the LO colours/brand and do them in a Suru style.  Also, the vertical oblong from the mimetype happens to be one of our "non-uniform Suru shapes".

**If** LO let us, why don't we use these as the app icons for Ubuntu?  It would make a big positive difference to the default app grid and launcher.  I've tried it in a local branch and think it looks good:

![image](https://user-images.githubusercontent.com/38893390/62012001-4bf43c00-b178-11e9-9fcb-c3cb3794aa85.png)

![image](https://user-images.githubusercontent.com/38893390/62012004-56163a80-b178-11e9-8939-0b16fca26199.png)

If LO don't mind, I don't see a reason not to do this?  Any thoughts, @Feichtmeier @clobrano @madsrh?

**Comment by ubuntujaggers** [comment]
@fitojb what would be the best way to approach Libre Office about this?  (and what do you think?)

**Comment by fitojb** [comment]
@ubuntujaggers Beautiful work. We like it! We hang out at https://t.me/LibreOfficeDesign; Andreas Kainz (also of KDE Design fame) has already seen this; he may have more feedback for you.

**Comment by ubuntujaggers** [comment]
@fitojb Really glad you like them - wish I could say I did these ones but we inherited them :)

**Comment by ubuntujaggers** [comment]
@Feichtmeier made the point that the app icons in this proposal are the same as the mimetypes which might be confusing (i.e., app versus doc shortcut).  So, I've redone this proposal with a full LO-style cut in the corner for the app icon.  Also, I've based the 256px pictogram on the smaller size pictograms for a slightly more modern (less detailed) look.

![image](https://user-images.githubusercontent.com/38893390/62313532-e7dbbb80-b488-11e9-9455-36d200be2179.png)

![image](https://user-images.githubusercontent.com/38893390/62313557-f2965080-b488-11e9-8f8f-ac30545ffc8b.png)

**Comment by Feichtmeier** [comment]
@ubuntujaggers nice one! That shape helps to distinguish the app icons from the mimetypes! And those smaller sizes fit much better. I wonder why the LO icons are so super large 🤔

**Comment by ubuntujaggers** [comment]
Voilà:

![image](https://user-images.githubusercontent.com/38893390/62395494-55124e00-b568-11e9-8248-554fb71e939d.png)

![image](https://user-images.githubusercontent.com/38893390/62395501-5c395c00-b568-11e9-8323-36d817cd43b2.png)

![image](https://user-images.githubusercontent.com/38893390/62395505-6196a680-b568-11e9-8da5-ac07ffe1b8b5.png)

![image](https://user-images.githubusercontent.com/38893390/62395525-69eee180-b568-11e9-8b53-9c52af2adb83.png)

**Comment by Feichtmeier** [comment]
Closing it since it's merged! Thank you @ubuntujaggers !
