### ISSUE TITLE
Snap Store icon isn't in Yaru style

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1433]
We're powerless to fix this but maybe we could ask the snap maintainers to consider it?  We could do something like:

![image](https://user-images.githubusercontent.com/38893390/62161316-cb674400-b30d-11e9-8477-11b16c921ef7.png)

![image](https://user-images.githubusercontent.com/38893390/62161333-d6ba6f80-b30d-11e9-8720-ce79ecfbb2fd.png)

**Comment by clobrano** [comment]
This is really nice I think. @didrocks, do you know who we might get in touch with for the proposal?

**Comment by didrocks** [comment]
You should ping Robert Ancell (@robert-ancell if you look at your github notifications) on freenode, early in our morning or late (he lives in NZ) :)

**Comment by clobrano** [comment]
Thanks!

**Comment by kenvandine** [comment]
There's current work that's about to land that will enable snaps installing a fallback icon to handle cases where the theme may not provide an icon.  

https://trello.com/c/q4lVSmTr/13-allow-snaps-to-provide-icon-theme-icons

Once this lands, we would be happy to use the themed snap-store icon and install the current icon as a fallback to use.  So I would suggest adding this to the Yaru theme.
