### ISSUE TITLE
Missing communitheme after restart on 18.04

### ISSUE THREAD

**Issue by KTConnolly** [ubuntu/yaru#1437]
Hi, I'm having the same problem as this https://askubuntu.com/questions/1163507/missing-communitheme-after-restart-on-18-04

communitheme is not showing under the Applications section after restarting.

![Screenshot from 2019-08-07 07-19-21](https://user-images.githubusercontent.com/44116267/62599320-d1e45580-b8e3-11e9-81bf-5711d083e3da.png)

**Comment by KTConnolly** [comment]
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: yesterday at 17:32 BST
channels:
  stable:    0.1 2019-03-13 (1768) 16MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-07-06 (1823) 17MB -
installed:   0.1            (1768) 16MB -

**Comment by clobrano** [comment]
Hi @KTConnolly,

thanks for reporting this. We actually did not make any change recently that might have caused this, have you already tried to reporte this bug in [launchpad](https://launchpad.net/)?

**Comment by KTConnolly** [comment]
Will give that a go, thx.
