### ISSUE TITLE
GNOME Music stars broken on Yaru Dark

### ISSUE THREAD

**Issue by PizzaLovingNerd** [ubuntu/yaru#1444]
## Expected Behavior

For the stars to look like this (result on Yaru light):

![image](https://user-images.githubusercontent.com/13041099/62814942-ed5c8580-bac8-11e9-82c4-9da4581cf8b6.png)

## Actual Behavior

This is what they look like on Yaru Dark

![image](https://user-images.githubusercontent.com/13041099/62814952-082efa00-bac9-11e9-84b7-1ded74011c24.png)

## Steps to Reproduce the Problem

  1. Open GNOME Music
  2. Go to the Album tab
  3. Select an Album

## Specifications

Information for package gtk3-metatheme-yaru:
```
Repository     : repo-oss                             
Name           : gtk3-metatheme-yaru                  
Version        : 18.10.7-1.3                          
Arch           : noarch                               
Vendor         : openSUSE                             
Installed Size : 1000.1 KiB                           
Installed      : Yes (automatically)                  
Status         : up-to-date                           
Source package : yaru-theme-18.10.7-1.3.src           
Summary        : GTK+ 3 support for the Yaru Gtk Theme
Description    : This is the theme shaped by the community on the Ubuntu hub.
```

## Software that presents the issue:
- Name: GNOME Music
- Version: 3.32.2

## Note:
I am running this on OpenSUSE Tumbleweed, and not Ubuntu.

**Comment by clobrano** [comment]
Hi @PizzaLovingNerd,

on my system gnome music looks like this

![image](https://user-images.githubusercontent.com/2883614/62821495-269eff00-bb76-11e9-9c31-c660f15d49e9.png)

I am running master now, so surely the fix - if necessary - is soon to be available.
I wonder if the gtk3-metatheme-yaru version 18.10.7-1.3 has anything to do with ubuntu versioning. If that so, 18.10 looks like a very old base
