### ISSUE TITLE
Record icon could be white instead of red

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1448]
![image](https://user-images.githubusercontent.com/15329494/62931861-58ef6d00-bdbf-11e9-8c2f-d8de882bcef8.png)

![image](https://user-images.githubusercontent.com/15329494/62931879-64db2f00-bdbf-11e9-962c-726f9eb698ec.png)

Noticed that the adwaita icon is white, which looks better on red record buttons :)

@ubuntujaggers thoughts? :)

**Comment by meetdilip** [comment]
Perhaps a white outline to the red button.

**Comment by clobrano** [comment]
Better full white for me 👍

**Comment by ubuntujaggers** [comment]
I agree, will do this soon 👍
