### ISSUE TITLE
Prep for 19.10 release

### ISSUE THREAD

**Issue by iainlane** [ubuntu/yaru#1461]
@clobrano @Feichtmeier just wanted to file this to chat about making the first `19.10.1` release, think you've been talking to @3v1n0 about this already?

Could one of you write the Debian changelog maybe please? Anything else that needs doing?

**Comment by Feichtmeier** [comment]
Hi @iainlane 

Yes let me get two PRs into master, then @clobrano wanted to do the release **this eve or tomorrow** -> is this okay for you?
Yes we talked with @3v1n0 about this on telegram :)

**Comment by iainlane** [comment]
sounds good, thanks!

**Comment by Feichtmeier** [comment]
@iainlane is this the last chance to get  icons/theme changes into eon?

**Comment by iainlane** [comment]
No, that's the UI freeze (later), we mainly need a release now to be compatible with shell 3.33.90
