### ISSUE TITLE
Overview search results displaced and cut off

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#1466]
I'm seeing an issue with searching in the overview

## Expected Behavior

Overview search should look like this (Stock gnome session):

![Screenshot from 2019-08-19 16-46-25](https://user-images.githubusercontent.com/1044087/63298251-120ee500-c2a1-11e9-8241-457a1c549c2a.png)

## Actual Behavior

Instead it looks like this with items shunted off to the right and cut off:

![Screenshot from 2019-08-19 16-44-21](https://user-images.githubusercontent.com/1044087/63299145-19cf8900-c2a3-11e9-9191-a3aa2021b812.png)

## Steps to reproduce

* tap super
* search for something

## Specifications

I'm using yaru master via the Arch Linux AUR package. I'm on the regular Arch gnome-shell and mutter packages:

mutter 3.32.2+43+gb7f158811-1
gnome-shell 1:3.32.2+11+g1c6abf378-1

I believe there are some performance patches backported to these packages, so they're not totally vanilla, but the issue I'm describing appeared with an update to yaru in the last 24 hours, whereas gnome-shell and mutter have not changed.

**Comment by Feichtmeier** [comment]
You need the latest shell changes for this.
Wait some days then it should be in the eoan daily.
This needs gnome 3.34
Thanks for reporting

**Comment by chrisjbillington** [comment]
I see, Yaru now needs the changes that caused #1434 

Switching back to the patched gnome-shell on which I saw #1434 I no longer see this issue.

**Comment by Feichtmeier** [comment]
Yes the master branch is the development branch. :)
I think when gtk and gnome shell 3.34 is released you should be able to pull it in arch, or how does it work outside of the Ubuntu land?

**Comment by Devorlon** [comment]
Sorry for my ignorance but just to clarify. This should be fixed in a few days when gnome-shell is updated?

Also, I'm not sure if it's intended but the notifications / calendar panel as well as the quick settings are a light theme no matter if you use Yaru (light) or Yaru-Dark.

Arch.
mutter 3.32.2+43+gb7f158811-1
gnome-shell 1:3.32.2+11+g1c6abf378-1

**Comment by clobrano** [comment]
> Also, I'm not sure if it's intended but the notifications / calendar panel as well as the quick settings are a light theme no matter if you use Yaru (light) or Yaru-Dark.

Yes, this is intended. Yaru light/dark only reflects in GTK applications, not on the Shell, at least for now

**Comment by Feichtmeier** [comment]
> Sorry for my ignorance but just to clarify. This should be fixed in a few days when gnome-shell is updated?

Yes, the recent scss changes need gnome shell 3.34

**Comment by chrisjbillington** [comment]
@Devorlon I think the 3.34 release is still a few weeks away. In the meantime you can use this [AUR package](https://aur.archlinux.org/packages/gnome-shell-performance/) which has the relevant changes backported to 3.32.

Normal practice on Arch would be for the 3.34 GTK and GNOME packages to be in the repos as soon as all their dependencies are satisfied in the repos, though possibly everything will sit in the testing repo for a short time depending on how things are behaving (or let's be honest, how adventurous the packagers are feeling :p ). I notice I can't build mutter master presently from an AUR package because a required library is not new enough. In the meantime you can use the above AUR package, or I'm sure other AUR packages for the release candidates etc will pop up in the coming days and weeks that will build on an up-to-date Arch install. You can also modify the PKGBUILD for Yaru to pull a commit prior to the CSS change. That will work fine - no need to always be running master! There was an AUR package shipping just the actual releases of yaru, but it has been orphaned by its packager and so it not updated anymore.

**Comment by Feichtmeier** [comment]
Ubuntu users please just relax everyone and wait until Ubuntu 19.10 daily had entered some of those freeze points :D or for the real 19.10 release

Thanks for the explanation, Chris!

**Comment by Devorlon** [comment]
@chrisjbillington Just tried out that AUR package at it worked great, Thanks.
