### ISSUE TITLE
Contacts icon in "Settings" is not clearly visible

### ISSUE THREAD

**Issue by fcole90** [ubuntu/yaru#1467]
If you go in Settings->Details->Users, you will notice that the current user icon is barely visible.

![image](https://user-images.githubusercontent.com/1292230/63494760-0b61b700-c4c7-11e9-98f9-0c73d02ac069.png)

In the screenshot I'm using the current master (Adwaita recolored) with Gnome 3.34.

```
$git describe
19.10.1
```

**Comment by Feichtmeier** [comment]
Upstream bug https://gitlab.gnome.org/GNOME/gnome-control-center/issues/663
