### ISSUE TITLE
Why was the "Files" icon changed?

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [ubuntu/yaru#1469]
Hi, why was the perfect folder icon changed? I don't get how this 
![Screenshot from 2019-08-23 17-22-03](https://user-images.githubusercontent.com/38913802/63581912-9f687700-c5ca-11e9-8289-e3b77ad83ad9.png)
is better than the previous icon.

**Comment by clobrano** [comment]
Hi, previous icon was easy to mistake for a normal folder. I hope you'll get along well with new one soon

**Comment by ReyLeonardAmorato** [comment]
Glad to see the drawer icon gone. :)
