### ISSUE TITLE
Introduce an option to change accent colours

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#1470]
Suggestion:
I know the colour orange means a lot in Ubuntu.
But sometimes It does not blend or contrast well with certain UI elements of gnome-shell for me.

I do not suggest total removal of orange but inclusion of other colours (distinct colours like blue,pink,yellow,green..etc.) and allowing the option to change them by the user in settings.

Thanks!

**Comment by clobrano** [comment]
Hi @Muqtxdir,

thank you for taking time to propose your idea. Unfortunately this is out of our possibilities as Yaru team, in the sense that we cannot implement color selection in user settings as you might like.

Is there any specific UI element you think doesn't get along well with orange?

**Comment by Muqtxdir** [comment]
Most of the contrast issues with orange I have are the light themed context menus in gnome shell

for example:
It takes time to see where the default selection is in the shutdown menu
![light](https://user-images.githubusercontent.com/54065734/63637143-a78de880-c696-11e9-9aa9-5784cb005661.png)
