### ISSUE TITLE
Subwoofer icon is missing

### ISSUE THREAD

**Issue by zd-dalibor** [ubuntu/yaru#1471]
![image](https://user-images.githubusercontent.com/226822/63641372-7c62c380-c6ad-11e9-9277-4abcb7a8fe74.png)

```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by Feichtmeier** [comment]
Sorry I Schneegrills accidentally closed it!

Thanks for the issue! I think in top of the missing one, we could use all the others in the yaru style.

**Comment by madsrh** [comment]
Sorry if I've asked this before @Feichtmeier but is there any way to change the color of the icons?

**Comment by madsrh** [comment]
> Yes, symbolic icons colour can be changed. But maybe it's hard coded colour in the app. What app is this?

Let's hope it isn't hard coded. It's Gnome Settings ⚙️ just hit the _test_ button
![image](https://user-images.githubusercontent.com/3986894/63809829-9d344e80-c923-11e9-8b93-84d976cefafe.png)

The icon below is just borrowed from the web (I'm sure @ubuntujaggers can come up with something more fitting) to illustrate how this could look with white symbolic icons (like the rest of the UI uses 😉).

![image](https://user-images.githubusercontent.com/3986894/63809735-61998480-c923-11e9-9f77-87db2e5e320d.png)

**Comment by madsrh** [comment]
@ubuntujaggers could you draw a subwoofer icon?

It's called `audio-subwoofer.svg` and with color `audio-subwoofer-testing.svg` in the **devices** folder.
[Here is Paprius](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/tree/master/Papirus/48x48/devices) for reference

I think the blue "testing" color is #729fcf 
![image](https://user-images.githubusercontent.com/3986894/73029282-86911580-3e37-11ea-9fcd-54fffa3e812f.png)

**Comment by Feichtmeier** [comment]
Just to have a list for you to check after the nice finding of mads:

- [ ] audio-speaker-center-back-testing.svg
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-center-back-testing.svg

- [ ] audio-speaker-center-back.svg
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-center-back.svg

- [ ] audio-speaker-center-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-center-testing.svg

- [ ] audio-speaker-center.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-center.svg

- [ ] audio-speaker-left-back-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-left-back-testing.svg

- [ ] audio-speaker-left-back.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-left-back.svg

- [ ] audio-speaker-left-side-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-left-side-testing.svg

- [ ] audio-speaker-left-side.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-left-side.svg

- [ ] audio-speaker-left-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-left-testing.svg

- [ ] audio-speaker-left.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-left.svg

- [ ] audio-speaker-mono-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-mono-testing.svg

- [ ] audio-speaker-mono.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-mono.svg

- [ ] audio-speaker-right-back-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-right-back-testing.svg

- [ ] audio-speaker-right-back.svg
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-right-back.svg

- [ ] audio-speaker-right-side-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-right-side-testing.svg

- [ ] audio-speaker-right-side.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-right-side.svg


- [ ] audio-speaker-right-testing.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-right-testing.svg

- [ ] audio-speaker-right.svg	
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/devices/audio-speaker-right.svg

Rofl xD For every corner there is a normal and a -testing icon with blue color

**Comment by ubuntujaggers** [comment]
Good diagnosis!

**Comment by meetdilip** [comment]
![sub woofer 2](https://user-images.githubusercontent.com/6965443/73059595-0d87d180-3ebc-11ea-9772-f99738f7cbff.png)

![sub woofer](https://user-images.githubusercontent.com/6965443/73059596-0e206800-3ebc-11ea-9241-ce227c932de2.png)

You want blue colour with white background ?

**Comment by madsrh** [comment]
> You want blue colour with white background ?

The blue color is only when the speaker is tested (sound is coming from the speaker). If @ubuntujaggers is redoing **all** of the icons, he can just use another color (one that work great on light and dark background) - as long as all the icons match :)

**Comment by meetdilip** [comment]
Made from @madsrh 's hex code

![subwoofer 3x white 1](https://user-images.githubusercontent.com/6965443/73060066-0c0ad900-3ebd-11ea-9c9c-ded964542251.png)

**Comment by meetdilip** [comment]
![subwoofer grey 3](https://user-images.githubusercontent.com/6965443/73066885-411f2780-3ecd-11ea-8314-4267f0a400b7.png)

![subwoofer blue](https://user-images.githubusercontent.com/6965443/73066886-41b7be00-3ecd-11ea-8fb1-ae3270422ec8.png)

**Comment by meetdilip** [comment]
Managed to identify the colour which works with both backgrounds. Same icon, different backgrounds. Also, I am not sure what " mono " is and which position it will take. Care to share a screenshot ? 

![demo 2](https://user-images.githubusercontent.com/6965443/73088424-35962580-3efa-11ea-8115-061d40243822.png)

**Comment by meetdilip** [comment]
Testing icons in blue

![demo 2 blue](https://user-images.githubusercontent.com/6965443/73089375-17c9c000-3efc-11ea-9bcb-932d966d2dd6.png)

**Comment by meetdilip** [comment]
Just for reference

![demo files 2x](https://user-images.githubusercontent.com/6965443/73113324-339f8700-3f39-11ea-987e-dc2322a550e2.png)
