### ISSUE TITLE
Text missing in Gnome shell search with rebased Yaru theme

### ISSUE THREAD

**Issue by minghuaw** [ubuntu/yaru#1474]
------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior 
![Screenshot from 2019-08-26 12-33-38](https://user-images.githubusercontent.com/29760666/63717769-d2468100-c7fd-11e9-9d4f-e7d32b0fde4c.png)

Typing anything in the Gnome shell search should show the related apps or files including their relevant text. The above screenshot is produced with the default Adwaita gnome shell theme.

## Actual Behavior
![Screenshot from 2019-08-26 12-33-57](https://user-images.githubusercontent.com/29760666/63717890-1fc2ee00-c7fe-11e9-912d-9d2953a68678.png)

Changing the gnome shell theme to the rebased Yaru theme would make the relevant text for the files disappear.

## Steps to Reproduce the Problem

  1. Choose Yaru theme or default on Ubuntu 19.10 for shell theme in gnome-tweaks
  2. Press `super` button (`Windows` button on PC) and type any text in gnome shell's default search box

## Specifications
Ubuntu 19.10 Eoan (development branch) with the default Yaru theme.

Software that presents the issue:
- Name: Gnome Shell
- Version: 3.32.2

**Comment by clobrano** [comment]
Hi, 

You need the latest gnome shell package which is not on Eoan yet (there's a ppa but I'm on my phone now and I don't have the name here).
