### ISSUE TITLE
Shell theme asset paths

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1475]
Assets are not loaded when using the ```url("resource:///org/gnome/shell/.....``` path

It works if you remove the absolute path to the resource but I think then the svg is not converted into a gresource.

This was the reason for the checkmarks not showing up before #1472 

Another example is the on screen keyboard:
With absolute path there are the adwaita assets
![grafik](https://user-images.githubusercontent.com/15329494/63784145-7d366800-c8ee-11e9-9ffd-cb4c926492e6.png)

With relative paths there is our asset (I think the green is questionable, maybe @madsrh has an idea which of our colors fits here :D ?)
![grafik](https://user-images.githubusercontent.com/15329494/63784264-b242ba80-c8ee-11e9-8797-c9900b0a0049.png)

@3v1n0 @clobrano is there a way we could use a gresource in yaru for these assets?

**Comment by madsrh** [comment]
> I think the green is questionable, maybe @madsrh has an idea which of our colors fits here :D 

Questionable indeed. The green jumps out but even more the orange. Would it be possible to go with the [upstream colors](https://raw.githubusercontent.com/gnome-design-team/gnome-mockups/master/osk/osk-wires.png) but using a shade from our color palette?

I don't see any of the other options working out here 🤔

**Comment by Feichtmeier** [comment]
Or use orange for the arrows and green for the enter key?

**Comment by clobrano** [comment]
+1 for using upstream colors in our palette. Orange always look a bit destructive :)

**Comment by madsrh** [comment]
> Or use orange for the arrows and green for the enter key?

I do really like [Arrons initial stying](https://github.com/ubuntu/yaru/pull/961), but there was an issue with green not being a great solution for ENTER because it can also be a destructive action 🤷‍♂

> +1 for using upstream colors in our palette. Orange always look a bit destructive :)

👍
