### ISSUE TITLE
The shadows of the File Manager icon are inverted

### ISSUE THREAD

**Issue by Trine4** [ubuntu/yaru#1479]
Hello everyone,

I just noticed that the shadows of the File Manager were inverted (especially at the handles). Shadows are at the top instead of at the bottom (like the bottom of the icon)

![Current File Manager](https://user-images.githubusercontent.com/38893390/62970150-ba86fa00-be06-11e9-884c-622d9afb4788.png)

Can you also change the trash that has become ugly with its gray tint? Thanks :)

**Comment by madsrh** [comment]
Nicely spotted @Trine4 👍 Thanks! I'll tag our icon guy here.

> Can you also change the trash that has become ugly with its gray tint? Thanks :)

Please avoid using the word "ugly" in the issue description. It has a very negative sound (obviously), we've spent many hours putting in our best effort and "ugly" doesn't really add any value other than letting us know that you don't like it.

**Comment by ValentinM1** [comment]
You are right. It is badly said and I apologize. You did a monstrous job on Yaru 👍

**Comment by Trine4** [comment]
You are right. It is badly said and I apologize. You did a monstrous job on Yaru 👍
