### ISSUE TITLE
Headerbar switch is hard to see

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1480]
Headerbar switches (either enabled, disabled and in backdrop) are too hard to see

enabled switched off
![image](https://user-images.githubusercontent.com/2883614/63950084-a7696080-ca7b-11e9-8c3a-eb30e6ff9a5c.png)

disabled switched off
![image](https://user-images.githubusercontent.com/2883614/63950263-f2837380-ca7b-11e9-8dc4-400ab8f955ef.png)

**Comment by madsrh** [comment]
Adding the old Yaru style switches for reference (because they looked pretty great TBH)

![image](https://user-images.githubusercontent.com/3986894/63980314-79a40c00-cabb-11e9-8729-91079936d91e.png)

**Comment by clobrano** [comment]
This might be fixed by #1478

**Comment by Feichtmeier** [comment]
Depending on the colour of the headerbar you end up with, you need to adjust the code in tweaks that tries to mitigate the fact that switches in the light theme are drawn with the mixins from drawing that expect the theme to be light

**Comment by Feichtmeier** [comment]
Fixed by https://github.com/ubuntu/yaru/pull/1493
