### ISSUE TITLE
Window switcher doesn't keep the height when including CJK characters

### ISSUE THREAD

**Issue by sicklylife-jp** [ubuntu/yaru#1481]
OS: Ubuntu 19.04 and Ubuntu 19.10 development branch
Language: Japanese

## Screencast

![peekJ3SE7Z](https://user-images.githubusercontent.com/43719368/64013425-bb37c400-cb5a-11e9-9228-53b330cd3a81.gif)

## Steps to Reproduce the Problem

  1. Create English name folders
  2. Create CJK name folders (ex. 桌面, デスクトップ, 바탕 화면)
  3. Double click them to open
  4. Press Alt+Tab

**Comment by Feichtmeier** [comment]
Thanks for reporting!
This could be an upstream bug since our shell theme only changes colours. I'll check

**Comment by Feichtmeier** [comment]
It's also happening on the upstream shell. We didn't modify the shell except colours. Please report this on the upstream repo on gnome shell. I can eventually fix it upstream then. I don't want to do double work :) (lazy)

**Comment by sicklylife-jp** [comment]
I understand.
Thank you!
