### ISSUE TITLE
Sim City (=Micropolis) needs a proper icon

### ISSUE THREAD

**Issue by real-amano** [ubuntu/yaru#1485]
That game is in an urgent need for a proper icon. With the recent update today the old icon isn't displayed at all in the dock.

And the old icon isn't a real icon at all, it is just a button from within the game.

If somebody came up with a proper icon I would propose that upstream.

**Comment by real-amano** [comment]
![grafik](https://user-images.githubusercontent.com/25839976/64366875-71962000-d017-11e9-903d-3f43c04b535d.png)

Look at the dock. The icon is missing. You see the "icon" within the Sim City UI (upper left).

**Comment by real-amano** [comment]
![grafik](https://user-images.githubusercontent.com/25839976/64367339-10bb1780-d018-11e9-9026-343a6ea03bbe.png)

That is the icon in the grid. It doesn't look like an icon at all, it is just "something" from within the UI.

**Comment by Feichtmeier** [comment]
@real-amano it's undeniable a bad icon. But this is something we actually didn't want to start: providing icons for anything.

First prio: unbranded gnome core apps with generic names (files, settings.... Etc)
Second prio: other preinstalled apps after asking the developers for an OK (libre office, shotwell, transmission, remmina)

Everything else is really out of scope for us. If @ubuntujaggers wouldn't have mutated into an icon artist we would pretty much using stock Suru icons now
I suggest to contact the Devs from that icon . Thus closing this, thanks for reporting issues on Yaru <3

**Comment by real-amano** [comment]
Nope, it is the deb from the Ubuntu repositories. 

I would have reported that upstream if there was an active upstream (the last contribution was to a Readme file 4 years ago). 

So bad luck then, I guess.

**Comment by Feichtmeier** [comment]
Okay, maybe ubuntujaggers has time for this anyways, but then not in this repo. Because if you do it for one app, other apps might start asking :)
