### ISSUE TITLE
Icon of Evince document viewer is confusing

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1489]
Evince has a rather strange icon in my opinion. The use of a magnifier glass in the icon indicates that it is a search/find utility rather than a document viewer. I hope it could be improved.
![grafik](https://user-images.githubusercontent.com/15329494/64491751-29bc0680-d26c-11e9-8591-c95448e6ab90.png)

Take a look at the upstream icon for inspiration:
https://gitlab.gnome.org/GNOME/evince/blob/master/data/icons/scalable/apps/org.gnome.Evince.svg

![grafik](https://user-images.githubusercontent.com/15329494/64491744-1872fa00-d26c-11e9-8172-977dd3ad6e9b.png)

**Comment by Feichtmeier** [comment]
Thanks for reporting!

Imho, since we have a solid icon for this, it's nothing super important. But I agree that some sort of "PDF"-glyph should be visible in the icon

**Comment by Amr-Ibra** [comment]
The idea is to reflect that Evince is a document viewer for multiple document formats. It supports these formats: PDF, Postscript, djvu, tiff, dvi, XPS, SyncTex support with gedit, comics books (cbr, cbz, cb7 and cbt).
So I think its icon should reflect its identity and it would be best to preserve its "e" symbol, which was in its old upstream icon and is in the new upstream icon too.

**Comment by ubuntujaggers** [comment]
Yep, I can do this.  It's currently just a re-shape of the icon that Suru had in this position.  I can certainly draw something with the "E" in for 20.04 and some glasses  :)  but don't think I can do it before feature freeze for 19.10 (sorry).

**Comment by ubuntujaggers** [comment]
Hi guys,

We already have a Yaru document icon with glasses in:

https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/documents-app.svg

How about we just use that and make the image square inside the doc red, and add the white swirl?

**Comment by clobrano** [comment]
I think it's a good idea :)

**Comment by Amr-Ibra** [comment]
That icon is used by gnome-documents, which is a document explorer app for documents collection.
When you install gnome-documents, it uses the documents-app.svg icon.

**Comment by clobrano** [comment]
The plan is to do something similar, not to use the same icon

**Comment by ubuntujaggers** [comment]
It's split into two icons now, @Amr-Ibra (when we merge my latest PR) - the generic doc viewer still exists in the theme, but evince has its own icon rather than just symlinking to a generic one.

**Comment by Amr-Ibra** [comment]
Yes, original Suru has two icons:
- docviewer-app.svg - a document viewer - used by Evince
- documents-app.svg - a document explorer - used by gnome-documents
