### ISSUE TITLE
Scroll bar in the focussed Terminal window is almost invisible

### ISSUE THREAD

**Issue by vanvugt** [ubuntu/yaru#1490]
Scroll bar in the focussed Terminal window is almost invisible. Strangely it's quite visible for all the other (unfocussed) Terminal windows.

## Expected Behavior

The scroll bar colour contrasts with the Terminal window background.

## Actual Behavior

The scroll bar colour does not contrast with the Terminal window background.

![Screenshot from 2019-09-09 11-15-08](https://user-images.githubusercontent.com/11951986/64501316-6848d400-d2f3-11e9-9230-1c72e443683a.png)

## Steps to Reproduce the Problem

  1. Open a Terminal window.

## Specifications

Ubuntu 19.10
```
ii  yaru-theme-gnome-shell                     19.10.1                               all          Yaru GNOME Shell desktop theme from the Ubuntu Community
ii  yaru-theme-gtk                             19.10.1                               all          Yaru GTK theme from the Ubuntu Community
ii  yaru-theme-icon                            19.10.1                               all          Yaru icon theme from the Ubuntu Community
ii  yaru-theme-sound                           19.10.1                               all          Yaru sound theme from the Ubuntu Community
```

Downstream bug: https://bugs.launchpad.net/bugs/1842898

**Comment by Feichtmeier** [comment]
@vanvugt that's strange it's showing up for me. Do you used X or Wayland in that picture? 
We'll fix that

**Comment by vanvugt** [comment]
The bug occurs in both X and Wayland sessions, on every machine I install Ubuntu 19.10 on.

**Comment by vanvugt** [comment]
Though for some reason (this white web page?) the screenshot looks worse here. Try opening the image in a new tab.

**Comment by Feichtmeier** [comment]
Okay then I will just reduce the transparentization

**Comment by vanvugt** [comment]
I guess the best test would be a black background?

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.20/_apps.scss#L179

 it looks definitely more opaque for me here, but in the picture it's not visible enough, so we could just decrease the transparentization

**Comment by vanvugt** [comment]
How good is your monitor's colour reproduction? That might be a factor here. I think I've only tested this on fairly accurate monitors so far, that are close to 100% sRGB.

**Comment by Feichtmeier** [comment]
No idea tbh, I only know that one of my pc's has a very bad brightness!

There was another problem I noticed while working on a fix.
Our custom code for the terminal does not really work if the user selects light colors while using the light yaru theme

The best thing is to not touch the colors at all then every combination works
- purple custom ubuntu color + yaru light / yaru dark
![image](https://user-images.githubusercontent.com/15329494/64517373-38330e00-d2be-11e9-8fb1-b1ddd8ab9d71.png)
![image](https://user-images.githubusercontent.com/15329494/64517409-4aad4780-d2be-11e9-844b-19b0600f5564.png)


- light terminal bg color + yaru light / yaru dark
![image](https://user-images.githubusercontent.com/15329494/64517483-6d3f6080-d2be-11e9-8338-d8fe7d84843b.png)
![image](https://user-images.githubusercontent.com/15329494/64517451-60227180-d2be-11e9-8c2a-ed581ec39edf.png)

- dark terminal bg color + yaru light / yaru dark
![image](https://user-images.githubusercontent.com/15329494/64517529-80523080-d2be-11e9-8723-e74336a4a5fe.png)
![image](https://user-images.githubusercontent.com/15329494/64517549-8c3df280-d2be-11e9-9c8a-6bd9f2ae01e1.png)

This is the safest solution, thought the scrollbar is quiet visible now, maybe too visible for some. But better "safe and not-super-sexy" than sorry, right?
