### ISSUE TITLE
Update the color of the progress bars

### ISSUE THREAD

**Issue by Trine4** [ubuntu/yaru#1495]
Hi,
Would it be possible to change the color of the progress bars in Yaru? The blue color is too bright compared to the rest of the theme.
This is all the more obvious with the new light theme when changing the volume.

![64419068-1f321f00-d06a-11e9-9697-2942f947227c](https://user-images.githubusercontent.com/34983829/64552725-1e361180-d338-11e9-8799-074ae470a713.png)

**Comment by clobrano** [comment]
Hi, 

The color palette is going to be reviewed in the next cycle, but I can't promise anything right now. 
By the way, the new light theme changed only the headerbar color

**Comment by Trine4** [comment]
I know but I find that the color is less harmonious with the new theme :)

**Comment by meetdilip** [comment]
When using Transmission, the entire torrent entry is highlighted in Orange. But with that comes this Blue progress bar. It is certainly a kind of mismatch in that scenario. 

![transmission colours](https://user-images.githubusercontent.com/6965443/64590803-0016f280-d3c6-11e9-8ac2-c71609a88c41.png)

**Comment by Feichtmeier** [comment]
This is the "old" theme pre-upstream-resync right? It should be white with master

**Comment by meetdilip** [comment]
I see. Thanks for reminding.

**Comment by madsrh** [comment]
> This is the "old" theme pre-upstream-resync right? It should be white with master

I can't test at the moment, but does this mean that we can close this issue?

**Comment by madsrh** [comment]
I did a few experiments and just wanted to share them here for future reference regarding the color palette review. These were my best ideas and they are pretty bad 🤦‍♂ I still prefer [the current bright blue](https://user-images.githubusercontent.com/34983829/64552725-1e361180-d338-11e9-8799-074ae470a713.png). 

### Coffee #9c9c9d
![image](https://user-images.githubusercontent.com/3986894/64726581-427c2480-d4d7-11e9-91f6-7e9bd6c83173.png)



### Unity8.1 Blue #335280
![image](https://user-images.githubusercontent.com/3986894/64726621-5a53a880-d4d7-11e9-8659-6dc31b58d156.png)



### Slightly darker current blue #209dd2
![image](https://user-images.githubusercontent.com/3986894/64726853-cb935b80-d4d7-11e9-9858-0bfeee7b50f4.png)

**Comment by Feichtmeier** [comment]
Thanks for the efforts @madsrh 
But I agree with you
What is exactly different now that the dark headerbar is gone in the light theme, that makes the blue different than before? It is the EXACT same bg_color and base_color and what not. Nothing changed except the headerbar. Imho this issue is pointless, sorry.

**Comment by meetdilip** [comment]
It is always good to keep the progress bar bright. Most use case scenarios will support it.
