### ISSUE TITLE
Tag labels in Nautilus are too high

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1497]
Tag labels in Nautilus are too high
![image](https://user-images.githubusercontent.com/3986894/64571480-43407980-d364-11e9-86b1-cdc9bf0dc72a.png)

**Comment by Feichtmeier** [comment]
Nautilus checks the current gtk theme
And only If the current gtk theme is Adwaita this custom CSS file and within the line which we now need to readd for us:

https://gitlab.gnome.org/GNOME/nautilus/blob/master/src/resources/css/Adwaita.css#L77
