### ISSUE TITLE
Restyling of Nautilus floatingbar

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1498]
Not really an issue, but there were some other design ideas in the PR/issue that this came from (_as you can tell from the title of this issue, I can't remember the name_). Perhaps another style would fit the full light theme better?

If not, feel free to close this!

![image](https://user-images.githubusercontent.com/3986894/64571348-e3e26980-d363-11e9-9f92-db74c7e4c848.png)

**Comment by clobrano** [comment]
Indeed, the inkstone color does not match with anything there anymore. I'd like to work on this

**Comment by Feichtmeier** [comment]
I'm just asking a general design question: what actually could this label be categorised as? 
We styled it as something like a OSD (on screen display... Or like a web "toast")
But it's not going away so OSD was prbly wrong :)

**Comment by madsrh** [comment]
>  I'd like to work on this

@clobrano can you locate the old PR or issue? I think Frederik and I had some good alternatives in there (if it wasn't on Telegram 😱 ), but I can't find it.

**Comment by clobrano** [comment]
Any of you remember the name of that thing?

**Comment by Feichtmeier** [comment]
.floating-bar

**Comment by clobrano** [comment]
Thanks, I wonder, can't we simply use upstream one?

**Comment by Feichtmeier** [comment]
Doesn't look too bad
![image](https://user-images.githubusercontent.com/15329494/64597945-ceca0280-d384-11e9-9bde-027dcd4e864f.png)

Maybe a + shadow? :man_shrugging:

**Comment by clobrano** [comment]
Okay, since at the end we still need to add code, we can do whatever we want, but box-shadow doesn't seem to apply to this widget

![image](https://user-images.githubusercontent.com/2883614/64624415-ea67f400-d3ea-11e9-9d8d-e17e7f0117d0.png)
