### ISSUE TITLE
Update the issue template

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1503]
It's a little bit outdated
https://github.com/ubuntu/yaru/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by clobrano** [comment]
It needs to be ported to the new github workflow. Do you mean also changes to the content?

**Comment by Feichtmeier** [comment]
Just minor tweaks

- "the next Ubuntu default Theme made by the community."
- If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

`$ snap info communitheme`

I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

`$ git describe`

We should add the "official" way, the .deb package from ubuntu :)

**Comment by clobrano** [comment]
done
