### ISSUE TITLE
Dark notifications seems out of place in the light-theme

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1511]
![image](https://user-images.githubusercontent.com/3986894/64654961-10ad8400-d42b-11e9-8de9-32d4e9b939dc.png)

IMO the dark notifications looks out of place with the white theme. Can we use white notifications or brighten the current design? If not white, then perhaps something like this:

![image](https://user-images.githubusercontent.com/3986894/64654975-2327bd80-d42b-11e9-8535-4c6153a2e881.png)

**Comment by Feichtmeier** [comment]
I don't like them either.

The design logic behind it is, as far as I understood them, that it's an OSD. Like the volume OSD in the shell or a tooltip in gtk. Something that drips in and then goes away.
My problem with his logic is that it's interactive. I'm not sure if it's still an OSD then.
Maybe we could reopen this issue I've made upstream:

https://gitlab.gnome.org/GNOME/gtk/issues/2072

**Comment by madsrh** [comment]
> https://gitlab.gnome.org/GNOME/gtk/issues/2072

Did he even leave a comment or did he just make them darker? Odd.

The problem IMHO is that it looks like it is coming out from the headerbar, which is now light. So having an almost black notification looks very alien. Also that dark UNDO button is hardly visible.
It's not like OSD because it isn't floating freely like the shell notifications - it is attached to the window.

Let's ~~blame~~ work with upstream on this.

**Comment by Feichtmeier** [comment]
@madsrh 
![grafik](https://user-images.githubusercontent.com/15329494/64697381-05953b00-d4a1-11e9-8e60-f44a1d21a548.png)
?

**Comment by madsrh** [comment]
Just linking this issue to it's PR https://github.com/ubuntu/yaru/pull/1515 😉
