### ISSUE TITLE
Ubuntu dock is always black and no transparent effect with yaru-gnome-shell-theme.

### ISSUE THREAD

**Issue by laichiaheng** [ubuntu/yaru#1513]
It doesn't happen with vanilla Gnome.
## Expected Behavior

See a transparent dock.

## Actual Behavior

Always black

## Steps to Reproduce the Problem

  1. No step

## Specifications

    `$ yay -S yaru-gnome-shell-theme`

Software that presents the issue:
- Name: gnome-shell-extension-ubuntu-dock
- Version: 64ubuntu4-1

**Comment by Feichtmeier** [comment]
Thanks for reportig @laichiaheng !

Indeed, there is the .transparent style class in dash to dock, that stopped working after gnome shell 3.32. So we had the choice between perma opaque or perma transparent. We've chosen perma opaque now, and yeah it looks really heavy when you have no maximized window.

Would be really nice if @3v1n0 could fix this until 20.04 (or anyone else, but I know that he has the skills, so I assigned him :angel: )

**Comment by clobrano** [comment]
In any case, even if it is not nice, this is the intended behavior right now (and everybody is looking for the moment when transparency will be back).
