### ISSUE TITLE
Review color palette

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1522]
One of the steps of the [Vendor style initiative](https://discourse.gnome.org/t/gtk-adwaita-and-vendor-styles/1641) is to export the theme color palette in the *public color list*.

Yaru started with some colors from [Unity8 palette](https://github.com/ubuntu/yaru/wiki/%231-Ubuntu-Theme-Refresh:-why-and-how%3F#how), but we might need/want to review them in order to:

- find colors that fit better with our current design, taking into account that an official [Ubuntu color palette](https://design.ubuntu.com/brand/colour-palette/) exists already,
- actually use the palette consistently (this is also another step of Vendor Style initiative)
- provide the same range of colors the other projects taking part of this initiative provide
    - [GNOME](https://developer.gnome.org/hig/stable/icon-design.html.en#palette): **8 colors** (blue, green yellow, orange, red, purple, brown, neutral) and **5 tones per color** (except Neutral that has 7)
    - [elementary OS](https://elementary.io/en/brand): **10 colors** (strawberry-red, orange, banana-yellow, lime-green, blueberry-blue, grape-purple, brown-cocoa, silver, slate, black) and **5 tones** for each (no exception)

Elementary OS actually provides more tones for what GNOME calls "neutral" color, considering that they use 3 different colors for 5 tones (silver, slate, black), but except that, both projects provide **(7 colors + 1 "grey") x 5 tones**.

EDIT:
This task is considered completed once the palette is defined and agreed. To expose it as public color will be a different task

**Comment by Feichtmeier** [comment]
Nice!

Somewhere in this process it would be great to also get ```$headerbar_bg_color``` (currently a color on top of ```_ubuntu_colors.scss```: ```#2B2929```) and our light theme ```$bg_color``` (currently a color on top of ```_ubuntu_colors.scss```: ```#f5f6f7```) from this palette
And move those widget colors out of the defacto kind-of-palette file

**Comment by clobrano** [comment]
This would be good, but I see it as a different task, more related to "actually use the palette consistently (this is also another step of Vendor Style initiative)"

**Comment by madsrh** [comment]
I think we can close this one now 😄
