### ISSUE TITLE
Checks and radios are not sharp

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1530]
Checks and radios don't have sharp borders and looks fuzzy and blurry.

Especially in the dark theme:
![grafik](https://user-images.githubusercontent.com/15329494/64918260-1e9d3500-d79c-11e9-95da-a6e59ac3fc24.png)

But also in the light theme:
![grafik](https://user-images.githubusercontent.com/15329494/64918266-2f4dab00-d79c-11e9-82cd-f060c468caac.png)

We currently use the upstream checks/radios but make them flat.
They use a background image for all buttons including checks/radios
Somehow this does not look as sharp as our old checks/radios in Yaru 1.0

@clobrano maybe we could import the old mixins first to tweaks and then propose it upstream after?

**Comment by clobrano** [comment]
Since we have an entire cycle to make it upstream, I'd say there's no hurry to fix it in Yaru first, I agree that if we can't make it, for 20.04 we can do the change downstream

**Comment by Feichtmeier** [comment]
I guess upstream you need to see what is preferred. We could use our branch as a fast playground. Ofc no hurry...
