### ISSUE TITLE
Lack of consistency in the desktop context menu

### ISSUE THREAD

**Issue by Trine4** [ubuntu/yaru#1533]
Hi,

I find that the context menu of the desktop is too wide compared to the rest of the menus (out of dock).
Why use different widths than in nautilus?

Cosmic Cuttlefish:
<img width="908" alt="1" src="https://user-images.githubusercontent.com/34983829/64951097-529c5700-d87d-11e9-94b9-1e7a58df5364.png">

Desktop under Cosmic Cuttlefish:
<img width="440" alt="Capture d’écran 2019-09-16 à 12 18 33" src="https://user-images.githubusercontent.com/34983829/64951038-30a2d480-d87d-11e9-8b9c-289a57744dac.png">

Now with Eoan Ermine:
![68747470733a2f2f692e696d6775722e636f6d2f6c5964696545582e706e67](https://user-images.githubusercontent.com/34983829/64951080-46b09500-d87d-11e9-8364-bd7ee381c6e8.png)

**Comment by clobrano** [comment]
Hi @Trine4,

thanks for reporting this. Those two menus come from different areas (gtk vs shell), but indeed there's a difference and the latter looks a bit too big

**Comment by Feichtmeier** [comment]
Since we didn't change this downstream, would you be so kind and create an issue about this upstream @trine4?

**Comment by ElectricGestalt** [comment]
I actually like the bigger menus, but yeah this is a difference between the shell settings and the gtk settings. I think the gtk menu is even slimmer in 19.10 than it was in Cosmic.

**Comment by Trine4** [comment]
I don't know if it's directly related to Gnome. Gnome does not have a desktop anymore. These menus were not designed for this.
On the other hand, Ubuntu chose to reintroduce a desktop (which is great) but the context menus have inherited Gnome styles that are not necessarily appropriate for this use. Context menus take up too much space on the screen. This is not ergonomic and contrary to what is done on all other OS (macOS, Windows, etc.).
Of course, this is my opinion.

**Comment by clobrano** [comment]
It is related to Gnome as said above and Gnome does have a desktop actually, what it does not have - by default - is a dock, but it supports a shell extension to have it

![fedora](https://user-images.githubusercontent.com/2883614/65022070-969c6400-d930-11e9-97eb-48aa136d147c.png)

Yaru shell menus have the same size, as you can see

![Screenshot from 2019-09-17 09-48-29](https://user-images.githubusercontent.com/2883614/65022135-b3d13280-d930-11e9-9d31-4e9a404a4d41.png)

**Comment by Trine4** [comment]
When I spoke of desktop, I spoke of desktop with icons!
Consequence, it is necessary to use quite often this contextual menu which is not ergonomic with the current disposition. Especially when alternating between desktop and nautilus.

**Comment by clobrano** [comment]
> When I spoke of desktop, I spoke of desktop with icons!

You don't really need to be rude, since I agreed that it's probably a bit too big (at least the separator line might be reduced).

**Comment by Trine4** [comment]
It was not mean! I just rephrased my sentence :)
I'm French and I sometimes use Google Translation that does not always work well!

**Comment by clobrano** [comment]
The exclamation mark means you're shouting, just to let you know, but okay.
We don't plan any change in gnome-shell, except colors. So if you think this is important to be change, please open the same bug on Gnome GTK issue tracker https://gitlab.gnome.org/GNOME/gtk/issues

thanks
