### ISSUE TITLE
Two icon and cursor themes, Suru and Communitheme, from the Bionic snap

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1535]
Steps on Bionic:
1. Install the communitheme snap from the edge channel
2. Open Tweaks
3. Try to change the icon and cursor theme
4. There are two options coming from the snap, Suru and Communitheme

Are both the same thing? Which one is the most updated?

I suggest removing the Suru option from both (icon and cursor) and keep only the Communitheme choice in order not to confuse users.

**Comment by Feichtmeier** [comment]
I observed that even though communitheme session defaults to "communitheme" for the icons, the snaps look up for "Suru" and end up with the wrong icons of communitheme is chosen

**Comment by Feichtmeier** [comment]
It is a symlink defined here:
https://github.com/ubuntu/yaru/blob/master/snap/snapcraft.yaml#L32
I'll test what happens if we dont symlink this in a test bionic branch

**Comment by Muqtxdir** [comment]
since no updates are being passed to `communitheme` snap anymore, closing this issue seems rerasonable (_see #3154_)
