### ISSUE TITLE
Terminal headerbar is taller than other headerbars

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1537]
As in below picture

![image](https://user-images.githubusercontent.com/2883614/65068702-6503b700-d989-11e9-9a98-7dc454bfc6e8.png)

**Comment by Feichtmeier** [comment]
Doesnt happen on a fresh eoan installation, so it must be either something in the ambiance branch or at some point of the commits after the alst release
![grafik](https://user-images.githubusercontent.com/15329494/65070948-e5c4b200-d98d-11e9-95ac-31e5e55b3231.png)

**Comment by clobrano** [comment]
My picture is from master, but I'll try again

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/65071849-e8280b80-d98f-11e9-9bf7-27fd160e6b1d.png)
fresh eoan, build from src, switched to the ambiance branch, refresh the gtk theme :man_shrugging: 
But I've observed that the yaru session is not working for some reason my session restarts then

**Comment by clobrano** [comment]
Terminal noticed already

**Comment by clobrano** [comment]
Not reproducible after installing 19.10
