### ISSUE TITLE
[Legacy + Bionic] 35% battery shows more than half icon

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1541]
The yaru-theme before 19.10.2 has the legacy battery icons so as the Bionic branch. There is also a bug in Launchpad (66% battery shows full icon):
https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1840557

Upstream adwaita-icon-theme added some fixes some time ago to the legacy battery icons (by now there are new battery icons), maybe Yaru has, in the Bionic branch, the same issues:
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/03eae765c15a5c5c3a44f3abd2a1c968b0b0ed5c
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/ff788b65f2df30aa5a53ad0692816f75e3ed5f1e

**Comment by Feichtmeier** [comment]
Should be fixed with https://github.com/ubuntu/yaru/pull/1538

**Comment by Amr-Ibra** [comment]
That's a different issue, the new battery icons are not used in the Bionic branch because of the older gnome-shell. This issue is about the legacy battery icons that still live in the Bionic branch.

**Comment by Feichtmeier** [comment]
Ah sorry also for bionic branch...
Yeah we see what we backport after the 19.10 final release I guess...

**Comment by Amr-Ibra** [comment]
I believe the new battery icons (10% steps and new names) are not (and will not) be used on Bionic because Bionic has an old gnome-shell 3.28. Only the new gnome-shell¹ (>= 3.34) implements the more fine-grained battery levels with the new naming.
¹ https://gitlab.gnome.org/GNOME/gnome-shell/commit/bd18313d125aa1873c21b9cce9bbf81a335e48b0

I have mentioned two upstream commits in the issue description, which are done 7 months ago by upstream on the legacy battery icons with the old names. Maybe Yaru has the same issues on the legacy battery icons.

**Comment by Feichtmeier** [comment]
So you say that with yet another set of battery icons for the bionic shell only, this can be fixed?

**Comment by Amr-Ibra** [comment]
I think the existing legacy ones could be improved if they share the same fixes with the upstream ones, and if the fixes could be applied to them.

**Comment by Amr-Ibra** [comment]
Just to be clear, the new battery icons (10% steps) do not overwrite the old battery icons with the legacy names. They both coexist.
gnome-shell >= 3.34 use the new icons, older versions use the legacy icons.

**Comment by Feichtmeier** [comment]
Ah... okay, ...
We try to cherry-pick everything from master into bionic what we can though.
Don't know what the others (especially @ubuntujaggers  because he is defacto THE ONLY icon contributor here) think but IMHO we can't really maintain two sets of icons for master and bionic.

**Comment by ubuntujaggers** [comment]
The old battery icons (with the old names) are still part of the theme, although possibly in the wrong folder. So maybe whatever they did in Adwaita can be quickly done on them. I'll have a look and see if I can work it out.

**Comment by Feichtmeier** [comment]
Same opinion here, I think we should stop to support bionic

**Comment by clobrano** [comment]
I'm torn for Bionic, because it's still supported and used, being an LTS.
I'd say that we should only try to fix bugs and not porting any new stuff. What do you think?

**Comment by ubuntujaggers** [comment]
> I'm torn for Bionic, because it's still supported and used, being an LTS.
> I'd say that we should only try to fix bugs and not porting any new stuff. What do you think?

This seems fair, do I understand correctly that it's just a case of cherry picking something we already did into Bionic?

**Comment by clobrano** [comment]
> it's just a case of cherry picking something we already did into Bionic?

It might be just backporting from master branch, but since the gtk version is different, some fixes might require different approaches.

**Comment by Muqtxdir** [comment]
legacy_battery icons issue solved with #3260
