### ISSUE TITLE
Drop upstream gradients

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1545]
Maybe we should drop the gradients from the upstream drawing file for the headerbar and the buttons.
I think we had this also in some of the proposals I showed you.
Three lines of code change end up like this:

![image](https://user-images.githubusercontent.com/15329494/65438189-0f993100-ddf3-11e9-9af1-686f158b2ba3.png)

![image](https://user-images.githubusercontent.com/15329494/65438223-1de74d00-ddf3-11e9-8cfa-85f618778da1.png)

I think this is closer to the "original yaru" and everthing looks less round in the Z-axis
Downside is that buttons look less "press-me" :man_shrugging: 

We could also only drop the gradient in the headerbar instead

Opinions?

For 20.04 ofc...

**Comment by meetdilip** [comment]
In that case, can the header bar colour be the same as in Yaru 1.0 ?

**Comment by clobrano** [comment]
> I think we had this also in some of the proposals I showed you.

Could you please share again the patch? I'd like to see the difference on a VM

**Comment by Feichtmeier** [comment]
@clobrano https://github.com/ubuntu/yaru/commit/2e8eb6bf7e421ed28135d5cce7fc04e559dc5f94

3 lines, but one could also think about only taking 1 of those 3

**Comment by Feichtmeier** [comment]
But to prevent the buttons to merge with the background, this is also needed in _tweaks
https://github.com/ubuntu/yaru/commit/716fbf8a331a73bd90ab3b6356370ed12197a9c3

**Comment by meetdilip** [comment]
> Maybe we should drop the gradients from the upstream drawing file for the headerbar and the buttons.
> I think we had this also in some of the proposals I showed you.
> Three lines of code change end up like this:
> 
> ![image](https://user-images.githubusercontent.com/15329494/65438189-0f993100-ddf3-11e9-9af1-686f158b2ba3.png)
> 
> ![image](https://user-images.githubusercontent.com/15329494/65438223-1de74d00-ddf3-11e9-8cfa-85f618778da1.png)
> 
> I think this is closer to the "original yaru" and everthing looks less round in the Z-axis
> Downside is that buttons look less "press-me" man_shrugging
> 
> We could also only drop the gradient in the headerbar instead
> 
> Opinions?
> 
> For 20.04 ofc...

I took the liberty of editing the image you posted. I couldn't get the polished white as the header bar though. I used #fbfbfb

![yaru 2 0 white headerbar mockup](https://user-images.githubusercontent.com/6965443/65604385-0233a080-dfc5-11e9-9c05-4298db173384.png)

**Comment by Trine4** [comment]
Personally, I prefer with the gradient that gives a little "depth" and "relief" to the interface.

**Comment by Feichtmeier** [comment]
Alright! Maybe you are right. Just leaving it open for some more opinions for some time.

**Comment by Paz-it** [comment]
+1 for removing the gradient.  Closer to the original is what I like the most.

**Comment by jakedel** [comment]
I'm also in favor of keeping the gradients, subtle depth is a great way to indicate what can be interacted with or not, and is also a little more natural and easy on the eyes compared to solid blocks of color.

**Comment by Feichtmeier** [comment]
Most people are pro keeping it. Closing for now
