### ISSUE TITLE
Wheel in lock screen overlaps button

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1551]
I'm not sure whether this is a bug in Yaru. It has been bugging me in 19.04 and it still is in 19.10 beta, so I decided to report it. The problem is that the loading wheel in lock screen slightly overlaps the login button.

![IMG_20190927_230400](https://user-images.githubusercontent.com/2845433/65810062-a8290b80-e17b-11e9-9e26-5199487dfe55.jpg)

My screen is 3000x2000 and the scaling factor is 2x. This is X11, fractional scaling is not enabled.

## Expected Behavior

Loading wheel doesn't touch the button.

## Actual Behavior

Loading wheel overlaps the button.

## Steps to Reproduce the Problem

  1. Lock your screen.
  1. Login again.
  1. Watch at the wheel.

## Specifications

Software that presents the issue:

Ubutu 19.10 beta, maybe gdm

**Comment by memeplex** [comment]
Notice that the wheel is also vertically ill-aligned.

**Comment by memeplex** [comment]
Moreover, it doesn't happen in the login screen, just the lock screen.

**Comment by Feichtmeier** [comment]
Could you try to record this with 
Control + Shift + Alt + R
?

**Comment by memeplex** [comment]
Unfortunately the recorder just stops when I lock the screen.

**Comment by clobrano** [comment]
Honestly, I've never experienced this in any machine, being real hw or VM. I wonder what's happening there.

**Comment by memeplex** [comment]
Notice that 3x2 is not the usual screen resolution ratio these days, could that be it? I'm going to check it later and let you know.

**Comment by clobrano** [comment]
If this is the reason, it's not something we can fix on our side and maybe there's something already reported upstream

**Comment by memeplex** [comment]
I have been  doing some testing in order to find conditions for reproducibility:

1. With other aspect ratios than 3:2 (4:3, 16:9) the problem is still present.
2. Switching the scaling factor to 1 fixes the issue for any aspect ratio.
3. The problem is also present in Gnome vanilla lock screen.
4. There also is overlapping between the wheel and the cog in the login screen.
5. The overlapping is still there in a Wayland session.

So this seems to be an upstream problem mainly related to screen scaling.

I'm closing and reporting this upstream: https://gitlab.gnome.org/GNOME/gdm/issues/521

**Comment by clobrano** [comment]
Thanks for testing!

**Comment by memeplex** [comment]
They were able to reproduce it in EndelessOS and they're working on a patch for this issue, see https://gitlab.gnome.org/GNOME/gnome-shell/issues/1746#note_687751.

**Comment by memeplex** [comment]
This was fixed upstream :)
