### ISSUE TITLE
Bug icons desktop

### ISSUE THREAD

**Issue by childjc** [ubuntu/yaru#1552]
hi, i am using ubuntu 18.04.3 with yuru ppa, but select yuru or yuru-light and letters of icons of desktop is a gray color...... with yaru dark is perfect white. Is a bug?

**Comment by remiariro** [comment]
Yes, the desktop icons' font color when using Yaru or Yaru-light is now a dark gray that is unreadable over any less-than-insanely-bright background. Only Yaru-dark shows white desktop labels.
It looks awful and makes no sense.

18.04 with Yaru PPA

![2019-09-29-01-50-14](https://user-images.githubusercontent.com/1826466/65826452-9028b900-e25b-11e9-8b87-a41de2410438.png)

**Comment by Feichtmeier** [comment]
Yeah that's my fault

First I thought it's not possible to Backport gtk and shell to bionic but it was somehow manageable
Previous I removed the nautilus desktop styling from _apps
We just need to reinsert this. Sorry.

**Comment by Feichtmeier** [comment]
.nautilus-desktop-window { .nautilus-desktop.view { color: $selected_fg_color; text-shadow: 0px 1px 2px rgba(0, 0, 0, 0.5); }}

**Comment by clobrano** [comment]
closed by #1553
