### ISSUE TITLE
Yaru light does not work with snaps

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1554]
![image](https://user-images.githubusercontent.com/15329494/65946724-c190b880-e404-11e9-8b64-62eb84f4a6ec.png)

I don't know if this can be fixed by providing  yaru-light version in the gtk-commont-themes?
@jhenstridge

**Comment by jhenstridge** [comment]
I've put together [gtk-common-themes MR!16](https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/merge_requests/16) that should solve this.  I think everything looks okay, but if you want to give the resulting snap a try, it is available here:

https://gitlab.gnome.org/jamesh/gtk-common-themes/-/jobs/453740/artifacts/browse

**Comment by Feichtmeier** [comment]
Thank you very much @jhenstridge 
I think I won't have time to test it in the next three weeks though

**Comment by jhenstridge** [comment]
I've merged the branch, since it looks like everything is in place correctly.  If there are any problems, we can fix them later.

**Comment by clobrano** [comment]
Awesome, thanks!

**Comment by Feichtmeier** [comment]
Thank you - fixed after refreshing from gtk-common-themes from --edge

![grafik](https://user-images.githubusercontent.com/15329494/67096359-4ecf5d80-f1b8-11e9-81bf-b8a074af140b.png)
