### ISSUE TITLE
Unexpected element in titlbar of window when window is wide

### ISSUE THREAD

**Issue by digimezzo** [ubuntu/yaru#1555]
## Expected Behavior

Increase horizontal size of a Nautilus Window, by grabbing the right border of the Nautilus window and dragging to th eright.

## Actual Behavior

The Nautilus window became wider, but a unexpected element appeared in the window's titlebar as soon as a certain width was reached.

## Steps to Reproduce the Problem

  1. In Ubuntu 19.10, open a Nautilus window
  2. make it wider by using the mouse
  3. When a certain width is reached, the unexpected element in the titlebar appears

## Specifications

The default Yaru theme of Ubuntu 19.10 is used (version of 1 okt 2019).

## Screenshot of the issue

Nautilus
![image](https://user-images.githubusercontent.com/11945339/65994615-0d3e7300-e494-11e9-9859-a7023c7c83c2.png)

**Comment by clobrano** [comment]
Hi @digimezzo, 

Thanks to taking time to contribute to Yaru. This is actually the intended behavior. Since latest gtk, Nautilus pathbar is linked to the search button when the window is "wide enough" and that element provides the visual connection.

**Comment by Feichtmeier** [comment]
Though it's like Carlo said, I would like to add that if you have concerns with the design, you should ask on the nautilus gitlab repo. But use adwaita gtk and icon theme for the screenshots there ... :)
