### ISSUE TITLE
[dark variant] gedit's cursor is not visible

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1563]
# Expected Behavior

See the cursor in Gedit while using dark variant

## Actual Behavior

Cursor color is the same as background and so not visible

![image](https://user-images.githubusercontent.com/2883614/66293043-0ffef500-e8e6-11e9-8d88-d2dae8654a4b.png)

It seems that Gnome 3.34 (in Arch) uses a dark background, so it could be an upstream fix we missed

**Comment by Feichtmeier** [comment]
Uhm my Gedit window is dark, and thus you can see the cursor:
![Screenshot from 2019-10-31 12-04-32](https://user-images.githubusercontent.com/15329494/67941742-9e5d5280-fbd6-11e9-860e-77902f13c704.png)

@clobrano could you double check if this issue is still present for you?

**Comment by clobrano** [comment]
Indeed, it doesn't seem reproducible anymore, thanks
