### ISSUE TITLE
Third party app: To squircle or not to squircle?

### ISSUE THREAD

**Issue by ztefn** [ubuntu/yaru#1564]
Hi there! I'm in need of a little bit advise.

As @eaglersdeveloper pointed out [on Twitter](https://twitter.com/eaglersdev/status/1078534626514292736) a while ago, [Haguichi](https://github.com/ztefn/haguichi) was the first third party app to ship an [Suru/Yaru style icon](https://github.com/ztefn/haguichi/blob/master/data/icons/suru-source.svg) for Ubuntu. Everything was fine back then.

However, starting Ubuntu 19.04 the Yaru icons have shifted style from _squircle_ to more square. So while the icon I'm shipping looks perfect on Ubuntu 18.04, it looks a little bit off on Ubuntu 19.04 and 19.10 (and 20.04 LTS in 6 months).

So, this left me wandering which road I should take:
1. Keep the Suru _squirle_ style (and be out of place on every Ubuntu version later than 18.04).
2. Update the icon to a more square style (and be out of place only on Ubuntu 18.04).
3. Stop shipping the Suru/Yaru style icons completely and thus have Ubuntu use the [standard GNOME style icon](https://github.com/ztefn/haguichi/blob/master/data/icons/hicolor/scalable/apps/haguichi.svg).
4. Some other option I haven't thought about?

Although it's a waste of effort I'm tending towards option 3 myself. Option 2 might also work if someone from the Yaru team is willing to update the icon.

What do you guys think?

**Comment by clobrano** [comment]
Hi @ztefn,

I believe there's a little misunderstanding. The icon style on 18.04 is the same as in 19.04 and following, this is basically because we already dropped the squircle style, so if you update to the new Yaru icons, it will fit perfectly in 18.04 as well

About option 2 let's summon @ubuntujaggers to see what he thinks :)

**Comment by Feichtmeier** [comment]
But only in the edge channel, right?

**Comment by clobrano** [comment]
Did we switch icon set only on edge? Okay, this is a problem, but it's
going to be released soon, together with Eoan

**Comment by ubuntujaggers** [comment]
Lovely icon! I'm more than happy to update it.

**Comment by ztefn** [comment]
Cool! You're welcome to fork Haguichi master branch and open a pull request any time you want.

Also, if you have any questions don't hesitate to ask!

**Comment by clobrano** [comment]
Very well! Since the work will be done on Haguichi repo, I can close this here. Feel free to reopen it if you think it's necessary. Thanks!
