### ISSUE TITLE
Icon "weather-few-clouds-symbolic.svg" should not be the same as "weather-cloudy-symbolic.svg"

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1566]
The two icons "weather-cloudy-symbolic.svg" and "weather-few-clouds-symbolic.svg" are the same.

The "few-clouds" icon would better have a sun behind the cloud, just like the upstream Adwaita icon.

That affects the graphic in gnome-weather when the weather condition is "few clouds".

**Yaru**
[weather-cloudy-symbolic.svg](https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/status/weather-cloudy-symbolic.svg) 
![grafik](https://user-images.githubusercontent.com/45657128/66422248-a415ad00-ea09-11e9-937f-6f4b75555322.png)

[weather-few-clouds-symbolic.svg](https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/status/weather-few-clouds-symbolic.svg) 
![grafik](https://user-images.githubusercontent.com/45657128/66422411-ef2fc000-ea09-11e9-82b5-ab7a8f750b29.png)

**Upstream Adwaita**
[weather-few-clouds-symbolic.svg](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/status/weather-few-clouds-symbolic.svg) 
![grafik](https://user-images.githubusercontent.com/45657128/66422870-ca881800-ea0a-11e9-97ca-6087dfc8d031.png)

**Comment by ubuntujaggers** [comment]
This is weird...  we _do_ have a suitable weather-few-clouds-symbolic:

![image](https://user-images.githubusercontent.com/38893390/68756168-96070d80-0601-11ea-8953-557e83635cd7.png)

...so there might be a symlink or something that's making the two cloud icons the same.  I'll have a look.
