### ISSUE TITLE
GNOME Shell looking glass isn't too readable in yaru

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/yaru#1570]
Looking glass (Alt+F2 -> `lg` -> Enter) extensions page and some inspection elements aren't much readable.

Extensions page:
![image](https://user-images.githubusercontent.com/345675/66649926-b1ac7c00-ec2f-11e9-8e27-a3e6d92530ac.png)

Text inputted in console and inspection view:

![image](https://user-images.githubusercontent.com/345675/66650043-f59f8100-ec2f-11e9-8abc-b30267b88a5b.png)

**Comment by Feichtmeier** [comment]
It's the same in upstream but we didnt switch to the light variant there. I'd say it's again an upstream task if you have time for this @clobrano 
And then pull it later to yaru

**Comment by Feichtmeier** [comment]
This should be fixed with https://github.com/ubuntu/yaru/pull/1746 please check while you are on testing @3v1n0 :) Best regards

**Comment by Feichtmeier** [comment]
@clobrano removed your assignment because I think I got it with #1746 - hope this was okay? :)

**Comment by clobrano** [comment]
yeah, no problem
