### ISSUE TITLE
Titlebar looks wide on Unity

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ubuntu/yaru#1573]
Some examples with Firefox and GNOME Terminal
![image](https://user-images.githubusercontent.com/13153124/66765382-ce3bf480-ee79-11e9-88da-10e5eca7c18a.png)
![image](https://user-images.githubusercontent.com/13153124/66765487-fe839300-ee79-11e9-9060-7dfdc7d2f543.png)

**Comment by clobrano** [comment]
Hi @YamiYukiSenpai, thanks for contributing to Yaru. 
I believe this issue is visible in Yaru only, right? Not in Ambiance, I mean

**Comment by YamiYukiSenpai** [comment]
It got fixed after I ran the update today and rebooted.

**Comment by Paz-it** [comment]
@YamiYukiSenpai I think Arc have an updated metacity theme . Yaru have none and the Ambiance maybe not updated? Just guessing thou... :question:

**Comment by clobrano** [comment]
Sorry for the silly question: how do I test this? Install Yaru on Unity and select it with gnome-tweaks?

**Comment by clobrano** [comment]
I cannot reproduce this. @YamiYukiSenpai could you tell me if you can reproduce this using Yaru's master branch, please?

**Comment by clobrano** [comment]
This is actually fixed now, probably by #1523
