### ISSUE TITLE
No system-ready sound

### ISSUE THREAD

**Issue by iainlane** [ubuntu/yaru#1575]
ubiquity (the Ubuntu installer) tries to play 'system-ready' to indicate to visually impared users that the system is ready - so they can start the screen reader or whatever they need.

Unfortunately yaru-theme-sound doesn't ship this sound. This means that we broke it when we switch from the old ubuntu-sounds theme.

[This is cross-posted from Launchpad.](https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1848217)

**Comment by clobrano** [comment]
@madsrh, could you have a look at this?

**Comment by madsrh** [comment]
Could we symlink the `desktop-login.ogg` (which isn't in use)?

**Comment by clobrano** [comment]
It sounds good to me (no pun intended :D)

**Comment by madsrh** [comment]
> It sounds good to me (no pun intended :D)

Lol and 👍 can you create the symlink?

I wonder if it's too long compared to the short 1s drumroll. 

Is this only played in ubiquity or is at every boot? 🤔 (I can't test atm)

**Comment by clobrano** [comment]
> I wonder if it's too long compared to the short 1s drumroll.

uhm, good question

**Comment by clobrano** [comment]
I might be doing something wrong. I both symlinked and copied the file giving the name "system-ready.oga", but it does not play using the command 

    $ /usr/bin/canberra-gtk-play --id="system-ready"                                                                                                                  
    Failed to play sound: File or data not found

This one works instead

    $ /usr/bin/canberra-gtk-play --id="system-ready" -f /usr/share/sounds/Yaru/stereo/system-ready.oga

here the full content of the sound folder

```
$ ls -l /usr/share/sound/Yaru/stereo 
total 644
-rw-r--r-- 1 root root   8078 set 13 08:23 audio-volume-change.oga
-rw-r--r-- 1 root root  23389 set 10 15:41 battery-low.oga
-rw-r--r-- 1 root root  15813 set 10 15:41 bell.oga
-rw-r--r-- 1 root root  48977 set 10 15:41 complete.oga
-rw-r--r-- 1 root root 159288 set 10 15:41 desktop-login.oga
-rw-r--r-- 1 root root  21799 set 10 15:41 device-added.oga
-rw-r--r-- 1 root root  20096 set 10 15:41 device-removed.oga
-rw-r--r-- 1 root root  18476 set 10 15:41 dialog-error.oga
-rw-r--r-- 1 root root  20936 set 10 15:41 dialog-question.oga
-rw-r--r-- 1 root root  16992 set 10 15:41 dialog-warning.oga
-rw-r--r-- 1 root root  19100 set 10 15:41 message-new-email.oga
-rw-r--r-- 1 root root  20907 set 10 15:41 message-new-instant.oga
-rw-r--r-- 1 root root  19100 set 10 15:41 message.oga
-rw-r--r-- 1 root root 159288 ott 18 15:52 system-ready.oga
-rw-r--r-- 1 root root  63914 set 10 15:41 trash-empty.oga
```

any idea?

**Comment by madsrh** [comment]
There's some issue with the path, because if I move the file to `/usr/share/sounds/ubuntu/stereo/system-ready.oga` it works just fine 🤔

**Comment by clobrano** [comment]
I wonder if I was in Yaru or Ubuntu session when I tested. Probably the path is `session-name` dependent

**Comment by clobrano** [comment]
Report what @seb told me on IRC for future reference:

> the sound theme/system-ready thing, the path used for lookup is $XDG_DATA_DIRS/sounds

btw, now it works with the symlink in both Ubuntu and Yaru session (which is normal). I was probably doing something wrong
