### ISSUE TITLE
Sublime Text and VS Code have white menubars on Ubuntu 19.10

### ISSUE THREAD

**Issue by logix2** [ubuntu/yaru#1576]
Sublime Text and VS Code have white menubars on Ubuntu 19.10, while the application window is dark, which looks ugly and inconsistent. Screenshot: [https://i.imgur.com/l7OyXeI.png](https://i.imgur.com/l7OyXeI.png)

**Comment by clobrano** [comment]
Hi @logix2, it is intended. You might prefer to start it in dark mode instead, which has dark menu

**Comment by ph03** [comment]
This is quite annoying, as other apps (in particular Thunderbird) are unusable with the fully dark mode theme.

Where is this particular menu bar color defined? Perhaps we can just change it locally to revert to the pre-ubuntu 19.10 state (without changing it upstream)?

**Comment by clobrano** [comment]
There isn't **one** specific place. Colors are generated per variant "light/dark" and then used in several places. I'll see how is the experience with thiese apps

**Comment by clobrano** [comment]
Btw, it is not something to be changed upstream, since upstream doesn't have a theme with dark headerbars only :)

**Comment by neuged** [comment]
Is there any way to reopen this issue? These applications looked absolutely gorgeous on 19.04.

**Comment by clobrano** [comment]
I do agree it was better in 19.04, but the code base was really different.
I am considering re-implementing this, but it takes time, *it is easy to
introduce regressions* and, unfortunately, there are other priorities. If
any of you want to propose a PR I'll be more than happy to review it.
Hint: the file where the modification should land is *_headerbar.scss*

**Comment by YuriFontella** [comment]
This inconsistency still remains in the update to 20.04
https://imgur.com/a/CqsTUfK

Some other themes, it doesn't.
https://imgur.com/a/1PTsR81

The theme is perfect, it would be nice if the application menu were uniform with the windows.

**Comment by clobrano** [comment]
Thanks @YuriFontella, any chance you would like to propose a patch?

**Comment by YuriFontella** [comment]
Look, that when I change to yaru-dark, the color of the menu is changed to a lighter black scale, a dark gray. The same happens with yaru-light, a very light gray window, and the white menu.

https://imgur.com/a/gQAVefP yaru-dark

It seems to be the default theme, not leaving the menu the same color as the window. Just change it to the same color pattern, with a different shade.

If so, that's fine.

Otherwise, I believe that the menu should follow the same pattern as the window. (sorry english)

**Comment by Feichtmeier** [comment]
Okay.
Despite the fact that vscode supports a CSD mode with self drawn menus, I think that the headerbar is sometimes considered as a source for menu styling. Before we fastly change anything here, we'll need to investigate what's actually happening.

Gtk3 applications are doing fine with the three themes. 
The theme you've linked is not a "mixed" theme but purely light.

**Comment by Feichtmeier** [comment]
The styling that is being sucked into sublime text definitely does not come from GtkMenuBar or GtkMenu

**Comment by mzur** [comment]
Any update on this issue? I'm willing to put some work into this if anyone can point out where to start.
