### ISSUE TITLE
[19.10] Inconsistent headerbar color mix in Evince

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1577]
## Expected Behavior

Headerbars are dark in Yaru theme, including all fields.

## Actual Behavior

Evince headerbar has some light fields. Compare with Nautilus (behind):

![image](https://user-images.githubusercontent.com/2845433/67139413-59c0d700-f226-11e9-810e-0f4a4e9918c0.png)

## Steps to Reproduce the Problem

  1. Open Evince
  
## Software that presents the issue

- Name: Evince
- Version: 3.34.1

## Yaru version

Yaru 19.10.4

**Comment by clobrano** [comment]
I'm sorry, but the expectation is wrong. Entries are expected to be white in this variant

**Comment by memeplex** [comment]
Oh, I was afraid of that answer, it looks a bit awful to me now, but probably it will grow on me :)
