### ISSUE TITLE
Wrong padding in app folder rename popup

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1579]
Maybe an upstream issue:

![image](https://user-images.githubusercontent.com/2845433/67152404-6cc9ba80-f2ab-11e9-983a-adf152ae9d1d.png)

There is no left padding and, OTOH, right padding might be too large.

## Software that presents the issue

- Name: gnome-shell
- Version: 3.34.1

## Yaru version

- Name: yaru-theme-gnome-shell
- Version: 19.10.4

**Comment by Feichtmeier** [comment]
This is expected to be fixed with https://github.com/ubuntu/yaru/pull/1572
