### ISSUE TITLE
Build problem after directory layout change

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#1583]
After the changes to allow switching between dark and light shell themes, the Arch PKGBUILD I'm using broke. I figured the PKGBUILD needed to be updated to reflect the changes (It deletes directories in order to split yaru into multiple packages, sound, gtk, shell, session, icons so is vulnerable to changes in directory layout).

I thought I'd make a non-split package so that yaru can just be installed all at once and the PKGBUILD is no longer vulnerable to changes like this. But I'm hitting an issue and wondering if it is an issue with Yaru itself.

I'm building like so:

```
cd /tmp
git clone https://github.com/ubuntu/yaru
meson yaru build
ninja -C build
mkdir pkg
DESTDIR=/tmp/pkg ninja -C build install
```

And getting the following error during `ninja -C build install`:
```
<snip>
Running custom install script '/tmp/yaru/gnome-shell/src/install-shell.sh Yaru'
ln: failed to create symbolic link '/tmp/pkg/usr/share/gnome-shell/theme/Yaru': No such file or directory
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

Indeed, there is no such directory `usr/share/gnome-shell/theme`. There is `usr/share/themes/gnome-shell` though.

Does the script `gnome-shell/src/install-shell.sh` need to be updated to reflect the recent directory changes? Or am I misunderstanding something?

**Comment by clobrano** [comment]
Hi @chrisjbillington,

the script `install-shell.sh` was introduced with #1578, it's job is to link the new install path `/usr/share/themes/Yaru/gnome-shell` to the old one `/usr/share/gnome-shell/themes/Yaru`. I wonder if the Arch filesystem differs from Ubuntu's one in this regard

**Comment by chrisjbillington** [comment]
Since I'm pointing the installation to a newly created directory (`DESTDIR=/tmp/pkg ninja -C build install`) in order to create a package rather than installing on my system, I'm under the impression that what's actually on my system isn't relevant at this stage.

Even if I were installing to the root filesystem directly, wouldn't it still be the case that `/usr/share/gnome-shell/themes/Yaru` would not exist on a fresh system that hadn't seen Yaru before?

**Comment by clobrano** [comment]
> Even if I were installing to the root filesystem directly, wouldn't it still be the case that `/usr/share/gnome-shell/themes/Yaru` would not exist on a fresh system that hadn't seen Yaru before?

This is the name of the link, so I don't expect it to fully exist to last `Yaru` substring. 

> ln: failed to create symbolic link '/tmp/pkg/usr/share/gnome-shell/theme/Yaru': No such file or directory 

it seems to me that the `ln` is complaining that the symlink's `target` is missing, not its `link name`

**Comment by chrisjbillington** [comment]
Ah I see. So the parent directory of the link `/tmp/pkg/usr/share/gnome-shell/theme/`, doesn't exist in my package directory, whereas it does exist on my root filesystem.

I can just make my package `mkdir -p` this directory before running ninja - but does this problem not occur when building other packages such as snaps or `.debs`?

If so it is fixed with:

```
--- a/gnome-shell/src/install-shell.sh
+++ b/gnome-shell/src/install-shell.sh
@@ -4,4 +4,5 @@
 project_name="$1"
 prefix="${MESON_INSTALL_DESTDIR_PREFIX}/share"
 
+mkdir -p "${prefix}/gnome-shell/theme/"
 ln -sf "${prefix}/themes/${project_name}/gnome-shell" "${prefix}/gnome-shell/theme/${project_name}"
```

With this change I can build my Arch package :)

**Comment by clobrano** [comment]
I have a problem with the build, but before this step :D

**Comment by chrisjbillington** [comment]
Haha :p

So actually to not end up with a symlink into a build directory after installation, I need to make the following change to a relative symlink:

```diff
diff --git a/gnome-shell/src/install-shell.sh b/gnome-shell/src/install-shell.sh
index d95c3322..3ae9f0d3 100755
--- a/gnome-shell/src/install-shell.sh
+++ b/gnome-shell/src/install-shell.sh
@@ -4,4 +4,5 @@
 project_name="$1"
 prefix="${MESON_INSTALL_DESTDIR_PREFIX}/share"
 
-ln -sf "${prefix}/themes/${project_name}/gnome-shell" "${prefix}/gnome-shell/theme/${project_name}"
+mkdir -p "${prefix}/gnome-shell/theme/"
+ln -sf "../../themes/${project_name}/gnome-shell" "${prefix}/gnome-shell/theme/${project_name}"
```

This might not be normal practice, though I'm not finding much about what other packages do in this context. I think ideally the link target would be absolute with `/usr/share/` as the prefix, and the link itself would be created in `${MESON_INSTALL_DESTDIR_PREFIX}/share`. So the link within the package would be a broken link until installed into an actual system.

I'm sure there is convention for this, I'm just not sure what it is.

In any case now that I understand the issue I can make my package work.

**Comment by chrisjbillington** [comment]
OK, figured it out (sorry, not familiar with meson). I think ideally (ideally for people like me) the link target should use `MESON_INSTALL_PREFIX/share` (this is `/usr/share`), and the link location should use the `MESON_INSTALL_DESTDIR_PREFIX/share` (this is the packaging dir). And the link location's parent directory needs to be created.

Then an absolute link to `/usr/share` is created within the packaging directory, which is a dangling link until actually installed on a system.

```bash
#!/usr/bin/env bash
# -*- coding: UTF-8 -*-

project_name="$1"
destdir_prefix="${MESON_INSTALL_DESTDIR_PREFIX}/share"
install_prefix="${MESON_INSTALL_PREFIX}/share"

mkdir -p "${destdir_prefix}/gnome-shell/theme/"
ln -sf "${install_prefix}/themes/${project_name}/gnome-shell" "${destdir_prefix}/gnome-shell/theme/${project_name}"
```
