### ISSUE TITLE
Eventually revert checks/radios to upstream

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1584]
I feel like [my quick and dirty flattening in _tweaks.scss ](https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_tweaks.scss#L110) somehow went a bit wrong: 

![grafik](https://user-images.githubusercontent.com/15329494/67328244-7d7f6800-f519-11e9-8a8c-0bf1dc9ab403.png)

Resulting in 
- https://github.com/ubuntu/yaru/issues/1530
- transparent bgs for empty boxes
- weird combinations in lists on hover

Maybe we should revert back to the upstream "3d" look until I have time to finish https://gitlab.gnome.org/Teams/Design/os-mockups/issues/25#note_611716 ? 
![grafik](https://user-images.githubusercontent.com/15329494/67330244-63935480-f51c-11e9-84ba-07a871113785.png)
![grafik](https://user-images.githubusercontent.com/15329494/67330298-6db55300-f51c-11e9-864e-75bf75fee976.png)

@clobrano @madsrh @ubuntujaggers

**Comment by madsrh** [comment]
Maybe reverting temporary would be better - I don't know.
When I look at the image above, that black border in the radio/checkbox next to the white text makes my mind 💥🤯 I guess I should file a bug for that 🤔

**Comment by Feichtmeier** [comment]
Oh, well the dark border would stay in the dark theme, but with a gradient and with a background. Open the last two images I posted in a new tab, that's how it would look if we would remove the lines in _tweaks
Just so you don't misunderstand me

But nonetheless they look outdated in yaru and upstream, thus that upstream issue.
(Any good design ideas would be welcome I think on the upstream issue)

**Comment by clobrano** [comment]
For me it's ok

[carlo - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=7tnp5)	[7tnp5]

On October 22, 2019 at 22:13 GMT, Feichtmeier <notifications@github.com> wrote:

Oh, well the dark border would stay in the dark theme, but with a gradient and with a background. Open the last two images I posted in a new tab, that's how it would look if we would remove the lines in _tweaks
Just so you don't misunderstand me

But nonetheless they look outdated in yaru and upstream, thus that upstream issue.
(Any good design ideas would be welcome I think on the upstream issue)

**Comment by Feichtmeier** [comment]
@clobrano what is okay? Reverting it or leaving it as it is? :smile_cat:

**Comment by clobrano** [comment]
It's ok the proposal, that is to revert it

[carlo - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=7to2u)	[7to2u]

On October 23, 2019 at 19:03 GMT, Feichtmeier <notifications@github.com> wrote:

[@clobrano](https://github.com/clobrano) what is okay? Reverting it or leaving it as it is? 😸

**Comment by clobrano** [comment]
Okay, I won't reply from email ever again... Too messy :/

**Comment by clobrano** [comment]
@madsrh, any last idea?

![image](https://user-images.githubusercontent.com/2883614/67432231-357a4700-f5e6-11e9-9baf-11d508414f97.png)  ![image](https://user-images.githubusercontent.com/2883614/67432278-4dea6180-f5e6-11e9-928d-e0c0e45b0b03.png)

**Comment by madsrh** [comment]
@clobrano nope 👍
