### ISSUE TITLE
Printer icon could be better

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1590]
I've never really been happy with the printer icon (although it's not as bad as it was) and I've had to revisit it, because whatever I do for legacy/document-print has to be consistent with the device icon.

I wondered what everyone thought of this...  it's a simpler graphic and (IMO) resembles the other Suru icons a bit more:

![image](https://user-images.githubusercontent.com/38893390/67633571-49a19b00-f8a9-11e9-9a6f-b45ea8182bbd.png)

**Comment by meetdilip** [comment]
Looks nice. If I may, would be nice to change those 3 button colours. More like the Mac theme :)

**Comment by meetdilip** [comment]
I am adding another one. Just for another viewpoint

![printer 3x](https://user-images.githubusercontent.com/6965443/67635081-c6079e80-f8e8-11e9-9b35-cacfa49a6e3c.png)

**Comment by Feichtmeier** [comment]
Hm.... @ubuntujaggers I think I would prefer the current printer icon. I think you really hit the spot with it (is this correct english? :D )

**Comment by meetdilip** [comment]
The current printer icon is something like this, right ?

![printer simple](https://user-images.githubusercontent.com/6965443/67656024-a1f39e00-f978-11e9-8353-ab2f45b57544.png)

**Comment by clobrano** [comment]
Current is this one 

https://raw.githubusercontent.com/ubuntu/yaru/master/icons/Suru/256x256/devices/printer.png
![image](https://user-images.githubusercontent.com/2883614/67656725-e66d4280-f954-11e9-9b12-24ef4cbec8be.png)

> it's a simpler graphic and (IMO) resembles the other Suru icons a bit more

I totally agree with this, the current one is probably the most 3D-ish we have now. Both are fantastic though, so if it is a matter of consistency with new work, I am ok with changing it.

**Comment by Feichtmeier** [comment]
The current icon makes sense in terms of perspective.
The icon @meetdilip posted is a different perspective, the top perspective and makes also sense. 
My problem with your new proposal @ubuntujaggers is that I don't get what perspective it is. It's somehow two perspectives on one :D

**Comment by ubuntujaggers** [comment]
Hmm, looking again I hate them both. Let me take another pass when I'm home...

**Comment by ubuntujaggers** [comment]
Tell you what though: because it's not a quick job to do, I'll finish the legacy action buttons first, and I might end up redoing the document-print button if I can come up with something better for printers in general.

**Comment by ubuntujaggers** [comment]
Okay, is this moving in the right direction:

![image](https://user-images.githubusercontent.com/38893390/67977482-185dfd80-fc10-11e9-959e-28eb915245d9.png)

Current one for context:

![image](https://user-images.githubusercontent.com/38893390/67977399-ed73a980-fc0f-11e9-9019-e3a8b8c77159.png)

**Comment by clobrano** [comment]
Wow, indeed a good step forward 👍

**Comment by ubuntujaggers** [comment]
Okay, I'm fairly happy with this:

![image](https://user-images.githubusercontent.com/38893390/68075804-d619f500-fda4-11e9-97e3-3553b948337d.png)

More or less the same design as current but not quite as crap  :)

**Comment by clobrano** [comment]
Okay, this looks amazing :)
Could you just edit the PR's title in something like "Improve" or "Redesign" printer icon? Just for simplify next changelog

**Comment by ya-d** [comment]
Definitely an improvement! I still find the traffic light buttons very distracting and have never seen anything like that on a printer. (They're also totally out of proportion considering the point of view.) If you have to keep them I tend to prefer the smaller ones from [above](https://github.com/ubuntu/yaru/issues/1590#issuecomment-548520788) and would remove them in all but the largest size. Maybe try a more simple on/off button as seen in the icons posted by meetdilip?

Adding the corner radius to the highlight line is probably too much detail for the smaller sizes?

**Comment by Feichtmeier** [comment]
@ubuntujaggers 
Thanks for the rework!
Do you consider this issue fixed now?

**Comment by ubuntujaggers** [comment]
Yep, we can always add more improvements to any icon at any time - I created the issue because the printer was really bugging me before :)

For instance: @ya-d, when I get chance I'll try your ideas.
