### ISSUE TITLE
application-x-addon-symbolic.svg is missing

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1608]
![image](https://user-images.githubusercontent.com/15329494/68201287-c4f9ff80-ffc1-11e9-8cc8-9a4c03358ddb.png)

Thought it is named
"application-x-addon-symbolic.symbolic.png" in the adwaita icon theme :man_shrugging: 
![image](https://user-images.githubusercontent.com/15329494/68201624-64b78d80-ffc2-11e9-9dd2-fc37f381d8e8.png)

We could try it
"application-x-addon-symbolic.svg" first :smile: 

(ninja assigning @ubuntujaggers :angel: )

Example can be seen in gnome-software
![image](https://user-images.githubusercontent.com/15329494/68201497-2b7f1d80-ffc2-11e9-8b95-e58f7ba25dc2.png)

It wouldn't really be visible but all our symbolic icons are rather outlines and not filled

**Comment by ubuntujaggers** [comment]
This one I thought I did, but badly... I'll look at this while I revisit categories in general :)

**Comment by ubuntujaggers** [comment]
It's coming:

![image](https://user-images.githubusercontent.com/38893390/68707384-8c41c380-0589-11ea-8f37-e400b5777b76.png)
