### ISSUE TITLE
Icon theme parsing errors

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1610]
![image](https://user-images.githubusercontent.com/15329494/68303818-eaac0500-00a4-11ea-9cec-7cff32c8c7a2.png)

:man_shrugging: 

I think we miss the "legacy" dirs in the ....@2 dirs

OR

The index.theme has no "Size=" field for those legacy icons.

@clobrano @ubuntujaggers any other idea?

**Comment by clobrano** [comment]
Maybe both

**Comment by ubuntujaggers** [comment]
Hmm, looks like this predates the addition of legacy folders because there are some other folders in the error messages... is this just something that needs doing in index.theme? What happens when these errors occur?

**Comment by clobrano** [comment]
> What happens when these errors occur?

nothing really, it's managed somehow by the application, but it's annoying. I'll try some fixes later today
