### ISSUE TITLE
Yaru-Dark, auto-complete options are black on black

### ISSUE THREAD

**Issue by BloodyIron** [ubuntu/yaru#1612]
When I'm at a login prompt, or even the search field on github, the auto-complete options list that is presented is black on black. Naturally with the Light theme it's black font on white background, so that's legible.

In this case this really needs to be white text on black background.

I'm using the version of Yaru Black that ships with Ubuntu 19.10.

**Comment by clobrano** [comment]
Hi @BloodyIron, are you talking about text field in browsers only, or even in other applications?
If it's only in browsers, it's up to the browser or the web page to adapt to the current theme, we have no power here :)

**Comment by BloodyIron** [comment]
I haven't tested it with non-browser applications, but switching between Yaru Light and Dark changes the background of the Auto-complete list, so I'm sceptical that nothing can be done here.

**Comment by clobrano** [comment]
If it's only in browser is how it works. Firefox/chrome pick only the background color from the theme and not the text color, that's why the issue.

**Comment by BloodyIron** [comment]
:/
