### ISSUE TITLE
Feature colored folder icons for folder-color package

### ISSUE THREAD

**Issue by phokas** [ubuntu/yaru#1613]
This is a rather general request: Add colored folder icons to the Yaru Icon Theme.

There is a package called [folder-color](https://foldercolor.tuxfamily.org/) in the Ubuntu repositories that lets you choose the color of any folder in Nautilus. A number of icon themes support this, among them the Humanity Icon Theme found in Ubuntu 18.04 LTS.

However, since 20.04 LTS will feature Yaru icons, wouldn't it be desirable to have colored folder icons available for it? [Maybe this work](https://github.com/Jannomag/Yaru-Colors) (not by me) can give an idea of what this could look like.

_Possible_ folder colors would be:
- black
- blue
- cyan
- brown
- green
- gray
- orange
- pink
- magenta
- purple
- red
- yellow

I'm not sure if maintainability would be an issue here. However, since folder-color is not a default package anyway, I don't think the additional folders would ever be a "blocker" as long as that is the case.

So, in general, what do the developers think about this?

**Comment by ubuntujaggers** [comment]
Hi @phokas 

Just wondering: have you seen https://github.com/Jannomag/Yaru-Colors ?

**Comment by phokas** [comment]
Yes, I even link to it in my post.

The "problem" is, Yaru-colors gives you colored folders (and themes), but only one color at a time.

The folder-colors package, which this issue is about, is a tool to select various folder colors in Nautilus, not to have one at a time.

However, the work done by "Jannomag" might be an inspiration for how to solve this issue (if that is feasible, of course).

**Comment by madsrh** [comment]
@Jannomag did some fine work. Perhaps he would be able to create a PR for this request? 📁

**Comment by madsrh** [comment]
I'm closing this request for now. 
If @Jannomag or anyone else want to contribute here, that would be great.

**Comment by costales** [comment]
Hi, 

I adapted (renamed file names and redone directories) the [Yaru-Colors](https://github.com/Jannomag/Yaru-Colors) for working with Folder Color:
https://github.com/costales/yaru-colors-folder-color

You can try it from a PPA with:

```
sudo apt install folder-color
sudo add-apt-repository ppa:costales/yaru-colors-folder-color
sudo apt install yaru-colors-folder-color
nautilus -q
```

All credits for [Jan Schröder](https://github.com/Jannomag)!

A hug.
