### ISSUE TITLE
Unable to build Yaru cursor

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#1630]
I was trying to change the " busy " and " watch " art for Yaru cursor. As instructed in the readme file, I installed python-pil and x11-apps and successfully rendered the cursor theme. I now have the bitmaps folder. But when I try ./x11-make.sh, I get

    $ ./x11-make.sh
    Error reading config file!
    Error reading config file!

Will it be possible for you to help me out of this ? Thanks.

I have an edited source-cursors.svg

------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior

Successful build

## Actual Behavior

$ ./x11-make.sh
Error reading config file!
Error reading config file!

## Steps to Reproduce the Problem

  1. Use ./x11-make.sh command
  1.
  1.

## Software that presents the issue

- Name: Ubuntu
- Version: 18.04

## Yaru version : I downloaded from " master " yesterday

Please report the Yaru version in your system using one of the following commands

* If you installed Yaru from PPA

    `$ apt show communitheme`

* If you installed Yaru via Snap

    `$ snap info communitheme`

* I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

**Comment by clobrano** [comment]
I can't reproduce this. I didn't make changes to the assets, but I can run the script with no issues

Adding some verbose logging I got this:

```
carlo ● cursors $ ./x11-make.sh
+ [ ! -d ../../../Suru/cursors ]
+ xcursorgen all-scroll.in ../../../Suru/cursors/all-scroll
+ xcursorgen bd_double_arrow.in ../../../Suru/cursors/bd_double_arrow
+ xcursorgen bottom_left_corner.in ../../../Suru/cursors/bottom_left_corner
+ xcursorgen bottom_right_corner.in ../../../Suru/cursors/bottom_right_corner
+ xcursorgen bottom_side.in ../../../Suru/cursors/bottom_side
+ xcursorgen bottom_tee.in ../../../Suru/cursors/bottom_tee
+ xcursorgen circle.in ../../../Suru/cursors/circle
+ xcursorgen context-menu.in ../../../Suru/cursors/context-menu
+ xcursorgen copy.in ../../../Suru/cursors/copy
+ xcursorgen cross.in ../../../Suru/cursors/cross
+ xcursorgen crossed_circle.in ../../../Suru/cursors/crossed_circle
+ xcursorgen crosshair.in ../../../Suru/cursors/cell
+ xcursorgen dnd-ask.in ../../../Suru/cursors/dnd-ask
+ xcursorgen dnd-copy.in ../../../Suru/cursors/dnd-copy
+ xcursorgen dnd-link.in ../../../Suru/cursors/dnd-link
+ xcursorgen dnd-move.in ../../../Suru/cursors/dnd-move
+ xcursorgen dnd-no-drop.in ../../../Suru/cursors/dnd-no-drop
+ xcursorgen dnd-none.in ../../../Suru/cursors/dnd-none
+ xcursorgen dotbox.in ../../../Suru/cursors/dotbox
+ xcursorgen fd_double_arrow.in ../../../Suru/cursors/fd_double_arrow
+ xcursorgen grabbing.in ../../../Suru/cursors/grabbing
+ xcursorgen hand1.in ../../../Suru/cursors/hand1
+ xcursorgen hand2.in ../../../Suru/cursors/hand2
+ xcursorgen left_ptr.in ../../../Suru/cursors/left_ptr
+ xcursorgen left_ptr_watch.in ../../../Suru/cursors/left_ptr_watch
+ xcursorgen left_side.in ../../../Suru/cursors/left_side
+ xcursorgen left_tee.in ../../../Suru/cursors/left_tee
+ xcursorgen link.in ../../../Suru/cursors/link
+ xcursorgen ll_angle.in ../../../Suru/cursors/ll_angle
+ xcursorgen lr_angle.in ../../../Suru/cursors/lr_angle
+ xcursorgen move.in ../../../Suru/cursors/move
+ xcursorgen pencil.in ../../../Suru/cursors/pencil
+ xcursorgen plus.in ../../../Suru/cursors/plus
+ xcursorgen pointer-move.in ../../../Suru/cursors/pointer-move
+ xcursorgen question_arrow.in ../../../Suru/cursors/question_arrow
+ xcursorgen right_ptr.in ../../../Suru/cursors/right_ptr
+ xcursorgen right_side.in ../../../Suru/cursors/right_side
+ xcursorgen right_tee.in ../../../Suru/cursors/right_tee
+ xcursorgen sb_down_arrow.in ../../../Suru/cursors/sb_down_arrow
+ xcursorgen sb_h_double_arrow.in ../../../Suru/cursors/sb_h_double_arrow
+ xcursorgen sb_left_arrow.in ../../../Suru/cursors/sb_left_arrow
+ xcursorgen sb_right_arrow.in ../../../Suru/cursors/sb_right_arrow
+ xcursorgen sb_up_arrow.in ../../../Suru/cursors/sb_up_arrow
+ xcursorgen sb_v_double_arrow.in ../../../Suru/cursors/sb_v_double_arrow
+ xcursorgen tcross.in ../../../Suru/cursors/tcross
+ xcursorgen top_left_corner.in ../../../Suru/cursors/top_left_corner
+ xcursorgen top_right_corner.in ../../../Suru/cursors/top_right_corner
+ xcursorgen top_side.in ../../../Suru/cursors/top_side
+ xcursorgen top_tee.in ../../../Suru/cursors/top_tee
+ xcursorgen ul_angle.in ../../../Suru/cursors/ul_angle
+ xcursorgen ur_angle.in ../../../Suru/cursors/ur_angle
+ xcursorgen vertical-text.in ../../../Suru/cursors/vertical-text
+ xcursorgen watch.in ../../../Suru/cursors/watch
+ xcursorgen X_cursor.in ../../../Suru/cursors/X_cursor
+ xcursorgen xterm.in ../../../Suru/cursors/xterm
+ xcursorgen zoom-in.in ../../../Suru/cursors/zoom-in
+ xcursorgen zoom-out.in ../../../Suru/cursors/zoom-out
+ cd ..
```

**Comment by meetdilip** [comment]
Thanks for the try. I downloaded this repo and changed the SVG. bitmaps was generated fine but got stuck with x11-make.sh. It would be great if you can try with my modified SVG ( link below ). Thanks

https://drive.google.com/file/d/1Fxq6wq6rpaKY1we2FlRV5RPNb1YUM19J/view?usp=sharing

**Comment by clobrano** [comment]
I tried, but it works fine on my machine. Could you try to modify the `x11-make.sh` script adding the line `set -x` above the line `THEME=Suru` and then run the script and copy here the  result?

**Comment by meetdilip** [comment]
I got error again

> $ ./x11-make.sh
> + THEME=Suru
> + DIR=../../..
> + cd bitmaps
> + [ ! -d ../../../Suru/cursors ]
> + xcursorgen all-scroll.in ../../../Suru/cursors/all-scroll
> Error reading config file!
> + xcursorgen bd_double_arrow.in ../../../Suru/cursors/bd_double_arrow
> Error reading config file!
> + xcursorgen bottom_left_corner.in ../../../Suru/cursors/bottom_left_corner
> Error reading config file!
> + xcursorgen bottom_right_corner.in ../../../Suru/cursors/bottom_right_corner
> Error reading config file!
> + xcursorgen bottom_side.in ../../../Suru/cursors/bottom_side
> Error reading config file!
> + xcursorgen bottom_tee.in ../../../Suru/cursors/bottom_tee
> Error reading config file!
> + xcursorgen circle.in ../../../Suru/cursors/circle
> Error reading config file!
> + xcursorgen context-menu.in ../../../Suru/cursors/context-menu
> Error reading config file!
> + xcursorgen copy.in ../../../Suru/cursors/copy
> Error reading config file!
> + xcursorgen cross.in ../../../Suru/cursors/cross
> Error reading config file!
> + xcursorgen crossed_circle.in ../../../Suru/cursors/crossed_circle
> Error reading config file!
> + xcursorgen crosshair.in ../../../Suru/cursors/cell
> Error reading config file!
> + xcursorgen dnd-ask.in ../../../Suru/cursors/dnd-ask
> Error reading config file!
> + xcursorgen dnd-copy.in ../../../Suru/cursors/dnd-copy
> Error reading config file!
> + xcursorgen dnd-link.in ../../../Suru/cursors/dnd-link
> Error reading config file!
> + xcursorgen dnd-move.in ../../../Suru/cursors/dnd-move
> Error reading config file!
> + xcursorgen dnd-no-drop.in ../../../Suru/cursors/dnd-no-drop
> Error reading config file!
> + xcursorgen dnd-none.in ../../../Suru/cursors/dnd-none
> Error reading config file!
> + xcursorgen dotbox.in ../../../Suru/cursors/dotbox
> Error reading config file!
> + xcursorgen fd_double_arrow.in ../../../Suru/cursors/fd_double_arrow
> Error reading config file!
> + xcursorgen grabbing.in ../../../Suru/cursors/grabbing
> Error reading config file!
> + xcursorgen hand1.in ../../../Suru/cursors/hand1
> Error reading config file!
> + xcursorgen hand2.in ../../../Suru/cursors/hand2
> Error reading config file!
> + xcursorgen left_ptr.in ../../../Suru/cursors/left_ptr
> Error reading config file!
> + xcursorgen left_ptr_watch.in ../../../Suru/cursors/left_ptr_watch
> Error reading config file!
> + xcursorgen left_side.in ../../../Suru/cursors/left_side
> Error reading config file!
> + xcursorgen left_tee.in ../../../Suru/cursors/left_tee
> Error reading config file!
> + xcursorgen link.in ../../../Suru/cursors/link
> Error reading config file!
> + xcursorgen ll_angle.in ../../../Suru/cursors/ll_angle
> Error reading config file!
> + xcursorgen lr_angle.in ../../../Suru/cursors/lr_angle
> Error reading config file!
> + xcursorgen move.in ../../../Suru/cursors/move
> Error reading config file!
> + xcursorgen pencil.in ../../../Suru/cursors/pencil
> Error reading config file!
> + xcursorgen plus.in ../../../Suru/cursors/plus
> Error reading config file!
> + xcursorgen pointer-move.in ../../../Suru/cursors/pointer-move
> Error reading config file!
> + xcursorgen question_arrow.in ../../../Suru/cursors/question_arrow
> Error reading config file!
> + xcursorgen right_ptr.in ../../../Suru/cursors/right_ptr
> Error reading config file!
> + xcursorgen right_side.in ../../../Suru/cursors/right_side
> Error reading config file!
> + xcursorgen right_tee.in ../../../Suru/cursors/right_tee
> Error reading config file!
> + xcursorgen sb_down_arrow.in ../../../Suru/cursors/sb_down_arrow
> Error reading config file!
> + xcursorgen sb_h_double_arrow.in ../../../Suru/cursors/sb_h_double_arrow
> Error reading config file!
> + xcursorgen sb_left_arrow.in ../../../Suru/cursors/sb_left_arrow
> Error reading config file!
> + xcursorgen sb_right_arrow.in ../../../Suru/cursors/sb_right_arrow
> Error reading config file!
> + xcursorgen sb_up_arrow.in ../../../Suru/cursors/sb_up_arrow
> Error reading config file!
> + xcursorgen sb_v_double_arrow.in ../../../Suru/cursors/sb_v_double_arrow
> Error reading config file!
> + xcursorgen tcross.in ../../../Suru/cursors/tcross
> Error reading config file!
> + xcursorgen top_left_corner.in ../../../Suru/cursors/top_left_corner
> Error reading config file!
> + xcursorgen top_right_corner.in ../../../Suru/cursors/top_right_corner
> Error reading config file!
> + xcursorgen top_side.in ../../../Suru/cursors/top_side
> Error reading config file!
> + xcursorgen top_tee.in ../../../Suru/cursors/top_tee
> Error reading config file!
> + xcursorgen ul_angle.in ../../../Suru/cursors/ul_angle
> Error reading config file!
> + xcursorgen ur_angle.in ../../../Suru/cursors/ur_angle
> Error reading config file!
> + xcursorgen vertical-text.in ../../../Suru/cursors/vertical-text
> Error reading config file!
> + xcursorgen watch.in ../../../Suru/cursors/watch
> Error reading config file!
> + xcursorgen X_cursor.in ../../../Suru/cursors/X_cursor
> Error reading config file!
> + xcursorgen xterm.in ../../../Suru/cursors/xterm
> Error reading config file!
> + xcursorgen zoom-in.in ../../../Suru/cursors/zoom-in
> Error reading config file!
> + xcursorgen zoom-out.in ../../../Suru/cursors/zoom-out
> Error reading config file!
> + cd ..

**Comment by clobrano** [comment]
> * xcursorgen all-scroll.in ../../../Suru/cursors/all-scroll
>   Error reading config file!

It's basically saying that the it cannot read file `all-scroll.in` in current directory, which should be `icon/src/cursor/bitmap`

**Comment by meetdilip** [comment]
`bitmaps` was generated by the script. I am not sure what went wrong. I am attaching the whole folder. Only thing I changed is `source-cursors.svg` . If possible, please look into it. Thanks

**Comment by clobrano** [comment]
`bitmap` is part of Yaru repository though (https://github.com/ubuntu/yaru/tree/master/icons/src/cursors/bitmaps). If your bitmaps folder is empty or does not have all the files expected by `x11-make.sh`, the problem was probably in `render-cursors.py`

**Comment by meetdilip** [comment]
I am not sure. Here is my folder. I got it from this repo and svg is all that I have changed. Thanks.

[src.zip](https://github.com/ubuntu/yaru/files/3862734/src.zip)

**Comment by clobrano** [comment]
how did you call `render-cursor.py` script?

**Comment by meetdilip** [comment]
As in `readme`

`./render-cursors.py source-cursors.svg`

https://github.com/ubuntu/yaru/blob/master/icons/src/cursors/README.md

**Comment by clobrano** [comment]
Tried again with your svg and running python script first, everything worked fine.

I suggest you to copy your svg into a newly cloned Yaru repo, double check that `bitmaps` folder is complete before and after running the python script.

**Comment by meetdilip** [comment]
I see. No idea why it didn't work for me. If you have completed the build, can you share it with me, please ? 
There was no bitmaps folder when I ran the Python script. The script created that folder. I am not sure what to check for before and after. Thanks.

**Comment by meetdilip** [comment]
Downloaded this repo again and extracted it. Deleted `bitmaps` folder and `svg` file. Used my SVG file. Started render command. bitmaps folder took time and was completed using render script. When I tried `./x11-make.sh` , same error occurred. 

Then I tried ./win32-make.sh the result was an error
```

$ ./w32-make.sh
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'tcross.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'all-scroll.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'bd_double_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'bottom_left_corner.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'bottom_right_corner.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'bottom_side.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'bottom_tee.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'circle.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'context-menu.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'copy.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'cross.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'crossed_circle.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'crosshair.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'dnd-ask.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'dnd-copy.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'dnd-link.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'dnd-move.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'dnd-no-drop.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'dnd-none.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'dotbox.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'fd_double_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'grabbing.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'hand1.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'hand2.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'left_ptr.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'left_ptr_watch.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'left_side.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'left_tee.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'link.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'll_angle.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'lr_angle.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'move.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'pencil.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'plus.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'pointer-move.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'question_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'right_ptr.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'right_side.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'right_tee.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'sb_down_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'sb_h_double_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'sb_left_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'sb_right_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'sb_up_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'sb_v_double_arrow.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'top_left_corner.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'top_right_corner.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'top_side.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'top_tee.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'ul_angle.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'ur_angle.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'vertical-text.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'watch.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'X_cursor.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'xterm.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'zoom-in.in'
Traceback (most recent call last):
  File "../anicursorgen.py", line 392, in <module>
    sys.exit (main ())
  File "../anicursorgen.py", line 83, in main
    input_config = open (args.input_config, 'rb')
IOError: [Errno 2] No such file or directory: 'zoom-out.in'
```

**Comment by meetdilip** [comment]
What you said was right. .in files were not produced in bitmaps folder by the render script. I am not sure why .in files were made.

**Comment by clobrano** [comment]
Honestly, I've never used this script. Could you tell me which is your expected workflow? Maybe this way I can figure out what's the problem

**Comment by meetdilip** [comment]
When I download the repo, I take out the `src` folder. Inside it, I go to `cursors` folder. Then I delete `bitmaps` folder and replace `source-cursors.svg` with my own custom SVG. 

Then, inside the `cursors` folder, I run `./render-cursors.py source-cursors.svg` . But that is only creating folders and PNG, not `.in` files in `bitmaps`. Assuming that everything is fine, I run `./x11-make.sh`. It creates a folder named `Suru>cursors` outside `src` folder inside which I am performing those actions

Assuming that my laptop is not ready, I tried this on my desktop. I still got folders and PNG in `bitmaps` but not the `.in` files. So I took the .in files from the Suru repo and put it in the `bitmaps` folder and then tried `./x11-make.sh`. This time `Suru >cursors` folder outside `src` folder has some PNG.

I am not sure what is wrong. Please see if you can do anything. Thanks.

**Comment by clobrano** [comment]
Silly question maybe, but are you sure you're supposed to delete the bitmaps folder?

Looking at the pythons script, it doesn't seem supposed to generate any `.in` file, only the files inside bitmaps subfolders (e.g. 24x24, ...)

**Comment by meetdilip** [comment]
I see. I wondered the same. That is why I added the `.in` files from suru repo I downloaded on my desktop. That worked a bit. ie, `Suru>cursor`s folder alongside `src` folder now had some PNG. But even that is no useful cursor theme.

Do you want me to try without deleting `bitmaps` ?

**Comment by clobrano** [comment]
> Do you want me to try without deleting `bitmaps` ?

yes. It seems that the `.in` files simply instruct `xcursorgen` where to find the PNG files (generated by `render-cursor.py`) and some other metadata

**Comment by meetdilip** [comment]
When I tried without touching `bitmaps` folder, it says

```
name@name-laptop-2005:~/Downloads/yaru-master/icons/src/cursors$ ./render-cursors.py source-cursors.svg
Inkscape 0.92.4 (unknown) interactive shell mode. Type 'quit' to quit.
```

**Comment by meetdilip** [comment]
Inkscape was open. I closed it and tried. This is what I got

> :~/Downloads/yaru-master/icons/src/cursors$ ./render-cursorspy
> 
> Call me with the SVG as a parameter.
> 
> Traceback (most recent call last):
>   File "./render-cursors.py", line 618, in <module>
>     fatalError("\nCall me with the SVG as a parameter.\n\n")
>   File "./render-cursors.py", line 88, in fatalError
>     cleanup()
>   File "./render-cursors.py", line 75, in cleanup
>     for inkscape, inkscape_stderr, inkscape_stderr_thread in inkscape_instances:
> NameError: global name 'inkscape_instances' is not defined

**Comment by meetdilip** [comment]
@clobrano please forget the above error. It was due to a typo in command.

**Comment by meetdilip** [comment]
Step 2 : I kept the `.in` files intact and moved the folders containing PNG. Now used command `./render-cursors.py source-cursors.svg` . It is generating folders and PNG. I will try `./x11-make.sh` after that.

**Comment by clobrano** [comment]
> When I tried without touching `bitmaps` folder, it says
> 
> ```
> name@name-laptop-2005:~/Downloads/yaru-master/icons/src/cursors$ ./render-cursors.py source-cursors.svg
> Inkscape 0.92.4 (unknown) interactive shell mode. Type 'quit' to quit.
> ```

I guess this is expected

**Comment by meetdilip** [comment]
It will take some time

> >Background RRGGBBAA: ffffff00
> Area 312:408:336:432 exported to 32 x 32 pixels (128 dpi)
> Bitmap saved as: bitmaps/32x32/watch_0007.png
> >Background RRGGBBAA: ffffff00
> Area 312:408:336:432 exported to 48 x 48 pixels (192 dpi)
> Bitmap saved as: bitmaps/48x48/watch_0007.png
> >Background RRGGBBAA: ffffff00
> Area 312:408:336:432 exported to 64 x 64 pixels (256 dpi)
> Bitmap saved as: bitmaps/64x64/watch_0007.png

Above is a part of the command line progress

**Comment by meetdilip** [comment]
Looks like bitmaps folder is fine. `Suru > cursors` should have 179 items ( as in repo ). For the first time, `Suru > cursors` is not blank and after 20 minutes have 57 `cur` files. I think we have to give it time.

**Comment by meetdilip** [comment]
@clobrano I kept the PC and Terminal ON till now. But nothing. The same 57 files. What to do ? :(

**Comment by meetdilip** [comment]
Looks like that's all. The cursor theme is working. I changed the pointer and that is live now. So is the busy icon. Thanks.

**Comment by meetdilip** [comment]
Ok. This is strange. I let my desktop run `./x11-make.sh` for 2.5 hours. Not run, I simply did not close the terminal and let the desktop as it is. After 2.5 hours, it got 179 files with 34 MB. Same as what we have in the repo, but with my modifications. That means it worked correctly if we give an enormous amount of time. Perhaps something to do with packages on my laptop as well. Right now, looks like everything is solved. Thanks.

**Comment by clobrano** [comment]
I didn't expect it to take so long, but at least the configuration is correct :+1:  :)

**Comment by meetdilip** [comment]
The `cursor waiting` icon is still the blue one. I don't know from where it fetched that shape and colour. Perhaps `.in` files store such data.

**Comment by meetdilip** [comment]
@ubuntujaggers This time gave it 4 hours. Tried an old Yaru-master, the latest Yaru-master, latest Suru-master. Up to Bitmap folder it is working fine, but when I try `./x11-make.sh` with the latest `yaru-master`, I get this and it is stuck here

![Screenshot from 2020-03-02 09-27-01](https://user-images.githubusercontent.com/6965443/75644332-00eb5b80-5c68-11ea-8587-0c776bfed4b5.png)
