### ISSUE TITLE
Use Gnome shell theme in 18.04 through .themes folder

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#1634]
------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior

Put gnome-shell folder in .themes > Yaru to get Gnome shell theme

(What you were trying to do)

## Actual Behavior
Not able to see Gnome shell theme in Gnome Tweaks
(What happened instead)

## Steps to Reproduce the Problem

  1. I have a Yaru theme folder from a previous installation. I have put it in .themes folder and it works fine
  1. But when I add gnome-shell folder the same way it does not work
  1.

## Software that presents the issue

- Name: Ubuntu 
- Version: 18.04

## Yaru version

Please report the Yaru version in your system using one of the following commands

* If you installed Yaru from PPA

    `$ apt show communitheme`

* If you installed Yaru via Snap

    `$ snap info communitheme`

* I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

Is it possible that I can build the gnome-shell folder alone and add in .themes > Yaru which works fine for me ? Thanks.

**Comment by clobrano** [comment]
Gnome-shell is not a gtk theme, so as far as I know, the `.theme` folder won't work in any case.

**Comment by meetdilip** [comment]
The reason I asked, I took the `Materia` theme folder from `usr/share` and used it in `.themes` folder. Inside `Materia` folder, there is a folder called `gnome-shell`. And when I used Gnome Tweaks, I am able to use their Gnome shell theme. 

I am willing to let it go. Just wanted to ask whether I can build the content of `gnome-shell` folder in Yaru and use it on 18.04. Because I am facing severe intermittent keyboard freeze while using the communiTheme snap. Thanks.

**Comment by clobrano** [comment]
I double-checked User Theme g-s extension and indeed it looks into `$HOME/.themes` for custom theme, cool!
So the answer should be affirmative, since we already support User Theme extension to change from light to dark variant, I didn't test it though.

**Comment by meetdilip** [comment]
I just got the shell theme working. Took the files from 19.10 live session and put them in .themes/yaru/gnome-shell . I think it is working fully.

**Comment by clobrano** [comment]
Perfect :)
