### ISSUE TITLE
Dark Theme for Gnome Shell

### ISSUE THREAD

**Issue by otavioschwanck** [ubuntu/yaru#1637]
Would be nice to have a dark theme for gnome shell too.  It look weird when you are using the dark GTK theme.

**Comment by clobrano** [comment]
Hi! There is a dark variant. You need to install user theme gnome shell extension to select it.

**Comment by otavioschwanck** [comment]
> Hi! There is a dark variant. You need to install user theme gnome shell extension to select it.

I already installed and only shows the default (Padrão):

![image](https://user-images.githubusercontent.com/9551316/70378945-a14e1000-1905-11ea-94d3-c58c7e1cd19c.png)

**Comment by clobrano** [comment]
Version 19.10.4, released with Ubuntu 19.10 does not have this feature enabled already. You either need to install from source, install the snap version or the PPA (options are in order of preference).
