### ISSUE TITLE
yaru-dark shell theme for 18.04

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#1638]
I just need to know the CSS class where I can change the colour of these icons. Thanks.

------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior
Visible icons
(What you were trying to do)

## Actual Behavior

![icon yaru-dark](https://user-images.githubusercontent.com/6965443/69490185-0c312d00-0eaa-11ea-9bfe-d92bec5acd01.png)

(What happened instead)

## Steps to Reproduce the Problem

  1. Use gnome-shell.css for 19.10 in yaru-dark > gnome-shell
  1.
  1.

## Software that presents the issue

- Name: Ubuntu
- Version: 18.04

## Yaru version

Took from a live session in 19.10

Please report the Yaru version in your system using one of the following commands

* If you installed Yaru from PPA

    `$ apt show communitheme`

* If you installed Yaru via Snap

    `$ snap info communitheme`

* I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

**Comment by Feichtmeier** [comment]
``` 
 .system-menu-action {
    -st-icon-style: symbolic;
    color: $fg_color;
    border-radius: 32px; /* wish we could do 50% */
    padding: 13px;
    border: 1px solid $_bubble_borders_color;

    &:hover, &:focus {
      background-color: $_hover_bg_color;
      color: $fg_color;
      border: none;
      padding: 14px;
    }
    &:active { 
      background-color: $_active_bg_color;
      color: $fg_color;
    }

    & > StIcon { icon-size: 16px; }
  }
```

but just toggle the version to dark in gnome-shell/src/gnome-shell.scss

then $fg_color and $bg_color inverts

**Comment by meetdilip** [comment]
I think it went well. But the brightness and headphone buttons did go as planned. I am happy with this one though :) Thanks @Feichtmeier 

![system menu dark](https://user-images.githubusercontent.com/6965443/69494860-926b6480-0ee6-11ea-94e7-220c7d973bff.gif)

**Comment by Feichtmeier** [comment]
I would change stuff in the **C**SS files AT ALL :)

Rather change 
https://github.com/ubuntu/yaru/blob/bionic/gnome-shell/src/gnome-shell.scss#L1
This to **dark**

**Comment by meetdilip** [comment]
The files I am using are from my previous snap installation. I was facing frequent keyboard and mouse freeze while using communiTheme snap in 18.04. I reported a bug, but nothing happened. Now only chance of using Yaru is to use those copied files and make changes to them. 

I was not sure which branch was Bionic. I tried not to trouble you guys much :)

Thanks.

**Comment by Feichtmeier** [comment]
I am pretty sure the theme has nothing to do with your keyboard stuck :D 

I would rather remove the snap, reboot, re install the snap (from edge) and reboot again and login into the session

**Comment by meetdilip** [comment]
You are right. The freeze bug is there in default Ubuntu as well for some users like me. But it is severe when I use communiTheme session. I have reinstalled 18.04 a couple of times after that.

**Comment by meetdilip** [comment]
Now that you mentioned, I would like to try. How can I get the bionic branch ?

**Comment by Feichtmeier** [comment]
```
sudo apt install libgtk-3-dev git meson sassc
git clone https://github.com/ubuntu/yaru.git
cd yaru
git checkout bionic
meson build
cd build
sudo ninja install
```

**Comment by meetdilip** [comment]
Thanks. At which point should I edit the SCSS file ?

**Comment by Feichtmeier** [comment]
Before the last step

**Comment by meetdilip** [comment]
Everything went well. Thanks a lot :)

**Comment by meetdilip** [comment]
I don't get startup and shutdown sounds. Only sound is when I click the slider for sound control. Is there anything we can do ?

**Comment by Feichtmeier** [comment]
> I don't get startup and shutdown sounds. Is there anything we can do ?

https://github.com/ubuntu/yaru/blob/master/CONTRIBUTING.md#testing-desktop-login-sound

**Comment by meetdilip** [comment]
Tried twice. No sound on login :(

![Screenshot from 2019-11-27 08-41-50](https://user-images.githubusercontent.com/6965443/69690430-c8c8ff80-10f1-11ea-81fb-fc387b43fe52.png)

**Comment by clobrano** [comment]
Have you tried executing below command in a shell?

```
/usr/bin/canberra-gtk-play --id="desktop-login" --description="GNOME Login"
```

does it work?

**Comment by meetdilip** [comment]
Forgive me, by shell you mean as command in the startup window posted above ?

**Comment by meetdilip** [comment]
This one on `Terminal` helped

> gsettings set org.gnome.desktop.sound theme-name Yaru

Thanks. :)
