### ISSUE TITLE
Battery icon is red when the laptop has 30% battery left; it should only turn red when it hits 10%

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1646]
first reported here https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1854179

**Comment by Amr-Ibra** [comment]
Upstream Adwaita icons had some battery fixes, maybe Yaru needs similar fixes:

adjust batteries 20 and 30
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/5e5fcc700aec3d23c32bd8cda700a14c8e589643

add ! to battery level 0
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/73122bcb907a66c7f0a31f519d3940dd645010f3

add missing renders
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/9b0641cf1bb4f10d9e0bd79a832a14afbc7ade8f

battery 0 exclamation mark in style
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/56f663c61bd27c8dc5c3e612aff85cca89c0e4b3
