### ISSUE TITLE
Huge padding between menu action in top bar 

### ISSUE THREAD

**Issue by keshavbhatt** [ubuntu/yaru#1655]
On Ubuntu 19.10 there are huge paddings between menu actions which making the menu with 3 actions cover a lot of space in screen. I don't know why these random padding are added at first place. this is either coming from gnome shell theme or from gtk theme which is set to yaru.

**Comment by Feichtmeier** [comment]
Screenshot please

**Comment by keshavbhatt** [comment]
![photo_2019-12-09_17-51-25](https://user-images.githubusercontent.com/5965031/70435313-8bc71a80-1aac-11ea-84a3-5819279bdc4c.jpg)

**Comment by Feichtmeier** [comment]
Uhm, I'm pretty sure this doesn't happen on a fresh installation but can't check until tonight.
@clobrano can you confirm this?

**Comment by clobrano** [comment]
I can't reproduce this on "normal" apps like Nautilus

**Comment by keshavbhatt** [comment]
@clobrano this thing is coming from gnome shell, with yaru theme on ubuntu 19.10 with no external extension enabled. i will check with other apps tonight and update.

**Comment by clobrano** [comment]
It seems not reproducible with gnome-session, so it might be indeed something we do in Yaru

**Comment by keshavbhatt** [comment]
i think the height of that widget is somehow somewhere is being set to fixed. In qt we do widget->adjustSize() to update widget height to minimum required.

**Comment by clobrano** [comment]
It is reproducible with gnome software too, very strange

**Comment by clobrano** [comment]
Ok, reproduced it also on Fedora, this is very likely a gnome-shell thing. Thanks for discovering it ;)

**Comment by clobrano** [comment]
Gnome-software opened as first application
![image](https://user-images.githubusercontent.com/2883614/70453081-72bc6a80-1aa8-11ea-90a4-f7cd2078c0e4.png)

Gnome-software after Nautilus has been opened as well
![image](https://user-images.githubusercontent.com/2883614/70453103-7c45d280-1aa8-11ea-825f-e58abc035e26.png)

**Comment by clobrano** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/issues/2012
