### ISSUE TITLE
Workspace switcher doesn't seem to show the Yaru theme (19.10)

### ISSUE THREAD

**Issue by jessedubord** [ubuntu/yaru#1656]
## Observed Behavior
In Ubuntu 19.04, the workspace switcher in Activities Overview had a slick look. In 19.10, it seems to have the standard GNOME look, and the bottom border goes all the way down to the bottom (see the screenshot comparisons, below):

![Screenshot from 2019-12-09 22-43-42](https://user-images.githubusercontent.com/11955519/70502769-8c74a680-1ad6-11ea-94d2-38e1eb3a3dcf.png)
Ubuntu 19.04 (notice workspace switcher seems to use Yaru theme and bottom border stops at the usual place you expect to see it in GNOME)

![Screenshot from 2019-12-09 22-44-04](https://user-images.githubusercontent.com/11955519/70502820-b0d08300-1ad6-11ea-86b7-0fc9cd350e28.png)
Ubuntu 19.10 (notice the workspace switcher orange border goes all the way around the workspace, the top corner is rounded, and the bottom edge goes all the way down to the bottom of the screen).

## Steps to Reproduce the Problem

  1. Press Window/Super key to enter Activities Overlay. Observe appearance of Workspace Switcher.

## Software that presents the issue

- Name: gnome-shell
- Version: 3.34.1

## Yaru version
The default version of Yaru that was installed on the release ISO of Ubuntu 19.10

Thanks!

**Comment by clobrano** [comment]
Hi Jesse, thanks for taking time to contribute to Yaru.
What you see is the result of a rebase on upstream Gnome theme, so it is expected.

**Comment by jessedubord** [comment]
Ah okay, so it is a re-worked Yaru theme based on Adwaita 3.34, then, if I'm understanding it? Was that design intentional (including the bottom edge of the workspace switcher going down to the bottom)? I ask because that's not the appearance in the vanilla gnome shell in 19.10. I think what you all did in 19.04 for the workspace switcher looked amazing. If that became the default, that'd be sweet!

**Comment by clobrano** [comment]
> Ah okay, so it is a re-worked Yaru theme based on Adwaita 3.34, then, if I'm understanding it?

Correct

> including the bottom edge of the workspace switcher going down to the bottom

I didn't notice that previously the edge didn't go down to the bottom, otherwise I would have tried to fix it :D (it seems a bug to me)

>  I ask because that's not the appearance in the vanilla gnome shell in 19.10.

I will double check how vanilla looks like, but probably this difference is due to the difference in the color set Yaru uses.

**Comment by jessedubord** [comment]
> I didn't notice that previously the edge didn't go down to the bottom, otherwise I would have tried to fix it :D (it seems a bug to me)
I also think it's a bug. Could be related to a bug from the dash-to-dock extension (https://github.com/micheleg/dash-to-dock/issues/1007) as disabling this extension returns the bottom edge of the workspace switcher border to its original position.
