### ISSUE TITLE
Scrollbar arrow png's are missing when compiling

### ISSUE THREAD

**Issue by Jannomag** [ubuntu/yaru#1663]
Following images are missing in the assets directory of gtk2.0 after converting svg to png:
scrollbar-arrow-up.png
scrollbar-arrow-down.png
scrollbar-arrow-left.png
scrollbar-arrow-right.png

They are also missing in the svg and assets.txt. Is this supposed to be like this?

**Comment by clobrano** [comment]
It seems we don't have them in [assets.svg](https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-2.0/assets.svg) either. Are those required by any application?

**Comment by Jannomag** [comment]
In your main.rc you commented that it's used by Qt. I've got a comment on my Yaru-Colors fork from a user who got this error:
/usr/share/themes/Yaru-Deepblue-dark/gtk-2.0/main.rc:409: Unable to locate image file in pixmap_path: "assets/scrollbar-arrow-up.png" /usr/share/themes/Yaru-Deepblue-dark/gtk-2.0/main.rc:414: Overlay image options specified without filename

The pngs are in the assets directory and they're also needed by main.rc.

**Comment by clobrano** [comment]
The png assets exist in https://github.com/ubuntu/yaru/tree/master/gtk/src/default/gtk-2.0/assets, but they don't come from assets.svg

**Comment by Jannomag** [comment]
So, the assets directory is not completely compiled while creating yaru and the pngs are just from stock gtk2.0 (Adwaita?)?

**Comment by clobrano** [comment]
Not compiled right, but more likely from old light themes, more than from
adwaita

**Comment by Jannomag** [comment]
Okay. I'll add them manually to my fork. Thanks, I'm closing this issue.
