### ISSUE TITLE
Tiny backdrop issues

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1679]
### Link button turns orange in backdrop:

![image](https://user-images.githubusercontent.com/3986894/71383222-979dfb00-25db-11ea-8a6f-08616ff0bfc0.png)

### I know this was fixed in Yaru 1.0 but checkmark border are dark (in focus):
![image](https://user-images.githubusercontent.com/3986894/71383339-2874d680-25dc-11ea-9fd9-13ee084a9011.png)

### Same thing here in backdrop:
![image](https://user-images.githubusercontent.com/3986894/71384353-2103fc00-25e1-11ea-9c0d-ec440bb74d9e.png)

**Comment by clobrano** [comment]
The first one is fixed upstream, but I forgot to downstream it, while I didn't know the second, nicely spotted thanks

**Comment by Feichtmeier** [comment]
A little bit embarrassing for me that I probably caused these issues upstream :see_no_evil: :blush: 

I think the second one needs a change in _common in treeviews

**Comment by clobrano** [comment]
I can't reproduce the second issue using master branch. This is how it appears on my machine

![image](https://user-images.githubusercontent.com/2883614/71420806-98846a80-2677-11ea-9ccb-1e00a496079c.png)

which makes sense, since the checks are assets and there is no backdrop version

**Comment by madsrh** [comment]
Closed! All issues are fixed in the master branch
