### ISSUE TITLE
Printer still isn't the same style as other icons

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1680]
I've had numerous passes at printer and I think it's a nice set of icons, but it doesn't quite have the same style as the rest of the Suru icon sets.  When you compare it to other physical objects like the camera and the keyboard it's a bit out of place.

![image](https://user-images.githubusercontent.com/38893390/71486966-b46f4400-2810-11ea-8546-ee45a72b2225.png)

I've been working on a printer in a more abstract style - I wonder if we could use something like this:

![image](https://user-images.githubusercontent.com/38893390/71487028-eda7b400-2810-11ea-9f9f-d309067dbbae.png)

**Comment by madsrh** [comment]
I can't tell if this one fits better but I understand what you're trying to do here - I do prefer the current icon.

**Comment by Feichtmeier** [comment]
I think the devices icons are not bound to the 4 sizes we use (or 3? :smile: )

![grafik](https://user-images.githubusercontent.com/15329494/71510279-9fd19100-288e-11ea-9789-584fa6985b05.png)

**Comment by meetdilip** [comment]
@ubuntujaggers if you remake `drive-removable-media.png` to a printer icon, it will live amongst similar toned icons. Possible those colourful buttons and lighter grey tone is taking printer icon standout.

**Comment by meetdilip** [comment]
I did a mock-up 64px size

![printer-device](https://user-images.githubusercontent.com/6965443/71512847-ebe7fa00-28bd-11ea-8229-0d2701235544.png)

**Comment by meetdilip** [comment]
Added it to the list

![printer-device-mockup](https://user-images.githubusercontent.com/6965443/71513035-bee81700-28be-11ea-91c5-e985d8337da3.png)

**Comment by ubuntujaggers** [comment]
> I did a mock-up 64px size
> 
> ![printer-device](https://user-images.githubusercontent.com/6965443/71512847-ebe7fa00-28bd-11ea-8229-0d2701235544.png)

I certainly like these proportions better than the current full size icon!

**Comment by ubuntujaggers** [comment]
Closing for now because I can live with the printer now the larger icon has better proportions.
