### ISSUE TITLE
Context menu checkboxes are gray on hover

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1681]
Again, a very tiny issue: Context menu checkboxes are black but gray on hover.

![Peek 2019-12-29 07-24](https://user-images.githubusercontent.com/3986894/71558882-b4d42e80-2a0c-11ea-9e22-f2d4ed57513f.gif)

Adwaita is also a mixing black and white borders, so perhaps this should/could be fixed upstream? I'm not sure what they are going for here, but IMO the border should be the same color as the text.

![adwaita](https://user-images.githubusercontent.com/3986894/71558968-a4708380-2a0d-11ea-8152-bd0aa4d4ae1a.gif)

**Comment by Feichtmeier** [comment]
They should look differnt in master, like this:

![grafik](https://user-images.githubusercontent.com/15329494/71559723-15da2180-2a62-11ea-8b8b-ca6052f393e9.png)

**Comment by madsrh** [comment]
SORRY! I promise to check the master branch before posting another issue!

![image](https://user-images.githubusercontent.com/3986894/71561846-f971c100-2a30-11ea-8d49-d7e3278c6963.png)

**Comment by Feichtmeier** [comment]
Better an outdated issue than no issue tracked for the LTS :)
