### ISSUE TITLE
Missing icons: TeXInfo and Logs

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1682]
If we're keeping a list (checking it twice 🎅 ) of missing Yaru style icons, I don't know where it is. But here is two icons to add to [the list](https://github.com/ubuntu/yaru/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22Area%3A+icon+theme%22+missing) 

![image](https://user-images.githubusercontent.com/3986894/71559575-f4783600-2a5f-11ea-809e-22a47aabcc34.png)

![image](https://user-images.githubusercontent.com/3986894/71559569-e62a1a00-2a5f-11ea-975d-f36de429a68c.png)

**Comment by Feichtmeier** [comment]
Logs is there, the snap is just not sucking it up :smile_cat: 
If you remove the snap and apt install the deb the icon is taken correctly
![grafik](https://user-images.githubusercontent.com/15329494/71559702-b8de6b80-2a61-11ea-9993-450d549c0e06.png)
I think @jhenstridge has something in the pipe to fix this :)

For TeXInfo I think you are right :thinking: :smile: But I don't even know what this app is

**Comment by madsrh** [comment]
Ahhh that's right, it's the snap issue. Same goes for Characters

**Comment by ubuntujaggers** [comment]
Funny, I just Telegrammed about this!  When I right click and do "details" on TeXInfo it looks like a doc viewer app, but when I run it it just goes to the info command in terminal.  I think something has gone wrong here...
