### ISSUE TITLE
Missing icons: checkmark and close-X action icons

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1686]
In the Ubuntu installer (ubiquity-frontend-gtk) there are green checkmarks showing up if you filled a field successfully :heavy_check_mark: 
Those are still taken from the Humanity icon theme and could use an update

![Screenshot from 2020-01-02 12-44-28](https://user-images.githubusercontent.com/15329494/71667623-cf384000-2d5d-11ea-8f17-4c4394b6dcae.png)

It looks like two symlinks are also needed. As a bonus the X-icons could also be updated 
![image](https://user-images.githubusercontent.com/15329494/71667667-03136580-2d5e-11ea-83a4-14aec857bf85.png)

The list could be:

**Positive checkmarks:**
- [x] dialog-apply (THIS is the icon, the rest are "only" symlinks)
- [x] dialog-yes
- [x] dialog-ok
- [x] gtk-ok
- [x] gtk-yes
- [x] stock_calc-accept
- [x] stock_mark
- [x] stock_mail-filters-apply
- [x] stock_yes

**Negative cancel X icons**
- [x] window-close (THIS is the icon, the rest are "only" symlinks)
- [x] cancel
- [x] dialog-close
- [x] dialog-no
- [x] dialog-cancel
- [x] button_cancel (with _ not -)
- [x] gtk-close
- [x] stock_calc-cancel
- [x] stock_close

@ubuntujaggers and/or @madsrh please have a look in /usr/share/icons/Humanity/actions

**Comment by madsrh** [comment]
Regarding the checkmark ✔️ there's two options:
![image](https://user-images.githubusercontent.com/3986894/71668631-fac12780-2d69-11ea-9f53-a9965e71a5b5.png)

or...

![image](https://user-images.githubusercontent.com/3986894/71668640-03196280-2d6a-11ea-99e4-faf3729a2b52.png)

The second one is most in line with the [Canonical design specs](https://raw.githubusercontent.com/canonical-web-and-design/design-vanilla-framework/master/Forms/forms.png) we will be discussing next week. Moving the checkmark inside the textfield isn't possible, right?
![image](https://user-images.githubusercontent.com/3986894/71668754-6e633480-2d6a-11ea-8380-a82387669d08.png)

**Comment by clobrano** [comment]
> Moving the checkmark inside the textfield isn't possible, right?

I think not, it should be a widget feature, but afaik gtk entries don't have check image inside.

**Comment by madsrh** [comment]
We could simply symlink to the emblem icons:
![image](https://user-images.githubusercontent.com/3986894/71679214-54841a80-2d87-11ea-8bf9-5b500f84b4e8.png)

but perhaps these should also be revisited and updated with these? This green is #0e8420

https://assets.ubuntu.com/v1/5594880d-error.svg
https://assets.ubuntu.com/v1/94949185-icon-success.svg

**Comment by ubuntujaggers** [comment]
Thinking about it: if we have a lot of green ticks and red X's that are symlinked, the origin file shouldn't be the Dropbox ones because those icons are too app-specific. As it happens the two Dropbox emblems are currently very generic so it works but we might change things later (e.g. if Dropbox develops its own widely-understood glyphs).  So, IMO best practice would be:

- Clone the (lovely) Dropbox emblems to make icons for dialog-apply and window-close, which will cascade through symlinks to the other use cases

- Consider whether we want to make the Dropbox icons symlinks instead of having two identical icons in Yaru.

**Comment by ubuntujaggers** [comment]
> * Clone the (lovely) Dropbox emblems to make icons for dialog-apply and window-close, which will cascade through symlinks to the other use cases

Doing a branch for this now  :)

**Comment by madsrh** [comment]
> Doing a branch for this now :)

We might want to base this on the Canonical design. Which is slightly different and slightly darker. See the links above

**Comment by ubuntujaggers** [comment]
Should we wait till after design fest then?

**Comment by madsrh** [comment]
> Should we wait till after design fest then?

Well, it's just the two icons so we can always change this

**Comment by ubuntujaggers** [comment]
> Well, it's just the two icons so we can always change this later

:+1:  And all the folders/symlinks will still be made and work  :)

**Comment by madsrh** [comment]
Also missing is the view-refresh.svg and it's symlinks

![image](https://user-images.githubusercontent.com/3986894/72211550-830f9d00-34cd-11ea-975c-fdc96b115199.png)

**Comment by Feichtmeier** [comment]
It looks like we've missed one symlink
![image](https://user-images.githubusercontent.com/15329494/74467901-3affe380-4e9a-11ea-99a6-bf51e13c96ab.png)
