### ISSUE TITLE
Switch/slider focus inconsistency is in GTK

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1704]
The focus indication is different for switches vs. sliders: for a switch it’s inside the thumb, but for a slider it’s around the whole slider. This also means that when you click a slider thumb, every part of the slider is highlighted except the part you actually clicked.

![image](https://user-images.githubusercontent.com/3986894/71985565-b37fde80-3222-11ea-9bc9-1745c7a43db2.png)

@Carlo will investigate whether it’s possible to make them consistent

**Comment by friendlyapple** [comment]
Just to link other issues and PR:
- `issue` review how focus ring appears and works #1769
- `PR` focus ring: review focus ring for some widgets #1788

**Comment by clobrano** [comment]
Thanks @friendlyapple, this reminds me that I can close this issue for what I wrote here https://github.com/ubuntu/yaru/issues/1769#issuecomment-576892539
