### ISSUE TITLE
Remove space infront of caret in entrys

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1705]
The text in a text field — and therefore the caret in an empty text field — is inset so much (8 pixels) that it’s unclear whether the field is actually empty, or whether it contains a space character.

![image](https://user-images.githubusercontent.com/3986894/71987016-55082f80-3225-11ea-9c5f-99a96f81c111.png)

**Comment by madsrh** [comment]
Can we close this issue if it's moved upstream or should we merge the `padding-left: 6px;` PR as a temporary fix?

**Comment by clobrano** [comment]
I know we said that upstream is a better place for this issue, but I wonder if it's still a issue with a different entry size

**Comment by Feichtmeier** [comment]
No - that's why - if we wanted to make this upstream - to bind this to the global metric variables at the top of common so they switch then changing the sizevariant

**Comment by Feichtmeier** [comment]
Fixed with the big padding change
