### ISSUE TITLE
Shell slider color must be visible with hover 

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1723]
We should pick a color for the shell sliders that has good contrast against the background and also when hovered. A border might also help.

Current:
![image](https://user-images.githubusercontent.com/3986894/72193608-8f7ef180-340a-11ea-95cf-7b3e71d526f3.png)

`#8e3773` with a border
![image](https://user-images.githubusercontent.com/3986894/72193655-b76e5500-340a-11ea-9e8e-ea237e997c6e.png)

**Comment by Feichtmeier** [comment]
Agreed, and this without ruining the default shell which is white :)
But it's easily changeable

**Comment by meetdilip** [comment]
Just curious. Why not Ubuntu Orange ?

**Comment by madsrh** [comment]
> Just curious. Why not Ubuntu Orange ?

A very reasonable question 😄 The Ubuntu orange is great for branding but as a UI element, it's often too much. A more subtle color would be blue, but that is also used in Adwaita, Windows and OSX and so we are simply exploring other options.

**Comment by meetdilip** [comment]
I see. Good luck :)

**Comment by clobrano** [comment]
@madsrh, what do you think about this?

![image](https://user-images.githubusercontent.com/2883614/72217599-28eff580-3528-11ea-807b-b388348c6187.png)

**Comment by Feichtmeier** [comment]
Not exactly the same issue, but the sliders colour need also be adapted to the gtk ones. Though the switch colour should be the reference then, because the sliders of the scale are are darkened by gtk

**Comment by clobrano** [comment]
Already working on that
