### ISSUE TITLE
Colour selection for window snapping

### ISSUE THREAD

**Issue by popey** [ubuntu/yaru#1727]
## Expected Behavior

With the latest build of Yaru on 20.04 (built from source as per the excellent Contributing document), I noticed the window snapping guide is bright orange.

Given during the recent desktop yaru design sprint we committed to reducing the overall amount pf orange on the desktop. I wanted to start a discussion whether we think the orange snap is still appropriate, and if not, what would it look like when changed?

![Screenshot from 2020-01-12 10-35-20](https://user-images.githubusercontent.com/1841272/72218606-81c58b00-3534-11ea-8f0e-0df1cd64e50f.png)

**Comment by clobrano** [comment]
I had a look at the code and, luckily, it's entirely in our powers

![image](https://user-images.githubusercontent.com/2883614/72220803-7c743a80-354c-11ea-8b0d-9b5085c2c06e.png)

**Comment by madsrh** [comment]
If we can change border and background independently, how about white solid border and background only 20-25% transparent white? I was thinking that this would be sort of related to the highlight on hover 🤷‍♂ 

![image](https://user-images.githubusercontent.com/3986894/72225276-cc222880-3583-11ea-9654-03686ef1a4b0.png)

**Comment by clobrano** [comment]
I still don't know how you can be so precise with a mock-up :D 

This is on the real thing

![image](https://user-images.githubusercontent.com/2883614/72225961-66ce3780-3583-11ea-8563-2f1a090e7b8f.png)

**Comment by clobrano** [comment]
So, @popey, @madsrh, any preference? White is probably more neutral as orange alternative, but I don't have a strong opinion here

**Comment by madsrh** [comment]
I prefer the white one (if it fits with the theme). Can you make a test PR?

I tried to make a PR for this myself for testing, but I didn't succeed. So I'm keen to see how you did it 😃

**Comment by popey** [comment]
I really like the white/porcelain, that's much better than 🍊 or 🍆. 
How does it look with each of the three theme options?

**Comment by clobrano** [comment]
Being a gnome-shell thing, it's the same on all three options

**Comment by popey** [comment]
I meant can you show a mockup of it in all three?

**Comment by clobrano** [comment]
Oh sorry, sure I can do that

**Comment by clobrano** [comment]
Uhm, I am afraid this white is actually a problem with white backgrounds

![image](https://user-images.githubusercontent.com/2883614/74110607-4d260d00-4b8e-11ea-96a6-eda88bc25b33.png)

**Comment by clobrano** [comment]
Over at the PR #1883 I am posting some mockups, let's discuss there

**Comment by madsrh** [comment]
I'll reopen this since this isn't in 20.04 after the shell refresh :/

**Comment by clobrano** [comment]
Let me check again

**Comment by geckolinux** [comment]
> ## Expected Behavior
> 
> ![Screenshot from 2020-01-12 10-35-20](https://user-images.githubusercontent.com/1841272/72218606-81c58b00-3534-11ea-8f0e-0df1cd64e50f.png)

This definitely feels like the most natural color option, in my very subjective and totally biased opinion. :-)
