### ISSUE TITLE
dark: "slider scale has mark" differs from normal slider

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1728]
## Expected Behavior

the "slider with mark" asset to have the same background color and flatness of circular slider

![image](https://user-images.githubusercontent.com/2883614/72257200-52ce1880-360b-11ea-9e54-0ca4f3ac3f3d.png)

![image](https://user-images.githubusercontent.com/2883614/72257157-38943a80-360b-11ea-840e-f0ae30f0dbc3.png)

![image](https://user-images.githubusercontent.com/2883614/72257284-8446e400-360b-11ea-8558-b0abfc4a685b.png)

## Actual Behavior

In the dark variant, the "slider with mark" has a gradient and a base color which is way darker than the circular slider.

In the light variant the only difference is the gradient.

**Comment by clobrano** [comment]
This was initially listed in the #1710, but it's better to fix it outside to avoid blocking other development

/cc @ubuntujaggers, if you have time, I bet you'll be faster than me, otherwise no problem :D

**Comment by ubuntujaggers** [comment]
Can do this tomorrow 👍
