### ISSUE TITLE
gtk: review suggested action button colors

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1729]
The suggested action buttons with the new green color might require some adjustment for the borders and other states (e.g. pressed) that might be too dark (at least for me)

Borders
![image](https://user-images.githubusercontent.com/2883614/72258077-139cc900-3605-11ea-8fe0-31ec5e85c74d.png)

Pressed
![image](https://user-images.githubusercontent.com/2883614/72258142-38913c00-3605-11ea-901f-ba23f77b2e5d.png)

**Comment by Feichtmeier** [comment]
I would like to avoid if colour = X then do this in drawing
Eventually we could lighten the green again a little? Suggested border color exists thus this relation is no problem

**Comment by clobrano** [comment]
I agree, maybe something in the middle between this one and the previous can work as well

**Comment by Feichtmeier** [comment]
Could you please have a look if this was fixed with https://github.com/ubuntu/yaru/pull/1750?

If not I would rather use an if else for greens rather than to darken all buttons, because the normal buttons look fine imho

**Comment by clobrano** [comment]
Yes, it's surely better, maybe still a little too dark when pressed, but I can live with that. Thanks!
