### ISSUE TITLE
consider #6e3c61 as aubergine

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1731]
Current Aubergine second accent color #924D8B might be too light. @madsrh suggested trying #6e3c61 instead

**Comment by clobrano** [comment]
Here are some comparisons between #6e3c61 and #924D8B (current)

#6e3c61 
![image](https://user-images.githubusercontent.com/2883614/72273287-05a97100-3622-11ea-965f-fa97b054f2b2.png)
#924D8B
![image](https://user-images.githubusercontent.com/2883614/72273436-3f7a7780-3622-11ea-92db-162ad25639f0.png)

![image](https://user-images.githubusercontent.com/2883614/72273362-22de3f80-3622-11ea-8071-7b339bcf7aa0.png)
#924D8B
![image](https://user-images.githubusercontent.com/2883614/72273583-7e103200-3622-11ea-8531-00e2e06639b2.png)

![image](https://user-images.githubusercontent.com/2883614/72273389-2c67a780-3622-11ea-8262-7e6482a42385.png)
#924D8B
![image](https://user-images.githubusercontent.com/2883614/72273609-8a948a80-3622-11ea-8dfa-74530636f81b.png)

**Comment by Feichtmeier** [comment]
I think this is an improvement. Looks less pony and more serious. Do we need the ack of anyone for this?

**Comment by madsrh** [comment]
@clobrano could you post your opinion? 😜

I don't like the dark sliders (that is too dark), but darker checkboxes are definitely an improvement IMO

**Comment by friendlyapple** [comment]
I have a preference for the color #924D8B. #6e3c61 is too dark especially on the progressbars and sliders which seem black on my screen.

**Comment by clobrano** [comment]
It looks fine, but It's on the edge of being too dark for me. Some of the sliders have a thin black border, so that they look even darker.
This aubergine is very recent, I'd suggest to live with current master for a little and keep this option opened.

**Comment by clobrano** [comment]
In future we can even have three tones, one for switches, one for sliders and one for focus ring

**Comment by chrisjbillington** [comment]
I think the darker purple will be too dark for yaru-dark

**Comment by madsrh** [comment]
I'll try to find something in between

**Comment by Feichtmeier** [comment]
We can have one aubergines for each variant
Just like it's now and just like it's with all colours :)
Just saying
(Look into _colors.scss)
