### ISSUE TITLE
Slider colour is somewhat low contrast in dark theme

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#1732]
Grey folders are a bit low contrast in the dark theme. So are the purple sliders.

Regardless of contrast, I preferred orange and green for folders and sliders/checkboxes. Particularly with checkboxes, sliders, radio-buttons, green meaning on was a breath of fresh air when Yaru first started doing it. It's so obvious because of the association of green with things being enabled/active.

Colour of folders is a personal preference probably going back to the actual colour of Manila folders.

![image](https://user-images.githubusercontent.com/1044087/72320889-af5a3200-36f6-11ea-95b5-887eb379bb94.png)

**Comment by Feichtmeier** [comment]
Purple sliders need a darker border indeed

I don't agree about the contrast of the folders though
