### ISSUE TITLE
Dark menus have low contrast

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1739]
Could we change the background color of the menu here? It blends too much with the background IMO. I know there's a "_Menu borders in the dark theme are not strong enough_" item on the TODO list, but a background color tweaking wouldn't hurt.

![image](https://user-images.githubusercontent.com/3986894/72386348-87cc8f00-3721-11ea-9986-bf823c8cf61f.png)

**Comment by Feichtmeier** [comment]
Yup there is a menu color in colors - np
Also the border is not dark enough

**Comment by Feichtmeier** [comment]
Another image for a "proof"
![grafik](https://user-images.githubusercontent.com/15329494/72494824-5a690980-3825-11ea-9cd1-9db5df9f202c.png)

**Comment by Feichtmeier** [comment]
@madsrh 
is this already an improvement?
![grafik](https://user-images.githubusercontent.com/15329494/72497747-ac159200-382d-11ea-8808-2926c979e9a5.png)

**Comment by madsrh** [comment]
> is this already an improvement?

Yes, for sure, but why be subtle? 🙈 

What do you think about using the same brightness as the label in the lower right corner?
![image](https://user-images.githubusercontent.com/3986894/72500486-e5053500-3834-11ea-859f-acd3bf8eff4a.png)

Or darker, like the headerbar? I know that menus should be lighter, but just trying something with highter contrast. 
![image](https://user-images.githubusercontent.com/3986894/72500537-023a0380-3835-11ea-9c27-ae83e8b72808.png)

Too much?

**Comment by Feichtmeier** [comment]
I guess the brighter one is somehow consistent with the light theme (becomes brighter)
Okay what about this:
![grafik](https://user-images.githubusercontent.com/15329494/72500906-d1a69980-3835-11ea-82f9-c53484ec0eae.png)


I can't make it exactly like the $bg_color otherwise it drowns elsewhere
(this is another example: you can't just pick one place - there are the weirdest gtk apps that take this widget in this box and that widget in that box and so on)

**Comment by madsrh** [comment]
I think that's much better than the first suggestion 👍 

I'm guessing that it's deliberate that these borders are just slightly different.
![image](https://user-images.githubusercontent.com/3986894/72501762-fdc31a00-3837-11ea-91a9-ca6ed1301e87.png)

**Comment by Feichtmeier** [comment]
:man_shrugging: 
Might be but that's all upstream code

About the borders in general: they are defined deep down in _common.scss for ALL window borders. So windows, menus, csd menus and so on.
They descent from the $borders_color but are double transparentized to avoid some bug (at least this is what someone from upstream wrote in common)

So if you are okay with it I would make a PR and then check also the checkbox from the big issue about the borders

**Comment by madsrh** [comment]
Perfect
