### ISSUE TITLE
Titlebar/headerbar of inactive windows

### ISSUE THREAD

**Issue by cavillagomez** [ubuntu/yaru#1740]
In Yaru theme (not light, not dark) the titlebars/headerbars of inactive windows are the same color (or almost) of active windows; It should be more like in Yaru-dark that is significantly different.

**Comment by madsrh** [comment]
Thanks for taking the time to improve Yaru  @cavillagomez 👍
In earlier versions of the theme, this difference was more pronounced. I'm keen to see it return, but let's hear what rest of the team thinks :)

**Comment by Feichtmeier** [comment]
I'm not sure about this. The borders and and the buttons become less buttons become flat
Currently everything behaves the same in backdrop
If we start to change this now we might end up inconsistent in the end

**Comment by madsrh** [comment]
> Currently everything behaves the same in backdrop
If we start to change this now we might end up inconsistent in the end

I agree. It's for cases like below where multiple windows are stacked. I think the difference looks small  because the headerbar is dark. The difference is easily spotted in Yaru-light (or Adwaita 🙈)

But you're right @Feichtmeier this should be enough difference for most screens to easily tell which window is in focus 🤷‍♂ 

![image](https://user-images.githubusercontent.com/3986894/72412806-95f4cc80-376e-11ea-98e7-a1dfdb498ab5.png)

**Comment by Feichtmeier** [comment]
Maybe this is something for the backlog but not for Todo 20.04? 

@cavillagomez if you have this problem explicitly in the default theme  we could change it in _headerbar.scss
Currently Carlo make it behave like the dark theme which is the right thing imho

**Comment by clobrano** [comment]
![image](https://user-images.githubusercontent.com/2883614/72450039-f3fad180-37b9-11ea-832c-d6fdb2e4b8c5.png)
![image](https://user-images.githubusercontent.com/2883614/72450068-fe1cd000-37b9-11ea-9aaa-51ad7d5c4c77.png)

It is actually very hard to tell the difference in default variant, but it's probably fixable in headerbar only

**Comment by clobrano** [comment]
it's curious, because the "light from above" effect is the main difference between headerbars in the default variant, but the same effect is barely noticeable in the dark one

**Comment by Feichtmeier** [comment]
Very hard? I really don't think so
The button colour changes completely
The text colour becomes less visible
The close button becomes gray from bright orange

Imho this would be an unnecessary change

**Comment by clobrano** [comment]
LOL, a color difference will help ;)
