### ISSUE TITLE
Ubuntu dock and Top bar for Yaru-light

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#1741]
The Yaru-light theme exists only for Applications but please expand it for gnome-shell and ubuntu dock as well. It will complete the Yaru-light theme.

## Suggested Behavior
![Screenshot from 2020-01-15 11-44-16](https://user-images.githubusercontent.com/54065734/72410505-7a99b980-378e-11ea-86df-2da3f6f17dc0.png)
![Screenshot from 2020-01-15 12-15-02](https://user-images.githubusercontent.com/54065734/72411427-d6fdd880-3790-11ea-965c-994ed5e4864f.png)

## Actual Behavior
![Screenshot from 2020-01-15 12-17-20](https://user-images.githubusercontent.com/54065734/72411510-09a7d100-3791-11ea-8042-7148e9671de2.png)

Thanks!

**Comment by Feichtmeier** [comment]
Hi, basically this makes sense but....

Upstream gnome shell, which's work we use for our theme, wants the volume popups (called OSD - on screen display) to be white on black on both variants.
The same for the top panel, which they called "negative space"

Just for explaining why this is happening.

Also in the shell there are currently only two variants.
This means either we use the dark popups or the light popups.

For the Ubuntu default installation this "mixed" colours are clearly wanted by the most people on the design team and a dark headerbar in the default theme needs a dark top panel to not look out of place

So we would need three variants in the shell to support this.
Currently we can't even switch the shell themes at all so this is not something we could work on right away

**Comment by clobrano** [comment]
>  Currently we can't even switch the shell themes at all so this is not something we could work on right away

just to be complete, it is possible to change the Shell theme if one installs both gnome-tweaks and user themes shell extension, what is not possible is to switch both gtk AND shell theme at once.

While the dark panel fits well with all of Yaru three gtk themes, an hypothetical white shell would work on gtk light only, but we're technically limited right now, as said, and we cannot force the gtk theme to be white with the shell white variant.
Such limitation is under investigation though, so things might change in the future

**Comment by Feichtmeier** [comment]
I would go so far and say, since we are heavily based on the upstream shell theme, which only supports two variants, this is not fixable unless we introduce this in upstream.

- OSD colors are currently the same for both light and dark
- panel colors are currently the same for both light and dark

They are used ALL over the place in the shell themes. Targeting this would be a big refactoring. Do we want this @clobrano ? I personally pass

**Comment by clobrano** [comment]
I agree, it's out of our scope
