### ISSUE TITLE
Selected disabled checkmarks in listview

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1743]
For the selected disabled checkmarks and text in listview the checkmark shouldn't be orange and the text is too subtle.

Current:

![image](https://user-images.githubusercontent.com/3986894/72424742-c2b4de00-3786-11ea-8827-7b2387adf2c1.png)

I don't really have a good idea for this one 😞 Maybe something like this?

![image](https://user-images.githubusercontent.com/3986894/72424953-1b847680-3787-11ea-8cce-a8ec09a63d75.png)

**Comment by Feichtmeier** [comment]
Thanks :+1: 

Fix should be placed in _drawing.scss
