### ISSUE TITLE
New Folder set proposal

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#1749]
## Expected Behavior

![folders](https://user-images.githubusercontent.com/6965443/72476018-20423c80-3812-11ea-92eb-01bbfd4751fa.png)

(What you were trying to do)

## Actual Behavior

![image](https://user-images.githubusercontent.com/6965443/72474135-28987880-380e-11ea-9f7f-77cb8459b2e5.png)

(What happened instead)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Software that presents the issue

- Name: Ubuntu 
- Version: 20.04

I know there would be a lot of brainstorming before the proposed folder icon was finalized. But since I heard it is experimental, I believe the gradient in it is a bit flashy on some occasions. It looks great when the image size is 64 px or higher. But for 48 px and below, there is some `highlight` due to the gradient.

I am not trying to say that what we have right now has to change. But if you are considering other options before finalizing, I thought I would propose something simpler. Thanks.

**Comment by Feichtmeier** [comment]
Uhm that screenshot is a mockup by one of the ubuntu designers
The actual real look when build from master is this:

![grafik](https://user-images.githubusercontent.com/15329494/72502211-0e27c480-3839-11ea-8709-65a38266ebeb.png)

![grafik](https://user-images.githubusercontent.com/15329494/72502223-1849c300-3839-11ea-98b8-f3d785cc4c1d.png)

![grafik](https://user-images.githubusercontent.com/15329494/72502234-213a9480-3839-11ea-93e1-b93a989bf4b8.png)

**Comment by clobrano** [comment]
The usage of the gradient has one more nice effect: the orange side keeps good the contrast with the dark variant, while the purple one does the same but with the light variant :D

**Comment by meetdilip** [comment]
I read that the folder design is experimental at OMG Ubuntu. So I thought will start a discussion with possible alternatives. 

> On your proposal - I don't like it :/ It somehow looks like folders from a comic or something, really not fitting into the yaru icons

I don't like a couple of them. But I used the full scope of colours. From what I learned from designing for others, people have strange tastes. :)

> The usage of the gradient has one more nice effect: the orange side keeps good the contrast with the dark variant, while the purple one does the same but with the light variant :D

Sure. This is the first time I have seen gradient in folder icons. Hopefully, with time, will get used to it. :)

**Comment by clobrano** [comment]
Please don't feel discouraged by critiques. I don't find these icons bad at all, probably the set that fits best with both light and dark variant is this

![image](https://user-images.githubusercontent.com/2883614/72505453-41ba1d00-3840-11ea-9fe0-f52647f88b35.png)

which are the current (which I personally prefer) without the gradient and hypothetically can be considered by others team members, so let's keep this ticket open (if you like) and visible

**Comment by meetdilip** [comment]
Thank you. At first, I thought 2 different sets of icons for dark and light themes. But that would be more work, I guess.

**Comment by clobrano** [comment]
The folder set does not change with theme variant, unfortunately

**Comment by meetdilip** [comment]
I don't know whether it fits here. But at times, I think the whole idea of a folder can have some refresh. Box icons replacing folder icons. 

![Screenshot from 2020-01-16 14-40-57](https://user-images.githubusercontent.com/6965443/72509775-44336b80-386e-11ea-866a-79ce8a6c2a70.png)

![Screenshot from 2020-01-16 14-43-34](https://user-images.githubusercontent.com/6965443/72509976-9e343100-386e-11ea-8352-5c98d919fac3.png)

I think when we rework on colours and perhaps " representation ", box icon might be more appealing than a folder icon

**Comment by meetdilip** [comment]
@Feichtmeier I made my comments based on M Wimpress' blog which I saw on Twitter. It had pictures of folder with dark and white backgrounds. Another source I had was images from OMG Ubuntu. They were comparatively smaller than M Wimpress' blog images.

It looked a bit strange to me from those screenshots. But that is just one man's opinion which does not matter at all. I am no one when it comes to Ubuntu.

From the pictures you posted ( and my own comment from the 1 st post ), it looks great when we view it on 64px or higher. UbuntuJaggers and others have indeed done a good job from that viewpoint.

I was so used to the bright Orange folders ( which I didn't like the first time ) that this one looked different to me.

The only reason I started this discussion was that " folder design is experimental ". I thought in that case, the team wants to discuss other possible designs.

Please don't be upset about my comments on the folder design. It is just one user and that does not matter at all. :)

**Comment by Feichtmeier** [comment]
I am not upset at all! 
I just want to analyse the problem, maybe it's indeed a contrast problem maybe not.
Just build from master and see if you still feel that the contrast is bad in either of the themes

**Comment by madsrh** [comment]
> Please don't be upset about my comments on the folder design...

It may sound like it, but I assure you that no one here is ever upset! We are all just highly passionate about making a beautiful desktop - and so are you, it seems 😃 Different opinions are welcome and especially if they bring actual suggestions 😉

**Comment by meetdilip** [comment]
I tried those folder variants

![light](https://user-images.githubusercontent.com/6965443/72533343-07ca3480-389b-11ea-944d-5f08a944b167.png)


![dark](https://user-images.githubusercontent.com/6965443/72533344-0862cb00-389b-11ea-9a25-e4fff33f3c22.png)

**Comment by real-amano** [comment]
Just for the sake of completeness: That mockup was posted by the user Templar82 in the Phoronix forums: 
[
![grafik](https://user-images.githubusercontent.com/25839976/72555582-216c7b80-389d-11ea-8d5d-b979a81c5871.png)
](url)

**Comment by chrisjbillington** [comment]
I would prefer something with more contrast with the dark theme when it comes to the folder icons. I liked orange (keeping it would be my preference, I pretty much always prefer more distinctiveness!), but lightening the grey a bit would help too.

**Comment by friendlyapple** [comment]
After a week of using Ubuntu with the new Yaru design, I must say that the new folder design is really beautiful. The colors are well chosen and the gradient is the most beautiful effect.

I finally do not regret losing the orange folders. The new folders give Yaru a fresh look.

Congratulations 🎉

**Comment by Feichtmeier** [comment]
@meetdilip re-reading your issue, I think you refereed to the screenshots on OMGubuntu which were from the mockups, not the real SVGs

I think there is no contrast problem with the real folder icons on the light and dark gtk theme, so I'm closing this issue, thanks for contributing :+1:
