### ISSUE TITLE
Suggestion: develop yaru-qt, in the style of adwaita-qt

### ISSUE THREAD

**Issue by coxackie** [ubuntu/yaru#1760]
This is not a bug per-se. I love Yaru, but it does play as well as Adwaita does via `adwaita-qt` (https://github.com/FedoraQt/adwaita-qt) for Qt applications. I tried to use `adwaita-qt` with Yaru, but for the "standard" (not dark or light) theme the title bars of `Qt` applications appear greyish with white text - it seems that the color is not picked up. (I can provide screenshots if needed.)

 I was wondering whether, since you want to keep as close as Adwaita upstream as possible, you would be willing to fork `adwaita-qt` into something like `yaru-qt`.

**Comment by clobrano** [comment]
Hey, thank you, this is an idea to explore for sure

**Comment by coxackie** [comment]
Some screenshots to provide evidence. I am using Yary and `adwaita-qt`. First screenshot:
![Screenshot from 2020-01-18 18-42-56](https://user-images.githubusercontent.com/22049642/72668811-738ad980-3a22-11ea-9261-ec61f65b1b7c.png)

It shows the normal Yaru theme - you see Files and Spotify with the correct title/headerbar colors, and RStudio and Flacon (qt) with grey title-bars.

The same set-up with Yaru-light or Yaru-dark playes well with `adwaita-qt`:
![Screenshot from 2020-01-18 18-38-00](https://user-images.githubusercontent.com/22049642/72668865-0af02c80-3a23-11ea-952a-7929924d37d4.png)
![Screenshot from 2020-01-18 18-37-18](https://user-images.githubusercontent.com/22049642/72668867-117ea400-3a23-11ea-934e-7c29f9bd6a4a.png)

 I guess this is related to the fact that Adwaita only has the two flavours (light and dark).

 But even if this is resolved in `adwaita-qt`, it still uses Adwaita theming. It would be great to get a native Yaru feeling.

**Comment by Feichtmeier** [comment]
I think this only happens if you switch between all three themes. It happens for server side decorated apps.
If you only switch between yaru and yaru-dark it should not happen ( I think )

**Comment by coxackie** [comment]
well, when I first noticed it (situation like the first screenshot) I have been using yaru for a very long time, I was not using yaru-light or yaru-dark at all. Although I do agree that things get weird once you start changing through themes - going from yaru to yaru-dark changes SSD to the correct color, and back to yaru keeps them as such. At any rate, there is clear inconsistency. (Only to be expected, of course, since once cannot hope that yaru and `adwaita-qt` should work well together)

**Comment by coxackie** [comment]
I wonder if it would be a good idea to actually open an issue at `adwaita-qt` on this. It may be the case that they can handle the themes in a unified way, since yaru will be following adwaita closely. What do you guys think?

**Comment by Feichtmeier** [comment]
@coxackie knowing the guys a bit and this is def. not a good idea :)

**Comment by coxackie** [comment]
lol... ok. keeping my cool then - nothing to see here.

**Comment by asegarra** [comment]
Would love to see this, in conjunction with packaging QGnomePlatform.

**Comment by coxackie** [comment]
Yeah, I know, but seems that the issue has not gathered enough traction...

**Comment by fouzan14** [comment]
Is it not easy to change and modify `adwaita-qt` to `yaru-qt`, I mean since `yaru` itself is based on tweaks to `Adwaita` right?
I just want consistency and this to really happen: https://discourse.ubuntu.com/t/having-yaru-as-a-global-ubuntu-flavor-theme/18470

**Comment by clobrano** [comment]
As far as it is related to GTK application, it is not that hard (see #2331), but for different toolkits is harder. It would be great if anyone interested could work on this :)

**Comment by coxackie** [comment]
I guess this would require someone knowledgeable in QT/C++ (to manage through the code of `adwaita-qt`) and the yaru theme. Do the developers have someone in mind? Presumably Ubuntu would be quite interested in such consistent experience.

**Comment by Feichtmeier** [comment]
@coxackie is this the same issue as https://github.com/ubuntu/yaru/issues/1357 ?

**Comment by coxackie** [comment]
@Feichtmeier yes, if something like `yaru-qt` is developed (based on `adwaita-qt`), it would appear as a candidate in `qt5ct` (although, with `qgnomeplatform` installed, `qt5ct` should not be necessary). As mentioned above, this would require someone with `Qt` skills to go through the codebase of `adwaita-qt`, which does not seem like a totally trivial task.

**Comment by Feichtmeier** [comment]
Okay then we can close this one :+1:
