### ISSUE TITLE
Notebook tab text is wrong on hover

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1762]
Notebook tab text looks disabled on hover.

This is a bit odd because the Adwaita tab hover works fine.

![Peek 2020-01-17 07-20](https://user-images.githubusercontent.com/3986894/72672156-828b7f00-3a56-11ea-8712-325bfa36f073.gif)

No video but in the light theme the text is also grayed.

**EDIT:** 

One fix would be to just keep the same $fg_color
![border_dark_](https://user-images.githubusercontent.com/3986894/72672305-4ce79580-3a58-11ea-99a9-7a58c5d85599.gif)
![border_light](https://user-images.githubusercontent.com/3986894/72672306-4ce79580-3a58-11ea-9cb3-dc0298dd0ef0.gif)

OR...

add a subtle background highlight like the buttons has (I vote for this one 😉 )
![darktabs_bg](https://user-images.githubusercontent.com/3986894/72672313-6b4d9100-3a58-11ea-99bc-7894ae595336.gif)
![lighttabs_bg](https://user-images.githubusercontent.com/3986894/72672310-64bf1980-3a58-11ea-86d0-e60fd672f94f.gif)

I was almost ready to make a PR with the code above, when I discovered that backdrop was broken 😭

**Comment by clobrano** [comment]
My bad, I forgot to fix the text on hover
