### ISSUE TITLE
review how focus ring appears and works

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1769]
First a brief recap of what discussed at the design fest, where the inconsistency of the focus ring has rightfully pointed out: we had

- solid colored focus ring for entries and
- dashed gray for all the other widgets.

Since focus ring is an **accessibility feature**, it has to be visible, to it was decided to use colored solid focus ring everywhere except in buttons, because of the resulting heaviness of the design.

Also consider that in GTK, the focus ring is *always* present from the moment when the window opens, that is, there is always a widget with the focus ring and it often moves together with the in-focus widget (e.g. pressing on a button move the focus ring on that button).

For this latter reason, my personal opinion is that using a solid and colored focus ring is too visible when it's usually not necessary, at least with current gtk behavior

![image](https://user-images.githubusercontent.com/2883614/72806895-6f470200-3c56-11ea-9971-d41982253e79.png)
![image](https://user-images.githubusercontent.com/2883614/72807385-90f4b900-3c57-11ea-8f6b-869096363a60.png)
![image](https://user-images.githubusercontent.com/2883614/72807486-cbf6ec80-3c57-11ea-951b-7252b704361d.png)
![image](https://user-images.githubusercontent.com/2883614/72807515-ddd88f80-3c57-11ea-9ec6-3ae2abd37f4a.png)

There are two ways to improve this I think

1. reverting dashed focus ring for everything except entries
2. proposing a gtk change so that the focus ring appears only after a specific keyboard event (e.g. pressing Tab), that is only under explicit user request

My personal preference would probably be to go with 1, while working on 2.

This is an important design topic, so if anyone knows Mpt's handle on github I'd love hearing from him as well

/cc @flexiondotorg, @madsrh, @Feichtmeier, @ubuntujaggers, @didrocks

**Comment by Feichtmeier** [comment]
@mattehpaulthomas

**Comment by Feichtmeier** [comment]
There is, in my opinion, a third option: 

Change the focus ring everywhere to a transparent purple
This works quiet good on the shell refresh branch (have a look)

I think Mpt is totally okay with it being visible though

**Comment by friendlyapple** [comment]
I tested the latest development version of Yaru yesterday and I prefer the behavior of Yaru 1.0 / 2.0. 
The purple focus ring is omnipresent in Yaru 3.0 (which is unpleasant).

**Comment by Feichtmeier** [comment]
![Peek 2020-01-19 10-26](https://user-images.githubusercontent.com/15329494/72678461-7cbd8a00-3aa6-11ea-8ccb-a8a929823cbf.gif)
This could be an alternative

**Comment by Feichtmeier** [comment]
@clobrano try if

transparentize($focus_border_color, 0.7);
With
$focus_border_color: lighten ($aubergine, 14%)

Maybe you like it. It's looking like in many websites (transparent fat focus ring)
It only looks good on the light theme I think but maybe this is a solution for everywhere except switches

**Comment by Feichtmeier** [comment]
Okay, sorry I meant for everywhere except switches and entries :). 
I think it is less inconsistent than the dashed lines plus the ultra pony ring and it looks a bit better

**Comment by clobrano** [comment]
> Okay, sorry I meant for everywhere except switches and entries :).

and buttons :D which are already different. That is what I mean, it's already hard to use this pattern, but okay we can improve it of course.

**Comment by Feichtmeier** [comment]
Just asked Jakub Steiner again, and they are still interested to get rid of the dashed line. But only two weeks left until Gnome UI freeze.

**Comment by clobrano** [comment]
I think that from an accessibility point of view, dashed line is not enough
indeed

**Comment by meetdilip** [comment]
Just leaving this mockup for valuation.

I like the idea of `dashed` highlight. Is it just like in Yaru green buttons ?

![highlight 20 04](https://user-images.githubusercontent.com/6965443/72817540-f5336f00-3c8f-11ea-83a6-e0d09dfc9b28.png)

In the last screenshot for the LHS panel, perhaps dashed outline would be better than a solid border.

**Comment by clobrano** [comment]
@madsrh, could you post some screenshots to see how OSX handles it (if it does it?) for reference? :)

**Comment by meetdilip** [comment]
I got this one up. Not sure how good looking/acceptable  it is. Perhaps better than a solid outline.

![lhs highlight](https://user-images.githubusercontent.com/6965443/72818734-fcf41300-3c91-11ea-8959-bbd54699f91f.png)

**Comment by clobrano** [comment]
Thanks @meetdilip, these are probably nicer than the solid line, but focus ring shall be easily distinguishable from the standard selection and more subtle I think, this is why we are focusing on lines (dashed or solid)

**Comment by madsrh** [comment]
> could you post some screenshots to see how OSX handles it (if it does it?) for reference? :)

@clobrano Here you can also find Windows 10, Android and iOS: https://www.conceptdraw.com/solution-park/software-mac-os-user-interface

**Comment by clobrano** [comment]
Awesome! Thanks!

**Comment by matthewpaulthomas** [comment]
> ![Yaru focus ring around menu and its label](https://user-images.githubusercontent.com/19801137/72819677-922ce280-3c65-11ea-8ec5-3b789dd94c2d.png)

Is it possible to change the selector so that the ring is drawn around just the menu, rather than its label? And the same for checkboxes, radio buttons, switches etc. (Even a dotted focus ring would look bizarre if the label happened to be above the menu, rather than to its left.)

Separately, I wonder if you could work around the flashing focus ring on menubuttons by changing the selector to exclude a focused menubutton if it’s being clicked right now.

> ![Nautilus menu with item focused](https://user-images.githubusercontent.com/19801137/72820606-1af84e00-3c67-11ea-8cda-cbbc2bf94c4f.png)

When you hover over these items, they highlight like menu items, but when you use arrow keys they get focus rings instead. This tells me it’s a bug in GTK. Chromium’s menu gets this right, highlighting its items as menu items regardless of whether you’re using pointing device or keyboard.

**Comment by Feichtmeier** [comment]
@matthewpaulthomas thanks for replying!

I think we could eventually split those issues.
If I understood @clobrano issue, this is more about finding a good colour for Gtk3, with all the weird bugs included which we can't fix here sadly :/ 

The row that has that :focus ring ... Does it select the button inside or the next row when you tab?

**Comment by clobrano** [comment]
> Is it possible to change the selector so that the ring is drawn around just the menu, rather than its label?

GTK has both; in the picture above is represented the row's focus ring, the row which contains a label and a menu button. Pressing tab, the focus ring moves to the button menu.

![image](https://user-images.githubusercontent.com/2883614/72844671-54e44700-3c9d-11ea-8b23-a81631afe285.png)

This is common in gtk, many widgets have their specific focus ring, except the entry.

Technically speaking the focus ring is the outline css property (probably as it is in standard web css). As far as I know, all widgets have it except the entries, whose *keyboard-selection* state changes the style of its borders instead.

We can decide how the outline looks like (style, color, width, radius), but not how and *where* it is drawn by gtk, the only exception being an *outline-offset* property, which defines how far from the widget the outline is (and a negative offset draws the outline inside the widget, as we had for switches).

Composite widgets like switches and scrollbars have an outline only on one of their components. For example the switch has it in the slider only (the circular handle), while the scrollbar has it in the trough (and not int the slider).

Then it comes the case of checkboxes that might have their own focus ring

![image](https://user-images.githubusercontent.com/2883614/72844739-76453300-3c9d-11ea-981f-af7db2ca4327.png)
(hard to see it, but it's there, around the unchecked checkbox)

unless they belong to a composition like the one below
![image](https://user-images.githubusercontent.com/2883614/72844790-91b03e00-3c9d-11ea-8041-2a60147f6eda.png)

> Separately, I wonder if you could work around the flashing focus ring on menubuttons by changing the selector to exclude a focused menubutton if it’s being clicked right now.

This is not possible, since it is up to gtk toolkit.

[This](https://medium.com/hackernoon/removing-that-ugly-focus-ring-and-keeping-it-too-6c8727fefcd2) article suggests using the same style for selection/hover and focus, so that for the user is exactly the same if they use mouse or keyboard, but we only have the outline style which is not enough (we are missing the background color), but it's maybe a good way to start for a gtk change proposal.

> If I understood @clobrano issue, this is more about finding a good colour for Gtk3

Yeah, or more broadly a way to draw it in a way that is visible, but less heavy, and consistent. Once solved this *little* :eyes: issue I can move on and discover time travel easily :rofl: 

I am up to something, but I don't like spoilers :) let's see tomorrow

**Comment by Feichtmeier** [comment]
For selected rows we can have a white ring

**Comment by clobrano** [comment]
More on this
> Separately, I wonder if you could work around the flashing focus ring on menubuttons by changing the selector to exclude a focused menubutton if it’s being clicked right now.

This is a gtk property which is probably true by default.

![image](https://user-images.githubusercontent.com/2883614/72873952-43c52580-3cf1-11ea-8e1f-942f42ff99be.png)

with gtk-inspector, I can set it to false, and in fact that widget (a button) gets the focus ring *only* using keyboard and not with mouse clicking

**Comment by Feichtmeier** [comment]
Some inspiration
![Peek 2020-01-22 09-30](https://user-images.githubusercontent.com/15329494/72882117-ef727380-3cf9-11ea-86bd-007c9fa7aeb0.gif)

@clobrano @madsrh @matthewpaulthomas 

I think this is annoying enough, looks quiet sexy but needs tweaking for selected rows for sure

**Comment by clobrano** [comment]
Yes, this is very similar to what I was trying

**Comment by friendlyapple** [comment]
The purple dots are clearly distinguishable. Why not use them?

<img width="625" alt="Capture d’écran 2020-01-22 à 12 34 21" src="https://user-images.githubusercontent.com/59767069/72891180-f7d7a800-3d13-11ea-8e68-f6d2af25550d.png">

And white on darker or orange backgrounds:

<img width="953" alt="Capture d’écran 2020-01-22 à 12 35 40" src="https://user-images.githubusercontent.com/59767069/72891301-3ff6ca80-3d14-11ea-9367-f49807b21650.png">

**Comment by clobrano** [comment]
That's exactly what I was trying instead :D

**Comment by friendlyapple** [comment]
On a switch:

<img width="552" src="https://user-images.githubusercontent.com/59767069/72891783-518ca200-3d15-11ea-94c6-2a7bb10b47ab.png">

**Comment by clobrano** [comment]
Yes, that's usually ok, but the pattern is different, since the outline is not around the widget, but inside. To improve the consistency, Frederick idea is probably better. I'll work on a PR to test it

**Comment by friendlyapple** [comment]
The outline is not around but inside on my screenshot?
Like the current version of Yaru:

<img width="667" alt="test" src="https://user-images.githubusercontent.com/59767069/72892384-a54bbb00-3d16-11ea-9a74-5f97276e7f53.png">

**Comment by clobrano** [comment]
Yes it's inside the slider, while for buttons an other widgets is around it

**Comment by friendlyapple** [comment]
Ok :)

**Comment by Feichtmeier** [comment]
Can we close this because of #1788 @clobrano ? Or do we want some testing phase?

**Comment by clobrano** [comment]
Sure

closed by #1788

**Comment by vstepaniuk** [comment]
How to disable the focus ring?

![Screenshot from 2020-05-08 19-56-20_crop](https://user-images.githubusercontent.com/24701640/81456228-db139300-9191-11ea-8c51-19231992f364.png)
