### ISSUE TITLE
Ubiquity (app) styling review

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1771]
![image](https://user-images.githubusercontent.com/3986894/72886669-85ae9580-3d0a-11ea-9538-2404b9939179.png)
Found by @madsrh 

- [ ] fix blue dots
- ...

**Comment by friendlyapple** [comment]
Is it also possible to change the shape of the indicators?

Like this:
![install](https://user-images.githubusercontent.com/59767069/72889050-23a45f00-3d0f-11ea-9bc4-62d7d796c453.png)

**Comment by Feichtmeier** [comment]
Very nice idea @friendlyapple !

Problem is that those dots are actually progressbars :laughing: 

So they always look uneven and like a very small bar besides circles
(I am too lazy to post the full explanation)

This is the closest we can get to your mockup (with some little hacks to padding and a box-shadow):
![Screenshot from 2020-01-22 13-27-41](https://user-images.githubusercontent.com/15329494/72898033-33c23b80-3d1b-11ea-9f6d-34d310263150.png)

If @madsrh is okay with this I could make a PR
(I try to give the full explanation later if anyone is interested)

**Comment by Feichtmeier** [comment]
Haha,... okay or with 1px "border"...

![Screenshot from 2020-01-22 13-42-43](https://user-images.githubusercontent.com/15329494/72899026-1c844d80-3d1d-11ea-918a-70c15952ad50.png)

**Comment by madsrh** [comment]
> Haha,... okay or with 1px "border"...
> 
> ![Screenshot from 2020-01-22 13-42-43](https://user-images.githubusercontent.com/15329494/72899026-1c844d80-3d1d-11ea-918a-70c15952ad50.png)

This looks MUCH better @Feichtmeier 👍

**Comment by Feichtmeier** [comment]
@madsrh with correct purple:

![Screenshot from 2020-01-22 14-04-16](https://user-images.githubusercontent.com/15329494/72900607-1d6aae80-3d20-11ea-8498-2fef4b3b1a19.png)

**Comment by friendlyapple** [comment]
Nice :) however, it looks like they are not round. They measure 15px * 14px.

Is it also possible to reduce the circles slightly? (I know it's a detail!)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/72902673-ce267d00-3d23-11ea-97b0-652937b3dc3e.png)

Nope sadly I can't reduce the size : /

Yeah they do not look round because it is basically a hack (see comment above)

**Comment by friendlyapple** [comment]
You say it's a progress bar. What kind of progress bar is it? If it's a progress bar like below, maybe it's better not to style it to make it consistent with the rest of the system.
![72273583-7e103200-3622-11ea-8531-00e2e06639b2](https://user-images.githubusercontent.com/59767069/72903232-2b72fc00-3d2d-11ea-945a-3cefefd3e952.png)
