### ISSUE TITLE
Add the same border on the progressbar as on the switches

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1775]
To add more consistency, I suggest adding the border used for switches on progress bars.

![test-progress](https://user-images.githubusercontent.com/59767069/72908822-50b83800-3d36-11ea-9440-a9cc9846c599.png)

**Comment by Feichtmeier** [comment]
Hey @friendlyapple :) (love the name btw)

Let's see how the pending gnome shell upstream work will look like

We should aim for consistency where it makes sense indeed.

The slider you showed is from gnome shell, in the pending gnome shell refresh they look a little bit more modern.
Let's keep this issue to remind ourselves of keeping gtk and shell in sync as much as possible

**Comment by friendlyapple** [comment]
This concerns all progress bars (except level bars):
![72273583-7e103200-3622-11ea-8531-00e2e06639b2](https://user-images.githubusercontent.com/59767069/72909995-2c5d5b00-3d38-11ea-8bfe-800737e40b99.png)

**Comment by clobrano** [comment]
Not really fond to borderless :smile:, but it looks good enough in the light variant, so I'd keep it.
Also consider that it is not strictly necessary to have dark and light variant be exactly the same. The borders in the dark variant were just necessary to have a proper contrast.

**Comment by friendlyapple** [comment]
@Feichtmeier You're right. Progressbars and sliders are too thin. Adding a border may not be the best idea.

@clobrano I understand. It's true that the progressbars of the light theme are beautiful and they don't lack contrast.

So, I close the issue :)
