### ISSUE TITLE
Gtk: Gedit invisible cursor in the dark theme

### ISSUE THREAD

**Issue by lextra2** [ubuntu/yaru#1776]
**Issue 01:** The bar of the volume indicator that shows up when using keys that are bound to volume down/up is white instead of the new violet that is used for sliders. (This is true for all yaru themes, not just the dark one.)
![Screenshot from 2020-01-22 16-39-18](https://user-images.githubusercontent.com/20690384/72908475-cec80f00-3d35-11ea-98a7-768d7b8e6404.png)

**Issue 02:** The "Open" button of the file browser window that opens when selecting a file via web browser still has the old green instead of the new violet.  (This is true for all yaru themes, not just the dark one.)
![Screenshot from 2020-01-22 16-43-15](https://user-images.githubusercontent.com/20690384/72908802-4bf38400-3d36-11ea-8090-a729ed19690a.png)

**Issue 03:** The blinking insertion point indicator in gedit is invisible with the new dark theme. (works fine with light theme.)

Yaru version **0cc5861**

**Comment by Feichtmeier** [comment]
The 1) issue is on purpose
It's a different context thus consider is not the most important thing here

This popup is a on screen display which is normally just monochrome

**Comment by lextra2** [comment]
> The 1) issue is on purpose
> It's a different context thus consider is not the most important thing here
> 
> This popup is a on screen display which is normally just monochrome

It used to be blue, thats why I was confused.

**Comment by Feichtmeier** [comment]
2) is on purpose, too

Suggested actions are green in the canonical design language. Thanks for the issues, I'll rename the issue of you don't mind!?
Please keep reporting issues if you see them

**Comment by lextra2** [comment]
> 2 is on purpose, too
> 
> Suggested actions are green in the canonical design language. Thanks for the issues, I'll rename the issue of you don't mind!?
Go ahead

> Please keep reporting issues if you see them
Will do

**Comment by lextra2** [comment]
Just to clarify, the mouse cursor is still visible in gedit. Just the blinking insertion point is not.
