### ISSUE TITLE
Update the document-open.svg icon

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1780]
When we drag and drop on a folder, it is the old icon that appears. I think it needs to be updated to be in line with the new icons.

**Current document-open.svg icon:**
<img width="379" alt="icon" src="https://user-images.githubusercontent.com/59767069/72967413-91a95e80-3dc1-11ea-8583-24d81572e346.png">

**Drag and drop:**
<img width="130" alt="drag-and-drop" src="https://user-images.githubusercontent.com/59767069/72967536-d7662700-3dc1-11ea-8e58-a1c824acde0e.png">

**Comment by friendlyapple** [comment]
I just noticed that the icon already exists. But it coexists with the old icon.

<img width="913" alt="icons" src="https://user-images.githubusercontent.com/59767069/72975615-662e7000-3dd1-11ea-9474-5eb9833b5db6.png">

**folder-open.png:**
![folder-open](https://user-images.githubusercontent.com/59767069/72975628-6dee1480-3dd1-11ea-9f7f-f614da3f1366.png)

**folder-drag-accept.png:**
![folder-drag-accept](https://user-images.githubusercontent.com/59767069/72975724-8fe79700-3dd1-11ea-8fb0-f1b8a78f5e5e.png)

**Comment by madsrh** [comment]
Since the two icons are identical, this could be fixed with a symlink

**Comment by ubuntujaggers** [comment]
Actually I think the symlink is problematic because they're in different folders and also categories (and we have a list of symlinks per category)...  but it's an easy fix anyway :+1:
