### ISSUE TITLE
Missing mimetype icon for .pyc

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1781]
To simplify the work of @madsrh, I open a dedicated issue on this subject.

There is currently no Yaru icon for Python precompiled files (PYC).

**Current icon:**
<img width="88" alt="cur-icon" src="https://user-images.githubusercontent.com/59767069/72968235-60319280-3dc3-11ea-895e-f09d77faa9d9.png">

**Suggested icon:**
<img width="120" alt="test" src="https://user-images.githubusercontent.com/59767069/72967940-beaa4100-3dc2-11ea-8664-3b70a07d5ab8.png">
**x2**
<img width="198,5" alt="test2" src="https://user-images.githubusercontent.com/59767069/72968000-e13c5a00-3dc2-11ea-849d-3c53fbb67476.png">

I used the **text-x-python.svg** and **application-octet-stream.svg** icons.
I hope you can add it :)

**Comment by madsrh** [comment]
Thanks @friendlyapple I'll create a PR later (hopefully) today.
