### ISSUE TITLE
Update the software-update-available icon :) 

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1783]
The software update icon (*software-update-available.svg*) no longer corresponds to the current Yaru style. This icon comes from the Suru icon pack.

**Current icon:**
<img width="116" alt="cur-icon-update" src="https://user-images.githubusercontent.com/59767069/72980034-f4a6ef80-3dd9-11ea-89f2-cfff4ffc2f21.png">

**Suggested icons:**
<img width="453" alt="sug-icon-update" src="https://user-images.githubusercontent.com/59767069/72980051-fe305780-3dd9-11ea-8403-abc4d1a7402b.png">

**Comment by Feichtmeier** [comment]
Hi, very nice icons you made there!

I actually have no idea where this icon is used :)
For the software updates there is the software updater ( A )

Do you know where this specific icon is used? (I know that it's in our repo)

**Comment by friendlyapple** [comment]
Good point! I don't remember seeing it in a recent version of Ubuntu. Maybe other people can help us?

**Comment by madsrh** [comment]
@ubuntujaggers ?

**Comment by Feichtmeier** [comment]
But if it isn't used anywhere, why don't we remove it from the theme? :)

**Comment by friendlyapple** [comment]
@Feichtmeier I agree with you. It will be better :)

**Comment by madsrh** [comment]
I mean, maybe Jaggers knows where this is used. I think I've seen it somewhere 🤔

**Comment by friendlyapple** [comment]
I think it was used in Gnome 2. I didn't find a newer version of the icon.

Here is the icon included in Gnome 2:
![gnome-software-update-available svg](https://user-images.githubusercontent.com/59767069/73057405-b10fbc80-3e91-11ea-932a-73c6cfaa1b17.png)

**Comment by ubuntujaggers** [comment]
I've never seen it used either...  but yes, we should remove it.

Perfect Yaru icons there, @friendlyapple  :+1:

**Comment by madsrh** [comment]
I think the icon is from UpdateNotifier. Perhaps the new release upgrade icon, which would explain why we've never seen it. 
https://wiki.ubuntu.com/UpdateNotifier

Looks like this package contains a few more icons, but I have no idea how to test :man_shrugging: 

https://packages.ubuntu.com/xenial-updates/amd64/update-notifier/filelist

**Comment by ubuntujaggers** [comment]
@Feichtmeier found a context where this can appear...  @friendlyapple, do you fancy a PR for one of yours?  I like either of the circles  :)

**Comment by madsrh** [comment]
Just posting a comment here to remind myself that we need to create a symlink for this
![image](https://user-images.githubusercontent.com/3986894/73688991-84e40f00-46cd-11ea-8550-344b33ab5d88.png)

**Comment by friendlyapple** [comment]
Hello everyone, as I said in a previous issue, I'm very busy right now and I don't have time to train on Inkscape for several months. I'm sorry @ubuntujaggers but I can't make this icon myself 😢

**Comment by madsrh** [comment]
No problem @friendlyapple 👌
Looking forward to your return 😉

**Comment by binarykitchen** [comment]
Closed? I still see that error:

```
Mar 15 20:00:43 M1 ubuntu-appindicators@ubuntu.com[10367]: unable to update icon for software-update-available
```
