### ISSUE TITLE
Entryfields in dark theme are hard to spot

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1784]
Entryfields are really hard to spot:
![image](https://user-images.githubusercontent.com/3986894/72987456-ba921980-3dea-11ea-8c77-652478b3babc.png)

**Comment by Feichtmeier** [comment]
Yes because the background is using base colour there.
Could you show a different app please?:)
I'm sure they look fine elsewhere

**Comment by Feichtmeier** [comment]
Please check Nautilus and control center

**Comment by clobrano** [comment]
![image](https://user-images.githubusercontent.com/2883614/72989425-8587c600-3dee-11ea-8c74-d75d7884aba0.png)
![image](https://user-images.githubusercontent.com/2883614/72989498-a6501b80-3dee-11ea-83b0-ccd9e1e94148.png)

**Comment by madsrh** [comment]
> Could you show a different app please?:)

This one is fine.
![image](https://user-images.githubusercontent.com/3986894/72990742-ffb94a00-3df0-11ea-9f2f-acaaa2069f29.png)

but this one is odd (Terminal settings):

![asdfasdfasdfasdf](https://user-images.githubusercontent.com/3986894/72991180-c6350e80-3df1-11ea-9fdf-401739e93422.gif)

**Comment by Feichtmeier** [comment]
Yes but that's the problem.
There are some elements that use bgcolor and some use base colour
So we would need to brighten them up like with the buttons (1%)

I understand that certain parts are not always perfect but at least they are consistent. I would rather stop to do it this way:

- find elements that are not perfect
- add a fix for that element in tweaks
- move on

I think we are past this phase for now where we've chosen the current build and model

I have an idea for the entries though. But I'm really getting worried

**Comment by clobrano** [comment]
I agree we should not abuse tweaks.
Let's try not to prevent any change only for the fear to break something. I would suggest marking this and similar "works-everywhere-but-here" bugs as "papercuts", hopefully having a clearer big picture about this kind of issues will make also clearer how to proceed

**Comment by Feichtmeier** [comment]
Let's not change something only for certain parts of certain apps ;)
If it's really a big issue, there is _apps.scss

If we continue like this the whole thing will fall apart just like it did in the first version.

Not to break something should really be the first priority for a professional theme suite, in my opinion.

**Comment by clobrano** [comment]
Not to break anything for sure, not to fear also ;)

**Comment by madsrh** [comment]
I think we're all on the same page here. 
You'll have to excuse my ignorance but I'm not skilled enough to tell if it's using bgcolor or base colour. I simply noticed something that could be improved and opened an issue for it 😄 
Not just for this one but for all issues, both of you are perfectly entitled to close them or mark as won't fix - no hard feelings AT ALL 👍

**Comment by Feichtmeier** [comment]
I would be lying to say that those entries on top of elements with $base_color, like rows and notebook tabs, are easy to spot.

It would be just awesome if we could get all the double styling out of _tweaks, like the switches (which was my mistake not to include $switch_bg/border_color in my upstream contribution) and Carlos tab styling that haven't been merged yet upstream.
And it would be awesome if we could have a smart theme which works for all widgets in gtk in all apps.

Reality is, that we disagree often with upstream and gtk apps are not designed consistent. 

I'll see what we can do about the entries

**Comment by clobrano** [comment]
So, do we agree on adding a papercut tag?

**Comment by clobrano** [comment]
Added papercut label, to suggest that this a fix here is surely desirable, but since the nature of the fix is complex, it's also annoying :smile:

**Comment by Feichtmeier** [comment]
@madsrh 

This is how dark theme entries look, when they are drawn on $bg_color:

![image](https://user-images.githubusercontent.com/15329494/72996591-e1ece480-3df2-11ea-94bf-c6ab1bb434bb.png)

![image](https://user-images.githubusercontent.com/15329494/72996601-e913f280-3df2-11ea-9a58-81e20b52b5c3.png)

![image](https://user-images.githubusercontent.com/15329494/72996646-f7faa500-3df2-11ea-9e9c-25a18422ecad.png)

![image](https://user-images.githubusercontent.com/15329494/72996838-4740d580-3df3-11ea-8cbf-ce59e0f7f88b.png)


I think the good thing about this darker-than-buttons-look is, that they look different from buttons - AND I am very sure to remember an issue from Yaru1.0 where someone complained that entries can't be differentiated from buttons ;)

this is with the same color the buttons use (lighten(bg_color, 1%):

![image](https://user-images.githubusercontent.com/15329494/72996996-8cfd9e00-3df3-11ea-8c5d-0e89d763ff3c.png)

Now they drown, too - as they are drawn on $bg_color

So the only solution I see is to darken them explicitly

![image](https://user-images.githubusercontent.com/15329494/72998274-7b1cfa80-3df5-11ea-89e5-7990ae19b9ea.png)

@if $variant=='dark' {
  row entry, tab entry, notebook entry, notbook tab entry { background-color: darken($base_color, 4%); }
}

**Comment by madsrh** [comment]
Looks like a good solution @Feichtmeier

**Comment by Feichtmeier** [comment]
@madsrh @clobrano 
Tab's should now always be $base_color, so i think this is a safe special case for entries

however rows in listboxes are not. I would rather not special case all entries in rows and only in notebooks. Is this okay for you?

**Comment by madsrh** [comment]
> I would rather not special case all entries in rows and only in notebooks

Sorry, but I'm not sure what that means 🙈😄

**Comment by Feichtmeier** [comment]
Np. What I mean is

Entries on a notebook page, is a very common pattern. 
Entries have $base_color
Notebook pages have $base_color

Rows have sometimes $bg_color and sometimes $base_color
But I've rarely seen entries in rows, except the search entries which receive a focus border immediately for example in gnome control center
![Peek 2020-02-12 20-24](https://user-images.githubusercontent.com/15329494/74369456-b0ee4700-4dd5-11ea-8980-006884a26bcb.gif)


So If you agree @madsrh , I would reduce the change only to entries in notebooks:
![image](https://user-images.githubusercontent.com/15329494/74369378-9320e200-4dd5-11ea-8552-82236db47958.png)

**Comment by madsrh** [comment]
Thanks 👍😀 Yes! +1
