### ISSUE TITLE
Support for Lubuntu

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#1786]
## Expected Behavior

(What you were trying to do)

Make Yaru available for Lubuntu DE

## Actual Behavior

(What happened instead)

In 18.04 when you install Lubuntu over default 18.04 , Yaru works in

1. LightDM GTK Greeter
2.  Widget in `customise look and feel`
3. Icon theme
4. Cursor

But does not work in 

1. Window border - Theme
2. Openbox configuration Manager - Theme

It is looking for an `.obt` archive

## Steps to Reproduce the Problem

  1. Install `lubuntu-desktop` from Synaptic Package manager
  1.
  1.

## Software that presents the issue

- Name: Ubuntu
- Version: 18.04

## Yaru version

Please report the Yaru version in your system using one of the following commands

* If you installed Yaru from PPA

    `$ apt show communitheme`

* If you installed Yaru via Snap

    `$ snap info communitheme`

* I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

> $ git describe
> $: command not found
>

**Comment by Feichtmeier** [comment]
Ubuntu does not even use Gtk anymore, so what's the point? =)

**Comment by meetdilip** [comment]
I am not sure. I recently started using it. It works with the login page and widget ( as they call it )

Widget gives makes the header bar Yaru-ish

![lubuntu widget](https://user-images.githubusercontent.com/6965443/73024231-30ca6680-3e53-11ea-862c-596655abf388.png)

In short, it works in most areas with whatever we have now. Just making sure that all areas got covered. 

If there is a need for reference, `Adapta` has both the missing elements.

**Comment by Feichtmeier** [comment]
Okay this is nautilus :)
But what style classes are missing? Style classes from which Lubuntu only gtk elements?

**Comment by coxackie** [comment]
> Edit: Sorry was on the phone....
> 
> Thanks for the suggestion
> 
> Lubuntu does not even use Gtk anymore, so what's the point? =)
> 
> I think they use Qt now (LXQT)
> 
> So maybe we could rather add this to the pending Yaru-Qt issue?

Note that yaru-qt would be used to bend at applications to use gtk style, and not the opposite. This is exactly what adwaita-qt does.

**Comment by meetdilip** [comment]
> Okay this is nautilus :)
> But what style classes are missing? Style classes from which Lubuntu only gtk elements?

I have both PCManFM file manager and Nautilus since installed Lubuntu DE on top of default 18.04. Yaru works mostly everywhere. 
> 
>     Window border - Theme
>     Openbox configuration Manager - Theme

But since the above was missing, it could be missing somewhere. Here is the PCManFM screenshot

![lubuntu default PCMan](https://user-images.githubusercontent.com/6965443/73047721-b3c3df00-3e9c-11ea-95ae-ddb6ecbda263.png)

Please see the top Window border. It is a Windows 2000 style grey gradient in `Lubuntu default` theme. It was good before because I used Adapta for  `Openbox configuration Manager - Theme`.

Thanks.

**Comment by Feichtmeier** [comment]
Which version is it
I'm very very sure that they switched to lxqt

**Comment by meetdilip** [comment]
> Which version is it

Any command to find out ? I installed `lubuntu-desktop` through Synaptic Package Manager.

**Comment by Feichtmeier** [comment]
https://de.m.wikipedia.org/wiki/LXQt?wprov=sfla1

They changed it with 18.10

**Comment by meetdilip** [comment]
I see. So no support will be possible ?

**Comment by Feichtmeier** [comment]
At least not now, since I think we would need to have a way of theming Qt stuff in LXQT and some of the remaining gtk apps (I thin kthey have a mix)
I'll close it, if @clobrano see if you want to reopen this imho this is out of our scope currently, we don't even have a proper Qt support

**Comment by meetdilip** [comment]
Ok. Just wanted to tell you it works fine for most of the part by default. Expect which I mentioned.

**Comment by meetdilip** [comment]
Looks like what they offer through Synaptic package manager uses GTK2 and GTK3. I have identified the only area of Yaru theme that is missing. It is the `openbox-3` folder in all `openbox configuration manager` themes.  Attaching the part from Adapta.

[openbox-3.zip](https://github.com/ubuntu/yaru/files/4116543/openbox-3.zip)

If we Yaru -fy Adapta colours and re-design .xbm elements ( if possible ), then Yaru is completely compatible with `openbox configuration manager` themes. Thanks.

**Comment by meetdilip** [comment]
I managed to get a Yaru fied version of Openbox theme derived from Adapta. You can see it here ( please click to see the full-sized version )

![openbox configuration manager](https://user-images.githubusercontent.com/6965443/73230482-78c6f180-41a3-11ea-83e8-2e1f8b9c96a0.png)

I changed the active window colour, active menu bg and active menu text colours. 

I could not get .xbm file with an orange circle. Looks like it does not support colours. Will have to see if we can put an orange circle around the close button. How, I have no idea.

I wanted to ask what are the hex codes for **active window** and **inactive window** in Yaru ?

**Comment by ItzSwirlz** [comment]
Hey, just want to update. (Ping @Feichtmeier ) - I believe LXQt still uses Openbox and that can be themed :)
