### ISSUE TITLE
Overshots for undershots in scrolledwindows

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1790]
![image](https://user-images.githubusercontent.com/15329494/73069827-b4617300-3ea6-11ea-9718-0a70b37c566b.png)

I think there could be a better solution.
Eventually we should rather add back the undershots mixin in tweaks?

WDYT @clobrano ?

**Comment by clobrano** [comment]
Of course, my change was only to have an initial working implementation

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/issues/523

**Comment by Feichtmeier** [comment]
Let's start with what we had:

![image](https://user-images.githubusercontent.com/15329494/73104865-c0295580-3ef7-11ea-9d24-e54b4e55e410.png)
![image](https://user-images.githubusercontent.com/15329494/73104899-d3d4bc00-3ef7-11ea-8cac-a2ace96c7232.png)

![image](https://user-images.githubusercontent.com/15329494/73104926-e64ef580-3ef7-11ea-950c-24a566e896ae.png)

![image](https://user-images.githubusercontent.com/15329494/73104959-f7980200-3ef7-11ea-95c9-8d7533e65f31.png)

Any further improvements @madsrh @clobrano @friendlyapple ?

**Comment by friendlyapple** [comment]
@Feichtmeier Much better. It's great! 👍
