### ISSUE TITLE
[discussion] Improvements to the shadows (in a list)

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1792]
It's me again :) I don't really like the current shadows, which I think could be improved.

Look:

![test](https://user-images.githubusercontent.com/59767069/73070978-efb56f00-3eb1-11ea-92fb-0be71451ec9a.png)

They are hardly visible. It just looks like the borders are darker and not uniform.

**Comment by friendlyapple** [comment]
Apparently, the issue #1790 deals with the same problem.

**Comment by clobrano** [comment]
Those are called overshot (bottom) and undershot (top).

Undershot are actually the very same thing overshot are, at the moment, so yeah, if you have already something in mind feel free to propose it or open a PR.

**Comment by friendlyapple** [comment]
Thanks for the info :) Where are the SCSS files to modify?

**Comment by madsrh** [comment]
> Thanks for the info :) Where are the SCSS files to modify?

In `common.scss` 😃 

Are you aware of how the overshoot works? It's not just a border 😉

**Comment by friendlyapple** [comment]
Thanks! No, I don't know how it works :)

**Comment by Feichtmeier** [comment]
Ok let's discuss it in https://github.com/ubuntu/yaru/issues/1790
