### ISSUE TITLE
Re-update the normal/opened folder icon

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1797]
Sorry to reopen a new issue. I noticed a difference between closed (normal) and opened folders.
The styles are not the same (especially on icons in 48x48px).

Click to zoom:
![folders](https://user-images.githubusercontent.com/59767069/73123926-860e9100-3f95-11ea-8303-765fcfd4ac2c.png)

Moreover, the following icon has not been updated:
https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/legacy/document-open.svg

You will end up hating me! 😄

**Comment by madsrh** [comment]
> You will end up hating me! smile

Never! Thanks for reporting :+1:

**Comment by ubuntujaggers** [comment]
Cheers @friendlyapple 👍

I'll fix the edging on the 48px first because it's easier.

The legacy document-open button is only used as the "open" button in legacy app UIs - I think it can be a generic folder rather than a "brand colours" folder but welcome thoughts.

**Comment by friendlyapple** [comment]
Merged (#1824)

I close this issue because the main problem has been fixed. Blurred icons affect all icons in sizes @2x. I will see if I open a dedicated issue.
