### ISSUE TITLE
Gtk3: notebook issues

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1802]
1) When a tab is selected, there shouldn't be a change on hover. Here a bottom border appears.
![Peek 2020-01-25 20-05](https://user-images.githubusercontent.com/59767069/73126439-c9c3c380-3fb2-11ea-8b07-e684d52bb50b.gif)

2) In the backdrop they have the wrong bg color
![image](https://user-images.githubusercontent.com/15329494/73136071-c4658800-4049-11ea-9c68-34261c7c7284.png)
I guess they need the backdrop_base_color

3) Padding changes when clicked
![Peek 2020-01-26 15-34](https://user-images.githubusercontent.com/15329494/73136747-72c0fb80-4051-11ea-8e92-e40c945c0992.gif)

Edited by @Feichtmeier

**Comment by clobrano** [comment]
Thanks for the work, really appreciated 😉

I think snaps are in line with latest official release 19.10.4, but the others are right concerns

**Comment by Feichtmeier** [comment]
Circular buttons padding needs a fix because we use the slim padding and I didn't make it right upstream: (

**Comment by Feichtmeier** [comment]
@friendlyapple 
The first issue: does this also happen with other themes?

**Comment by friendlyapple** [comment]
@Feichtmeier Yes. I don't know why I haven't tested it on Adwaita too (on Debian 10).

![Peek 2020-01-25 23-12](https://user-images.githubusercontent.com/59767069/73127977-98ee8900-3fc8-11ea-8220-1cfb558e8e93.gif)

**Comment by Feichtmeier** [comment]
Okay thanks for checking
Then you can remove it from the list prbly
This repo can only fix stuff with scss and svgs :)

**Comment by friendlyapple** [comment]
@Feichtmeier Of course!

**Comment by Feichtmeier** [comment]
@clobrano would be neat if you could fix that
I'm not that much into notebooks :P 

I extracted the circular button issue into a dedicated issue
@friendlyapple nitpicking about your issue reporting (because it is REALLY nice reporting): please use dedicated issues instead of gathering issues :heart:

**Comment by friendlyapple** [comment]
@Feichtmeier You're right. I'll think about it next time.

**Comment by Feichtmeier** [comment]
@clobrano found another one :angel: 

Padding changes when clicked
![Peek 2020-01-26 15-34](https://user-images.githubusercontent.com/15329494/73136747-72c0fb80-4051-11ea-8e92-e40c945c0992.gif)

**Comment by clobrano** [comment]
I think it's the effect of the font change, more than the padding
