### ISSUE TITLE
Nautilus sidebar color

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1803]
PR #1798 made me realize that Nautilus siderbar and Gnome-settings (and gedit, and tweaks) background colors are not aligned as they used to be.

Mads correctly used `background-color: mix($bg_color, $base_color, 50%);` for the floating bar, because it's the same color the sidebar has, but it used to be `$bg_color` (and they're almost the same color (#FBFBFB vs #F7F7F7 which is porcelain) as the main window background color of the mentioned main Gnome applications. The difference is below

Nautilus in master
![image](https://user-images.githubusercontent.com/2883614/73127954-5d53bf00-3fc8-11ea-9fe8-50496282f962.png)

Nautilus with sidebar using `$bg_color`
![image](https://user-images.githubusercontent.com/2883614/73127947-44e3a480-3fc8-11ea-8438-c2a19dbd9350.png)

and here the matching settings
![image](https://user-images.githubusercontent.com/2883614/73127960-72305280-3fc8-11ea-9b87-fdddc1cc2f6e.png)

also gedit has the same colors
![image](https://user-images.githubusercontent.com/2883614/73128018-4eb9d780-3fc9-11ea-8b63-b655b5465a1f.png)

It is not a big problem, but at least explain to me why the sidebar seemed different in the last months.
Personally, nautilus sidebar color is not different enough to create a separation from the main windows. The two colors are so similar that one might ask why not making them the same.

My motivation to revert sidebar to `$bg_color` is to avoid having yet another color in the palette and to create some matching with the other main applications with a sidebar (gnome-settings, gedit and tweaks).

**Comment by friendlyapple** [comment]
Which explains the difference in borders when we choose a file:
<img width="966" alt="Test" src="https://user-images.githubusercontent.com/59767069/73128217-4c0cb180-3fcc-11ea-8fee-24e98710490e.png">

Now, if I totally agree with you to standardize, I love the current color of the Nautilus sidebar. 😭

**Comment by friendlyapple** [comment]
@clobrano There is something I don't understand on your screenshots. Why are the buttons darker on the first screenshot than on the other and why the icons in the sidebar also change? Does it also affect these elements?

**Comment by Feichtmeier** [comment]
@clobrano good idea :+1: 
Could you take care of @madsrh PR then? I mean consolidate his changes in yours? Or would you want to make two separate PRs?

And bwt nautilus: how about using your the upstream-sync script again?

**Comment by clobrano** [comment]
We can safely merge Mads' PR
