### ISSUE TITLE
Wrong icon background in Disk

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1805]
There is a bug in gnome-disk with menus buttons background.

## Expected Behavior

Yaru-dark:
![Capture d’écran du 2020-01-26 13-48-23](https://user-images.githubusercontent.com/36476595/73135464-a0527880-4042-11ea-84a2-a2e21bdcfb7c.png)
![Capture d’écran du 2020-01-26 13-48-14](https://user-images.githubusercontent.com/36476595/73135463-9fb9e200-4042-11ea-8ec1-2b7a7384ed35.png)

## Actual Behavior

Yaru:
![Capture d’écran du 2020-01-26 13-24-31](https://user-images.githubusercontent.com/36476595/73135320-f1fa0380-4040-11ea-97b4-601c162098ce.png)
![Capture d’écran du 2020-01-26 13-35-37](https://user-images.githubusercontent.com/36476595/73135322-f58d8a80-4040-11ea-9ffb-1be43fac3ead.png)

## Software that presents the issue

- Name: Gnome-disk
- Version: 3.34
- Tested on Ubuntu 19.10 and 20.04

Adwaita theme not affected neither yaru-dark nor yaru-light.

**Comment by Feichtmeier** [comment]
Thanks @Jupiter007-43 
I guess we missed a style class in _headerbar.scss ....

**Comment by Feichtmeier** [comment]
Hmmmm testing this with the code from master and I can not confirm this:
![image](https://user-images.githubusercontent.com/15329494/73136207-66d23b00-404b-11ea-86c8-6354aed57bcb.png)

Are we talking about the same app @Jupiter007-43 ?
Or... maybe I am in the wrong view? :thinking:

**Comment by friendlyapple** [comment]
I don't have this problem either...

**Comment by Jupiter007-43** [comment]
@Feichtmeier No it is the same view... 
@friendlyapple Strange 😕

Screenshot from 19.10 :
![Capture d’écran du 2020-01-26 17-27-30](https://user-images.githubusercontent.com/36476595/73138351-e8cd5e80-4061-11ea-8750-616d4f6b511a.png)

By the way, the RAID icon is a little weird...

 And from 20.04 (uptodate and proposed enable) :
![Capture d’écran du 2020-01-26 17-43-12](https://user-images.githubusercontent.com/36476595/73138487-5cbc3680-4063-11ea-88e2-6ef07fc4c16d.png)

I'm going to see by compiling theme from master.

**Comment by clobrano** [comment]
I confirm no problem as well, it might be something already fixed from 19.10 to master

**Comment by friendlyapple** [comment]
@Jupiter007-43 OK. I get it. Look at the buttons. It's still the old style. Update Yaru to the latest version :)

**Comment by Jupiter007-43** [comment]
All right!
I should have directly test from master...

Thanks for your great job 👍

**Comment by Jupiter007-43** [comment]
Should I open an issue for RAID icon ?

**Comment by friendlyapple** [comment]
@Jupiter007-43 Yes. I think it will be easier for them.
