### ISSUE TITLE
Gtk3: circular buttons have a wrong padding

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1806]
**In Yaru:**
<img width="681" alt="1" src="https://user-images.githubusercontent.com/59767069/73126457-07285100-3fb3-11ea-9b40-6811593909b9.png">

**In Adwaita:**
<img width="736" alt="2" src="https://user-images.githubusercontent.com/59767069/73126568-a3068c80-3fb4-11ea-9124-1325fe47dcbc.png">

Caused by wrong use of variables in my upstream contributions :man_facepalming: 
Missed to insert it for circular buttons padding

Previously reported by @friendlyapple

**Comment by Feichtmeier** [comment]
@friendlyapple 
Strangely this does also happen for me with adwaita
![image](https://user-images.githubusercontent.com/15329494/73136900-1b238f80-4053-11ea-9946-81244353af77.png)

But it is fixable for Yaru
![image](https://user-images.githubusercontent.com/15329494/73136914-3f7f6c00-4053-11ea-8913-0d14d5e67b97.png)

**Comment by friendlyapple** [comment]
@Feichtmeier Really strange because on Debian 10 and Adwaita, there is no problem. The only difference I see between our two screenshots is the icon inside the button.
