### ISSUE TITLE
Icons: dedicated mobile vendor symbolics

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1809]
Found that adwaita has some workaround for samsung phones 

![image](https://user-images.githubusercontent.com/15329494/73139092-862c9080-406a-11ea-958d-fa5dcf170991.png)

- [ ] phone-samsung-galaxy-s
- [ ] phone-palm-pre
- [ ] phone-htc-g1-white
- [ ] phone-google-nexus-one
- [ ] phone-apple-iphone
- [ ] multimedia-player-apple-ipod-touch

For the phones we could prbly symlink to
![image](https://user-images.githubusercontent.com/15329494/73139113-e28fb000-406a-11ea-81da-fd2e6db4692b.png)

- [ ] computer-apple-ipad
And for the tablet to
![image](https://user-images.githubusercontent.com/15329494/73139121-f63b1680-406a-11ea-9ac3-010a2f46fec1.png)

**Comment by Feichtmeier** [comment]
Nevermind, I am an idiot:
![image](https://user-images.githubusercontent.com/15329494/73140265-5d5ec800-4077-11ea-90fd-e76ff7bc2546.png)
![image](https://user-images.githubusercontent.com/15329494/73140277-74051f00-4077-11ea-94c5-f487dd06dcee.png)
![image](https://user-images.githubusercontent.com/15329494/73140279-7d8e8700-4077-11ea-8aa6-d962186b15a3.png)

**Comment by madsrh** [comment]
These should all be symlinks, right?

![image](https://user-images.githubusercontent.com/3986894/73140555-6d2bdb80-407a-11ea-8a74-9f5220722e3f.png)
