### ISSUE TITLE
Inconsistent RAID icon in disk

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1810]
## Actual Behavior

![Capture d’écran du 2020-01-26 17-27-30](https://user-images.githubusercontent.com/36476595/73139294-ed4b4480-406c-11ea-810d-fe4822a20ebc.png)
RAID icon looks inconsistent relative to others.

## Software that presents the issue

- Name: gnome-disk
- Version: 3.34
- Ubuntu 19.10

I am going to look on master on my VM 20.04

**Comment by Feichtmeier** [comment]
Thanks for the report

I think the full colour version is simply missing
Thus the fall back to the symbolic one

How does it look with the adwaita icon theme?

**Comment by Jupiter007-43** [comment]
Here is :
![Capture d’écran du 2020-01-26 19-14-00](https://user-images.githubusercontent.com/36476595/73139621-17523600-4070-11ea-894f-14256983bfb3.png)

**Comment by Feichtmeier** [comment]
Thanks :dancer:

**Comment by Jupiter007-43** [comment]
Same issue on master.

**Comment by meetdilip** [comment]
Like this ?

![raid 64](https://user-images.githubusercontent.com/6965443/73147297-d80dfe80-40dc-11ea-952d-d294ed89f01c.png)

![raid 48](https://user-images.githubusercontent.com/6965443/73147296-d80dfe80-40dc-11ea-9134-88e32cdead6c.png)

![raid 32](https://user-images.githubusercontent.com/6965443/73147295-d7756800-40dc-11ea-859f-592c0a166e2b.png)

**Comment by meetdilip** [comment]
For smaller sizes, this one might be more suitable

![raid alt 32](https://user-images.githubusercontent.com/6965443/73147952-f3c6d400-40df-11ea-973b-55a6f5f04323.png)

![raid alt 48](https://user-images.githubusercontent.com/6965443/73147954-f45f6a80-40df-11ea-92bb-d6cc3f418d38.png)

![raid alt 64](https://user-images.githubusercontent.com/6965443/73147955-f45f6a80-40df-11ea-9005-c29deb26844f.png)

**Comment by meetdilip** [comment]
Details look fine on bigger sizes, but 32 px and below, we need to keep it simple and dark

![small 24](https://user-images.githubusercontent.com/6965443/73149339-d21d1b00-40e6-11ea-9c95-ffa587c3798d.png)

![small 32](https://user-images.githubusercontent.com/6965443/73149340-d2b5b180-40e6-11ea-944c-2ce916d57af2.png)

I got 2 mockups, one with details and other minimal icon

![r 2](https://user-images.githubusercontent.com/6965443/73149367-fbd64200-40e6-11ea-824a-67a24ca21c6e.png)
![r 1](https://user-images.githubusercontent.com/6965443/73149368-fbd64200-40e6-11ea-9e01-8ac2f2ea4972.png)

**Comment by Jupiter007-43** [comment]
> I got 2 mockups, one with details and other minimal icon

The first one looks very good 👍

> ![r 2](https://user-images.githubusercontent.com/6965443/73149367-fbd64200-40e6-11ea-824a-67a24ca21c6e.png)

**Comment by madsrh** [comment]
@meetdilip would it be possible to change the sharp coners? It would fit the Yaru style better

**Comment by meetdilip** [comment]
How is this one ?

![Screenshot from 2020-01-29 20-24-07](https://user-images.githubusercontent.com/6965443/73367322-6e0c7980-42d5-11ea-8f54-f8dd7e9219c0.png)

**Comment by meetdilip** [comment]
I was working on a bigger image and curves were getting vanished when made small. This one should fit your guidelines.

![Screenshot from 2020-01-29 20-40-00](https://user-images.githubusercontent.com/6965443/73369246-49fe6780-42d8-11ea-83be-0285d6d443ce.png)

![128](https://user-images.githubusercontent.com/6965443/73369248-4a96fe00-42d8-11ea-9c8d-121f55e32979.png)

**Comment by meetdilip** [comment]
Hope you will like this

![raid curve](https://user-images.githubusercontent.com/6965443/73370169-cc3b5b80-42d9-11ea-8d87-793e9bf9f038.png)

**Comment by ubuntujaggers** [comment]
Hi @meetdilip 

That's a really nice icon, but we don't have any other icon with that realistic perspective (we do have some "slightly 3D" ones but they don't taper).  I'm open-minded to bucking the trend  :)  but if we do there's edging to include that's consistent across the whole icon set.  Do you mind picking an existing Yaru icon as a starting point and seeing if you can edit it to make something, or use it as a reference point and copy how the border works, highlights, etc.?

One option might be to do a slightly 3D icon [in this style](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-removable-media.svg) using [this](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-harddisk.svg) as a baseplate (moving the glyph up to make room for the detail at the bottom/front).  Alternatively, just study those two and add the same edging to your existing design :+1:

**Comment by meetdilip** [comment]
Thanks for the comment @ubuntujaggers 

I am not familiar with that kind of template. I can only promise to try. :)

**Comment by meetdilip** [comment]
I tried a non 3D ish icon concept. I hope @ubuntujaggers will have some tips for me to make it more Suru - ish. 

![Screenshot from 2020-01-29 21-42-00](https://user-images.githubusercontent.com/6965443/73374609-803fe500-42e0-11ea-8e11-7d7b5dd61a04.png)

RAID is a set of hard drives. So I think something like this might fit the scene. Thanks.

**Comment by ubuntujaggers** [comment]
I'll post some tips about next steps tonight :)

**Comment by ubuntujaggers** [comment]
Okay: in Yaru terms, the easiest design to try first is the flat one, because we already have some good reference points.

We've got a device icon that already has the right shape, so download [this file](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-removable-media.svg) and delete the bit at the bottom of each icon (the bit that represents the front of the drive).  Then you've got a plain shape to do the flat design on.

Next, download [this file](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-harddisk.svg) and pipette the darker grey from it (the one used for the symbol).  Using that colour, draw the darker details onto each of your different sized baseplates, making sure the vertical and horizontal lines are snapped to whole pixels for maximum sharpness at every size (press # in Inkscape to reveal the grid).  You can copy/resize the design onto each size as long as you then edit it slightly to align it with the pixels for that size:

![image](https://user-images.githubusercontent.com/38893390/73565289-26aef600-4459-11ea-8ffa-845bd8548d0f.png)

For the biggest icon, instead of aligning the design to individual pixels, work to a grid of 4px squares where possible.

If the resulting design looks good, you have an icon that's consistent with the edging, gradients and shades as the other devices  :)  and we can use it in the icon theme.  If not, we think again!

**Comment by meetdilip** [comment]
I will keep in mind :)

**Comment by meetdilip** [comment]
How about these ?

![RAID PNG Feb](https://user-images.githubusercontent.com/6965443/73587196-ff9b0780-44de-11ea-8885-97cfc8a62528.png)

**Comment by meetdilip** [comment]
Tried a mockup

![RAID v Feb](https://user-images.githubusercontent.com/6965443/73587727-3c69fd00-44e5-11ea-830f-6123331408bb.png)

**Comment by meetdilip** [comment]
Seems ok with small sizes as well

![Feb v RAID](https://user-images.githubusercontent.com/6965443/73587870-1e9d9780-44e7-11ea-99dd-ed6e86e7ef3a.png)

**Comment by ubuntujaggers** [comment]
Okay, so for the vertical concept, save the svg of [this file](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-harddisk.svg):

![image](https://user-images.githubusercontent.com/38893390/73597163-1c582f00-4521-11ea-833d-3d267c9feefd.png)

Load it in Inkscape and delete the glyph to make the plain backplate:

![plain grey oblong](https://user-images.githubusercontent.com/38893390/73597249-d5b70480-4521-11ea-8c55-ddd8b4b83495.png)

...then draw your RAID design on each of the five backplates using this colour for the darker grey:

![glyph](https://user-images.githubusercontent.com/38893390/73597263-f0897900-4521-11ea-8f23-d0a3396aab49.png)

:+1:

**Comment by meetdilip** [comment]
Thanks. That is how I did it. However, I had to tweak the disk background and disk colour + stroke to make it look good.  Otherwise, the output will be

![demo raid 1](https://user-images.githubusercontent.com/6965443/73601651-59590b80-458b-11ea-80eb-7a8f0f59f268.png)

**Comment by meetdilip** [comment]
Added to other base plates as well

![demo 2](https://user-images.githubusercontent.com/6965443/73601694-06338880-458c-11ea-9847-9a075e5c0cb1.png)

**Comment by friendlyapple** [comment]
@meetdilip It looks like a server. Why not use the same style as for the SSD?

![1](https://user-images.githubusercontent.com/59767069/73606155-903d1a80-45a7-11ea-81cc-237d4da6e7b3.png)

Or why not a set of hard drives?

![2](https://user-images.githubusercontent.com/59767069/73606164-b662ba80-45a7-11ea-9740-6c62009075e5.png)

**Comment by meetdilip** [comment]
Perhaps we follow the same for HDD. 

Stacked HDD looks better. But please check existing icons for devices which uses RAID.

**Comment by friendlyapple** [comment]
@meetdilip The icon you are trying to make is too complex. You are trying to show the HDD and a system/case that manages the hardware RAID (which is not necessary). I think this goes against Yaru principles which wants an icon to be simple and easily identifiable.

It would also be wise to take inspiration from the following file:
https://github.com/ubuntu/yaru/blob/master/icons/src/scalable/source-symbolic.svg

RAID: current symbolic icon:

![icon](https://user-images.githubusercontent.com/59767069/73608461-7c071680-45c3-11ea-80b8-4cb6243e8473.png)

**Comment by meetdilip** [comment]
> You are trying to show the HDD and a system/case that manages the hardware RAID (which is not necessary).

That is how a RAID system is. Different views are welcome.

**Comment by friendlyapple** [comment]
@meetdilip I agree with you for a hardware RAID (recognized by the system as a conventional hard drive). But here it is a software RAID. Therefore your icon is not appropriate.

**Comment by meetdilip** [comment]
Please see the upstream icon. It is in post no. 3.

**Comment by friendlyapple** [comment]
> Please see the upstream icon. It is in post no. 3.

It's a choice of representation, which is probably not the best for me. It is a fairly complicated subject. Besides, if you look at macOS or Windows, they have the same icon as an ordinary hard drive. If we still want to display the difference between a conventional hard drive and a RAID, and since it is a software RAID, I think we have to keep it simple.

As you said, it's interesting to have several points of view 👍

**Comment by ubuntujaggers** [comment]
Hi guys,

We had a little chat about this and think the least controversial option is probably the same as SSD:

![73606155-903d1a80-45a7-11ea-81cc-237d4da6e7b3](https://user-images.githubusercontent.com/38893390/73609978-9ee8f900-45ca-11ea-845c-345c1abf1051.png)

...especially because the icon will rarely be seen. This would be a great first PR for a new contributor because it's simple but you get to run the scripts to build the pngs, does either of you fancy it :) If not I can do it 👍

**Comment by meetdilip** [comment]
Not smart enough for making a PR. I give it a pass this time. :)

**Comment by madsrh** [comment]
> Not smart enough for making a PR. I give it a pass this time. :)

I made [a video](https://www.youtube.com/watch?v=KZPKJX0eKkY) 😁 Can you render the .png? I think ubuntujaggers posted a guide somewhere 🤔 

Please don't be discouraged because of the disagreement!

**Comment by meetdilip** [comment]
Thanks for the video. I will check that.

I feel ok. Just that this is not my concept. So it will not be appropriate to claim the credit. :)

**Comment by ubuntujaggers** [comment]
Hmm, actually...  I just started this PR and it turns out the icon is called drive-multidisk, would it be unwise to specify "RAID" on it?  Maybe it's better to do a full colour version of the symbol :thinking:

**Comment by madsrh** [comment]
> I just started this PR and it turns out the icon is called drive-multidisk, would it be unwise to specify "RAID" on it? Maybe it's better to do a full colour version of the symbol

I agree that it might be safer. Special hardware cases like these are difficult to test.

**Comment by friendlyapple** [comment]
@madsrh Your video is great! Very well explained 😃

On the other hand, I really have trouble with Inkscape and I don't have time to train on it currently. Sorry, I can't do it. :/

**Comment by madsrh** [comment]
> On the other hand, I really have trouble with Inkscape and I don't have time to train on it currently. Sorry, I can't do it. :/

No problem. I think there's a **How to edit and render icons** video coming too 😉

**Comment by Jupiter007-43** [comment]
Personally (and as a RAID user 😉) I think the set of disk is the most understandable icon :

![](https://user-images.githubusercontent.com/59767069/73606164-b662ba80-45a7-11ea-9740-6c62009075e5.png)

But this is just my opinion...
