### ISSUE TITLE
Suggestion: create a yaru libreoffice icon theme

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1815]
This is not a bug, but I thinks it should be great to have a yaru icon theme for libreoffice, which actually looks very inconsistent with the rest of the OS :

Elementary icons looks too much "Elementary"
![elementary](https://user-images.githubusercontent.com/36476595/73187408-a5d2c000-4121-11ea-9fea-c8744d27c124.png)

Breeze icons (which at the moment seems to me to be the most neutral) looks too much "KDE"
![breeze](https://user-images.githubusercontent.com/36476595/73187463-ba16bd00-4121-11ea-9d3f-3337abcd58b2.png)

And Colibre icons are just too "Windows" 😈
![colibre](https://user-images.githubusercontent.com/36476595/73187647-02ce7600-4122-11ea-9773-1f418817c74a.png)

I know it's a lot of work, so this is just a suggestion.

**Comment by Feichtmeier** [comment]
Could you link to the specifications?

**Comment by madsrh** [comment]
Thanks @Jupiter007-43 
It's been on my wishlist for a while but it's a ton of work, so this proberly isn't going to happen in this cycle.

**Comment by Jupiter007-43** [comment]
@Feichtmeier Which mean (sorry I'm French) ?
If it's the documentation I haven't found any resource (I've been searching since yesterday).

@madsrh Yes it's over a thousand icons... 😰
But it will look very great !

**Comment by madsrh** [comment]
> Yes it's over a thousand icons... cold_sweat
But it will look very great !

Okay, my comment was a bit misleading but I would love to see this, but I doubt that it will ever happen - especially if it's thousand icons 😬 

> it should be great to have a yaru icon theme for libreoffice, which actually looks very inconsistent with the rest of the OS

A much easier solution would be to default to a icon theme that fits better with Yaru (if any of them does)

**Comment by Jupiter007-43** [comment]
> A much easier solution would be to default to a icon theme that fits better with Yaru (if any of them does)

Yes, it's a good idea, but there's really not a lot of themes available (https://libreofficehelp.com/change-libreoffice-default-look-and-feel/).

Bonus : some yaru icons in libreoffice !

![Capture d’écran du 2020-01-28 21-20-21](https://user-images.githubusercontent.com/36476595/73303210-46a2a780-4216-11ea-9d97-df2e79e813a3.png)

I got breeze zip and replace some icons.

**Comment by madsrh** [comment]
@Jupiter007-43 I had a quick look at this and it's a WAY too huge task for us. There is **3760** files within one iconset 😵 

I'll have to close the issue here. If anyone wants to step up to this "challenge" that would be fantastic!

We can't change the default icon theme in LO, so if you think there's a more fitting one to match Yaru, you'll have to file a bug against LibreOffice in Launchpad.

Thanks! 


...And if anyone wants to have a look, the files are stored here:
![image](https://user-images.githubusercontent.com/3986894/73616814-6ec84700-4618-11ea-9ff9-6df696e11bb3.png)

**Comment by Jupiter007-43** [comment]
I'm working on a here: https://github.com/Jupiter007-43/libreoffice-style-yaru

![Capture d’écran du 2020-03-04 13-13-26](https://user-images.githubusercontent.com/36476595/75878597-24560800-5e1a-11ea-92b5-ca93a9e28d7c.png)
![Capture d’écran du 2020-03-04 13-15-18](https://user-images.githubusercontent.com/36476595/75878649-35067e00-5e1a-11ea-9f33-1d55a4b238c3.png)

**Comment by Feichtmeier** [comment]
Woah awesome! 
How far are you? Maybe we could still get this into 20.04 (it's not me to decide at all, just thinking about it)

**Comment by Jupiter007-43** [comment]
Most of the work is done:
I replace all KDE blue with Ubuntu purple, rounded corners (table, ...), replace some icons with Yaru ones, and create some missing ones from scratch.

A few more screenshot:

![Capture d’écran du 2020-03-04 15-35-56](https://user-images.githubusercontent.com/36476595/75890137-3c378700-5e2e-11ea-86da-0d0c734ae1bd.png)
![Capture d’écran du 2020-03-04 15-37-47](https://user-images.githubusercontent.com/36476595/75890138-3cd01d80-5e2e-11ea-9206-b6209521501b.png)

I don't know if it should be ready for 20.04...

**Comment by madsrh** [comment]
@hellsworth Would it be possible to get this into 20.04 (if it's ready)?

**Comment by Jupiter007-43** [comment]
I'm going to attempt... but I can't promise anything 😉

**Comment by Jupiter007-43** [comment]
I will post some news here.

**Comment by hellsworth** [comment]
>Would it be possible to get this into 20.04 (if it's ready)?
@madsrh If the yaru team gets an icon theme for libreoffice to me in time, then I can make this the default.

**Comment by Feichtmeier** [comment]
Awesome @hellsworth :+1: 
Will libreoffice be a snap or a deb in 20.04?

**Comment by hellsworth** [comment]
> Will libreoffice be a snap or a deb in 20.04?

Most likely we will ship both.

**Comment by Jupiter007-43** [comment]
A preview, bundled in an extension:

[yaru-theme.zip](https://github.com/ubuntu/yaru/files/4289919/yaru-theme.zip)

**Comment by madsrh** [comment]
As much as I like the icons @Jupiter007-43 I don't think we should ship this by default. Have you checked out the work ubuntujaggers is doing with the Inkscape legacy icons?

![image](https://user-images.githubusercontent.com/3986894/75932929-f227c300-5e78-11ea-90a5-76b219ee91b0.png)

**Comment by Feichtmeier** [comment]
Yes they need to work in both light and dark themes as libre office can't handle symbolic icons yet. As mads said, check out Stuart's inkscape branch

**Comment by Jupiter007-43** [comment]
The dark theme is separated:

![Capture d’écran du 2020-03-05 18-44-09](https://user-images.githubusercontent.com/36476595/76009422-7a59a700-5f11-11ea-8109-10647b9ae415.png)

[yaru-theme-dark.zip](https://github.com/ubuntu/yaru/files/4294307/yaru-theme-dark.zip)

Do you mean that the same theme must support both light and dark variants (Breeze has two variants)?

**Comment by madsrh** [comment]
> Do you mean that the same theme must support both light and dark variants (Breeze has two variants)?

Preferably one icon theme should work in both light and dark.

**Comment by Jupiter007-43** [comment]
Oh! So a symbolic icon set isn't a good idea...

All this is for nothing. It's sad. 😢
That doesn't matter I'll put it on my computer.

**Comment by Jupiter007-43** [comment]
Great job with Inkscape 👍

**Comment by Feichtmeier** [comment]
Nooooo it's not for nothing:

Take your light set, and create 1px black and 1px white outlines, then fill it with a color, similar to what stuart did with the inkscape icons

**Comment by Feichtmeier** [comment]
@Jupiter007-43 or... before I give some crap advice, better keep your hands calm until @ubuntujaggers is back from his break, he can give real advices

**Comment by Jupiter007-43** [comment]
OK, thanks!

**Comment by Feichtmeier** [comment]
He is not done yet, but here are some, maybe it's already an inspiration for indeas:
![Bildschirmfoto von 2020-03-05 19-50-05](https://user-images.githubusercontent.com/15329494/76014858-9f064c80-5f1a-11ea-9cad-e6ba03c01d39.png)

**Comment by Jupiter007-43** [comment]
The Libreoffice Gtk dark theme support is (very) bad:

![Capture d’écran du 2020-03-06 19-22-53](https://user-images.githubusercontent.com/36476595/76111213-2cf83b00-5fe0-11ea-99ce-fc9db8390b3a.png)
(Maybe custom style make this strange rendering with the left menu)

And some icons of the actual default theme (Elementary) are almost invisible (bold, underline, align, ...) and disabled icons are just desaturated and a bit lighter (which look bad on dark theme):

![Capture d’écran du 2020-03-06 19-23-14](https://user-images.githubusercontent.com/36476595/76111215-2ec1fe80-5fe0-11ea-86c7-9097fe914f0b.png)

It's really difficult to work under these conditions... 😰

**Comment by Jupiter007-43** [comment]
I tested a mid grey icon set:

![Capture d’écran du 2020-03-06 19-56-50](https://user-images.githubusercontent.com/36476595/76113618-c75a7d80-5fe4-11ea-9123-a62003942a40.png)
![Capture d’écran du 2020-03-06 19-57-11](https://user-images.githubusercontent.com/36476595/76113620-c88baa80-5fe4-11ea-8800-c1b12075781c.png)

But it's too light on light theme and too dark on dark theme... 😑

**Comment by Jupiter007-43** [comment]
Grey icons on white background:

![Capture d’écran du 2020-03-09 17-08-23](https://user-images.githubusercontent.com/36476595/76233666-d16cbe00-6228-11ea-829a-3075a0734bd8.png)
![Capture d’écran du 2020-03-09 17-08-44](https://user-images.githubusercontent.com/36476595/76233668-d2055480-6228-11ea-8e51-ee477b59f492.png)

The visibility is good on both dark and light theme. But each icons need to be edited one by one...

**Comment by Jupiter007-43** [comment]
I tested another grey (#808080) without white background and with light purple, which look pretty well on both theme:

![Capture d’écran du 2020-03-11 14-54-59](https://user-images.githubusercontent.com/36476595/76424313-5c27f700-63a8-11ea-8628-722c28e6bff0.png)
![Capture d’écran du 2020-03-11 14-55-21](https://user-images.githubusercontent.com/36476595/76424317-5cc08d80-63a8-11ea-9a18-185891428ad3.png)

[yaru-theme.zip](https://github.com/ubuntu/yaru/files/4318609/yaru-theme.zip)

Can I get your opinion: which one is better with or without white background?

**Comment by Feichtmeier** [comment]
I think you need @ubuntujaggers opinion here.
I think your border needs to be way darker to look good in the dark theme. And the icons need to be indeed filled like you've showed in the comment above :)

**Comment by madsrh** [comment]
[This](https://github.com/ubuntu/yaru/issues/1815#issuecomment-596625833) one was really great 🎉Maybe a bit more color than just white, is probably needed IMO 😀

**Comment by ubuntujaggers** [comment]
Visually I think the mid grey symbols with people accents look smart and cool... but the problem I have with monochrome buttons in apps with many buttons is, nothing catches my eye. E.g., I use GIMP all the time, but whenever I need a particular tool I have to look at them one by one till I find it ☹️

What do you think of the 16px legacy icons in Master currently? They're like halfway between a full colour icon and a symbol and many of them are based on symbols. It's an easy style to do, if you like them it would be good to get a second pair of hands on the project if we want to target as many apps as possible (including LO). Likewise @madsrh could join in if he fancies 👍

**Comment by Jupiter007-43** [comment]
>I use GIMP all the time, but whenever I need a particular tool I have to look at them one by one till I find it frowning_face

I'm in the same case, that's why I use the color icons in Gimp 😉 (in Libreoffice I got used to symbolic). 

In fact, it was simpler for me to use Breeze as a starting point because I only had to round some corners and change the blue to purple (among other things). And also...symbolic icons are very easy to create!
There is three size 16px, 24px and 32px, most of them are very specific and there is a lot of declensions. There is about more 3000 icons! I will try with some of the legacy icons, but it will take much longer...
Certainly won't be ready for 20.04 (it was my target 😢). That doesn't matter, maybe 20.10! 😃

>it would be good to get a second pair of hands on the project if we want to target as many apps as possible (including LO).

If there's anything I can do, let me know!

**Comment by ubuntujaggers** [comment]
@Jupiter007-43, would be great to take some of the legacy icons for common functions (e.g. print) and see how they look in LO 👍

**Comment by Jupiter007-43** [comment]
Et voila !

![Capture d’écran du 2020-03-13 11-56-38](https://user-images.githubusercontent.com/36476595/76616462-5eaf5b80-6524-11ea-8c12-83e82530e959.png)

![Capture d’écran du 2020-03-13 12-03-39](https://user-images.githubusercontent.com/36476595/76616465-5f47f200-6524-11ea-9700-514490b56f54.png)

Just 2px too small (I didn't take the time to resize them).
It look great on both theme 👍

**Comment by Feichtmeier** [comment]
Nice, thanks for the screenshots.
In my opinion this could work! It's too late for a default in focal now but...
Maybe we could provide a "libreoffice-icons-yaru.deb" later in the focal cycle?
If you want to manage this task together with @ubuntujaggers don't stress yourself - it's a really huge task :)

**Comment by ubuntujaggers** [comment]
@Jupiter007-43 and I could start by targeting just the icons that appear on the top bar by default? Getting a Yaru set of those would be a great start 👍

**Comment by madsrh** [comment]
Where can I download this? Could you upload this to your [Github repo](https://github.com/Jupiter007-43/libreoffice-style-yaru-symbolic)?

> Et voila !
> 
> ![Capture d’écran du 2020-03-13 11-56-38](https://user-images.githubusercontent.com/36476595/76616462-5eaf5b80-6524-11ea-8c12-83e82530e959.png)
> 
> ![Capture d’écran du 2020-03-13 12-03-39](https://user-images.githubusercontent.com/36476595/76616465-5f47f200-6524-11ea-9700-514490b56f54.png)
>

**Comment by Jupiter007-43** [comment]
The new repository is here: https://github.com/Jupiter007-43/libreoffice-style-yaru-fullcolor

**Comment by Jupiter007-43** [comment]
And the old: https://github.com/Jupiter007-43/libreoffice-style-yaru-symbolic

I still want to finish the symbolic version!

**Comment by Jupiter007-43** [comment]
Some new screenshot (main toolbar, but some icons in other places are fullcolor too):

**Small**
![Capture d’écran du 2020-03-17 20-13-45](https://user-images.githubusercontent.com/36476595/76893337-7b34f600-688c-11ea-9107-4766fb296e76.png)

**Medium**
![Capture d’écran du 2020-03-17 20-13-18](https://user-images.githubusercontent.com/36476595/76893332-796b3280-688c-11ea-8572-a22513dd9efb.png)

**Large**
![Capture d’écran du 2020-03-17 20-14-39](https://user-images.githubusercontent.com/36476595/76893339-7bcd8c80-688c-11ea-815f-f58228537406.png)


But don't know how to render this kind of icon (just a letter) to fit consistency with overs 🤔
![Capture d’écran du 2020-03-17 20-26-31](https://user-images.githubusercontent.com/36476595/76894020-9bb18000-688d-11ea-9f33-9b3137505868.png)

It looks strange like with just a white border...

**Comment by Jupiter007-43** [comment]
🎉 I finished the main toolbar of Writer on medium size: 🎉

![Capture d’écran du 2020-03-20 15-02-02](https://user-images.githubusercontent.com/36476595/77170970-165fe280-6abc-11ea-9e71-d9782e7f190d.png)
![Capture d’écran du 2020-03-20 15-02-21](https://user-images.githubusercontent.com/36476595/77170985-1a8c0000-6abc-11ea-869a-97bf37288770.png)

What do you think of ?
Can I resize them on Large and Small size, and make declensions ?

**Comment by Feichtmeier** [comment]
This looks really good, gj @Jupiter007-43 !

**Comment by Jupiter007-43** [comment]
I had forgotten masked icons, it's done now.

![Capture d’écran du 2020-03-20 20-14-19](https://user-images.githubusercontent.com/36476595/77198736-dca4d100-6ae7-11ea-8705-c5d67569f7b7.png)
![Capture d’écran du 2020-03-20 20-14-49](https://user-images.githubusercontent.com/36476595/77198743-df072b00-6ae7-11ea-9898-4795066b62b7.png)

But my toolbar is a big mess now!

**Comment by ubuntujaggers** [comment]
This is starting to shape up really nicely  :)  Couple of thoughts:

- Some of the icons that are made up of bars and lines probably don't need the outline...  Inkscape has a mix including some that are just coloured glyphs and I don't think they look out of place:

![image](https://user-images.githubusercontent.com/38893390/77229659-03661480-6b87-11ea-879b-4ce5da9257f6.png)

- We might rethink how we handle letter-based designs.  The existing legacy buttons do have the white outline, but there are only a couple of affected buttons in Inkscape.  There's a lot more of these in LO and the overall impression might not be great in dark theme.

**Comment by Jupiter007-43** [comment]
![Capture d’écran du 2020-03-21 19-44-16](https://user-images.githubusercontent.com/36476595/77234160-95ccdf00-6bac-11ea-8e9b-4b293b4996ef.png)
![Capture d’écran du 2020-03-21 19-44-49](https://user-images.githubusercontent.com/36476595/77234161-96fe0c00-6bac-11ea-89f6-e2e634291d8f.png)

Much better without outline indeed 👍

About the letter icons, I've tried some concepts but I can't find one that looks nice and with a good contrast with light and dark theme in the same time... 😑

**Comment by Jupiter007-43** [comment]
🎉 I finished resizing Writer main toolbar icon to large and small sizes:

![dark large](https://user-images.githubusercontent.com/36476595/78926964-4ccac500-7a9e-11ea-8683-5a4d494ebc74.png)
![dark medium](https://user-images.githubusercontent.com/36476595/78926968-4d635b80-7a9e-11ea-8314-b5bc561980ce.png)
![dark small](https://user-images.githubusercontent.com/36476595/78926972-4dfbf200-7a9e-11ea-9af3-0ed4fc7510c0.png)
![light large](https://user-images.githubusercontent.com/36476595/78926973-4e948880-7a9e-11ea-99fd-3f48703cd0eb.png)
![light medium](https://user-images.githubusercontent.com/36476595/78926975-4f2d1f00-7a9e-11ea-9dcf-c04366cd1aa2.png)
![light small](https://user-images.githubusercontent.com/36476595/78926976-4fc5b580-7a9e-11ea-97d9-3e3560df89a7.png)

And I started working on the table toolbar (medium icons):

![table dark](https://user-images.githubusercontent.com/36476595/78927067-813e8100-7a9e-11ea-96b9-4d6a7ab0df06.png)
![table light](https://user-images.githubusercontent.com/36476595/78927070-826fae00-7a9e-11ea-8839-bc4a2f7ce84e.png)

**Comment by Jupiter007-43** [comment]
Other thing, what do you think of these font based icons?

![Capture d’écran du 2020-04-09 20-14-27](https://user-images.githubusercontent.com/36476595/78927279-e5614500-7a9e-11ea-95bd-e456793a79df.png)
![Capture d’écran du 2020-04-09 20-14-54](https://user-images.githubusercontent.com/36476595/78927283-e72b0880-7a9e-11ea-9607-aaebee9d459e.png)

**Comment by ubuntujaggers** [comment]
Great work @Jupiter007-43 - those text-based icons look pretty smart!

**Comment by hellsworth** [comment]
Hey folks, I've been watching this and the icons all look great! I'd like to try implementing what you have in the LO deb now but do you have any guidance on how to do that? (sorry, still learning my way around the LO packing) Have you all been building LO with the fonts to grab the beautiful screenshots? Do I need to grab some branch from https://github.com/Jupiter007-43/libreoffice-style-yaru-fullcolor first?

Any advice you all can offer would be helpful to get this in LO so thanks :)

**Comment by Jupiter007-43** [comment]
Thanks a lot @hellsworth but I don't know how to package a LO icon theme into a deb. Actually I just symlink a zip into /usr/lib/libreoffice/share/config/ which is the folder where LO looks at to find icons. I also create an oxt extension to share with others but never a deb, sorry... 😓
 
Either way, this icon theme is actually still very incomplete (only Writer main toolbar with some overs icons are available).
The symbolic version is almost complete but it is not compatible with both light and dark theme in the same time.

**Comment by Feichtmeier** [comment]
@didrocks @clobrano  could we think about getting those wonderful icons into the yaru repository and produce a .deb then?

**Comment by clobrano** [comment]
+1 from me, but wasn't @hellsworth already on this?

**Comment by didrocks** [comment]
I think that was the case, indeed

**Comment by hellsworth** [comment]
Yep I've built and loaded the zip to poke around and I'm trying to get it into the deb first, then the snap.

**Comment by Jupiter007-43** [comment]
I everyone. Here are some good news:
🎉 I finished to render all LO Writer icons  🎉 (maybe a few are missing here and there but most of them are here) !
In total, I render exactly **1461** icons.

I invite you to test it there:
https://github.com/Jupiter007-43/libreoffice-style-yaru-fullcolor/raw/master/oxt/yaru-theme.oxt

I also profit of this message to thanks all Yaru team for his hard job with this theme : I upgrade to 20.04 a few days ago and it's beautiful. 👍 Thank you !

**Comment by madsrh** [comment]
I didn't try it yet but awesome work @Jupiter007-43 🥳💪 1461 icons 😲 just wow!!

**Comment by Jupiter007-43** [comment]
I'm about halfway through. To put things into perspective, there's a lot of redundancy. And icons aren't very complexes, it's just very long to do.
But the result is very satisfying!

I forgot to specify something: new font based icons aren't available in this branch.

**Comment by fitojb** [comment]
> there's a lot of redundancy

You avoid that by making use of the links.txt file (LibreOffice’s equivalent to symlinks). See [this example from the Colibre theme](https://opengrok.libreoffice.org/xref/core/icon-themes/colibre/links.txt?r=5b56db7d) to know how to use it.

**Comment by Jupiter007-43** [comment]
Thanks for the explanation @fitojb, I didn't know the purpose of this file. It will be very useful for me. 👍
But what I meant to say was most icons are almost identical (sorry for my misspoke I'm French).
Ex: Table icons with only different symbol.

**Comment by Jupiter007-43** [comment]
Just a screenshot with new text-based icons of the main toolbar.

![Capture d’écran du 2020-05-03 18-50-29](https://user-images.githubusercontent.com/36476595/80920786-54fee300-8d72-11ea-8ff2-0306b776e9a0.png)

I think it looks good with over icons.

**Comment by Feichtmeier** [comment]
Really awesome work @Jupiter007-43

**Comment by ubuntujaggers** [comment]
Amazing work Jupiter, well done ♥️

**Comment by Jupiter007-43** [comment]
Hi everyone.
I merged a few days ago the Text-icons branch and I just finished to render all LO Calc main toolbar icons in both classic and netbook version. 🎉

![Capture d’écran du 2020-05-22 20-34-03](https://user-images.githubusercontent.com/36476595/82698728-9bf24100-9c6b-11ea-81e6-872386285a09.png)

![Capture d’écran du 2020-05-22 20-36-31](https://user-images.githubusercontent.com/36476595/82698889-f25f7f80-9c6b-11ea-8436-94b66aa0290a.png)

![Capture d’écran du 2020-05-22 20-37-32](https://user-images.githubusercontent.com/36476595/82698989-1ae77980-9c6c-11ea-9064-c23c55176103.png)

**Comment by Feichtmeier** [comment]
This looks very good @Jupiter007-43 
I really enjoy how much contrast it has and still is very sharp and yaru.
I hope we have it packaged in ubuntu soon

**Comment by Jupiter007-43** [comment]
🎉 I just finished LO Impress and Draw main toolbars:

![Capture d’écran du 2020-05-27 20-53-25](https://user-images.githubusercontent.com/36476595/83061000-95453e80-a05c-11ea-858a-e00b3c0b982a.png)

![Capture d’écran du 2020-05-27 20-57-45](https://user-images.githubusercontent.com/36476595/83061101-bdcd3880-a05c-11ea-9606-ff8e5edbc230.png)

All that's missing now are just about 400 icons...

@hellsworth have you been able to put it into a deb?

**Comment by hellsworth** [comment]
@Jupiter007-43 no sorry i've been swamped by other things. I'll try and pick this back up by the end of the week though.

**Comment by Jupiter007-43** [comment]
Don't be sorry. I understand. 🙂
Keep me informed.

**Comment by Feichtmeier** [comment]
@Jupiter007-43 first of all - awesome work as always!

Secondly, when you say 400 icons, do you mean in total - including symlinks - or really 400 unique icons?

**Comment by Jupiter007-43** [comment]
Exactly 142 unique icons x 3 sizes + some here and there.

**Comment by Feichtmeier** [comment]
Crazy.... Good luck :crossed_fingers:  :four_leaf_clover:

**Comment by Jupiter007-43** [comment]
🎉 I just finish to render all icons from /cmd (~2700 icons) 🎉
This icon pack is (almost) complete.

A last screenshot with the macro editor:

![Capture d’écran du 2020-05-31 15-47-33](https://user-images.githubusercontent.com/36476595/83879524-0d3af500-a73e-11ea-8722-9f20edd91316.png)

**Comment by clobrano** [comment]
amazing work, thanks!

**Comment by Jupiter007-43** [comment]
You're welcome. 😊
If anyone has a suggestion, tell me.

**Comment by Jupiter007-43** [comment]
After a huge work, I'm happy to say I finish to render all icons of this LO theme. 🎉
I just finish to check all folders.

Next step, create a package.

**Comment by Feichtmeier** [comment]
Thank you very much! This will help Ubuntu a lot to get a polished and consistent look!

**Comment by Jupiter007-43** [comment]
Effectively it looks great with the rest of the os !

**Comment by Jupiter007-43** [comment]
I have a few questions to ask:
Which version of Inkscape do you use (0.92 or 1.0)?
And it is too late for shipping these icons into 20.04 (never mind if it is, I just want to know)?

Thanks 🙂

**Comment by Jupiter007-43** [comment]
@hellsworth How far along are you? 🙂

**Comment by Jupiter007-43** [comment]
Since my repository will be integrated into ubuntu namespace (@didrocks on n’attend que vous 😉), I think this issue should be closed.
