### ISSUE TITLE
Suggestion: Code OSS icon

### ISSUE THREAD

**Issue by coxackie** [ubuntu/yaru#1816]
The icon for vs code (oss version - bottom one before the applications grid icon in the screenshot) is too large as compared to other yaru-style icons. I was wondering whether you would be interested in having a go at it. There are so many users of this editor - this will be highly visible.
![Screenshot from 2020-01-27 17-19-46](https://user-images.githubusercontent.com/22049642/73197672-9e171980-4129-11ea-89b2-58c6c0460713.png)

**Comment by Feichtmeier** [comment]
Hi, sorry we don't change third party apps
Especially not from those big players like Firefox, Google, Microsoft and so on. Otherwise we'll go to branding hell :) closing this, thanks for contributing

**Comment by clobrano** [comment]
Hey @coxackie, do you know if the maintainer is interested in a Yaru icon for this? We have designed only gnome default app icons and for the others we seek maintainers' permission and involvement

**Comment by meetdilip** [comment]
Was it supposed to be like this ? Adding a background is bad ?

![code oss](https://user-images.githubusercontent.com/6965443/73205818-befe5f80-4167-11ea-942b-7df31f3e9cba.png)

**Comment by clobrano** [comment]
It is not really the look of the icon, but the approach. We prefer to involve the maintainers as good manners :)
They might not like how the icon look like or just don't want to change it for branding or preference

**Comment by coxackie** [comment]
@clobrano the "maintainer" is Microsoft - I am not entirely sure how easy it would be to get them involved. Otherwise, something like what @meetdilip suggests is not bad. There is immediate branding recognition, but also making the icon more in line with the others. More like "slight shrinkage".

**Comment by clobrano** [comment]
This is the same discussion we had in the past about Firefox.

**Comment by coxackie** [comment]
Apologies - I was not around back then for such discussion. Presumably the Firefox icon would be of the same size and shape as for Chromium and Spotify in my screenshot. These do not look so way off (size-wise) as Code. But, anyway, all this is null and void - I understand your approach to respect (as well as avoid issues with) branding.

**Comment by clobrano** [comment]
> Apologies - I was not around back then for such discussion.

I did not mean you should know it already, sorry, just that our current
approach has been tested on a similar case. Thanks for the support and
please keep report any issue you think will make Yaru better.

**Comment by coxackie** [comment]
@clobrano Sorry for coming back to this, but I realised that `Code - OSS` is open source, while VS code is the Microsoft product; see: 
https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code
Distros like Arch package `Code - OSS`, which should be free of any Microsoft licencing, etc. I think that, as long as there is no icon for Microsoft VS Code, it should be OK (legally).

 Could you maybe reconsider? Especially since an attempts has been made previously by @meetdilip.

**Comment by clobrano** [comment]
Hi @coxackie, it was not a problem of licensing, but of being a third-party application + not installed by default. If there is any interest from them to have a Yaru icon, we could have a go.

**Comment by coxackie** [comment]
Thanks, @clobrano, but in this case I am not sure who "them" would be that needs to be consulted. It is not Microsoft per-se, as this is an OSS build of the repo, not Microsoft's VS Code. Specifically, I am using [this](https://www.archlinux.org/packages/community/x86_64/code/) package.

**Comment by Feichtmeier** [comment]
Answering to the initial issue report, I am not sure if I can follow. I think the vscode icon looks quiet fancy along other icons and also along yaru icons

![grafik](https://user-images.githubusercontent.com/15329494/101790107-5bbcb800-3b02-11eb-8df2-3dac37a57175.png)

What is code OSS?

**Comment by coxackie** [comment]
I am not talking about vscode exactly; code - oss is an "open source software" build, directly from the repo. You can see the icon below - it is the last blue one with white lines.

![image](https://user-images.githubusercontent.com/22049642/101790836-cbc74000-3afa-11eb-8cde-6e2b98b194c7.png)

**Comment by madsrh** [comment]
https://github.com/microsoft/vscode/blob/master/resources/linux/code.png

**Comment by Feichtmeier** [comment]
lol this is indeed butt ugly :D 
Wouldn't it be cool if we would rather get our icon crew to contribute an icon to them?

**Comment by coxackie** [comment]
@Feichtmeier that would be amazing, although I am not sure how receptive they might be at including an icon with specific guidelines,  as Yaru tries. For reference, here is what Papirus has done:
![image](https://user-images.githubusercontent.com/22049642/101793502-c7e8ed00-3afd-11eb-86d9-6da3fca0c96c.png)
All these correspond to a different build of code - it is the first one I am talking about. (Obviously, I am not leaving this here for you to "take inspiration", but just to show that Papirus also has a candidate that follows their guidelines.)

**Comment by coxackie** [comment]
@Feichtmeier @clobrano This whole discussion is also making me realise that there is no obvious way for requesting icons. I understand that you want to get the OK from developers, but I think in this case there should be a way to do this seamlessly for anyone who wants to request an icon. For example, a centralised webpage of some sort that we can direct authors of packages to see the yaru style, and give consent that they are OK with yaru to implement an icon. It would further increase your visibility in time, and developers would potentially request it themselves. At the end of the day, everyone would like to see an nice icon in Ubuntu for their app.

 If you think this is a reasonable idea that should be discussed, I would like to open a new issue so other parts of the community can give their feedback.

**Comment by coxackie** [comment]
@Feichtmeier sorry for coming back to this, but is there scope, as you discussed above, to do something with the horrid `code - oss` icon? if not, and one really needs to go through asking permission, could you tell me how I should proceed? Do I open an issue at `vscode` repo and point to this issue? I have asked (comment right above) on what the procedure should be, but I cannot see any guidelines.

**Comment by Feichtmeier** [comment]
@coxackie I would just try to point out that you do not like their icon and would love if they would make a better icon - or if you have a suggestion include a suggested icon

**Comment by coxackie** [comment]
@Feichtmeier Do I understand correctly that, if I ask them whether it is OK to use, for example, the icon in https://github.com/ubuntu/yaru/issues/1816#issuecomment-578907387 in the yaru icon theme and they say ok, then you will include it?

**Comment by Feichtmeier** [comment]
If the app devs give their okay we can ask our icon team if they have time to create an icon.
But in opposite to for example spotify or vscode where the real icon looks very good and a yaru icon would only provide consistency to Ubuntu, this codeoss icon would be better provided for all people because it looks really bad. Thus I would not request the icon here, but on their repo and then see if they agree. I hope I didn't over complicate my answer =D

**Comment by coxackie** [comment]
@Feichtmeier the answer is not complicated, but maybe the approach is not the best one. I feel they may be much more willing to accept yaru shipping a slightly changed icon than changing their icon themselves (even with the help of another team). I would rather propose to them first that yaru ships something like https://github.com/ubuntu/yaru/issues/1816#issuecomment-578907387 and then, if they wish, to have help in redesigning the icon. I feel that if I ask them directly that their icon gets redesigned they will dismiss the issue. Is it OK if I proceed as suggested?
