### ISSUE TITLE
ProgressBar Style

### ISSUE THREAD

**Issue by Neocazen** [ubuntu/yaru#1819]
Is there any chance that the Progress bar will get past that?

![Captura de tela de 2020-01-27 19-35-27](https://user-images.githubusercontent.com/15347187/73220628-a9744000-413d-11ea-87fa-00251f88dbb1.png)

For this?
![Captura de tela de 2020-01-27 19-36-30](https://user-images.githubusercontent.com/15347187/73220696-d163a380-413d-11ea-93cb-f3a777c3344d.png)

Get more modern

**Comment by Feichtmeier** [comment]
No sorry, at least not from my side. I am fine with the progress bars in ... what is that? A treeview?

Yes it's a treeview :) 
I would rather not start fiddling with those again. I was so happy that upstream modernized them. You should have seen them last year in Adwaita :D Looked like comic sans

**Comment by Neocazen** [comment]
> No sorry, at least not from my side. I am fine with the progress bars in ... what is that? A treeview?
> 
> Yes it's a treeview :)
> I would rather not start fiddling with those again. I was so happy that upstream modernized them. You should have seen them last year in Adwaita :D Looked like comic sans

This is a view of Deluge Torrent with a yaru theme that I modified (the first version), but the code is very polluted. 
    I agree. Adwaita has always been ugly. You can only use gnome with this Ubuntu theme. Beautiful and differentiated.
        Congratulations on the work of making the Dark theme really dark and without the blue that has no identity with Ubuntu.
        No more, thanks for responding.
