### ISSUE TITLE
Hover for menus and popovers is too dark

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1821]
I find the current hover for menus and popovers to be just a tiny bit too dark (not the dark theme). Could we lighten it up a bit? 

Also there's a huge difference between the sidebar hover (found in Settings and Nautilus) and menus and popovers hover.

For reference:
https://github.com/ubuntu/yaru/pull/1486

**Comment by Feichtmeier** [comment]
Just play with it in _tweaks line 1. I think you are right. We need to remember to adapt the shell too water the big pr is merged
