### ISSUE TITLE
focus ring on switches looks blurry

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1822]
![Peek 2020-01-28 13-15](https://user-images.githubusercontent.com/15329494/73267285-a6765f80-41d0-11ea-93a9-6e4b4f43c8cc.gif)

**Comment by clobrano** [comment]
I'm just working on this too, how do you think about this instead?

![Peek 2020-01-28 14-55](https://user-images.githubusercontent.com/2883614/73270113-5b634900-41de-11ea-9347-5011b4f0eac7.gif)

**Comment by Feichtmeier** [comment]
Looks blurry on the outside

**Comment by Feichtmeier** [comment]
I think the colour is probably the worst pick. I think even the dashed line was better.
You made it clear that blue can't be an option in any way so I'm not sure about this coloured ring all together
Mpts initial problem was that SWITCHES had no visible outline

**Comment by Feichtmeier** [comment]
@clobrano 

![light](https://user-images.githubusercontent.com/15329494/73444030-b5cfe700-434f-11ea-9d75-e2a028681ab5.gif)

**Comment by clobrano** [comment]
it looks good to me, good work!
