### ISSUE TITLE
Links aren't visible on hover

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1826]
Did anyone else notice the link color in Firefox using the dark theme?

I guess this is a _upstream issue_ or a _can't fix_, right @Feichtmeier 
![Peek 2020-01-29 00-28](https://user-images.githubusercontent.com/3986894/73339956-a73dde80-422e-11ea-9dd3-c31abb808dbd.gif)

**Comment by clobrano** [comment]
Hi @madsrh, 

from which application this gif comes? Is it Chrome?

**Comment by madsrh** [comment]
> Did anyone else notice the link color in **Firefox** using the dark theme?

😉

**Comment by clobrano** [comment]
Man, sorry, I need a second coffee today

**Comment by clobrano** [comment]
I think this is firefox specific. The hover bg is probably too bright and it's one case where chromium does it better

![image](https://user-images.githubusercontent.com/2883614/73343797-7cc94100-4281-11ea-9119-fb7c582d2753.png)
![image](https://user-images.githubusercontent.com/2883614/73343841-8e124d80-4281-11ea-89c2-3586b721fbf6.png)

**Comment by clobrano** [comment]
Let's keep it in backlog, since it's an accessibility problem at least

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/73404200-66f36480-42f1-11ea-9bf4-be844caf23d0.png)
This is from adwaita-dark
I am not entirely sure, but isn't this the same blue?

**Comment by Feichtmeier** [comment]
No, lol they actually somehow suck in the $link_color 
![image](https://user-images.githubusercontent.com/15329494/73446385-8e2f4d80-4354-11ea-9e2d-3fe03037896d.png)

But it's not from the public colors that are at the top of the css file

**Comment by madsrh** [comment]
> What if we change the $link_color only for the dark theme to the "old" $blue?

That would work. You know the answer is orange link text 🤣 

Would it be better to have the same (the old) link color for both light and dark? We didn't change it because it wasn't working. The "only reason" was to be closer to the vanilla color palette 🤷‍♂ Don't get me wrong, I like the new blue.

**Comment by Feichtmeier** [comment]
Almost all colours are different in the dark theme because it's just a different mix of colours ofc :)
Yes I personally like $blue much more than $linkblue but the link blue is less of a problem in the light theme as it has a better contrast there
I also tried to lighten it up for the dark theme but then it looks washed out
