### ISSUE TITLE
Shell popover styling

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1832]
Here's a wishlist @Feichtmeier. Let's see if any of them are fixable.

1) **Less padding**
Actually, the line height isn't much different between GTK and the shell, but the padding around the separators are huge. 
![image](https://user-images.githubusercontent.com/3986894/73555408-dbdbb100-444d-11ea-8df7-c408c0b8312c.png)

2) **Background is different**
This might be deliberately but the background color is #fff in the GTK context menu and #f7f7f7 in the shell menus 🤷‍♂ 

3) **Shell does not respect font change**
Not sure if this is even fixable, but it would be great if the two were linked. Perhaps we could tag didrocks ?
![image](https://user-images.githubusercontent.com/3986894/73555005-1db82780-444d-11ea-86cb-b5cddf02dac8.png)

**Comment by Feichtmeier** [comment]
2) is easy and I'm sure it's fixed in the WIP PR if not three secs

3) is luckily fixed with the new shell version 

1) could be difficult to not break anything but I'll check

**Comment by Feichtmeier** [comment]
@madsrh concerning the colour, which yaru version did you try?
The popovers are f7f7f7 in master
https://github.com/ubuntu/yaru/blob/9c5f466d866eaf25abfdb2a832ff6291118a7677/gnome-shell/src/gnome-shell-sass/_colors.scss#L6
->
https://github.com/ubuntu/yaru/blob/9c5f466d866eaf25abfdb2a832ff6291118a7677/gnome-shell/src/gnome-shell-sass/_common.scss#L600

**Comment by madsrh** [comment]
Oh, I don't recall 🤔I'll check later.

Do you prefer the f7f7f7 or white?

**Comment by Feichtmeier** [comment]
f7f7f7, like in gtk

**Comment by madsrh** [comment]
👍 As long as they use the same color I'm happy 😀

**Comment by madsrh** [comment]
@Feichtmeier 

![image](https://user-images.githubusercontent.com/3986894/75099542-2cfd4180-55c3-11ea-9237-770d7ae38a22.png)

**Comment by Feichtmeier** [comment]
Master?

**Comment by madsrh** [comment]
> Master?

Yes, apprentices?

Sorry, couldn't resist. Yes, it's in master

**Comment by Feichtmeier** [comment]
Well then it's a problem with how the shell renders the colors, have a look yourself:

![Bildschirmfoto-20200222230229-1848x1053](https://user-images.githubusercontent.com/15329494/75099954-d1818280-55c7-11ea-9393-94fdc2c03d50.png)
![Bildschirmfoto-20200222230704-1848x1053](https://user-images.githubusercontent.com/15329494/75099989-58365f80-55c8-11ea-8086-2cff73d0b54d.png)

**Comment by madsrh** [comment]
As you can see in the closed PR above, I tried to just use $porcelain which works just fine (I messed up the PR though).

I know this is not the prefered approach, but could we do this? or perhaps @clobrano can spot something from your screenshots above 😃

**Comment by clobrano** [comment]
About point number 2 is the context menu that has the "wrong" color (in master too), I can propose a PR right away

![Peek 2020-02-25 10-44](https://user-images.githubusercontent.com/2883614/75235246-369dc980-57bc-11ea-8b8e-11ef618b5470.gif)

**Comment by madsrh** [comment]
Sorry @clobrano I should have been more clear. The issue has been boiled down to the shell menu not being #f7f7f7 - SORRY
See the screenshot [here](https://user-images.githubusercontent.com/3986894/75099542-2cfd4180-55c3-11ea-9237-770d7ae38a22.png)

**Comment by clobrano** [comment]
Oh, sorry I misunderstood.

Context menu is white as well, do you prefer it different from all the rest?

**Comment by madsrh** [comment]
> Context menu is white as well, do you prefer it different from all the rest?

I do like the white context menu, but I understand that it's not optimal, so perhaps your suggestion above is better

**Comment by clobrano** [comment]
Ok, so I confirm that in master, shell popovers are #F7F7F7

![image](https://user-images.githubusercontent.com/2883614/75236735-81b8dc00-57be-11ea-8912-a1fcc6e8357b.png)

**Comment by Feichtmeier** [comment]
I can't nail down what I prefer
The popovers having $bg_color is needed to have a good contrast against the brighter buttons

I agree that it would be nice to have one colour for everything that is some kind of menu

On the other hand a context menu is a little bit different context than a popover

I can live with both. It's up to you two guys :)

**Comment by madsrh** [comment]
> I can live with both. It's up to you two guys :)

👍 

> context menu is a little bit different context than a popover and the current white menus look cool

It does look cool 😄 

I just can't live with the #f7f7f7 which I think gives it an old school look

**Comment by Feichtmeier** [comment]
We could say "screw light theme(s) popover button contrast"
And just make all menus and popups and popovers and popmenuupovers and what not white 🤷‍♂
