### ISSUE TITLE
Terminal window bar is opacity 0 

### ISSUE THREAD

**Issue by mdragossh** [ubuntu/yaru#1837]
Fedora 31, Gnome 3.34.3
![Screenshot from 2020-02-01 22-47-32](https://user-images.githubusercontent.com/46487312/73598760-fc3a6700-4544-11ea-9a36-3a2f13b932b3.png)

**Comment by clobrano** [comment]
Hey @mdragossh, 
Are you installing from sources? If that so, try first deleting all Yaru folders from `/usr/share/themes` and then re-install
