### ISSUE TITLE
Add more animations to the gtk-theme

### ISSUE THREAD

**Issue by ghost** [ubuntu/yaru#184]
Please add "design"-label.

The theme should have more animations to look modern. Some examples could be found in the pop-theme. I do not know how to make gifs. Maybe someone else could so the designers could see some examples and look what would fit to the theme.

**Comment by clobrano** [comment]
Hi @NusiNusi,

to make gifs, you can install Peek from Gnome Software. Just be aware to use Communitheme on Xorg (you can select it at login) because last time I tried, Peek wasn't working on Wayland.

In the meantime, can you explain where you'd like to see more animations? At least designer can have an Idea of what you expect.

**Comment by NusiNusi** [comment]
@clobrano Thank you for the tip.
Here are some animations i found in other themes (pop-theme). I am not sure what other animations are possible. These animations look a lot like google materials design. Of course i am open to a different design-language with other animations.

Stackswitcher
![stackswitcher](https://user-images.githubusercontent.com/36449926/36440362-e04b5122-166f-11e8-83d0-77f65e31f714.gif)

Tabs in nautilus
![nautilustab](https://user-images.githubusercontent.com/36449926/36440365-e06799ea-166f-11e8-89d2-64d57379ee0e.gif)

In nautilus
![nautilus](https://user-images.githubusercontent.com/36449926/36440366-e083d164-166f-11e8-8e44-2248c0bd625b.gif)

The little headerbar buttons
![headerbarbuttons](https://user-images.githubusercontent.com/36449926/36440367-e0a51aa4-166f-11e8-850a-496400c8fd6e.gif)

Buttons (for the button-behaviour i opened another issue)
![buttons](https://user-images.githubusercontent.com/36449926/36440368-e0cc61e0-166f-11e8-86ac-0538c2105bce.gif)

**Comment by jim3872** [comment]
Pop theme would form a great base to work from ;)

**Comment by madsrh** [comment]
**Yes!** @NusiNusi is definitely lacks some animations to look modern.

I've been looking at POP OS too and I really like it. Changing between a lot of folders quickly in Nautilus feels a bit annoying, but I guess that's not the typical use case. We could make the Communitheme animations slightly more discreet IMHO. I think subtle is the keyword here.

Just looking at [CodePen for animated buttons](https://codepen.io/search/pens?q=button+animation&limit=all&type=type-pens) shows that there's a million ways to do this. We could simply ask **[isantop](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/29)** to help implement this. This would free up the other devs, to do other work, but of course we should know exactly what we want first and that might require creating a few mockups.

What exact parts of the UI are animated?
- Sidebars (Nautilus, Gnome Tweak, ...)
- Stackswitcher (Natutilus, Softwarecenter, Rythmbox, ...)
- Checkboxes (_already done_)
- Buttons (On hover / press)
- ?

**Comment by NusiNusi** [comment]
+1 for asking isantop! I asked him already but he did not answer me. It would be better when someone of the communitheme-team asks him. I am just an outsider. Maybe you @madsrh :) His help would be great and i am sure he has some awesome ideas when it comes to animations. Pop-theme is top-notch when it comes to animations and pushing possibilities of gtk-themes to the edge.
Another part that could be (more) animated:
- progressbar (i remember progressbars with a glow)
- minimize, maximize and close-button when clicked?

**Comment by NusiNusi** [comment]
@madsrh could you find a moment to reach isantop? Something new on that?

**Comment by madsrh** [comment]
@NusiNusi I'm still investigating difference animations ideas. I'll post here before moving on.

**Comment by NusiNusi** [comment]
looking forward to it! any other themes we could take some inspirations from? couldnt find other themes with animations.

**Comment by clobrano** [comment]
> When the window gets closed the close-button changes it color.
I guess this is because it hasn't any other effect when pressing the button. Communitheme has a "press" effect on the button already and I don't feel the need to a color change. Also red would be too similar to current orange

**Comment by NusiNusi** [comment]
@madsrh i discovered the beautiful material-ubuntu-theme from @nana-4 . It has very nice animations too. I recommend you to have a look at it.
![peek 2018-03-05 20-55](https://user-images.githubusercontent.com/36449926/36996722-c6398522-20b7-11e8-8832-9aae2e8f4d7b.gif)

**Comment by clobrano** [comment]
I would not overkill though. It's nice and cool when you see it the first times, but think about working on it for hours.

**Comment by madsrh** [comment]
> I would not overkill though. It's nice and cool when you see it the first times, but think about working on it for hours.

+1 👍 

To quote myself:
> Changing between a lot of folders quickly in Nautilus feels a bit annoying, but I guess that's not the typical use case. We could make the Communitheme animations slightly more discreet IMHO. I think subtle is the keyword here.

**Comment by nana-4** [comment]
FYI, Pop, Adapta and material-ubuntu-theme that mentioned here are all derivatives of [Materia theme](https://github.com/nana-4/materia-theme) which based on Material Design. :)

And I agree here with _subtle_ animations @madsrh said. In many cases, Material ripple effects wouldn't suit with Cmmunitheme IMO.

**Comment by madsrh** [comment]
Perhaps it just the colors that makes it jump out. [Matcha](https://www.gnome-look.org/p/1187179/) also uses Material Design, but the color is way more subtle. 

If you've got an idea @nana-4, please just take a shot at it 😄

**Comment by nana-4** [comment]
@madsrh Hmm, at least to me Matcha doesn't look like Material Design. It looks flat design as written in the description.

Anyway I'll post it here if I find a good idea. :)

**Comment by madsrh** [comment]
@NusiNusi Yes it's a Arc derivative, but I was refering to the animation in the pathbar.

Great! Looking forward to seeing what you come up with 😄

**Comment by NusiNusi** [comment]
@madsrh  pretty sure you meant @nana-4  ;-) I am looking forward to his animations too.

**Comment by clobrano** [comment]
@fitojb we're all on the same page

**Comment by nana-4** [comment]
Here are a few ideas about underlines in stack-switcher/path-bar:

1. Checked animation with hover background (#225)
![check-animation-with-background](https://user-images.githubusercontent.com/9556384/37146801-2d8e9800-2308-11e8-8834-f7f98b98284e.gif)

2. Checked animation with current design
![check-animation](https://user-images.githubusercontent.com/9556384/37146914-82d79848-2308-11e8-951f-ecd38ee6a261.gif)

3. Hover animation like Firefox Quantum
![hover-animation](https://user-images.githubusercontent.com/9556384/37146803-2db8c5b2-2308-11e8-8d74-543901df2d8e.gif)

I personally like No.3 (the hover animation). :wink:

**Comment by NusiNusi** [comment]
I like no. 1 but without the orange line. Instead of orange the line could be grey. Already enough orange in the theme. But this is only my little opinion.

**Comment by pojntfx** [comment]
I like 1 as well, otherwise there is a little to much movement IMHO

**Comment by godlyranchdressing** [comment]
I really like 3. I've been experimenting on my own, but I'm not really sure what look to go for.

![peek 2018-03-22 10-53](https://user-images.githubusercontent.com/27529229/37778045-5b98a3e6-2dbf-11e8-8e6b-3af6d3b67b2c.gif)

**Comment by nana-4** [comment]
@godlyranchdressing Sorry for the late reply. I also still like 3. :)

IMHO, your gif's animation might be too _dramatic_.

But inspired by _your animation_ and [this post](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/794), I came up with such a sidebar animation:

![peek 2018-04-01 01-05](https://user-images.githubusercontent.com/9556384/38165082-fef194ae-3548-11e8-9988-adb8c1da5a6b.gif)

It's just an idea, I think such a _subtle_ animation would not feel annoyed.

**Comment by NusiNusi** [comment]
@nana-4 I think with adding bold black text and black symbol it would be even better.

**Comment by nana-4** [comment]
@NusiNusi Here is:

![peek 2018-04-01 02-10](https://user-images.githubusercontent.com/9556384/38165696-6829f764-3552-11e8-9c98-5e9c4c53f35d.gif)

Indeed (IMO) it looks better than before. :)

**Comment by NusiNusi** [comment]
IMHO perfection!

**Comment by clobrano** [comment]
Interesting :smile: , I'd like to try that

**Comment by madsrh** [comment]
+1 Let's try it. Like [CraigD's mockup](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/791) on the forum, this is, as part of the community requested, less orange 👍

**Comment by NusiNusi** [comment]
> Like CraigD's mockup on the forum, this is, as part of the community requested, less orange +1

I see with words i cant make my suggestions clear enough. Mockups is the way to go... Need to learn how to make them.

**Comment by CDrummond** [comment]
@nana-4 It think it'd be nicer if the selected item text still aligned with the rest. Either that, or the icon should move too - then it'd look like the orange bar moved the icon + text. But my preference would be to keep the text aligned.

**Comment by NusiNusi** [comment]
@nana-4 @madsrh @clobrano I found some very nice animations on this site. It shows some animations that could be done with lines like communitheme has in some places. pretty sure it can give at least some inspiration.
http://littlesnippets.net/some-inspiration-for-menus-using-animated-lines/

**Comment by madsrh** [comment]
What do you guys think about the way the text is animated [here](https://youtu.be/VzXlLnczygo?t=5s)  when a sidebar button is pressed? Use the gear in the YouTube player to set playback to 0.5

**Comment by madsrh** [comment]
@NusiNusi Yes, pressed down. It hard to describe in english, but check the videos and 50 or even 25% speed. I don't think the opposite (bigger) would make any sense. To me, this animation translates 100% to pushing something in the real world - like pushing your hand into a foam pillow and how it "slowly" returns to its original shape.

I hope @nana-4 or @godlyranchdressing will give this a try 😄

**Comment by NusiNusi** [comment]
When the selected item on sidebar gets bold black text + black symbol + vertical orange line it will be the perfect equivalent to the selected item in stackswitcher (only difference is the horizontal line and inverted text- and background-color. When this (very beautiful) animation gets added to the sidebar we should talk about if we should add it to the stackswitcher too. And yes, pushed means smaller, you are right. Looking forward to the implementation.

**Comment by madsrh** [comment]
Not sure if this belongs here or in #397 :man_shrugging: 
I just stumbled upon the hover effect for buttons, and wanted to suggest this:
```
*button:hover { transition: all .2s ease-in-out; }
*button { transition: all .4s ease-in-out;   }
```

![peek 2018-05-28 02-37](https://user-images.githubusercontent.com/3986894/40608580-b8990992-6220-11e8-9d57-8eefb5dd1743.gif)

It might be a bit too much with the long fadeout, but just a suggestion :smile: 

IMHO it feel more smooth, but the current does feel very fast responding.

**Comment by clobrano** [comment]
This was because we have no transition on non-flat buttons :D 

I feel that .4s and ease-in-out is a bit too slow. What about this (.4s ease-out)
![button-transition](https://user-images.githubusercontent.com/2883614/40936995-8319f1e6-683d-11e8-8808-173fa54b8fc6.gif)

**Comment by madsrh** [comment]
@clobrano +1 let's give it a try 😁

**Comment by Feichtmeier** [comment]
Can't we close this? Ripple effects belong in material design themes. This is the wrong theme for this

**Comment by madsrh** [comment]
Sure, but I think there's still room for more animations IMHO - like the pressed sidebar I mentioned above

**Comment by Feichtmeier** [comment]
Didn't we decide against that sidebar stripe? oO 
Or which sidebar look are you talking about?

**Comment by madsrh** [comment]
@Feichtmeier the one mentioned here: https://github.com/ubuntu/communitheme/issues/184#issuecomment-382121981

**Comment by Feichtmeier** [comment]
@madsrh 
I am not sure if I interpret this *ultra hd* gif correctly ;D Sorry if I am a bit slow here. 
You are talking about the active effect, right?
You want to increase the fon-weight in active state, something like this?
![peek 2018-07-20 20-28](https://user-images.githubusercontent.com/15329494/43018956-a24bbd28-8c5b-11e8-849f-98e37ef47138.gif)

**Comment by Feichtmeier** [comment]
Why is this gtk2 :0 ?

After watching the video mads attached and not the gif, I have to admit that those animations do not really fit to the overall look and feel we currently provide, in my opinion.

**Comment by clobrano** [comment]
My bad, it's not gtk2 indeed. Alright, we can close this one as well
