### ISSUE TITLE
Gtk3: suggested- and destruction-action buttons need special cased :focus styling

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1840]
![image](https://user-images.githubusercontent.com/15329494/73606846-f2e5e480-45ae-11ea-923d-4b66d406834c.png)

![image](https://user-images.githubusercontent.com/15329494/73606854-288acd80-45af-11ea-9627-47d60d8d14f5.png)

**Comment by friendlyapple** [comment]
We can take inspiration from bootstrap: https://getbootstrap.com/docs/4.4/components/buttons/

![buttons](https://user-images.githubusercontent.com/59767069/73612415-e2079400-45eb-11ea-99a4-139aa722fae8.png)

**Comment by Feichtmeier** [comment]
I think it looks really good
I don't know if it's doable though, I'll check

**Comment by Feichtmeier** [comment]
Nope, doesn't work with gtk :/
![image](https://user-images.githubusercontent.com/15329494/73612669-f9e01780-45ed-11ea-950d-d1ba6f0192e9.png)

I would love this look if we could finally go full 2020 and have flat buttons but :man_shrugging: 

This is from the PR
![image](https://user-images.githubusercontent.com/15329494/73612684-2431d500-45ee-11ea-84f1-923760ec306b.png)
![image](https://user-images.githubusercontent.com/15329494/73612698-39a6ff00-45ee-11ea-91ac-0754f51720a1.png)

**Comment by clobrano** [comment]
LOL, I had a patch ready for this, but forgot to push it... It looks good, we can use this :D
