### ISSUE TITLE
Icons: blueetooth icon has the old suru squircle baseplate

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1841]
![image](https://user-images.githubusercontent.com/15329494/73606868-5a9c2f80-45af-11ea-8e51-6280e8f21a2a.png)

**Comment by ubuntujaggers** [comment]
Good spot!

**Comment by ubuntujaggers** [comment]
Actually we've got a square version of that icon:

![image](https://user-images.githubusercontent.com/38893390/73607489-77843300-45ae-11ea-8c6c-aa13fcf00fa2.png)

...but it looks like I forgot the pngs, lol.  Doing now.
