### ISSUE TITLE
Gtk3: outline-offset for dialogue buttons could fit better

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1844]
![image](https://user-images.githubusercontent.com/15329494/73607591-604a4300-45b8-11ea-8d75-40e2f238ac17.png)

Do you agree @clobrano ?
If yes I fix it

**Comment by clobrano** [comment]
Indeed, but double check with linked buttons

**Comment by Feichtmeier** [comment]
Okay I'll with linked buttons too
