### ISSUE TITLE
Combobox menu’s edges are both 1 pixel too wide

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1849]
In Yaru

![image](https://user-images.githubusercontent.com/2883614/73669689-2c4e4b00-46a8-11ea-9c88-8cee7d77ce33.png)

In Adwaita

![image](https://user-images.githubusercontent.com/2883614/73669733-4425cf00-46a8-11ea-97b4-49565cf72e08.png)

**Comment by Feichtmeier** [comment]
Oh weird. I hope it's not because of the slim buttons :(

**Comment by clobrano** [comment]
I don't expect that, the width of the buttons is not affected, I believe

**Comment by clobrano** [comment]
Basically, I think it's something on gtk side

This is the structure of this widget, at least in widget factory

![image](https://user-images.githubusercontent.com/2883614/73767245-7c481300-4777-11ea-8fbd-58820ab4eec3.png)


The window decoration inside a combobox is 1px larger than the combobox itself because of the border. I checked other themes and it seems to be the same everywhere.
One solution would be to remove both border and box-shadow from the window decoration and replace it with its sibling menu's border.
This works, but only inside gtk-inspector :disappointed: 

![image](https://user-images.githubusercontent.com/2883614/73766733-c250a700-4776-11ea-989a-5f5f54b23eae.png)

```
combobox decoration {
  box-shadow: none;
}

combobox menu {
 border: 1px solid #BBB;
}
```

I also tried with different `background-clip`, but without success

**Comment by Feichtmeier** [comment]
Does the menu padding change anything there?
And thanks already for time investment
Another idea would be up blur the shadow more again? Like in yaru 1.0

**Comment by Feichtmeier** [comment]
Also... Maybe this is really an issue that's not sooooo important? @matthewpaulthomas

**Comment by clobrano** [comment]
Yep, probably is not solvable anyway

**Comment by clobrano** [comment]
Alright, let's close this now and keep an eye on it in case we find a way to solve it
