### ISSUE TITLE
Gtk3: osd buttons could be more visible

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1850]
@madsrh @ubuntujaggers @clobrano 

Currently:
(normal)
![image](https://user-images.githubusercontent.com/15329494/73681980-b7870b00-46bf-11ea-80bc-6f898bce79b9.png)

(hover)
![image](https://user-images.githubusercontent.com/15329494/73681998-c372cd00-46bf-11ea-9eb2-9043dccf4f5f.png)

(active)
![image](https://user-images.githubusercontent.com/15329494/73682019-cec5f880-46bf-11ea-8bd3-4f23d088463e.png)

Idea:

(normal)
![image](https://user-images.githubusercontent.com/15329494/73681783-5c551880-46bf-11ea-981c-b5cbfead34ba.png)

(hover)
![image](https://user-images.githubusercontent.com/15329494/73681832-70007f00-46bf-11ea-9f99-186f4fbf3df0.png)

(active)
![image](https://user-images.githubusercontent.com/15329494/73681864-7d1d6e00-46bf-11ea-8075-d202636cb5d3.png)

Also might the sliders brighter - WDYT?

**Comment by clobrano** [comment]
Hover seems too similar to normal I think. Probably a normal color less bright?

**Comment by Feichtmeier** [comment]
Yes indeed that hover is not much difference

But the first question is: do you have a problem with the current look? =)

**Comment by clobrano** [comment]
*Slightly* brighter will be better

**Comment by Feichtmeier** [comment]
![Peek 2020-02-03 20-43](https://user-images.githubusercontent.com/15329494/73685116-d5576e80-46c5-11ea-9657-589544ecb0e2.gif)
Like this?

**Comment by Feichtmeier** [comment]
Less bright on normal
![Peek 2020-02-03 20-53](https://user-images.githubusercontent.com/15329494/73685961-65e27e80-46c7-11ea-8731-9bd87a630f26.gif)

**Comment by clobrano** [comment]
Better this last one for me

**Comment by Feichtmeier** [comment]
Okay here in detail:

(normal)
![image](https://user-images.githubusercontent.com/15329494/73686244-eacd9800-46c7-11ea-900f-5a08787e4d66.png)

(hover)
![image](https://user-images.githubusercontent.com/15329494/73686289-fa4ce100-46c7-11ea-81e2-0060b93a3522.png)

(active)
![image](https://user-images.githubusercontent.com/15329494/73686312-06d13980-46c8-11ea-8110-b1da2b86316f.png)

@clobrano what about the bright slider ? Do you like it? Or rather not?

**Comment by Feichtmeier** [comment]
Dark slider
![image](https://user-images.githubusercontent.com/15329494/73686461-4f88f280-46c8-11ea-850e-85a69b772cad.png)

**Comment by Feichtmeier** [comment]
Slightly less bright white slider
![image](https://user-images.githubusercontent.com/15329494/73687146-b6f37200-46c9-11ea-8211-45ab6fcd673d.png)

**Comment by clobrano** [comment]
Yeah, probably better bright, but not this last one
