### ISSUE TITLE
Why Current Title Bar is too much big?

### ISSUE THREAD

**Issue by Donboscow** [ubuntu/yaru#1854]
I'm currently using "Yaru" community theme in my Ubuntu 18.04.3 LTS. Problem is, it's title bar is unusually too much big. Is there any plan to fix this issue in upcoming Ubuntu 20.04 release?

![rsz_screenshot_from_2020-02-04_10-25-33](https://user-images.githubusercontent.com/44976018/73714368-e42c3880-473a-11ea-87ff-5a29f02cdfa7.jpg)

**Comment by madsrh** [comment]
Hi @Donboscow 
Thanks for taking the time to report this.

> Is there any plan to fix this issue...

The theme is based on Adwaita (which has an even bigger headerbar) and we don't want to risk break anything by reducing the height of the headerbar further.

For more info see issue #179 or #451

Thanks again 😃

**Comment by Feichtmeier** [comment]
Even though I agree on closing it, I'm wondering how Ambiance did to:

- slim down titlebars that are not CSD
- keep headerbars and CSD titlebars as they are

**Comment by clobrano** [comment]
Probably smaller window controls
