### ISSUE TITLE
Title bars and menu invisible in some GNOME apps

### ISSUE THREAD

**Issue by Dragon8oy** [ubuntu/yaru#1855]
## Expected Behavior
When applications, I would expect the menu bar to be visible and menus to be visible.

## Actual Behavior
Instead, the menu bar background is invisible. Menus are invisible, and the scaling seems to be off too, making it very hard to use and even see the text.
I've noticed this is present on The Eye of GNOME and GNOME Videos
When starting Eye of GNOME (via. `eog`), the following error is present:

```(eog:13987): Gtk-WARNING **: 20:08:34.806: Theme parsing error: gtk-dark.css:1:68: Failed to import: The resource at “/com/ubuntu/themes/Yaru/3.20/gtk-dark.css” does not exist```

Notice the missing title bar and menu background:
![yaru](https://user-images.githubusercontent.com/33733427/73782826-9ccd9880-478a-11ea-8fc9-e9a7b6093986.png)

## Steps to Reproduce the Problem

  1. Open an image or video with either app
  2. Notice the missing graphics

## Software that presents the issue

- Name: Eye of GNOME
- Version: 3.34.1

## Yaru version
 - 19.10.5-317-g21f8b266

**Comment by clobrano** [comment]
If you installed from sources, please delete first the Yaru folders from /usr/share/themes and then reinstall

**Comment by Dragon8oy** [comment]
Yeah, that sorted the issue. Is that written in the build instructions or not? Might be a good idea, unless I totally missed it if it is, because anyone building on Ubuntu would run into this issue.

**Comment by clobrano** [comment]
It's not always needed. We renewed the project structure lately, so it was necessary only this time

**Comment by clobrano** [comment]
Btw, looking at the closed issue you should find some duplicates already, e.g. #1818

**Comment by Dragon8oy** [comment]
Sorry about that then, I didn't notice the duplicate. Thanks.
