### ISSUE TITLE
Use updated color palette for emblems

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1858]
As mentioned by @ubuntujaggers emblems should use colors from the updated palette.

**Comment by Muqtxdir** [comment]
hi, 

so I changed a couple of emblem colors to match the pallete colors
### Screenshots:
- **emblem-list-add** (before and after) 

![add](https://user-images.githubusercontent.com/54065734/96118108-ad810180-0f08-11eb-8440-d512bbb842af.png)

- **emblem-default** (before and after)

![default](https://user-images.githubusercontent.com/54065734/96118314-f20c9d00-0f08-11eb-81d3-697121f1bd9b.png)

- **emblem-shared** (before and after)

![share](https://user-images.githubusercontent.com/54065734/96118506-39932900-0f09-11eb-9c2d-e09a15376113.png)

- **emblem-symbolic-link** (before and after)

![symbolic](https://user-images.githubusercontent.com/54065734/96118820-af979000-0f09-11eb-8a7c-41595a5ebe73.png)

- **emblem-unreadable** (before and after)

![close](https://user-images.githubusercontent.com/54065734/96118971-ea012d00-0f09-11eb-92ba-369aaeeb5cec.png)

- **emblem-danger** (before and after)

![danger](https://user-images.githubusercontent.com/54065734/96119140-2765ba80-0f0a-11eb-9ddd-4ff692f524dd.png)

should I also do for photos and video emblem @madsrh ?

thanks!

**Comment by madsrh** [comment]
Thank you so much @Muqtxdir 🎉 Wow, what a difference actually.

> should I also do for photos and video emblem

Would be great if all of them matched.
