### ISSUE TITLE
GDM LogOn and LockScreen switch between dark and light?

### ISSUE THREAD

**Issue by mdragossh** [ubuntu/yaru#1861]
## Actual Behavior
Shell Theme is Yaru-dark
is there a way to switch GDM use shell Yaru-dark on LockScreen and LogOn Screen?

![1](https://user-images.githubusercontent.com/46487312/73931863-c0efbd80-48e1-11ea-93a9-964392ac227c.png)

Lockscreen or logon Screen
![2](https://user-images.githubusercontent.com/46487312/73931888-ce0cac80-48e1-11ea-8cf0-879fb5373891.png)

Thanks!

**Comment by madsrh** [comment]
Hi @mdragossh. Sadly no. Here's a quote from [a blogpost](https://ubuntu.com/blog/new-ubuntu-theme-in-development-for-20-04) by Ubuntu.com

> ...In future, we would also like these settings to switch the theme for shell elements, such as the top bar and notification bubbles. Achieving this without requiring a logout each time will require additional work in GNOME Shell – something we are investigating.

**Comment by mdragossh** [comment]
Thanks for answer.
