### ISSUE TITLE
Google Chrome password saving is unreadable

### ISSUE THREAD

**Issue by mdragossh** [ubuntu/yaru#1862]
## Expected Behavior

To be more readable when saving passwords
The problem is in **Google Chrome**?

## Actual Behavior
![1](https://user-images.githubusercontent.com/46487312/73932848-d7971400-48e3-11ea-952a-2bfd9e2de941.png)

## Steps to Reproduce the Problem

  1. Saving password in chrome while login

## Software that presents the issue

- Name: Google Chrome 
- Version: 80.0.3987.87

## Yaru version
```bash
$ git describe 
19.10.5-325-g9c5f466d
```

Thanks!

**Comment by clobrano** [comment]
> The problem is in Google Chrome?

Very likely, it seems that Chrome is not picking the right colors from Yaru. Is it Yaru-dark here?

**Comment by mdragossh** [comment]
> > The problem is in Google Chrome?
> 
> Very likely, it seems that Chrome is not picking the right colors from Yaru. Is it Yaru-dark here?

Yes, is Yaru-dark
![3](https://user-images.githubusercontent.com/46487312/73952708-f7d8ca00-4907-11ea-8a97-5be8106d3a7a.png)

**Comment by Feichtmeier** [comment]
@mdragossh is it also happening with Adwaita dark?

**Comment by mdragossh** [comment]
> @mdragossh is it also happening with Adwaita dark?

yes the same problem, I already reported it. 

![Screenshot from 2020-02-06 21-02-22](https://user-images.githubusercontent.com/46487312/73969391-0208c180-4924-11ea-8b7f-20ed07f819a8.png)

**Comment by madsrh** [comment]
Thanks @mdragossh  👍 Could you link to the upstream bug?

I'll close this issue here because we can't fix it here. Thank you for reporting.

**Comment by mdragossh** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=914974
