### ISSUE TITLE
gnome-terminal in Ubuntu 20.04: installing yaru from source breaks context menu

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1863]
This might not be due to Yaru, but I prefer to write it here for anyone that encounters the same problem

Soon after installing Yaru from source in 20.04, terminal context menu breaks

![image](https://user-images.githubusercontent.com/2883614/73957284-703e8b80-4906-11ea-89f0-568feaaa7843.png)

re-starting gnome-terminal fixes the problem.

**Comment by Feichtmeier** [comment]
Could you still see this issue in a recent master? @clobrano

**Comment by clobrano** [comment]
I broke my VM, I'll reinstall and double check

**Comment by clobrano** [comment]
can't reproduce it anymore, closing it
