### ISSUE TITLE
Crooked wheel tooth on settings-app-symbolic.svg

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1865]
## Expected Behavior

![Capture d’écran du 2020-02-07 18-08-32](https://user-images.githubusercontent.com/36476595/74049657-e14c7480-49d4-11ea-9568-f3949eb4b798.png)

## Actual Behavior

The highest tooth is crooked

![Capture d’écran du 2020-02-07 18-08-16](https://user-images.githubusercontent.com/36476595/74049678-ef01fa00-49d4-11ea-93bc-a279b2f3d456.png)

**Comment by ubuntujaggers** [comment]
Looks like a snapping error, will add to the list.
