### ISSUE TITLE
Gtk3: color picker button stretches the headerbar

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1878]
Prbly because it misses the button padding metrics from the top of common :| 
Yeah as I said you can put EVERYTHING in the headerbar. And gtk app devs just look for the default paddings of adwaita and apply this

![image](https://user-images.githubusercontent.com/15329494/74100456-6c418200-4b2f-11ea-9c1c-4888e7eac7d9.png)

Clicking on the list opens this stack ->

![image](https://user-images.githubusercontent.com/15329494/74100452-6350b080-4b2f-11ea-9792-4c46422f7172.png)

![Peek 2020-02-09 12-06](https://user-images.githubusercontent.com/15329494/74100952-afeaba80-4b34-11ea-89c3-ccac181588ea.gif)

**Comment by madsrh** [comment]
Isn't it supposed to look like that? :thinking:

**Comment by clobrano** [comment]
Do you mean the option button is thinner?

**Comment by Feichtmeier** [comment]
![Peek 2020-02-09 12-06](https://user-images.githubusercontent.com/15329494/74100951-9f3a4480-4b34-11ea-9fc6-226e61502617.gif)

**Comment by madsrh** [comment]
Ahhhhh sorry, I missed that in the screenshots but it's easy to see in the gif. I thought you meant that the button was a rectangle aka stretched in the headerbar 🤦‍♂ (too early for me 😄 )

**Comment by Feichtmeier** [comment]
Note: it turned out that this is actually an upstream inconsistency since the min height is not set, should fix this upstream
