### ISSUE TITLE
Gtk3: $window_radius is not used for the headerbar

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1880]
The window radius is defined here:
https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_common.scss#L11

And used here correctly for the window:
https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_common.scss#L4553

However! They are not used fot the headbars here
https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_common.scss#L1849-L1856

This results in a suuuuper thin background shining through for our theme:
![image](https://user-images.githubusercontent.com/15329494/74101178-4ae49400-4b37-11ea-935d-1fa17dc39e47.png)

It can be fixed by using 1px less than the window (because there is a 1px box shadow as the "window border"):
![image](https://user-images.githubusercontent.com/15329494/74101221-cb0af980-4b37-11ea-984d-c3fd54ff16e6.png)

**Comment by Feichtmeier** [comment]
I am not so sure about this anymore. It is a semi transparent border like it should be. And the background leak is only noticeable on bright backgrounds when using the dark theme. 
After we've darkened the dark theme border,which also changed the dark theme window border, I really have hard times to reproduce the issue:
![Bildschirmfoto von 2020-03-10 12-00-03](https://user-images.githubusercontent.com/15329494/76306211-c9635b80-62c6-11ea-8010-fdc3a0c4bbdf.png)

@clobrano are you okay with closing this?

**Comment by clobrano** [comment]
Considering how hard is it to spot it right, now (in the picture above seems everything find), we can close this
