### ISSUE TITLE
Missing mimetype for meson icons

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1885]
Could any of these ideas work @Feichtmeier @clobrano @ubuntujaggers ?

![image](https://user-images.githubusercontent.com/3986894/74107745-784f3300-4b73-11ea-82a4-576ac60c2edf.png)

**Comment by clobrano** [comment]
Number 2 for me, it seems more in line with the other mime types

**Comment by real-amano** [comment]
Maybe the icon is still a bit loud with that dark solid logo.

**Comment by madsrh** [comment]
> ...it seems more in line with the other mime types

Well, we do actually have a lot of icons with colored backgrounds, but I do agree that the white background fits better here. 

> the icon is still a bit loud with that dark solid logo.

This might be because I used the official meson color rather than a color from the suru color palette like below: 

![image](https://user-images.githubusercontent.com/3986894/74112169-9b410d80-4b9a-11ea-8cb7-7193d87bbff4.png)

I'll update the PR with white version here

**Comment by meetdilip** [comment]
All 4 are good.  Not just good, looks brilliant.
