### ISSUE TITLE
Files (Nautilus) icon looks out of place in version 29.179

### ISSUE THREAD

**Issue by fcole90** [ubuntu/yaru#1891]
Hi, I think that with the update 29.179 which has the Nautilus icon looking like its original Suru style, it looks very out of place, and a step behind compared to the previous version. At first I thought the wrong version had been linked by accident.

What happened?
Nautilus (Files) icon looks out of place and in a different style from the others.

![Screenshot from 2020-02-09 21-34-12_nautilus](https://user-images.githubusercontent.com/1292230/74131520-277c2080-4bed-11ea-814d-d64860f5e197.png)

What did I expect?
To have the same icon as previous versions, or at most a slight update in the same style.

![Screenshot from 2020-02-09 21-34-12_nautilus_previous](https://user-images.githubusercontent.com/1292230/74131533-2cd96b00-4bed-11ea-9fdf-757ceffb2260.png)

Version:
```
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: yesterday at 21:38 EET
channels:
  stable:    0.1    2019-03-13 (1768) 16MB -
  candidate: ↑                             
  beta:      ↑                             
  edge:      29.179 2020-01-16 (1949) 18MB -
installed:   29.179            (1949) 18MB
```

**Comment by clobrano** [comment]
Hey @fcole90, 

you might find informative #1755, where we discussed this move

**Comment by fcole90** [comment]
I think the cabinet looks more distinctive and also it would be in line with both the current Gnome design and the former Ubuntu style

![image](https://user-images.githubusercontent.com/1292230/74132772-de799b80-4bef-11ea-9b2e-ef415f08ac5f.png)

![image](https://user-images.githubusercontent.com/1292230/74132801-edf8e480-4bef-11ea-8321-d0339016ca66.png)

I can also understand your concerns that it looks too much detailed and less origami than the others, but I would rather suggest iterating on the cabinet than having just the old folder.

Also, if you really prefer a folder design, I think that indeed it should not _just_ be the former icon. It feels very out of place with the current restyle of the other icons. Perhaps just the folder icon (as was proposed) but with some distinctive colour or symbol could work.

In summary, while I'm more in favour of the cabinet, a folder design would be fine but just not the Suru one. 

Extra - Icons from other desktop OS:
![image](https://user-images.githubusercontent.com/1292230/74133192-b179b880-4bf0-11ea-8195-04361d3dde32.png)
![image](https://user-images.githubusercontent.com/1292230/74133281-ec7bec00-4bf0-11ea-9bf8-9c062a305b84.png)
![image](https://user-images.githubusercontent.com/1292230/74133339-0b7a7e00-4bf1-11ea-9b84-c7ab87bf9d0e.png)

**Comment by clobrano** [comment]
Closing this. Feel free to comment on #1755, the people who replied there will be notified even if the ticket is closed

**Comment by fcole90** [comment]
Sorry, I don't think to be a collaborator, but not problem, I could comment at least once :blush: :+1:
