### ISSUE TITLE
Remove light borders from Software Center

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1906]
In the dark theme we have dark borders, except in Software Center (so does Adwaita). I know that this is by design but it makes no sense IMO. 

For a quick test, just see how much better it looks in backdrop.

Current:
![image](https://user-images.githubusercontent.com/3986894/74389230-d68f4680-4dfd-11ea-890f-6675e52461eb.png)

Backdrop:
![image](https://user-images.githubusercontent.com/3986894/74389240-dee78180-4dfd-11ea-8627-6c67e1a730a5.png)

A dirty quick mockup:
![image](https://user-images.githubusercontent.com/3986894/74389262-eeff6100-4dfd-11ea-93dd-96731f4eabfc.png)

**Comment by Feichtmeier** [comment]
I know this sounds weird but those white lines look more like an outline and not like highlights.
And for some reason I think it looks good. Because it fits to the category icons in colour and stroke thickness.
But most important because it prevents the tiles from drowning

**Comment by Feichtmeier** [comment]
![Screenshot_20200213-090554](https://user-images.githubusercontent.com/15329494/74413654-1c6cfe80-4e40-11ea-8960-58a802cbf4f6.png)

**Comment by madsrh** [comment]
> those white lines look more like an outline and not like highlights.
And for some reason I think it looks good. Because it fits to the category icons in colour and stroke thickness.
But most importantly because it prevents the tiles from drowning

BUT that could also be true with a less screaming contrast. Here is:

**Normal borders**
![image](https://user-images.githubusercontent.com/3986894/74476199-2a0a9e80-4ea9-11ea-8607-98b3a82c3ea8.png)

**Dark borders**
![image](https://user-images.githubusercontent.com/3986894/74476263-4ad2f400-4ea9-11ea-84f1-03a91ecccd67.png)

**Semi bright borders**
![image](https://user-images.githubusercontent.com/3986894/74476295-5e7e5a80-4ea9-11ea-84b7-5f711dc395ae.png)

**Comment by madsrh** [comment]
Anyway, I don't think it's changeable 😞

**Comment by clobrano** [comment]
Dark borders are ofc more in line with the rest of the theme, however I too think we can't change it with Yaru. Playing with the inspector, the target to change is

```
button.tile {
  box-shadow: none;
  border: 1px solid black;
}

flowboxchild button {
  border: 1px solid black;
  box-shadow: none;
}
```
both defined in a `gtk-style.css`, which doesn't come from us :disappointed: 

![image](https://user-images.githubusercontent.com/2883614/74751356-69e8d180-526d-11ea-8dd9-e813e8fe166a.png)

My preferred way would be to ask the maintainer to reduce the custom styling (it's basically what upstream is asking us to do :smile: though) and relies on what the theme thinks is best for this kind of widgets

**Comment by madsrh** [comment]
Alright, let's close this one here
