### ISSUE TITLE
Wrong icon for network print

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1908]
The icon for network print is missing and revert to symbolic.

In gnome-settings :

![Capture d’écran du 2020-02-13 18-54-42](https://user-images.githubusercontent.com/36476595/74463643-6b438400-4e92-11ea-80c1-9be326939563.png)

And CUPS panel :

![Capture d’écran du 2020-02-13 18-55-16](https://user-images.githubusercontent.com/36476595/74463656-73032880-4e92-11ea-8fca-8eda7c6e34ae.png)

By the way emblems wrong too (issue ?).

**Comment by Jupiter007-43** [comment]
An icon proposal :

![Capture d’écran du 2020-02-13 19-03-35](https://user-images.githubusercontent.com/36476595/74464311-99759380-4e93-11ea-9b8f-df539654efcd.png)

**Comment by Feichtmeier** [comment]
Gief this icon now plz
Really, neat icon. PR plz

**Comment by friendlyapple** [comment]
Great! You can maybe use the same colors as on this icon:
<img width="321" alt="folder-sharing" src="https://user-images.githubusercontent.com/59767069/74514497-fc574100-4f0c-11ea-817c-f174d59de5d1.png">

**Comment by Jupiter007-43** [comment]
@friendlyapple In fact... I copied the cable from the folder-remote icon !

**Comment by gusbemacbe** [comment]
@friendlyapple and @Jupiter007-43 

Do your icons contain clip and mask?

**Comment by Jupiter007-43** [comment]
@gusbemacbe Yes it contain some </clipPath>. Why ?

**Comment by gusbemacbe** [comment]
Ah, because #1889.

**Comment by Jupiter007-43** [comment]
Ok, but I doesn't remove them because printer.svg, which is based on, has too.

**Comment by ubuntujaggers** [comment]
The branch for the lighter folders actually has a change to the greys on the network cable element... the original grey + purple folders still had the old warmer greys as an oversight, I've corrected that in the latest branch.

**Comment by Jupiter007-43** [comment]
Off topic, but where can I report that :

![Capture d’écran du 2020-02-14 19-13-52](https://user-images.githubusercontent.com/36476595/74556425-52080980-4f5e-11ea-8224-e90b9d035852.png)

Gnome-settings or Gtk gitlab?

**Comment by clobrano** [comment]
I'll try first the repository of the app

**Comment by Jupiter007-43** [comment]
Ok, thanks!
