### ISSUE TITLE
[Improvement] Wrong folder colour and Audaciou's icons are not in pure Yaru style

### ISSUE THREAD

**Issue by gusbemacbe** [ubuntu/yaru#1912]
## Actual Behaviour

![image](https://lh3.googleusercontent.com/-eQs6C0m4LGo/XkWd8aL12iI/AAAAAAAASXs/rwMTIjiYMjkkqaFAUl-B95o06bYEpSR4wCK8BGAsYHg/s0/2020-02-13.png)

## Description

In the folder "`/icons/Suru/256×256/legacy`", the folder colour (orange) is wrong and should be like the red and grey folders. In the app Audacious, the folder icon is wrong, and the icons are not in pure Yaru style.

**Comment by clobrano** [comment]
What is the role of "legacy" icons? According to the name, it looks like something from the past, but where it is used?

**Comment by gusbemacbe** [comment]
@clobrano 

Look at the app Audacious. It uses the legacy folder icon. Audacious is not old or outdated. It is updated. The latest stable is in December 2018 and its latest nightly release is in December 2019.

**Comment by clobrano** [comment]
I wonder what is the need to use the legacy folder

**Comment by gusbemacbe** [comment]
I am not developer of Audacious, then I can not say why. 

But in my opinion, using different folder colour in an app while the system uses another folder colour sounds strange for an user. I did not report it. It is the Italian guy who reported it. He found it strange. 

If you want to keep that folder colour in the legacy folder just because it is a legacy icon, I understand and will explain to the Italian guy.

**Comment by Feichtmeier** [comment]
Oh that icon is used in inkscape for example. It is indeed wrong!

**Comment by gusbemacbe** [comment]
@Feichtmeier, ah, I understood, I closed the issue because I thought Carlo does not want to change icons, and wants to keep the old icons.

**Comment by friendlyapple** [comment]
@gusbemacbe I already asked the question on this icon :)

https://github.com/ubuntu/yaru/issues/1797#issuecomment-579267931

**Comment by clobrano** [comment]
> @Feichtmeier, ah, I understood, I closed the issue because I thought Carlo does not want to change icons, and wants to keep the old icons.

No sorry, I was just wondering about the meaning of the "legacy" section.

**Comment by gusbemacbe** [comment]
@clobrano, @Feichtmeier and @friendlyapple 

Reported from the Italian guy, not only Audacious and Inkscape, other apps also use the legacy icons, including the orange folder icon. Observe that you developed a new icon for Transmission, then you also should change the folder icon and other old icons:

- Transmission:

![transmission](https://user-images.githubusercontent.com/2257024/74523085-3b7c9680-4efb-11ea-82b5-cb1e4eb66477.png)

- Puddletag, compare the orange folder (left top) to the different folder icons (left bottom):

![puddletag](https://user-images.githubusercontent.com/2257024/74523188-66ff8100-4efb-11ea-96db-cfaaf8c9f630.png)

**Comment by madsrh** [comment]
Thanks @gusbemacbe 👍 

A general icon question: Is there a way to tell where an icon is used? (sorry for the lightly off topic comment)

**Comment by gusbemacbe** [comment]
@madsrh 

- Transmission
   - Go to the line 167: https://github.com/transmission/transmission/blob/master/qt/MainWindow.cc
    - https://github.com/transmission/transmission/blob/master/qt/icons/Faenza/Faenza.qrc

**Comment by gusbemacbe** [comment]
@madsrh 

The post you pinged me is locked and limited to collaborators, then I can not answer there. I have to answer here.

**Comment by gusbemacbe** [comment]
@madsrh 

> Suru++ uses the symbolic icon which look great but that the downsides that it's monochrome and that it isn't visible in the dark theme.

Which Suru++? @Bonandry's Suru++ Ubuntu is totally outdated and buggy. 

My Suru++ is not updated for months because I was too dedicated to two projects Adwaita++ and Yaru++ @Bonandry broke 8 months ago. I took 6 months to repair, correct and redesign Adwaita++, having to redesign actions, apps and status icons, and purging the impure icons copied from Suru++ Ubuntu. I have already forbidden @Bonandry of copying and mixing Suru++ Ubuntu, overwriting Adwaita++ and Yaru++.

Adwaita++ is totally fixed, ready and upgraded last month. At the moment, I am repairing Yaru++ in my branch `gusbemacbe`. 

You may try to test with the upgraded Adwaita++ and the unstable branch `gusbemacbe`'s Yaru++ to see if the symbolic icons work on both dark and light environments.

**Comment by madsrh** [comment]
Hi @gusbemacbe 

I've had a look at the **Yaru++** branch and WOW! You've done a huge amount of awesome work 🎉  - I'm very impressed 🥇 
We're missing a lot of the stuff you have and to be honest, I'm a bit sad that all that awesome work is only found downstream in Yaru++ and not here in Yaru 😥 We really could use your talent here, but I understand that you're buried in work with all your other projects, and fixing issues here would be double the work. Anyway, we're happy that you drop by occasionally 😃 

And thanks for the explanation above!

[I've made a PR](https://github.com/ubuntu/yaru/pull/1934) that fixes this issue 😉

**Comment by gusbemacbe** [comment]
> I've had a look at the **Yaru++** branch and WOW! You've done a huge amount of awesome work tada - I'm very impressed

Thank you!



> We're missing a lot of the stuff you have and to be honest, I'm a bit sad that all that awesome work is only found downstream in Yaru++ and not here in Yaru disappointed_relieved. 

As @Bonandry's projects are under GPL licence, you can copy from them to your project, but the problem is that you use PNG. 

I have talked with @Bonandry, he said that 16px legacy icons do not seem good. And he said he would like his Yaru++ project be credited in your project because some of your icons are inspired by his project. 

>  We really could use your talent here, but I understand that you're buried in work with all your other projects, and fixing issues here would be double the work. Anyway, we're happy that you drop by occasionally smiley

I am finishing the Yaru++ project. Then I can work a bit with your project.

**Comment by Feichtmeier** [comment]
We would be mostly interested in the symlink lists
The icons not so much

**Comment by madsrh** [comment]
> Yaru++ project be credited in your project because some of your icons are inspired by his project.

Yes, sorry about that. We really need to update Authors and credit files! Also, we're [already borrowing](https://github.com/ubuntu/yaru/pull/1931) from all the great work you guys are doing!

> I am finishing the Yaru++ project. Then I can work a bit with your project.

THAT would be much welcome ❤️ 🎉 
We have User Interface Freeze on March 19 for the LTS release, so if you find anything critical please let us know!

> The icons ... Maybe some of them :)

@Feichtmeier I think gusbemacbe knows that we're not using monochrome icons or thirdparty apps 😉

**Comment by Feichtmeier** [comment]
@gusbemacbe we would need help with the full colour legacy icons (used in old gtk3 and gtk2 apps) and symlinkd. That'd be really really nice.

**Comment by ubuntujaggers** [comment]
> And he said he would like his Yaru++ project be credited in your project because some of your icons are inspired by his project.

Which ones...?

**Comment by Amr-Ibra** [comment]
> What is the role of "legacy" icons? According to the name, it looks like something from the past, but where it is used?

Legacy icons are needed primarily for Qt apps (see https://github.com/ubuntu/yaru/issues/1621 and https://github.com/ubuntu/yaru/issues/1294 for history), and as a side effect they are also picked up by GTK2 and GTK3 apps, which don't use symbolic icons, just because of the icon naming. They are not "strictly" needed there, as Humanity icons are sufficient for them.
They are placed in a "legacy" folder because that's what upstream Adwaita is doing with full-colour icons.

**Comment by clobrano** [comment]
Great explaination, thanks a lot
