### ISSUE TITLE
build: porting all python scripts to python3

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#1917]
While working on #1896 I noticed that some python scripts are still based on python2, whose support ended in January 2020

**Comment by Feichtmeier** [comment]
@clobrano are there any python2 scripts left? I remember that you converted two scripts

**Comment by clobrano** [comment]
No, we're free from such plague. Closing this 🙏

**Comment by Feichtmeier** [comment]
@clobrano thank you :)
