### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by paledega** [ubuntu/yaru#1923]
![Screenshot_2020-02-15_12-20-46](https://user-images.githubusercontent.com/38860643/74587664-9ee6f100-4fed-11ea-9c23-b5308612b6fe.png)

Source adress: https://github.com/ubuntu/yaru/archive/20.04.1.zip

**Comment by clobrano** [comment]
Hey @paledega, could you be a little more descriptive? :sweat_smile: 
In the issue template there are some hints, for example which Yaru version are you building.

I see that you are not using the suggested build command `meson build`, is there a reason to use all those flags instead?

**Comment by paledega** [comment]
meson build use build directory.
I am using inary builder so I must use inaryPackageBuild directory.


also I tried with meson.build but same issue

**Comment by paledega** [comment]
```shell
git clone https://github.com/ubuntu/yaru --depth=1
cd yaru
mkdir build ; meson build
cd build ; ninja
su 
ninja install
```

working now hmm

**Comment by paledega** [comment]
How can I install yaru in custom location?

**Comment by clobrano** [comment]
This might help https://mesonbuild.com/Installing.html#destdir-support
