### ISSUE TITLE
Wrong use of window-close

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1925]
Nitpicking incoming 😄 
The `window-close` icon doesn't really fit on buttons, where one expects to only see an X.
Perhpas we should just use symbolic icon so it also adapts to light/dark theme as seen in Adwaita and Yaru++

Also, the red color isn't same as the window decorations, which might seem odd. Very low priority, but something to look into later.

![image](https://user-images.githubusercontent.com/3986894/74604114-29495680-50bb-11ea-9a9b-f67019232ee9.png)

Adwaita
![image](https://user-images.githubusercontent.com/3986894/74604081-d8d1f900-50ba-11ea-9842-8c0155b3170c.png)

Yaru++
![image](https://user-images.githubusercontent.com/3986894/74604094-fc953f00-50ba-11ea-929f-8bc4b1d06e62.png)

**Comment by clobrano** [comment]
Which app is that?

**Comment by madsrh** [comment]
Evolution 📫

**Comment by clobrano** [comment]
Looking rapidly, it seems to be our `icon/src/fullcolor/actions/window-close.svg` icon

![image](https://user-images.githubusercontent.com/2883614/74608914-80642100-50e5-11ea-882f-f22a0a2c4293.png)

**Comment by madsrh** [comment]
This is Adwaita:
![image](https://user-images.githubusercontent.com/3986894/74609106-0f256d80-50e7-11ea-96fe-a665d3b894f9.png)

Yaru++:
![image](https://user-images.githubusercontent.com/3986894/74609118-282e1e80-50e7-11ea-85a1-511721fb0693.png)

**Comment by clobrano** [comment]
I like something like Yaru++, we just need to double check if other places are still using the current window-close

**Comment by Feichtmeier** [comment]
Guys I think this icon is perfectly fine! 
It's used in old gtk apps for several things and we have symlinks to it
![image](https://user-images.githubusercontent.com/15329494/75925966-e8e32a00-5e69-11ea-9f61-deb6e715f2e4.png)

/voteforclose :laughing:

**Comment by madsrh** [comment]
You're right, it's not critical, but if it's just a matter of borrowing the `window-close.svg` from Yaru++, then I would prefer this look:

![image](https://user-images.githubusercontent.com/3986894/75926443-db7a6f80-5e6a-11ea-92c8-b5d670e0a839.png)

**Comment by Feichtmeier** [comment]
But that's a faked symbolic icon which only works in this picture :) Full color icons should not be replaced by faked symbolics

**Comment by madsrh** [comment]
🤦‍♂ ofc not 😄
