### ISSUE TITLE
Full color headset icon is missing

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1930]
![image](https://user-images.githubusercontent.com/15329494/74609263-cb336800-50e8-11ea-9823-fd427220493b.png)

**Comment by madsrh** [comment]
Could you post a screenshot with the Adwaita icon theme? (If you have it handy)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/74609462-6973fd80-50ea-11ea-914d-860065f85c2c.png)

:rofl:

**Comment by madsrh** [comment]
I've tried and failed. I cannot draw this 🎧 Hopefully Stuart will have better luck 👼 

There's two types:
![image](https://user-images.githubusercontent.com/3986894/74614587-5298cf80-5119-11ea-9156-fa69cdf9fcd9.png)

**Comment by meetdilip** [comment]
This is fine ?

![headset with mic](https://user-images.githubusercontent.com/6965443/74621389-d62ade80-5162-11ea-9313-ca9c8464fe88.png)

**Comment by meetdilip** [comment]
I tried a gradient version

![headset with mic gradient](https://user-images.githubusercontent.com/6965443/74624603-1abc7700-516f-11ea-89a5-15cb85ce581b.png)

**Comment by meetdilip** [comment]
A mockup

![mockup headset blue](https://user-images.githubusercontent.com/6965443/74630649-05e8df00-5181-11ea-8b94-6c0d55e5a211.png)

I thought since Aubergine is used in plenty, trying it on the headset would go fine as well

![mockup headset aubergine](https://user-images.githubusercontent.com/6965443/74630703-2c0e7f00-5181-11ea-9f0d-d3ceac20b043.png)

**Comment by meetdilip** [comment]
I made the gradient version of aubergine. Thought I would add that too

![mockup aubergine gradient](https://user-images.githubusercontent.com/6965443/74672324-090cbb00-51d3-11ea-812f-e7674ceb3f31.png)

**Comment by madsrh** [comment]
Nice work @meetdilip 😃 Much better than anything I could have drawn. I think it may need a bit more Yaru styling to fit with the other device icons. If you could post this as a PR then Stuart could tweak it.

**Comment by meetdilip** [comment]
Thanks @madsrh Still not confident about PR. Do you mind if I attach the file here ?

[audio headset  with mic 3x 64.zip](https://github.com/ubuntu/yaru/files/4217111/audio.headset.with.mic.3x.64.zip)

**Comment by Feichtmeier** [comment]
@meetdilip thanks for the inspiration, much appreciated! 👍 
Let's see what @ubuntujaggers can draw with this inspiration :)
