### ISSUE TITLE
Indeterminate checkbox is visually inconsistent with checked checkbox

### ISSUE THREAD

**Issue by fitojb** [ubuntu/yaru#1933]
The indeterminate icon is too “fat” with respect to the checked one.

![imaxe](https://user-images.githubusercontent.com/554953/74624805-83740700-510f-11ea-946e-11e0a3936cb6.png)

**Comment by madsrh** [comment]
I have no idea how to edit this 🤔 Sorry! I would prefer if someone else could look into this.

**Comment by clobrano** [comment]
> I have no idea how to edit this thinking Sorry! I would prefer if someone else could look into this.

I self assigned this, but I'm on the same boat. Maybe @ubuntujaggers knows best

**Comment by Feichtmeier** [comment]
I can do it. It's in the asset file then export it. If you want assign me and I'll do it tonight

**Comment by Feichtmeier** [comment]
Closed by https://github.com/ubuntu/yaru/pull/1990
