### ISSUE TITLE
Snap apps icon revert to Adwaita

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1936]
## Actual Behavior

![Capture d’écran du 2020-02-18 12-24-37](https://user-images.githubusercontent.com/36476595/74732623-f2a24600-524a-11ea-9d30-fc7336ba6efe.png)

For gnome-characters icon used is /snap/gnome-characters/current/meta/gui/org.gnome.Characters.svg

Tested on master with an uptodate VM 20.04.

It doesn't concern me because I don't use snap for these apps (😋), but It's still an issue.

**Comment by Feichtmeier** [comment]
Yes this is a known issue. I think @jhenstridge landed a big bunch of code for this somewhere in snap land - I am not sure about the current status though. I'll close this here because we can not do anything about this, this is a snap issue. Thanks for the report

**Comment by Jupiter007-43** [comment]
If the problem is already known then everything is fine. 👍
