### ISSUE TITLE
Tweak indeterminate progress bars

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1937]
Try to reduce the "bouncing" effect of indeterminate progress bars by bring background and active background closer together.

**Concept:** (open in a new tab)
![Vertical wave](https://user-images.githubusercontent.com/15329494/72054364-204db400-32c9-11ea-9683-2d5c51c154e0.gif)

**Comment by Feichtmeier** [comment]
Outside of the widget factory  - has anyone every seen this?

**Comment by madsrh** [comment]
Not sure 🤔 Perhaps in the updater when it's searching for updates, but I'm not sure.

**Comment by clobrano** [comment]
I did, but don't remember where

**Comment by clobrano** [comment]
i'm not sure this is doable on css side

**Comment by Feichtmeier** [comment]
You need to change it here: https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/assets.svg
Then run this: https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/render-assets.sh
I think :)

**Comment by clobrano** [comment]
This progress bar is not an asset, unless I misunderstood something, it's made with css

**Comment by Feichtmeier** [comment]
Oh wrong issue! lol

**Comment by Feichtmeier** [comment]
@matthewpaulthomas 

I personally do not think that this is a good idea.
This widget shows up in a very important application, the software-updater:
![Peek 2020-02-23 15-10](https://user-images.githubusercontent.com/15329494/75113485-b60d8a80-564e-11ea-8353-aadb941ed51b.gif)

It switches from the indeterminate state to a normal progress bar.
Somehow adapting to the GIF you've send us would mean that the indeterminate progress bar would look very different from a normal progressbar. 

If you and @madsrh @clobrano agree here, I would personally prefer to not change this behaviour.

**Comment by matthewpaulthomas** [comment]
Sorry for the confusion. That GIF is something I made in about ten minutes. I did not mean at all for it to be used as the actual design! For one thing, it uses hard-coded colours, when the actual design should use theme colours.

I provided it simply so that you could test whether, in GTK, a background GIF _could_ be used as a method of animating indeterminate progress bars without hacking GTK itself. Themed background colour + animated semi-transparent background image + invisibly-transparent bouncer.

If it turns out to be feasible, the next step would be to try different designs for the indeterminate state, to find one that looks classy, distinct from, but related to, the determinate state.

**Comment by Feichtmeier** [comment]
Looking into the code for some time, it turns out there is no style class or pseudo class for indeterminate progressbars/scales.
I fear this is a "can't fix" @matthewpaulthomas

**Comment by Feichtmeier** [comment]
There is one for the "pulse", the part that moves, but not for the background

**Comment by matthewpaulthomas** [comment]
Is it possible to use CSS to override the width of the “pulse”? If so, maybe you could force it to be 100% all the time, then style that instead?

Alternatively, does GTK have any equivalent of [the `:has()` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)? If it does, you could use something like `.progressbar:has(>.pulse)` to change the progress bar background whenever there is a `.pulse` inside it. (And then make the pulse itself invisible.)

**Comment by Feichtmeier** [comment]
I will try.
I am still not a fan of the idea to change this widget at all but I'll try :)

**Comment by Feichtmeier** [comment]
Okay, you change the min-width of it, but you don't know how long the progress bar is. They can be X long so you don't know how to set the min-width.
Bouncing indeterminate progress bars seem also very common to me (which does not imply that this is the best design ofc). 
How about proposing a different design for gtk4?
I think changes here needed are so deep that CSS won't help

**Comment by matthewpaulthomas** [comment]
What happens if you set `{min-width: 100%}`?

**Comment by Feichtmeier** [comment]
Need to check this @matthewpaulthomas 
Sorry for not answering for so long

**Comment by Feichtmeier** [comment]
Didn't manage to set the min-width for the whole widget. I'm sorry but this looks like a unfixable. Maybe you can try on the gtk upstream repo @matthewpaulthomas
