### ISSUE TITLE
Icon for Software Properties, aka Software & Updates, doesn't relate to the app

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1940]
I've started my spring clean with the new templates and was reminded that the Software Properties icon is a bit unsatisfactory ("A" on a globe).

I wonder what you think of this concept: a similar icon to the Software Updater (because they're related apps) but with one of the new Yaru checkboxes to signify settings (and also because the app in question is full of them):

![image](https://user-images.githubusercontent.com/38893390/74773365-a4f8fe00-5289-11ea-9332-b8321a04be51.png)

![image](https://user-images.githubusercontent.com/38893390/74773389-b0e4c000-5289-11ea-9a5b-baf8af2438eb.png)

**Comment by madsrh** [comment]
I see what you're doing 😃 

Remember to change the progress bar too ;)

![image](https://user-images.githubusercontent.com/3986894/74775810-bd234a00-5296-11ea-8ad2-c1f50c31f6e3.png)

This just fun, but did you ever get this thought 😆 
![image](https://user-images.githubusercontent.com/3986894/74776126-518dac80-5297-11ea-98f9-5ed125b00b11.png)

**Comment by Feichtmeier** [comment]
Nice idea! 
And nice idea by mads. I like his purple circle a with a checkmark

**Comment by ubuntujaggers** [comment]
I'm very open to purple, I tried it first but wondered if it was too much! Let me have a go again...

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/74781445-666b3f80-5299-11ea-8dfc-904ab37282b9.png)

![image](https://user-images.githubusercontent.com/38893390/74781324-31f78380-5299-11ea-9ede-b2d925fbc1b9.png)

?

**Comment by ubuntujaggers** [comment]
Maybe needs to be darker...

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/74782064-aed72d00-529a-11ea-9675-b4310afe582a.png)

![image](https://user-images.githubusercontent.com/38893390/74782076-b7c7fe80-529a-11ea-9d9d-be5f7f17afd7.png)

^^ It's not this saturated, it's just the compression on Github.

**Comment by madsrh** [comment]
Is it because you want it to stand out from the checkbox? How about a dark aubergine? It is a bit insisting atm

**Comment by ubuntujaggers** [comment]
Yeah, let's just use the checkbox aubergine for the backplate too, as per your mockup:

![image](https://user-images.githubusercontent.com/38893390/74783689-193d9c80-529e-11ea-9bf4-b9e1ffa8e9b0.png)

![image](https://user-images.githubusercontent.com/38893390/74783737-33777a80-529e-11ea-9732-67e2ddb85660.png)

If you guys are happy with that, so am I :+1:

**Comment by madsrh** [comment]
> let's just use the checkbox aubergine

Could you just try the really dark aubergine?

**Comment by Feichtmeier** [comment]
I would just remove the background of the checkbox :D

**Comment by ubuntujaggers** [comment]
> > let's just use the checkbox aubergine
> 
> Could you just try the really dark aubergine? It might fit better with the gray icon next to it

Dark Aubergine:

![image](https://user-images.githubusercontent.com/38893390/74785538-74718e00-52a2-11ea-9b7d-6e3ef0b1174d.png)

Medium Aubergine:

![image](https://user-images.githubusercontent.com/38893390/74785382-1f357c80-52a2-11ea-8091-6d54c684eb6f.png)

The dark one looks nice in this screenshot but is possibly too dark in reality.

**Comment by ubuntujaggers** [comment]
If we're happy with this basic concept, we can choose a final aubergine and box versus non-box when we're trying the PR...  the screenshots look more PURPLE!!!! because of the compression.

**Comment by meetdilip** [comment]
> with one of the new Yaru checkboxes to signify settings (and also because the app in question is full of them):

While the check box looks interesing, won't a great icon be more indicative ?

**Comment by meetdilip** [comment]
I am not sure how pleasing this would be. Trying to convey the idea

![mockup 2x](https://user-images.githubusercontent.com/6965443/74809467-3b253680-5313-11ea-9d9b-07a70580a148.png)

It is better when you have a non-white background

![mockup 2x bg](https://user-images.githubusercontent.com/6965443/74809498-4c6e4300-5313-11ea-9b5b-9b067193978c.png)

**Comment by clobrano** [comment]
I really like these mockups :smile:. Probably I like more the one without checkmark, because it makes the design a little uneven :sweat_smile:, but it's a minor problem.

@meetdilip, the gear might recall some kind of option setting and I think it's better not to use it

**Comment by meetdilip** [comment]
Thanks for the response. I want to try something better. Let's say I got into a creative block. Tick icon is nice. I was trying to accommodate the " settings " part.

**Comment by meetdilip** [comment]
Allow me to add just one more mockup

![software and udates panel](https://user-images.githubusercontent.com/6965443/74817861-a37c1400-5323-11ea-9ffa-c60884f045cd.png)
![software and udates panel plain](https://user-images.githubusercontent.com/6965443/74817862-a4ad4100-5323-11ea-97e7-37c61058d550.png)

**Comment by Feichtmeier** [comment]
Uh... that would is kinda neat. If this would be on a standard yaru baseplate 🤔 
@ubuntujaggers WDYT?

**Comment by ubuntujaggers** [comment]
Nice idea, I'll give it a go 👍

**Comment by ubuntujaggers** [comment]
First attempt:

![image](https://user-images.githubusercontent.com/38893390/74842383-3b78fe00-5322-11ea-9689-686ae5bfc292.png)

![image](https://user-images.githubusercontent.com/38893390/74842401-42a00c00-5322-11ea-8cc2-b731270cb87f.png)

I really like the 48px, not sure about the full size yet.

**Comment by meetdilip** [comment]
No chance we can replace the grey background with something more closer to white ? Nice work :+1:

**Comment by madsrh** [comment]
I prefer the colored background or the gear idea. Nothing wrong with your execution Stuart but this idea looks IMO a bit like a music player

**Comment by Feichtmeier** [comment]
There was this nice idea by eaglersdeveloper with the progressbar in the A being replaced by a gear, anyone remembers?

**Comment by ubuntujaggers** [comment]
White looks a bit anaemic IMO, and strangely like a washing machine (if we put this with the casserole dish we can branch out into Yaru kitchenware):

![washing machine 2](https://user-images.githubusercontent.com/38893390/74848361-81888e80-532f-11ea-9f29-875e4ea35eb6.png)

![washing machine 1](https://user-images.githubusercontent.com/38893390/74848366-82212500-532f-11ea-978c-4d3ba1a17916.png)

The coloured background looks great in the mockup (my favourite) but unfortunately the purple bleeds into pretty much any colour at small sizes at there's a sort of "glare" where the detail is lost  :(

By the way, I can't believe I didn't think of at least trying this, given the "progress bar" metaphor on Software Updater:

![image](https://user-images.githubusercontent.com/38893390/74848524-a977f200-532f-11ea-9c0d-63ea45095027.png)

![image](https://user-images.githubusercontent.com/38893390/74848576-b5fc4a80-532f-11ea-99c3-8afd359e04e9.png)

^^ So far my vote goes for this - it looks nice, gets round the problem with the tickbox (which isn't very recognisable when you remove the box) and nicely complements software-updater.

**Comment by clobrano** [comment]
Last one is simply brilliant :)

**Comment by meetdilip** [comment]
> There was this nice idea by eaglersdeveloper with the progressbar in the A being replaced by a gear, anyone remembers?

I was working on this. I do not recall any old sample. But had this idea of 2 gears combo for this icon. At first,  I thought not to put it here. I made a few tweaks. Let us see how it is now

![1](https://user-images.githubusercontent.com/6965443/74850868-79951280-5360-11ea-8020-6383638377d2.png)

![2](https://user-images.githubusercontent.com/6965443/74850870-7ac63f80-5360-11ea-8703-fa8444d8baaa.png)

I was trying to find a proper contrast between the gear and background. If you can improve, most welcome.

**Comment by meetdilip** [comment]
Tried mockups. Looks fine on smaller sizes

![1 mockup](https://user-images.githubusercontent.com/6965443/74851991-01c7e780-5362-11ea-8004-189c6fc71a56.png)



![2 mockup](https://user-images.githubusercontent.com/6965443/74851994-02f91480-5362-11ea-90e2-be346f2fb453.png)

**Comment by meetdilip** [comment]
I tried an online colour palette tool. And it says this is the best choice for contrast for selected colours

![gear aubergine](https://user-images.githubusercontent.com/6965443/74853417-ebbb2680-5363-11ea-885d-fa6a3ab87196.png)

**Comment by madsrh** [comment]
Not my best idea 🤷‍♂ I still prefer [this one](https://user-images.githubusercontent.com/38893390/74848524-a977f200-532f-11ea-9c0d-63ea45095027.png) by Mr. Jaggers
![image](https://user-images.githubusercontent.com/3986894/74858048-ee5a5380-5344-11ea-8920-7b5cdc52e1b8.png)

**Comment by meetdilip** [comment]
@madsrh I like the 3 slider one. Too cute.

> ![image](https://user-images.githubusercontent.com/38893390/74848576-b5fc4a80-532f-11ea-99c3-8afd359e04e9.png)
 
I like the one from @ubuntujaggers too. Very smart idea. The only downside I see is that it looks mostly like `software updater` when it comes to smaller sizes.

**Comment by meetdilip** [comment]
Looks like grey background is the best if we are doing gears. Others have poor contrast

Blue looked much better than Aubergine. This one looks better even in smaller sizes

![blue grey](https://user-images.githubusercontent.com/6965443/74898227-46ce3700-53bf-11ea-81ab-1d84acd32ae0.png)


![gear blue grey](https://user-images.githubusercontent.com/6965443/74898231-47ff6400-53bf-11ea-8522-b5eb666d39fe.png)

**Comment by Feichtmeier** [comment]
I do like this one, too.

**Comment by ubuntujaggers** [comment]
@meetdilip can you try mocking up that design using the same gear shape as settings?

**Comment by meetdilip** [comment]
>  that design using the same gear shape as settings?

Sorry, didn't follow.  Which design ?

**Comment by ubuntujaggers** [comment]
Blue gears on grey background - see if it works using the existing gear shape from the settings-app icon :)

**Comment by meetdilip** [comment]
Tried these 2

![u1](https://user-images.githubusercontent.com/6965443/74916083-3f248780-53eb-11ea-9be0-d5976d124739.png)

![u2 blue](https://user-images.githubusercontent.com/6965443/74916087-40ee4b00-53eb-11ea-8304-678e49397653.png)

Kindly let me know if you want any changes.

**Comment by meetdilip** [comment]
Settings-app gear in full

![u blue](https://user-images.githubusercontent.com/6965443/74916781-7ba4b300-53ec-11ea-841b-6d392a9c44ca.png)

**Comment by madsrh** [comment]
https://user-images.githubusercontent.com/40228953/50160897-c52ed500-02f3-11e9-919c-2579ba926dd3.png

**Comment by Feichtmeier** [comment]
Yes, if we go with the gear, I would also prefer eagl e r s develop e r s approach

**Comment by meetdilip** [comment]
Something is wrong with my Inkscape. No matter I draw, they are selectable, but invisible. :(

**Comment by madsrh** [comment]
> No matter what I draw, they are selectable but invisible. :(

Maybe you've just set the layer to 0% in opacity

![image](https://user-images.githubusercontent.com/3986894/74920304-3ec8c400-53cc-11ea-8020-5aff38f366a3.png)

**Comment by meetdilip** [comment]
Thanks @madsrh . Fill opacity somehow got to zero

![soft and updates](https://user-images.githubusercontent.com/6965443/74921256-89aa0200-53f3-11ea-8408-ae507fdc7552.png)

**Comment by meetdilip** [comment]
Aubergine looks fine here

![gear aubergine](https://user-images.githubusercontent.com/6965443/74921556-f1604d00-53f3-11ea-83a9-cc1f38d82814.png)

**Comment by meetdilip** [comment]
I went back to our old slider design. This one look ok to me

![soft panel](https://user-images.githubusercontent.com/6965443/74923718-48b3ec80-53f7-11ea-97df-ae26060b94cd.png)

**Comment by ubuntujaggers** [comment]
Closing for now because we've got a new design in Master, but all icons are always up for review :+1:
