### ISSUE TITLE
[Feature Request] xfwm and openbox theme support

### ISSUE THREAD

**Issue by paledega** [ubuntu/yaru#1942]
I am xfce user. I changed gtk theme to yaru but xfwm theme not avaiable.
also I need openbox theme need.

thanks

**Comment by paledega** [comment]
![fffff-04-41](https://user-images.githubusercontent.com/38860643/74777876-569c2d00-5292-11ea-9009-bdd48c1f0bcd.png)
not look good :(

**Comment by clobrano** [comment]
Hey @paledega, I'm Sorry but an xfce version of Yaru is probably a bit out of our scope right know, unless you are willing to work on it or can bring someone that could :)
