### ISSUE TITLE
GDM lock screen using light menus

### ISSUE THREAD

**Issue by Dragon8oy** [ubuntu/yaru#1947]
## Expected Behavior

On the login screen, the menus in the top left corner are should be a dark grey, when using yaru-dark

## Actual Behavior

On the login screen, the menus in the top left corner are white instead of dark grey, when using yaru-dark

## Steps to Reproduce the Problem

  1. Install user-themes GNOME Shell Extension
  2. Install yaru
  3. Set everything to yaru, and where possible, set it to yaru-dark in GNOME Tweak Tool under Appearance > Themes
  3. Reboot
  4. Open the drop down menus on the login screen

## Software that presents the issue

- Name: gdm3
- Version: 3.34.1

## Yaru version

 * `$ git describe`
 * `20.04.1-63-ge88c84c7`

**Comment by clobrano** [comment]
Hey @Dragon8oy, I am not sure gdm screen is affected by user themes. Can you reproduce this issue with any other theme that supports the shell?

**Comment by Dragon8oy** [comment]
Yes, I tried Cyanogen (https://www.gnome-look.org/p/1273486/) and this issue is still present. Assuming I should file an issue with user-themes?

**Comment by clobrano** [comment]
This is probably a limitation of the shell. At that point in time, it can only load the default shell, but you can ask first in user-themes repo
