### ISSUE TITLE
Missing icon for sound device

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1948]
## Actual Behavior

![Capture d’écran du 2020-02-19 19-05-57](https://user-images.githubusercontent.com/36476595/74861643-00d78b80-534b-11ea-9fe3-68279f26667f.png)

## Steps to Reproduce the Problem

  1. Open Gnome-settings
  1. Go to bluetooth
  1. Connect a sound device

Tested on 19.10, I will test on master with my 20.04 VM.

**Comment by Jupiter007-43** [comment]
Same on master.

**Comment by madsrh** [comment]
Hi @Jupiter007-43 Could you post a screenshot from Adwaita?

**Comment by meetdilip** [comment]
Is this the intended behaviour ?

![bluetooth speaker](https://user-images.githubusercontent.com/6965443/74900624-6c127380-53c6-11ea-89fd-0a8bff034883.png)

**Comment by Jupiter007-43** [comment]
@madsrh here is :

![Capture d’écran du 2020-02-20 11-02-44](https://user-images.githubusercontent.com/36476595/74923384-fcee4c80-53d0-11ea-888f-85746107bdb1.png)

@meetdilip No, just the full-color icon is missing and revert to symbolic 😉

**Comment by Jupiter007-43** [comment]
Game controller icon is also missing #1951 

Maybe look at the list of icon to see which are missing ?

**Comment by meetdilip** [comment]
https://github.com/ubuntu/yaru/blob/master/icons/Suru/48x48@2x/apps/rhythmbox.png

There is one for Rhythmbox which looks like the one in Adwaita.

**Comment by Jupiter007-43** [comment]
![Capture d’écran du 2020-02-19 19-05-572 png](https://user-images.githubusercontent.com/36476595/74933353-151b9700-53e4-11ea-85fc-d2b024a3f99c.png)

**Comment by madsrh** [comment]
Too similar to Rhythmbox IMO

**Comment by Jupiter007-43** [comment]
Yes indeed.

**Comment by Feichtmeier** [comment]
We could just use the speaker inside that icon?  I mean, just emove the baseplate

**Comment by madsrh** [comment]
> We could just use the speaker inside that icon? I mean, just emove the baseplate

The bracket / skrew holes from Adwaita are nice too. Perhaps we can borrow them too

**Comment by Jupiter007-43** [comment]
@Feichtmeier Here is 

![Capture d’écran du 2020-02-19 19-05-572 png png](https://user-images.githubusercontent.com/36476595/74969755-6e53ec80-541d-11ea-877c-c9606aa78da6.png)

🤔 It's a good starting point, but there's something missing...

@madsrh Where is the repository for this Adwaita icon? I searched and didn't find it.

**Comment by madsrh** [comment]
https://gitlab.gnome.org/GNOME/adwaita-icon-theme

**Comment by Jupiter007-43** [comment]
Maybe I've got a problem, but I can't find it... 😓

**Comment by madsrh** [comment]
> Maybe I've got a problem, but I can't find it... 😓

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/src/fullcolor/legacy/audio-speakers.svg

**Comment by meetdilip** [comment]
I got the icon to blue. But not sure where to put in the Bluetooth audio logo

![speaker](https://user-images.githubusercontent.com/6965443/75001662-04bcf800-5488-11ea-90bf-b627fe445a56.png)

![speaker bluetooth](https://user-images.githubusercontent.com/6965443/75001667-0686bb80-5488-11ea-9c96-65dd1eb8e386.png)

**Comment by meetdilip** [comment]
Mockup

![mockup 1](https://user-images.githubusercontent.com/6965443/75010884-51163100-54a4-11ea-96bc-9eb977eea1c2.png)

**Comment by Jupiter007-43** [comment]
@madsrh Thanks very much! I must be really tired.

**Comment by Jupiter007-43** [comment]
@meetdilip This icon is named audio-speakers and not audio-speakers-bluetooth so I don't think that  a  Bluetooth logo is needed.

**Comment by meetdilip** [comment]
> @meetdilip This icon is named audio-speakers and not audio-speakers-bluetooth so I don't think that a Bluetooth logo is needed.

Sure. I was banking on the title. :)

**Comment by Jupiter007-43** [comment]
![g1050-6](https://user-images.githubusercontent.com/36476595/75041571-1d93d080-54bd-11ea-9577-9508e41433c3.png)

**Comment by ubuntujaggers** [comment]
We might consider making the icon more monochrome, because I think of the yellow more as the Rhythmbox logo than a generic non-branded speaker 🤔

**Comment by Feichtmeier** [comment]
Yeah, maybe that warmish gray ```#AEA79F```

**Comment by meetdilip** [comment]
Speakers look a lot different these days

![btooth2](https://user-images.githubusercontent.com/6965443/75090278-3c5e9980-5587-11ea-80c8-74ba3d81f6ae.jpg)

![btooth1](https://user-images.githubusercontent.com/6965443/75090281-3d8fc680-5587-11ea-94f8-16b2ce7cbefb.jpg)

**Comment by madsrh** [comment]
> Speakers look a lot different these days

That's only the speaker casing. That [actual speaker unit ](https://www.google.com/search?q=speaker+unit&client=ubuntu&hs=HQ&channel=fs&sxsrf=ALeKk03TwvqkcGYbyRRZnSejhiveev8ZHw:1582366358386&tbm=isch&source=iu&ictx=1&fir=n9pqGWaPH0yNAM%253A%252CdmUBssNySr7_GM%252C_&vet=1&usg=AI4_-kQ-VTO99eRWfT6LmnUlZSbzCDintQ&sa=X&ved=2ahUKEwiursiF9uTnAhVQ3qQKHbpVAHEQ9QEwAnoECAoQCA#imgrc=n9pqGWaPH0yNAM:)looks just like that :smiley:

**Comment by meetdilip** [comment]
> That [actual speaker unit ](https://www.google.com/search?q=speaker+unit&client=ubuntu&hs=HQ&channel=fs&sxsrf=ALeKk03TwvqkcGYbyRRZnSejhiveev8ZHw:1582366358386&tbm=isch&source=iu&ictx=1&fir=n9pqGWaPH0yNAM%253A%252CdmUBssNySr7_GM%252C_&vet=1&usg=AI4_-kQ-VTO99eRWfT6LmnUlZSbzCDintQ&sa=X&ved=2ahUKEwiursiF9uTnAhVQ3qQKHbpVAHEQ9QEwAnoECAoQCA#imgrc=n9pqGWaPH0yNAM:)looks just like that

That is true. But people mostly related sound device to mainly soundbar and Bluetooth speakers. I think those sell more. If we change it now, it will stay for another 5 years.

**Comment by Feichtmeier** [comment]
> > That [actual speaker unit ](https://www.google.com/search?q=speaker+unit&client=ubuntu&hs=HQ&channel=fs&sxsrf=ALeKk03TwvqkcGYbyRRZnSejhiveev8ZHw:1582366358386&tbm=isch&source=iu&ictx=1&fir=n9pqGWaPH0yNAM%253A%252CdmUBssNySr7_GM%252C_&vet=1&usg=AI4_-kQ-VTO99eRWfT6LmnUlZSbzCDintQ&sa=X&ved=2ahUKEwiursiF9uTnAhVQ3qQKHbpVAHEQ9QEwAnoECAoQCA#imgrc=n9pqGWaPH0yNAM:)looks just like that
> 
> That is true. But people mostly related sound device to mainly soundbar and Bluetooth speakers. I think those sell more. If we change it now, it will stay for another 5 years.

Na, I think putting a bluetooth glyph into the icon could be enough. That boxes are hard to draw in Yaru style.

**Comment by Jupiter007-43** [comment]
Monochrome version :

![sound svg](https://user-images.githubusercontent.com/36476595/75091966-5a220380-5573-11ea-942d-bebef924a8bf.png)

**Comment by meetdilip** [comment]
Hoping to do something different from Adwaita.

![speaker blue](https://user-images.githubusercontent.com/6965443/75092641-e8ac7a00-559f-11ea-87e5-e2f5667e9d38.png)

**Comment by madsrh** [comment]
> Hoping to do something different from Adwaita.

That is really good @meetdilip :muscle: 
I'm not sure that using a difference metaphor from Adwaita is an improvement. I prefer just creating a similar icon in the Yaru style like @Jupiter007-43 did [here.](https://github.com/ubuntu/yaru/issues/1948#issuecomment-589949653) (is there a PR incoming :wink: )

It's just my opinion and nothing wrong with you drawing though :smiley:

**Comment by meetdilip** [comment]
It is simply a personal choice. I somehow relate pictures like this to a sound device. Haven't seen bare bone speakers much.
