### ISSUE TITLE
Gnome Tweaks icon has old-style toggles

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#1958]
In master, the icon for Gnome Tweaks has square green toggles, which are no longer used in Yaru:

![image](https://user-images.githubusercontent.com/38893390/75061264-470e2580-54d8-11ea-8aa6-35609c3e4c19.png)

This is the replacement icon I'm working on for the spring clean:

![image](https://user-images.githubusercontent.com/38893390/75061305-5d1be600-54d8-11ea-9443-c9644dcdf3dc.png)

The purple is the same one used in the toggles - the compression on the image is just making it look more saturated here.

**Comment by Feichtmeier** [comment]
Nice!
I think they should start at the same pixel though
Like
0-1
1-0

**Comment by ubuntujaggers** [comment]
> Nice!
> I think they should start at the same pixel though
> Like
> 0-1
> 1-0

I tried that first but it looked a bit naff to my eye, because the proportions of the toggles are different and it looked a bit squished in horizontally :(  I'll post to show what I mean when I get chance.  I know there's a bit of "artistic licence" in staggering the toggles, but I hope people will like the design choice when they see the comparison.  If not, c'est la vie  :)

**Comment by Neocazen** [comment]
And this appeared to me
![Captura de tela de 2020-02-21 17-02-23](https://user-images.githubusercontent.com/15347187/75067806-a108ee00-54cc-11ea-8060-3491fd8b5ddd.png)

**Comment by Feichtmeier** [comment]
Yes yes, gnome shell 3.36 is missing for the yaru theme. Chill

**Comment by Feichtmeier** [comment]
@ubuntujaggers what if you would stretch the switches like in the old icon? :) Ah I just wait for your reply

**Comment by ubuntujaggers** [comment]
> @ubuntujaggers what if you would stretch the switches like in the old icon? :) Ah I just wait for your reply

Yep, we can try this - when I'm on my laptop I'll do all three versions for comparison ☺️

**Comment by ubuntujaggers** [comment]
Actually...  centred looks fine  :)  I've done a lot of work on the elements themselves since I last tried it this way, and I don't think the problem was the alignment after all:

![image](https://user-images.githubusercontent.com/38893390/75076465-32da2080-54f8-11ea-9e44-a9e5c176430a.png)

![image](https://user-images.githubusercontent.com/38893390/75076480-3d94b580-54f8-11ea-8260-dd767e1d9953.png)

IMO stretched doesn't look any better and resembles the real toggles less:

![image](https://user-images.githubusercontent.com/38893390/75076512-4be2d180-54f8-11ea-9438-4ba55f6bbc8e.png)

So I'm happy to go for realistic proportions and centred if everyone else is :+1:

**Comment by Feichtmeier** [comment]
@ubuntujaggers I think we all agreed here 🎉 
Just merge it when you find time 👍

**Comment by ubuntujaggers** [comment]
Yep, it's in the "square spring clean" branch that I just have to finish ☺️
