### ISSUE TITLE
Missing icon for phone device

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1960]
## Actual Behavior

![Capture d’écran du 2020-02-21 19-38-41](https://user-images.githubusercontent.com/36476595/75062385-ff40cb80-54e2-11ea-814d-e84a46708ec0.png)

## Adwaita

![Capture d’écran du 2020-02-21 19-38-58](https://user-images.githubusercontent.com/36476595/75062405-08319d00-54e3-11ea-9d39-70caedd458a4.png)

😲 Next gen phone!

## Steps to Reproduce the Problem

  1. Open Gnome-settings
  1. Go to bluetooth
  1. Connect a phone device

**Comment by Jupiter007-43** [comment]
We can use this https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/phone.svg

**Comment by ubuntujaggers** [comment]
Looks like a missing symlink 👍

**Comment by Jupiter007-43** [comment]
I tested this

`phone.png ../legacy/phone.png`

But that doesn't work.

**Comment by Feichtmeier** [comment]
We have an icon for that @ubuntujaggers just drew one

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/phone.svg

If you have time to fix it @Jupiter007-43 
do this:

add a new line here:
https://github.com/ubuntu/yaru/blob/master/icons/src/symlinks/fullcolor/devices.list

phone.png WHATEVERTHENEWICONISNAMED.png

and then run 

https://github.com/ubuntu/yaru/blob/master/icons/src/symlinks/generate-symlinks.sh
with the argument
-m phone
(I think that'd do)

**Comment by madsrh** [comment]
I can't confirm this issue 😕 

![image](https://user-images.githubusercontent.com/3986894/75101259-e9620200-55d9-11ea-9409-184231fcb888.png)

**Comment by Jupiter007-43** [comment]
Sorry I forgot to check on master... 😓
