### ISSUE TITLE
document-print-preview icon is ambiguous

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1962]
The `document-print-preview` icon is ambiguous and could need little improvement.

Yaru icon
[document-print-preview](https://github.com/ubuntu/yaru/blob/master/icons/Suru/256x256/legacy/document-print-preview.png)
![grafik](https://raw.githubusercontent.com/ubuntu/yaru/master/icons/Suru/256x256/legacy/document-print-preview.png)

Look at the Adwaita icon
[document-print-preview](https://github.com/GNOME/adwaita-icon-theme/blob/mainline/Adwaita/256x256/legacy/document-print-preview.png)
![grafik](https://raw.githubusercontent.com/GNOME/adwaita-icon-theme/mainline/Adwaita/256x256/legacy/document-print-preview.png)

And we already have this in Yaru
[document-print](https://github.com/ubuntu/yaru/blob/master/icons/Suru/256x256/legacy/document-print.png)
![grafik](https://raw.githubusercontent.com/ubuntu/yaru/master/icons/Suru/256x256/legacy/document-print.png)

So... `document-print` + magnifying glass = `document-print-preview` 😁

**Comment by madsrh** [comment]
Sorry @Amr-Ibra you've already mentioned this, but I forgot to reply. It's a good observation. Could you provide a PR for this?

**Comment by Amr-Ibra** [comment]
> Could you provide a PR for this?

I have no idea how to draw an icon, so I think I cannot.

**Comment by madsrh** [comment]
> I have no idea how to draw an icon, so I think I cannot.

I can't draw anything either, but it's just like you say 

> document-print + magnifying glass = document-print-preview

😄

**Comment by ubuntujaggers** [comment]
I think we need to update 256px legacy printer to match 256px printer device. We can also do a version with a magnifying glass 👍
