### ISSUE TITLE
Legacy icon for export and import are too similar

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1968]
It's really hard to tell the two legacy icons for export and import apart. Perhaps we should adopt that purple 😉 

![image](https://user-images.githubusercontent.com/3986894/75100766-84ef7480-55d2-11ea-8f2d-d6df75e9d285.png)

The same two icons in Humanity:
![image](https://user-images.githubusercontent.com/3986894/75100769-98024480-55d2-11ea-9e64-829bdde8dd80.png)

**Comment by meetdilip** [comment]
Or change the direction or the arrow. Import can arrow down and export can be arrow up. Or simply change `import` alone.
