### ISSUE TITLE
Style Video app icon similar to upstream

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1969]
I really like the (Totem) Video icon in Yaru, but IMO we should not deviate from upstream without good reason and here, I don't see a reason that the new Adwaita icon can't be Yaruified.

@ubuntujaggers WDYT?

![image](https://user-images.githubusercontent.com/3986894/75100976-e238f500-55d5-11ea-911c-c8d7346eaedb.png)

![image](https://user-images.githubusercontent.com/3986894/75100998-6ee3b300-55d6-11ea-89d2-5867e36574df.png)

https://gitlab.gnome.org/GNOME/totem/blob/master/data/icons/scalable/org.gnome.Totem.svg

**Comment by ubuntujaggers** [comment]
I think a flat version of that arrowhead could work really nicely on a white-ish backplate.

**Comment by meetdilip** [comment]
I used an existing template. Let me know if you find this ok, I can attach the SVG.

![totem yaru](https://user-images.githubusercontent.com/6965443/75103322-47650880-561f-11ea-8e25-f235b8db4c14.png)

![totem yaru purple](https://user-images.githubusercontent.com/6965443/75103323-492ecc00-561f-11ea-8b9f-7176afbce6ba.png)

**Comment by Feichtmeier** [comment]
I would personally not prioritize this, since we have a well made yaru icon for this. :man_shrugging:

**Comment by meetdilip** [comment]
@Feichtmeier I submitted this for @madsrh . Perhaps he prefers this for personal use.

Perfectly ok with whichever icon the team choose for the player :)

**Comment by meetdilip** [comment]
> I would personally not prioritize this, since we have a well made yaru icon for this. man_shrugging

Any place where team and others can talk and share off-topic ? I know I am not in the team, me and a few people who like to comment on the work. Something like Discord ?

**Comment by madsrh** [comment]
You are always welcome to comment here or on https://discourse.ubuntu.com/c/desktop

> I would personally not prioritize this, since we have a well made yaru icon for this.

We have! And low prioritize ofc, but also low hanging fruit.

**Comment by meetdilip** [comment]
> You are always welcome to comment here or on https://discourse.ubuntu.com/c/desktop

Without shouting to the whole world as well :)

**Comment by madsrh** [comment]
I really do think that Yarufying the upstream icon would have been a good move. It would be less confusing for people from other distros, but since the LTS has been released, I think that switching it now will be even more confusing.

I'll close it. Let me know if you feel otherwise @ubuntujaggers @Feichtmeier @clobrano
