### ISSUE TITLE
gtk/src/dark/gtk-3.0/meson.build:201:0: ERROR:  Tried to create target "gtk30_gresource", but a target of that name already exists.

### ISSUE THREAD

**Issue by Dragon8oy** [ubuntu/yaru#1972]
## Expected Behavior

When installing on Debian Buster 10.3, I recieved "gtk/src/dark/gtk-3.0/meson.build:201:0: ERROR:  Tried to create target "gtk30_gresource", but a target of that name already exists."
Commands I ran:
 - `sudo apt install git meson libgtk-3-dev sassc`
 - `sudo tar -xf yaru-20.04.1.tar.gz $$ cd yaru-20.04.1`
 - `sudo meson build`

## Actual Behavior

I got the error message
Full log: ```
Build started at 2020-02-23T13:06:51.791958
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.49.2
Source dir: /usr/share/mollusc-themes/yaru-20.04.1
Build dir: /usr/share/mollusc-themes/yaru-20.04.1/build
Build type: native build
Project name: Yaru
Project version: 19.10
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring cursor.theme using configuration
Configuring index.theme using configuration
Program meson/post_install.py found: YES (/usr/share/mollusc-themes/yaru-20.04.1/icons/meson/post_install.py)
Program sassc found: YES (/usr/bin/sassc)
Program sassc found: YES (/usr/bin/sassc)
Program install-shell.sh found: YES (/usr/share/mollusc-themes/yaru-20.04.1/gnome-shell/src/install-shell.sh)
Configuring index.theme using configuration
Program sassc found: YES (/usr/bin/sassc)
Configuring gtk.gresource.xml using configuration
Found pkg-config: /usr/bin/pkg-config (0.29)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.58.3
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -lglib-2.0
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-lglib-2.0
Program sassc found: YES (/usr/bin/sassc)
Configuring gtk.gresource.xml using configuration
Program sassc found: YES (/usr/bin/sassc)
Configuring index.theme using configuration
Program sassc found: YES (/usr/bin/sassc)
Configuring gtk.gresource.xml using configuration

gtk/src/dark/gtk-3.0/meson.build:201:0: ERROR:  Tried to create target "gtk30_gresource", but a target of that name already exists.
```

## Steps to Reproduce the Problem

  1. Install dependencies
  2. Attempt to compile

## Yaru version
  * `20.04.1` (From Releases)

**Comment by friendlyapple** [comment]
Try to update meson to the latest version :) I had the same problem as you: https://github.com/ubuntu/yaru/pull/1761#issuecomment-578077892

**Comment by Dragon8oy** [comment]
Yeah, works with the latest version of meson
