### ISSUE TITLE
Add symlinks from our emblems for insync emblems

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1973]
![image](https://user-images.githubusercontent.com/15329494/75113391-e99be500-564d-11ea-8f33-da14f8130d3d.png)

Maybe a "low hanging fruit" :kiwi_fruit: :banana: :cherries: ?

Will check if insync is okay with this, similar how I've checked that they are okay with the folder icon we have: https://github.com/ubuntu/yaru/issues/759#issuecomment-439012243

**Comment by madsrh** [comment]
Any news here @Feichtmeier ?

I installed insync, but have failed to make it show emblems in Nautilus 🤷‍♂

**Comment by Feichtmeier** [comment]
You need to install the nautilus insync package additionally to the insync daemon:
![grafik](https://user-images.githubusercontent.com/15329494/77247437-8fcd1180-6c31-11ea-8ace-3b00186546ba.png)

**Comment by madsrh** [comment]
I did. I'll check again later 🤔

**Comment by Feichtmeier** [comment]
Then you need to restart Nautilus
open a terminal and
nautilus -q

Are you loved into jnsync with your Google account?

**Comment by Feichtmeier** [comment]
Any news here @madsrh ?

**Comment by madsrh** [comment]
TBH I haven't looked more into this 😥 I'm not good friends with symlinks but I imagine @Jupiter007-43 can fix this in a few minutes 👼 Would you mind looking into this?

**Comment by Jupiter007-43** [comment]
> TBH I haven't looked more into this disappointed_relieved I'm not good friends with symlinks but I imagine @Jupiter007-43 can fix this in a few minutes angel Would you mind looking into this?

Of course!

**Comment by Jupiter007-43** [comment]
@Feichtmeier I don't see complete file names on your screenshot upper. Can you pass me the icon list?

**Comment by madsrh** [comment]
Th following icon names are used:

 emblem-insync-error
 emblem-insync-error-shared
 emblem-insync-synced-callbacks-active
 emblem-insync-synced-callbacks
 emblem-insync-synced
 emblem-insync-synced-shared
 emblem-insync-syncing
 emblem-insync-syncing-shared
