### ISSUE TITLE
network-group icon is ambiguous

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1974]
The `network-group` icon is ambiguously a globe with connecting lines.

**Yaru**
[network-group](https://github.com/ubuntu/yaru/blob/master/icons/Suru/256x256/places/network-workgroup.png)
![grafik](https://user-images.githubusercontent.com/45657128/75113288-cf153c00-564c-11ea-9c0a-da78d0ae50a3.png)

**Adwaita**
[network-group](https://github.com/GNOME/adwaita-icon-theme/blob/mainline/Adwaita/512x512/places/network-workgroup.png)
![grafik](https://user-images.githubusercontent.com/45657128/75113334-637f9e80-564d-11ea-8d58-6dbe1edc0cd2.png)

**Comment by Feichtmeier** [comment]
In my opinion the globe is not more ambiguous than the two computers are.

**Comment by Amr-Ibra** [comment]
Yes, however, `network-group` is a local network between local computers, and a globe does not really reflect that.

**Comment by rvz420** [comment]
This was a quick mockup, but maybe something like this?
![network](https://user-images.githubusercontent.com/21206715/75119408-64223000-5661-11ea-89e0-835dfdbda5eb.png)

**Comment by meetdilip** [comment]
Looks nice apart from the upside down monitor.

**Comment by friendlyapple** [comment]
@Amr-Ibra I don't find that the icon is ambiguous. On the contrary, when we want to discover the computers on the network, we quickly know where to look.

<img width="935" alt="network" src="https://user-images.githubusercontent.com/59767069/75140933-2d472b00-56f0-11ea-8756-0431910eacd2.png">

**Comment by Amr-Ibra** [comment]
Windows Network is a local network between local computers connected to the same router. The reason why we know where to look is because of the name and because we got used to it, not because of the icon, as it doesn't really represent a local network.

**Comment by Feichtmeier** [comment]
Yeah you are right. 
It' just that I don't like the upstream icon here and the circle looks so damn good and so damn suru styled. Maybe - if we have time - we find a solution that looks like suru and still fits the exact meaning of the icon.
Nice idea @rvz420 !
What I like about the globe is that the connection is made by a bright thin grid with dots at the knots and the baseplate shows the continents in such a sexy and subtle way. 
Maybe if you could somehow achieve this with your design idea we could get it in

**Comment by rvz420** [comment]
> 
> 
> Yeah you are right.
> It' just that I don't like the upstream icon here and the circle looks so damn good and so damn suru styled. Maybe - if we have time - we find a solution that looks like suru and still fits the exact meaning of the icon.
> Nice idea @rvz420 !
> What I like about the globe is that the connection is made by a bright thin grid with dots at the knots and the baseplate shows the continents in such a sexy and subtle way.
> Maybe if you could somehow achieve this with your design idea we could get it in

Yeah I love the globe design also...is so sexy

![red](https://user-images.githubusercontent.com/21206715/75155640-40a5c680-56ef-11ea-8795-7a74a02e6e73.png)

I don't think that thecircle shape is right in here

**Comment by rvz420** [comment]
![Frame 12](https://user-images.githubusercontent.com/21206715/75156994-038f0380-56f2-11ea-81fe-6c27e8dff748.png)

**Comment by Feichtmeier** [comment]
Maybe you could arange the computers in a circle"bus" rather than on that horizonzal "bus"? And the big image with the highlighted knots looks nice imo

**Comment by rvz420** [comment]
> 
> 
> Maybe you could arrange the computers in a circle"bus" rather than on that horizontal "bus"? And the big image with the highlighted knots looks nice imo
> 
> ![red](https://user-images.githubusercontent.com/21206715/75155640-40a5c680-56ef-11ea-8795-7a74a02e6e73.png)

![Frame 13](https://user-images.githubusercontent.com/21206715/75447121-81981800-5947-11ea-9d05-c8d317ef988a.png)

**Comment by rvz420** [comment]
Will look something like this
![Frame 14(1)](https://user-images.githubusercontent.com/21206715/75500025-9954b800-59aa-11ea-8649-0ab6f41d7983.png)
![Frame 14](https://user-images.githubusercontent.com/21206715/75500028-9c4fa880-59aa-11ea-88f9-2e722866a0a4.png)

**Comment by Amr-Ibra** [comment]
I actually prefer the one with the horizontal line.

**Comment by Feichtmeier** [comment]
Thanks @rvz420 for the nice ideas :+1: 

Personally I would not exchange the current one with the ones that you've shown. Maybe @ubuntujaggers or @madsrh have any idea on how to evolve your icon

**Comment by meetdilip** [comment]
I tried to put a monitor behind the globe. I looked good in bigger sizes, but I think not well enough with smaller sizes. So I tried a cluster. We can connect the globes if required but as is will be fine in my opinion

![Screenshot from 2020-03-02 12-24-00](https://user-images.githubusercontent.com/6965443/75652495-318bbf00-5c81-11ea-81f5-7e5952a3c02a.png)

**Comment by meetdilip** [comment]
Added connections between the cluster elements

![Screenshot from 2020-03-02 12-52-21](https://user-images.githubusercontent.com/6965443/75654033-c3e19200-5c84-11ea-8871-369158ebd5b6.png)

**Comment by real-amano** [comment]
But I thought that the point for a new icon was that the globe was misleading in a certain way because people would make an internet connection.
Can somebody show off a circle with just two monitors included? Without a turnt around third one?

**Comment by meetdilip** [comment]
If you see[ this](https://github.com/ubuntu/yaru/issues/1974#issuecomment-590291683) post, it talks about keeping globe a part of the icon and then incorporate monitors in some way. Since it comes from  a team member, it matters. That is why I tried those.

**Comment by meetdilip** [comment]
I am not sure whether this is any better. But since you asked @real-amano 

![network group no globe](https://user-images.githubusercontent.com/6965443/75750341-fd300580-5d49-11ea-94cd-6e48319c5e48.png)

**Comment by meetdilip** [comment]
One more attempt trying to keep the globe in picture

![globe + monitor](https://user-images.githubusercontent.com/6965443/75753040-e1c7f900-5d4f-11ea-81bd-6ea71c4df0d4.png)

**Comment by real-amano** [comment]
Hmm. How does that look with the monitors being vertically placed. At least the upper one resembles a bit a friendly Emoji Smiley with glasses

**Comment by meetdilip** [comment]
It is normally hard to avoid that.  If you want to keep monitors and the globe together. Someone more skilled will come up with a better idea.

**Comment by Feichtmeier** [comment]
How about skipping the Monitor = network participant metaphor and use people instead?

![image](https://user-images.githubusercontent.com/15329494/75758441-07430b80-5d2c-11ea-8056-a2dc50102e3a.png)
@ubuntujaggers @madsrh

**Comment by clobrano** [comment]
That's nice, but is the network-group only made of actual computers? I think it can connect also servers, if so, it's a bit misleading

**Comment by Feichtmeier** [comment]
It shows up for that windows network in Nautilus.
Yeah, I mean as long as people understand that they can connect to things or people the icon is fine. But then the current icon would also be fine.

**Comment by meetdilip** [comment]
If you see the popular options, they are very different from the globe

https://www.google.com/search?hs=5cp&channel=fs&sxsrf=ALeKk02FqZBggfftX_ByZj1zXHEU4HoIQQ:1583239714519&q=network+group+icon&tbm=isch&source=univ&client=ubuntu&sa=X&ved=2ahUKEwiEt5zGq_7nAhUoILcAHci2DYkQsAR6BAgLEAE&biw=1366&bih=662

**Comment by rvz420** [comment]
> 
> 
> I am not sure whether this is any better. But since you asked @real-amano
> 
> ![network group no globe](https://user-images.githubusercontent.com/6965443/75750341-fd300580-5d49-11ea-94cd-6e48319c5e48.png)

lovely monitors ♥
maybe arrange them like the Adwaita network group icon?

**Comment by real-amano** [comment]
I'd move the left monitor upwards a bit and the right one a bit towards the bottom. Thus we have some sort of diagonal. That should suffice to avoid the "Emoji face".
