### ISSUE TITLE
Nemo: icon in panel covered by scrollbar

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1981]
Forwarded from https://bugs.launchpad.net/nemo/+bug/1862520

**Network and USB unmount icon in left panel gets covered by scrollbar**

When a network drive or USB stick is mounted the unmount icon is on the right-hand edge.
When the cursor is placed over the unmount icon the scrollbar covers it except for a tiny sliver making it extremely difficult to unmount the drive via this method.
Either allow for width of scrollbar expanding on hover and move slightly to the left or add it on the left-hand side of the mount name.

Picture attached for illustration.

![image](https://user-images.githubusercontent.com/3986894/75123001-e92e3900-56a3-11ea-906c-d25269565819.png)

**Comment by Feichtmeier** [comment]
In my opinion there is no need to support Nemo at all since it's a file manager not pre installed on Ubuntu and I see not much reason to install it with Nautilus. But since we already have a section for Nemo in _apps.scss we can probably add some more stuff in there :)

**Comment by madsrh** [comment]
> But since we already have a section for Nemo in _apps.scss we can probably add some more stuff in there :)

This was my thinking too

**Comment by madsrh** [comment]
I'm closing this because this is a bug in Nemo
