### ISSUE TITLE
Power off dialog is screwed up

### ISSUE THREAD

**Issue by coxackie** [ubuntu/yaru#1984]
## Expected Behavior

See a nice power off dialogue.

## Actual Behavior

![Screenshot from 2020-02-24 18-55-15](https://user-images.githubusercontent.com/22049642/75182070-84bcb980-5737-11ea-896d-38eee8c9ed92.png)

## Yaru version

20.04.1-79-ge402f7b8 on Arch Linux.

**Comment by Feichtmeier** [comment]
Yup, new shell is needed for master. 
Apologies for merging to early :+1: 
Just wait some days for the new shell (if you are on arch... no idea when it will land)
Gnome shell consists of many parts and this repo only have 1/3 of it, the theme.

**Comment by clobrano** [comment]
Which gtk version do you have? Also, I saw something similar due to hidpi resolution, is that your case?

**Comment by Feichtmeier** [comment]
It's a shell dialogue

**Comment by coxackie** [comment]
no hidpi, gtk 3.24.14+9+g429a6287e0-1

**Comment by coxackie** [comment]
If the new shell is part of 3.36, arch will not get it until a week or so after official release. It is sad to have such issues for a month to come.

**Comment by clobrano** [comment]
Hi @coxackie, I understand, but master is a development branch. To have the right UI fallback to commit pre-rebase onto upstream (#1746)

**Comment by coxackie** [comment]
ok guys, thanks, I think I will switch to Adwaita for now and wait.
