### ISSUE TITLE
system-users icon does not visualize the plural of its name

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1988]
In Yaru, the side panel in Lollypop has a wrong icon for Compilation. It uses the right icon in Adwaita.

Yaru
![Lollypop_Yaru](https://user-images.githubusercontent.com/45657128/75240415-98fac800-57c4-11ea-9abb-76022f3f1f90.png)

Adwaita
![Lollypop_Adwaita](https://user-images.githubusercontent.com/45657128/75240449-a3b55d00-57c4-11ea-8d99-1fd0dfb2292b.png)

## Software that presents the issue
- OS: Ubuntu 20.04 focal development
- Name: Lollypop
- Version: 1.2.22

## Yaru version
$ apt show yaru-theme-icon 
Package: yaru-theme-icon
Version: 20.04.1

**Comment by Feichtmeier** [comment]
Alright had time to check a little:

 - the icon is called ```system-users``` and it is not missing (which you see in your picture)
- we could eventually try to visualize the plurality of the icon by adding a another user behind this one, just like Adwaita does:

![grafik](https://user-images.githubusercontent.com/15329494/76440770-a5834100-63be-11ea-81a6-0f3f6554e996.png)

(example, needs fine-tuning)

**Comment by Amr-Ibra** [comment]
This icon is also shown at the lower-right corner on the lock screen.

**Comment by Amr-Ibra** [comment]
Ping, if this is easy to fix and could be included in Ubuntu focal.

**Comment by Feichtmeier** [comment]
Sorry did not made it into focal. Also this should be bettr done by @ubuntujaggers since I often mess up the grid
