### ISSUE TITLE
Gtk3: notebook outline improvements

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1993]
Problem:
The notebook outline looks hardcore on top of the orange underline.
![taboutline](https://user-images.githubusercontent.com/15329494/75343298-0c1d4080-5890-11ea-98ee-9b86c935ff30.gif)

Solution 1)
Remove the outline for tabs since the focused tab is highlighted with the orange underline:
![Peek 2020-02-26 12-05](https://user-images.githubusercontent.com/15329494/75343417-556d9000-5890-11ea-863f-71c808823a40.gif)

Solution 2)
1px thick -6px offsetted outline:
![Peek 2020-02-26 12-06](https://user-images.githubusercontent.com/15329494/75343520-91a0f080-5890-11ea-8667-8c53dd5aeefb.gif)

I wasted some time to make the orange underline become the focus_border_color on :focus, sadly the tab does not receive the focus staet :dizzy_face: 

Do you prefer any of the proposed solutions or do you have any other idea? 
@madsrh @clobrano

**Comment by madsrh** [comment]
Solution 2 looks good to me

**Comment by meetdilip** [comment]
When viewing in this size, I think Solution 1 is my favourite. It is conventional as well.

**Comment by clobrano** [comment]
solution 2 is good, so I won't be disappointed if we chose that, but since it seems impossible to focus the tab without selecting it, solution 1 seems better to me.

**Comment by madsrh** [comment]
> since it seems impossible to focus the tab without selecting it, solution 1 seems better to me

Good point! That would be less annoying 😄
