### ISSUE TITLE
Snap store icon is not in Yaru style

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2000]
![Screenshot from 2020-02-27 16-18-42](https://user-images.githubusercontent.com/15329494/75464751-8e386280-597f-11ea-8a55-95873ab19845.png)

The current snap store has some fold effects but icon has a completely different shape than the rest of our icons. It looks very different from our current icon set.
@kenvandine could we change the icon for this application? 
If yes - where should we do it? Since it's a snap, it will probably not take up a yaru icon from the theme. 
In my opinion this is kind of important since as far as I understood you correctly, this is going to be the default software store in 20.04.

**Comment by meetdilip** [comment]
This ?

![snap store](https://user-images.githubusercontent.com/38893390/62161316-cb674400-b30d-11e9-8477-11b16c921ef7.png)

[Source ](https://github.com/ubuntu/yaru/issues/1433)

**Comment by Feichtmeier** [comment]
Yea this icon, it's in our repo already, just want to make sure, that this goes into 20.04

**Comment by kenvandine** [comment]
I'll take care of getting the icon updated.  Thanks!

**Comment by kenvandine** [comment]
Fixed with https://gitlab.gnome.org/Community/Ubuntu/gnome-software/-/commit/7f7e8402d4dd81ccc82b86105ceedd8aa415f1e9

**Comment by Feichtmeier** [comment]
@kenvandine Holy this was fast! Thank you. Gonna need to ping you soon again for the categories icons :angel:

**Comment by kenvandine** [comment]
> @kenvandine Holy this was fast! Thank you. Gonna need to ping you soon again for the categories icons angel

Oh, I would really appreciate that!  Those should be symbolic from the theme, but we are missing some.
