### ISSUE TITLE
Grid Icon. Ubuntu icon

### ISSUE THREAD

**Issue by Neocazen** [ubuntu/yaru#2006]
To increase the identity of Ubuntu, wouldn't it be time to take the grid app up on the dock and put the Ubuntu logo in place?

**Comment by clobrano** [comment]
Hey @Neocazen,
we discussed this a lot, feel free to review the state of the comments on the other closed issues 

e.g. 
- https://github.com/ubuntu/yaru/issues/796
- https://github.com/ubuntu/yaru/issues/584
- https://github.com/ubuntu/yaru/issues/49

**Comment by Neocazen** [comment]
Ok. Sorry.
