### ISSUE TITLE
GDM / search entry

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2007]
Disclaimer: please don't mind the broken elements, don't have the new shell on my host yet
Just look to the colors

@3v1n0 mentioned that he is not too happy with the white search and lock screen/login screen entries

As an alternative we could make it look like in 19.10 https://github.com/ubuntu/yaru/pull/1350

![image](https://user-images.githubusercontent.com/15329494/75606563-4c79fa00-5aee-11ea-878d-27a7fedc80dd.png)
![image](https://user-images.githubusercontent.com/15329494/75606573-60256080-5aee-11ea-8e06-62b82ed1d12b.png)

![Bildschirmfoto von 2020-02-29 12-20-49](https://user-images.githubusercontent.com/15329494/75606536-04f36e00-5aee-11ea-8a3d-163a5f86046e.png)
![Bildschirmfoto von 2020-02-29 12-20-44](https://user-images.githubusercontent.com/15329494/75606537-058c0480-5aee-11ea-8789-3902a3acead6.png)

I personally prefer the white one :crying_cat_face: 
@clobrano @madsrh ?

**Comment by Feichtmeier** [comment]
More transparency:
![image](https://user-images.githubusercontent.com/15329494/75606631-f78ab380-5aee-11ea-83ae-2102e1c81009.png)

**Comment by madsrh** [comment]
I like the "More transparency" version but I also prefer just white

**Comment by Feichtmeier** [comment]
White Version to compare

![image_2020-02-26_20-35-43](https://user-images.githubusercontent.com/15329494/75385836-d785a500-58e0-11ea-931a-5e84aa343826.png)
![image_2020-02-26_19-32-57](https://user-images.githubusercontent.com/15329494/75385839-d81e3b80-58e0-11ea-8cea-b291680c8d42.png)

**Comment by clobrano** [comment]
The last one is very nice

**Comment by Amr-Ibra** [comment]
I also prefer the white one.

**Comment by madsrh** [comment]
Can we safely do a gradient?

**Comment by Feichtmeier** [comment]
That's the new blur. It blurs the background but only for the lock screen

**Comment by friendlyapple** [comment]
The white version is nice.

**Comment by Paz-it** [comment]
> @3v1n0 mentioned that he is not too happy with the white search and lock screen/login screen entries.
I'm feeling the same, especially about the search entry. Looks like a minority opinion right now :smiley:

**Comment by Amr-Ibra** [comment]
What will happen to the "eye" asset in the login screen entry when the entry goes dark? As I can see, the asset itself is black, so a black asset on dark background...

**Comment by Feichtmeier** [comment]
Hi @Paz-it great to see you back :smile_cat: 

Okay since most people seem to prefer what's in master. Let's just keep it?

**Comment by Feichtmeier** [comment]
> What will happen to the "eye" asset in the login screen entry when the entry goes dark? As I can see, the asset itself is black, so a black asset on dark background...

We need to slim it. Will tackle this is @3v1n0 successfully put the spinner as a gresource into Ubuntu

**Comment by Feichtmeier** [comment]
Closing it since most people like the current white entries :+1: 
(search entry switches to dark when one uses the dark shell theme with https://extensions.gnome.org/extension/19/user-themes/)

**Comment by Feichtmeier** [comment]
![Screenshot from 2020-03-06 08-55-26](https://user-images.githubusercontent.com/15329494/76068069-61d8a380-5f88-11ea-9f22-29ebbcb84e65.png)
![Screenshot from 2020-03-06 08-54-57](https://user-images.githubusercontent.com/15329494/76068072-62713a00-5f88-11ea-9268-50f81ce68466.png)

Just for a fair comparison, this is what the 19.10 entry would look like in the new lock screen
