### ISSUE TITLE
Some of the content are not dark for dark theme

### ISSUE THREAD

**Issue by RasitAyaz** [ubuntu/yaru#2008]
I am using Ubuntu 18.04 and installed Communitheme via `snap install communitheme`. I am currently using Communitheme-dark which I enabled from Gnome Tweak Tool. Some of the content have light background like pop-up windows but they have dark background in Ubuntu and Ubuntu on Wayland sessions. This occurs only on Communitheme sessions.

For example;
## Expected Behavior

This is a screenshot from Ubuntu on wayland session:
![Screenshot from 2020-02-29 17-43-49](https://user-images.githubusercontent.com/45076094/75609713-020f7200-5b1c-11ea-83cf-5ebf63dd7f91.png)

## Actual Behavior

And from Communitheme on wayland session:
![Screenshot from 2020-02-29 17-44-33](https://user-images.githubusercontent.com/45076094/75609743-2ec38980-5b1c-11ea-9f27-35ee0ba37b3b.png)

## Yaru version

```
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru
  will become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out
  the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and
  select the "Ubuntu with communitheme snap" session from the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: today at 17:32 +03
channels:
  stable:    0.1    2019-03-13 (1768) 16MB -
  candidate: ↑                             
  beta:      ↑                             
  edge:      29.179 2020-01-16 (1949) 18MB -
installed:   0.1               (1768) 16MB -
```

I am new to Ubuntu and don't know much about linux also. I can also use Communitheme on normal sessions but when I restart the pc I have to start Communitheme session at least once. If I don't, theme won't show up on Gnome Tweak Tool and it loads default theme.

If is there a way to install the theme on normal session permanently how can I do it? If not, how can I fix this problem while using Communitheme sessions?

Thanks in advance.

**Comment by clobrano** [comment]
Hi @RasitAyaz,

thanks for taking time to report this. A little premise. The theme is made of two components, the shell and the gtk part. Usually from gnome-tweaks you can change the gtk part, that's why you still see some parts (the shell ones) white.

We implemented also a way to select the dark shell using an extension called "User themes", but for some technical limitation I didn't find a solution for, yet, this is not possible from the snap install, I am sorry about that.

**Comment by RasitAyaz** [comment]
Thanks @clobrano, so can I remove the theme from snap and install with another method to fix this?

**Comment by Feichtmeier** [comment]
@RasitAyaz Hi there :wave: 

You can keep the snap but you need to install https://extensions.gnome.org/extension/19/user-themes/
to switch to the dark shell version :+1: 
Closing this as we can't change the problem that shell and gtk themes are not linked :/ Thanks for contributing :+1:

**Comment by clobrano** [comment]
Hey @RasitAyaz, that was a misunderstanding. Unfortunately snap does not allow selecting shell dark variant and snap is the official support for Ubuntu 18.04 and it's the only package with the right support for the gtk and shell versions 18.04 has
Hope you can wait and update for the next LTS which is about 1 month away, when you can use the dark-shell

**Comment by RasitAyaz** [comment]
Thank you, I started to use a different shell and gtk themes along with Yaru's icons. This theme has the best icons for Ubuntu!
