### ISSUE TITLE
Symbols differ in aspect ratio for sidebar vs. folder icon

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#2012]
I want to reopen an old issue in which @matthewpaulthomas said that the symbols were different between the sidebar and the folder icons.

The problem is still here. Moreover, it concerns all folders and not only the download folder.

Original issue: https://github.com/ubuntu/yaru/issues/865

**Comment by Feichtmeier** [comment]
Fixed with #2052
