### ISSUE TITLE
Battery levels have the wrong color

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2014]
Battery levels should not use aubergine 🔋 

![image](https://user-images.githubusercontent.com/3986894/75633151-bf749500-5c02-11ea-83d9-e0b70f171ff6.png)

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/blob/ce5ab2d770754037bba5156a001d3df13d3926bc/gtk/src/default/gtk-3.20/_common.scss#L3698-L3724

Just for finding it faster later
