### ISSUE TITLE
Shell: tiled previews have upstream boder-radius

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2021]
https://github.com/ubuntu/yaru/blob/fa22fe031cff99dc6d6fc887869292a0ab695356/gnome-shell/src/gnome-shell-sass/widgets/_tiled-previews.scss#L3-L19

![image](https://user-images.githubusercontent.com/15329494/75684839-7a4b7400-5c91-11ea-8198-e40f32866093.png)

https://github.com/ubuntu/yaru/blob/fa22fe031cff99dc6d6fc887869292a0ab695356/gnome-shell/src/gnome-shell-sass/widgets/_tiled-previews.scss#L3
should be 0 I guess

**Comment by clobrano** [comment]
Yes, you're right, I'm going to fix it
