### ISSUE TITLE
ShellTheme: eye assets could be less bold

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2026]
With https://github.com/ubuntu/yaru/pull/2025
We will be able to have a complete set of assets in our gnome shell theme, including those:
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/eye-not-looking-symbolic.svg
![image](https://user-images.githubusercontent.com/15329494/75757335-0e691a00-5d2a-11ea-82ec-cf428082b07e.png)
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/eye-open-negative-filled-symbolic.svg
![image](https://user-images.githubusercontent.com/15329494/75757367-1e80f980-5d2a-11ea-9b44-6413a81dc916.png)

Do we want to slim them down? Or are they fine like they are? @ubuntujaggers @madsrh @clobrano ?

Edit: they show up in password fields

**Comment by clobrano** [comment]
From the pictures, it doesn't seem too bulky

**Comment by Feichtmeier** [comment]
It looks very different from our other symbolic icons
![image](https://user-images.githubusercontent.com/15329494/76082580-04eee480-5fac-11ea-8917-d84928d59eb0.png)

- no 1px stroke
- it has rounded edges

**Comment by Amr-Ibra** [comment]
Am I the only one who thinks that the Adwaita icon is more recognizable and "looks smoother"?

**Comment by clobrano** [comment]
Recognizable, no, but smoother, some yes, but it's a compromise
