### ISSUE TITLE
gnome-software stackswitcher central button has odd white border

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#2028]
![image](https://user-images.githubusercontent.com/2883614/75802527-2322cd80-5d7d-11ea-8ced-a4ff659bef9f.png)

**Comment by Feichtmeier** [comment]
Maybe it's because of this
https://github.com/ubuntu/yaru/commit/ce1949a5e0b796d32e81418b43d4ceb5e382876f
We need to include this here
https://github.com/ubuntu/yaru/blob/1799458d9799fb936754a92bb0251bb95a34a5fa/gtk/src/default/gtk-3.20/_headerbar.scss#L8

**Comment by Feichtmeier** [comment]
![Bildschirmfoto von 2020-03-03 20-07-37](https://user-images.githubusercontent.com/15329494/75810330-ac8ccc80-5d8a-11ea-929d-99d78e5b07d1.png)
yup, that's it
