### ISSUE TITLE
shell: missing border in dark shell slider

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#2034]
Is this a regression or an upstream change?

![image](https://user-images.githubusercontent.com/2883614/75859893-2a88bc00-5dfb-11ea-834e-732ea40e86e2.png)

**Comment by Feichtmeier** [comment]
Uh that's weird, last time I checked the dark shell theme was yesterday from master and it was not like this. I do like the white slider but I know others don't. So I guess this is a regression

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/blob/f5452e62ef1da89d9345f00e1699750bae64a46b/gnome-shell/src/gnome-shell-sass/widgets/_slider.scss#L22-L24

```$fg_color``` is ```f7f7f7``` for the dark theme

**Comment by clobrano** [comment]
Yes, the handle is supposed to be dark, probably, but I was referring to the slider border. At the sprint, or soon after, we decided to add a border because aubergine blends too much with the dark panel

**Comment by Feichtmeier** [comment]
Yes sorry. That's what weird :) I can fix both of you haven't already started

**Comment by clobrano** [comment]
I started no worries :)

**Comment by Feichtmeier** [comment]
if you like those: https://github.com/ubuntu/yaru/pull/2039
could you also adapt the light variant to that branch's look=?
