### ISSUE TITLE
Dark shell theme no longer selectable in gnome-tweaks

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#2043]
A few commits ago, the dark shell theme was installed to `/usr/share/themes/Yaru-dark/gnome-shell`, and now it has moved to `/usr/share/gnome-shell/themes/Yaru-dark`.

I see that this brings it in line with the light shell theme, which lives in `/usr/share/gnome-shell/themes/Yaru`, but is symlinked to from `/usr/share/themes/Yaru/gnome-shell`.

However, The dark shell theme is no longer selectable in gnome-tweaks (at least on gnome 3.34).

Should it get a symlink from `/usr/share/themes/Yaru-dark/gnome-shell` like the light theme has? Or are things different in gnome 3.36 such that those symlinks are not necessary for the themes to appear in gnome-tweaks (in which case the light theme's symlink can be removed)?

**Comment by clobrano** [comment]
Hi @chrisjbillington,

I noticed this yesterday, the fix should be easy, I'm jus waiting for a feedback from desktop team

**Comment by fra98** [comment]
The Yaru-dark entry disappeared even with the Yaru release from January (19.10.5), so it doesn't seem to be related to the latest changes, any idea?

**Comment by chrisjbillington** [comment]
@fra98 for me I saw it in gnome-tweaks until a few commits ago and can pinpoint the cause as the move of the dark shell theme out of `/usr/share/themes`. However, I'm building from source (well, in the context of an Arch Linux package).

It's possible that for e.g. the Debian packages something could be packaged wrong leading to a similar issue - what OS and packages are you using?

@clobrano thanks! Feel free to close my PR, and if you @ me in the changes I'll test them.
