### ISSUE TITLE
Shell dialogs are broken

### ISSUE THREAD

**Issue by fra98** [ubuntu/yaru#2046]
## Expected Behavior
Shell dialogs don't render correctly the entire window
![Screenshot from 2020-03-06 10-50-53](https://user-images.githubusercontent.com/28491164/76072953-22ff1980-5f99-11ea-90d5-ee094b4f98c4.png)

## Steps to Reproduce the Problem

  1. Try to login into an app that asks su rights

## Yaru version

Yaru installed from sources

**Comment by Feichtmeier** [comment]
Hi @fra98 
You need to have the 3.35.91 shell to use the new dialogs correctly :)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/76073951-61450a80-5f92-11ea-9b05-88262799758a.png)
I think the new shell should be in the regular updates you receive in the dailies, closing this, thanks for reporting :+1:
