### ISSUE TITLE
Current Ubuntu-Dock opacity: should the dock be darkened? 

### ISSUE THREAD

**Issue by real-amano** [ubuntu/yaru#2054]
I made to switch to Focal yesterday and wondered if the current rather translucent dock looks really good when having an app maximised.

That looks worse when you have chosen the dark theme and use a relatively bright background (especially the upper corner surrounded by the black topbar and the dark appwindow/headerbar). 

Personally it is a non issue for me since I know the gsettings command to darken the dock (I set it to 90% opacity now). But newcomers to Linux will have a hard time to figure that out?
Is the current one a good default?

Otherwise the theme looks brilliant and Ubuntu-ish with no other nitpick to be found. Thanks for all your efforts.

**Comment by clobrano** [comment]
Hey @real-amano, I understand your point, but speaking about defaults, I think it's interesting to see what changes you made to make the transparency odd. Dark theme is largely used, but it is not default, as well as bright backgrounds (which I think - but might be wrong - is not the most common in dark variant lovers). On the other side, using all the defaults it's the opaque dock that looks odd, so I believe that this choice still holds.

**Comment by real-amano** [comment]
![full](https://user-images.githubusercontent.com/25839976/76253395-ee19ed80-624a-11ea-96be-d20a69e93a6b.png)
That is my desktop. Beautiful. Many background pictures have a blue sky in the upper part of the picture.

That is the top-left corner with Firefox maximised:
![standard](https://user-images.githubusercontent.com/25839976/76253570-376a3d00-624b-11ea-81a6-225a1d630b15.png)

That is my screen with the opacity increased to 90 percent. 
![90percent](https://user-images.githubusercontent.com/25839976/76253630-510b8480-624b-11ea-802e-e09d7cc3ae08.png)

**Comment by clobrano** [comment]
Thanks @real-amano, this is the same reason we released first with some more opacity, but later on changed to the current state. It's a compromise, so in some cases might not be the best. Luckily someone in gnome is working to bring back the change between solid and transparent top panel, when that arrive we can go back to the beautiful transparencies of 18.10
