### ISSUE TITLE
Wrong folder icon in Gimp

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2057]
## Actual Behavior

![Capture d’écran du 2020-03-10 17-14-50](https://user-images.githubusercontent.com/36476595/76335497-e878e200-62f4-11ea-9f90-af1ec8689a9b.png)

Only desktop and home folder use the correct one.

Gimp 2.10.14, Ubuntu 20.04, tested on master.

**Comment by clobrano** [comment]
Hey @Jupiter007-43, could you double check if this is a regression? That is, did gimp show the right icons before?

**Comment by Jupiter007-43** [comment]
I forgot to check with Adwaita again... I'm too much hurry, sorry. 😓

Adwaita wrong too:

![Capture d’écran du 2020-03-10 17-40-09](https://user-images.githubusercontent.com/36476595/76336475-5a9df680-62f6-11ea-9cf4-2b38d86e461a.png)

Surely a bug with gtk2 which will disappear with Gimp 3.

**Comment by clobrano** [comment]
Awesome, thanks! I'm going to close, np :wink:
