### ISSUE TITLE
Default theme: Gnome clocks "hdysqueezer" buttons have wrong hover color

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2060]
![Bildschirmfoto von 2020-03-11 12-28-54](https://user-images.githubusercontent.com/15329494/76412485-faf62880-6393-11ea-859f-355c0776c88a.png)

Probably because they are not included in our _headerbar.scss styling
Issues so far:

- [ ] wrong hover/active/backdrop styling for those squeezer buttons
- [x] our compact mode is not working there, and the squeezer buttons stretch the whole headerbar including the buttons
- [x] circular buttons are stretched in the "add new" dialogue

**Comment by clobrano** [comment]
I'm afraid this is a common problem for non-adwaita themes. This is Materia

![image](https://user-images.githubusercontent.com/2883614/76452728-e042a480-63d1-11ea-8c7e-8c3294ddc97a.png)

**Comment by clobrano** [comment]
It is basically using the exported background color. If the exported theme_bg_color is green, also the hover effect becomes green

![image](https://user-images.githubusercontent.com/2883614/76454477-07e73c00-63d5-11ea-96a8-a8ad569775bc.png)

**Comment by Feichtmeier** [comment]
Yes it's a problem with light themes with a dark headerbar :) 
So, what shall we do?

**Comment by clobrano** [comment]
Basically we can't fix it

**Comment by clobrano** [comment]
I'd try to build ghome-clocks without some styling and propose a patch if can find one, but not really soon

**Comment by ubuntujaggers** [comment]
Do we have to supply some symbols for these widgets or do we think the design is baked into the app?

**Comment by Feichtmeier** [comment]
I think those are installed by the app under hicolor
Couldn't find those here https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/src/symbolic/gnome-stencils.svg

**Comment by Feichtmeier** [comment]
@clobrano okay, then let's keep it opened so people don't own new bugs? Or rather close it?
I would suggest as a long term goal for 22.04 to either introduce headerbar colours into gtk or drop the mixed theme

**Comment by clobrano** [comment]
Let's keep it open for now

**Comment by clobrano** [comment]
This is a promising step forward https://aplazas.pages.gitlab.gnome.org/blog/blog/2020/04/02/coloring-api.html

**Comment by Feichtmeier** [comment]
Concerning stretched sizes:

Setting the [$sizevariant](https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_common.scss#L15) to ```default``` fixed two issues with the new gnome mobile widges:

![image](https://user-images.githubusercontent.com/15329494/79750056-8efecc80-8310-11ea-9f1a-42ed0ec71784.png)

**Comment by clobrano** [comment]
As demonstration of how quickly hdyleaflet are changing, this issue has become outdated. The look of clock application (and similar ones) is now this one

![image](https://user-images.githubusercontent.com/2883614/94847206-90393700-0422-11eb-83d3-27cc6a1b951e.png)

So there's still a problem, but it's better described by #2364

**Comment by Feichtmeier** [comment]
Oh, last time I've checked gnome clocks the sizing is fine. Let me see

**Comment by Feichtmeier** [comment]
No, the problem here is the wrong BG colour in the default theme, so this issue is still valid. Only  The sizing is fixed. Gnome web have their own implementation of that headerbar and so t he styling had to be applied in their custom css and we are blocked out. I know it's a bit confusing but this should still be opened

**Comment by Feichtmeier** [comment]
![Peek 2020-10-01 23-26](https://user-images.githubusercontent.com/15329494/94865291-9dafea80-043d-11eb-8b4f-e442864eda77.gif)

**Comment by Feichtmeier** [comment]
Maybe my gnome-clocks is just not up-to-date. Will check tomorrow. :zzz: :sleeping:

**Comment by madsrh** [comment]
> Gnome web have their own implementation of that headerbar and so the styling had to be applied in their custom css and we are blocked out. I know it's a bit confusing but this should still be opened...

This should really be fixed upstream, right?

**Comment by Feichtmeier** [comment]
Not the hover thing. You would need to convince upstream too support coloured headerbars and an exported headerbar_bg_color. The chance is never hero but... Very close to zero.

If it's true that a newer version of gnome clocks features again a different hdy version which we can't fix from our side because adwaita doesn't have the fix but the app... Then yes we really need to fix this madness upstream but this means work on gtk and work on the apps that fix the missing adwaita css

**Comment by clobrano** [comment]
There is something I don't understand here.
I have two gnome-clock, one just installed from deb, with version 3.36 and one from flathub with version 3.38. Both show this interface though

![image](https://user-images.githubusercontent.com/2883614/94935190-01cdbf80-04cd-11eb-88a4-3257074988c3.png)

**Comment by Feichtmeier** [comment]
Did you try #2382 ?

**Comment by clobrano** [comment]
Not yet,  but the point is that the specific issue of this ticket is not reproducible with master for me.
