### ISSUE TITLE
Adjust preferences-desktop-online-accounts-symbolic icon to be closer to Adwaita's

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2066]
Adwaita has changed its `goa-panel-symbolic` icon (`preferences-desktop-online-accounts-symbolic` in Yaru) to become an @ symbol instead of a cloud. The reason is that online accounts are not always cloud services, and a cloud icon is a bit misleading.

I think Yaru should follow suit.

**Upstream issue:**
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/issues/60

**Adwaita icon**
[goa-panel-symbolic](https://github.com/GNOME/adwaita-icon-theme/blob/mainline/Adwaita/scalable/apps/goa-panel-symbolic.svg)
![grafik](https://user-images.githubusercontent.com/45657128/76678068-12702400-65d5-11ea-9e03-921b526791ea.png)

**Yaru icon**
[preferences-desktop-online-accounts-symbolic](https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/apps/preferences-desktop-online-accounts-symbolic.svg)
![grafik](https://user-images.githubusercontent.com/45657128/76678091-4d725780-65d5-11ea-944b-4cacd1a9dce1.png)

**Comment by Feichtmeier** [comment]
Uhhh Why? I think the cloud fits pretty good nowadays

**Comment by clobrano** [comment]
I'm a bit surprised as well. It's true that not everything is in cloud, but it seems to comprehend a wider list of services, and also doesn't confuse with email

**Comment by Feichtmeier** [comment]
If you put an @ sign or a cloud you need to abstract it nevertheless. I'm for closing it,I like the cloud :) 
But thanks @Amr-Ibra your are a great help and I think one of our top issue hunters :+1:
