### ISSUE TITLE
update-manager: garbled switch

### ISSUE THREAD

**Issue by real-amano** [ubuntu/yaru#2067]
The switch loads and looks as expected but at the last moment resizes to look squished:

![grafik](https://user-images.githubusercontent.com/25839976/76685028-d3f85a80-6610-11ea-9047-2e4efdc8bbc6.png)

**Comment by clobrano** [comment]
Hi @real-amano, how does it look with adwaita?

**Comment by real-amano** [comment]
That's the correct looking switch when still loading:
![grafik](https://user-images.githubusercontent.com/25839976/76685485-533b5d80-6614-11ea-9038-57b1dba2224b.png)

**Comment by real-amano** [comment]
Same story with Adwaita: Correctly looking when loading. But then resizing and getting garbled :(

I guess that it isn't a theming issue then.

**Comment by clobrano** [comment]
I guess so as well, it should be reported to update-manager bug tracker, either launchpad, or gitlab. I'll check. Thanks for reporting it anyway
