### ISSUE TITLE
Style dark headerbar similar to light theme

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2070]
I'm not sure how big the diff is here, but what I immediately noticed in backdrop was the button borders when using the Terminal (dark theme) in the light theme.

![image](https://user-images.githubusercontent.com/3986894/76688820-bf2bbf00-6630-11ea-949e-e441f046cf7d.png)

**Comment by madsrh** [comment]
@clobrano What do you think about a border color somewhere in between the two current ones?

**Comment by clobrano** [comment]
Not sure, but I'll post some attempts
