### ISSUE TITLE
system-log-out-symbolic and system-reboot-symbolic do not exist in Yaru

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2073]
`system-log-out-symbolic` and `system-reboot-symbolic` do not exist in Yaru. These icons are supposed to be used in gnome-shell when you search for "logout" and "reboot".

As a result, gnome-shell shows the icon `application-exit-symbolic`, which is basically an [X](https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/actions/application-exit-symbolic.svg), instead when you search for "logout".

**Adwaita icons**

[system-log-out-symbolic](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/scalable/actions/system-log-out-symbolic.svg)
![grafik](https://user-images.githubusercontent.com/45657128/76703010-83dfcd80-66ce-11ea-88a6-54e39e58f4aa.png)

[system-reboot-symbolic](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/scalable/actions/system-reboot-symbolic.svg)
![grafik](https://user-images.githubusercontent.com/45657128/76703044-af62b800-66ce-11ea-9a03-912ac657834d.png)

**Comment by real-amano** [comment]
Hmm. When searching for the german word "abmelden"  (=logout), the "x" is shown. But it doesn't work with "logout" itself.
And I don't seem to be able to trigger "reboot" and "shutdown" at all. But that may be the symptom of this bug. 
IMHO this together with the invisible extensions app are the most glaring Yaru bugs for 20.04 because they remove Shell functionality.

**Comment by Feichtmeier** [comment]
Shutdown is working very well for focal and now backported to bionic

**Comment by real-amano** [comment]
Strange. What is the german word to trigger it? "Ausschalten"? "Herunterfahren"? Both?
![Bildschirmfoto von 2020-03-28 09-43-56](https://user-images.githubusercontent.com/25839976/77819201-453c1100-70d9-11ea-94ce-68c01917e1ef.png)

**Comment by Amr-Ibra** [comment]
In Bionic, I search for Ausschalten = Shutdown, Neustarten = Restart.

**Comment by Feichtmeier** [comment]
So many germans here! (german myself) xD
