### ISSUE TITLE
Some legacy 16x16 icon have twisted paths

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2075]
## Actual Behavior

Document-open icon:

![Capture d’écran du 2020-03-15 18-29-11](https://user-images.githubusercontent.com/36476595/76706889-3160da00-66eb-11ea-9d38-fe89e2747664.png)

Print icon:

![Capture d’écran du 2020-03-15 18-29-35](https://user-images.githubusercontent.com/36476595/76706892-345bca80-66eb-11ea-881d-0f1e14eb0e97.png)

I didn't check all icons from legacy.

**Comment by Jupiter007-43** [comment]
But does it matter? 🤔

![Capture d’écran du 2020-03-15 18-34-21](https://user-images.githubusercontent.com/36476595/76706945-a92f0480-66eb-11ea-9d46-6bd34b4c0c82.png)

It's not clean, but it doesn't seem to affect the 16x16 matrix...

**Comment by ubuntujaggers** [comment]
Good spot, we should fix these when we have chance.
