### ISSUE TITLE
emblems in nautilus not appearing in yaru 20.04.2

### ISSUE THREAD

**Issue by coxackie** [ubuntu/yaru#2076]
## Expected Behavior

there should be emblems for special folders (Music, Documents, etc) in nautilus

## Actual Behavior

there are not there; compare adwaita
![Screenshot from 2020-03-16 08-23-01](https://user-images.githubusercontent.com/22049642/76736801-70307780-675f-11ea-8f08-134cc249d7f3.png)
with yaru
![Screenshot from 2020-03-16 08-22-31](https://user-images.githubusercontent.com/22049642/76736809-76beef00-675f-11ea-8de9-c3e8dd33ce43.png)

## Yaru version

20.04.2, installed from AUR in Arch

**Comment by clobrano** [comment]
Confirmed. The glyphs on the folders appear only at 150% zoom

![image](https://user-images.githubusercontent.com/2883614/76739648-ca840500-676c-11ea-85bc-892215301ec4.png)

**Comment by coxackie** [comment]
I can see them now with latest version. Should we close this?
