### ISSUE TITLE
Incoherent gnome-clocks icons: globe-symbolic, stopwatch-symbolic and timer-symbolic do not exist in Yaru

### ISSUE THREAD

**Issue by real-amano** [ubuntu/yaru#2077]
![grafik](https://user-images.githubusercontent.com/25839976/76736839-e3d68280-6767-11ea-836d-3bbd86a5f847.png)
All gnome-clocks icons look like being bold (just like a font), except for the "Alarms" icon. It looks too fine-grained an fragile in comparison. Can you thicken the boundary circle of this icon by one pixel?

It is looks even more out of place when "Alarms" is selected and the font next to it IS actually bold:

![grafik](https://user-images.githubusercontent.com/25839976/76737542-41b79a00-6769-11ea-9556-c1ec4ef0210a.png)

**Comment by Feichtmeier** [comment]
No, all of our icons use a 1px stroke.
We could either keep it as it is or look up the icon names of the other clock symbols and provide icons. 
If you have time, could you look up the icon names please?

**Comment by real-amano** [comment]
I will try to hunt it down in Gitlab.

**Comment by real-amano** [comment]
https://github.com/GNOME/gnome-clocks/blob/mainline/data/gtk/icons/globe-symbolic.svg
https://github.com/GNOME/gnome-clocks/blob/mainline/data/gtk/icons/stopwatch-symbolic.svg
https://github.com/GNOME/gnome-clocks/blob/mainline/data/gtk/icons/timer-symbolic.svg

**Comment by real-amano** [comment]
And I see why that is inconsistent. There is no separate icon for "Alarms". They reused the symbolic variant of the gnome-clocks icon. And that was probably yarufied when the full-colour proper gnome-clocks icon was updated for Yaru.

**Comment by real-amano** [comment]
While not directly related to gnome-clocks, I am noting it anyway: The shutdown icon in the right corner of the top bar looks very fragile next to the sound icon and the wifi icon. In my eyes that looks incoherent as well. If you want me to do it, I can file a bug for that as well.
But maybe it is just me? It is the same fragile vs bold thin like in the gnome-clocks headerbar.

**Comment by real-amano** [comment]
Thanks. Fixed in Master
