### ISSUE TITLE
Sidebar item list with Large border arfter leave focus on Gnome Settings

### ISSUE THREAD

**Issue by AdsonCicilioti** [ubuntu/yaru#2081]
## Expected Behavior

That no border or outline appears in the Sidebar item list after operations that take the focus off.

## Actual Behavior

An large white border is appearing on Current (orange) sidebar item after..

Search...
![ezgif-3-06e07738db1b](https://user-images.githubusercontent.com/6278398/76880022-da2b4880-6855-11ea-8f86-ec45bcbbf8c4.gif)

after window switching (alt+tab)...
![ezgif-3-c3110f668b3a](https://user-images.githubusercontent.com/6278398/76880093-f6c78080-6855-11ea-865d-7d01459c4b58.gif)

and others operations that leave focus and back.

## Steps to Reproduce the Problem

ABOVE

## Software that presents the issue

- Name: Gnome Settings
- Version: 3.36

## Yaru version
`20.04.1-142-g4baa55a3`

**Comment by clobrano** [comment]
Hey @AdsonCicilioti, thanks for taking time to contribute to Yaru.
The border is expected, it is an accessibility feature to move focus on different button, entry, etc using the keybord

**Comment by AdsonCicilioti** [comment]
OMG! Sorry so.

**Comment by clobrano** [comment]
No worries and feel free to open other tickets while using Ubuntu 😉
