### ISSUE TITLE
Extension app: missing symlink

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2096]
![image](https://user-images.githubusercontent.com/15329494/77157434-a04e8200-6aa1-11ea-9d9b-8a12d4d3a423.png)

@ubuntujaggers nice new icon is not used because the desktop file uses that org.gnome.Extension name

**Comment by Amr-Ibra** [comment]
Ping, if this is easy to fix and could be included in Ubuntu focal.
