### ISSUE TITLE
Text in Wacom "Map buttons" is unreadable

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2099]
Text in Wacom "Map buttons" is unreadable

![image](https://user-images.githubusercontent.com/3986894/77224437-f4bb3580-6b65-11ea-91a4-f2bdc4ba286f.png)

**Comment by madsrh** [comment]
And some content is off screen

![image](https://user-images.githubusercontent.com/3986894/77224521-d0ac2400-6b66-11ea-8941-d7d640d288f1.png)

**Comment by clobrano** [comment]
hey Mads, does it make any difference using the dark shell theme?

**Comment by madsrh** [comment]
> hey Mads, does it make any difference using the dark shell theme?

No, it looks the same in both light, dark and with Adwaita. 

Even with the dark theme the dropdown and buttons are still white

**Comment by madsrh** [comment]
SORRY , I missed the "shell" in your comment

**Comment by Feichtmeier** [comment]
You could try to
sudo apt install gnome-session
Reboot
And log into the vanilla gnome shell which is dark

**Comment by madsrh** [comment]
This is with the dark shell

![image](https://user-images.githubusercontent.com/3986894/77231862-d2dda500-6b9d-11ea-9dea-eed8cdb314b1.png)

**Comment by clobrano** [comment]
So it's the same. The last test would be to use gnome vanilla, if the issue is reproducible, is something upstream

**Comment by madsrh** [comment]
> So it's the same.

It's not the same. Now the text is white but yeah, this isn't great looking.

**Comment by clobrano** [comment]
oh, sorry, I only looked at the buttons, you're right

**Comment by Feichtmeier** [comment]
Could you press
alt + f2 
then enter
lg
and press enter?
then you can take the widget picker and see what that widget is called in the shell?

**Comment by Feichtmeier** [comment]
Searched a bit in gnome-shell commit history. There is no specific style class for the wacom stuff. We could try to catch it with a wildcard, before the widgets are loaded
like
* {
color: $osd_fg_color;
}

....

@ import 'widgets';

**Comment by madsrh** [comment]
> Could you press...

No, everything is disabled. Nothing happens if I press ALT+F2 and I can't bring up the inspector either 😢

**Comment by Dragon8oy** [comment]
The text hanging off the edge of the screen also affects me on Debian Unstable with GNOME 3.36

**Comment by madsrh** [comment]
I'm not sure how to test [your idea above](https://github.com/ubuntu/yaru/issues/2099#issuecomment-602086105), but perhaps we can just close this as it's an upstream issue, right @Feichtmeier ?

**Comment by Feichtmeier** [comment]
No wait please I have an idea for this Eve

**Comment by Feichtmeier** [comment]
Uhm yeah... except the test on bionic, I did not do much here. Problem is that I do not want to use my host machine as a yaru dev machine currently and for those shell changes you need to build it and log into yaru session. 
I could try to give my VM access to the USB port and then try to use the wacom tablet
My guess is that this would also happen on upstream shell if you select the variant to be light, which is the case for the classic session. So it could be eventually fixed upstream
