### ISSUE TITLE
Missing symlinks for dialog warning

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2103]
![grafik](https://user-images.githubusercontent.com/15329494/77257628-d6dcf600-6c75-11ea-8b8d-6a56d625a13e.png)
![grafik](https://user-images.githubusercontent.com/15329494/77257691-36d39c80-6c76-11ea-82da-3999e26bf056.png)

Could be either
```gtk-dialog-warning```
or
```important```
or
```messagebox_warning```
or
```stock_dialog-warning```

that need a symlink to

```dialog-warning```

@ubuntujaggers could you fix that?

**Comment by Amr-Ibra** [comment]
Ping, if this is easy to fix and could be included in Ubuntu focal.
