### ISSUE TITLE
[Regression] Provide bigger sizes of all legacy icons

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2108]
### Steps to reproduce the problem
1. Install transmission, geany, pdfarranger, meld
2. Look at the tiny toolbar icons
3. Switch between Yaru and Humanity icon themes

![Yaru-legacy_Humanity](https://user-images.githubusercontent.com/45657128/77520827-12e4a680-6e82-11ea-9406-6ebd65a21928.gif)

Notice that Humanity provides bigger icons, which look much better.

Notice that Transmission uses a mix of Humanity and legacy Yaru icons, which does not look nice nor consistent.

In my humble opinion, Humanity icons look much better.

### Software that presents the issue
All gtk2 and gtk3 apps, which don't use symbolic icons.

### Yaru version
apt show yaru-theme-icon 
Package: yaru-theme-icon
Version: 20.04.4

**Comment by Amr-Ibra** [comment]
Here is another example from meld (sudo apt install meld):

![meld](https://user-images.githubusercontent.com/45657128/78013366-ab799b80-7346-11ea-8f86-8363767c2b67.png)

**Comment by Feichtmeier** [comment]
Yeah definitely a problem
@ubuntujaggers do you have an idea how to fix this?

**Comment by Bonandry** [comment]
Hi, these are the icons, folder 48 in svg
![Schermata da 2020-03-31 19-10-03](https://user-images.githubusercontent.com/7957697/78055292-a129c280-7383-11ea-87ff-2083c866298b.png)
