### ISSUE TITLE
Icon view captions in Nautilus are hard to read when selected

### ISSUE THREAD

**Issue by Nilsolm** [ubuntu/yaru#2110]
I've noticed that in the latest version of Yaru–the one that just landed in Focal daily–Nautilus' icon caption view becomes unreadable against the orange background when the icon is selected. See example screenshots below.
![Screenshot from 2020-03-25 13-36-55](https://user-images.githubusercontent.com/22319656/77537813-015dc780-6e9f-11ea-876b-1fb61e94e45b.png)
![Screenshot from 2020-03-25 13-37-03](https://user-images.githubusercontent.com/22319656/77537817-03c02180-6e9f-11ea-95c0-d9b1c0fc8537.png)

## Steps to Reproduce the Problem

  1. Turn on icon view captions in Nautilus.
  2. Select any icon.

## Software that presents the issue

- Name: Nautlius
- Version: 3.36.0-stable

## Yaru version

Version 20.04.4 in current Focal daily.

**Comment by Amr-Ibra** [comment]
Yes, this does not happen in Adwaita. Icon captions are clearly visible when selected.

![Nautilus](https://user-images.githubusercontent.com/45657128/77541009-5bad5700-6ea4-11ea-8069-819803dac7c7.png)

**Comment by madsrh** [comment]
Nicely spotted @Nilsolm 👍
