### ISSUE TITLE
Adjust tweaks-app-symbolic to match its icon tweaks-app

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2112]
`tweaks-app-symbolic` does not match its icon `tweaks-app`.

[tweaks-app-symbolic](https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/apps/tweaks-app-symbolic.svg)
![grafik](https://user-images.githubusercontent.com/45657128/77543616-3f131e00-6ea8-11ea-8f7c-447aafb48e29.png)

[tweaks-app](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/tweaks-app.svg)
![grafik](https://user-images.githubusercontent.com/45657128/77543820-800b3280-6ea8-11ea-9f0e-a2aa5130b29b.png)

**Comment by real-amano** [comment]
Not a must-fix in my eyes.
