### ISSUE TITLE
Missing "Health end Fitness" symbolic icon

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#2124]
In snap-store : 
![image](https://user-images.githubusercontent.com/23138504/77893438-3342a580-7274-11ea-8e7a-777bbf5c7ed6.png)
It's missing in Adwaita too.

**Comment by Feichtmeier** [comment]
We have it in yaru
Maybe it's still missing in the snap store C file?@kenvandine

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/categories/applications-health-symbolic.svg

**Comment by kenvandine** [comment]
It's not fixed in stable yet, the fix is in beta as well as the ubuntu-20.04 channel

**Comment by Feichtmeier** [comment]
Alright thanks for clarification @kenvandine 
Closing this issue here then, since
```
application-health-symbolic
```
exists in yaru :)
