### ISSUE TITLE
Bluetooth icon in Configurations isn't very recognizable

### ISSUE THREAD

**Issue by lekegf** [ubuntu/yaru#2126]
## Expected Behavior

See the bluetooth icon cleary in the Configurations section.

## Actual Behavior

The icon appears more like a black spot than a bluethooth icon.

## Steps to Reproduce the Problem

  1. Launch all applications
  2. Select Configurations icon
  3. Search for the bluetooth entry
  
## Yaru version

The one used in Ubuntu 20.04 daily (march 30)

Maybe removing the black background and enlarging the bluetooth symbol itself would fit best?

**Comment by Feichtmeier** [comment]
Cannot confirm this. It's perfectly recognisable for me.
