### ISSUE TITLE
20.04 Misaligned password field in login screen

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#2129]
I refer to this brief discussion in Discourse:

https://discourse.ubuntu.com/t/alignment-of-password-field-in-20-04-login-screen/15146

![image](https://user-images.githubusercontent.com/2845433/78398847-2e5e5880-75ca-11ea-96d3-c97b7f48338c.png)

**Comment by clobrano** [comment]
Hey @memeplex, in which version are you observing this?

**Comment by clobrano** [comment]
This is supposed to be fixed already in 20.04.4

**Comment by memeplex** [comment]
Hi Carlo, I've seen it a few days ago, so it might be fixed as you say, I'll check it again a let you know.

**Comment by memeplex** [comment]
Carlo, it's already fixed as you said, new there is a subtle "ilussion" that makes the field seem misaligned to the other side, as Daniel mentioned in Discourse, but it's a subtle effect that I don't care about, so do as you see fit regarding this report. Thanks!

**Comment by clobrano** [comment]
Thank you for double checking!
