### ISSUE TITLE
buttons in yaru

### ISSUE THREAD

**Issue by avild25** [ubuntu/yaru#2131]
with the new update yaru make checkbox and radio buttons purple. But still the buttons are green. Can't we also change them to pupple?
![Screenshot from 2020-04-04 16-03-26](https://user-images.githubusercontent.com/63145336/78424905-4f887d00-768e-11ea-8b20-07e94b10cd5d.png)
![Screenshot from 2020-04-04 16-03-42](https://user-images.githubusercontent.com/63145336/78424964-af7f2380-768e-11ea-93e9-a05921436121.png)
![Screenshot from 2020-04-04 16-03-56](https://user-images.githubusercontent.com/63145336/78424972-c58ce400-768e-11ea-920a-c884c0d201f3.png)

**Comment by clobrano** [comment]
Hi @havild25, suggested action color is still green, there is no plan to change it.
