### ISSUE TITLE
Python Icon Request

### ISSUE THREAD

**Issue by magikol** [ubuntu/yaru#2136]
Hey guys so I installed a program called python idle and I was horrified when I saw the icon:
![Screenshot-20200406222154-166x155](https://user-images.githubusercontent.com/51972983/78712863-f06d7700-78de-11ea-8e11-15a3b2cb8e77.png)
So I was thinking you guys could re-make the logo. Here's an idea that I made for it:
![Screenshot-20200407125101-378x333](https://user-images.githubusercontent.com/51972983/78713091-522de100-78df-11ea-912d-65cdd0828aa9.png)
Updated icon:
![Screenshot-20200407170518-436x334](https://user-images.githubusercontent.com/51972983/78723991-18b2a100-78f2-11ea-9379-d9fb206fac0a.png)

I hope you guys see this suggestion!

**Comment by Feichtmeier** [comment]
hi! Unless not explicitely allowed or wanted by the developers of the app the icon belongs to, we do not include third-party icons in yaru.

**Comment by madsrh** [comment]
Hi @magikol You should contact the app developer directly. Like @Feichtmeier mentioned above, we don't include third-party icons, so I'll close the issue here for now.
