### ISSUE TITLE
VirtualBox Icon Request

### ISSUE THREAD

**Issue by jqadev** [ubuntu/yaru#2137]
Dear team,

please use for VirtualBox from Ubuntu repository the sharp high resolution VirtualBox icon from official Oracle builds from https://www.virtualbox.org/ instead of currently used custom blurry icon.
If you can't do this because of licence issue, please upgrade resolution of currently used custom icon.

**Comment by Feichtmeier** [comment]
hi! Unless not explicitely allowed or wanted by the developers of the app the icon belongs to, we do not include third-party icons in yaru.

**Comment by jqadev** [comment]
@Feichtmeier ok, so If Canonical developers build custom version of VirtualBox and provide custom icon, please upgrade resolution of currently used custom icon.

**Comment by Feichtmeier** [comment]
First of all, this project, though included in Ubuntu, is made 95% by the Ubuntu community and not canonical developers.

Secondly what custom icon do you talk about? There is no virtual box icon in yaru. 
If Ubuntu packages a virtual box Deb with a bad icon then please open a bug on launchpad about it.

Thanks for contributing

**Comment by jqadev** [comment]
Thank you for clarification.
