### ISSUE TITLE
Build fails following instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by owzim** [ubuntu/yaru#2139]
## Expected Behavior

I want to build the theme following the instructions in `CONTRIBUTING.md`, so I expect it to sucessfully finish to build.

## Actual Behavior

The build fails:

![image](https://user-images.githubusercontent.com/1720088/78837240-eab58580-79f3-11ea-87f1-6e9f5ed1b262.png)

## Steps to Reproduce the Problem

  1. Follow the instructions in `CONTRIBUTING.md`

## Software that presents the issue

- Name: Ubuntu
- Version:  20.04 beta

## Yaru version

`20.04.4-5-geobeecf3`

Thanks!

**Comment by clobrano** [comment]
Hi @owzim,

I just tried with a new VM, and I cannot reproduce this error. Could you double check whether the file that gives the error exists in your filesystem?

**Comment by owzim** [comment]
I am so sorry, yes it exists. It was just a permission thing.

**Comment by clobrano** [comment]
No worries, thanks for reporting back.
