### ISSUE TITLE
Date and day of the week in the right of the GNOME Shell message tray are missing the lower part

### ISSUE THREAD

**Issue by ochazuke-suki** [ubuntu/yaru#2146]
## Info

- Yaru version: 20.04.4
- Ubuntu version: Ubuntu Focal Fossa (development branch)
- Language: Japanese

## Screenshot

![Screenshot_01](https://user-images.githubusercontent.com/63552361/79073456-b4447700-7d21-11ea-8ffd-6a35f9fca039.png)

**Comment by clobrano** [comment]
Hi @ochazuke-suki, thanks for taking time to contribute. Any chance you can try this with vanilla gnome? I need to understand whether it's a Yaru/Ubuntu-gnome or Upstream gnome issue and setting the system language in japanese for me would be a problem :D

**Comment by ochazuke-suki** [comment]
Sure.
I confirmed that the Vanilla GNOME on Ubuntu Focal Fossa doesn't have this issue.

# Screenshots
**Vanilla GNOME**
![vanilla_gnome_screenshot_01](https://user-images.githubusercontent.com/63552361/79119145-a0088480-7dca-11ea-9ed4-1b7da0d74e07.png)

**update-alternatives**
![vanilla_gnome_screenshot_02](https://user-images.githubusercontent.com/63552361/79119228-ccbc9c00-7dca-11ea-9d6a-7c2c41ceb162.png)

**Login screen**
![vanilla_gnome_screenshot_03](https://user-images.githubusercontent.com/63552361/79119271-ee1d8800-7dca-11ea-8323-faa05d36a8d1.png)

**Comment by clobrano** [comment]
Thanks a lot for your help!

**Comment by Feichtmeier** [comment]
this could be an Ubuntu font issue
I've noticed in entries that the Ubuntu font is a little bit bigger than Cantarell. so the pdding might not exactly fit always

**Comment by Feichtmeier** [comment]
@ochazuke-suki try to select the font Cantarell in gnome tweaks and see if the cutting off the letters is gone then please

**Comment by ochazuke-suki** [comment]
@Feichtmeier
@clobrano
I'm sorry, I noticed that the Cantarell and the Vanilla GNOME have this issue (little chipped).

# 2 screenshots

## Better (Cantarell or Vanilla GNOME)

![better_cantarell_01](https://user-images.githubusercontent.com/63552361/79299538-4796cb80-7f1f-11ea-8947-df3cb19b5f46.png)

## Best (Noto Sans CJK JP)

![best_noto_sans_cjk_jp_02](https://user-images.githubusercontent.com/63552361/79299561-58dfd800-7f1f-11ea-865f-a8f97d22bf3b.png)

**Comment by real-amano** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2668#note_779529 might be the issue or at least related to it.

**Comment by Feichtmeier** [comment]
@ochazuke-suki does the fix from the link @real-amano posted work for you? Or is this still present in Ubuntu 20.04?

**Comment by ochazuke-suki** [comment]
@real-amano 
I'm sorry for the delay in my reply.
Changing font hinting affects a little.

# 4 screenshots

## Hinting: None

![003b](https://user-images.githubusercontent.com/63552361/87732491-183a7800-c808-11ea-8ffc-9f4ae951610b.png)

## Hinting: Slight (default)

![004b](https://user-images.githubusercontent.com/63552361/87732555-45872600-c808-11ea-8edc-33b02ae2bdaf.png)

## Hinting: Medium
same as "Slight"

![005b](https://user-images.githubusercontent.com/63552361/87732649-9008a280-c808-11ea-82e2-3c9e1592e6c9.png)

## Hinting: Full
same as "Slight"

![006b](https://user-images.githubusercontent.com/63552361/87732670-a282dc00-c808-11ea-9c6e-8adf12b8c5c0.png)

**Comment by ochazuke-suki** [comment]
@Feichtmeier
Perhaps the issue has been affected by the link, but the one still exists.
After logging in to GNOME Shell 3.36.3, the issue is appeared if I click on the topbar date, but not after that until log out.

# 2 screenshots

## The first time

![001a](https://user-images.githubusercontent.com/63552361/87733075-a5320100-c809-11ea-9339-1c6b1a57ebbc.png)

## The second time

![002b](https://user-images.githubusercontent.com/63552361/87733081-a95e1e80-c809-11ea-9014-4e96c19e1226.png)

**Comment by Feichtmeier** [comment]
Ah Okay. Thanks for the detailed information! I'm still not sure if we should fix this in css. Actually, from my understanding, the UI should adapt to the font. I must admit that I didn't really understand the reply in that gnome shell issue and if they think that they fixed it or not

**Comment by ochazuke-suki** [comment]
Additional screencast
![Peek 2020-07-18 06-18](https://user-images.githubusercontent.com/63552361/87831849-9148d680-c8bf-11ea-9674-35f578fcc443.gif)

**Comment by clobrano** [comment]
@ochazuke-suki, could you confirm this comment https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2668#note_779529 ?
If not, better reply to the ticket and reopen it

**Comment by Feichtmeier** [comment]
It seems like this has been been fixed

"Apparently, simply changing the text hinting settings once via gnome-tweaks fixes the issue permanently with the current gnome-3-36 branch. I've confirmed this on two systems.
Maybe there was some kind of settings migration issue, but I suppose this can be closed."
