### ISSUE TITLE
Enlarged icons in system menu

### ISSUE THREAD

**Issue by lgg** [ubuntu/yaru#2150]
## Expected Behavior

Normal icon sizes.

## Actual Behavior

Enlarged icons.
![image](https://user-images.githubusercontent.com/12018713/79400253-61bbc280-7f8e-11ea-898d-06b4ed04552e.png)

## Steps to Reproduce the Problem

1. `sudo apt install git meson sassc libglib2.0-dev libxml2-utils`
2. `git clone https://github.com/ubuntu/yaru`
3. `cd yaru`
4. `git checkout 20.04.5`
5. `meson build`
6. `cd build`
7. `sudo ninja install`
8. reboot and now icons are enlarged

## Yaru version

git: 20.04.5

Thanks!

**Comment by Feichtmeier** [comment]
it looks like you have the wrong version of Gnome shell
that old system menu is no longer having the round buttons and is instead a menu button so upstream and we don't style it anymore
could you check which version of gnome shell you use?

**Comment by lgg** [comment]
```

**Comment by clobrano** [comment]
Hi @lgg, tag 20.04.x are not supposed to work in 19.10 because the gnome-shell version is too old (you'll need version 3.36)

**Comment by lgg** [comment]
@clobrano thank you!
