### ISSUE TITLE
In alttab switcher its difficult to see choice

### ISSUE THREAD

**Issue by sorenoneill** [ubuntu/yaru#2153]
------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior

When cycling through open apps using alt+tab, the switcher window should display the currently highlighted app clearly

## Actual Behavior

When cycling through open apps using alt+tab, it is very hard to make out which app is currently highlighted. See example in this screen shot:
[http://www.oneill.dk/alttab.png](url)

## Steps to Reproduce the Problem

  1. Open a few applications
  2. Close your eyes
  3. Hold Alt and press tab repeatedly
  4. Open your eyes and see if you can spot the highlighted app

## Software that presents the issue

- Name: Ubuntu 20.04 - clean install with gnome
- Version:

Thanks!

**Comment by clobrano** [comment]
Hi, this should be solved in Yaru 20.04.5 released a couple of days ago. Could you check which version you have?

dpkg -l | grep yaru

**Comment by sorenoneill** [comment]
ii  yaru-theme-gnome-shell                     20.04.5                                    all          Yaru GNOME Shell desktop theme from the Ubuntu Community
ii  yaru-theme-gtk                             20.04.5                                    all          Yaru GTK theme from the Ubuntu Community
ii  yaru-theme-icon                            20.04.5                                    all          Yaru icon theme from the Ubuntu Community
ii  yaru-theme-sound                           20.04.5                                    all          Yaru sound theme from the Ubuntu Community

... I think I may have changed, yes ... into a lighter shade of grey?

**Comment by Amr-Ibra** [comment]
The screenshot does not open, the link is mistyped.

**Comment by sorenoneill** [comment]
ii  yaru-theme-gnome-shell                     20.04.5                                    all          Yaru GNOME Shell desktop theme from the Ubuntu Community
ii  yaru-theme-gtk                             20.04.5                                    all          Yaru GTK theme from the Ubuntu Community
ii  yaru-theme-icon                            20.04.5                                    all          Yaru icon theme from the Ubuntu Community
ii  yaru-theme-sound                           20.04.5                                    all          Yaru sound theme from the Ubuntu Community

... I think I may have changed, yes ... into a lighter shade of grey?

**Comment by sorenoneill** [comment]
www.oneill.dk/alttab.png

**Comment by clobrano** [comment]
In Yaru 20.04.5 the highlight is brighter than before. Can we close this?

**Comment by Feichtmeier** [comment]
yes. in the Bionic snap edge it's not happening. (btw could you release stable? :0)

**Comment by sorenoneill** [comment]
Yes fine. Personally I would have preferred something even lighter og perhaps with a purple bar underneath ... but it's certainly much better than it was

**Comment by clobrano** [comment]
> btw could you release stable

Done 👍️

**Comment by Feichtmeier** [comment]
nice!!! thank you
