### ISSUE TITLE
Problems in Activities menu

### ISSUE THREAD

**Issue by darkdragon-001** [ubuntu/yaru#2155]
## Expected Behavior

Show full icon when searching in _Activites_ switcher.

Show open windows in a reasonable size.

## Actual Behavior

Icon is cropped in _Activites_ switcher:
![Yaru-Search-Problem](https://user-images.githubusercontent.com/177976/79502113-73a17200-802f-11ea-91c7-234af0682440.png)

Open windows are shown tiny:
![Yaru-Activities-Problem](https://user-images.githubusercontent.com/177976/79502121-77cd8f80-802f-11ea-8208-30c55a40e986.png)

## Steps to Reproduce the Problem

  0. Upgrade from Ubuntu 19.10 to 20.04
  1. Click _Super_ key
  2. Start typing application name

## Yaru version

20.04.5 (default on `focal`)

**Comment by clobrano** [comment]
Hi @darkdragon-001, I cannot reproduce this problem. It seems to me an upgrade problem, more than an issue with Yaru theme. I suggest you to report the problem to gnome-shell package on Launchpad

**Comment by darkdragon-001** [comment]
I posted it in [`gnome-shell`](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2651).

**Comment by clobrano** [comment]
I suggested launchpad because it might be a problem with Ubuntu update first. In gnome shell is, as far as I can tell, not reproducible
