### ISSUE TITLE
Open app-indicator

### ISSUE THREAD

**Issue by Neocazen** [ubuntu/yaru#2156]
Hi, guys
       The open applications indicator is standing in front of the name. 
        Using Ubuntu 20.04

![Captura de tela de 2020-04-18 15-07-58](https://user-images.githubusercontent.com/15347187/79646857-74005100-8186-11ea-959f-f25e6da71f4b.png)

**Comment by Feichtmeier** [comment]
oh that's weird
I see your font is italic
did you change the font?

**Comment by clobrano** [comment]
Also the dock seems different, did you installed dash to dock?

>

**Comment by Neocazen** [comment]
It was with a friend on Telegram that he realized. His is with native sources. And not. The dock is native, I only enabled it to change the grid icon upwards to allow custom colors with the dconf-editor program

**Comment by Neocazen** [comment]
![Captura de tela de 2020-04-18 17-22-04](https://user-images.githubusercontent.com/15347187/79670445-85068d80-8199-11ea-9e33-3babba4767f2.png)

**Comment by Neocazen** [comment]
> oh that's weird
> I see your font is italic
> did you change the font?

Yes

**Comment by clobrano** [comment]
Which is your current Font settings, then?

**Comment by Neocazen** [comment]
> Which is your current Font settings, then?

I ended up going back to the original sources and it remainsUbuntu Regular 11, sans regular 11, Ubuntu mono regular 13, Ubuntu bold 11 ). I consulted another friend and his is normal.
     I undid the modifications in the dock, I disabled the extensions I have and it remains the same.

**Comment by Neocazen** [comment]
With another theme there is no problem
![Captura de tela de 2020-04-18 18-25-02](https://user-images.githubusercontent.com/15347187/79671613-1417a380-81a2-11ea-9b3c-ee7c77b18987.png)

**Comment by Neocazen** [comment]
With another theme there is no problem
![Captura de tela de 2020-04-18 18-25-02](https://user-images.githubusercontent.com/15347187/79671613-1417a380-81a2-11ea-9b3c-ee7c77b18987.png)

**Comment by Neocazen** [comment]
With another theme there is no problem
![Captura de tela de 2020-04-18 18-25-02](https://user-images.githubusercontent.com/15347187/79672175-1419a280-81a6-11ea-880f-7e88da4415cd.png)

**Comment by Feichtmeier** [comment]
do you use a 4k Screen and use the UI scaling feature?

**Comment by Neocazen** [comment]
> do you use a 4k Screen and use the UI scaling feature?

longe disso. Estou usando um notebook 1366x768.

**Comment by clobrano** [comment]
Do you remember if initially, with default configuration, the problem was already present?

**Comment by Neocazen** [comment]
> Do you remember if initially, with default configuration, the problem was already present?

Problem not. It was a friend who asked me in a Telegram group that is having the problem and ended up asking me if he also had

**Comment by Feichtmeier** [comment]
need to test if this is connected to the modifications you've did since we didn't observe this ourselves when working on the theme

**Comment by Neocazen** [comment]
> need to test if this is connected to the modifications you've did since we didn't observe this ourselves when working on the theme

I will download the latest Ubuntu Daily and test it live

**Comment by clobrano** [comment]
I tried changing font, font size and zoom, but I cannot replicate it

**Comment by Neocazen** [comment]
> I tried changing font, font size and zoom, but I cannot replicate it

Ok. If you can replicate the problem with the cause, I’ll report it here.

**Comment by Neocazen** [comment]
It must be because of the resolution. LiveCD day 04/17

![Captura de tela de 2020-04-19 16-38-22](https://user-images.githubusercontent.com/15347187/79693890-9dcb7d80-8243-11ea-8fa1-f14fa872cb86.png)

**Comment by clobrano** [comment]
Yes, I replicated with a VM, forcing a low resolution. I believe this  is gnome-shell issue then

**Comment by Neocazen** [comment]
> Yes, I replicated with a VM, forcing a low resolution. I believe this is gnome-shell issue then

Ok.

**Comment by Feichtmeier** [comment]
If this is connected to the low resolution, could you do us a favor and check if this also happens with the default gnome theme?

For 20.04 ofc:

```
sudo apt install gnome-session
reboot
```

click the little gear icon in the bottom right in your login screen and select gnome 
@Neocazen

**Comment by Neocazen** [comment]
> If this is connected to the low resolution, could you do us a favor and check if this also happens with the default gnome theme?
> 
> For 20.04 ofc:
> 
> ```
> sudo apt install gnome-session
> reboot
> ```
> 
> click the little gear icon in the bottom right in your login screen and select gnome
> @Neocazen

The same thing xorg and wayland respectively
![Captura de tela de 2020-04-24 11-21-11](https://user-images.githubusercontent.com/15347187/80223318-82cf8380-861e-11ea-8539-b6af025d8549.png)
![Captura de tela de 2020-04-24 11-22-43](https://user-images.githubusercontent.com/15347187/80223322-83681a00-861e-11ea-9e24-a804444be538.png)


if i reduce the scale factor in the tweaks to 0.74 it gets normal, but it's too small

![Captura de tela de 2020-04-24 11-29-14](https://user-images.githubusercontent.com/15347187/80223592-db9f1c00-861e-11ea-9d9f-c1e7ec79f648.png)

**Comment by Feichtmeier** [comment]
Okay so we know upstream has the problem, too. Thank you @Neocazen 
That doesn't mean that it is not fixable with SCSS. 
Maybe we could fix it with a min-height or padding here: https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss#L95

**Comment by Neocazen** [comment]
Thanks for your attention guys.

**Comment by Feichtmeier** [comment]
@Neocazen 

If you have much time could you do us a favour and open an issue about this on gnome-shell repo instead? Because I think this issue should also happen there. If it is fixed upstream we can pull it back to yaru later.
BUT! do not use the ubuntu themes for this :P They are kinda sensitive there
So you would need to do the following:

sudo apt install gnome-session
reboot
click the little ⚙️ button in the bottom right
chose the gnome session
make sure you have adwaita icon themes + gtk themes selected
make a screenshot of your issue
make an issue about it here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues

Thanks in advance

**Comment by Feichtmeier** [comment]
@Neocazen sorry, did not scroll up to see that you already did test it in gnome-session!

Florian Muellner marked it as dubilcate of the same issue happening in fedora rawhide with the defaul themes, so know that it is an upstream issue. Not yet sure if it is related to the theme (in which case we would need pull the fix to yaru too) or if it is related to the other parts of gnome shell, JS, mutter and whatnot

**Comment by clobrano** [comment]
I think we can close this, right?

**Comment by Feichtmeier** [comment]
Yes, upstream issue :) may be fixed with the new grid in groovy

**Comment by Feichtmeier** [comment]
Just wanted to confirm that this has been indeed fixed in the new gnome shell 3.38
![grafik](https://user-images.githubusercontent.com/15329494/95301148-7c595f00-0880-11eb-8735-1432994a910f.png)
