### ISSUE TITLE
Dropdown List smashed in Qt application

### ISSUE THREAD

**Issue by leoheck** [ubuntu/yaru#2158]
Hi, I am seeing some dropdown lists being smashed in Freecad, which is a Qt application, Like the following example. This is Yaru-dark in ubuntu 20.04. 

![image](https://user-images.githubusercontent.com/1277920/79690696-1de8e780-8232-11ea-911a-414ffb523d14.png)

I reported that in the Freecad forum since I was thinking it was a problem with Freecad itself. People there added screenshots from the same App in other OS's and I added examples in Adwaita too that has the same issue.
https://forum.freecadweb.org/viewtopic.php?f=3&t=45344&p=389271#p389271

Someone told that `Numix` does not have the same issue but it does not have any screenshots
Does it look like a theme issue or it is more like a software-design related?

**Comment by madsrh** [comment]
Hi leoheck. Thanks for taking the time to report this. Could you check if this issue also exist in Adwaita?

**Comment by leoheck** [comment]
Hi @madsrh, I will always be glad to share issues when designers/developers reply as you do. Yes, it happens with Adwaita too. 

It does happen with Adwaita too, look:

![image](https://user-images.githubusercontent.com/1277920/79761657-1db31f80-82f8-11ea-9deb-a699942d1993.png)

**Comment by madsrh** [comment]
Thanks for the effort but this means that this is an upstream issue and therefore has to be fixed there :(

Thanks again for wanting to make Yaru better 👍

**Comment by leoheck** [comment]
Ok, this is good enough for me to know. Do you know where I can report it?

**Comment by madsrh** [comment]
> Do you know where I can report it?

I would think against GTK. Just tag it _Adwaita_ and _Theme_

https://gitlab.gnome.org/GNOME/gtk

I'll close the issue here, but feel free to put the link to the upstream bug in the comments

**Comment by Feichtmeier** [comment]
Kind advice: use adwaita screenshots on their repo, not yaru please @leoheck ; )

**Comment by leoheck** [comment]
Sure! Thanks for the advice.
