### ISSUE TITLE
ShellTheme: wrong selected-color

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2163]
![Bildschirmfoto von 2020-04-24 15-50-55](https://user-images.githubusercontent.com/15329494/80219991-7f022800-8643-11ea-94fc-8aa74112da68.png)
Even though it is correctly defined here: https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/gnome-shell-sass/widgets/_entries.scss#L13
We have a wrong selected-color for entries
Eventually it needs to be set specifically https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/gnome-shell-sass/widgets/_dialogs.scss#L102 for the new password entries style class
or the app folder entry https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss#L55
![Bildschirmfoto von 2020-04-24 15-54-43](https://user-images.githubusercontent.com/15329494/80220321-ed46ea80-8643-11ea-9f44-78bfbb6fa935.png)

**Comment by clobrano** [comment]
note this https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1878998

**Comment by Feichtmeier** [comment]
@clobrano tried this a bit and in the **yaru** session everything is fine:
![grafik](https://user-images.githubusercontent.com/15329494/82679656-82410180-9c4b-11ea-81b5-77b402210153.png)
When you change it to red
![grafik](https://user-images.githubusercontent.com/15329494/82679737-9e44a300-9c4b-11ea-8093-d54b38c59152.png)
:shrug: 
Did not read launchpad yet, but I think we are golden here, must be something related to the session. Maybe @3v1n0 has an idea?

**Comment by clobrano** [comment]
I tried too, it seems a gnome-shell bug to me, hence the LP ticket :)

**Comment by Feichtmeier** [comment]
I wonder if they actually understand that it's probably a Ubuntu issue and not css

**Comment by clobrano** [comment]
I think we can close this since Yaru is doing what it's expected. Eventually, we could reopen it later.

**Comment by 3v1n0** [comment]
Took a while, but apparently this was due to the fix for the coloured emojis! :)

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2260/diffs

**Comment by Jupi007** [comment]
There's indeed still this issue in light theme entries.
And I spent hours trying to fix it with scss 😅

Thanks @3v1n0
