### ISSUE TITLE
Gtk2: Selected radio button does not look right

### ISSUE THREAD

**Issue by kazalex** [ubuntu/yaru#2166]
![claws mail](https://i.imgur.com/YuliqR5.png)

**Comment by Feichtmeier** [comment]
I agree - I would just make them purple.
@madsrh @clobrano could you think about changing your opinion on this one? This looks broken

**Comment by madsrh** [comment]
+1

**Comment by clobrano** [comment]
Gtk2 does not use radio and check buttons properly. @Feichtmeier, do you mean purple like the ones we already have? If so, Ok for me

**Comment by Feichtmeier** [comment]
Yes make both of the radio/check types in assets and assets external purple. Then it is not synced with the border less "osd" type gtk3 ones but at least one could not think that something is damaged :)
