### ISSUE TITLE
Big change in the Ubuntu dock or dashboard

### ISSUE THREAD

**Issue by Gilfoyle153** [ubuntu/yaru#2169]
Dock Ubuntu, which was used a long time ago, would be great if you could make a big Change to what you see in the photo, because it has a lot of user experience and a nice user interface.
If we can uninstall the application launcher and replace it with a second photo, it will be much better and more excellent. I designed these two photos and put them here.
We can also keep this previous dashboard design and add an option in the settings that anyone can adjust the new dock or dashboard to their liking.
This new dock can also be easily coded. All you have to do is give the sticky dock to the left of the screen, a margin to the right, and move it up and down the Border Radius and the Ubuntu launcher icon up. Let's move on and make the rest look like the designed design, which will really have a beautiful and great dashboard that users can experience a great user interface and enjoyable user experience. Ubuntu downloads also increase dramatically because they inspire a great user experience.
Is such a thing possible ?!
![Panel-Left-Github-Yaru-Theme](https://user-images.githubusercontent.com/64503642/80545313-e97ad700-8967-11ea-9006-fc6389f4a7d4.jpg)
![Panel-Left-Extended-App-Yaru-Theme](https://user-images.githubusercontent.com/64503642/80545319-ed0e5e00-8967-11ea-964f-28d9e1365bbe.jpg)
![Panel-Ubuntu-Dock-Yaru-Theme](https://user-images.githubusercontent.com/64503642/80545326-f0a1e500-8967-11ea-8fea-17fcd28296c7.png)

**Comment by clobrano** [comment]
Hey @Gilfoyle153, thank you for taking time to contribute to Yaru.
With Ubuntu one can already do that, just installing a different icon set and a different dock extension. We are proud of our icon set and we don't plan to change it so deeply in a near future though.

**Comment by Gilfoyle153** [comment]
Hi, thank you for answering me
I'm not saying that the design of the Yaru theme is not good
Because it has a better user experience and user interface, and downloading
the new version of Ubuntu is on the rise.
