### ISSUE TITLE
Suggestion: Add choice of accent colors

### ISSUE THREAD

**Issue by ocelaiwo** [ubuntu/yaru#2170]
Not a bug and I'm not sure whether I found the right place to express the matter, but I feel like it might be a good feature to let the user choose accent colors of the theme. As the colors for checkboxes, sliders and stuff changed from light blue and green to purple, I personally would like to keep the colors as they were. Accent colors play a big role in the way the user perceives the desktop, so this might be a simple but important customization option.

**Comment by Feichtmeier** [comment]
Not a bad idea.
I think @clobrano has something in the pipeline for our build system to make something like this possible.
The colors should be ofc sane choices I guess

**Comment by clobrano** [comment]
Hey @ocelaiwo,

if your request is an option to pick and choose the colors, unfortunately this is impossible, considered the state of theming support in Gtk right now (and I think it will be impossible also in the future).

The closest thing is to release an entire new set of Yaru-ish themes, each one with different accent colors (blue, green, etc.), which we are already planning to do for the Ubuntu flavors that want it.

In this sense, yes, there is a PR that will make it easier to do it (even outside this project), but I am not sure we can manage the effort of releasing (and testing) even more themes.

**Comment by ocelaiwo** [comment]
@clobrano Thank you for your response.

**Comment by avil25** [comment]
can we also have folder color support to better suit the overall look of ubuntu flavors? like mate can use green folder color, KDE can use blue and so on. I do think there is already an unofficial way to do this.

**Comment by clobrano** [comment]
Yes, that's the plan, but I'm not sure it would be easy for KDE, since Yaru is a GTK theme

**Comment by stevenjaycohen** [comment]
> Not a bad idea.
> I think @clobrano has something in the pipeline for our build system to make something like this possible.
> The colors should be ofc sane choices I guess

You could base them on Ubuntu's official colour palette: https://design.ubuntu.com/brand/colour-palette/

**Comment by stevenjaycohen** [comment]
I hadn't seen this existing issue when I opened that one. Sorry.

**Comment by ashahir05** [comment]
I absolutely cannot tolerate the energetic Orange and Purple accents of Yaru however I really like the design. A choice of accent colours would be great. Given other OSs like Windows and MacOS already have this feature, this would be a great addition to Ubuntu. I know the Yaru Colours theme already do this however that's not really integrated to the system like snaps don't use it and the login screen etc.

**Comment by ashahir05** [comment]
This is probably not the place to say this but using a neutral accent colour on the login screen (something like grey like) would be great as well.

**Comment by clobrano** [comment]
A choice of color accent is currently impossible due to upstream limitation.

**Comment by Feichtmeier** [comment]
We could only implement some color variants of yaru, with your new build stuff

**Comment by clobrano** [comment]
Yes, but it's the same as Yaru Colours

**Comment by ashahir05** [comment]
Yes it is but with better support. For example snaps would use the accent colour. Unlike yaru colours in which snaps use Adwaita.

**Comment by clobrano** [comment]
I was thinking about this again, and I think there's a big showstopper issue. We still cannot change gtk and shell theme at the same time. We've got already many people complaining that selecting dark theme does not change the shell to dark as well. Consider the effect of a gtk theme with (for example) blue accent color, and the shell that keeps the orange one

**Comment by ashahir05** [comment]
How come though? For example changing the shell theme using gnome tweaks works perfectly fine. So I can't really understand how what you said happens.

**Comment by Feichtmeier** [comment]
gnome-tweaks needs the user-themes extension to change shell themes. which is not installed by default in Ubuntu

**Comment by clobrano** [comment]
Yes, it's as @Feichtmeier said. Basically it is not impossible, but it needs support under Gnome-shell first, and lately I am more convinced than ever to try and push this kind of things upstream first, which might even be rejected, since theming is not always well accepted there.

**Comment by ashahir05** [comment]
Zorin OS already does this. And when I used Zorin it seemed to have worked fine. Maybe you guys could look at that?

**Comment by Feichtmeier** [comment]
Zorin Just preinstall the user themes extension.
It's not in our control. We only make the theme (s).

If you would like to convince the Ubuntu developers to preinstall the user themes extension maybe a thread on the Ubuntu discourse could help.
