### ISSUE TITLE
Icon Request: Difference between iso and img file

### ISSUE THREAD

**Issue by avil25** [ubuntu/yaru#2171]
## Expected Behavior

iso(application/x-cd-image) and img (application/x-raw-disk-image) are almost similar archival formats. They both should have the same or similar type of icon. 

## Actual Behavior
Both do have some connection with cd and the icon of ISO looks good but the IMG icon has the same icon as of plain text.
![Screenshot from 2020-04-29 21-07-25](https://user-images.githubusercontent.com/40562410/80617087-4b6a3800-8a5f-11ea-9da6-d6793011ede7.png)

Also, object file (application/x-object) contains machine code and it does have an icon similar to the document type which looks little misplaced. An Icon like this will look better for binary files.
![application-x-object](https://user-images.githubusercontent.com/40562410/80618282-c08a3d00-8a60-11ea-9825-ed5a73b2adc7.png)

I do not know if it is a good idea but what do you about making mime type icon colorful like this.
![Screenshot from 2020-04-29 21-35-29](https://user-images.githubusercontent.com/40562410/80618817-81a8b700-8a61-11ea-888d-753e925c85f6.png)

I do know all these are non-necessary things and Yaru team does have lots of important work to do but I wonder if someone with a few spare time can do some of the things.

Anyways thank you, everyone, for making Yaru wonderful.

**Comment by madsrh** [comment]
> iso(application/x-cd-image) and img (application/x-raw-disk-image) are almost similar archival formats. They both should have the same or similar type of icon.

Actually they have exactly the same icon 😄 but sure, we could do something similar to the audio files like:

![image](https://user-images.githubusercontent.com/3986894/80621890-4483fb00-8a48-11ea-9ac8-04d9f7ac0562.png)

> ...what do you about making mime type icon colorful like this.

I'm not sure it's a good idea. Any comments @ubuntujaggers @Feichtmeier @clobrano ?

> Also, object file (application/x-object) contains machine code and it does have an icon similar to the document type which looks little misplaced. An Icon like this will look better for binary files.

So, use the binary icon for object files (application/x-object) too?

> Anyways thank you, everyone, for making Yaru wonderful.

😃 Thank you for providing this feedback @avil25. I see you've made [.png mockups](https://user-images.githubusercontent.com/40562410/80618817-81a8b700-8a61-11ea-888d-753e925c85f6.png), but can you create the icons in Inkscape too?

**Comment by clobrano** [comment]
Thanks @avil25 for the feedback, really appreciate it.
I am unsure about colorful mime icons, not against, but I do prefer the ones we have I think

**Comment by avil25** [comment]
Thank you for your quick reply.
But I do see different icons for img and iso is it the problem with my version?

`apt show yaru-theme-icon   
Package: yaru-theme-icon  
Version: 20.04.6
`
also don't get you about object files is it also using the binary icon currently I am seeing it like this

![Screenshot from 2020-04-29 22-53-10](https://user-images.githubusercontent.com/40562410/80627299-4ca26180-8a6d-11ea-9150-8fe72afa7e44.png)


I can create icons in Inkscape but I have never thought these simple-looking icons have this much shades. Do we have any guide that we can follow?

**Comment by avil25** [comment]
Thank you for your quick reply.
But I do see different icons for img and iso is it the problem with my version?

`apt show yaru-theme-icon   
Package: yaru-theme-icon  
Version: 20.04.6
`

also don't get you about object files is it also using the binary icon currently I am seeing it like this

![Screenshot from 2020-04-29 22-53-10](https://user-images.githubusercontent.com/40562410/80627717-f550c100-8a6d-11ea-8ff7-f8266775b8a5.png)

I can create icons in Inkscape but I have never thought these simple-looking icons have this much shades. Do we have any guide that we can follow?

**Comment by Feichtmeier** [comment]
I like the idea :+1: I like colorful icons

**Comment by clobrano** [comment]
> But I do see different icons for img and iso is it the problem with my version?

how did you created the `.img` file? As far as I know, to let the system understand what mimetype a file is, the extension of the filename is not enough

**Comment by ubuntujaggers** [comment]
I also quite like colourful mimetypes 👍

**Comment by avil25** [comment]
> how did you create the `.img` file?

I have not created `.img` file I know changing extensions does not change mimetype I have downloaded Tails os long time ago and instead of iso they provide img file. You can check its mime type. 
![Screenshot from 2020-04-30 07-21-59](https://user-images.githubusercontent.com/40562410/80664123-8dbd6480-8ab3-11ea-9642-e65342a2841c.png)

And thank you everyone on your views.

**Comment by Feichtmeier** [comment]
I think it would have been better to make two issues here. One for the IMG file and one for the color request

**Comment by avil25** [comment]
thanks for your feedback let this one for img file and I will open a new issue for color icon request.

**Comment by Feichtmeier** [comment]
Ninja assigning Mr. Mimetype alias @madsrh to this 😄

**Comment by Feichtmeier** [comment]
Fixed by @madsrh with #2213
