### ISSUE TITLE
gnome-shell theme broken when using custom theme name and gnome-shell-gresource

### ISSUE THREAD

**Issue by fkohlgrueber** [ubuntu/yaru#2173]
I'm trying to make a custom theme based on yaru ([yaru-anycolor](https://github.com/fkohlgrueber/yaru-anycolor)) on Ubuntu 20.04 and the built gnome-shell theme doesn't work. The combination of `-D gnome-shell-gresource=true` and a theme name other than `Yaru` seems to be the problem.

## Expected Behavior

- Successful login using `YaruTest` as shell theme

## Actual Behavior

- Black screen for a couple of seconds, then returns to login screen

## Steps to Reproduce the Problem

- Change theme name to `YaruTest` (in meson.build)
- Build yaru using `-D gnome-shell-gresource=true`
- Log out
- Select the `YaruTest` session and login

## Software that presents the issue

- Ubuntu 20.04 / Gnome 3.36.1

## Yaru version

- Current master (1c3f661)

## Solution

After some digging into this issue, I discovered that the theme name `Yaru` is hardcoded in `gnome-shell/src/data/gnome-shell-theme.gresource.xml`:

```
    ...
    <file alias="Yaru/gnome-shell.css">gnome-shell.css</file>
    <file alias="Yaru/gnome-shell-high-contrast.css">gnome-shell-high-contrast.css</file>
    <file alias="Yaru-dark/gnome-shell.css">gnome-shell-dark.css</file>
    <file alias="Yaru-dark/gnome-shell-high-contrast.css">gnome-shell-high-contrast-dark.css</file>
    ...
```

Replacing `Yaru` with `YaruTest` in that file solves the issue for me. I don't know how this should properly be fixed. I think it'd be possible to make meson put the project name into the file during build. Another option might be to remove the theme name from the aliases completely, but I'm not sure if that plays nicely with gnome.

I could write a PR once I know how this should be fixed.

Thanks in advance and have a nice day ;-)

**Comment by clobrano** [comment]
Hey @fkohlgrueber, thanks for taking time to contribute.
As changing the name of the project is not expected, we probably forgot to make that part of the gresource xml file dynamic. The "fix" is relatively easy, but if you want to have a go, please do :)

**Comment by Muqtxdir** [comment]
The `gnome-shell-theme-gresource` now makes use of custom-names for accent-colors in `gnome-shell`
