### ISSUE TITLE
Icon Request: Making mimetypes more colorful

### ISSUE THREAD

**Issue by avil25** [ubuntu/yaru#2174]
I think it's a good idea to make Yaru mimetype icons a little bit more color full. We can match the color of mimetype icon with the icons of languages if they have any. There are some mockup icons.

![Screenshot from 2020-04-30 21-35-14](https://user-images.githubusercontent.com/40562410/80733733-b41ee680-8b2b-11ea-8506-802da464fc43.png)

**Comment by abeautifulpseudo** [comment]
I like the current icons. They are discreet but clearly visible. They are also very modern. I'm afraid that if we add as much color we lose readability.

**Comment by Paz-it** [comment]
I like the current icons when in use in the light themes. 
It will be nice to have dark ones when using the dark theme. 
Not colorful like @avil25  suggested , only dark background instead.

**Comment by Feichtmeier** [comment]
What is the consensus here? 
I think @madsrh @ubuntujaggers and @Jupiter007-43 updated many mimetypes in the last yaru update. Can we close this issue?

**Comment by ubuntujaggers** [comment]
I say close it, apart from doc-style (white page) icons the mimetypes are very colorful!

**Comment by madsrh** [comment]
> Can we close this issue?

Yes
