### ISSUE TITLE
Overflowing text in ethernet connections settings

### ISSUE THREAD

**Issue by galgalesh** [ubuntu/yaru#2175]
# Actual Behavior

In the "connections" settings panel, for ethernet connections; the text overlaps. This happens in all versions of Yaru on eon

![image](https://user-images.githubusercontent.com/1492981/80840422-96ba4d00-8bfd-11ea-865c-1dd61b3d3689.png)

## Steps to Reproduce the Problem

  1. Open settings
  1. Go to Network
  1. Add a new wired connection (default settings are OK)
  1. Click on the gear next to the new wired connection.

It specifically happens with a wired connection which _is not used_. That's why you can only see it _after_ you add a second wired connection

## Yaru version

default version on bionic.

PS: these instructions in the issue template seem out of date. They still talk about communitheme.

**Comment by madsrh** [comment]
How nice to hear from you again @galgalesh 👋😀

Did you check if the issue also occurs in Adwaita?

**Comment by galgalesh** [comment]
Hi @madsrh it's nice to see you too! Ubuntu 20.04 looks soooo great! Such an awesome job!

The issue also happens in Adwaita:

![image](https://user-images.githubusercontent.com/1492981/80913692-d3459000-8d46-11ea-971b-2ec2e4d90491.png)

**Comment by clobrano** [comment]
Hi @galgalesh, welcome back 😊

It seems a problem within the application. Have you already reported this behaviour in its bug tracker?

**Comment by galgalesh** [comment]
I opened a new issue here: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/991

Do I close this issue?
