### ISSUE TITLE
[Feature Request] Highlight Color Selector

### ISSUE THREAD

**Issue by stevenjaycohen** [ubuntu/yaru#2176]
It would be a notable improvement and reduce the number of people looking to install 3rd Party themes if you would consider adding a macOS-like highlight color selector:

![image](https://user-images.githubusercontent.com/23110485/80845845-7fb53400-8bd8-11ea-9872-a783e9be814c.png)

The selector could be populated with colors from Ubuntu's official palette: https://design.ubuntu.com/brand/colour-palette/

There are a few ways to handle the actual color changes behind the scenes. I won't presume to know best on that front. But, the addition of a Highlight Color Selector to the Appearance Settings seems like a good idea to me.

**Comment by clobrano** [comment]
Hi @rinchen, thanks for the feedback, we discussed the same problem in #2170
