### ISSUE TITLE
bargraph to thin with 4K desktop

### ISSUE THREAD

**Issue by Neo595** [ubuntu/yaru#2177]
## Expected Behavior
Bar graphs (progressbar) displayed in any panel enough tick be correctly seen

## Actual Behavior
bar graphs are too thin

## Steps to Reproduce the Problem
4K Desktop
DPI set to 102
Display any panel with bar graphs (H or V)

## Software that presents the issue
Focal 20.04

## Yaru version
20.04.6

Here we can see that orange underlying thickness is ok as reference : 
![image](https://user-images.githubusercontent.com/25134439/80898927-c35b8b00-8d09-11ea-9c00-64aa4cd98179.png)

vertical progress bar (seems to be magnified when you click on the image)
![image](https://user-images.githubusercontent.com/25134439/80898934-e0905980-8d09-11ea-969e-43de2a5f3119.png)

**Comment by Feichtmeier** [comment]
We use the same padding as the default gtk theme adwaita for progressbars.
If this is really an issue it is a gtk issue

**Comment by madsrh** [comment]
I'll close this issue since it's an issue upstream.
@Neo595 feel free to open the issue upstream
