### ISSUE TITLE
Evolution folder list looks strange in Ubuntu 20.04 - some icons missing?

### ISSUE THREAD

**Issue by Aceler** [ubuntu/yaru#2180]
## Actual Behavior

(What happened instead)
![Снимок экрана от 2020-05-04 11-22-05](https://user-images.githubusercontent.com/5177608/80948044-0301a000-8dfa-11ea-9000-b30f87830582.png)

## Steps to Reproduce the Problem

  1. Install Evolution mail client with sudo apt install evolution
  1. Set up some email account to sync with
  1. Look at the folder icons

## Software that presents the issue

- Name: Evolution
- Version: 3.36.1-2

## Yaru version
```apt-cache policy yaru-theme-icon
yaru-theme-icon:
  Installed: 20.04.6
  Candidate: 20.04.6
  Version table:
 *** 20.04.6 500
        500 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        500 http://ru.archive.ubuntu.com/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by madsrh** [comment]
Hi @Aceler 
Thanks for taking the time to report this 👍 

We are aware of the problem. These are all considered legacy icons, but there has been some fantastic work done to include these. Is it still the plan for 20.04.1 @ubuntujaggers?

**Comment by Feichtmeier** [comment]
Could totally be some icons missing in yaru which fall back to humanity.

Our icon theme is not complete for "legacy" / full color icons for actions
We only have @ubuntujaggers doing the nice icon work with @madsrh  and me sometimes doing some easy icons. 

If you have time it would be cool if you could find out the names of those toolbar icons @Aceler 
Thanks in advance

**Comment by ubuntujaggers** [comment]
Okay, a bunch of these are picked up in my (local) legacy icons test branch.  Now Inkscape looks good I will use this as the next reference app :+1:

**Comment by ubuntujaggers** [comment]
This is how Evolution looks so far in my branch:

![image](https://user-images.githubusercontent.com/38893390/94363857-09502b80-00bd-11eb-9f18-0295c70917bd.png)

**Comment by Feichtmeier** [comment]
I guess you fixed this @ubuntujaggers =)
