### ISSUE TITLE
PSPP icon with yaru theme.

### ISSUE THREAD

**Issue by nazar2sfive** [ubuntu/yaru#2181]
its all dark cannot see.

![image](https://user-images.githubusercontent.com/12841320/81031669-bc20b280-8eac-11ea-8a94-1e99ae13ab49.png)

**Comment by Feichtmeier** [comment]
how does it look with adwaita-dark?

**Comment by Feichtmeier** [comment]
Looking at the picture it looks like Adwaita icons. 
Could you show us which icon themes you have selected and how you did install PSPP ?
Thanks in advance

**Comment by nazar2sfive** [comment]
icon theme - is yaru icon
i installed pspp via downloading pspp from 19.10 repo. pspp not available in 20.04

**Comment by Feichtmeier** [comment]
I guess those are not monochrome SVG icons but full color PNG icons 
So they do not suck up the color we define for text. Which should be white in this case.
Could you link to the repo? Then I could validate this guess and then we could eventually close it here and you could open it on their repo. 
Also, how does it look when you select the adwaita icon theme?

**Comment by nazar2sfive** [comment]
https://www.ubuntuupdates.org/package/core/eoan/universe/base/pspp

**Comment by Feichtmeier** [comment]
@nazar2sfive could you please post a screenshot of this app when adwaita dark

**Comment by Feichtmeier** [comment]
Closed since no response since half a year and I am pretty sure this is a problem with this application using dark icons in a dark theme
