### ISSUE TITLE
GtkSpinner is blue on destructive buttons

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2182]
![grafik](https://user-images.githubusercontent.com/15329494/81177557-2453bf00-8fa7-11ea-9765-594977d18e93.png)
This is simplescan

Imo it should be white

**Comment by clobrano** [comment]
It makes sense. I wonder though if it's too hard to add a minimal dark border also, so that if it appears over white surfaces it'll be still visible

**Comment by Feichtmeier** [comment]
I would rather special case this only for those situations. Please see the PR
