### ISSUE TITLE
nemo: toolbar has wrong color on default Yaru (not light or dark)

### ISSUE THREAD

**Issue by fcastilloec** [ubuntu/yaru#2184]
## Expected Behavior
There are three Yaru theme variants on Ubuntu: Yaru (standard), Yaru-light and Yaru-dark.
The menubar and toolbar for Yaru (standard) have the same color as Yaru-light, there's no difference between them.
There was a previous bug #445 that addressed theming the toolbar and there's a fixed mentioned there (PR #455), but this fix is not showing on Ubuntu 20.04
I think that nemo is not using CSD, so the topbar wouldn't change colors, but I'm expecting the toolbar to do so.

## Actual Behavior
Nemo should have its menubar and toolbar be dark when using Yaru. Yaru-dark changes everything to dark as expected, so Yaru-default should be able to do only a partial change on the menubar and toolbar.
Here's a GIF that shows the current behavior. I'm using GNOME Tweaks to change the theme.
![toolbar](https://user-images.githubusercontent.com/1280530/81339643-59bde280-9063-11ea-80b0-86e2805d7e17.gif)

## Steps to Reproduce the Problem

  1. Select Yaru (Standard) theme
  2. nemo should have it's menubar and toolbar dark.

## Software that presents the issue

- Name: nemo
- Version: 4.4.2

## Yaru version

Official Yaru theme from Ubuntu repositories: `v20.04.6`

**Comment by Feichtmeier** [comment]
No the toolbar should not be dark. The toolbar should be light, like everything in yaru default except the headerbar. Thanks for contributing
