### ISSUE TITLE
Is the mic icon too outlined?

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#2185]
I find the mic icon a bit too outlined when compared to all other, more solid, icons:

![image](https://user-images.githubusercontent.com/2845433/81346893-7ffa7700-9091-11ea-9114-78580851fa5a.png)

don't you?

**Comment by Feichtmeier** [comment]
@memeplex could you try to "gimp"/"glimple" the mic to be solid? Then we would have a comparison

**Comment by avil25** [comment]
i tried to make mic solid its look fine for me.
![81346893-7ffa7700-9091-11ea-9114-78580851fa5a](https://user-images.githubusercontent.com/40562410/83036698-907e8b80-a058-11ea-8993-c621cedc4fcc.png)

**Comment by Feichtmeier** [comment]
I agree, it's really okay this way. Might want to make a pull request? We're kinda lazy right now

**Comment by avil25** [comment]
I don't know how to do that still learning. Don't know much about GitHub.

**Comment by Jupiter007-43** [comment]
I can do it if you want.
