### ISSUE TITLE
nemo: bookmark icons have inconsistent color

### ISSUE THREAD

**Issue by fcastilloec** [ubuntu/yaru#2191]
## Expected Behavior
All Bookmarks should have the same icon color

## Actual Behavior

Some Bookmarks are dark while others are white.
![Selection_002](https://user-images.githubusercontent.com/1280530/82285888-5115b800-9951-11ea-9a7f-a97026d1fc40.png)

## Steps to Reproduce the Problem

  1. Open nemo. Make sure there are bookmarks.
  2. All icons should start as white. Click on a bookmark.
  3. Click away from the previous bookmark to see the change in color. The clicked bookmark in step 2 is now dark.
 
Note: nemo will remember the color of the icons until it has been restarted. `nemo -q` will reset the icons all back to white.

## Software that presents the issue

- Name: nemo
- Version: 4.4.2

## Yaru version

Official version from Ubuntu repositories: v20.04.6

**Comment by clobrano** [comment]
Hi @fcastilloec,

it seems that Nemo is using two different icons, not just with different color.
Is this reproducible with Yaru only, or with Adwaita is the same?

**Comment by fcastilloec** [comment]
When using Adwaita icon theme, this doesn't happen. They all show the same color, black.
I think nemo is trying to distinguish between folders. The two that are dark in the image are folders being synchronized with Insync, so that's why they are black initially. Nonetheless, when clicking in any of the other folders, i.e. Shows, and then clicking away, you'll see the change in colors even though the Shows folder is just a regular folder (not being sync with any program, or a mounted folder, etc)

**Comment by Feichtmeier** [comment]
We have an insync folder for full color. Maybe ths collides with the way nemo searches for the folder names? Eventually we just need a symlink from folder-symbolic to folder-insync-symbolic or something.
Nonetheless, be aware that we do not officially support Nemo, if carlo or me finds time we can fix it though

**Comment by Feichtmeier** [comment]
@fcastilloec could you look up the names of the symbolic icons that are used there. Then it could be a really easy fix with a symlink

**Comment by fcastilloec** [comment]
@Feichtmeier I'm sorry but I wouldn't know which symbolic link is being used.
Some googling brought me to https://github.com/linuxmint/nemo/blob/master/libnemo-private/nemo-icon-names.h#L34-L55 and https://github.com/linuxmint/nemo/commit/eb0f27d487b110bc1f328fc1a81ce519a88b3985. Hopefully, that's useful.

**Comment by Feichtmeier** [comment]
@ubuntujaggers @Jupiter007-43 eventually check if this one is relevant and fixable within some mate contributions

**Comment by Jupiter007-43** [comment]
I created a Mate VM for testing.
@fcastilloec how did you got these symbolic icons? I only can only see fullcolor icons:

![1](https://user-images.githubusercontent.com/36476595/107152897-df601d00-696a-11eb-9310-5705955df929.png)

**Comment by Feichtmeier** [comment]
He is using nemo. But maybe some of the recent symlinks fixed this issue, too

**Comment by Feichtmeier** [comment]
Noticed in Gedit that this is also a problem for default Ubuntu:

![grafik](https://user-images.githubusercontent.com/15329494/110322076-dcf8ed80-8012-11eb-96d7-0c422a616050.png)

I think there must be some symlink we've missed 
CC @Jupi007 @ubuntujaggers
