### ISSUE TITLE
Bluetooth web connection is green

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#2192]
[Ubuntu 20.04, Gnome session, Yaru icons and gtk 20.04.7]

Hi,

![image](https://user-images.githubusercontent.com/23138504/82462875-69561600-9abc-11ea-91a3-fa6e5925623d.png)

does not fit black and white panel style (e.g. wifi icon is not green), imho.
I suggest a greyish/white filling, like battery or wifi indicators.

**Comment by clobrano** [comment]
Hi @fthx, thanks for taking time to report this issue. Could you tell us how to reproduce this behaviour? Did you installed anything, for example, and what do you mean for Bluetooth "web" connection?

**Comment by Feichtmeier** [comment]
![Screenshot_20200520-230700](https://user-images.githubusercontent.com/15329494/82497522-b226c280-9aee-11ea-9547-6f9b562ead4a.png)

You can use the Bluetooth tethering and then use the mobile internet of your mobile phone

**Comment by ubuntujaggers** [comment]
Closed by #2252
