### ISSUE TITLE
GTK warning: Invalid name of pseudo-class

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#2207]
I'm on Arch Linux with GTK 3.24.20, using the Yaru-dark GTK theme built from current git master.

If I run a GTK application from the terminal, I see the following warning printed:
```
# Theme parsing error: gtk.css:5449:34: Invalid name of pseudo-class
```

For example, running `gnome-terminal` from `gnome-terminal`.

Not sure if this indicates any problem, but I don't think it used to occur. I was using the last official release of Yaru until the last few days when I built current master to test a packaging issue, so this warning presumably was introduced by a change sometime between the last release and now.

**Comment by clobrano** [comment]
Hi @chrisjbillington,

I can confirm this on Ubuntu 20.04 with boht gnome-terminal and gedit, but my error is at line 5480

`button.suggested-action spinner:backrop, button.destructive-action spinner:backrop {`

could you extract the gtk.css from gresource and double check if the line is the same?

if you need it, the command is
```
$ gresource extract /usr/share/themes/Yaru/gtk-3.20/gtk.gresource /com/ubuntu/themes/Yaru/3.20/gtk.css
```

**Comment by chrisjbillington** [comment]
The difference I think is me using Yaru-dark and you using Yaru, but yep my line 5449 matches your line 5480:

```
  button.suggested-action spinner:backrop, button.destructive-action spinner:backrop {
```
