### ISSUE TITLE
Missing icons into lollypop

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2208]
Some icons into lollypop are missing in Yaru:
![Capture d’écran du 2020-06-15 14-48-18](https://user-images.githubusercontent.com/36476595/84660094-a45f3400-af18-11ea-8c12-693d50170a4e.png)

Complete list here: https://gitlab.gnome.org/World/lollypop/-/tree/master/data/icons/hicolor/scalable/apps

**Comment by ubuntujaggers** [comment]
Closed by #2235
