### ISSUE TITLE
Change window tiling hint color?

### ISSUE THREAD

**Issue by geckolinux** [ubuntu/yaru#2215]
Hi there, first of all, thanks for this very nice theme. I'm using Yaru 20.04 on openSUSE Tumbleweed and Leap 15.2 with Mate 1.24.0.

Would it be possible to change the window tiling hint color (when you drag a window that will get tiled in quarter or half screen and before you release the mouse) to a light transparent orange color, to make it more in line with the Yaru theme (and most other GTK themes as well). Thanks!

![Screenshot at 2020-06-22 10-26-29](https://user-images.githubusercontent.com/2692138/85306338-f00f6180-b473-11ea-8f22-4ce4913f7d39.png)

**Comment by clobrano** [comment]
Hi @geckolinux,

thank you for taking time to give us your feedback and for liking Yaru :)
This is probably a case of preferences. You could see at the following links the reasons for the current state.

- https://github.com/ubuntu/yaru/issues/1727
- https://github.com/ubuntu/yaru/pull/1883
