### ISSUE TITLE
Nautilus column text in backdrop is gray

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2216]
Nautilus column text in backdrop is gray, which can't be read on the selected item:

![image](https://user-images.githubusercontent.com/3986894/85334623-d4d83c80-b4db-11ea-8766-6146944b32a0.png)

**Comment by madsrh** [comment]
I don't understand this 🤯 Did something change in master? Because now, it seems that the backdrop works fine. The labels are dimmed but not gray. 
This PR keeps everything white 🤔

**Comment by clobrano** [comment]
Something in master or in Nautilus. The code I removed was explicitly to fix this very same bug, but now I can only keep it white :(

**Comment by madsrh** [comment]
I'm fine with the current master, but sorry for wasting your time on this 😬

**Comment by Feichtmeier** [comment]
Maybe something changed in nautilus? I mean in the gtk code?

**Comment by clobrano** [comment]
I did reproduce the error when working on this, soo I am a bit suprised

**Comment by Feichtmeier** [comment]
I can reproduce this with the current yaru version in focal. If we did not change _apps.scss since 20.04.0, I don't think anything changed here, and we need indeed the fix from carlos PR.
