### ISSUE TITLE
Shell: notifications could use more shadow

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2217]
I think at some point in the bionic shell we had it right and the notifications had a great contrast on either dark oder white headerbars. Currently I think there is room for improvement:
![Bildschirmfoto von 2020-06-23 09-28-53](https://user-images.githubusercontent.com/15329494/85373817-1d234900-b534-11ea-8a9f-7e42c70583f1.png)

Maybe again similar to the app notifications, which use (as far as I remember) the "old" notification shadows:
![grafik](https://user-images.githubusercontent.com/15329494/85373968-565bb900-b534-11ea-8a77-6f6303eb6216.png)

I try to fix it - if you agree here @clobrano @madsrh

**Comment by madsrh** [comment]
Are you saying you want to add more shadow to the shell notifications? But I do like the pure #fff background in the shell.

**Comment by Feichtmeier** [comment]
Yes a little bit and a bit different shadow :) The bg color is great
Best would be if I would show examples I guess :thinking:

**Comment by clobrano** [comment]
I think to remember a problem giving shadows to these bubbles because they apply to "pointed"  OSD too, but if this is not the case, I am OK with this change.
