### ISSUE TITLE
Gtk3: context menus could use more shadows

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2221]
Similar to the shell shadows, I preferred the "Yaru 1.0" shadows. I think @madsrh could remember what I mean.
This is not enough in my opinion and it looks like it's on the same layer as the background:

![grafik](https://user-images.githubusercontent.com/15329494/86259704-a4b82a00-bbbc-11ea-8f91-535b6f509b5c.png)

**Comment by madsrh** [comment]
I'm definitely +1 for more shadow

**Comment by clobrano** [comment]
I agree with Mads, can we try a bit more? It doesn't really look like a shadow

**Comment by Feichtmeier** [comment]
Do we consider this to be a contrast problem that needs to be put into focal?

**Comment by clobrano** [comment]
The point release is quite close. I think I am ok with current, so it is ok for me to keep it this way on focal, however I prefer the shadow if it is sensible

**Comment by Feichtmeier** [comment]
1. darker shadow + more spread
![grafik](https://user-images.githubusercontent.com/15329494/86532768-a6d7fc80-becc-11ea-82b7-64943c21ba07.png)
2. slightly darker shadow + slightly more spread
![grafik](https://user-images.githubusercontent.com/15329494/86532801-e6064d80-becc-11ea-917f-a3b9305dbd58.png)
3. darker border shadow + sligthyl more spread
![grafik](https://user-images.githubusercontent.com/15329494/86532946-f0751700-becd-11ea-9da3-9c7b620411bf.png)
Any more ideas?
Why did we change the menu color from white to fafafa btw? :thinking: I think white "popped" up more in the light theme(s)

**Comment by madsrh** [comment]
All good suggestions. I think I prefer #1 

>  I think white "popped" up more in the light theme(s)

White was better. If we changed it dillibertly, it was probably to unify all the menus/pop-over backgrounds

**Comment by Jupiter007-43** [comment]
I also prefer the first one. Good improvement 👍

**Comment by clobrano** [comment]
I agree on #1
