### ISSUE TITLE
Gtk3: Different font colors in backdrop in listbox/sidebar rows

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2227]
White text should be "dimmed" equally in backdrop:

![gif](https://user-images.githubusercontent.com/3986894/86543789-f85ea680-bf21-11ea-9ffb-4e0466722a00.gif)

The combobox text almost looks disabled in backdrop 🤷‍♂️

**Comment by Feichtmeier** [comment]
Maybe this depends on the application.
This one looks fine:
![Peek 2020-07-06 09-30](https://user-images.githubusercontent.com/15329494/86567382-9460d000-bf6b-11ea-9a14-b361fbc2fa80.gif)

**Comment by madsrh** [comment]
> Maybe this depends on the application.

I think you're right 🤔

Focus  vs.  Backdrop
![image](https://user-images.githubusercontent.com/3986894/86584724-a6e80300-bf85-11ea-8be5-19f4b94002b0.png)

Anyway, this is REALLY nitpicking 😄

**Comment by clobrano** [comment]
It might even be because the background of buttons, entries and windows area is different. I agree though that it would be cool to keep the same relationship between the labels in backdrop

**Comment by clobrano** [comment]
Is it Yaru-only? Or we can work on upstream on this?

**Comment by madsrh** [comment]
> Is it Yaru-only? Or we can work on upstream on this?

Adwaita too
![image](https://user-images.githubusercontent.com/3986894/86593939-7492d180-bf96-11ea-81e8-db10cbfb7693.png)

**Comment by Feichtmeier** [comment]
Okay I've nailed this down to

text in "row" widgets

Let's fix this next cycle. Yes it should be fixed upstream but we can also fix it here.

**Comment by Feichtmeier** [comment]
Still relevant for the light theme(s)
