### ISSUE TITLE
Nautilus image border is too bright (dark theme)

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2228]
In Nautilus the border around image previews is light gray (#bbbeb7). In the dark theme the borders are pure white. Would it be possible to make the borders in the dark theme subtle like the light theme?

**Current light theme:**
![image](https://user-images.githubusercontent.com/3986894/86575784-15be5f80-bf78-11ea-9953-81e2bbc460d9.png)

**Current dark theme:**
![image](https://user-images.githubusercontent.com/3986894/86575891-40a8b380-bf78-11ea-9d0a-22ed6d068f5a.png)

**Dark theme mockup:**
![image](https://user-images.githubusercontent.com/3986894/86575909-47cfc180-bf78-11ea-9d4b-65377c76b977.png)

**Comment by madsrh** [comment]
What do you think about this one @Feichtmeier @clobrano ?

**Comment by clobrano** [comment]
It makes sense, Ill try to check if we can fix it

**Comment by Feichtmeier** [comment]
it's def. very bright :D 
If it's an easy fix why not :+1: I guess some nautilus "canvas" stuff. I hope this won't break your very special selection :D *fingers crossed*

**Comment by clobrano** [comment]
I noticed this issue is reproducible on upstream as well, and opened a bug there to push eventually a fix on Nautilus itself

https://gitlab.gnome.org/GNOME/nautilus/-/issues/1558

**Comment by madsrh** [comment]
Soooo, skulle we close it here @clobrano ?

**Comment by clobrano** [comment]
Yeah, why not :)
