### ISSUE TITLE
some icons has crooked path

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2240]
![Capture d’écran du 2020-07-10 11-54-11](https://user-images.githubusercontent.com/36476595/87141942-1589d100-c2a4-11ea-8cc8-c964ce598e89.png)

The PR will follow.

**Comment by Jupiter007-43** [comment]
Same thing with x-office-calendar:

![Capture d’écran du 2020-07-10 12-05-10](https://user-images.githubusercontent.com/36476595/87142975-aa40fe80-c2a5-11ea-9b5d-dc60dab65152.png)

**Comment by Jupiter007-43** [comment]
😱 Some emblems have affected by this issue too:

![Capture d’écran du 2020-07-10 20-40-10](https://user-images.githubusercontent.com/36476595/87187546-9de09400-c2ed-11ea-9a10-21745161e6db.png)
![Capture d’écran du 2020-07-10 20-40-31](https://user-images.githubusercontent.com/36476595/87187547-9f11c100-c2ed-11ea-9764-2dd986d89584.png)


It's a real epidemic 😅

**Comment by madsrh** [comment]
Funny, I always thought that it was this way by design :man_shrugging:

**Comment by Muqtxdir** [comment]
Hi @Jupiter007-43,

Some other icons that also have crooked-path are:
- mimetypes **application-pgp-keys:**
![pgp](https://user-images.githubusercontent.com/54065734/87345474-bb239580-c56d-11ea-8c68-65392d9cd76a.png)


- mimetypes **application-x-executable:**
![exec](https://user-images.githubusercontent.com/54065734/87345482-beb71c80-c56d-11ea-98c9-ff32a29084ed.png)

Thanks!

**Comment by Jupiter007-43** [comment]
Hi @Muqtxdir,
thank you very much 👍
I'll update my PR.
