### ISSUE TITLE
Name issue for mimetype-application-x-theme.svg

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#2241]
Hi,

The icon-baseplate **name** for **mimetype application-x-theme** is named as **mimetype application-x-ms-dos-executable** which might cause an issue when rendering this **theme-mimetype**(application-x-theme.svg) and  **.exe-mimetype**(application-x-mos-dos-executable.svg) with **./render-bitmaps.py**
### Screenshot
![theme](https://user-images.githubusercontent.com/54065734/87142874-d28b2600-c2c2-11ea-89a1-6e560c760d40.png)

Thanks!

**Comment by Muqtxdir** [comment]
I did my first pull-request for this
Please check it

**Comment by madsrh** [comment]
Nicely spotted 👍

**Comment by Muqtxdir** [comment]
Closed with Pull request #2243
