### ISSUE TITLE
Change hover on stackswitcher / pathbar

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#225]
Use the same kind of background hover for stackswitcher / pathbar as we do for other buttons in the headerbar.

![peek 2018-03-02 09-29](https://user-images.githubusercontent.com/3986894/36912709-e40a798e-1e47-11e8-8f1f-8ccc4a36c3e3.gif)

**Comment by NusiNusi** [comment]
Maybe with a soft transition too?

**Comment by nana-4** [comment]
At first I thought @madsrh's mockup looks good. But when I actually tested it, I felt it doesn't look so good than I expected. What do you think? (See also the referenced issue above.)

![0 without-anime](https://user-images.githubusercontent.com/9556384/37146719-eb507efe-2307-11e8-839b-0faf1bb00159.gif)

**Comment by NusiNusi** [comment]
Here it looks a bit "softer". I think because of the transition/fade in.
![stackswitcher](https://user-images.githubusercontent.com/36449926/37149289-c9759632-22cd-11e8-9a15-b1baefded4a5.gif)
(Your Material-Ubuntu-Theme)

**Comment by clobrano** [comment]
@nana-4 would you double check stackswitcher on an open file window? It uses the same style of headerbar, but in a light version

**Comment by nana-4** [comment]
> maybe because of the gif you cant see the fade in good enough... :(

Exactly. My GIF doesn't show real (enough) transition. :(
I think that my strange feeling is due to the square corners of the buttons (that cannot be rounded).

**Comment by nana-4** [comment]
@clobrano Are you talking about the invisible background of `.path-bar`? If so, I'll fix that to make the background color visible again. :)
![image](https://user-images.githubusercontent.com/9556384/37152952-683db1dc-231e-11e8-93ee-4d1de615ce7c.png)

**Comment by nana-4** [comment]
> I'd like to see whether the background highlight on hover would affect also that pathbar.

We can choose whether to affect or not to the pathbar, but if we adapt the highlight, it should be like this:
![out3](https://user-images.githubusercontent.com/9556384/37156371-46e8e686-2329-11e8-900e-f3c6bc746fd1.gif)

**Comment by clobrano** [comment]
Awesome!

**Comment by yawzub** [comment]
Personally, I like the current behavior (gray line on hover > orange line when active)
It feels very natural to me. Is it possible to have both at the same time? Like in firefox:
![fox](https://user-images.githubusercontent.com/36858800/37170690-954e71d6-231c-11e8-9e6b-b9fc37d1eb9d.gif)

**Comment by madsrh** [comment]
![image](https://user-images.githubusercontent.com/36858800/37170690-954e71d6-231c-11e8-9e6b-b9fc37d1eb9d.gif)

I agree that this one might be the best fit 👍 
Should the animation then be the exact same as in Firefox? To me it looks like a [overline from center](http://ianlunn.github.io/Hover/) and on click everything changes instantly (without any animation).

**Comment by ya-d** [comment]
Sorry, but whats wrong with the current style?

Judging from the mockups/gifs I tend to prefer how things are. Status is indicated by the the underline: orange if selected/active, grey on hover. This seems logical to me and is consistent with other elements. Why change the background on hover (…and than change it back if selected and add an underline instead)?

**Comment by clobrano** [comment]
There's only the animation left

**Comment by Feichtmeier** [comment]
Is this still up-to-date?
@madsrh @clobrano

**Comment by clobrano** [comment]
It is, I just haven't found a way to implement it :(

**Comment by Feichtmeier** [comment]
What I don't understand is why would we change this for the white underline? The underline makes perfect sense since when you press it it becomes an orange underline. :/

**Comment by clobrano** [comment]
The underline will be orange, just the animation is required

**Comment by clobrano** [comment]
I believe the underline will still be orange

**Comment by Feichtmeier** [comment]
I would prefer the current hover with only a grey line instead of the whole background. 
@madsrh don't you agree? I know it has been some months but why should we exchange the cool 
no line / white line / orange line for normal / hover / active ? I think that fits perfectly with the shell's top panel

**Comment by madsrh** [comment]
@Feichtmeier it's been FIVE months (I need to get our more LOL) so, +1 for keeping the current.

Does the gray line have a subtle/fast fadein on hover? Like we did for the buttons. I don't remember and I'm on the road atm

**Comment by Feichtmeier** [comment]
@madsrh I try to look how @nana-4 does it with his materia and all the many forks of it (canta, pop)

**Comment by madsrh** [comment]
There's a quick fadein/out (in Yaru) and I think that's fine, so I'll close this issue for now.
