### ISSUE TITLE
After a few hours of inactivity, The screen looks like a broken color TV. #Ubuntu 20.04

### ISSUE THREAD

**Issue by RusimbiP** [ubuntu/yaru#2250]
## Expected Behavior
N/A

## Actual Behavior

After a few hours of inactivity, The screen looks like a broken color tv
![issue](https://user-images.githubusercontent.com/54870069/87210231-20c91500-c315-11ea-93b9-1d1489f420ee.png)

## Steps to Reproduce the Problem

  1. Leave your screen for a few hours
  1. Revisit and checkout a chrome tab or Vs code
  1.

## Software that presents the issue

- Name: Ubuntu 20.04
- Version:

## Yaru version

Please report the Yaru version in your system using one of the following commands

* If you installed Yaru from PPA

    `$ apt show communitheme`

* If you installed Yaru via Snap

    `$ snap info communitheme`

* I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

## Icon Request

If you're filing an issue for a missing icon provide the following in your request:

- If it is an application, the file name of the icon used (can be found in the `Icon=` field in an app's `.desktop` file)
- If it is a file type icon, such as "JSON icon" please include its media type (can be found in a file's Properties dialog, e.g. `text/x-css`)
- If possible provide a screenshot, link-to, or copy of a related icon or logo.

Thanks!

**Comment by clobrano** [comment]
Hi @RusimbiP, thanks for taking time to report the issue, but this is hardly due to Yaru. It might be more a bug between a driver and the suspend feature.
You might find more help to identify the culprit in an Ubuntu forum

https://ubuntu.com/support/community-support

**Comment by RusimbiP** [comment]
Thanks!!
