### ISSUE TITLE
Make core symbols more Yaru?

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#2254]
Some of the most core symbols (like documents and images) are very square and don't quite match the rest of the set.  I wonder if anyone would be interested in us revising them to match the others, as follows:

![image](https://user-images.githubusercontent.com/38893390/87241943-07f95600-c420-11ea-879c-0674c3a03927.png)

??

**Comment by Jupiter007-43** [comment]
Square angles have always seemed strange for me.

**Comment by Muqtxdir** [comment]
Hi,

If the documents and images (symbol) is being changed, will Folder-documents and Folder-pictures Pictogram also be revised to this new-change as well ?

**Comment by Jupiter007-43** [comment]
I think @ubuntujaggers will do it in the same time.

**Comment by ubuntujaggers** [comment]
Yep, they'll be made to match 👍

**Comment by Jupiter007-43** [comment]
@ubuntujaggers I think this issue should be closed as you merged the PR (#2283) 😉
