### ISSUE TITLE
Missing display settings icons

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2257]
## Actual Behavior

![Capture d’écran du 2020-07-15 19-43-56](https://user-images.githubusercontent.com/36476595/87577668-8b8e9d80-c6d3-11ea-953b-5842799f7865.png)

😱 In addition Adwaita's ones look blurry...

I've already test to replace one icon:

![Capture d’écran du 2020-07-15 19-16-06](https://user-images.githubusercontent.com/36476595/87577739-a6611200-c6d3-11ea-93ba-f6ed09dfdb96.png)

Icons names are: **video-joined-displays-symbolic**, **view-mirror-symbolic** and **video-single-display-symbolic**.
These are 24px icons.

**Comment by Jupiter007-43** [comment]
These icons are 16px but Settings upscale them to 24px (that's why they look blurry). Should I create 24px (like in my screenshot upper) or 16px icons?

**Comment by Feichtmeier** [comment]
I think this question goes out to @ubuntujaggers =)

**Comment by Jupiter007-43** [comment]
Yep!

**Comment by Feichtmeier** [comment]
If you don't want to wait, you can just commit both - but shouldn't those be scalable/symbolic icons anyways? :thinking:

**Comment by Jupiter007-43** [comment]
Although being scalable, a vectorial image must be aligned on a grid which is like the pixel of a matrix image. So a pixel perfect 16px icon will looks blurry if it's upscale to 24px (but looks good at 32px because it is a multiple of 16)...
I hope I'm clear. I'm not a vector image expert at all, so if I say stupid things tell me @ubuntujaggers. 😉

**Comment by Jupiter007-43** [comment]
In fact it is impossible to add 24px icon, it render a black square:

![Capture d’écran du 2020-07-17 19-42-37](https://user-images.githubusercontent.com/36476595/87815576-20c19b80-c866-11ea-8696-a000995b05a1.png)

So they'll still look blurry... 😰
I think I'll open an issue for that on Settings repo.

**Comment by Feichtmeier** [comment]
While you work on this, as a notebook + external display user, I've always found the third option "use internal display" to be badly represented by a monitor - don't you think? I think we should eihter use a display without a stand or a notebook display :thinking:

**Comment by Jupiter007-43** [comment]
🤔 The last button is an option to enable just one screen. I don't think it is just for the internal display (I use it daily for free my second screen for playing with my NS). So in my opinion the monitor is a good icon. Personally I was thinking to use the video-display icon:

![Capture d’écran du 2020-07-17 19-59-12](https://user-images.githubusercontent.com/36476595/87816665-0092dc00-c868-11ea-9055-36da78e9e1ae.png)

By the way the icon name is video-single-display.
But let's ask the others to see what they think about this.

**Comment by Jupiter007-43** [comment]
A first look:

![Capture d’écran du 2020-07-17 20-06-25](https://user-images.githubusercontent.com/36476595/87817307-05a45b00-c869-11ea-88a0-4ee7f2b8f3f2.png)

**Comment by Jupiter007-43** [comment]
@ubuntujaggers I was thinking to put them into the Status layer?

**Comment by Jupiter007-43** [comment]
And with the notebook icon:

![Capture d’écran du 2020-07-17 20-19-40](https://user-images.githubusercontent.com/36476595/87818473-1f8a7180-c85a-11ea-89d4-ebfcfa6f942b.png)

**Comment by Feichtmeier** [comment]
The question is: does the text of the third button change depending on what your setup is?
Like... you connect a 2. monitor to your laptop it says "internal display"?

If you press "windowskey + P" you can cycle through the options again:
![grafik](https://user-images.githubusercontent.com/15329494/87819424-8153d700-c86c-11ea-9055-ecc4cf40531b.png)
It's german... it says
Mirror | Arange screens together | only external | only internal

**Comment by Jupiter007-43** [comment]
Sorry I didn't understand...
I don't have a laptop, just a desk computer with two screen. But when I press "Super + P" it looks exactly like you with the same text (in French 😉).
However I can't found the name of the last icon because it does not appear on the .ui file (https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/display/cc-display-panel.ui).

**Comment by Jupiter007-43** [comment]
I just realized that she's using the computer icon. So we can't modify it without altered the computer icon. I'm sorry 😓
