### ISSUE TITLE
Enhance the current curl or add a paper fold on file icons

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2268]
**This issue is for discussing enhancing curl at the bottom of the mimetype icons or adding a paper fold at the top!**

![image](https://user-images.githubusercontent.com/3986894/88099319-4e2a8400-cb9b-11ea-845a-317a02830904.png)
_Enhanced, Fold and current_ 👆 

For a long time now, I've found the paper curl at the bottom of the mimetype icons to be too subtle. At the moment, the current curl is only present at 256 px (and above ofc). 
The fold would be a clear distinction between the application and file icons.

Adding the top fold, is a very controversial suggestion and it's also a massive amount of work to adapt the current 54 icons. A less intrusive suggestion is to increase the current curl.

In no particular order, here's document icons from OSX, Windows, Humanity, Adwaita, Papirus and Yaru 📄 

![image](https://user-images.githubusercontent.com/3986894/88096590-2fc28980-cb97-11ea-8a0e-db49ec71dabd.png)

**Comment by clobrano** [comment]
This is a nice idea. My preference would go to a neat fold, like the examples in the third column :+1:

**Comment by Feichtmeier** [comment]
I'd prefer to not change the base plate do I'd go with option 1

**Comment by ubuntujaggers** [comment]
If we wanted to try an actual fold, we could take the shape of the folded corner (and very well executed shadow!) from this:

![image](https://user-images.githubusercontent.com/38893390/88970339-2679a100-d2aa-11ea-95a2-906f1971c505.png)

(Minus the black behind it.)

**Comment by ubuntujaggers** [comment]
Guys - do we want a test branch to try the folded corner?

**Comment by madsrh** [comment]
> do we want a test branch to try the folded corner?

That would be great but also a ton of work for you, just to test this

**Comment by ubuntujaggers** [comment]
I actually really like this!  I've done the backplate for 48px and tried a few out:

![image](https://user-images.githubusercontent.com/38893390/94853143-d8585980-0422-11eb-814d-183b3a4ad136.png)

**Comment by Jupiter007-43** [comment]
This looks really good!

**Comment by ubuntujaggers** [comment]
Suggested backplate at all five sizes:

![image](https://user-images.githubusercontent.com/38893390/94945277-59baf500-04d2-11eb-9ae2-061b8fa68b86.png)

**Comment by Feichtmeier** [comment]
Do it @ubuntujaggers ;)

**Comment by ubuntujaggers** [comment]
WIP:

![image](https://user-images.githubusercontent.com/38893390/95017097-14700200-064f-11eb-87c9-a7fd5058683c.png)
