### ISSUE TITLE
Missing mimetype icon: .dart

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2272]
![grafik](https://user-images.githubusercontent.com/15329494/88223129-459f7f80-cc67-11ea-8fff-11c31f11f888.png)

![grafik](https://user-images.githubusercontent.com/15329494/88223237-6a93f280-cc67-11ea-92e7-9db0c816008f.png)

Missing .dart mimetype. Dart is used in Flutter
https://flutter.dev/docs/cookbook/networking/fetch-data

**Comment by madsrh** [comment]
I actually tried this yesterday, but it's no recognized :/

I'll post screenshots later

**Comment by madsrh** [comment]
@didrocks are you still on holiday? 😄 🌴 ⛱️ 🌞 

Could you help adding the support for the .dart filetype on the Ubuntu side?

**Comment by madsrh** [comment]
I'll close this issue here since the missing support isn't a Yaru issue 👼

**Comment by madsrh** [comment]
@Feichtmeier it's still lacking support for the .dart filetype on the Ubuntu side, right? 🤔  The mimetype icon is there

![image](https://user-images.githubusercontent.com/3986894/107831417-51cb6580-6d8e-11eb-858b-bb8c6a697731.png)
