### ISSUE TITLE
Missing mimetype: maven XML files

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2278]
![grafik](https://user-images.githubusercontent.com/15329494/88433417-4f0f2000-cdfe-11ea-9e79-c84822225d57.png)
I think symlinking them to normal XML files would be enough though :) 
Maven is used in java projects to pull dependencies and export your code into a specific format and so on (basically the whole lifecycle)

**Comment by madsrh** [comment]
I'm **+1** for symlinking (as long as someone else does it 😄 )

BUT we could also do something like this, based on the colors of the logo: (quick mockup)
![image](https://user-images.githubusercontent.com/3986894/88435238-1709dc00-ce02-11ea-8027-25882259ef37.png)

**Comment by Feichtmeier** [comment]
That looks neat, nice gradient

**Comment by madsrh** [comment]
Really?

This gradient might fit better with the logo. Shall I create PR or is the symlink "safer"?

![image](https://user-images.githubusercontent.com/3986894/88437141-20954300-ce06-11ea-9569-b96d6bbabbc1.png)

**Comment by Feichtmeier** [comment]
I think it looks cool :shrug: :smile_cat:
