### ISSUE TITLE
Problem installing Yaru Theme from source on Ubuntu 18.04

### ISSUE THREAD

**Issue by sardus-X** [ubuntu/yaru#2285]
Some time ago, unfortunately not having read the warnings in your README.md file (Installing from source is not recommended for average usage), I tried to install from the sources your new beautiful "20.04" Yaru theme on my Ubuntu 18.04 system, by running these commands:
`sudo apt install git meson sassc libglib2.0-dev libxml2-utils`
`git clone https://github.com/ubuntu/yaru`
`cd yaru`
`meson build`
`cd build`
`sudo ninja install`
it seemed that everything was successful but later I noticed some problems, as shown in these images:
![immagine](https://user-images.githubusercontent.com/29210004/88555957-bd372b00-d028-11ea-84f9-f045292511eb.png)
![immagine](https://user-images.githubusercontent.com/29210004/88556008-ccb67400-d028-11ea-96ca-fe0131b9d222.png)
how could this problem be corrected or, alternatively how can I (sigh!) completely uninstall the theme from my system?

**Comment by Jupiter007-43** [comment]
🤔 I'm not sure, but it must be because the dialog boxes have changed with 20.04.

**Comment by Feichtmeier** [comment]
The shell theme does not work on 18.04 build from master
Either build from bionic branch
Or better install the communitheme snap

**Comment by Muqtxdir** [comment]
Hi @sardus-X ,
>  alternatively how can I (sigh!) completely uninstall the theme from my system?

### To remove  **Yaru**:
- To remove all Yaru, first simply run the following in terminal (although some files won't be deleted succesfully)

```
   cd yaru
   cd build
   sudo ninja uninstall
```
- The remaining can be removed by doing this:
```
# This will delete all gnome-shell-theme-folders named Yaru, Yaru-dark
sudo rm -R /usr/share/gnome-shell/theme/Yaru*

# This will delete all GTK3-theme-folders named Yaru, Yaru-light, Yaru-dark
sudo rm -R /usr/share/themes/Yaru*

# This will delete icon-folder named Yaru
sudo rm -R /usr/share/icons/Yaru

# This will delete sound-folder named Yaru
sudo rm -R /usr/share/sounds/Yaru
```

**Comment by Muqtxdir** [comment]
**To install Yaru on Ubuntu 18.04 (from README):**
- To install Yaru (as snap) , simply run the following in terminal:
```
snap install communitheme
```
- Restart your computer
- Click on your user, click on the gear icon and select the "Ubuntu with communitheme snap" session from the pop-up, and login
- Now Ubuntu is using the communitheme including the system, applications, icons, sounds and the cursor.

**Comment by Feichtmeier** [comment]
Thanks @Muqtxdir for the nice rescue instructions!
