### ISSUE TITLE
Rounding some more symbolic icons

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2296]
I propose to rounding the corners of these icons to stay consistent with the other icons from #2283, like this:

mail-drafts and mail-drafts-rtl:

![Capture d’écran du 2020-07-29 15-25-18](https://user-images.githubusercontent.com/36476595/88805684-bf77c180-d1af-11ea-9f8e-1cf472b527b0.png)

insert-image:

![Capture d’écran du 2020-07-29 15-26-01](https://user-images.githubusercontent.com/36476595/88805736-d3232800-d1af-11ea-8305-c7b1b370d97d.png)

document-new:

![Capture d’écran du 2020-07-29 15-26-21](https://user-images.githubusercontent.com/36476595/88805785-e1714400-d1af-11ea-9430-f8f353984fc5.png)

and document-page-setup:

![Capture d’écran du 2020-07-29 15-27-04](https://user-images.githubusercontent.com/36476595/88805848-f77f0480-d1af-11ea-837a-6b0cd48e4a1b.png)

What do you think of @ubuntujaggers?

**Comment by ubuntujaggers** [comment]
Yep, fully agree 👍
