### ISSUE TITLE
Adding Virtualbox mimetypes

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2305]
Related to #2271

### Todo list

- [x] x-virtualbox-vbox
- [x] x-virtualbox-vbox-extpack
- [x] x-virtualbox-ova
- [x] x-virtualbox-ovf

Disk mimetypes:
- [x] x-virtualbox-vdi
- [x] x-virtualbox-vhd
- [x] x-virtualbox-vmkd
- [x] x-virtualbox-hdd

**Comment by Jupiter007-43** [comment]
A proposal for all disks mimetypes:

![Capture d’écran du 2020-08-02 20-03-58](https://user-images.githubusercontent.com/36476595/89129219-e90c5200-d4fb-11ea-8a24-1dbe571d8031.png)

Or maybe adding an accent color corresponding to the file type:

![Capture d’écran du 2020-08-02 20-03-42](https://user-images.githubusercontent.com/36476595/89129232-017c6c80-d4fc-11ea-843c-e39b64f9a7c8.png)

**Comment by Jupiter007-43** [comment]
Another idea should be to use this model:

![Capture d’écran du 2020-08-02 20-20-30](https://user-images.githubusercontent.com/36476595/89129436-e0604f80-d4ec-11ea-9cfb-d876a243a1ac.png)


This for all icons and just changing the text below the pictogram (and the background color) to fit the mimetype.

**Comment by madsrh** [comment]
Nice 👍 I prefer the second version 〽️
Perhaps use blue for the background like they have in their logo? https://www.virtualbox.org/

I wonder if changing the background for each type is a bit too much IDK

**Comment by Jupiter007-43** [comment]
In fact I'd like to add different background color to clearly differentiate them like with the hicolor icons (also like archives icons):

![Capture d’écran du 2020-08-02 20-26-52](https://user-images.githubusercontent.com/36476595/89129579-f1f62700-d4ed-11ea-85e3-a939984811e8.png)

But if you think it's not a good idea I'm ok for adding blue background 🤷

**Comment by madsrh** [comment]
Ahh, I see. Let's try that

**Comment by Jupiter007-43** [comment]
One more screenshot:

![Capture d’écran du 2020-08-03 14-28-42](https://user-images.githubusercontent.com/36476595/89182237-aac37100-d595-11ea-89d0-e4ae7e1e7666.png)
