### ISSUE TITLE
Yaru-Dark Not working properly on gnome-logs and gnome-boxes

### ISSUE THREAD

**Issue by raushankumar27** [ubuntu/yaru#2306]
Yaru-Dark not working properly on gnome-logs and gnome -boxes
OS: Ubuntu Groovy Gorilla (development branch)
Gnome : 3.36.4

Gnome logs
![image](https://user-images.githubusercontent.com/9436987/89129747-672d2080-d51d-11ea-8c2a-221bbb88b7fa.png)
![image](https://user-images.githubusercontent.com/9436987/89129767-9d6aa000-d51d-11ea-99a2-1ccdc7cc972e.png)

Gnome-boxes
![image](https://user-images.githubusercontent.com/9436987/89129785-d7d43d00-d51d-11ea-9410-0ddeaebfb641.png)

**Comment by madsrh** [comment]
Hi @raushankumar27 

Thanks for taking the time to open this issue. Could you post the same screenshots with Adwaita dark?

**Comment by raushankumar27** [comment]
Similar issue is also present with With Adwaita dark
gnome-logs
![image](https://user-images.githubusercontent.com/9436987/89130095-d99f0000-d51f-11ea-92cd-f761249a6e07.png)

gnome -boxes
![image](https://user-images.githubusercontent.com/9436987/89130110-fa675580-d51f-11ea-8247-25c886d1dfe7.png)

**Comment by madsrh** [comment]
I suspected that. It means it's an upstream issue, so you need to create a bug on https://gitlab.gnome.org/GNOME

Is there anything else we can do here @Feichtmeier / @clobrano ?

I'll close the issue here (comments still open)

Thanks again @raushankumar27

**Comment by clobrano** [comment]
They'll probably say that dark is not supported on these apps, and to fix ourselves, but the right thing is to open a but upstream I think

**Comment by raushankumar27** [comment]
Created a upstream bug: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3039
