### ISSUE TITLE
Where is th code for dark LibreOffice theme.

### ISSUE THREAD

**Issue by MahdiBaghbani** [ubuntu/yaru#2307]
Hi, I'm also trying to develop a theme base on adwaita

I can see yaru is modifying LibreOffice theme for dark theme which is an improvement over adwaita.

But I can't find the cod in repository, can someone point to LibreOffice css section? Thanks!

Adwaita-Dark LibreOffice
![adwaita-dark](https://user-images.githubusercontent.com/13681688/89130632-ace8e980-d51b-11ea-8eb1-5022feb6d19b.png)

Yaru Dark LibreOffice
![yaru-dark](https://user-images.githubusercontent.com/13681688/89130643-cd18a880-d51b-11ea-8f8d-3d70e3368efd.png)

**Comment by madsrh** [comment]
Actually @Jupiter007-43 has been working hard to create a fullcolor version of the Yaru theme for Libreoffice!

https://launchpad.net/~hellsworth/+archive/ubuntu/libreoffice5/+packages

https://github.com/Jupiter007-43/libreoffice-style-yaru-fullcolor

I'll close this "Where is th code for dark LibreOffice theme" issue, but comments are still open 😃

**Comment by Jupiter007-43** [comment]
The only reference to Libreoffice into the code (Gtk2 so not css) is here: https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-2.0/hacks.rc#L36
