### ISSUE TITLE
Improve progress bar constrast on dark theme

### ISSUE THREAD

**Issue by otavioschwanck** [ubuntu/yaru#2308]
The progress bar on dark theme is hard to see.

![image](https://user-images.githubusercontent.com/9551316/89142441-d145c580-d51d-11ea-9483-5cb06cf2d5c4.png)

![image](https://user-images.githubusercontent.com/9551316/89142542-136f0700-d51e-11ea-8013-9c514aafcaab.png)

On yaru from 19.10, the light blue color are far best from the current (in dark variant at least)

**Comment by Feichtmeier** [comment]
Duplicate of #2214

**Comment by Feichtmeier** [comment]
Missclicked ... XD
