### ISSUE TITLE
Ubiquity icon suggestion

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#2319]
I loved the icon concept but wasn't able to draw a brilliant version.  Unless @Jupiter007-43 fancies a go at doing the pixels concept...  how about this:

![ubiquity suggestion](https://user-images.githubusercontent.com/38893390/89783649-36497e80-db0f-11ea-8c09-d5de93c6f3c2.png)

Tested using Sudoku app:

![image](https://user-images.githubusercontent.com/38893390/89783671-3fd2e680-db0f-11ea-80c5-98369a61321c.png)

![image](https://user-images.githubusercontent.com/38893390/89783685-43ff0400-db0f-11ea-9f79-16cafa64bb21.png)

Mockup of live disk desktop:

![image](https://user-images.githubusercontent.com/38893390/89783701-4b261200-db0f-11ea-9959-35c4e9085d13.png)

???

**Comment by Jupiter007-43** [comment]
I love this concept 😍
How does it look at small size?

**Comment by Jupiter007-43** [comment]
I'm stupid there's already a picture with small size above. 😅

**Comment by Feichtmeier** [comment]
Looks really good Stuart

**Comment by Feichtmeier** [comment]
The only concern that might come up is that that Ubuntu thing draws on a disk and could be misunderstood as burn an Ubuntu cd

**Comment by Jupiter007-43** [comment]
> The only concern that might come up is that that Ubuntu thing draws on a disk and could be misunderstood as burn an Ubuntu cd

That's right!
@ubuntujaggers can you try to replace the CD with a HDD?

**Comment by ubuntujaggers** [comment]
Hi guys,

Something like this:

![image](https://user-images.githubusercontent.com/38893390/90550209-8667b700-e187-11ea-9261-a1587597fca8.png)

?

**Comment by Jupiter007-43** [comment]
Much better with the hdd 👍

**Comment by ubuntujaggers** [comment]
Okay, I'll do a PR of this as soon as I have chance 👍

**Comment by Feichtmeier** [comment]
I think this one should be really backported to 20.04 (don't tell my wife) - big improvement
