### ISSUE TITLE
Low contrast on indicator of multiple windows

### ISSUE THREAD

**Issue by sagcan** [ubuntu/yaru#2320]
Currently the indicator that multiple windows of the same applications are open inside the application switcher has a very low contrast and as such is _almost_ impossible to see. Hence I'm wondering if you guys would be open to update the color of said indicator? For reference here are two screenshots (indicator at the bottom of the Chrome icon):   

a) Default:
![switcher](https://user-images.githubusercontent.com/29666622/89904345-18504c80-dbe9-11ea-8399-c9c6f63786c0.png)

b) Updated:
![switcher-updated](https://user-images.githubusercontent.com/29666622/89904422-3322c100-dbe9-11ea-99b1-6bbb45a9f66f.png)

The Yaru version would be `20.04.7` according to `apt show yaru-theme-gnome-shell`. 

p.s. Thanks for all the hard work on Yaru, the theme looks sick as fuck ;]

**Comment by Jupiter007-43** [comment]
🤔 Strange, on my computer, the indicator is an orange dot:

![Capture d’écran du 2020-08-11 15-48-02](https://user-images.githubusercontent.com/36476595/89905430-77629100-dbea-11ea-80be-1a3df12d5aad.png)

**Comment by sagcan** [comment]
Whoops, sorry I thought application switcher == `Alt + Tab` or rather `Super + Tab`

**Comment by Feichtmeier** [comment]
Agreed!

**Comment by clobrano** [comment]
On my system it's quite visible

![image](https://user-images.githubusercontent.com/2883614/90157385-f5ab6880-dd8d-11ea-9a0b-738350f4da0a.png)

**Comment by Jupiter007-43** [comment]
Very nice wallpaper @clobrano 😉

Even stranger, on my computer it looks like @sagcan (look at under nautilus icon), are you using 20.04:

![Capture d’écran du 2020-08-13 18-34-13](https://user-images.githubusercontent.com/36476595/90161751-e3ccc400-dd93-11ea-80cb-cacf86be1465.png)

Is that arrow an icon or hard coded in css?

**Comment by clobrano** [comment]
I might have Yaru's master installed currently. If that so, the problem is fixed already even if I don't remember any specific bugfix from upstream. 
@Jupiter007-43  do you have stock Yaru?

**Comment by Jupiter007-43** [comment]
> @Jupiter007-43 do you have stock Yaru?

Yes, I'm using gnome-shell theme from apt.
On Adwaita session, the arrow is much brighter just like on your screenshot.

I also tested Yaru master, and there is the same problem.

**Comment by clobrano** [comment]
> I also tested Yaru master, and there is the same problem.

this worries me, since I am always on master and I don't have it. I wonder if it is due to some combination of sw version :thinking:

**Comment by Feichtmeier** [comment]
I think the problem is the default shell (light) where I can reproduce this issue with the SUPER + tab switcher (with the alt + tab switcher, the windwos are not gathered in a group):
... super+tab cycles through all apps, on all workspaces:

![grafik](https://user-images.githubusercontent.com/15329494/91015530-8e8e7f00-e5eb-11ea-817d-7fbe1143cd0e.png)

When using the dark yaru shell with user-themes, this little arrow is perfectly white, so I guess they do not use osd_fg_color here:

![grafik](https://user-images.githubusercontent.com/15329494/91015627-bbdb2d00-e5eb-11ea-8b51-b1aaedbf6fa1.png)

**Comment by Feichtmeier** [comment]
Yep, here we go :roll_eyes: 

https://github.com/ubuntu/yaru/blob/c1d7a55ba36e6ef287f3e75198a2082a97a8f5b5/gnome-shell/src/gnome-shell-sass/widgets/_switcher-popup.scss#L51

**Comment by clobrano** [comment]
of course :facepalm: I have the dark shel

**Comment by DoctorRover** [comment]
Just in case, I confirm that the issue vanishes if Yaru-dark shell them is activated.

**Comment by sagcan** [comment]
Out of curiosity, when can we expect those changes to land on the official Ubuntu repository?

**Comment by clobrano** [comment]
Officially, this might land in 20.10, but I do not know the plans to update LTS, though

**Comment by sagcan** [comment]
I'd much appreciate if this somehow lands in 20.04 :p 
Coming from Arch Linux, Ubuntu sometimes is a PITA regarding the update policy (which is totally understandable as it should be stable but still)

**Comment by clobrano** [comment]
> I'd much appreciate if this somehow lands in 20.04 :p
> Coming from Arch Linux, Ubuntu sometimes is a PITA regarding the update policy (which is totally understandable as it should be stable but still)

Then you might find https://github.com/wimpysworld/rolling-rhino very interesting :)
