### ISSUE TITLE
snap-logo on snap-folder 

### ISSUE THREAD

**Issue by fouzan14** [ubuntu/yaru#2322]
## Icon Request

 Idk whether this is needed, but still request for Icon of snap-folder (icon-emblem) in home directory from [omgubuntu](https://www.omgubuntu.co.uk/2020/06/snap-folder-icon-emblem) article
something like this 👇
![small-change-snap-folder](https://user-images.githubusercontent.com/69529058/89926704-db08b080-dc22-11ea-9a12-86c527beabf9.jpg)

Thank-you

**Comment by madsrh** [comment]
Hi @fouzan14 
Thank you for taking the time to create this issue (now that Joey couldn't find the time 😉 )

We can "easily" add an icon to the folder, but IMHO we shouldn't. There's actually nothing in the folder the average user needs to access. We would prefer the folder to be hidden or moved, but that's not technically possible atm.

**Comment by Jupiter007-43** [comment]
Hi @fouzan14,
if you want to hide this folder (that I did on my computer), you just had to create a `.hidden` file into your home folder and just put this inside:
```
snap
```

By the way, I think this should be set by default...

**Comment by Jupiter007-43** [comment]
There is a Lunchpad bug for this:
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1575053

**Comment by Jupiter007-43** [comment]
> There's actually nothing in the folder the average user needs to access.

In fact, this folder could be used by confined apps for saving data when you don't allow it to access to your Home folder. It is the fallback Home for snap apps.

So imo, as this folder is present on **every** new install by default, I think we should considering to add an emblem on it (even if it's just a patch awaiting a real solution from snapd devs).

**Comment by madsrh** [comment]
> So imo, as this folder is present on every new install by default, I think we should considering to add an emblem on it...


👍 Let's do that. Did you just assign yourself there @Jupiter007-43? 😅

**Comment by fouzan14** [comment]
hey, just wanted to ask the icon-name for snap-folder is it like **folder-snap**? or something else? (to name in the svg)
![snap-emblem](https://user-images.githubusercontent.com/69529058/90802320-b43e2e80-e334-11ea-947f-9e60dfb9f41b.png)

**Comment by Jupiter007-43** [comment]
In fact it's a bit more complicated. I've already tried to create an icon named **folder-snap** and another named **snap-folder**.
But as snap don't provide an icon for this folder we cannot (for the moment) override it and put a pictogram.
We are currently looking for a solution, I'll keep you informed. 🙂

**Comment by ubuntujaggers** [comment]
I think we can close this after consultation with Popey because the folder itself will be hidden?
