### ISSUE TITLE
Ubuntu 20.04 topbar context menu text overlapping

### ISSUE THREAD

**Issue by prashanthbabu07** [ubuntu/yaru#2323]
This context menu shows overlapping text:

![gnome_menu_overlapping](https://user-images.githubusercontent.com/819230/90254394-48edeb80-de60-11ea-84e2-69fc58794614.png)

**Comment by madsrh** [comment]
That does look weird @prashanthbabu07 
Could you post the same screenshot using the Adwaita theme?

**Comment by prashanthbabu07** [comment]
@madsrh  - With long text breaks the menu

![Screenshot from 2020-08-14 19-12-05-good](https://user-images.githubusercontent.com/819230/90255809-69b74080-de62-11ea-951c-786f0e9c420b.png)


![Screenshot from 2020-08-14 19-12-49-bad](https://user-images.githubusercontent.com/819230/90255802-6754e680-de62-11ea-953f-f6bc68deb77a.png)

**Comment by prashanthbabu07** [comment]
On Gnome tweaks when I change "Shell" in Appearance anything other than "Default" this issue occurs.

**Comment by Feichtmeier** [comment]
@prashanthbabu07 is this a normal 20.04 yaru or did you install it from master?

**Comment by prashanthbabu07** [comment]
After updating with Complete-Yaru-Colors-20.04.5.tar.xz the issue is resolved. closing the issues.

**Comment by clobrano** [comment]
> @Feichtmeier - After updating with Complete-Yaru-Colors-20.04.5.tar.xz the issue is resolved. closing the issues.

This package doesn't seem to come from us. Whjat is the source?

**Comment by prashanthbabu07** [comment]
@clobrano - Below is the source.
https://github.com/Jannomag/Yaru-Colors
