### ISSUE TITLE
Icon Request: Disk Standby Icon for gnome-disk-utility

### ISSUE THREAD

**Issue by countingpine** [ubuntu/yaru#2324]
In Ubuntu 18.04, the icon for a sleeping disk is a sort of "ZZZ" icon (/usr/share/icons/hicolor/scalable/apps/gnome-disks-state-standby-symbolic.svg)
In 19.10 and 20.04, the sleeping disk is now accompanied by the main application icon (/usr/share/icons/Yaru/scalable/apps/org.gnome.DiskUtility-symbolic.svg, or possibly one of a handful of similarly named but identical SVGs).

See also this [Ask Ubuntu question](https://askubuntu.com/questions/1226490/what-does-this-icon-in-disk-utility-mean) and this [gnome-disk-utility issue](https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/180).

The Ask Ubuntu thread provides examples of both icons, but I can probably find and attach the SVGs if helpful.

(Apologies if this issue is posted in the wrong place or lacking crucial information.)

**Comment by Jupiter007-43** [comment]
Hi @countingpine,
thanks very much for reporting that.
The **gnome-disks-state-standby** symbolic icon is indeed missing into Yaru.
I'll try add it then sleep my external disk.

**Comment by Jupiter007-43** [comment]
The upstream icon is here:
https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/blob/master/data/icons/hicolor/scalable/apps/gnome-disks-state-standby-symbolic.svg
