### ISSUE TITLE
Missing icon .patch files (text/x-patch)

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2341]
Mimetype **text/x-patch** (.patch and .diff)

A proposal icon:

![Capture d’écran du 2020-09-01 13-10-38](https://user-images.githubusercontent.com/36476595/91842587-9b971800-ec54-11ea-9a85-5632cf07c566.png)

Related to #2334

**Comment by Jupiter007-43** [comment]
![Capture d’écran du 2020-09-16 20-00-27](https://user-images.githubusercontent.com/36476595/93374704-60513780-f857-11ea-8a76-399953dd47b6.png)

PR?

**Comment by Jupiter007-43** [comment]
Another idea should be just the red and green lines:

![Capture d’écran du 2020-09-16 20-06-05](https://user-images.githubusercontent.com/36476595/93375213-246aa200-f858-11ea-89f3-7323bb8d58c4.png)

**Comment by madsrh** [comment]
> PR?

IMO, Yes please 😀

This looks good @Jupiter007-43 
I wonder if a slightly dark color for the patch would work better, but I can test that myself if you make the PR ;)

**Comment by Jupiter007-43** [comment]
10% darker:

![Capture d’écran du 2020-09-16 20-27-53](https://user-images.githubusercontent.com/36476595/93377313-24b86c80-f85b-11ea-8c8e-1cf1703c718f.png)

The PR use the first colors.
