### ISSUE TITLE
Missing symlinks: gnome-dev-disk-dvd-*

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2351]
![grafik](https://user-images.githubusercontent.com/15329494/93050881-ef95f980-f663-11ea-992a-ac0801230678.png)
(left side wrong DVD icon, right side a normal yaru CD icon)

I am pretty sure we have an icon for this, just missed some symlinks. List is this, could be partially complete, need to check:

- [ ] gnome-dev-disk-dvdr
- [ ] gnome-dev-disk-dvdrw
- [ ] gnome-dev-disk-dvdram
- [ ] gnome-dev-disk-dvdrom
- [ ] gnome-dev-disk-dvdr-plus

edit: this icon is used when you are in a gnome-boxes VM

**Comment by Jupiter007-43** [comment]
@Feichtmeier Where did you found the icons names?

**Comment by Feichtmeier** [comment]
I searched in the humanity icons because the icon in the dock is clearly a humanity icon :)
When I say humanity I mean humanity+ubuntu-mono-dark

It must be just one missing symlink
