### ISSUE TITLE
Missing symbolic icons for Gnome-screenshot 3.38

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2352]
Gnome-screenshot is coming with a new UI with the 3.38 version and all icons are missing in Yaru:

![Capture d’écran du 2020-09-16 19-22-30](https://user-images.githubusercontent.com/36476595/93371747-1fefba80-f853-11ea-92de-648fde215fea.png)

Icons name are:
- display-symbolic
- window-symbolic
- selection-symbolic

**Comment by ubuntujaggers** [comment]
Good spot!

**Comment by Jupiter007-43** [comment]
🤔 In which folder should I put these icons, **/devices** for **display-symbolic** but I really don't know which one to choose for the other two.

**Comment by Feichtmeier** [comment]
I would say actions

**Comment by Jupiter007-43** [comment]
> I would say actions

That's I did, thanks.
