### ISSUE TITLE
Some Gnome 3.37 apps have unrounded headerbar corners

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2355]
Ubuntu 20.10
Gnome 3.37

**Gnome-screenshot:**

![Capture d’écran du 2020-09-19 18-57-00](https://user-images.githubusercontent.com/36476595/93672284-0ac09900-faaa-11ea-88b2-856f9db8d2e8.png)

Adwaita not affected.

**Comment by Feichtmeier** [comment]
Also found in geary preferences
![grafik](https://user-images.githubusercontent.com/15329494/93707045-e3aaab80-fb2b-11ea-91ca-9de832ae8284.png)
