### ISSUE TITLE
Default theme does not have the correct bg color for gnome disk analyser

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2358]
![grafik](https://user-images.githubusercontent.com/15329494/93706763-04720180-fb2a-11ea-9c3e-7720d484f2ee.png)

Light/dark works
![grafik](https://user-images.githubusercontent.com/15329494/93706777-181d6800-fb2a-11ea-9ecf-d17492384212.png)
![grafik](https://user-images.githubusercontent.com/15329494/93706779-210e3980-fb2a-11ea-8dc5-dc6335d30923.png)

**Comment by madsrh** [comment]
> Light/dark works

I see what you did there 😜

**Comment by Feichtmeier** [comment]
hehe, nono tried some stuff but.... https://gitlab.gnome.org/GNOME/baobab/-/blob/master/data/baobab.css#L74
: / Theme's bg color us used in in app css, which is actually even the correct way to do it.... but in yaru default headerbar bg color != bg color

**Comment by Feichtmeier** [comment]
So either someone needs to bite into the sour apple (lol, German saying) and create an issue on their repo, to ask how we can overwrite this. Any volunteers who have nothing to lose? 
@madsrh ?

**Comment by madsrh** [comment]
🙈

**Comment by Feichtmeier** [comment]
@Jupiter007-43 since you seem quiet experienced with SCSS could you try if you find a smart way of overwriting the header bar inside _headerbar.scss ?
Currently there is just the whole section copied plus iterating over the button states
I know nana-4 did something like this in the past or maybe it was carlo in yaru-1.0 but I was always unhappy with my solution in _headerbar.scss
I don't think this will fix this issue anyhow, since the problem is the hardcoded, priorizied app-specific widget css for this app, but yet it solves some of my headache around the inverted headerbar in a **light** theme you all love so much :alien:

**Comment by Jupiter007-43** [comment]
I'll try to have a look 😄

**Comment by Feichtmeier** [comment]
Fixed with #2922
