### ISSUE TITLE
Log mimetype 48px size border is too strong

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2372]
![grafik](https://user-images.githubusercontent.com/15329494/94555735-51598480-025c-11eb-816c-b29718982a87.png)

Compared to the other "document"-style mimetypes

**Comment by ubuntujaggers** [comment]
Looks like the paper is a bit greyer than the others too - just a case of cloning a white one and adding the pictogram 👍

**Comment by ubuntujaggers** [comment]
This one was resolved when we added the corners :+1:
