### ISSUE TITLE
Design idea

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2373]
With the flat buttons the relatively strong shadow looks a bit too much in my opinion.
Also I've found that swapping selection fg and bg color reduces the jarring of the orange a lot and gives all three themes a "fresh" vibe?

What do you think @clobrano @madsrh @ubuntujaggers @Jupiter007-43 ?
:wastebasket: or :+1: ? 

![grafik](https://user-images.githubusercontent.com/15329494/94558884-badb9200-0260-11eb-966c-d6f5487fbd98.png)

![grafik](https://user-images.githubusercontent.com/15329494/94558914-c929ae00-0260-11eb-8bac-6fa340e126b4.png)

![grafik](https://user-images.githubusercontent.com/15329494/94558993-e199c880-0260-11eb-8e2c-e336c711a0fc.png)

**Comment by ubuntujaggers** [comment]
For ease of reference can we please have before/after in the top post? Some differences are instantly obvious (e.g. the X) but maybe not all.

**Comment by Feichtmeier** [comment]
Yeah the orange close button might be too iconic... let's keep this out of discussion for the moment. 

Selection in nautilus 
![grafik](https://user-images.githubusercontent.com/15329494/94560556-20308280-0263-11eb-9004-1d07c985c3eb.png)

![grafik](https://user-images.githubusercontent.com/15329494/94560660-422a0500-0263-11eb-84c7-8cfbad8d1c87.png)

Selection in text areas like in Gedit
![grafik](https://user-images.githubusercontent.com/15329494/94560727-553cd500-0263-11eb-8926-1424bda8e06d.png)

Selection in entries
![grafik](https://user-images.githubusercontent.com/15329494/94560845-79001b00-0263-11eb-9b27-940f5345dc83.png)

**Comment by madsrh** [comment]
I'm not instantly a fan, but this could grow over time 😊 
IMO the current colors are much better for usability. I think by design, colored text is a bad idea. [Looking at 🍏](https://products.ls.graphics/macos/) there's a lot of blue, but the text is always black/white 🤷‍♂️

**Comment by Feichtmeier** [comment]
Yeah I think making this global is prbly a very bad idea. Maybe it's still the sidebar blobs I dislike. MacOS looks really good. Really good. Maybe we could include some of those ideas

**Comment by Feichtmeier** [comment]
@madsrh what comes a little closer to mac os sidebars is maybe this:
![grafik](https://user-images.githubusercontent.com/15329494/94568625-07c56580-026d-11eb-839c-36c2f8f845a5.png)

**Comment by Jupiter007-43** [comment]
The actual style is very good for visibility. We clearly see which items are selected and it's not the case IMO in your first proposal.
But the orange in nautilus sidebar is also a bit aggressive (it looks good for me, but I think it could be aggressive for some people) and I think your last screenshot is very smarter.

> Selection in text areas like in G edit
> ![grafik](https://user-images.githubusercontent.com/15329494/94560727-553cd500-0263-11eb-8926-1424bda8e06d.png)

😄 It is a Yaru song (Ya Yaru Ya Ya Yaru 🎶💃)?

**Comment by clobrano** [comment]
I'm not sure it's ok for visibility actually. Using background color for highlight guarantees that the text is always visible no matter what background the selection has.

**Comment by Feichtmeier** [comment]
Yeah. Looks sometimes cool but it's prbly not realistic.

What about the last picture with the upstream style row selection plus orange icon?

**Comment by clobrano** [comment]
> What about the last picture with the upstream style row selection plus orange icon?

It's nice, but probably unnecessary.

**Comment by madsrh** [comment]
A less orange solution 😄 

![image](https://user-images.githubusercontent.com/3986894/94659029-f4190e00-0303-11eb-86b8-16424cf98995.png)

**Comment by Feichtmeier** [comment]
Okay, shall I propose a PR with that rows then?
It's basically this code from upstream nautilus but folded on all sidebars:

https://github.com/ubuntu/yaru/blob/553ecb3367facabba90c6d6d6dde235747a25739/gtk/upstream/nautilus/Adwaita.css#L76-L95

**Comment by clobrano** [comment]
> Okay, shall I propose a PR with that rows then?

At this point, I think we should change things to solve problems, and I don't understand what the orange symbol is solving.

**Comment by Feichtmeier** [comment]
If you mean bug = problem, there is no bug. This is why this issue is named "Design idea" and not "Bug idea" :roll_eyes: 
I showed the orange icons, because I think this looks good on the gray bars, similar to what macos does, and it adds the icons als little orange "gems"/runes on top of the subtle gray selection. I think it's elegant but I can understand if you don't like it or whatever.

The proposal contained more though. Even if I can't convince @clobrano that the orange blob must die, I still think that with the bigger buttons are current shadow does not work anymore. 
Adding pictures of zoomed buttons later before/after and you can share you opinion.

**Comment by clobrano** [comment]
> This is why this issue is named "Design idea" and not "Bug idea" :roll_eyes:

No need to roll eyes, I understood. I meant problem, like a design problem. After a couple of years of development I think we should keep things a bit stable, not changing design with a specific need. It is not specific to "this" change, but as approach in general.

> The proposal contained more though. 

It would be easy to show 1 thing at a time, I think and discuss that only. 

If by orange blob you mean the orange selection in nautilus, we can use grey as upstream does.
For the strong shadow, this is true for the light headerbar, while dark ones look fine for me.

**Comment by Feichtmeier** [comment]
That emoji should address my bad joke, not your reply. :| 

Anyways, without the orange icon, which also didn't look very good on the dark theme, the row looks like this if it is selected and has focus:
![grafik](https://user-images.githubusercontent.com/15329494/94697520-96eb7f80-0338-11eb-93e3-a54994ec3696.png)
has focus master:
![grafik](https://user-images.githubusercontent.com/15329494/94699469-a10e7d80-033a-11eb-9ab0-cfa4f7856120.png)


Without focus:
![grafik](https://user-images.githubusercontent.com/15329494/94697623-b2ef2100-0338-11eb-9bda-8d8803ef5fe5.png)
Master:
![grafik](https://user-images.githubusercontent.com/15329494/94699400-92c06180-033a-11eb-9f44-84135a2d1b2c.png)


## Buttons

### Master:

normal button:

![grafik](https://user-images.githubusercontent.com/15329494/94699588-c3a09680-033a-11eb-98ad-4a9471c00d1a.png)

hovered button:

![grafik](https://user-images.githubusercontent.com/15329494/94699635-d31fdf80-033a-11eb-81f5-ee1db2df23cc.png)



### Proposal:

normal button:

![grafik](https://user-images.githubusercontent.com/15329494/94698100-4294cf80-0339-11eb-8ef1-e0fed1bf9895.png)

hovered button:

![grafik](https://user-images.githubusercontent.com/15329494/94698193-58a29000-0339-11eb-9d67-4d9a9b60b446.png)

![Peek 2020-09-30 16-24](https://user-images.githubusercontent.com/15329494/94698344-7f60c680-0339-11eb-8531-1bc81dd4075b.gif)

![Peek 2020-09-30 16-30](https://user-images.githubusercontent.com/15329494/94699136-4a08a880-033a-11eb-9e1a-0d11f5cdf67a.gif)


## Zoomed
### Proposal:

normal button:

![grafik](https://user-images.githubusercontent.com/15329494/94698628-c8b11600-0339-11eb-9701-82f43a732cee.png)

hovered button:

![grafik](https://user-images.githubusercontent.com/15329494/94698703-dd8da980-0339-11eb-9838-28b0d227750b.png)

![Peek 2020-09-30 16-28](https://user-images.githubusercontent.com/15329494/94698775-ef6f4c80-0339-11eb-8365-8105bc4c54e1.gif)

**Comment by clobrano** [comment]
For me, the grey selection proposed, even with the orange borders, looks good.
Also the button in bright headerbar is good. I think this applies to Yaru-dark and defult, right? Since it's already quite dark, does it lose visibility with dark headerbar? If not, I am ok with this changes.

**Comment by Feichtmeier** [comment]
Okay, i'll post images and GIFs of the other themes later, would be nice if you could write what you think of those, too. The branch is already pushed if you have time to test it yourself before

**Comment by Feichtmeier** [comment]
## dark theme

![Peek 2020-09-30 18-58](https://user-images.githubusercontent.com/15329494/94716283-e76dd780-034e-11eb-8178-8d85be71309b.gif)

### zoomed

![Peek 2020-09-30 18-59](https://user-images.githubusercontent.com/15329494/94716426-1f751a80-034f-11eb-8fde-5822ccc53f2d.gif)


## mixed theme

![Peek 2020-09-30 19-02](https://user-images.githubusercontent.com/15329494/94716675-7e3a9400-034f-11eb-8cab-a20707f7ba52.gif)

### zoomed

![Peek 2020-09-30 19-01](https://user-images.githubusercontent.com/15329494/94716607-66fba680-034f-11eb-8e45-b9d994aea061.gif)

**Comment by madsrh** [comment]
This looks good @Feichtmeier 👍 My only concern is that the gray is too similar to the hover gray - ofc this is easy to fix

**Comment by Feichtmeier** [comment]
![Peek 2020-09-30 19-06](https://user-images.githubusercontent.com/15329494/94717043-10db3300-0350-11eb-9d91-f2964cd4700b.gif)

Important point, I think there is still enough difference, what do you think?

**Comment by ubuntujaggers** [comment]
The grey for sidebar/selection looks quite nice. For text selection I really think it has to have a properly visible background so you can see whether your selection is picking up white space and stuff at the sides.

**Comment by Feichtmeier** [comment]
Yeah text selection was a bad idea :| looked so cool for a moment :brain:

**Comment by Muqtxdir** [comment]
hi,

For me the grey for sidebar/selection works fine with **Yaru-light** and **Yaru** but on **Yaru-dark**, the selection is too similar to hover 

maybe darken the selection a little bit?

![yaru-darky](https://user-images.githubusercontent.com/54065734/94777920-e934ab00-03e1-11eb-97cd-e102dd7877ca.gif)

**Comment by Feichtmeier** [comment]
@Muqtxdir thanks for notice. Like this?

![Peek 2020-10-01 09-59](https://user-images.githubusercontent.com/15329494/94783345-d6fc4200-03cc-11eb-9c9a-726f15d5ae38.gif)

**Comment by Muqtxdir** [comment]
yes, this looks better

**Comment by Feichtmeier** [comment]
Thanks, pushed @Muqtxdir 
Would you be interested in further contributing? What's your name on discourse.ubuntu.com ?

**Comment by Muqtxdir** [comment]
> Would you be interested in further contributing? What's your name on discourse.ubuntu.com ?

yes, name on discourse.ubuntu.com : Muqtxdir
