### ISSUE TITLE
Nautilus sidebar looks different in backdrop

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2388]
Looks like the gray sidebar in backdrop isn't the same in every app.

![image](https://user-images.githubusercontent.com/3986894/95016442-471bf980-0653-11eb-8c50-aa355b8413de.png)

**Comment by Feichtmeier** [comment]
I'm quiet happy how it looks in Nautilus, shall we adapt the others to it?
How does gnome settings look?

**Comment by madsrh** [comment]
> I'm quiet happy how it looks in Nautilus, shall we adapt the others to it?

Hmmm, TBH I would prefer something in between. What I don't like about the Nautilus styling is that the icon is gray but the text is black. Could they both be gray?

![image](https://user-images.githubusercontent.com/3986894/95017293-c95aec80-0658-11eb-8ae4-2ce176ce309a.png)

> How does gnome settings look?

Settings is similar to Tweaks (same widget if I understood Carlo correctly)

**Comment by Muqtxdir** [comment]
hi,
for comparison here is nautilus followed by gnome-control-center in backdrop

![settings](https://user-images.githubusercontent.com/54065734/95017451-01712800-0677-11eb-9fb6-bdad70d7fd46.png)

**Comment by Feichtmeier** [comment]
yes the text is def. too dark in the backdrop in nautilus
I'll play around with it later and share some pictures if no one else is fast =)

**Comment by Feichtmeier** [comment]
Adapted all to nautilus:

![grafik](https://user-images.githubusercontent.com/15329494/95022756-7c3b4280-0679-11eb-8652-1e309ecfc057.png)
![grafik](https://user-images.githubusercontent.com/15329494/95022806-aee53b00-0679-11eb-83ad-bc9410d789f1.png)

![grafik](https://user-images.githubusercontent.com/15329494/95022821-bb699380-0679-11eb-94a1-879690e1fde3.png)
![grafik](https://user-images.githubusercontent.com/15329494/95022834-ca504600-0679-11eb-87e0-9bab46e71013.png)

Like this @madsrh @Muqtxdir ?

**Comment by madsrh** [comment]
What do you think about giving the non-selected labels a bit more color?

**Comment by Feichtmeier** [comment]
Looking at the pictures, actually now that you've put the attention to this... this is the first time the sidebar text has the same color in backdrop as the rest xD  Why didn't we think of this before?
If we change the text to be less "disabled" we should then do it for the whole window, or?

**Comment by Feichtmeier** [comment]
aaand the default theme headerbar backdrop label color is too bright ^^

**Comment by madsrh** [comment]
> If we change the text to be less "disabled" we should then do it for the whole window, or?

Then we probably shouldn't 😀

**Comment by Feichtmeier** [comment]
I can try :shrug: let me see

**Comment by Feichtmeier** [comment]
Okay I didn't manage : | Is indeed to complicated and the risk to ruin some other place is high.
But I've found that we always missed to color the headerbar label correctly in the backdrop for the default theme.

Dark theme:
![grafik](https://user-images.githubusercontent.com/15329494/95023680-aba07e00-067e-11eb-9e0d-1048a065ebe2.png)

Default theme:
![grafik](https://user-images.githubusercontent.com/15329494/95023707-cbd03d00-067e-11eb-9f41-1e3e2c22b295.png)

Light theme:
![grafik](https://user-images.githubusercontent.com/15329494/95023730-e6a2b180-067e-11eb-9efa-2299b4224b95.png)
