### ISSUE TITLE
"Gedit icon is too pale"

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2402]
[From launchpad:](https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1873365)

```The grey lines representing text on the paper sheet and the tip of the pencil in the icon are too pale. They are almost invisible so that the gedit icon is seen as a white rectangle crossed by a blue bar. Before focal, the icons of gedit and Evince used to have similar design, that is they both were pale. Now in focal, the Evince icon is redesigned and it is more clear with more contrast. The suggestion is to apply similar modifications to the gedit icon to make it more clear. For example, it can use the same dark gray color of the text lines as Evince icon.```

Personally I was never a huge fan of the pencil metaphor. The pencil metaphor (in my opinion) stands for "notes" or "sketches"

When I think about for what **I** mostly use Gedit I find myself always using it for all text files which are not linked to a **specifc** program, like.. java files -> IDE or something.
So aren't they mostly for this? Or does anyone really use them for notes/sketches ? I think most people use them for source code or unix files or freedesktop files that are often smilar to source code because they are either interpreted by some interpreter or compiled by some compiler.

My first idea does not really fix the "grey is too pale" issue, but maybe this fits the purpose of the app better and if you like it, maybe some of the inkscape pros here can make it right:

![grafik](https://user-images.githubusercontent.com/15329494/95578952-0d713700-0a35-11eb-8253-f27c000671be.png)

**Comment by Jupiter007-43** [comment]
This is my point of view:

I think IMO that the actual metaphor is pretty good.
My own usage of Gedit is mainly for writing a bit of text without launch LO, and occasionally for opening a downloaded file (mainly CSS, HTML, PHP or any other code source file) without launch my mamouth Atom code editor.
And as Gedit is the MS notepad of Gnome I don't think that the noob Ubuntu user (which can have never seen one line of code) will understand correctly the metaphor of your proposal.

But this is just my own opinion and I'm curious to know what others think of. 🙂

**Comment by Feichtmeier** [comment]
Sure, the actual issue is more about contrast and not about the motive :)
If you want and have an idea go ahead ☺️

**Comment by Feichtmeier** [comment]
Maybe we can exchange the pencil for some other pen?

**Comment by Feichtmeier** [comment]
Duplicate of https://github.com/ubuntu/yaru/issues/2435
Let's discuss it there @ubuntujaggers @Jupiter007-43
