### ISSUE TITLE
file-roller archive encrypted files show generic icon instead of lock-style icon

### ISSUE THREAD

**Issue by wesinator** [ubuntu/yaru#2415]
## Expected Behavior

Lock icon with encrypted files in archive opened with file-roller

## Actual Behavior
Yaru theme displays generic document icon for encrypted files in archive 

Numix theme:
![image](https://user-images.githubusercontent.com/5124946/96113446-315bcf00-0eb2-11eb-8657-544d72dda203.png)

Yaru theme: 
![image](https://user-images.githubusercontent.com/5124946/96113558-54867e80-0eb2-11eb-8718-f40af5212b2b.png)

## Steps to Reproduce the Problem

  1. Zip file with encrypted files (example attached) 
[example.zip](https://github.com/ubuntu/yaru/files/5384236/example.zip)
 2. View zip in file-roller
Notice the icon on the encrypted file in the archive 

## Software that presents the issue

- Name: file-roller
- Version: 3.36.3

## Yaru version
20.04.8

**Comment by Jupiter007-43** [comment]
Hi @wesinator and thank you for taking the time of reporting that problem.
To be very honest, I don't know what's append with our icon theme. File-roller seems to use an emblem (I don't know which one) with Numix but use the **text-x-generic** mimetype icon with Yaru.
I also tested other icon theme like Adwaita and Humanity and there's the same behavior as Yaru.

**Comment by Feichtmeier** [comment]
Maybe we miss the emblem then @Jupiter007-43 ?

**Comment by Jupiter007-43** [comment]
I don't know but as this bug is also present with Adwaita icons, maybe ask upstream first.

**Comment by Jupiter007-43** [comment]
https://gitlab.gnome.org/GNOME/file-roller/-/issues/120

**Comment by Jupi007** [comment]
Fixed upstream (see: https://gitlab.gnome.org/GNOME/file-roller/-/issues/120).
