### ISSUE TITLE
Yaru dark renders GNOME To Do unusable

### ISSUE THREAD

**Issue by thedefectiveram** [ubuntu/yaru#2449]
I just recently noticed that when I am using Yaru dark the list in GNOME To Do app is not readable.
![Screenshot from 2020-10-20 05-58-17](https://user-images.githubusercontent.com/60362849/96580553-11efe800-129e-11eb-844a-a66a87b6f3bb.png)

I am running Ubuntu 20.10 beta.

**Comment by Muqtxdir** [comment]
hi @thedefectiveram ,

I am also using Ubuntu 20.10 beta and the GNOME To Do app is readable for me
![Screenshot from 2020-10-20 17-07-24](https://user-images.githubusercontent.com/54065734/96581005-c61d5d00-12f6-11eb-892b-36e50b332af5.png)

**Comment by Feichtmeier** [comment]
Hmmm @thedefectiveram 
I can not reproduce this either.

Todo with your color in backdrop:
![grafik](https://user-images.githubusercontent.com/15329494/96595144-a7fe2f80-12eb-11eb-9ed2-ad6c09a84813.png)
![grafik](https://user-images.githubusercontent.com/15329494/96595264-c6fcc180-12eb-11eb-8373-c55fc0857a68.png)


Active window:
![grafik](https://user-images.githubusercontent.com/15329494/96595175-b0ef0100-12eb-11eb-9a88-1360e0ba5054.png)
![grafik](https://user-images.githubusercontent.com/15329494/96595294-cd8b3900-12eb-11eb-8f91-a282250993ce.png)

**Comment by clobrano** [comment]
Hi @thedefectiveram,

did you install gnome to-do from flathub?
We fixed the flatpak version of Yaru yesterday with a @Muqtxdir's contribute, maybe your app was using an old version then. Could you try re-installing the app again? I hope this will download the yaru theme as well.

**Comment by thedefectiveram** [comment]
> 
> 
> Hi @thedefectiveram,
> 
> did you install gnome to-do from flathub?
> We fixed the flatpak version of Yaru yesterday with a @Muqtxdir's contribute, maybe your app was using an old version then. Could you try re-installing the app again? I hope this will download the yaru theme as well.

I did not, I believe it comes pre-installed on default (non-minimal) install of Ubuntu.

**Comment by Feichtmeier** [comment]
Checked again and this is not reproducible on multiple installations
