### ISSUE TITLE
Request: Suggestions for potential fonts to complement Yaru

### ISSUE THREAD

**Issue by coxackie** [ubuntu/yaru#2455]
not a bug, and not sure whether this has been addressed before, but I would like to see suggestions on fonts (names and sizes) to use with `yaru` (for example tweaked in gnome-tweaks). They do not have to be necessarily the ones used in Ubuntu, but certainly what the team thinks is best. I personally use Arch and right now sticking with Cantarell mostly, because I find it very clean, but would appreciate alternatives.

**Comment by clobrano** [comment]
Hi @coxackie,

thank you for your interest in the project. Ubuntu ships with Ubuntu fonts and size 11 for readability, but also size 10 seems nice. I believe you can find more info on some Ubuntu forum.
Thanks again, closing this now.
