### ISSUE TITLE
Cannot Expand Remmina Applet Subcategories on Dark Yaru Theme 

### ISSUE THREAD

**Issue by thepuppet33r** [ubuntu/yaru#2460]
## Expected Behavior

I cannot expand the categories to list the available RDP files on the taskbar applet. Whenever I go to click on a category ("Domain Controllers"), it just changes from a right-pointing triangle to a down-pointing triangle.

## Actual Behavior

When I click on a category on the applet menu, it should (and has in the past) shown all available entries in that category.
I've reinstalled the program, I've changed my desktop resolution, I've run repairs...I'm at a loss. Everything else in Remmina works fine.

## Steps to Reproduce the Problem

  1. Start Remmina. 
  1. Click on the taskbar applet.  
  1. Try to select any of the categories - It just changes from a side-pointing arrow to a down-pointing arrow. 

![2020-10-22_11-32](https://user-images.githubusercontent.com/16672129/96926477-35bc5500-147b-11eb-9ffc-e07294922b2c.png)

## Software that presents the issue

- Name: Remmina
- Version: 1.4.8

## Yaru version

29.187 2020-04-19 (1987) 22MB -

**Comment by thepuppet33r** [comment]
This issue does not happen Adwaita. 

Also reported here: 
https://gitlab.com/Remmina/Remmina/-/issues/2321#note_434669133

**Comment by clobrano** [comment]
Hi @thepuppet33r,

could you help me more? What's the taskbar applet?

Also, it seems you installed the snap version of Yaru, which Ubuntu version do you have?

**Comment by Feichtmeier** [comment]
Ohhhh... The snap version of yaru only works for the gnome shell in 18.04

**Comment by thepuppet33r** [comment]
That would do it then! Good to know. Thank you! You can close this issue out.

**Comment by clobrano** [comment]
Good to know. Feel free to reopen if the problem occurs again.
Thank you :)
