### ISSUE TITLE
Inkscape error while rendering cursors

### ISSUE THREAD

**Issue by Jannomag** [ubuntu/yaru#2467]
I'm getting following error, when running `./render-cursors.py ./source-cursors.svg`:    
`Inkscape interactive shell mode. Type 'action-list' to list all actions. Type 'quit' to quit.
 Input of the form:
 action1:arg1; action2;arg2; verb1; verb2; ...
Only verbs that don't require a desktop may be used.
`
Everything on a fresh Ubuntu 20.10 installation. Inkscape, python3, python, python-pil are installed via the repo.

Edit:
Didn't try it out yet but maybe it's caused by Inkscape 1.0?

**Comment by clobrano** [comment]
Hi @Jannomag,

yes, it's because of inkscape 1.0. I updated a couple of days ago another render script, but the one for the cursors still need the fix.

**Comment by Jannomag** [comment]
Alright then. Thanks!

**Comment by Jupi007** [comment]
@clobrano Can you have a look at this, please :)

**Comment by clobrano** [comment]
I'll try to have a look tomorrow
