### ISSUE TITLE
GTK2 assets missing in dark theme 

### ISSUE THREAD

**Issue by Jannomag** [ubuntu/yaru#2472]
Following assets are not getting rendered because they aren't in the [assets.txt](https://github.com/ubuntu/yaru/blob/master/gtk/src/dark/gtk-2.0/assets.txt) file but they're in the .svg file.
This happens with the gtk2 dark theme only:
- menu-checkbox-hover
- menu-checkbox-insensitive
- menu-checkbox-checked-insensitive
- menu-checkbox-mixed-insensitive

When rendering the assets and activating the theme following errors appear:
```/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:183: Bilddatei konnte nicht in pixmap_path gefunden werden: »assets/menu-checkbox-insensitive.png«
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:185: Overlay image options specified without filename
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:223: Bilddatei konnte nicht in pixmap_path gefunden werden: »assets/menu-checkbox-checked-insensitive.png«
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:225: Overlay image options specified without filename
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:1634: Bilddatei konnte nicht in pixmap_path gefunden werden: »assets/menu-checkbox-insensitive.png«
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:1636: Overlay image options specified without filename
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:1666: Bilddatei konnte nicht in pixmap_path gefunden werden: »assets/menu-checkbox-checked-insensitive.png«
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:1668: Overlay image options specified without filename
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:1698: Bilddatei konnte nicht in pixmap_path gefunden werden: »assets/menu-checkbox-mixed-insensitive.png«
/home/jan/.themes/Yaru-Blue-dark/gtk-2.0/main.rc:1700: Overlay image options specified without filename
```
(Don't mind the paths and sorry for not using English)

Adding the missing files to the assets.txt fixes the errors.

**Comment by clobrano** [comment]
Thanks @Jannomag, and nice catch.
Mind committing the change you already tested as PR? 😍

**Comment by Jannomag** [comment]
Did it... hopefully. I'm a totally github noob and won't get how it really works, though 😂

I close this issue because I opened a PR.

**Comment by Feichtmeier** [comment]
Thanks @Jannomag 
If your PR fixes this issue, simply put

```Closes #2472```

At the end of your PR description. When your PR is merged, github will auto close this issue then :)

**Comment by Jannomag** [comment]
Thanks, I try to keep it in mind.

**Comment by clobrano** [comment]
Thanks a lot @Jannomag !

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru/pull/2475
