### ISSUE TITLE
Aren't the arrows little more bigger?

### ISSUE THREAD

**Issue by UltraBurstXD** [ubuntu/yaru#2476]
Hi,
I'm using Ubuntu 20.10 I've noticed that the arrows may be little more bigger than they used to be:

![](https://user-images.githubusercontent.com/55871338/98238677-6d44fa00-1f6f-11eb-9b2e-bf50acae5e6c.png)

And that is making it look ugly. Not only in system menu, others apps are affected too. Not all of them, Apache NetBeans is normal for me even though if it's using system l&f as default:

![](https://user-images.githubusercontent.com/55871338/98240944-e1cd6800-1f72-11eb-9543-6d9af41b4f41.png)

**Comment by clobrano** [comment]
Hi @UltraBurstXD,

I don't feel they look "ugly", but that's an opinion. I am unsure they are bigger as well, unless upstream changed the size recently

**Comment by Feichtmeier** [comment]
We once had the arrows from our icon theme. But at some point they changed the icon name.
@UltraBurstXD if you like you can track down the icon name in upstream gnome shell

**Comment by UltraBurstXD** [comment]
What is it's name? I'm having some trouble finding it in the upstream gnome shell...

**Comment by UltraBurstXD** [comment]
Hmmm... Having some trouble finding it though... So [scrollbar-arrow](https://github.com/ubuntu/yaru/blob/master/gtk/src/dark/gtk-2.0/assets/scrollbar-arrow-down.png)... is that the name? It kinda looks fancy, like the arrows of Firefox. I think it'd look cool in system menu and others widgets too...

**Comment by Jupiter007-43** [comment]
All these icons are named pan-*-symbolic, see #2593
