### ISSUE TITLE
Top bar and lock screen clock weird cuted out

### ISSUE THREAD

**Issue by tosziro** [ubuntu/yaru#2493]
**Expected Behavior**
Clean looking clock.

**Actual Behavior**

Sometimes top bar looks like it cuted on the right side, and display weirdly. It fix itself when you simply take mouse cursor on it. Appears again after some time.
This happens on both of my machines running Ubuntu 20.10.

**System information**
Ubuntu 20.10

**Yaru version**
Package: yaru-theme-gnome-shell
Version: 20.10.6.1

**Screenshots**

![ezgif-1-5d237660fb9e](https://user-images.githubusercontent.com/41963712/99675106-182cdc00-2a77-11eb-887d-c4d2d5e9db62.gif)

**Upstream check**
It appears only in Ubuntu default session. Looks fine on Adwaita.

**Comment by tosziro** [comment]
Ok, its not only top bar but also lock screen. Just noticed this.


![ezgif-2-2703035bddb9](https://user-images.githubusercontent.com/41963712/99726438-ca37c880-2ab6-11eb-8aa2-9ceba62a3691.gif)

**Comment by Feichtmeier** [comment]
I think this again a font size issue with the Ubuntu font
@vanvugt any idea?

**Comment by Jupiter007-43** [comment]
> Ok, its not only top bar but also lock screen. Just noticed this.

I also encountered this problem on lock screen.

**Comment by Muqtxdir** [comment]
hi,
I am also on Ubuntu 20.10 and these dont happen to me, is there something else changed besides the seconds to be displayed on top-bar?
### top-bar:
![2020-11-20 15-00-20](https://user-images.githubusercontent.com/54065734/99784580-07956800-2b42-11eb-8854-c0c41ca52430.gif)

**Comment by tosziro** [comment]
I have hidpi screen. 2560x1440 so fonts are scaled to 1.25

**Comment by Muqtxdir** [comment]
> I have hidpi screen. 2560x1440 so fonts are scaled to 1.25

I too am using HiDPI screen (1920x1080),by fonts scaling do you mean **gnome-tweaks > Fonts > scaling factor** or **Settings > Displays > Fractional scaling** ( i use this) 


> **Note that this is not like that all the time. Its happens sometimes.**

do you use nvidia-card?

**Comment by tosziro** [comment]
> > I have hidpi screen. 2560x1440 so fonts are scaled to 1.25
> 
> I too am using HiDPI screen (1920x1080),by fonts scaling do you mean **gnome-tweaks > Fonts > scaling factor** or **Settings > Displays > Fractional scaling** ( i use this)
> 
> > **Note that this is not like that all the time. Its happens sometimes.**
> 
> do you use nvidia-card?

gnome-tweaks > Fonts > scaling factor

No, I use AMD on one machine, Intel on second.

**Comment by Muqtxdir** [comment]
wow, such a quick reply!

> gnome-tweaks > Fonts > scaling factor

if it's this then @Feichtmeier is right, this might be related to font issues

**Comment by tosziro** [comment]
I changed font in top bar and issue has gone. I hope guys you can fix this problem with Ubuntu font soon.

**Comment by tosziro** [comment]
Anyway why default GNOME font Cantarell looks so different in Ubuntu than in other distributions for example here openSUSE?  Maybe there is a problem? 
![cantarell](https://user-images.githubusercontent.com/41963712/99874576-5813d080-2be9-11eb-8688-533cfbfab959.png)

**Comment by vanvugt** [comment]
This is probably a gnome-shell bug. We are [tracking it upstream here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2912).

**Comment by clobrano** [comment]
Thanks @vanvugt! Closing this for now, then.
