### ISSUE TITLE
org.gnome.Shell.Extensions missing

### ISSUE THREAD

**Issue by Dragon8oy** [ubuntu/yaru#2498]
As useful as the template is, it feels a bit unnecessary for such a quick fix.
org.gnome.Shell.Extensions is missing, and should be the same as org.gnome.Extensions
I'd submit a PR myself, but the icon directory structure in this project is a little confusing, sorry.

**Comment by Jupiter007-43** [comment]
Hi @Dragon8oy,
thank you for reporting this.
If you want to submit a PR here is the way to do:
- go to _icons/src/symlinks/fullcolor/apps.list_
- add this line: `extensions.png org.gnome.Shell.Extensions.png` (below `extensions.png org.gnome.Extensions.png`)
- and run the script (located in _/symlinks_): `./generate-symlinks.sh -m org.gnome.Shell.Extensions`

That's it :slightly_smiling_face:

**Comment by Jupiter007-43** [comment]
You're welcome!
One more thing please: could you link your PR to this issue (just add a comment with `Closes #2498`)?

**Comment by Jupiter007-43** [comment]
Perfect, thanks!
