### ISSUE TITLE
Drag cursor is not consistent 

### ISSUE THREAD

**Issue by cybbro** [ubuntu/yaru#2507]
Yaru cursor dragging icons are not consistent I don't know whether that is a feature or a bug though, when I drag a window I get this nice cursor:

![Screenshot from 2020-12-17 10-54-30](https://user-images.githubusercontent.com/10908092/102466040-1a269280-4057-11eb-9ddd-194177a3d855.png)

But if I try to drag a web element, something inside a web app or even in some other desktop applications I get this:

![2020-12-17_11-06](https://user-images.githubusercontent.com/10908092/102466691-07608d80-4058-11eb-8322-460ce6a05a6a.png)

Video:

https://streamable.com/2fc0nl

That is when cursor is hovering OVER the element, if I try to click and drag, it briefly turns to that white hand from first image, and then goes back to this dark cursor image again..

To reproduce this, it's easiest to try and drag elements in scratch editor, which I did in the second picture https://scratch.mit.edu/projects/editor/?tutorial=getStarted.

I used Chromium browser on Ubuntu 20.10

**Comment by Feichtmeier** [comment]
Hi @cybbro thanks for the issue
I think this could be the case of a missing cursor symlink and then the adwaita cursor jumping in.

**Comment by cybbro** [comment]
> Hi @cybbro thanks for the issue
> I think this could be the case of a missing cursor symlink and then the adwaita cursor jumping in.

That's a reasonable assumption! by default, Ubuntu 20.10 did not come with adwaita cursors, but I installed them via Synaptic. So it might be picking up those. But I have no idea how cursors work, so I don't know where to change that.  Maybe I should uninstall adwaita cursors to see what it does if it can't find those?

**Comment by Jupiter007-43** [comment]
![Capture d’écran du 2020-12-17 11-43-42](https://user-images.githubusercontent.com/36476595/102477844-30375180-405d-11eb-863f-cdcd1736abd0.png)

The grab cursor (css name) is missing, see: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by cybbro** [comment]
So, what would be the best next step here, should I wait for an advice how to fix it, or just close the issue since it's the duplicate of #2219 ?

**Comment by Jupiter007-43** [comment]
There was a PR (#2453) which was linking the **hand1** icon to the **grab** one. But looking at **/usr/share/icons/Yaru/cursors/** I can't found any **grab** icon.
IMO this PR is incomplete. How can we symlink a cursor?

> So, what would be the best next step here, should I wait for an advice how to fix it, or just close the issue since it's the duplicate of #2219 ?

As it's a Yaru problem, just wait for a fix PR 🙂

**Comment by Feichtmeier** [comment]
Idk, can't you just ln -s on the hand cursor ?
Otherwise just copy paste it :shrug:

**Comment by Jupiter007-43** [comment]
> Idk, can't you just ln -s on the hand cursor ?
> Otherwise just copy paste it shrug

In fact I was asking how to symlink cursors in Yaru repo. 😅 I have no idea of the way to do.

I tried ln -s and it works on Todo:

![Capture d’écran du 2020-12-17 12-38-35](https://user-images.githubusercontent.com/36476595/102483578-3d583e80-4065-11eb-8c6d-d67b70313ade.png)

But that didn't resolved the problem into Firefox. By the way there is the same problem with Adwaita. IMO this is a Firefox bug.

**Comment by Muqtxdir** [comment]
> In fact I was asking how to symlink cursors in Yaru repo. sweat_smile I have no idea of the way to do.

@Jupiter007-43 is right, `generate-symlink.sh` does-not symlink cursor sets even though `cursors.list` is present
I think its maybe because `generate-symlink.sh`does not have `cursors` in `CONTEXT`
