### ISSUE TITLE
question: what value to change to get font like adwaita

### ISSUE THREAD

**Issue by fouzan14** [ubuntu/yaru#2519]
I noticed Yaru uses normal font weight in places where Adwaita default uses bold font-weight
What values in scss do i change to get the default adwaita-font weight in top-bar and app-folders? (basically, asking what tweak should I remove to get the default adwaita font-weight in gnome-shell theme) 
Please point me to the file, where I need to make changes

**Comment by madsrh** [comment]
Hi fouzan14. I'm going to close your issue here since this isn't an actual issue in Yaru 😊 The comments are still open of course.

**Comment by fouzan14** [comment]
ok dude, but could you tell me how to change the font weights?

**Comment by Feichtmeier** [comment]
Yo dude 🙄

If you mean the Gnome shell app folders remove the wild card in gnome shell theme dir _widgets.scss 

Yo yo, let's all communicate like some primates from 20k years ago, yo yo

**Comment by fouzan14** [comment]
Thanks ! I apologise if my tone seemed inappropriate
