### ISSUE TITLE
Improve the gnome-characters icon

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2520]
The upstream icon of gnome-characters, in my opinion, represents the nature of the app better than the Yaru icon. The upstream icon has an Asian character, an Arabic letter, an emoji and a symbol, which are really the things that are searched for in the app. On the other hand, the Yaru icon has only an accented "a" letter. So I think the Yaru icon could be improved.

[Upstream icon](https://gitlab.gnome.org/GNOME/gnome-characters/-/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Characters.svg)
![image](https://user-images.githubusercontent.com/45657128/103175972-7c10a480-486e-11eb-9bfc-03c3caf2741c.png)

[Yaru icon](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/accessories-character-map.svg)
![image](https://user-images.githubusercontent.com/45657128/103176005-b67a4180-486e-11eb-961a-38aef9eb1c28.png)

**Comment by ubuntujaggers** [comment]
Is this any good?

![image](https://user-images.githubusercontent.com/38893390/104123339-9fddeb00-5342-11eb-98c4-67d94b44625b.png)

**Comment by Amr-Ibra** [comment]
Yes, but I prefer the look of the Arabic letter ش on the upstream icon because the three dots look more symmetrical there.

Also, the eyes in the emoji look a bit too large in the suggested Yaru icon.

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/104137800-6f746c00-5397-11eb-9aab-ad59b6d06cdc.png)

??

**Comment by Amr-Ibra** [comment]
Much better.
