### ISSUE TITLE
High res dark shell switch asset is low res

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2524]
![Peek 2021-01-05 11-06](https://user-images.githubusercontent.com/15329494/103633559-30cd5480-4f46-11eb-95d3-37e9d53b49fe.gif)
https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/toggle-off-dark.svg

**Comment by madsrh** [comment]
Nicely spotted 🕵️

**Comment by Feichtmeier** [comment]
could not reproduce
maybe this was just a temporary thing and the old asset was loaded
it is def. not a problem of the asset

**Comment by Jupiter007-43** [comment]
Did you noticed it on a 4K screen?

**Comment by Feichtmeier** [comment]
yes, last time and this time. last time eventually the shell missed to reload the asset

**Comment by Jupiter007-43** [comment]
Ok, so I can't test with my 1080p display, sorry.
🤔 Looking at assets, I didn't noticed anything.

**Comment by Feichtmeier** [comment]
Uncofirmed, I guess it's rather a bug in gnome-shell

**Comment by Feichtmeier** [comment]
Some observations to this:
- the light theme has the same problem
- this happens when you have a running gnome shell session which was previously connected to a 1920x1080 screen, hibernate resume and connect to a 4k screen
- restarting the shell fixes this issue
- happens also with vanilla gnome
