### ISSUE TITLE
[Missing icon] Sound Recorder

### ISSUE THREAD

**Issue by vitalkanev** [ubuntu/yaru#2538]
**Icon Request**
**Note**: This is an *official* GNOME app included in other distributions (and shown in GNOME home page, hehe), but not in Ubuntu. Podcasts app is not included by default in Ubuntu, but the icon exists. Hmm

**Steps to locate the icon**

1. Install `gnome-sound-recorder` from Ubuntu repositories (tested with `devel` channel thanks to Martin Wimpress :D)
2. Go to app grid
3. (optional, for small screens) scroll down until you see the icon
4. Observe the icon

**Software where the icon is missing**
Name: GNOME Sound Recorder (icon name: `org.gnome.SoundRecorder`)
Version: 3.38.0
Yaru & System version:
```
$ lsb_release -idrc && apt policy yaru-theme-icon
Distributor ID:	Ubuntu
Description:	Ubuntu Hirsute Hippo (development branch)
Release:	21.04
Codename:	hirsute
yaru-theme-icon:
  Installed: 20.10.6.1
  Candidate: 20.10.6.1
  Version table:
 *** 20.10.6.1 500
        500 http://archive.ubuntu.com/ubuntu devel/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu devel/main i386 Packages
        100 /var/lib/dpkg/status
```

**Screenshots**

![Screenshot of Gnome App listing showing ugly icon of Sound Recorder](https://i.imgur.com/any6KYG.png)

*Optional* Maybe Yaru icon should look similar to upstream (like in Evince)? Or similar to Podcasts?

**Comment by Feichtmeier** [comment]
Thanks - looks like a generic gnome app and we should be safe to provide an icon for this. Good idea to stay close to upstream

**Comment by ubuntujaggers** [comment]
This is the Adwaita icon in Ubuntu:

![image](https://user-images.githubusercontent.com/38893390/107812638-e2db1600-6d67-11eb-8edb-1981fb7864b3.png)

![image](https://user-images.githubusercontent.com/38893390/107812658-ebcbe780-6d67-11eb-8f45-94c2018de7d2.png)

IMO being super-faithful to the design results in something that's a bit wrong for Yaru:

![image](https://user-images.githubusercontent.com/38893390/107812860-02723e80-6d68-11eb-815b-d0286549aa2f.png)

![image](https://user-images.githubusercontent.com/38893390/107813273-22a1fd80-6d68-11eb-9b61-1041225214db.png)

...and doesn't look better than the Adwaita icon, so I'll try something else :+1:

**Comment by ubuntujaggers** [comment]
What about something more like:

**Comment by Jupiter007-43** [comment]
This one looks better, but I think it isn't enough obvious.
Can you try to redo your first proposal in this style (I mean without padding)?

**Comment by Feichtmeier** [comment]
![Screenshot_20210212-213921.png](https://user-images.githubusercontent.com/15329494/107820279-cd231c00-6d7a-11eb-98fa-037b97661d63.png)

Eventually put a subtle sound wave as a baseplate?
But this one looks already cool

**Comment by ubuntujaggers** [comment]
@Jupiter007-43 

![image](https://user-images.githubusercontent.com/38893390/107826587-078db880-6d7d-11eb-8c91-26c6514e556a.png)

???

**Comment by ubuntujaggers** [comment]
Ooh, I like this!  Just the wave:

![image](https://user-images.githubusercontent.com/38893390/107827022-db266c00-6d7d-11eb-9fc7-f7151a46f520.png)

![image](https://user-images.githubusercontent.com/38893390/107827038-e2e61080-6d7d-11eb-9e80-274f7eab306c.png)

**Comment by ubuntujaggers** [comment]
Click the images to view them - seems to resize them slightly in the post so they aren't as clear.

**Comment by Feichtmeier** [comment]
I thin this green looks maybe too much like engieering / health

Could you try a purple baseplate and without the echo shadow?
![grafik](https://user-images.githubusercontent.com/15329494/107827900-fa29fb80-6d87-11eb-99f4-236bb59136c1.png)
(amateur atempt)^^

**Comment by Jupiter007-43** [comment]
> Ooh, I like this! Just the wave:
> 
> ![image](https://user-images.githubusercontent.com/38893390/107827022-db266c00-6d7d-11eb-9fc7-f7151a46f520.png)
> 
> ![image](https://user-images.githubusercontent.com/38893390/107827038-e2e61080-6d7d-11eb-9e80-274f7eab306c.png)

Just the wave is much better 👍
But I agree @Feichtmeier about colors, can you try with purple?

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/107859056-0a48e600-6e2f-11eb-9ac3-c96d8194048c.png)

![image](https://user-images.githubusercontent.com/38893390/107859064-116ff400-6e2f-11eb-8d4d-2d3b8a19487e.png)

???

**Comment by Jupiter007-43** [comment]
Perfect 😃
