### ISSUE TITLE
Preemptive question: no "early" support for GNOME 40?

### ISSUE THREAD

**Issue by coxackie** [ubuntu/yaru#2553]
Hi there. I recently read that Ubuntu 21.04 will stay with GNOME 3.38, and that one of the reason was that yaru would not be "ready" for the GTK4 transition by then. I am opening this issue to ask if this is indeed the case. There is a large community using yaru outside of Ubuntu, and I wanted to know whether updating to GNOME 40 after release is going to break the theme.

 Many thanks for your incredible work, everyone!

**Comment by Feichtmeier** [comment]
Sorry we won't discuss this here
Here is the discussion: https://discourse.ubuntu.com/t/staying-on-gtk3-and-gnome-3-38-this-cycle/20466/24

As always, Yaru will support what's in Ubuntu

**Comment by coxackie** [comment]
@Feichtmeier thanks, and I totally understand that your priority is Ubuntu. I was just asking whether there would be *any* support for gtk4. From what I see in the discussion thread you sent, is https://gitlab.gnome.org/Feichtmeier/gtk/-/commits/yaru going to provide such functionality, or are you not going to merge this to yaru until the next Ubuntu iteration?

**Comment by Feichtmeier** [comment]
Yes ofc, but just wait please

**Comment by coxackie** [comment]
@Feichtmeier of course - I am not in any hurry, and apologies if it appears so. They only thing I wish is that yaru still more or less work after March, when certain distros (such as Arch) update to GNOME 40. This is all. And, once again, many thanks for your great work.
