### ISSUE TITLE
About Icon-theme Specification

### ISSUE THREAD

**Issue by kwwzzz** [ubuntu/yaru#2557]
**Expected Behavior**

At the same pixel size, different types should not have the same name.

**Description and Screenshots**

Hi! I've realized a question about icon-theme during my development process: Shouldn't there be icons with the same name under different types of folders of the same pixel size?
Although the index.theme file controls the order in which the application looks for icons, I don't think it makes sense to have icons with the same name under different types of folders of the same pixel size. 
Since the control of the index.theme file can make some images meaningless if there are icons with the same name, I did a check of yaru's icon-theme and found some icons with the same name at the same pixel size and different types.

as follows.

- aptdaemon-download.png  in  apps/status
![aptdaemon-download](https://user-images.githubusercontent.com/49967540/105566100-52f80c80-5d65-11eb-83d9-6da42cd93dcf.png)

- text-x-log.png  in  apps/mimetypes
![text-x-log png](https://user-images.githubusercontent.com/49967540/105566122-71f69e80-5d65-11eb-97e4-771399081deb.png)

- preferences-system-symbolic.svg   in  apps/categories
![preferences-system-symbolic](https://user-images.githubusercontent.com/49967540/105566145-83d84180-5d65-11eb-8e56-832555d52b64.png)

- gnome-control-center-symbolic.svg  in   apps/categories
![gnome-control-center-symbolic](https://user-images.githubusercontent.com/49967540/105566162-9f434c80-5d65-11eb-97ff-81b00a913191.png)

- preferences-desktop-keyboard-symbolic.svg  in   apps/devices
![preferences-desktop-keyboard-symbolic](https://user-images.githubusercontent.com/49967540/105566171-abc7a500-5d65-11eb-9551-d55ffa23b620.png)

- video-x-generic-symbolic.svg   in  places/mimtypes
![video-x-generic-symbolic](https://user-images.githubusercontent.com/49967540/105566190-c69a1980-5d65-11eb-8c86-d84782feb9d6.png)

- preferences-ubuntu-panel-symbolic.svg   in  apps/categories
![preferences-ubuntu-panel-symbolic](https://user-images.githubusercontent.com/49967540/105566200-d31e7200-5d65-11eb-9ab6-703d27c7133d.png)

Looking forward to hearing from you, thanks!

**Comment by Jupiter007-43** [comment]
Hi @kwwzzz,
thanks for the report.
I created a PR which remove duplicated icons:  #2563

**Comment by kwwzzz** [comment]
thx！I'm glad you took my advice.
