### ISSUE TITLE
Svgs have unused definitions

### ISSUE THREAD

**Issue by Dragon8oy** [ubuntu/yaru#2571]
Many of the svgs in the icon theme have unused definitions in them, which can safely be removed and save file size. They can be cleaned up in Inkscape via `File > Clean Up Document`, or cleaned up with `inkscape --vacuum-defs --export-filename=./filename.svg ./filename.svg`. If anyone's interested, I'll recursively do this later and submit a pull request.

**Comment by madsrh** [comment]
>  If anyone's interested, I'll recursively do this later and submit a pull request.

Fantastic!

I know next to nothing about Inkscape, but that sound like a great idea. Right, @ubuntujaggers ?

**Comment by Feichtmeier** [comment]
Yes please do :)

**Comment by Feichtmeier** [comment]
@Dragon8oy are you on https://discourse.ubuntu.com/ ?

**Comment by Dragon8oy** [comment]
> @Dragon8oy are you on https://discourse.ubuntu.com/ ?

I'm not, I used to use Ubuntu, but I just use this theme now :)

**Comment by Feichtmeier** [comment]
Okay just asking because you've been contributing quiet a bit. So if you are interested in joining the team just ping us on discourse in a PM. Otherwise github is also very much fine :+1:

**Comment by Dragon8oy** [comment]
Ah okay, thanks

**Comment by ubuntujaggers** [comment]
Excellent, thank you! 🙂
