### ISSUE TITLE
Missing desktop icon in Advanced MATE Menu

### ISSUE THREAD

**Issue by vitalkanev** [ubuntu/yaru#2577]
**Expected Behavior**
Yaru Desktop icon should appear

**Actual Behavior**
Desktop icon from Ambiant is used

**Steps to Reproduce the Problem**
1. **Important!** Add "Advanced MATE menu" to any free panel
2. Open the menu
3. Look at the desktop icon

**Software that presents the issue**
!["Advanced MATE Menu" version dialogue box](https://i.imgur.com/Xuxegrk.png)

**Yaru version**
Git commit: 0faae97512a2acd11a0e34c24640c6fd2159bd6a
```bash
$ lsb_release -idrc
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

**Screenshots**
![Don't have time to add alt text 😐](https://i.imgur.com/Z8Aosxf.png)

**Comment by flexiondotorg** [comment]
This can be closed, the Advanced MATE Menu is deprecated and not shipped by default since Hirsute.
