### ISSUE TITLE
GTK 2: menus use text colour too bright to be readable

### ISSUE THREAD

**Issue by andrewshadura** [ubuntu/yaru#2580]
**Expected Behavior**

![image](https://user-images.githubusercontent.com/309253/106352719-a6c6a080-62e5-11eb-98ee-47a76026854d.png)

**Actual Behavior**

![image](https://user-images.githubusercontent.com/309253/106352688-636c3200-62e5-11eb-9b49-6ec66a68d43a.png)

**Steps to Reproduce the Problem**

Use the default (non-dark) Yaru

**Software that presents the issue**

Software based on GTK 2, for example GIMP.

**Yaru version**

Yaru 20.10.6.1, same behaviour in the latest Git version

**Comment by godlyranchdressing** [comment]
@andrewshadura what distro/Ubuntu release are you running? I went through a couple of GTK2 apps and I'm not getting the light text problem, so it may be GIMP-specific but I'm on 20.10 and that doesn't have a GTK2 based version of GIMP.

**Comment by andrewshadura** [comment]
@godlyranchdressing, Ubuntu 20.10 has GTK2-based GIMP:
```
gimp:
  Installed: 2.10.22-3
  Candidate: 2.10.22-3
  Version table:
 *** 2.10.22-3 500
        500 http://at.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        100 /var/lib/dpkg/status
```
```
$ ldd /usr/bin/gimp | grep gtk
	libgtk3-nocsd.so.0 => /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 (0x00007fc54951e000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fc549014000)
```

**Comment by andrewshadura** [comment]
And it’s not GIMP-specific. I can observe the same behaviour with gbdfed:

https://user-images.githubusercontent.com/309253/115916117-a0733b00-a474-11eb-86cc-952b0741adc5.mp4

**Comment by godlyranchdressing** [comment]
This is what I see: 

https://user-images.githubusercontent.com/27529229/115922416-dc91a600-a44a-11eb-80b5-abd59e97d51f.mp4

Your textboxes also look odd though, and that has me guessing that it's a missing package. Try:

`apt install gtk2-engines-murrine gtk2-engines-pixbuf`

If that doesn't help, try:

`gnome-themes-extra gnome-themes-extra-data`

**Comment by andrewshadura** [comment]
All four packages are installed and are at their latest versions.

**Comment by andrewshadura** [comment]
Right, I ran `gtk-chtheme`, and, to my surprise, it said that Ambiance was selected. This obviously wasn’t *completely* true, since this theme didn’t look exactly like Ambiance, but nevertheless I went ahead and changed it to Yaru — and then it normalised.

I guess, somehow I ended up with a mix of Ambiance and Yaru, I’m not sure how exactly.

**Comment by andrewshadura** [comment]
That would also explain why none of the changes I tried in the gtkrc file worked.
¯\\\_(ツ)_/¯

I guess I can close this issue :slightly_smiling_face:
