### ISSUE TITLE
Icons in GAJA shouldn't be green

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2584]
In GAJA, only the label should be green and the icon should have a slightly gray overlay, similar to icons in Nautilus.

![image](https://user-images.githubusercontent.com/3986894/106358823-d8079680-630e-11eb-8d74-1882c86000e5.png)

**Comment by Muqtxdir** [comment]
This is caused because caja, uses GtkFlowBox for icon-representation unlike nautilus
