### ISSUE TITLE
Wrong colors in Indicator applet

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2585]
The speaker and the Menu icons are #f2f2f2 but the rest is #dfdbd2

![image](https://user-images.githubusercontent.com/3986894/106359097-ae4f6f00-6310-11eb-96c3-6b58eeecfb8c.png)

**Comment by flexiondotorg** [comment]
These "symbolic" icons are shared between the old AMbiant/Radiant themes and Yaru MATE. Next cycle, 21.10, we can make sure those icons integrate with Yaru MATE.

**Comment by flexiondotorg** [comment]
The is fixed via https://github.com/ubuntu-mate/ubuntu-mate-artwork/releases/tag/22.04.7

**Comment by madsrh** [comment]
Thanks @flexiondotorg 👍
