### ISSUE TITLE
Mate panel: menu popover is overlapping

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2586]
Not sure if this is actually an issue, but the menu (or at least the border) is above the panel. Perhaps we should add a bit of space between the two, similar to the app preview in the bottom panel? 

![image](https://user-images.githubusercontent.com/3986894/106359290-0aff5980-6312-11eb-9fe0-c8ad303946c6.png)

For reference:
![image](https://user-images.githubusercontent.com/3986894/106359313-4ac64100-6312-11eb-8300-8b3d816c55c2.png)

**Comment by Muqtxdir** [comment]
Hi @madsrh 

The Popover in the first screenshot is a `GtkMenu` widget and in the second screenshot it is a `tooltip_text` property. So essentially both are different things so there's no way in `scss/css` to unify it without globally changing the look of `tooltip_text` (_which is really not a good idea_)

I hope Im making sense 😅

**Comment by madsrh** [comment]
Thanks for looking into this @Muqtxdir but the issue was poorly explained by me - sorry.
I only confused you by mention the tooltip. This probably isn't an issue at all, but you more clearly see the overlap in the image below. IMHO 1px down would be better (or more hence the tooltip reference 😉)

![Screenshot_20220313-222111__01](https://user-images.githubusercontent.com/3986894/158079908-0c7fde26-69fd-4dcf-a21a-883b08ecfc70.jpg)

**Comment by Jupi007** [comment]
Anyway this is not fixable (at least I didn't found a way to fix it).
I'm sorry @madsrh but I'm closing this :)
