### ISSUE TITLE
Network-server icon lacks contrast

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2587]
At small sizes the network-server icon just looks gray to me. Could anything be done to make the details stand out more, without ruining the style @ubuntujaggers?

![image](https://user-images.githubusercontent.com/3986894/106359940-1785b100-6316-11eb-9764-814118c607d6.png)

I'm on a 4k screen, so this might not be a problem for everyone else 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/3986894/106359826-46e7ee00-6315-11eb-950d-b17172dfe7c5.png)

**Comment by ubuntujaggers** [comment]
The suggested version is much better :+1:
