### ISSUE TITLE
Revisit tabs styling

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2588]
@clobrano @Feichtmeier I know that we've tweaked the tabs a ton of times 🙈 I don't recall why we landed with the current design (or maybe something changed), but having the label go darker on hover seems very unintuitive IMHO. 
Could we revisit or was there perhaps a larger issue blocking?
I remember that there was an issue with the black underline in this issue: https://github.com/ubuntu/yaru/pull/1983

![Peek 2021-01-30 16-54](https://user-images.githubusercontent.com/3986894/106361171-cb8a3a80-631c-11eb-8645-bc9e391135d5.gif)

![Peek 2021-01-30 16-55](https://user-images.githubusercontent.com/3986894/106361177-cfb65800-631c-11eb-9204-78cc530c47d0.gif)

Altso Mate:
![alt text](https://i.postimg.cc/fTF56RfT/Peek-2021-01-30-16-27.gif)

**Comment by Feichtmeier** [comment]
I personally would prefer if the label would not change at all only the underline

**Comment by madsrh** [comment]
> I personally would prefer if the label would not change at all only the underline

+1 exactly

**Comment by Feichtmeier** [comment]
@madsrh 
![ya](https://user-images.githubusercontent.com/15329494/107038103-51deca80-67bc-11eb-9fa5-ab1141a4394f.png)
![Peek 2021-02-05 14-11](https://user-images.githubusercontent.com/15329494/107038105-52776100-67bc-11eb-8354-7cf3882f290a.gif)

?
