### ISSUE TITLE
Popup window width

### ISSUE THREAD

**Issue by nenadcvele** [ubuntu/yaru#2590]
**Expected Behavior**

Logging out or opening Synaptic should show popup with background wide enough to cover all the content.

**Actual Behavior**

The popup window background is not wide enough, the text goes out of it.

**System information**
OS Debian 10 Buster
Gnome shell 3.30.2

**Yaru version**
20.10.6.1-109-g9b47c206

**Screenshots**
![Screenshot from 2021-01-31 20-29-44](https://user-images.githubusercontent.com/2467527/106395820-935e2700-6404-11eb-8b2e-acd514e54037.png)

**Comment by Feichtmeier** [comment]
The problem is that you use the wrong version of yaru for this old shell.
Focal has 3.36
Groovy 3.38
Current yaru master is 3.38

**Comment by nenadcvele** [comment]
What's the branch for 3.30? Sorry.

**Comment by Muqtxdir** [comment]
> What's the branch for 3.30? Sorry.

hi @nenadcvele,

If I'm not wrong for gnome 3.30, you could select the `bionic` branch

**Comment by nenadcvele** [comment]
@Muqtxdir 
Thanx, I got it working now :)
