### ISSUE TITLE
GitHub Action for GTK4 (master) branch observation

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2599]
Hi @didrocks 
Sorry for shamelessly assigning you to this :smile_cat: 

So, as we already observe GTK-3-24, gnome-shell and libhandy repos via GitHub Actions, we need another action to observe the GTK repo but this time the master branch, or in the future a gtk4 branch, if they again chose to create GTK5, 6, 7, ... GTK-n (with ```n ∈ ℕ``` :trollface: )

Would be nice to get this rolling before GTK4 hits Ubuntu.
Anyone else feel free to grab it from Didier.

**Comment by Jupiter007-43** [comment]
Sorry I forgotten to do this. I can do it if you want @didrocks.

**Comment by didrocks** [comment]
@Jupiter007-43: feel grab it from me :) It would be great to share the github Action knowledge :)
