### ISSUE TITLE
[icon-request] Nvidia X server settings icon

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#2610]
hi,

since **ubuntu-desktop** ships nvidia-drivers out of the box for users with nvidia-graphics cards, the current default icon is ugly and needs the yaru-ish style icon for it :-)

### useful-links:
https://github.com/pop-os/icon-theme/blob/master/src/bitmaps/apps/nvidia-settings.svg

### default-icon:
![Screenshot from 2021-02-05 23-39-07](https://user-images.githubusercontent.com/54065734/107072495-33a0bb00-680c-11eb-9daa-ca5fc1a417fc.png)

do you mind doing this one @Jupiter007-43 if you are free?

thanks!

**Comment by Jupiter007-43** [comment]
What do you think of?

![Capture d’écran du 2021-02-06 12-59-15](https://user-images.githubusercontent.com/36476595/107117541-34246a80-687b-11eb-9988-6775db164b84.png)

![Capture d’écran de 2021-02-06 12-57-35](https://user-images.githubusercontent.com/36476595/107117539-31c21080-687b-11eb-8b04-2de1f01ccc4f.png)

**Comment by madsrh** [comment]
> What do you think of?

Very Yaru-ish 😄 👍

**Comment by Muqtxdir** [comment]
really nicely done in yaru style @Jupiter007-43
