### ISSUE TITLE
I've never really liked the Yaru icon for Transmission

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#2651]
I don't think it's a bad icon at all but it doesn't really "pop" off the screen - the red looks quite muted on the grey - and also it's quite a liberal interpretation of the default Transmission icon.  This is what we've got:

![image](https://user-images.githubusercontent.com/38893390/107881966-b5fd3f00-6ede-11eb-8b92-ac4cf05d0b4a.png)

Whereas this is the official Transmission logo:

![image](https://user-images.githubusercontent.com/38893390/107881984-ca413c00-6ede-11eb-9528-5408e809188a.png)

I'm working on a Yaru icon that's more recognisable as the app's branding and would welcome any comments.  This is my work in progress (click to view so it's sharp):

![image](https://user-images.githubusercontent.com/38893390/107882013-f6f55380-6ede-11eb-8ff9-8a005ddcda89.png)

Dunno why my embedded images are blurry nowadays :shrug: but clicking should give you a fair representation.

**Comment by Feichtmeier** [comment]
That looks pretty cool right away! :gun: :+1:

**Comment by Jupi007** [comment]
Looks great 👍
