### ISSUE TITLE
toggle-switches in gtk theme require change to follow gnome-shell theme

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#2652]
hi,

I have been trying the newly refined dark-shell theme by @Feichtmeier, really liking it and it improves on the previous gnome-shell theme. While using it I noticed that the toggle-switch used in gnome-shell theme has a white-ish slider (this is much better than dark-previous one)

If it's supposed to be like this, it got me wondering that the toggle-switches in gtk dark-theme would look better if the slider is consistent with the slider used in shell-theme and would make the switches easier to look at

### screenshots:
![Screenshot from 2021-02-14 22-52-06](https://user-images.githubusercontent.com/54065734/107884013-76534900-6f18-11eb-98dd-d0f4e382a18f.png)

![Screenshot from 2021-02-14 22-46-34](https://user-images.githubusercontent.com/54065734/107883944-0775f000-6f18-11eb-8ccf-9df286c5c9a8.png)

thanks!

**Comment by Feichtmeier** [comment]
Yes the shell is now looking different than the gtk theme popovers and the switches. I think this is okay since the shell is now using  more of a OSD look like the volume OSD etc 
But I do like the white knobs much more so if the rest is okay I can align them. Eventually we could also make the gtk theme darker. But I don't think that the shell needs to look like the gtk theme

**Comment by Muqtxdir** [comment]
> But I do like the white knobs much more so if the rest is okay I can align them

Fingers crossed 🤞 for whenever this lands into gtk dark-theme

> Eventually we could also make the gtk theme darker. But I don't think that the shell needs to look like the gtk theme

I am onboard with this but I think this would require opinion of others as well, and comes close to this discussion #2644

**Comment by Feichtmeier** [comment]
@Muqtxdir 
Darkening the gtk theme and aligning menu and popover borders would look like this:
![Screenshot from 2021-02-15 14-47-57](https://user-images.githubusercontent.com/15329494/107954972-78abb680-6f9d-11eb-9f07-c50db0160dc2.png)
![Screenshot from 2021-02-15 14-47-26](https://user-images.githubusercontent.com/15329494/107954976-79444d00-6f9d-11eb-832c-12a26ddc7abb.png)
![Screenshot from 2021-02-15 14-46-49](https://user-images.githubusercontent.com/15329494/107954980-79dce380-6f9d-11eb-8dd0-688d712586ee.png)

**Comment by Feichtmeier** [comment]
Okay this was maybe a little bit too dark. This could be closer to the spot:
![grafik](https://user-images.githubusercontent.com/15329494/107959076-2e2d3880-6fa3-11eb-95fa-4e7d3e6da9f2.png)

On topic of the switch handles, the shell sliders are not so big though. So I would keep them like they are and also keep the gtk sliders like they are.

**Comment by Muqtxdir** [comment]
wow! this looks fantastic in screenshots 😃

**Comment by Feichtmeier** [comment]
I am still thinking what to do with this. 
I think it would be the best to align the shell to the gtk sliders again. This bright slider just pops out too much in gtk

**Comment by elioqoshi** [comment]
How about using a slightly brighter slider than the original darker gray used in gtk? I agree the bright slider pops out too much (imagine having a completely black slider on a light theme). 

Eventually a brighter aubergine might help with adding contrast here as well (I assume this aubergine is an Ubuntu brand colour).

I could give it a go and do a few mockups experiments tomorrow if you like so we can finetune it.

**Comment by Feichtmeier** [comment]
Thanks @elioqoshi will sort this one next out after we've settled down a good solution for the darker dark gtk theme :smile_cat:

**Comment by Feichtmeier** [comment]
@elioqoshi could you give me a good color tip for the slider handles? I would like to get this done today before UI freeze

**Comment by elioqoshi** [comment]
@Feichtmeier are you referring to instances like this?
![image](https://user-images.githubusercontent.com/5436686/109939498-6a65d600-7cd1-11eb-929b-65c3e744c60f.png)

Could you show me a few examples where else these would appear?

**Comment by Feichtmeier** [comment]
> @Feichtmeier are you referring to instances like this?
> ![image](https://user-images.githubusercontent.com/5436686/109939498-6a65d600-7cd1-11eb-929b-65c3e744c60f.png)
> 
> Could you show me a few examples where else these would appear?

Basically only there in the shell and in the calendar with that switch. Switches are assets, sliders CSS. But I can colour both as we wish. I like the idea of bringing gtk and shell sliders closer together but I'm not sure which darkened white you like

**Comment by elioqoshi** [comment]
Got it. I will check a bit later today with a few thoughts.

**Comment by elioqoshi** [comment]
@Feichtmeier 

Here is what I'd suggest:

![image](https://user-images.githubusercontent.com/5436686/109979124-d6126800-7cfe-11eb-9cdc-4d7d7e3f859f.png)

The colour of the slider background would be Light Aubergine 80% and the slider button Warm Gray.
These are all Ubuntu brand colours:
https://design.ubuntu.com/brand/colour-palette/#tints

What do you think?

**Comment by Feichtmeier** [comment]
Really cool idea, like this very much. 
Needed to lighten it up for the light theme a bit though, hope this was okay?
![Screenshot from 2021-03-04 16-16-01](https://user-images.githubusercontent.com/15329494/109985418-05c46e80-7d05-11eb-91d4-e6c8a0c9e87e.png)
![Screenshot from 2021-03-04 16-29-28](https://user-images.githubusercontent.com/15329494/109987325-d151b200-7d06-11eb-866e-68d346bc2a0a.png)
Let's see what the others think CC @madsrh @Jupi007

**Comment by elioqoshi** [comment]
@Feichtmeier Great!

For the light theme feel free to get any of the warm gray colors on the bright side:

![image](https://user-images.githubusercontent.com/5436686/109991796-f0524300-7d0a-11eb-961e-8de3187ce7ce.png)


Maybe around 20%?

**Comment by Feichtmeier** [comment]
Hmmm, I would stick to white for the light theme if this is okay. I think they need to pop out here

**Comment by Feichtmeier** [comment]
But this reminds me that we should update the palette to match the canonical palette. This mish mash we currently have annoys me since some time :D But not for now, maybe next cycle

**Comment by madsrh** [comment]
Your mockup looks great @elioqoshi, but the colors seems a bit different from the screenshots by @Feichtmeier 🤷‍♂️ 
Could we land on something in between the current and the suggested? 

For the slider: I agree that the 80% aubergine looks better than the current pale washed out aubergine, but we made it brighter so it would pop out and I think making it that dark isn't great for usability. Something in the middle might work.

The toggle-switch / knob: The warm gray (#aea79f) looks a bit too dark next to the "white" labels IMHO. Again, I think something in between would look good. 

This is just my opinion and I'm referring to the shell (and the dark theme) 😃 

![image](https://user-images.githubusercontent.com/3986894/110009022-b853fb80-7d1c-11eb-9f25-b043994d2274.png)

**Comment by Feichtmeier** [comment]
@madsrh when you say lighter than `#77216F` do you mean more saturated or actually lighter?
http://scg.ar-ch.org/
You can play there a bit
![grafik](https://user-images.githubusercontent.com/15329494/110010389-89d72000-7d1e-11eb-87d9-bc4cb0889632.png)
![grafik](https://user-images.githubusercontent.com/15329494/110010422-9196c480-7d1e-11eb-91ce-894bf46bbef3.png)

**Comment by Jupi007** [comment]
> Really cool idea, like this very much.
> Needed to lighten it up for the light theme a bit though, hope this was okay?
> Let's see what the others think CC @madsrh @Jupi007

I have two suggestions:
- Maybe use a less saturated purple? I think the color `#aa5a94` from @elioqoshi mockup looks perfect.
- Also, the slide handle on dark theme is too dark. IMO that grey doesn't contrast enough with the background.

Anyway, that will be a good improvement 👍

**Comment by Feichtmeier** [comment]
I try to get closer to the purple today @madsrh @Jupi007 
But I have my veto on changing that warm gray 😸  I think it looks fantastic and would like to keep it if you are okay with this?!

**Comment by elioqoshi** [comment]
> Also, the slide handle on dark theme is too dark. IMO that grey doesn't contrast enough with the background.

I don't think that's an issue at all. The contrast is very high for legibility and accessibility purposes. You also don't want sharp black/white contrast on dark theme so softening it with a gray is often a good approach.

**Comment by madsrh** [comment]
I haven't had time to play further with the colors @Feichtmeier but I'll say this after viewing this thread on my phone outside (not the most common use case), the purple in your screenshot below isn't visible at all:

https://user-images.githubusercontent.com/15329494/109987325-d151b200-7d06-11eb-866e-68d346bc2a0a.png

**Comment by Feichtmeier** [comment]
![Screenshot from 2021-03-05 11-09-02](https://user-images.githubusercontent.com/15329494/110100912-41157a80-7da3-11eb-9d78-73aa9bee525d.png)
This is 5% lighter for the dark theme, is this better @madsrh ?
I also need to fix both the gtk <) asset and the shell switch assets after we've decided here

**Comment by Feichtmeier** [comment]
Sorry now with refreshed gtk as well:
![Screenshot from 2021-03-05 11-11-40](https://user-images.githubusercontent.com/15329494/110101246-9a7da980-7da3-11eb-82a3-d996e97ebf0b.png)

**Comment by madsrh** [comment]
@Feichtmeier I am very happy with this suggestion 👍 Is this okay for you @elioqoshi ?

@clobrano raised the concern of allow different tones of color, rather than using the same everywhere. I think we have to tweak the color in some places. Anyway, I just wanted to bring it up, so this is a deliberate decision.

**Comment by elioqoshi** [comment]
This looks great to me too!

**Comment by Jupi007** [comment]
@Feichtmeier I just tested your PR. I think it's perfect.
Current dark theme color scheme is very sad 😅

> I don't think that's an issue at all. The contrast is very high for legibility and accessibility purposes. You also don't want sharp black/white contrast on dark theme so softening it with a gray is often a good approach.

You're right @elioqoshi.
My previous opinion was only based only on the screenshot. In fact, those grey slide handle look very good in action and there's no contrast problem ^^
