### ISSUE TITLE
The color of the sidebar in Files is orange instead of gray

### ISSUE THREAD

**Issue by lekegf** [ubuntu/yaru#2666]
**Expected Behavior**

To see the gray color on sidebar in Files, following the Adwaita approach.

**Actual Behavior**

There's the orange color instead, in both active and non-active windows.

**Steps to Reproduce the Problem**

1. Open nautilus
2. Spot at the sidebar to see the orange color
3. Change the theme to Adwaita to see the difference 

**Software that presents the issue**

- Files
- OS version: Ubuntu 20.04.2

**Yaru version**

- Version: 20.04.10.1

**Screenshots**
![Captura de tela de 2021-02-18 01-32-46](https://user-images.githubusercontent.com/62917388/108307981-b0795080-718d-11eb-88ec-c586516e1f7c.png)
![Captura de tela de 2021-02-18 01-32-05](https://user-images.githubusercontent.com/62917388/108307985-b3744100-718d-11eb-9188-566adc9ba939.png)

**Comment by Feichtmeier** [comment]
Hi there.. I'm very much thinking the same.
And I've brought this up many times. We've even had grey sidebars in master for some time before the upstream rebase.

But I disagree that we should only make the Nautilus sidebars gray. If we do gray sidebars again it needs to be for all sidebars. And as far as I know that's the case in gtk4 sidebars and the only reason why it's still blue in Gtk3 is lack of will to backport.

**Comment by Feichtmeier** [comment]
CC @waynecrosby

**Comment by elioqoshi** [comment]
We should not rush into this I'd suggest. It's a pretty impactful change and we should consider it well and do a few proposals before deciding. These are what I noticed:

- The active item background colour is definitely a branding decision in Ubuntu, it emphasizes to the user that this is Ubuntu (similar to how the Terminal background is a dark aubergine).
- The Ubuntu orange has potentially accessibility issues with white text. It fails WCAG 2.0 AA requirements. This is some interesting research though: https://www.bounteous.com/insights/2019/03/22/orange-you-accessible-mini-case-study-color-ratio/
- If the Ubuntu orange is used on light, it should likely not be used on dark, it's the wrong equivalent.

We might need to discuss this a bit more thoroughly before coming up with solutions.

**Comment by Feichtmeier** [comment]
@elioqoshi I agree 

I would appreciate some mock-ups
And/or getting inspired by thise thread and nice ideas by @madsrh 
https://discourse.ubuntu.com/t/design-mockups-updates-designer-only/2053/7
https://discourse.ubuntu.com/t/design-mockups-updates-designer-only/2053/8
![](https://ubuntucommunity.s3.dualstack.us-east-2.amazonaws.com/original/1X/0132301217ad5cae2bdf468de55b693ef5e302d4.jpg)
![](https://ubuntucommunity.s3.dualstack.us-east-2.amazonaws.com/original/1X/632398c0bea53875fbfeb807527fc48d894da20e.jpg)
Also keep in mind that gtk4 moved away from those colored rectangles and moved to rounded soft gray selections for sidebars

**Comment by elioqoshi** [comment]
@Feichtmeier These look great! However the legibility is being compromised for aesthetics which is not ideal. It could work with more contrastful text labels though. The green is also too light for white text to be read properly.

If Gtk4 moved away from full highlights on the side bar items, we might want to do that too? That creates some nice compromise between branding and legibility.

Quick mockup: 
![image](https://user-images.githubusercontent.com/5436686/108380437-1e159300-7207-11eb-8c63-2356f81ef3e7.png)

**Comment by Feichtmeier** [comment]
I like this very much - if you get  go from the branding department (if you aren't this department yourself :D) I can create a pull request for this

**Comment by elioqoshi** [comment]
We should probably have @waynecrosby have a look at it :)

**Comment by Feichtmeier** [comment]
I'll set up a test branch later - aubergine for dark sounds like a good idea, or darken the orange more

**Comment by elioqoshi** [comment]
> or darken the orange more

There is no darker orange in Ubuntus brand palette: https://design.ubuntu.com/brand/colour-palette/#tints
A darker orange would end up being muddy and not really orange anymore. That's the issue with yellow and orange...

It's an issue I raised on various other Ubuntu things and we have no solution yet.

**Comment by Feichtmeier** [comment]
@elioqoshi there is one problem with using purple as the primary accent color for the gtk dark theme: the shell. If we go for purpler, the shell accents remain orange, or if we go for purple in the shell it would be inconsistent with the two light gtk themes : /

**Comment by Feichtmeier** [comment]
@elioqoshi I didn't manage to round up the edges of this little orange bar, but this is possible:

![image](https://user-images.githubusercontent.com/15329494/108525796-c6435e80-72d0-11eb-9eeb-069724a02f6e.png)
![image](https://user-images.githubusercontent.com/15329494/108525947-e3782d00-72d0-11eb-9487-6b66c59a4791.png)

or without the little space at the left
![image](https://user-images.githubusercontent.com/15329494/108526236-2c2fe600-72d1-11eb-8954-45b60c1c69ae.png)
![image](https://user-images.githubusercontent.com/15329494/108526315-44a00080-72d1-11eb-9142-cbc910b4f78d.png)

**Comment by Feichtmeier** [comment]
better backdrop + treeview selection

![Screenshot from 2021-02-19 17-00-52](https://user-images.githubusercontent.com/15329494/108528896-330c2800-72d4-11eb-95f5-badd281474c8.png)

**Comment by Jupi007** [comment]
I love this design.
Personally I prefer without padding-left.

**Comment by elioqoshi** [comment]
Same! The paddingless version looks great!

**Comment by Feichtmeier** [comment]
> Same! The paddingless version looks great!

Nice! 
Are the branding guys okay with this? :)

**Comment by elioqoshi** [comment]
@Feichtmeier we should get an update today :)

**Comment by waynecrosby** [comment]
@Feichtmeier @madsrh @elioqoshi The no padding visuals look great, they are a lot more subtle than the previous highlights used and echo the 'selected' pattern we use in some of our web apps and across the web. I'm happy with them as long as we're sure the contrast is strong enough. 
Also, on the dark mode version, can we echo what is used on the light version, so knock back the selected text and use a slight grey panel for the window behind, see below:

![darkmode](https://user-images.githubusercontent.com/42238722/108707066-70a4c700-7507-11eb-8706-0be64c5f041c.png)

**Comment by elioqoshi** [comment]
@waynecrosby That generally is a good direction, I just am wary that the contrast ratio here is too low. We should strive for 4.5 while it's 3.93 here.

![image](https://user-images.githubusercontent.com/5436686/108712886-ba95a900-7517-11eb-8672-b5f1c738b2e7.png)


Having the text slightly lighter or the backdrop slightly darker (or a combination of them) should do the trick. We need to also make sure to do the equivalent in the light theme @Feichtmeier

**Comment by Feichtmeier** [comment]
Created a pull request to test :) Let's swap over everyone
