### ISSUE TITLE
gnome-shell 40: process changes to yaru

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2667]
- [ ] wait for gnome-shell 40 to land in Ubuntu (probably 21.10)
- [x] copy+paste scss code from upstream->src
- [x] reapply the Yaru redesign

**Comment by chrisjbillington** [comment]
For what it's worth, users of the shell themes on Arch Linux (there are dozens of us!) will be getting GNOME 40 in the coming weeks. This means:

1. unless we're lucky and the theme works as-is, we will sadly have to stop using the Yaru shell themes until this update is done

2. once this update is done, we will help test and report bugs!

**Comment by Feichtmeier** [comment]
Eventually, which would be very helpful for us as well, @3v1n0 could create a PPA with gnome 40 for me, then I can work on it before it hits 21.10 daily
