### ISSUE TITLE
Icons: libre office app icons could be improved

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2668]
This is how they look in yaru
![grafik](https://user-images.githubusercontent.com/15329494/108365758-dc312080-71f7-11eb-881b-3083888d040c.png)

and this is how they look without yaru
![grafik](https://user-images.githubusercontent.com/15329494/108365916-0edb1900-71f8-11eb-8e27-44d0a590ed62.png)

Though the idea of yaru-fying the baseplate is great, the mix with the inside symbols looks a bit inconsistent to me.
As the libre office designers already agreed that we (the yaru team/ubuntu) can do what we want with the icons (at least this is what they said last year), couldn't we also yarufy the inner symbols?

CC @ubuntujaggers

**Comment by elioqoshi** [comment]
I could have a go at this. Do we have the source files of the icons handy?

**Comment by Muqtxdir** [comment]
> I could have a go at this. Do we have the source files of the icons handy?

Sure we do have them, the source files are placed under /icons/src/apps

**Comment by elioqoshi** [comment]
>  Sure we do have the source SVG files, they are placed under /icons/src/full-color/apps (https://github.com/ubuntu/yaru/tree/master/icons/src/fullcolor/apps)


Thanks! I am not familiar with the project structure yet :)

**Comment by elioqoshi** [comment]
Here is a quick sketch where I made everything a bit fluffier basically. Might not be perfect but probably closer to the current Yaru style?

![image](https://user-images.githubusercontent.com/5436686/108393682-2c1de080-7214-11eb-80be-1e64d9e9741f.png)

**Comment by elioqoshi** [comment]
What if we do some colour corrections? I find it to be confusing when you are looking for Calc and there are other colours present. Similar to Draw, it is very close to the Impress colour (original LibreOffice Draw is a brighter yellow).

Here is another proposal building on this:

![image](https://user-images.githubusercontent.com/5436686/108395544-304afd80-7216-11eb-9c4a-abe713cce58d.png)

**Comment by Muqtxdir** [comment]
wow, these new sketches are so fine-tuned

**Comment by Feichtmeier** [comment]
I like both the form changed to be more round and the colours to be unified. The different colours in the icons was probably also what made it a little bit chaotic for me.
Really cool :+1:

**Comment by ubuntujaggers** [comment]
No objection from me - I was happy with the current icons but these look like improvements :)

**Comment by elioqoshi** [comment]
Great! I will try to have a look and tweak the smaller resolution icons as well

**Comment by elioqoshi** [comment]
Here is a first draft of Calc. I tried to not alter the smaller resolution round corners too much as I don't think they will be noticeable on these small sizes anymore and anti-alias might make them worse. We might need to some testing on how these look in production.

![image](https://user-images.githubusercontent.com/5436686/108503512-cb92b000-72b4-11eb-8cea-0340db0cc567.png)

**Comment by Feichtmeier** [comment]
@elioqoshi you think you could get this in for 21.04? Do you need help on the PR?

**Comment by elioqoshi** [comment]
@Feichtmeier Yeah I think I can give this a go and wrap up the designs this week. Would anyone be able to help out with ensuring the SVG's are correctly aligned?

**Comment by elioqoshi** [comment]
Finished:

![image](https://user-images.githubusercontent.com/5436686/111437693-ac484080-8703-11eb-85a7-745a986cde11.png)
