### ISSUE TITLE
"Legacy icons" aren't Free Desktop compliant or done properly

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#2669]
We've got a lot of legacy colour icons which look pretty good, but I think we need to pause and do them properly (I'm not including the LibreOffice icons because those exist in their own sort of bubble).

The icons in question don't get exported from Src like our other colour icons because they're not the same sizes (22px is one that gets used).  Also there are duplicate icons instead of symlinks.  I can do the symlinks, but if I make a full colour icon template to put in Src with 22px and any extra sizes, can someone make the script work with it?

Also, we call them "legacy icons", but it's basically just colour icons with names from the following list, which people will use in their apps:

https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html

We don't have to worry about stuff like mimetypes and apps because we already have good coverage (bigger than the list).  However, actions and categories in Suru are typically symbols.  Now we're in the business of having full colour versions of the actions, I think we should use the Free Desktop spec as a checklist and do them properly in _all_ sizes, with a script to export the pngs, and with symlinks for names that aren't part of the spec but still get used.

I can start by making the Src template with the extra sizes, but can anyone help with updating the script so it exports the extra sizes when they're present?  Then I can start working down the list and turning all those existing 16px icons into full templates, and any of our icon designers are welcome to help with that :)

**Comment by Feichtmeier** [comment]
@ubuntujaggers totally agree. This would be nice. I try to help you with the script.

**Comment by Feichtmeier** [comment]
Looked over the script, actions is already part of the dir array and the subdirs paths are created if they do not exist and the subdir names are created

**Comment by ubuntujaggers** [comment]
Can it handle additional sizes (e.g. 22px)?

**Comment by ubuntujaggers** [comment]
Actually I think it will, remember when it was automatically making folders for stuff like 47.98687667 because the template wasn't quite right? I think it just exports what it finds, I'll try.

**Comment by Feichtmeier** [comment]
I think it's based on the layers but will check again

**Comment by Jupi007** [comment]
I agree in all points with you @ubuntujaggers 
If you need more help, feel free to ask.

About design: will "actions" icons being flat or are we going to do them in full Yaru style at all sizes?

**Comment by ubuntujaggers** [comment]
I think we should definitely keep them flat at 16px at least

**Comment by Feichtmeier** [comment]
I would even start with the flat style at 22px
Those highlights and shadows lose their purpose at those tiny sizes in my opinion

**Comment by elioqoshi** [comment]
Agreed. On such small sizes flat icons will have better legibility.

**Comment by Jupi007** [comment]
> Can it handle additional sizes (e.g. 22px)?

@ubuntujaggers If you want to add a new size to an icon, you just need to add a new baseplate (duplicated an existent one is the simpler way) with, for example, the **inkscape:label="22x22"** attribute:

![1](https://user-images.githubusercontent.com/36476595/108596341-b7b67f00-7384-11eb-8f16-078d8b13eb74.png)

**Comment by Amr-Ibra** [comment]
A comment on the "legacy" naming: it came originally from upstream GNOME Adwaita because they wanted to deprecate the coloured action icons and replace them with symbolic action icons in their native apps, and let third-party apps either use the symbolic action icons or ship their own coloured action icons. However, that hasn't really taken off because until this day a lot off third-party apps still rely on the coloured action icons that are shipped by the system icon theme, e.g. all third-party GTK2, GTK3 apps (Evolution, Inkscape, GIMP, Transmission, Geany) and all KDE and Qt apps.

Another big example is elementary OS, they rely on coloured action icons in their native GTK3 apps:
https://elementary.io/docs/human-interface-guidelines#action-icons
https://github.com/elementary/icons
