### ISSUE TITLE
Plymouth help

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#2674]
hello,  in 20.04 Plymouth, I see 

throbber.svg, 
throbber-0001 to 0030 and 
animation-0001 to 0036

It would be nice to know what they do. I assume that throbber 1-30 PNGs is the rotation steps and if we replace it with our own, it should work.

What does animation 1-36 PNGs do ? It looks like steps of opacity

Also, what is the purpose of throbber.svg . Is there anything we need to be careful about while replacing it ? Thanks.

**Comment by Feichtmeier** [comment]
Hi @meetdilip 
Yeah I've spent some fun time to rotate that dozens of spinners for 20.04
The repo is in  freed desktop gitlab
Let me find it

You need both spinner and throbbed, don't remember why xD

**Comment by Feichtmeier** [comment]
@meetdilip here it is: https://gitlab.freedesktop.org/Feichtmeier/plymouth/-/tree/master/themes/spinner

**Comment by meetdilip** [comment]
Hi, I blindly replaced the throbber images and could get nice results. But when I rotate a square there is some colour bleeding around the corners. But I have no idea what throbber.png and animation-0 to36 do. I ask because there seem some parts where only the Ubuntu logo is there in custom Plymouth, but in default, there used to be the spinner.

**Comment by Feichtmeier** [comment]
> Hi, I blindly replaced the throbber images and could get nice results. But when I rotate a square there is some colour bleeding around the corners. But I have no idea what throbber.png and animation-0 to36 do. I ask because there seem some parts where only the Ubuntu logo is there in custom Plymouth, but in default, there used to be the spinner.

The throbber is the spinner that always looks the same. But at some point, when the system is about to boot the animation is loaded which has a little fade out at the end

**Comment by meetdilip** [comment]
Thanks. throbber.SVG, does it have any specific function ?
