### ISSUE TITLE
ubuntu startx error

### ISSUE THREAD

**Issue by Steve-God** [ubuntu/yaru#2680]
X.Org X Server 1.19.6
Release Date: 2017-12-20
[  1285.878] X Protocol Version 11, Revision 0
[  1285.878] Build Operating System: Linux 4.15.0-124-generic x86_64 Ubuntu
[  1285.878] Current Operating System: Linux ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64
[  1285.878] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-87-generic root=UUID=535b2e54-2659-4d31-904f-fe8fc83565a9 ro
[  1285.878] Build Date: 30 November 2020  08:01:56PM
[  1285.878] xorg-server 2:1.19.6-1ubuntu4.8 (For technical support please see http://www.ubuntu.com/support)
[  1285.878] Current version of pixman: 0.34.0
[  1285.878]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[  1285.878] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1285.879] (==) Log file: "/var/log/Xorg.0.log", Time: Sat Feb 27 02:20:48 2021
[  1285.882] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  1285.884] (==) No Layout section.  Using the first Screen section.
[  1285.884] (==) No screen section available. Using defaults.
[  1285.884] (**) |-->Screen "Default Screen Section" (0)
[  1285.884] (**) |   |-->Monitor "<default monitor>"
[  1285.885] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  1285.885] (==) Automatically adding devices
[  1285.885] (==) Automatically enabling devices
[  1285.885] (==) Automatically adding GPU devices
[  1285.885] (==) Automatically binding GPU devices
[  1285.885] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  1285.890] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1285.890]    Entry deleted from font path.
[  1285.890] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1285.890]    Entry deleted from font path.
[  1285.890] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1285.890]    Entry deleted from font path.
[  1285.890] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  1285.890]    Entry deleted from font path.
[  1285.890] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1285.890]    Entry deleted from font path.
[  1285.890] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1285.890]    Entry deleted from font path.
"/var/log/Xorg.0.log" 227L, 14930C

**Comment by Feichtmeier** [comment]
Hello @Steve-God 
Why do you think your startx error is related to yaru?

**Comment by Steve-God** [comment]
This is my log，I don't know where I was wrong.

**Comment by Steve-God** [comment]
I think it should be the monitor

**Comment by Feichtmeier** [comment]
Okay, thanks for contributing to the yaru project, but this is not the operating system Ubuntu issue reporting site, we only make the Ubuntu looks. Best would be if you go to https://bugs.launchpad.net/ubuntu/+source/xorg-server 
Closing is issue as it is not related to yaru

**Comment by Steve-God** [comment]
okay，thank you
