### ISSUE TITLE
hand cursor is white which doesn't match with other forms

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2686]

**Comment by Feichtmeier** [comment]
@madsrh and @ubuntujaggers could you explain why we ended with the white hand?

**Comment by madsrh** [comment]
@kothekarswaraj could you elaborate what you mean by "forms"?

If you're referring to the black pointer and white hand cursor, we've discussed this earlier:

> Looking at [another OS that uses a black pointer](https://daviddarnes.github.io/mac-cursors/), I think this works fine. The pointer and the hand are two different things IMO - like the spinner (we don't want a black spinner with a white outline).
