### ISSUE TITLE
New power mode icons in GCC 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2695]
power-profile-balanced-symbolic.svg power-profile-performance-symbolic.svg power-profile-power-saver-symbolic.svg are new icons in gnome control Center

Would be nice to get them in for hirsute
CC @Jupi007 @ubuntujaggers 

![IMG_20210306_100319_862.jpg](https://user-images.githubusercontent.com/15329494/110201410-34f0f200-7e63-11eb-95c8-46fe78371d58.jpg)

**Comment by Jupi007** [comment]
Sorry I did a mistake by pushing directly to master... 😰
@Feichtmeier Can you test? I don't have a laptop so I can't do it by myself.
