### ISSUE TITLE
Missing line spacing in Ubiquity

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2697]
Let's fix this if Ubiquity stays for another LTS release - it's currently marked as _low priority_ since a new installer is coming 🤞 
On this "page" in the install, the lines could use a bit more space:

![image](https://user-images.githubusercontent.com/3986894/110206753-f87fbf00-7e7f-11eb-8fc9-9634c54267fd.png)

In comparison, here's a screenshot with the normal spacing:

![image](https://user-images.githubusercontent.com/3986894/110206748-f289de00-7e7f-11eb-944d-b3beabbb9827.png)

**Comment by Muqtxdir** [comment]
Hi @madsrh 

This is not a yaru-issue, it is caused due to no use of proper-margins in ubiquity's GTK-frontend. That being said this is resolved (_see screenshot below_)

![ubiquity](https://user-images.githubusercontent.com/54065734/158031566-f7bf1a4f-67cf-475c-97f6-91ef3c866440.png)

**Comment by madsrh** [comment]
Thanks @Muqtxdir 👍
