### ISSUE TITLE
Avatar / circle size

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2698]
![image](https://user-images.githubusercontent.com/3986894/110207710-9cb83480-7e85-11eb-8877-c3998021c280.png)

![image](https://user-images.githubusercontent.com/3986894/110207938-6e872480-7e86-11eb-85c8-8113d73f5897.png)

**Comment by Muqtxdir** [comment]
Also happens on Yaru-light gnome-shell theme and it's totally white

### screenshot:
![Screenshot from 2021-03-06 21-49-14](https://user-images.githubusercontent.com/54065734/110213466-2f78c380-7ec6-11eb-8e93-124212111adc.png)

**Comment by Feichtmeier** [comment]
uhm, what gnome-shell version is installed? Maybe we missed some upstream change prior to gnome shell 40
