### ISSUE TITLE
Align toggle switches in GTK / Shell

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2699]
Is there any chance that we could add a lighter background to the GTK switches like the shell has for the toggle-off state? @Feichtmeier @Jupi007 

![image](https://user-images.githubusercontent.com/3986894/110208141-ac387d00-7e87-11eb-9b44-d12d4b2a9df9.png)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/110235329-bf9f2300-7f2f-11eb-9750-d708f3afe4c9.png)
Is this ok?

**Comment by madsrh** [comment]
Perfect @Feichtmeier 🎉🤘👍👌😎👏

**Comment by Feichtmeier** [comment]
Cool saw your :tada: before merge ;)
@Jupi007 could you align the gtk4 switches if you have time until 18th?

**Comment by Jupi007** [comment]
I'll do it 👌
