### ISSUE TITLE
KolourPaint icon doesn't match on dock and application overview

### ISSUE THREAD

**Issue by lekegf** [ubuntu/yaru#2709]
**Expected Behavior**

To see the same icon of KolourPaint in both, dock and application overview.

**Actual Behavior**

It's shown two different icons.

**Steps to Reproduce the Problem**

1. Install KolourPaint
2. Open application overview and look for it. Pay attention to the icon it shows.
3. Open KolourPaint
4. Look to the KolourPaint icon on the dock, and you'll see it's different.

**Software that presents the issue**

- Name: KolourPaint
- Version: 19.12.3
- OS version: Ubuntu 20.04

**Yaru version**

20.04.10.1

**Screenshots**

![Captura de tela de 2021-03-07 21-47-52](https://user-images.githubusercontent.com/62917388/110262000-fce7cd00-7f90-11eb-859c-0f7e138f73fb.png)

Observation: the same happens with the Kdenlive icon.

**Comment by Feichtmeier** [comment]
Hmmm, we do not have a kolour paint icon in our icon set. So, I am pretty sure that Yaru is not the reason of this problem :smile_cat: 
Did you install it via snap?
