### ISSUE TITLE
Wrong corners on no-csd windows.

### ISSUE THREAD

**Issue by Initu** [ubuntu/yaru#2715]
In the Unity and Cinnamon environments there are rounded corners on the no-csd windows as shown in the image below.
![WhatsApp Image 2021-03-10 at 18 06 30](https://user-images.githubusercontent.com/25691315/110704859-50962880-81d4-11eb-8a1d-db24968dae19.jpeg)
![b1f5f701-0ec8-4574-a0ff-b3b3af74fe66](https://user-images.githubusercontent.com/25691315/110704879-58ee6380-81d4-11eb-8732-c2b05a263cf8.jpeg)

The solution is to add these lines to the file tweaks.scss as shown in the image below.
![883b7db1-bb34-47c7-a6fc-87b2cb248ae2](https://user-images.githubusercontent.com/25691315/110705041-94892d80-81d4-11eb-8b3c-7825d121a9f1.jpeg)

After inserting these lines I built the theme and the problem was solved as shown in the image below.
![f197b469-2f37-47b0-b08f-b9213c6fca39](https://user-images.githubusercontent.com/25691315/110705207-d31ee800-81d4-11eb-9221-84236cc995d1.jpeg)
![WhatsApp Image 2021-03-10 at 19 06 05](https://user-images.githubusercontent.com/25691315/110705216-d74b0580-81d4-11eb-82a6-b242d9261491.jpeg)

I report this problem here because I don't know how to add PR.

**Comment by Feichtmeier** [comment]
Thanks, looks great!
How does this affect gnome apps in mate that feature CSD? I know, looking at the selector it should be fine, but sometimes there are edge cases

**Comment by Initu-Castilhos** [comment]
> Obrigado, parece ótimo!
> Como isso afeta os aplicativos gnome no mate que apresentam CSD? Eu sei, olhando para o seletor deve funcionar, mas às vezes há casos extremos

It does not affect anything, in Cinnamon you can see that the gnome-disk application does not affect it.

**Comment by Feichtmeier** [comment]
I will push it only to hirsute/mate for now, since this needs testing before we destroy something in default gnome (which is the ubuntu default)
Thank you very much for the fix

**Comment by Initu** [comment]
> Vou empurrá-lo apenas para hirsute / mate por enquanto, já que isso precisa de testes antes de podermos destruir algo no gnome padrão (que é o padrão do ubuntu)
> Muito obrigado pela correção

The compilation did not work, there is a typo. You have to type a dot in front of the word background to work well.
![Captura de tela de 2021-03-13 15-07-28](https://user-images.githubusercontent.com/25691315/111039656-ec5ea900-840d-11eb-9c80-a96c09cfec0b.png)

**Comment by Feichtmeier** [comment]
Sorry, fixed :)

**Comment by Initu-Castilhos** [comment]
> Desculpe, consertado :)

👍🏼
