### ISSUE TITLE
Add Unity theme in Yaru-dark and Yaru-light.

### ISSUE THREAD

**Issue by Initu** [ubuntu/yaru#2716]
Add Unity theme in Yaru-dark and Yaru-light.

**Comment by Feichtmeier** [comment]
I am not sure what you are refering to? We have our three themes and unity window controls, what do you mean?
https://github.com/ubuntu/yaru/tree/master/gtk/src/default

**Comment by Initu-Castilhos** [comment]
> Não tenho certeza do que você está se referindo? Temos nossos três temas e controles de janela de unidade, o que você quer dizer?
> https://github.com/ubuntu/yaru/tree/master/gtk/src/default

Desculpe, não fiz os testes.

**Comment by Feichtmeier** [comment]
yaru-unity-theme is not part of this repository

```
frederik@carbon:~$ sudo apt install yaru-theme-
yaru-theme-gnome-shell  yaru-theme-icon         yaru-theme-unity
yaru-theme-gtk          yaru-theme-sound  
```
