### ISSUE TITLE
Make GtkSourceView theme to automatically switch variant

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/yaru#2732]
Not sure if this is feasible at theme level, but leaving it here as it's something we'd expect.

I wanted to make yaru to be the default color scheme for gedit (by setting it in `org.gnome.gedit.preferences.editor scheme`), however, by doing this we've to pick a variant and this will not work well with the Appearance settings were we choose the gtk variant.

So, ideally we'd expose a "Yaru" theme (probably with no background?) that will react accordingly to the selected gtk variant.

**Comment by 3v1n0** [comment]
@flexiondotorg maybe you know better about this? :)

**Comment by flexiondotorg** [comment]
AFAIK, the GTK Source View spec has not actually changed since the GTK 2 days and there is no provision to make styles dynamic based on principle colours of the selected GTK theme.

Changing the GTK Source View style for gedit via GNOME settings would be a partial solution.

**Comment by Muqtxdir** [comment]
closing this as `gnome-control-center` appearance panel also changes the gedit's color scheme as well starting with ubuntu 21.10
