### ISSUE TITLE
Could we use Yaru cursors packages without installing the theme as whole?

### ISSUE THREAD

**Issue by UltraBurstXD** [ubuntu/yaru#2733]
Hi,
I think it would be helpful if the Yaru cursors was separated from it's main package, because it'd make things easy when porting the cursors to others Linux distros without the need to install the whole theme. Like:

- yaru-theme-gnome-shell: Yaru GNOME Shell desktop theme from the Ubuntu Community
- yaru-theme-gtk: Yaru GTK theme from the Ubuntu Community
- yaru-theme-icon: Yaru icon theme from the Ubuntu Community
- yaru-theme-sound: Yaru sound theme from the Ubuntu Community
- yaru-theme-unity: Yaru Unity theme from the Ubuntu Community

In real case, Ubuntu Budgie only has DMZ-White/Black out-of-the-box, it would be of great help if Yaru Cursors were apart from many (unnecessary) dependencies - many could freely install or ship it on some distros.. And, It'd be easier for others to reuse and tweak it according to their needs too.

**Comment by madsrh** [comment]
> it would be helpful if the Yaru cursors was separated from it's main package...

I think this is a pretty rare use case and there's nothing for us to gain by separating the package, so I don't see this happening.

If you want you can grab the original repo, but it's not synced with all the new changes: https://github.com/ubuntu/cursor-communitheme

I'll close this issue but it's still open for comments.

**Comment by UltraBurstXD** [comment]
> > it would be helpful if the Yaru cursors was separated from it's main package...
> 
> I think this is a pretty rare use case and there's nothing for us to gain by separating the package, so I don't see this happening.
> 
> If you want you can grab the original repo, but it's not synced with all the new changes: https://github.com/ubuntu/cursor-communitheme
> 
> I'll close this issue but it's still open for comments.

Well, that's kinda true, but thanks anyway.
