### ISSUE TITLE
Login screen button color turns white on white when disabled

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2746]
I can't screenshot since the moment is too short and I can not reproduce it in the lock screen because the button is not there then.
But when you login into a new session the white button to the left of the login input turns white on white bg when you are loggin in
This is caused by our modifications here 

https://github.com/ubuntu/yaru/blob/4f1d31c5d4de784e9671cadf1303a9ba14f9f0cd/gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss#L72-L90

@Jupi007 could you take a look? Currently no time :( 
Option 1: include a :disabled style
Option 2: revert to gnome shell 3.38 upstream styling (dark buttons)

**Comment by Jupi007** [comment]
I'll have a look tomorrow :)
