### ISSUE TITLE
Folder icon

### ISSUE THREAD

**Issue by meetdilip** [ubuntu/yaru#2747]
Hi, do you think we can give some love to the folder icons as we do to other areas of the UI?

I worked on a couple of ideas

![Folder idea](https://user-images.githubusercontent.com/6965443/112249006-ffc70b00-8c7c-11eb-933b-bb2e9cc92ac0.png)

Considering how much orange + purple dominates the existing icon and the UI colour scheme, started with a very basic folder design with these colours. I had a few variants, but I feel these 3 are worth posting here

![glass](https://user-images.githubusercontent.com/6965443/112249324-91367d00-8c7d-11eb-8929-d3a78cd56c2e.png)

You can see that they work well with dark and light themes which is an integral part of Ubuntu.

**What is the need for a new icon scheme ?**

Designs these days make use of environmental elements such as shadow, light etc. Having them in the UI adds a texture of real-life when handling the OS.

I think soon we will be talking about 3D icons which are already getting into the picture on different platforms. By including the real-life elements, we will be getting closer to such an idea.

**Comment by Feichtmeier** [comment]
Hi @meetdilip 
Thank you very much for your input. I think I can say that we are collectively very happy with the current folder icons.

Why do you want to change it?

**Comment by meetdilip** [comment]
Certainly not my request. We all know about icon themes :)

It is only for your consideration, the Yaru team, the wider Ubuntu community and those normal users who keep whatever comes with the default ISO.

**Comment by Initu** [comment]
> Certamente não é meu pedido. Todos nós sabemos sobre temas de ícones :)
> 
> É apenas para sua consideração, a equipe Yaru, a comunidade Ubuntu mais ampla e os usuários normais que mantêm tudo o que vem com o ISO padrão.
Você pode publicar no Gnome-Look para download?

**Comment by Feichtmeier** [comment]
> Certainly not my request. We all know about icon themes :)
> 
> It is only for your consideration, the Yaru team, the wider Ubuntu community and those normal users who keep whatever comes with the default ISO.

Alright. Thanks for your idea, but we'll pass this one. Thanks for contributing 🐱

**Comment by meetdilip** [comment]
Sure :)

**Comment by meetdilip** [comment]
> Você pode publicar no Gnome-Look para download?

I will try to.
