### ISSUE TITLE
Missing Wireless network full color icon

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2750]
Papirus
![Bildschirmfoto von 2021-03-26 18-31-31](https://user-images.githubusercontent.com/15329494/112670757-9d7b2f80-8e61-11eb-92a3-c65555830ef5.png)
Yaru
![Bildschirmfoto von 2021-03-26 18-31-18](https://user-images.githubusercontent.com/15329494/112670760-9e13c600-8e61-11eb-9cf1-23e6b53facea.png)

**Comment by Feichtmeier** [comment]
CC @ubuntujaggers @Jupi007 if anyone has time :1st_place_medal:

**Comment by Jupi007** [comment]
I found the icon name: `nm-device-wireless`.

What do you think of something like this:

![Capture d’écran du 2021-03-28 21-03-54](https://user-images.githubusercontent.com/36476595/112764498-21235080-9009-11eb-8080-b32aa8fc2b39.png)

About the background I don't know which one to choose. The actual color is the one from Template files.
