### ISSUE TITLE
[Yaru-Mate-Dark] Selected groups in mate-control-center being misaligned when scrolled

### ISSUE THREAD

**Issue by ahayzen** [ubuntu/yaru#2753]
**Expected Behavior**

For either the background of the control center's groups to follow when you scroll, or for it to be disabled like other themes (eg most other themes just change the header colour).

**Actual Behavior**

When you scroll the view, the background colour remains static so is misaligned.

**Steps to Reproduce the Problem**

1) Open the `mate-control-center`
2) Click on a "group" from the side panel
3) Scroll the view
4) Notice that the highlighted background remains static so is misaligned (it is only correct when scrolled to the top)

**Software that presents the issue**

`mate-control-center`

```
$ apt policy mate-control-center
mate-control-center:
  Installed: 1.24.1-1
  Candidate: 1.24.2-0ubuntu1
  Version table:
     1.24.2-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
 *** 1.24.1-1 100
        100 /var/lib/dpkg/status
```

**Yaru version**

This is from the `hirsute/mate` branch I believe (i'm using hirsute with mate).

**Screenshots**

![image](https://user-images.githubusercontent.com/3669750/112889918-2a2a2580-90ce-11eb-88e0-0bbbfb116725.png)

**Upstream check**

With Yaru-MATE-Light this does not happen, nor with other themes common to mate.

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru/commit/606fd814c308ee141b61d68c9a854c2dff8ce287

![image_2021-03-31_01-14-01](https://user-images.githubusercontent.com/15329494/113068599-e06d3800-91be-11eb-98d3-8cd087450251.png)
