### ISSUE TITLE
[Yaru-MATE-Dark] Tilda search bar has incorrect theming

### ISSUE THREAD

**Issue by ahayzen** [ubuntu/yaru#2755]
**Expected Behavior**

For the search bar have a dark background and light foreground.

**Actual Behavior**

Tilda search bar looks wrong with dark theme.

**Steps to Reproduce the Problem**

1) Choose Yaru-MATE-Dark
2) Open MATE Tweak
3) Select the panel page
4) Enable the pull down terminal
5) Press F12 to show pull down terminal
6) Right click on the terminal, select "toggle search bar"
7) Notice that the colours look wrong

**Software that presents the issue**

`tilda`

```
$ apt policy tilda
tilda:
  Installed: 1.5.4-1
  Candidate: 1.5.4-1
  Version table:
 *** 1.5.4-1 500
        500 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Yaru version**

This is from the hirsute/mate branch I believe (i'm using hirsute with mate).

**Screenshots**

![image](https://user-images.githubusercontent.com/3669750/112891756-69f20c80-90d0-11eb-8b04-494e9d74e1b5.png)

**Upstream check**

Yaru-MATE-Light looks fine.

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru/commit/6e24881daeaa073da58ae3ba098f7cdb9e4f7a64

![image_2021-03-31_01-49-40](https://user-images.githubusercontent.com/15329494/113070907-f03b4b00-91c3-11eb-8902-22580820f8d4.png)
