### ISSUE TITLE
Missing icon: wine tricks

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2759]
We already have a pretty cool icon for wine
![grafik](https://user-images.githubusercontent.com/15329494/113020458-e9d8af00-9182-11eb-8136-ce835605004f.png)

 I think we could complete it with an icon for winte tricks

![grafik](https://user-images.githubusercontent.com/15329494/113020368-d4638500-9182-11eb-9cc9-3c5a1a1809d7.png)

**Comment by Jupi007** [comment]
That icon give me hard time 😅

Here is my first try:

![Capture d’écran du 2021-03-31 11-43-07](https://user-images.githubusercontent.com/36476595/113289067-ff1f1c00-92ef-11eb-8285-05e50157c2f4.png)

But it's ... 🤢

I also through to add a star (stared wine is a good wine):

![Capture d’écran du 2021-03-31 11-42-51](https://user-images.githubusercontent.com/36476595/113289172-2d046080-92f0-11eb-92bb-4a9977b73106.png)
![Capture d’écran du 2021-04-01 13-40-55](https://user-images.githubusercontent.com/36476595/113289174-2e358d80-92f0-11eb-8b40-8a6bf1394ef1.png)

But I don't think it is a good idea to add an emblem to an app icon...

I'll try to yaruish the original winetricks icon but I don't know if it will look good enough.

If anyone has a good idea to propose, I will be very grateful to him!

**Comment by Feichtmeier** [comment]
Maybe just a magic hat or stick on a yaru baseplate?

**Comment by Jupi007** [comment]
> Maybe just a magic hat or stick on a yaru baseplate?

Thanks @Feichtmeier :)

**Comment by Jupi007** [comment]
What do you think of something like this:

![Capture d’écran du 2021-04-02 17-33-42](https://user-images.githubusercontent.com/36476595/113429947-97dd9680-93d9-11eb-905d-852f1a9b7c2a.png)

?

**Comment by vitalkanev** [comment]
> 
> 
> What do you think of something like this:
> 
> ![Capture d’écran du 2021-04-02 17-33-42](https://user-images.githubusercontent.com/36476595/113429947-97dd9680-93d9-11eb-905d-852f1a9b7c2a.png)
> 
> ?

Seems to look like :ok: for me

**Comment by Jupi007** [comment]
Thanks @vitalkanev :)
