### ISSUE TITLE
[Yaru-MATE-Light/Dark] Panel show focus highlight around last focused launcher when indicators are selected

### ISSUE THREAD

**Issue by ahayzen** [ubuntu/yaru#2760]
**Expected Behavior**

When indicators are selected, for the last focused launcher not to have a ring around it.

**Actual Behavior**

A green focus ring appears over the last focused launcher.

**Steps to Reproduce the Problem**

1) Launch a default MATE session
2) Click on an indicator on the right side of the top panel
3) Notice that one of the application launchers on the left side will have a green ring around it (like it's focused)

**Software that presents the issue**

`mate-panel`

```
$ apt policy mate-panel
mate-panel:
  Installed: 1.24.1-1
  Candidate: 1.24.2-0ubuntu1
  Version table:
     1.24.2-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
 *** 1.24.1-1 100
        100 /var/lib/dpkg/status
```

**Yaru version**

This is from the hirsute/mate branch I believe (i'm using hirsute with mate).

**Screenshots**

![image](https://user-images.githubusercontent.com/3669750/113048364-5ad79100-919a-11eb-8fba-246a4f6fd880.png)

**Upstream check**

Note, this does happen with other themes, however @flexiondotorg has told me that this issue has been resolved/improved before in the theming. (note some are much more subtle in the colour used, so it isn't as obvious)

**Comment by Feichtmeier** [comment]
I can remove the focus for not selected I think if this is wanted

**Comment by ahayzen** [comment]
@Feichtmeier This one might be best discussed with @flexiondotorg as I can see cases where you might want the focus ring to be shown (eg when using keyboard focus in the panel to launch items) but if this can be improved when you have the indicators selected that might be the solution :-)

**Comment by flexiondotorg** [comment]
@Feichtmeier or @Jupi007 Please can you remove the focus for not selected. 

Navigating the panel is an edge case, mostly reserved for the visually impaired who will hear spoken prompts anyway.
