### ISSUE TITLE
Do we need to update purple icons?

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2761]
Our purple accent changed to light aubergine, do we need to update this in our purple icons?

![grafik](https://user-images.githubusercontent.com/15329494/113116615-e76f6700-920d-11eb-9c23-d594bdb69966.png)

CC @ubuntujaggers @Jupi007 ?

**Comment by Jupi007** [comment]
Here is how it looks (only changed sliders and checks background):

![Capture d’écran de 2021-03-31 11-09-41](https://user-images.githubusercontent.com/36476595/113120273-b5600400-9211-11eb-85d8-621998738e79.png)

Also update "soft and updates" background looks:

![Capture d’écran de 2021-03-31 11-13-04](https://user-images.githubusercontent.com/36476595/113120747-31f2e280-9212-11eb-995d-0e0568fe0aa4.png)

**Comment by Feichtmeier** [comment]
I like this change, you too? :D

**Comment by Jupi007** [comment]
> I like this change, you too? :D

Yes, it looks very good!
I'll make a PR.
