### ISSUE TITLE
Full color computer icon is missing

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2769]
It's mostly visible in mate but also important for master

![grafik](https://user-images.githubusercontent.com/15329494/113279505-7601e800-92e3-11eb-85d6-970ead15796e.png)

**Comment by Jupi007** [comment]
What do you think of:

![1](https://user-images.githubusercontent.com/36476595/113440355-8c479b00-93ec-11eb-927f-a36bf4878831.png)
![Capture d’écran du 2021-04-02 19-49-17](https://user-images.githubusercontent.com/36476595/113440359-8d78c800-93ec-11eb-8fa1-34ee7511c87e.png)

?

**Comment by Feichtmeier** [comment]
The screen looks nice but the keys have something in them that doesn't fit but I'm not sure what :D

**Comment by Jupi007** [comment]
> The screen looks nice but the keys have something in them that doesn't fit but I'm not sure what :D

It is just the biggest one, or all ones?

**Comment by Jupi007** [comment]
@Feichtmeier It is better like that:

![Capture d’écran du 2021-04-02 20-49-59](https://user-images.githubusercontent.com/36476595/113444883-08de7780-93f5-11eb-88c7-12f88b1a7bdd.png)

**Comment by Feichtmeier** [comment]
Hmm even if it looks highly professional I'm not sure. Let's have @madsrh and/or @ubuntujaggers have a on this one. I feel like I'm not really a help 😅

**Comment by Muqtxdir** [comment]
@Jupi007 instead of doing a 3D representation of keyboard how about flat-keyboard stacking alongside monitor ? I think this way it may also look clear in smaller baseplate sizes. maybe this SVG-drawing will better explain what I mean (see below screenshot)

![computer](https://user-images.githubusercontent.com/54065734/113475508-c8820680-9493-11eb-8aaa-c5eb9cd6278a.png)

**Comment by Feichtmeier** [comment]
that's a good idea
we already have a keyboard icon one could reuse
![grafik](https://user-images.githubusercontent.com/15329494/113476903-af228f80-947e-11eb-939c-6921628313a2.png)

**Comment by Jupi007** [comment]
That is a really good idea @Muqtxdir 👍

After a good night's sleep I realize that my proposal keyboard is just ... 😱

**Comment by Muqtxdir** [comment]
> we already have a keyboard icon one could reuse

My bad, forgot about this great keyboard icon 😅

> That is a really good idea @Muqtxdir 👍

> After a good night's sleep I realize that my proposal keyboard is just ... 😱

It's alright, I hope this one helps you 👍

**Comment by ubuntujaggers** [comment]
The first one doesn't quite fit the theme because it's got a 3D effect on the keyboard viewed from an angle.  I like the idea of using the existing elements (keyboard and monitor) in a Yaru-style version of the second concept :+1:

**Comment by Jupi007** [comment]
> The first one doesn't quite fit the theme because it's got a 3D effect on the keyboard viewed from an angle.

You're right, I had forgotten that 3D effects wasn't Yaru. Also my proposals was just horrible 😬
I'll try to do a better job.

**Comment by ubuntujaggers** [comment]
> > The first one doesn't quite fit the theme because it's got a 3D effect on the keyboard viewed from an angle.
> 
> You're right, I had forgotten that 3D effects wasn't Yaru. But my proposals was just horrible 😬
> I'll try to do a better job.

Not at all!!

Is anyone working on this concept already or should I have a go at doing it?

**Comment by Jupi007** [comment]
> Is anyone working on this concept already or should I have a go at doing it?

I had assigned myself this issue, but I have a lot of work these day. I you have time, fell free to grab it :)
