### ISSUE TITLE
Slider handle

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/yaru#277]
The slider handle used for scales with tick marks, has a couple of **very** minor issues:

1. Unlike the other (square-ish) slider handle, it has no shadow
2. As its width is an even number, the point does not align with the tick mark. Perhaps it should be an odd numbered width?

The screenshot below shows a `xmag` capture of `gtk3-widget-factory`

![screenshot from 2018-03-23 07-46-49](https://user-images.githubusercontent.com/1141694/37817497-e11bf34c-2e6e-11e8-9502-60340123cfcb.png)

**Comment by godlyranchdressing** [comment]
@madsrh should we just use the round slider here since the squarish slider is gone?

**Comment by madsrh** [comment]
@godlyranchdressing Not sure what you mean be _round slider_ 🤔 Like this:
![image](https://user-images.githubusercontent.com/3986894/39377231-b3a8ef4e-4a54-11e8-919b-46c6700326ed.png)

I think the odd width is a great idea be @CDrummond if possible 👍

**Comment by CDrummond** [comment]
So, is it to be that the same slider handle is used in all cases? ie. the circle. Or should the triangular slider have a semi-circle top (as in the above screenshot). Or just use the existing handle, but reduce by 1 pix?

**Comment by Feichtmeier** [comment]
Box-shadow does not work because as you all already know, it is a picture:
![image](https://user-images.githubusercontent.com/15329494/43038145-83149ba0-8d14-11e8-81fa-b4987f9c89be.png)

**Comment by clobrano** [comment]
I think that a shape with a pointer fits better in this use case

**Comment by CDrummond** [comment]
@clobrano I agree - was just thinking of shapes that I assumed could be done in CSS. What about an elongated diamond?

**Comment by clobrano** [comment]
I shall explore what can be achieved playing with handle's radius

**Comment by clobrano** [comment]
Playing with the radius did't produce any benefit. However, I did some practice with inkscape for #397, so I hope to fix this in svg directly

**Comment by clobrano** [comment]
About the handle position, I observed the following two things

1. it's the same in adwaita

![image](https://user-images.githubusercontent.com/2883614/43354664-c5ddf922-9250-11e8-9b1c-c575ad224e08.png)

2. it looks more like a misalignment between the line on which the handle slides and the indicators below, in fact the line start is just over the first indicator, while the line ending ends before the last indicator
 
![image](https://user-images.githubusercontent.com/2883614/43354687-259e0870-9251-11e8-99a8-0b7aac250f3f.png)
![image](https://user-images.githubusercontent.com/2883614/43354688-2b0f104c-9251-11e8-8f16-3793fac0a1da.png) ![image](https://user-images.githubusercontent.com/2883614/43354689-30cccd4e-9251-11e8-9d78-b8eecaf632ff.png)

So, I tried to add some padding to the indicators below, to let them shift on the left by only 1 pixel.
This is the result (honestly I laughed a lot :D)

![handle-mark-position-fix](https://user-images.githubusercontent.com/2883614/43354804-deefb78c-9252-11e8-8e21-844f4130e7e4.gif)

**Comment by Feichtmeier** [comment]
haha! Epic! So 0.5 px does not work in X, right?

**Comment by clobrano** [comment]
Nope :D
