### ISSUE TITLE
Create Yaru-dark icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#2771]
Create Yaru-dark icons with Humanity-Dark as a dependency.

**Comment by Feichtmeier** [comment]
Why? We try to have yaru icons working in both dark and light themes

**Comment by Initu-Castilhos** [comment]
> Por quê? Tentamos ter ícones yaru trabalhando em temas claros e escuros

To use on xfce.

**Comment by Initu-Castilhos** [comment]
> > Porque? Tentamos ter ícones yaru trabalhando em temas claros e escuros

For the network icon to be lighter on the dark panel in XFCE and Unity.

**Comment by Feichtmeier** [comment]
We have symbolic icons which can be coloured just like text. Closing this then, we don't need a yaru dark icon set. The icons can be used on light and dark icon themes
