### ISSUE TITLE
Create a variant of the cursor set with an black version of the current hands

### ISSUE THREAD

**Issue by VSchris-code** [ubuntu/yaru#2773]
This is something that has been internally frustrating me since I've seen a video of the theme in action, which is Michael MJD's Edge for Linux video, and it just gets worse the longer I stare at one. Just to relieve this internal frustration, maybe you can make a variant of the cursor set that comes with Yaru with black versions of the current hand cursors? I slightly hate mixed cursor sets (cursor sets where some cursors are white with a black outline while the others are black with a white outline) but I add them anyways just for the sake of making my cursor set roster larger. If so, could you please make a variant of the cursor set that comes with Yaru with black versions of the current hand cursors, just to relieve my internal frustration?

**Comment by madsrh** [comment]
Thanks for the feedback @VSchris-code 

We're very happy with the current cursor theme and don't plan on maintaining another variant - sorry. 

Your frustrating is noted, but we can't create a new variant for every user request.


I'll close this issue but feel free to comment.

**Comment by VSchris-code** [comment]
I guess it's up to me to maintain the variant myself.

**Comment by VSchris-code** [comment]
Update: The current hands have been made black. Glad this was done.
