### ISSUE TITLE
should the accesories-text-editor icon be updated?

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#2777]
Hi,
This is a minor-nitpick from me, does the `accesories-text-editor` icon need to be revised according to the newly introduced text-based mime-types?

Did a quick _drawing-SVG_ for comparision of how it may look (see screenshots below)

### before
![before](https://user-images.githubusercontent.com/54065734/113617390-e3ab6c80-9673-11eb-85e3-3066f78ea563.png)

### after
![after](https://user-images.githubusercontent.com/54065734/113617487-ffaf0e00-9673-11eb-9366-0bfcb81f76f1.png)

**Comment by Feichtmeier** [comment]
No I think not. it's not a mimetype. With the foldv we've found a clear way to separate minetypes from other baseplates again, as it was in the original suru theme
