### ISSUE TITLE
How about a rounded scrollbar track?

### ISSUE THREAD

**Issue by UltraBurstXD** [ubuntu/yaru#2778]
Hi,
What about this rounded scrollbar track:
![images](https://user-images.githubusercontent.com/55871338/113686953-1bdc9a80-96c8-11eb-9992-be1e07617ab0.png)

Instead of this rectangular one:
![scrolledwindow](https://user-images.githubusercontent.com/55871338/113686232-572a9980-96c7-11eb-819b-1dfb2a360e4d.png)

I think rounded scrollbar track would make Ubuntu look more awesome in many scenarios (Depending on the Design concept). Maybe It'd reduce a little the scrolledWindow width too? And, as result, expand little bit more the window container in some apps?

The default one may be little bit messy in worst scenarios...

**Comment by Feichtmeier** [comment]
Yeah, the upstream scrollbar styling bugs me a lot in gtk. I tried to convince them about a transparent white background instead of transparent gray but no success. 

I don't know if rounding the background works for all places though. Generally interested in changing this

**Comment by UltraBurstXD** [comment]
If right colors are chosen from Ubuntu brand to represent some niche transitions and states, I think it'd look awesome.

**Comment by reC0D3D** [comment]
It appears that the GNOME design team is toying with the idea of rounded scrollbars. [See this mockup for reference](https://gitlab.gnome.org/Teams/Design/os-mockups/-/commit/0368bf1d29ad07b98fbaa3d96604bca838062db5).

**Comment by Feichtmeier** [comment]
Perfect, thanks @reC0D3D 
then nothing to change in yaru, we get it from upstream when it's done
