### ISSUE TITLE
Decrease the width of the dock.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#2781]
Currently the dock is very wide, if you decrease 2px it is the same size as the Unity dock (I know that the dock is not for reviving Unity).
Follows the prints of the css file with the changes.
![Captura de tela de 2021-04-08 10-36-58](https://user-images.githubusercontent.com/59381215/114037686-94be2c80-9857-11eb-98b5-4c2346923fda.png)
![Captura de tela de 2021-04-08 10-37-09](https://user-images.githubusercontent.com/59381215/114037715-9b4ca400-9857-11eb-95b1-7e58799b993c.png)
![Captura de tela de 2021-04-08 10-37-18](https://user-images.githubusercontent.com/59381215/114037750-a1db1b80-9857-11eb-9882-eb6d0201305e.png)

**Comment by Feichtmeier** [comment]
Thanks for the suggestion, but we like the current dock size
We also had this discussion before, eons ago =)
https://github.com/ubuntu/yaru/pull/924
