### ISSUE TITLE
Theme Previews do not match anymore

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2793]
@waynecrosby @robert-ancell

We really need to update the theme previews:

1. [the colors do not match anymore since our palette update, darker dark theme](https://github.com/ubuntu/yaru/pull/2655)
2. [the row selection does not fit anymore](https://github.com/ubuntu/yaru/pull/2675)
3. the pathbar selection actually never fitted =)

![grafik](https://user-images.githubusercontent.com/15329494/114701207-c7b66380-9d22-11eb-9bc6-a82b1e2ff287.png)

This would need to be transformed into images:
![grafik](https://user-images.githubusercontent.com/15329494/114700993-89b93f80-9d22-11eb-9267-74cf86f34e92.png)
![grafik](https://user-images.githubusercontent.com/15329494/114701027-9473d480-9d22-11eb-817a-faba21d8058c.png)
![grafik](https://user-images.githubusercontent.com/15329494/114701066-9f2e6980-9d22-11eb-8724-fd68925df891.png)

Since those screenshots are not included in yaru, what would be the correct github repository to open this issue?
Thanks in advance

Edit: I would make it as abstract as possible, maybe even remove the buttons from the headerbar in the abstraction

**Comment by Muqtxdir** [comment]
> Since those screenshots are not included in yaru, what would be the correct github repository to open this issue?

@Feichtmeier the repository for **gnome-control-center** is on [Ubuntu's gitlab](https://gitlab.gnome.org/Community/Ubuntu/gnome-control-center/).

The theme-previews are located at [standard-theme.svg](https://gitlab.gnome.org/Community/Ubuntu/gnome-control-center/-/blob/ubuntu-master/panels/ubuntu/theme-standard.svg), [light-theme.svg](https://gitlab.gnome.org/Community/Ubuntu/gnome-control-center/-/blob/ubuntu-master/panels/ubuntu/theme-light.svg) and [dark-theme.svg](https://gitlab.gnome.org/Community/Ubuntu/gnome-control-center/-/blob/ubuntu-master/panels/ubuntu/theme-dark.svg)

**Comment by Feichtmeier** [comment]
Thanks @Muqtxdir 
Created https://gitlab.gnome.org/Community/Ubuntu/gnome-control-center/-/issues/1
