### ISSUE TITLE
GNOME Software readability issue on main page

### ISSUE THREAD

**Issue by LinuxLlama** [ubuntu/yaru#2797]
**Software** (gnome-software)
`gnome-software 40.0`
Running on _Fedora 34 (Workstation Edition)_

**Yaru version**
`21.04.1-39-g53371e06`
Installed from source

---

### **Issue**

The current GNOME Software has a a refreshed header to display applications. It appears that the Yaru theme hasn't been updated to properly display its colors. This issue only occurs on _Yaru_ and _Yaru-light_. _Yaru-dark_, on the other hand, works as intended. Take a look at the screenshots below.

### **Screenshots**

Yaru (light theme has same results)

![Screenshot from 2021-04-20 12-06-19](https://user-images.githubusercontent.com/29968331/115451566-35a2d500-a1d2-11eb-897c-c3c917f00353.png)

Adwaita
![Screenshot from 2021-04-20 12-06-29](https://user-images.githubusercontent.com/29968331/115451637-4c492c00-a1d2-11eb-89d5-abe02877ab4e.png)

**Comment by Jupi007** [comment]
Hi,
sorry for the very long wait.

With GNOME Software 40, the header background color is computed directly by the app without css.
I don't know why but it looks that Yaru overwrite somewhere the background, but only with the light theme (it works correctly with the dark variant):

![Capture d’écran du 2021-06-03 16-55-36](https://user-images.githubusercontent.com/36476595/120667567-ec5eca00-c48d-11eb-97d7-933b3dd3ce9c.png)

The only solution I see actually is to drop the background-color like this:

![Capture d’écran du 2021-06-03 17-06-02](https://user-images.githubusercontent.com/36476595/120667648-fd0f4000-c48d-11eb-98fc-4e2de34d7208.png)

**Comment by Jupi007** [comment]
Maybe should we ask Gnome software devs, @Feichtmeier ?

**Comment by Feichtmeier** [comment]
There is a lot of gnome-software styling we overwrite, which we should prbly stop. This part could fit, otherwise maybe we should copy paste the upstream code for yaru

```
.app-listbox-header {
    background: $dark_fill;
}
```

**Comment by Jupi007** [comment]
I tried to drop our G-software styling but that don't change anything to this problem, sadly. Also tried to remove all apps and tweaks but no result...

About completely drop our G-software styling I don't know, I think we need to open an issue to discuss the matter of remove some tweaks/apps styling.

**Comment by Feichtmeier** [comment]
Yeah it's a meta discussion indeed, sorry.

I think there's changing much in next release, let's copy paste the upstream in app gnome software styling if they only apply this when theme is adwaita. That's what they do in Nautilus

**Comment by Jupi007** [comment]
Just tried to import all upstream styling, and it doesn't work either 😞
Make the header background transparent is the only solution IMO.

In fact by default the background-color isn't defined inside the css (see https://gitlab.gnome.org/GNOME/gnome-software/-/blob/master/src/gtk-style.css#L301-316) but directly inside the C code.
As Yaru styling comes in last position it is overwritten in a wrong way.

**Comment by Jupi007** [comment]
My solution doesn't work at all.
We cannot make the header background transparent because it is overwritten after by the app itself (even with a hyper specific selector). That was working with the inspector because it was applied **after** the app styling.

I think the only solution is ask the devs about this.

**Comment by Feichtmeier** [comment]
I think this is doesn't happen anymore, right?

**Comment by Jupi007** [comment]
Indeed:

![Capture d’écran du 2022-03-13 19-23-09](https://user-images.githubusercontent.com/36476595/158073705-21de5f09-f055-4bad-a8c6-7abb16136991.png)
