### ISSUE TITLE
redesign files icon

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2800]
**Expected Behavior**
files- icon must be like home icon on the desktop(with the house icon). It should have a rectangle foundation with a small upper left part coming out of the rectangle. It already has all those things but I am talking about that square background removal I think it would really blend more right? white suits the icon.

**Actual Behavior**

**Steps to Reproduce the Problem**

**Software that presents the issue**

**Yaru version**
yaru used in ubuntu hirsute hippo 21.04

**Screenshots**

**Comment by Feichtmeier** [comment]
Only gonna happen if we ever find a true Suru style replacement. No adwaita hardcopies. No big blue file cabinets.
If you have an actual idea that still fits exactly in our icon theme guidelines, shoot

**Comment by Feichtmeier** [comment]
Closing this issue in favour of https://github.com/ubuntu/yaru/issues/2964 where the discussion popped out again. Maybe we find a Suru/Yaru style icon everyone can agree on
