### ISSUE TITLE
hand cursor colour & wait cursor(spinner) colour

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2804]
**Expected Behavior**
The hand cursor(pick cursor) should be black(before & after grabbing. Just being precise) must match other black cursor icons.
Wait cursor(circle with rotating blue part) should be white in colour.

**Actual Behavior**
it is white in colour(hand cursor)
it is blue in colour(wait cursor)

**Steps to Reproduce the Problem**
hover on something that u can grab(hand cursor)
open an app wait cursor with blue part rotates(wait cursor)

**More info**
[https://snwh.org/suru](url)
all I am saying is we should convert all suru's cursor icons into black n white.
even those icons where the blue colour is used.
It would look more consistent if we avoid the purple & go for black n white.(#2779 recommended purple)

**Yaru version**
yaru used in ubuntu 21.04

**Screenshots**

**Comment by Jupi007** [comment]
At now, I think we should leave the spinner background white and drop the blue.
But as I don't know how it could look with a dark background I think we should try just to see, maybe that could be awesome :)

@Benni3-1415 as you're currently refresh the cursors, have you got time to look at this, please?

**Comment by Benni3-1415** [comment]
Hello,
I know this opens a completely new discussion ...

![image](https://user-images.githubusercontent.com/73243667/120669536-d5b97280-c48f-11eb-95b4-75081d153062.png)
![image](https://user-images.githubusercontent.com/73243667/120670446-b53de800-c490-11eb-8989-17a50afa5794.png)

If we see the spinner as an _add-on_ to the cursor we could color it's border black an it is styled like the rest of the _add-ons_.

Next problem: Why are the _add-on's_ colors inverted?

**Comment by Benni3-1415** [comment]
### Dark bg + light aubergine
![image](https://user-images.githubusercontent.com/73243667/120671434-a86dc400-c491-11eb-97bd-9b64c7f16d6b.png)

**Comment by Feichtmeier** [comment]
No :D 
Either white or orange :)

**Comment by Benni3-1415** [comment]
But if _all the add-ons_ have a black border the _copy_ and the _drag and drop copy_ cursors would look like this:

![image](https://user-images.githubusercontent.com/73243667/120673990-f388d680-c493-11eb-89ef-f072f4b2f0f1.png)
![image](https://user-images.githubusercontent.com/73243667/120674040-fe436b80-c493-11eb-8ad6-7db57a38b5f6.png)

**Comment by Feichtmeier** [comment]
Could you show the wait cursor with a dark bg and a white spinner instead?

**Comment by Benni3-1415** [comment]
### Dark bg + white (also used in an older version of [Suru](https://snwh.org/suru))
![image](https://user-images.githubusercontent.com/73243667/120678444-5f6d3e00-c498-11eb-8379-56bf7dff8305.png)

This means the _copy_ and the _drag and drop copy_ cursors get white as fg.

**Comment by Feichtmeier** [comment]
White looks clean but also pretty boring. Which was the reaspn why we went for the blue on the white disk in the first place.
I think a dark wait cursor is a -1 for me then, even if it means inconsistency 
Let's wait for the others 
Could you show an orange spinner on a white disk instead @Benni3-1415 ?

**Comment by Benni3-1415** [comment]
Spinner as _add-on_ with orange as fg
![image](https://user-images.githubusercontent.com/73243667/120679845-e969d680-c499-11eb-85f9-295bdf298809.png)

My favorite is this version colored in light aubergine.

**Comment by Feichtmeier** [comment]
btw this was the old issue https://github.com/ubuntu/yaru/issues/2779
should we eventually focus on on dicussion ? =)

**Comment by Benni3-1415** [comment]
Should I put the different variants in the original issue too?

**Comment by Feichtmeier** [comment]
Yes, sorry for the confusion. Kind of a cursor issue flood right now I need to handle
