### ISSUE TITLE
books, games & notes icon don't apply

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2810]
**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce the Problem**

**Software that presents the issue**

**Yaru version**
yaru used for ubuntu 21.04

**Screenshots**

**Comment by Feichtmeier** [comment]
Yeah, it's still this issue why we've removed those symlinks :) https://github.com/ubuntu/yaru/issues/2196

Thanks for your contributions
