### ISSUE TITLE
No transparency when rendering gtk2 assets for default and light variant

### ISSUE THREAD

**Issue by Jannomag** [ubuntu/yaru#2815]
Hi,
I'm currently working on an update for my Yaru-Color theme.    
I noticed that the assets for each gtk2 variant are having transparent backgrounds.    

When I render them using the render-all-assets.sh script, the assets won't get rendered with transparent background if there is a background in assets.svg.     
This happes for light and default variant ONLY. Dark seems to be okay, even though there's a background behind those assets in the assets.svg.    

I attached two files to compare.    
    
This one is directly from yaru master in ./gtk/src/gtk-2.0/light/assets directory
![menu-pan-down](https://user-images.githubusercontent.com/31586674/116536741-98d4eb80-a8e5-11eb-92a5-76fddff469e0.png)

    
This one is rendered using render-all-assets.svg within the ./gtk/src/gtk-2.0/light directory. 
![pan-down](https://user-images.githubusercontent.com/31586674/116536079-cbcaaf80-a8e4-11eb-8164-4f940e4ccf16.png)    

Nothing was modified, I downloaded the master branch as zip and tried it with those fresh files.    

Steps to reproduce:     
- clone or download the repro
- head over to ./gtk/src/gtk-2.0/light/
- check the assets in ../assets, for example "pan-down.png", it's a transparent png
- execute the render-all-assets.sh script
- check the same asset file again, it's not transparent anymore.

**Comment by Jannomag** [comment]
Reason found: with Inkscape 0.92.5 it's working.

Are you able to fix this?
Because it's needed to compile older Inkscape on >18.04 manually

**Comment by Feichtmeier** [comment]
No idea at this department but @clobrano and @Jupi007 recently worked on the script

**Comment by clobrano** [comment]
We did not work on `render-all-assets.sh`, that's why isn't working with inkscape 1.0. Weird that it works fine in dark variant though, it makes me wonder if there is a difference in the input asset.

**Comment by Jannomag** [comment]
Okay. I played a bit with inkscape's cli but couldn't find any alternative commands. `--export-background-opacity` is still valid.

@clobrano @Jupi007 
But I've found another bug. I have absolutely no clue about github and pull requests and before I do something wrong I post it here.

In the assets.svg of dark gtk2.0 variant is the "scale-slider" wrong.
Missing "scale-slider" in dark assets.svg of gtk2 theme.

Fix:
Replace lines 2404 to 2408:
```
       id="g1967"
       inkscape:export-filename="/home/jupiter007/yaru/gtk/src/dark/gtk-2.0/assets/scale-slider.png"
       inkscape:export-xdpi="96"
       inkscape:export-ydpi="96">
```
with 
```
       id="scale-slider"
       inkscape:label="#g5227"
       transform="translate(-43,230)">
```

**Comment by Jupi007** [comment]
Honestly, I don't what's happening here (the weirdest thing being that it works with Inkscape 1.0 but only with dark assets).
The last time I worked on Gtk2 assets, all _assets.svg_ files wasn't uptodate at all, so I just manually exported all assets I updated with Inkscape.

**Comment by Jannomag** [comment]
Since I change the colors in svgs and gtkrc for my themes, I need to export them everytime I add new colors. That's why I came across this. With Inkscape 0.92.5 it works as usual.

**Comment by clobrano** [comment]
I just looked at assets.svg file in both light and dark variants and it seems that while the dark one has a transparent bg, the light one doensn't

this is light
![image](https://user-images.githubusercontent.com/2883614/116692887-60a0dc00-a9bd-11eb-95cc-64fed8655471.png)

this is dark
![image](https://user-images.githubusercontent.com/2883614/116692931-71e9e880-a9bd-11eb-80be-dbf74c2819c1.png)

Is it possible that something changes in latest inkscape and this difference became relevant?

I fixed the warning using export-png and checked the documentation, so exporting the transparence is still right, but maybe it doesn't work if the original asset is not transparent.

**Comment by Jupi007** [comment]
> I just looked at assets.svg file in both light and dark variants and it seems that while the dark one has a transparent bg, the light one doensn't
> 
> this is light
> 
> this is dark
> 
> Is it possible that something changed in the latest inkscape and this difference became relevant?
> 
> I fixed the warning using export-png and checked the documentation, so exporting the transparence is still right, but maybe it doesn't work if the original asset is not transparent.

Both dark and light has transparent background (`inkscape:pageopacity="0"`), the "transparent effect" background comes from `inkscape:pagecheckerboard="true"`. But that has no impact on the rendering.

**Comment by clobrano** [comment]
Ok, I didn't know that. I set pagechekerboard="true" in light/assets.svg and I still see the pan-down section with a opaque background though, so I double checked and in my light/assets.svg "pageopacity" is 1. Set it to 0 resolve this issue.

**Comment by Jannomag** [comment]
Awesome, thanks for the work!
