### ISSUE TITLE
Make the microphone icon in the top panel reflect the input sound volume

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2821]
I have just discovered that the Adwaita microphone icon (adwaita-icon-theme 3.38.0) in the top panel reflects the input sound volume. So if the input volume is 50%, the mic icon is 50% filled.

**Steps to reproduce:**
1. Open any app that takes input sound (Discord for example)
2. Make sure that you see the mic icon in the top panel (that means that the app is listening to input sound)
3. Change the input sound volume

**What should happen:**
The mic icon should reflect the input sound volume.

**What happens instead:**
The mic icon is always solid.

yaru-theme-icon (20.04.10.1) on Ubuntu 20.04.

**Comment by Muqtxdir** [comment]
Hi @Amr-Ibra,

Now that #2806 is in `master` all the symbolic-icons are in-sync with adwaita-symbolics. So could you try the icon-theme from `master` and share whether this still happens for you?

attaching a clip that demonstrates the different microphone-levels with `master` applied

https://user-images.githubusercontent.com/54065734/117171854-df947b00-ade8-11eb-9f79-532dc951cdb2.mp4

**Comment by Amr-Ibra** [comment]
Ah, sorry I forgot to mention the theme and OS version. It's yaru-theme-icon (20.04.10.1) on Ubuntu 20.04. So if this is already fixed in master, then close this issue.

**Comment by Muqtxdir** [comment]
Alright, thanks for reporting. closing this issue :+1:
