### ISSUE TITLE
Nautilus listview: Improve the gray selection or revert to orange

### ISSUE THREAD

**Issue by jlemonde** [ubuntu/yaru#2822]
I feel annoyed by the selection colour in list view in Nautilus. It is furthermore super-hard to distinguish the colour of selected items from the colour of the item that is hovered with the mouse.

**Expected Behavior**

I would expect to distinguish the selected items much more, and I would expect the theme to be coherent between list view and icon view in Nautilus.

**Actual Behavior**

In icon view, selected items have text with orange highlighting colour, and are clearly distinguishable from non-selected items. The hovered item (the one that resides under the mouse cursor) is very slightly lighter, hardly noticeable, but at least enough for me. 

In list view however, selected items have grey highlighting colour that is lighter than hovering colour, which is disturbing. Furthermore, this light colour is hardly distinguishable from white depending on the illumination outside of the screen (for instance if you are outside in the sun with your laptop). While I miss the orange highlighting colour, I would consider myself happy with the newer grey highlighting colour if it were darker (for better contrast). 

I would suggest to let the hovering colour as is, and make the selection colour even darker. I believe grey has a good potential, but a darker one.

**Steps to Reproduce the Problem**

Just open Nautilus and highlight a few items in list view. Compare with doing the same in icon view.

**Software that presents the issue**

Ubuntu 21.04 with GNOME 3.38.4 and Nautilus 3.38.2

**Yaru version**

yaru-theme-gtk, version: 21.04.1

**Screenshots**

Below are two screenshots where I selected the folders "Langues", "Lecture" and "Modèles", and hovered "Documents" without selecting.

![Capture d’écran de 2021-05-05 14-28-08](https://user-images.githubusercontent.com/30623792/117142809-6b3de580-adb0-11eb-9d03-62bf4d6cdc48.png)
![Capture d’écran de 2021-05-05 14-33-22](https://user-images.githubusercontent.com/30623792/117142822-6f6a0300-adb0-11eb-8bdb-3d953b3ff2a9.png)

**Upstream check**

This bug does not occur with Adwaita. Only Yaru.

**Comment by Feichtmeier** [comment]
Alright, valid issue. Let's see what works better, either reverting for `$selected_bg_color` for nautilus .listview or a darker gray
