### ISSUE TITLE
Shell icon for software-properties-gtk isn't correct

### ISSUE THREAD

**Issue by hwittenborn** [ubuntu/yaru#2824]
**Expected Behavior**
Shell icon for "Software and Updates" should be the "A" icon in the shell.

**Actual Behavior**j
The shell icon for "Software and Updates" is a globe, as if it's defaulting back to another icon.

**Software that presents the issue**

- Name: Software and Updates (software-properties-gtk)
- Version: 0.98.9.4
- OS version: Ubuntu 20.04.2 LTS

**Yaru version**
20.04.10.1

**Screenshots**
![image](https://user-images.githubusercontent.com/74838472/117520200-b0a71200-af6c-11eb-8306-cf29e0be8f82.png)

**Comment by Feichtmeier** [comment]
Hi there. I think this is fixed in 21.04. let me take a look... Oh 😳 indeed unfixed

**Comment by Feichtmeier** [comment]
@ubuntujaggers @Jupi007 @Muqtxdir any takers?
