### ISSUE TITLE
Bottles: double row border

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2834]
In listviews in the settings of bottles (https://snapcraft.io/bottles) rows have a double border
![grafik](https://user-images.githubusercontent.com/15329494/118269402-fc067680-b4be-11eb-9315-ec1f4a7cde7d.png)

Looks like we do something wrong here in the libhandy gtk3 dir

@Jupi007 do you have time to look this up?

**Comment by Jupi007** [comment]
Ofc, I will have a look :)

**Comment by Feichtmeier** [comment]
Thank you! 
If you find the issue, we also need to make sure to push the change to gtk-common-themes, as this is a snap

**Comment by Jupi007** [comment]
It looks like an upstream bug, as Adwaita is also affected (but I don't know if it's a Bottle or a Libhandy problem):

![Capture d’écran du 2021-05-14 15-10-15](https://user-images.githubusercontent.com/36476595/118275301-8c948500-b4c6-11eb-811b-b4dbc67c3b25.png)

If you want I can add a little patch awaiting the upstream one:

```scss
preferencesgroup box box list {
    border: none;
}
```

**Comment by Jupi007** [comment]
I created a new issue here: https://github.com/bottlesdevs/Bottles/issues/275

**Comment by Feichtmeier** [comment]
Nice, le's just keep this opened until it is eventually fixed in libhandy, this is also a nice test for your nice githubab action :) 
Imagine if we would reduce the unusual theming things further, then we could actually let the action copy everything except _colors into src :D

**Comment by Jupi007** [comment]
That was indeed a bug of Bottles itself.
The dev just fixed it, so I close this :)
