### ISSUE TITLE
Switches in selected rows have the wrong styling

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2849]
![photo_2021-05-17_14-50-52](https://user-images.githubusercontent.com/15329494/118491428-48e88800-b71f-11eb-9da8-c9260bd6efe8.jpg)

https://github.com/ubuntu/yaru/blob/7fba4e50952a081932d844524f060d0b61ff6db1/gtk/src/default/gtk-3.20/_tweaks.scss#L435-L449

**Comment by Jupi007** [comment]
Fixed by #2850
