### ISSUE TITLE
List rows orange flash when unselected

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#2858]
I don't know why, but since #2855 when a `list row` is unselected, there is an orange flash:

![Peek 20-05-2021 12-31](https://user-images.githubusercontent.com/36476595/118963933-46786f00-b967-11eb-8105-a6e7d7476b0a.gif)

**Comment by Feichtmeier** [comment]
![Peek 2021-05-20 12-34](https://user-images.githubusercontent.com/15329494/118964449-cdc5e280-b967-11eb-81ae-cc504481ff4d.gif)
Must be something with that gradient
Maybe you need to style all states now? Since you use a background-image now only for selected

**Comment by Jupi007** [comment]
I think it is because list row use `background-color`.
In the fix PR (#2859) I used `background` instead of `background-image` so it can overwrite all background properties.
