### ISSUE TITLE
Gnome shell login screen dark/light mix looks weird and could be unified

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2870]
The mix of the super dark text input (gnomers call it "entry") plus the white buttons look kind of strange to me
![grafik](https://user-images.githubusercontent.com/15329494/119841933-85c63300-bf06-11eb-88c8-7a267a8e2b2a.png)

Thinking of two solutions if you agree on the problem:
- do not override gnome shell login screen buttons to be white
- make text inputs white

@madsrh @clobrano @Jupi007 ?

**Comment by clobrano** [comment]
What about the same color of the "wallpaper" and a white arrow? It is basically the same Gnome does, right?

**Comment by Feichtmeier** [comment]
> What about the same color of the "wallpaper" and a white arrow? It is basically the same Gnome does, right?

Doesn't sound bad
upstream uses the default dark button styling

**Comment by madsrh** [comment]
> - do not override gnome shell login screen buttons to be white
> - make text inputs white

Yeah, both options would look good. I like the white input background but perhaps making everything dark would fit better with the dark shell 🤷‍♂️

**Comment by Jupi007** [comment]
IMO we should make everything white for the white theme, and everything dark for the dark theme.
Also maybe on the login screen, force dark widgets because it is our default variant 🤔

**Comment by Feichtmeier** [comment]
In the upstream theme it is already white for light and dark for dark. So all we need to do is to revert the file to upstream :D 
then the lock screen follows if the light theme is selected from user-themes

**Comment by Jupi007** [comment]
Do you want I make a PR?

**Comment by Feichtmeier** [comment]
I can make it, too - but if you can now, go ahead :) Currently sick IRL and kinda slow

**Comment by Jupi007** [comment]
> I can make it, too - but if you can now, go ahead :) Currently sick IRL and kinda slow

My VS Code is already opened with Yaru, and I preworked the modifications 😉
