### ISSUE TITLE
Link select cursor in .svg cursor sheet has swapped gradient colors

### ISSUE THREAD

**Issue by VSchris-code** [ubuntu/yaru#2874]
Issue's title says _almost_ it all, so have this image.
![hedj](https://user-images.githubusercontent.com/81916873/120073388-6d712800-c06e-11eb-9686-29113403efd8.png)

**Comment by VSchris-code** [comment]
Mildly pissed due to the lack of response. Will reopen if I think there's going to be a response.

**Comment by Feichtmeier** [comment]
Uhm, sorry that we didn't respond?
Cursor get a make over in the pending pull request. Take a look mylord. No need to be pissed
