### ISSUE TITLE
Icon for Geany and OpenJDK

### ISSUE THREAD

**Issue by maxborowsky** [ubuntu/yaru#2878]
Please add Suru/Yaru-style icons for Geany and OpenJDK.

**Comment by Feichtmeier** [comment]
OpenJDK could be done I guess but better if we ask too

Geary not, since I know that they are explicitly against distributions overwriting their app icon

**Comment by Feichtmeier** [comment]
Hi @shipilev !
Sorry for summoning you here and sorry if you are the wrong person for this question I found you on the openJDK contributor list, but we have a user request for a yaru openJDK icon in Ubuntu. Would you be okay if we would provide a "yaru-fied" version of your openJDK icon?

**Comment by shipilev** [comment]
> Would you be okay if we would provide a "yaru-fied" version of your openJDK icon?

What is "my OpenJDK icon" here? There is [Duke repository](https://wiki.openjdk.java.net/display/duke/Gallery) in OpenJDK, which can be sourced freely, I think (I cannot see the license there, but can ask).

**Comment by maxborowsky** [comment]
@Feichtmeier
>Geary not (...)

Gea**r**y or Gea**n**y? I was talking about Geany IDE, not the GNOME Geary email app.

**Comment by Feichtmeier** [comment]
Woops, sorry. Well, it is always the same story, if the app devs are okay with a yaru icon, we can ask one of our icon designers to make one, if not it's a no-go.

@shipilev thanks! :) So I think your "team" has no problem with a special Ubuntu icon for the openJDK? (I could imagine that we would only change the baseplat and keep the Duke inside)

**Comment by shipilev** [comment]
> @shipilev thanks! :) So I think your "team" has no problem with a special Ubuntu icon for the openJDK? (I could imagine that we would only change the baseplat and keep the Duke inside)

I suspect that Duke images are free to use under one of the open-source licenses. Is it GPL? I cannot find the LICENSE file in the repository. You should probably ask about putting the license info into that repo here: https://mail.openjdk.java.net/mailman/listinfo/discuss

**Comment by Muqtxdir** [comment]
hi @shipilev 

as mentioned already above @Feichtmeier Geany is not a GNOME-core application and more a third-party application that isn't even shipped by default on ubuntu-desktop. It would require an approval permission from the maintainers (_please see: [stopthemingmyapp](https://stopthemingmy.app)_). 

That being said closing this issue as I don't think other icon-contributors here, have the time or motivation to provide icons for **Geany** or **OpenJDK** that follow Yaru's fullcolor icon-guidelines. If anyone is interested in providing icons for these, they are more than welcome to create the necessary PR(s) and the team would be happy to review them.

Thanks!
