### ISSUE TITLE
`cursor: grab;` doesn't work

### ISSUE THREAD

**Issue by Benni3-1415** [ubuntu/yaru#2880]
### Expected Behavior
Seeing Yaru's grab cursor.

### Actual Behavior
Seeing Browser's grab cursor.
![grap](https://user-images.githubusercontent.com/73243667/120624807-5745dc00-c461-11eb-80d7-41511600ca6a.png)

### Steps to Reproduce the Problem
- Open the `csscursors.html` file in any Browser
- Hover over `cursor: grab;` style-sheet in any Browser

### Software that presents the issue
**Name:** all browsers
**Version:** any
**OS version:** tested with Ubuntu 20.04 and 21.04

### Yaru version
tested with 20.04 and master on Gnome 40

**Comment by Jupi007** [comment]
Thanks for this report @Benni3-1415
This is similar to #2507 and #2219

I tested the `csscursors.html` into Chromium and Firefox and it revert to Adwaita (you surely don't have Adwaita installed so it revert to X default cursor):

![Capture d’écran du 2021-06-03 12-43-47](https://user-images.githubusercontent.com/36476595/120633049-fb338580-c469-11eb-8472-3e28ddb6b246.png)

But Gnome-web use the correct cursor:

![Capture d’écran du 2021-06-03 12-44-14](https://user-images.githubusercontent.com/36476595/120633109-0c7c9200-c46a-11eb-947a-9b16dfc10056.png)

I remember that there was a bug with Firefox/Chrome browsers and cursors, but maybe we missing another one. So we need to investigate cursors once again 😅

**Comment by Benni3-1415** [comment]
The `cursor: all-scroll;l` is in Firefox / Chromium the grab cursor and in Gnome-web the move cursor, but not the `all-scroll` ![all-scroll](https://user-images.githubusercontent.com/73243667/120636974-9cbcd600-c46e-11eb-818e-e2e524c0c43b.png).

**Comment by Feichtmeier** [comment]
Some of the cursor PRs have fixed this for both _chrome_ and _edge_:
![grab](https://user-images.githubusercontent.com/15329494/123401581-3a578100-d5a7-11eb-9722-7ffae000081e.gif)

but not with firefox
![ff](https://user-images.githubusercontent.com/15329494/123401918-84406700-d5a7-11eb-90a6-22409dd530b5.gif)

What symlink/name are we missing?

**Comment by Benni3-1415** [comment]
`cursor: grab;` does work now :+1:

> The `cursor: all-scroll;` is in Firefox / Chromium the `fleur` cursor ![grabbing](https://user-images.githubusercontent.com/73243667/120637195-ddb4ea80-c46e-11eb-871d-fec8f636449d.png) and in Gnome-web the `move` cursor ![move](https://user-images.githubusercontent.com/73243667/120637227-ec030680-c46e-11eb-9543-3e01720a4978.png),
but not the `all-scroll` ![all-scroll](https://user-images.githubusercontent.com/73243667/120636974-9cbcd600-c46e-11eb-818e-e2e524c0c43b.png).

But this is still not fixed!

**Comment by Jupi007** [comment]
@Benni3-1415 I remember that each navigator has it's own cursor name implementation. So it's not Yaru's fault 😉
