### ISSUE TITLE
Wait cursor is not rendered

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2888]
Thanks to @clobrano change with #2887 the w32 script now works and together with the x11 script it procudes a huge load of cursors but the wait cursor is still not being rendered and we want to render the recent cursor overhaul

I did the following:
./render-cursors.py source-cursors.svg 
./w32-make.sh 
./x11-make.sh 
ninja install
swap cursor theme

![Peek 2021-06-06 23-36](https://user-images.githubusercontent.com/15329494/120941014-b71dda80-c720-11eb-9ab9-742971161c7f.gif)

**Comment by Jupi007** [comment]
Closed with #2916
