### ISSUE TITLE
snap-symbolic is causing problems...

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#2895]
In Inkscape, it's replaced at least three of the icons associated with snapping:

![image](https://user-images.githubusercontent.com/38893390/121428703-0573e900-c96e-11eb-86c2-0259d9f02fac.png)

Does anyone know what the expected use is for this symbol...?

**Comment by Jupi007** [comment]
Here is what I think: we don't have these icons into Yaru so Gtk try to take an icon with a close name (snapping -> snap).
The snap symbolic is not used by any app, so either we drop it, either we add snapping icons into Yaru.

IMO we should drop this snap icon because that could brake other icons.

**Comment by ubuntujaggers** [comment]
It's a beautifully executed SVG of an origami bird so we should use it for something 🤔

I need to do snapping icons anyway so maybe I'll do those and see if it fixes it.
