### ISSUE TITLE
Send the Updated/Fixed plymouth theme to Seb128

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2896]
@seb128 
You helped me to work on the Ubuntu plymouth theme.
We've found some spinner frames to not be perfect which causes a slight lag in the spinning animation
@Muqtxdir fixed it
Shall we include the plymouth theme in the yaru repository?
And could you help us with getting it into 21.10?

**Comment by seb128** [comment]
@Feichtmeier thank you for the ping but where is the fix exactly? the spinner icons are included in the plymouth package and it probably makes sense to keep it this way since we can't ensure that yaru is installed or rely on that (also in the case of encrypted disk only the initramfs content is available)

**Comment by Feichtmeier** [comment]
@seb128 the fix is currently in @Muqtxdir 's hands - should he send you the fixed version?

**Comment by seb128** [comment]
> @seb128 the fix is currently in @Muqtxdir 's hands - should he send you the fixed version?

If you want it uploaded that would be advisable ;-)

**Comment by Muqtxdir** [comment]
Hi @Feichtmeier, @seb128 👋

Attached `spinner-assets.zip` containing:
- animation(0001 to 0036).pngs ( *modified* )
- bgrt-fallback.png ( ***newly-added***, *needed since this merge-request [#131](https://gitlab.freedesktop.org/plymouth/plymouth/-/merge_requests/131)* )
- bullet.png ( *unchanged* )
- capslock.png ( *unchanged* )
- entry.png ( *unchanged* )
- keyboard.png ( *modified* )
- keymap-render.png ( *unchanged* )
- lock.png ( *unchanged* )
- throbber(0001 to 0030).pngs ( *modified* )
- watermark.png ( *modified* )

**zip-attachement 📎** [spinner-assets.zip](https://github.com/ubuntu/yaru/files/6654557/spinner-assets.zip)

**Comment by seb128** [comment]
Thanks! So the files indicated as 'unchanged' it's compared to upstream which means we don't need to include those overrides in the packaging right? The changes to use a fallback aren't included in the current version so unsure how to test that one without trying to update the package first, how did you verify it was correctly displaying?

**Comment by Muqtxdir** [comment]
> Thanks! So the files indicated as 'unchanged' it's compared to upstream which means we don't need to include those overrides in the packaging right? 

your welcome and yes, no need to override them.
> The changes to use a fallback aren't included in the current version so unsure how to test that one without trying to update the package first

I tried out the `master` branch from the [plymouth-repository](https://gitlab.freedesktop.org/plymouth/plymouth) in a vm as I don't think the changes made to `two-step` plugin are present in `impish-devel` (I could be wrong about this).

**Comment by seb128** [comment]
Was there any discussion about the proposed changes? The updated watermark has a colored ubuntu icon where the desktop team updated it on purpose a year ago to use a black and white version since we were in agreement that it was nicer.

**Comment by Feichtmeier** [comment]
> Was there any discussion about the proposed changes? The updated watermark has a colored ubuntu icon where the desktop team updated it on purpose a year ago to use a black and white version since we were in agreement that it was nicer.

Good question - @Muqtxdir could you use the old watermark instead? I think it looks a little bit less in the face :)
Then re-upload the changed zip?

**Comment by seb128** [comment]
> Good question - @Muqtxdir could you use the old watermark instead? I think it looks a little bit less in the face :)
> Then re-upload the changed zip?

No need to reupload the zip if we decide to keep the old one, it just means we don't need to replace that file in the pltymouth package by the one from the zip. 

@Feichtmeier your comment suggests there is an agreement to use the non colored version? If so I will just uploaded with the other new assets from the current zip

**Comment by Feichtmeier** [comment]
I do not have an opinion on this one, I like both versions and I think both versions are compatible with the brand rules of the ubuntu logo - my intention was to fix the lagging spinner

**Comment by seb128** [comment]
Alright, I will upload the non controversial changes now and if someone cares about making the logo colored again please start a new topic specific to that one

**Comment by Feichtmeier** [comment]
Okay thanks :) Give @Muqtxdir some credits in the changelog please :)

**Comment by Muqtxdir** [comment]
> Was there any discussion about the proposed changes? The updated watermark has a colored ubuntu icon where the desktop team updated it on purpose a year ago to use a black and white version since we were in agreement that it was nicer.

I changed the watermark.png to the colored **_ubuntu-wordmark-logo_** to have it look similar to **_bgrt-fallback logo_** 
(*see screenshot* )
![bgrt-disable](https://user-images.githubusercontent.com/54065734/122218530-2d160480-cecc-11eb-967a-96ed666f1f96.png)

sorry for that, I'm totally onboard with using the previous black-and-white watermark

> Alright, I will upload the non controversial changes now and if someone cares about making the logo colored again please start a new topic specific to that one

nice, thank you :+1:

**Comment by Feichtmeier** [comment]
Landed in daily
```
Changes for plymouth-theme-spinner versions:
Installed version: 0.9.5-0ubuntu3
Available version: 0.9.5-0ubuntu3.1

Version 0.9.5-0ubuntu3.1: 

  * debian/local, debian/rules, debian/source/include-binaries:
    - updated assets for the bgrt theme, includes fixes for the spinning
      animation sligtly lagging, thanks Muqtadir!
```

thanks both @Muqtxdir and @seb128 !

**Comment by seb128** [comment]
@Muqtxdir was there an issue with the upload that your reopened?

**Comment by Muqtxdir** [comment]
Hi @seb128

I was trying out the new-changes in [plymouth_0.9.5-0ubuntu3.1](https://code.launchpad.net/~usd-import-team/ubuntu/+source/plymouth/+git/plymouth/+ref/applied/ubuntu/impish) and the **bgrt-fallback.png** is sized at 536x536, instead of it being 128x128 like the one from the updated`spinner-assets.zip` in previous comment

**Comment by seb128** [comment]
Oh, sorry, I missed your EDIT and the fact that you add a new zip with different content at the same place. We don't have the plymouth support for that feature at the moment but I will include the updated asset when we update plymouth

**Comment by Muqtxdir** [comment]
> Oh, sorry, I missed your EDIT and the fact that you add a new zip with different content at the same place. We don't have the plymouth support for that feature at the moment but I will include the updated asset when we update plymouth

thankyou for this, 👍

**Comment by seb128** [comment]
The logo has been included in the new upload, https://launchpad.net/ubuntu/+source/plymouth/0.9.5git20210323-0ubuntu1 , which is a new git snapshot with support for the fallback bgrt logo, testing feedback would be welcome!

**Comment by Muqtxdir** [comment]
Thanks @seb128. I'll try that in vm and close this issue

**Comment by Muqtxdir** [comment]
Tested on **ubuntu-desktop 21.10** by passing the `bgrt_disable` in grub-bootloader, it displays bgrt-fallback correctly 


https://user-images.githubusercontent.com/54065734/124129955-e7486700-da9b-11eb-9cb9-e7a3acede7b2.mp4
