### ISSUE TITLE
info bars are too bright

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2899]
![grafik](https://user-images.githubusercontent.com/15329494/121747551-df824c00-cb07-11eb-8ba1-8cd4fb3d916f.png)

**Comment by Jupi007** [comment]
@Feichtmeier Can I fix this?

**Comment by Feichtmeier** [comment]
@Jupi007 yes please 👍

**Comment by Feichtmeier** [comment]
I think we could just go with the unmodified upstream versions and could be good. No idea why they were changed

**Comment by Jupi007** [comment]
Upstream use totally transparent background.
Honestly, I prefer with a soft grey but I can just remove the tweak if you prefer.

**Comment by Feichtmeier** [comment]
Oh? Okay. Then it must be a thing for nautilus only. Other Infobars use this invertion of primary colour, desaturated

**Comment by Jupi007** [comment]
So we can just use a softer grey for this?
Btw where can I find other infobars?
Nautilus is the only place I saw one.

**Comment by Feichtmeier** [comment]
Found one 
![image](https://user-images.githubusercontent.com/15329494/159157183-6fc38945-c54f-412d-ab4d-6f3a5ef24163.png)

**Comment by Jupi007** [comment]
Thanks :+1: 

Imo, the patch should only target nautilus.
