### ISSUE TITLE
GDM background should follow overview

### ISSUE THREAD

**Issue by LinuxLlama** [ubuntu/yaru#2908]
The upstream GDM theme uses the same background as the shell theme. This isn't the case on Yaru. There's a somewhat jarring transition from the striking purple to the subdued gray. I also think that the overview gray color would look nicer with the bubbles and text field.

![Screenshot from 2021-06-13 10-05-23](https://user-images.githubusercontent.com/29968331/121816303-ae9d3680-cc2f-11eb-9932-fa7026dd5824.png)

![Screenshot from 2021-06-13 10-05-41](https://user-images.githubusercontent.com/29968331/121816306-b066fa00-cc2f-11eb-9084-be045e04fcf3.png)

**Comment by Jupi007** [comment]
Hi @LinuxLlama, thanks for this feedback.
Currently using Gnome 40 with Ubuntu 21.04 thanks to the [shemgp ppa](https://launchpad.net/~shemgp/+archive/ubuntu/gnome-40), I'm unable to use Yaru with GDM. How did you do that, I'm very interested?

About changing GDM background, I'm not against it at all. The only problem on my side is that I can't test Yaru with GDM...

_Offtopic: your wallpaper is really nice :)_

**Comment by LinuxLlama** [comment]
> How did you do that, I'm very interested?

I used the `set-gdm-theme` command from [this repository](https://github.com/realmazharhussain/gdm-tools). All the instructions are available on the page!

> Offtopic: your wallpaper is really nice :)

Thank you! I modified it to use the Ubuntu orange color. It looks great alongside Yaru.

**Comment by Jupi007** [comment]
I did a test PR here 👆

> I used the `set-gdm-theme` command from [this repository](https://github.com/realmazharhussain/gdm-tools). All the instructions are available on the page!

Awesome, I can finally use Yaru on the login screen, big thanks!

**Comment by Muqtxdir** [comment]
> Hi @LinuxLlama, thanks for this feedback.
> Currently using Gnome 40 with Ubuntu 21.04 thanks to the [shemgp ppa](https://launchpad.net/~shemgp/+archive/ubuntu/gnome-40), I'm unable to use Yaru with GDM. How did you do that, I'm very interested?
> 
> About changing GDM background, I'm not against it at all. The only problem on my side is that I can't test Yaru with GDM...
> 
> _Offtopic: your wallpaper is really nice :)_

**Comment by Jupi007** [comment]
> You need to turn on the gresource option for that gdm to change

Which gresource option?

**Comment by Muqtxdir** [comment]
the same gnome-shell gresource in the meson file but what @LinuxLlama says also works

**Comment by Jupi007** [comment]
Okay, thanks :)
