### ISSUE TITLE
Default/Mixed theme separators are white

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2912]
![grafik](https://user-images.githubusercontent.com/15329494/122019595-3d42bc80-cdc4-11eb-9b0b-7d0821840ac8.png)

**Comment by Jupi007** [comment]
Added the `not-fixable` label because as said on discord: separators aren't part of the headerbar.

**Comment by Feichtmeier** [comment]
Fixed with #2922
