### ISSUE TITLE
Missing icon for close button in overview

### ISSUE THREAD

**Issue by LinuxLlama** [ubuntu/yaru#2915]
**GNOME**: 40.1.0
**Distribution**: Fedora 34 (Workstation Edition)
**Yaru**: 21.04.1-96-g9105b764

![Screenshot from 2021-06-17 08-50-00](https://user-images.githubusercontent.com/29968331/122431664-82442b80-cf49-11eb-92e9-e65b9318b4ec.png)

This occurs when I build with the `gnome-shell-gresource` option set to `true` or if I use Yaru as the GDM theme. I did a bit of digging and found that the upstream shell theme has a 'preview-close-symbolic.svg' icon embedded in the shell theme. Maybe Yaru doesn't have this?

**Comment by LinuxLlama** [comment]
I'm in the Yaru session. All of the other added assets work, such as the spinner, notification bell, and arrows in the app grid

**Comment by Feichtmeier** [comment]
I think this only works in yaru with no modifications made to the build and in the Ubuntu session. But I think only @3v1n0 has a real answer on this, but he is very rarely on this repo around

**Comment by Muqtxdir** [comment]
@LinuxLlama I'll try out GNOME 40.1 session tomorrow, it's probably due to a change in name of `windows-close-24.svg` that was used in GNOME 40.0
