### ISSUE TITLE
Aubergine spinner could need an outline

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2923]
@Benni3-1415 

I really enjoy the aubgergine spinner, but because it has a purple border it can look smaller than it actually is. Could you try to make it have a white outline?

https://user-images.githubusercontent.com/15329494/122654116-6313ec80-d149-11eb-89a1-7b609615a682.mp4

**Comment by Benni3-1415** [comment]
At first:
All cursor _additions_ are white with a dark (black / orange / aubergine) outline (e. g. not _drag-and-drop move_ I'll correct this).
If there is an other solution (than making a white outline) I would chose it.

#### Dark theme
Stupid solution: enlarge the circle:
![spinner-dark](https://user-images.githubusercontent.com/73243667/122681653-b5aae280-d1f5-11eb-94fb-141b73fb442c.png)

#### Light theme
The spinner has a shadow that lowers the contrast, although all other _addition_ don't have a shadow.
Without shadow:
![spinner-light](https://user-images.githubusercontent.com/73243667/122681728-10443e80-d1f6-11eb-9dfd-c0d407d876bc.png)

**Comment by Feichtmeier** [comment]
Hmmm. Def. needs the shadow to get a little depth. THe bigger circle could work. Could you show a picture with the white outline though? :)

**Comment by Benni3-1415** [comment]
> Def. needs the shadow to get a little depth.

If all the _additions_ were given a shadow, those with a black border would look blurry:
![link](https://user-images.githubusercontent.com/73243667/122682243-a24d4680-d1f8-11eb-9dd8-0a07040e96ac.png)

#### @Feichtmeier your outline
![spinner-outline](https://user-images.githubusercontent.com/73243667/122682112-e0963600-d1f7-11eb-9617-435cdfa2b50c.png)

**Comment by Feichtmeier** [comment]
Well, this looks better IMO
I would not say that this spinner is "an addition". It is a full cursor :)
And thank you for the work btw :)!!!
Let's wait on the others' opinion

**Comment by Muqtxdir** [comment]
@Benni3-1415 would be cool if you could push a PR, so that we can see how it looks on various backgrounds.

but judging from the images in this issue-thread, this looks good

**Comment by Benni3-1415** [comment]
> I would not say that this spinner is "an addition". It is a full cursor :)

Right, it is very unusual to have a cursor as an _ addition_ ...

The spinner is the only cursor / widget, where a shape fades out!

#### Spinner as cursor
![cursor1](https://user-images.githubusercontent.com/73243667/122683227-248c3980-d1fe-11eb-93b8-c0b2a732091d.png) ![cursor2](https://user-images.githubusercontent.com/73243667/122683239-37067300-d1fe-11eb-866a-8459c4410d3c.png) ![cursor3](https://user-images.githubusercontent.com/73243667/122683250-45ed2580-d1fe-11eb-941f-0daf0c9c1057.png)
