### ISSUE TITLE
With dark theme, current line is unreadable in Gedit

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#2924]
Is this the case for everyone, or has something just gone funny for me?  The current line is highlighted in Gedit, but in dark theme, it comes out as white on light grey:

![image](https://user-images.githubusercontent.com/38893390/122767666-cc574500-d29a-11eb-9288-d1bbed05e13c.png)

**Comment by Muqtxdir** [comment]
Hi @ubuntujaggers 👋

This is known-issue and caused because of using the default classic `gtksourceview`, you can correct this by going to **preferences** -> **fonts & colors** and choosing either ***Yaru-light*** or ***Yaru-dark*** color scheme

**Comment by clobrano** [comment]
Yes, we had some Launchpad issues tracking this, but I think @flexiondotorg fixed also this in Mate somehow

**Comment by Muqtxdir** [comment]
@clobrano does it make sense to trigger theme-change of **gedit** via Appearance in Settings like this?

https://user-images.githubusercontent.com/54065734/124188293-b4729300-dadc-11eb-8071-f7c0c0c22400.mp4

**Comment by fouzan14** [comment]
I am also affected by this issue, @clobrano @muqtxdir @ubuntujaggers do I install yaru from Github to get this menu in Settings ?

**Comment by clobrano** [comment]
Hi @Muqtxdir, sorry for the late response, I didn't get the notification this time. It is a nice idea 👍

**Comment by Muqtxdir** [comment]
> Hi @Muqtxdir, sorry for the late response, I didn't get the notification this time. It is a nice idea +1

no problem, I'll add gedit-prefrences scheme into Theme-preview boxes.

> I am also affected by this issue, @clobrano @Muqtxdir @ubuntujaggers do I install yaru from Github to get this menu in Settings ?

@fouzan14 Sorry for the confusion this is not part of this repository, the clip is based on not yet finalized MR for **Settings: Appearance**. Hopefully, if it's approved you could look forward for this in ubuntu 21.10

**Comment by Muqtxdir** [comment]
The suggested patch for switching Text-editor color scheme along with GTK-theme has now been merged into GCC, take a look at this [gnome-control-center_40.0-1ubuntu4](https://launchpad.net/ubuntu/+source/gnome-control-center/1:40.0-1ubuntu4) (*only available on Ubuntu 21.10*) 

### screen-record:

![Peek 2021-08-05 13-43](https://user-images.githubusercontent.com/54065734/128316758-16d18fd9-fe16-4770-9e7f-6cd81e6955ca.gif)

closing the issue since this is resolved in the latest build of GCC
