### ISSUE TITLE
Remove aubergine from the Yaru palette

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2925]
This comes directly from a rebranding initiative at canonical:

All widgets coloured in aubergine need to be coloured in monochrome or ???. The only exception are the green elements.

This needs changes in gtk2, gtk3, gtk4, cursor theme and gnome shell theme for:

- sliders
- checks/radios
- switches
- the wait cursors

WIP: on waiting mode until the accent color is chosen

**Comment by LinuxLlama** [comment]
Would this also include the login screen? #2910

**Comment by Feichtmeier** [comment]
Good question - CC @elioqoshi

**Comment by Initu-Castilhos** [comment]
But the icons also have to change, as the tab has aubergine and orange gradient colors.

**Comment by Feichtmeier** [comment]
> But the icons also have to change, as the tab has aubergine and orange gradient colors.

I think gradients can stay

**Comment by elioqoshi** [comment]
> Would this also include the login screen? #2910

As far as I know everywhere aubergine is applied, so yes. 

In the context of the login screen we might apply light or dark theming to it, I assume? I mean there shouldn't be any reason for it to be dark if the light theme is selected, right?

Please keep in mind these are all work-in-progress discussions and we might not have all of the answers yet :)

**Comment by ro1y** [comment]
I personally think a black background or a mascot-less version of the current version's background would look nice for the lock screen.
