### ISSUE TITLE
Header bar is too huge

### ISSUE THREAD

**Issue by joaopauloalbq** [ubuntu/yaru#2935]
Could a more compact headerbar be added?

> Huge
![yaru huge](https://user-images.githubusercontent.com/9905202/123682241-24ed8b80-d821-11eb-9c41-525689fa1683.png)

> Compact
![yaru compact](https://user-images.githubusercontent.com/9905202/123683703-e953c100-d822-11eb-80f3-a341528d06da.png)

**Comment by Feichtmeier** [comment]
Hi there, we've decided to not change any of gnome themes padding. So I'm sorry but we're not gonna change this. Best regards and thanks for wanting to help

**Comment by joaopauloalbq** [comment]
I understood :(
Thanks for the answer!
