### ISSUE TITLE
GNOME Software 40-41 inconsistencies with Adwaita

### ISSUE THREAD

**Issue by LinuxLlama** [ubuntu/yaru#2941]
**Application:** gnome-software
**Version:** 41~alpha-0.20210701git839e7b0.fc34
**System:** Fedora 34 (Workstation Edition)
**Yaru:** 21.04.1-109-g3b9b1ffa

The latest development version of GNOME Software has some issues with the Yaru theme. Notice the lack of a border around the installed section:

![Screenshot from 2021-07-01 08-23-38](https://user-images.githubusercontent.com/29968331/124151803-cbb37100-da47-11eb-98d7-769953443275.png)
![Screenshot from 2021-07-01 08-23-52](https://user-images.githubusercontent.com/29968331/124151819-d110bb80-da47-11eb-8f71-862634934770.png)

The updates section has some unusual styling which is also present in the current stable release. The header background should match the rest of the box:

![Screenshot from 2021-07-01 08-23-22](https://user-images.githubusercontent.com/29968331/124152279-3cf32400-da48-11eb-80e8-c58b69449ec1.png)
![Screenshot from 2021-07-01 08-24-01](https://user-images.githubusercontent.com/29968331/124152298-4086ab00-da48-11eb-9b8d-06adb9f54ea6.png)

I'm able to test the new software design using a COPR repository on Fedora 34. [Here's the link for anyone interested.](https://copr.fedorainfracloud.org/coprs/mcrha/gnome-software-devel/)

**Comment by Feichtmeier** [comment]
I guess that's new custom CSS :) 

https://gitlab.gnome.org/GNOME/gnome-software/-/blob/master/src/gtk-style.css
