### ISSUE TITLE
Login screen button highlights are hardly perceptible

### ISSUE THREAD

**Issue by vanvugt** [ubuntu/yaru#2947]
On the login screen I can tab between the password field, back button and cogwheel button. But when either of the buttons are selected it's hardly noticeable. They're either white or slightly more white. It should be more obvious which button is focussed when tabbing between them on the keyboard.

Shell version: 3.38.4
OS version: Ubuntu Impish Indri (development branch)

Package: yaru-theme-gnome-shell
Version: 21.04.1

**Comment by Feichtmeier** [comment]
I think we actually thought this was fixed. @Jupi007 could you double check?
If not I would suggest to revert it back to what upstream uses

**Comment by Jupi007** [comment]
This is indeed fixed in master because we reverted to upstream look:

![Peek 08-07-2021 11-27](https://user-images.githubusercontent.com/36476595/124898475-8363f800-dfdf-11eb-840a-379f9f9e3ad8.gif)

I did this into #2871.
