### ISSUE TITLE
Global row selection is problematic

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2954]
The row selection for nautilus and apps with similar layout works.

However it does not work well globally because those rows can be everywhere
![grafik](https://user-images.githubusercontent.com/15329494/126298119-0ad147e1-916e-46a6-8f80-a3eb842c4c28.png)
(portal)

![grafik](https://user-images.githubusercontent.com/15329494/126298236-d3fd0d53-3c92-4a25-8eb9-4d5861241962.png)
(gnome software)

@Jupi007 do you have any idea how we can limit this to nautilus and gnome control center?

**Comment by Jupi007** [comment]
About nautilus, we can use the `.nautilus-window` top level selector, but as far as I know, there's no way to target gcc.

Maybe only style nautilus like this, and make selected row grey every where?

**Comment by Feichtmeier** [comment]
That sounds like a good idea yeah.
