### ISSUE TITLE
Support MIME type text/x-c++hdr

### ISSUE THREAD

**Issue by jgcodes2020** [ubuntu/yaru#2962]
**Icon Request**

Support `text/x-c++hdr`.

**Steps to locate the icon**

This icon will likely require an original design, but it should bear similarities to both the C header icon and C++ source icon.

**Software where the icon is missing**

- Name: Nautilus
- Version: 3.38.2-stable
- OS version: Ubuntu 21.04 (hirsute)

**Screenshots**
If we are going to maintain similarity to C icons, we could use a slightly lighter shade of red than this:
![text-x-chdr](https://user-images.githubusercontent.com/35639051/126643983-ffc9416b-b8f2-4df9-961f-f89b24cd8f7e.png)
And similar to this
![text-x-c++](https://user-images.githubusercontent.com/35639051/126644025-6ca0888a-d147-40ec-9058-e20a50c44bd9.png)
but with `H++` on it.

**Comment by Muqtxdir** [comment]
Hi @jgcodes2020 👋

Based on your suggested-input I've created a PR, do checkout: #2969
