### ISSUE TITLE
File manager is not our best icon...

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/yaru#2964]
I know everyone's pretty sick of this icon :smile: but I wondered what you thought of a small change to make the purpose of the app a little clearer:

![image](https://user-images.githubusercontent.com/38893390/126822359-0590c8cb-5c99-432d-9135-a841fdd3f63c.png)

![image](https://user-images.githubusercontent.com/38893390/126822397-37c7492c-b9ce-4491-ad18-865727bb7112.png)

**Comment by Feichtmeier** [comment]
nice idea. how does it look on the small size?

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/126832503-6b1117d3-3f48-4ec4-88b9-49247b44d47b.png)

**Comment by ubuntujaggers** [comment]
Hang on, one of them is too big... (32px)

**Comment by ubuntujaggers** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/38893390/126832714-ffa35055-4c15-467b-ab9e-4435b833df79.png)

**Comment by Muqtxdir** [comment]
Few general-opinions that I gathered from previous issues (see: #2800 #1891 #1755 )
- The Files icon inside the Square-baseplate looks a tad smaller than other Square icons (*Optical illusion point*)  
- Files-app icon is not similar to the Folders/Directories icons (*continuity and consistency point*)

Unfortunately I can't say it resolves these two and also may confuse others why there's a magnifying-glass/search icon on files app?

#### my suggestion:
##### White-baseplate with current folder:
![files1-dock](https://user-images.githubusercontent.com/54065734/126832556-7f27e2b9-336b-4978-a609-ddea3f2a9c37.png)

##### just current folder:
![files-dock](https://user-images.githubusercontent.com/54065734/126832656-45e765bc-25f8-44c0-8395-d79ad59686d5.png)

**Comment by madsrh** [comment]
I just had this idea 🗄️  Can you see it? 😅 

![image](https://user-images.githubusercontent.com/3986894/126849193-00f3eaf7-df66-478d-8c20-b9302c2d72ac.png)

**Comment by LinuxLlama** [comment]
Since we're throwing out ideas, what about a design like this? I tried to match the home folders. Ideally, the icon would be thinner and the folder size would match the rest of the icons

![folder](https://user-images.githubusercontent.com/29968331/126853747-e9403f6e-a518-49fa-8e52-b5a26c9b02f6.png)

**Comment by Feichtmeier** [comment]
There is one problem I see with the search metaphor: there is a specific type of directories/folders called "search results". This reminds of this. Gathering ideas sounds really great btw.

**Comment by ubuntujaggers** [comment]
> I just had this idea  Can you see it? 

Could flatten the top of the grey bit to make the front of a drawer:

![image](https://user-images.githubusercontent.com/38893390/126880926-884b175a-7d8b-4320-8a80-6d1cd76344a1.png)

**Comment by madsrh** [comment]
> Could flatten the top of the grey bit to make the front of a drawer

Yes! I don't know what everyone else thinks, but if it's no trouble, I would love a test PR for this @ubuntujaggers

**Comment by LinuxLlama** [comment]
> I would love a test PR for this

@madsrh Check #2965 😉️

**Comment by madsrh** [comment]
Closing this since #2965 is merged 🤘
