### ISSUE TITLE
Add an icon for synaptic and make Adwaita dependent.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#2967]
![Captura de tela de 2021-07-25 22-33-13](https://user-images.githubusercontent.com/59381215/126921889-eba57887-d4c8-4163-95d7-6e5a1dfcdbb3.png)
![synaptic](https://user-images.githubusercontent.com/59381215/126921910-0a9971d9-317f-4308-9b5a-8c3cb1b76a20.png)
Example icon for synaptic like the image above

**Comment by madsrh** [comment]
Isn't this actually two independent issues @Initu-Castilhos :

1. Add Yaru style icon for Synaptic
2. Make Yaru inherit icons from Adwaita (rather than Humanity)

Is this correct?

**Comment by Initu-Castilhos** [comment]
> Não são duas questões independentes @ Initu-Castilhos :
> 
> 1. Adicionar ícone de estilo Yaru para Synaptic
> 2. Faça Yaru herdar ícones de Adwaita (ao invés da Humanidade)
> 
> Isso está correto?

Yes!

**Comment by Muqtxdir** [comment]
Hi @Initu-Castilhos 

just created PR #2972 which adds icon for synaptic-package-manager, do checkout the branch
