### ISSUE TITLE
Missing icon: update-notifier

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2974]
![image](https://user-images.githubusercontent.com/3986894/127734784-afec296f-1d8b-4304-9dfe-56d4b5def9bf.png)

**Comment by Feichtmeier** [comment]
It's the update notifier :) this thing always crashes in the daily Iso since some years
We tried to make an icon for it once but then it was pixeled because somehow the small resolution icon is taken

**Comment by madsrh** [comment]
Doh, I knew that! It says so in the top bar 🤦‍♂️

Also the **System-crash-notification** is weird.

![image](https://user-images.githubusercontent.com/3986894/127735535-eee3b3aa-d33a-43f4-92f9-9e9a3c385122.png)

**Comment by madsrh** [comment]
Sorry I was on an old branch
