### ISSUE TITLE
canberra-gtk-play cannot play desktop-logoff.oga

### ISSUE THREAD

**Issue by peterwu** [ubuntu/yaru#2986]
```
$ canberra-gtk-play -i desktop-logoff
Failed to play sound: File or data corrupt
```
desktop-login works no problem.

**Comment by madsrh** [comment]
Hi @peterwu 
Thanks for taking the time to report this 👍 
It does indeed look like the _desktop-logoff_ is encoded with the wrong format. It should have been Ogg Vorbis audio.

@ItzSwirlz could you create a PR with a fixed version?

![image](https://user-images.githubusercontent.com/3986894/129627474-54006860-2c97-4df2-a6bc-64dd6c136a25.png)
