### ISSUE TITLE
Add colored category icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3008]
Add colorful category icons to ArcMenu and other graphical environments like: Cinnamon, XFCE, etc...
![Captura de tela de 2021-09-11 20-26-35](https://user-images.githubusercontent.com/59381215/132966209-b84e96c7-0938-4739-a95c-f139afa9a5a5.png)

![Captura de tela de 2021-09-11 20-28-09](https://user-images.githubusercontent.com/59381215/132966232-06ac9cb9-fb7b-4d96-8ff7-dec9b5275722.png)

Yaru-MATE icons can be used.

**Comment by Muqtxdir** [comment]
Hi @Initu-Castilhos 

The fullcolor-category icons have been added to Yaru by @Jupi007 in PR: #3225
