### ISSUE TITLE
GDM: add a border to buttons

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#3012]
IMO the buttons need a subtle border like the entry and the popup

![FLAMESHOT_2021-09-15_12-49](https://user-images.githubusercontent.com/15329494/133420522-ad333492-e365-4ac0-af13-24bcb8596222.png)

@Jupi007 could you eventually take care for this one for 21.10? :angel:

**Comment by Jupi007** [comment]
Ofc, will do it tonight :+1:
