### ISSUE TITLE
outdated ubiquity styling

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#3015]
Last night I tried out installing `ubuntu-desktop-21.10` and noticed these couple of issues:
(_see below screenshot and notice the highlighted numbering alongside the selected red-boxes_)

#### screenshot:
![2021-09-17_12-34](https://user-images.githubusercontent.com/54065734/133739707-a06cbf88-bcd0-4623-8c60-aec94247193e.png)

#### issues:

1.  The headerbar still uses the old Yaru headerbar_color in Light theme (_default one_)
2.   All slideshow screenshots are outdated as they represent the old Yaru theme
3.   The Appearance page is outdated and should use the one from ubuntu 21.10
4.    The dock options presented are less compared to what is offered (_missing **Show on:** option_)

**Comment by Feichtmeier** [comment]
Hi @Muqtxdir 
Both the slideshow and that dark heading is controlled by html
@madsrh made it in the past

____

I hope they will update the appearance page in time :( 
So it is already merged on launchpad?
I don't even know whom to tag anymore but maybe @didrocks finds time to help

**Comment by Muqtxdir** [comment]
> I hope they will update the appearance page in time :(
So it is already merged on launchpad?

The current appearance-page in 21.10 builds looks like this:
![Screenshot from 2021-09-17 14-17-02](https://user-images.githubusercontent.com/54065734/133753657-9cc7b74e-4a17-4257-9529-d5179a1ce93b.png)

However in [LP: #1943849](https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1943849) daniel just assigned it to me with status as ***in-progress***, so it may only needs review form robert and then merged
