### ISSUE TITLE
"copy" emblem in mouse cursor has poor contrast with orange selected item colour

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#3016]
Not a big deal, but the little plus icon on the drag-and-drop cursor is orange, and often what you're dragging-and-dropping is also orange (since it was selected), so this results in poor contrast:

![yaru-cursor](https://user-images.githubusercontent.com/1044087/133866007-973a6721-62c6-45c1-b0d9-8b3af230ae75.png)

Perhaps green would be better?

(rough GIMP scribble):

![yaru-cursor](https://user-images.githubusercontent.com/1044087/133866100-a4ee61fe-0551-4d02-97e4-ec85fdc26c40.png)

Or any other colour that is part of the yaru palette.

**Comment by Jupi007** [comment]
Very good suggestion 🤔

What do you think of @ubuntu/yaru-team ?

**Comment by Feichtmeier** [comment]
Totally agree. We should use green

**Comment by Muqtxdir** [comment]
I'd say we change the orange parts of `dnd-copy` and `copy` black-gradient, as the one found in `left_ptr_watch`. also we can't go for green because yaru-mate uses green shade for selected-items.

**Comment by madsrh** [comment]
+1

**Comment by Jupi007** [comment]
@Muqtxdir But the Mate green isn't the same as the green from our palette. So it is really annoying?
Does anyone can take screenshot from Mate?

Otherwise we could use purple 🤔

**Comment by Feichtmeier** [comment]
The mate green is different but maybe @Muqtxdir is right and we should use monochrome to be as neutral as possible

**Comment by Jupi007** [comment]
> The mate green is different but maybe @Muqtxdir is right and we should use monochrome to be as neutral as possible

Will try this :)

**Comment by chrisjbillington** [comment]
Brilliant, thanks for the fix!
