### ISSUE TITLE
Titlebars color are both light or dark

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#3018]
[Ubuntu 21.10, Ubuntu session, all Yaru appearance]

Hi,

I use Yaru (light).
I noticed some dark titlebars (as previous Yaru): terminal, firefox snap, chromium snap, libreoffice snap...
Some other are light: nautlius, logs, system monitor...

Is that intended? Is that a cache issue?

**Comment by Feichtmeier** [comment]
Yes we only have yaru (light) and yaru-dark (dark) now.

**Comment by Muqtxdir** [comment]
hi @fthx 👋

Thanks for reporting this, from what I can make snap-apps still use the old yaru headerbar? If that so then @Feichtmeier it might be good time to create the `ubuntu/impish` branch so that `gtk-common-themes` can be updated to that

**Comment by fthx** [comment]
Oooookkayy!
For GNOME Terminal, I feel it's an Ubuntu theming as Adwaita GTK theme in Ubuntu session gives me a black header bar too.
IMO that's not consistent with new light header bars in Yaru?

**Comment by fthx** [comment]
I found the culprit.
![image](https://user-images.githubusercontent.com/23138504/133908000-a06e08db-b53b-42ca-a692-adb9c89da288.png)
Using "system" value makes the headerbar follow Yaru's light colors.

**Comment by fthx** [comment]
For sure I did not modify this key!
I did not even know this key!

**Comment by Feichtmeier** [comment]
> Oooookkayy!
> For GNOME Terminal, I feel it's an Ubuntu theming as Adwaita GTK theme in Ubuntu session gives me a black header bar too.
> IMO that's not consistent with new light header bars in Yaru?

There are several apps that use the "prefer-dark" flag in gNoMe :) additionally Ubuntu uses this flag for the terminal. So there are several apps in Ubuntu perma dark,  which is in my opinion a VERY bad idea. I think this comes from a time when dark themes weren't a thing. I think it's too late now for a change to this in 21.10 but maybe we can ask for this in the next cycle. There are quiet a few people insisting on the permanent dark terminal though. So brace yourself for a little battle ;)

**Comment by Feichtmeier** [comment]
Ok after re reading the issue I think this is also related to gtk-common- themes

Since we've removed yaru light if you are not on impish already the snaps won't match the debs :/

On note of the dark terminal I think it's ok to have the prefer dark option pre-selected because you can opt out of it by selecting the system default in the terminal settings.
Most people still prefer the permanent dark terminal. For those who don't they can change to follow the system.
