### ISSUE TITLE
GTK theme parsing error: The :insensitive pseudo-class is deprecated

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#3028]
I'm getting this warning whenever running Gtk apps from a terminal, looks like it might be caused by the change in #3027
```
Gtk-WARNING **: 09:41:16.422: Theme parsing error: gtk.css:5571:2295: The :insensitive pseudo-class is deprecated. Use :disabled instead.
```

I'm on Arch Linux using yaru from the master branch, installed from the [AUR](https://aur.archlinux.org/pkgbase/yaru-git/)

The GTK version according to pacman is 3.24.30+62+g8d04980f38-1

**Comment by Jupi007** [comment]
Thanks for the report @chrisjbillington :)
I made a fix in the linked PR.

**Comment by chrisjbillington** [comment]
Thanks! Can verify the warning is gone now.
