### ISSUE TITLE
No 'default' button indicator

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/yaru#306]
With dialogs, etc, there is no indication as to what is the 'default' button - i.e. the button that is activated with the return/enter key. At start there is a focus rect, but this can be 'tabbed' away.

In the following screenshot, which is the default button?

![screenshot from 2018-04-02 12-19-57](https://user-images.githubusercontent.com/1141694/38194568-3066e2c8-3670-11e8-8c9c-e8c68c9878d9.png)

Perhaps a bold font should be used to indicate the default?

**Comment by clobrano** [comment]
Probably it's just missing the style for the selection ring

**Comment by CDrummond** [comment]
Selection ring? You mean focus? As stated the dialog starts with a focus indicator, but if you press 'tab' then it will eventually lose it.

Most desktops (KDE, Windows, macOS) indicate the 'default' button somehow - different colour, border, etc. The default button **can** be different to the widget that currently has focus - as can be seen by the screenshot above, because one of those does receive the return/enter key.

**Comment by clobrano** [comment]
![image](https://user-images.githubusercontent.com/2883614/38208037-fb8a9c62-36af-11e8-902f-cd66b264200f.png)

This is selection ring. So if the dialog starts with a focus indicator is OK, if the user press tab is trying to move somewhere else in the window, so he/she cannot expect to press enter and activate the default action (which was the one selected at the start).
Or are you talking about suggest action?

**Comment by CDrummond** [comment]
That's what I said. Initially it **has** focus. If I press tab, it loses focus - but will **still** react to enter/return. Hence why needing to indicate this button somehow.

Steps to reproduce:

1. Start GEdit
2. Type some text
3. Close GEdit
4. Dialog appears - `Save As...` has focus
5. Press `tab` key
6. `Save As...` no longer has focus, so no focus/selection ring
7. Press `Return`
8. `Save As...` button **is** pressed, and save dialog appears

I know this is a contrived example, but demonstrates that there is a _default_ button and this should be indicated somehow.

**Comment by CDrummond** [comment]
Also, with Geary's delete confirmation dialog, when tabbing from `Cancel` to `Delete` its no longer obvious where the focus is. Here, if the default button was indicated with bold text - then the text in `Delete` would turn bold.

![screenshot from 2018-04-02 19-59-12](https://user-images.githubusercontent.com/1141694/38210856-840d65a6-36b0-11e8-8c43-52601272f6f2.png)

**Comment by Feichtmeier** [comment]
@clobrano ah! Interesting - so one could theme the focus ring for specifc classes? Like for tabs in the GtkNotebookBar ? This would be a solution to https://github.com/ubuntu/gtk-communitheme/issues/303

**Comment by clobrano** [comment]
Yes, selection ring is defined separately for different widgets.

The point here is that we don't know which is the "default" action, unless styled with "suggested-action", but it is a different thing. We just now which is the initially selected button (but for selection we already have selection ring). When one press Tabs the focus goes elsewhere, according to the structure it might go to another button and then press will be on that button, not on the initial one.

**Comment by Feichtmeier** [comment]
@clobrano great. Could you help me out on #303 ?

Whats the name of the property?

**Comment by clobrano** [comment]
Sorry, but I can't do that now. Try looking for active or checked state. Also you might double check the places where selection color is used

**Comment by CDrummond** [comment]
Perhaps these screenshots will make things clearer? They're from Gtk2 Ambiance.

In this screenshot `Open` is the default button (coloured orange), and it has focus (orange glow).
![db](https://user-images.githubusercontent.com/1141694/38245629-d474c9fe-3736-11e8-81e9-3713d0de9d32.png)

In this screenshot `Open` is the default button but it does not have focus.
![dbf](https://user-images.githubusercontent.com/1141694/38245658-f1afed1e-3736-11e8-8886-742838a93539.png)

**Comment by Feichtmeier** [comment]
Ah yeah he is right, look this is ambiance GTK3 in Gedit
Just pressed closed and did not do any focus cycling via tab

![screenshot-20180403130719-741x453](https://user-images.githubusercontent.com/15329494/38245846-0dafd610-3740-11e8-8ff1-003a05723885.png)

**Comment by clobrano** [comment]
> In this screenshot Open is the default button (coloured orange), and it has focus (orange glow).

This is because "Open" is styled as "suggested-action". We use green for those buttons, but "Save As..." is not a suggested action.

I understood what you are asking, but I am not convinced with the change. Default action is already highlighted at the beginning. On gedit if you press tab twice, selection ring goes to "close without saving" even on Adwaita.
At this point, the bold text on Save As does not make any sense anymore, since if you press enter the action would be to close, not to save. I think this tab behavior" is just a problem with the windows structure, not with the theme

**Comment by CDrummond** [comment]
The bold text would follow the default button. When there is a button has focus it is also the default button (therefore focus ring + 'default indicator'). When no button has focus - then the bold font (or some other indicator) would signify which is the default.

**Comment by clobrano** [comment]
> therefore focus ring + 'default indicator'

So either one of focus ring or default indicator is redundant. Instead when a button other than default is selected, we will have to button styled differently. Which one will be activated on enter?

> When no button has focus - then the bold font (or some other indicator) would signify which is the default.

Are we sure about that? I have no evidence that, for sure, if no button has focus, the default one is pressed on enter.

Current behavior looks fine to me. If you want to activate the default do not press tab first.

**Comment by CDrummond** [comment]
I think you are getting hung up on this one specific dialog. Look at Geary's Accounts settings dialog (the one with the IMAP settings, etc). Here `Save` is the default button - but it does not initially have focus. If I use the `United-Ubuntu` theme, this `Save` button is given an orange background. Pressing `Enter` does indeed activate the `Save` button even when another widget has focus.

**Comment by CDrummond** [comment]
@clobrano 

> So either one of focus ring or default indicator is redundant. Instead when a button other than default is selected, we will have two buttons styled differently. Which one will be activated on enter?

Button with default indicator (e.g. bold) will be activated on Enter
Button with focus ring will be activated pressing Spacebar

**Comment by clobrano** [comment]
> Button with default indicator (e.g. bold) will be activated on Enter
> Button with focus ring will be activated pressing Spacebar

I didn't know this combination, but I cannot reproduce it. If I select another button and press enter, the default one is not activated, but the selected one is.

**Comment by CDrummond** [comment]
As stated, if a button has focus its is the current default button also. So:

No button has focus - there _can_ be a default button
A button has focus - it is the default button

Look at Rhythmbox's preference dialog. Initially the notebook tab has focus, and not a button. But if you press enter `Close` is activated => `Close` is the default button. If I press the spacebar, nothing happens - as no button has focus. I can now tab to the `Help` button. If I press spacebar, it is activated. If I press Enter it is also activated (as it is the current default button).

In this situation we'd have:
1. Initially tab has focus ring, `Close` has default button indicator
2. After tabbing to the `Help` button - it would have both the focus indicator and default button indicator (because it is the currently focused widget, and the current default button).

**Comment by clobrano** [comment]
What I said is that with a button selected, pressing spacebar did nothing. I guess it depends on the application. 
Anyway, I'm a bit more convinced now, at least it should not harm

**Comment by CDrummond** [comment]
@clobrano Ah, OK - must admit I wasn't sure about your comment. But try Rhythombox's preferences dialog. Checks/radios react to spacebar, as well as buttons (in fact most widgets do).

**Comment by clobrano** [comment]
I made some tests. I was surprise to see that *default* style class moves from button to button pressing tab or arrow keys. Below I just changed the font to bold for "default" button, as you can see it moves with selection ring

![default-button](https://user-images.githubusercontent.com/2883614/38274700-d089f7ac-378f-11e8-9f4c-d5f35fd41010.gif)

using bold is not an option, since with small button it changes the size of the button itself.

Here again with a different color

![default-button](https://user-images.githubusercontent.com/2883614/38274888-696d924e-3790-11e8-87dd-9ba591ad2419.gif)

It was OK for me to use bold style in theory, but changing color is weird, so I'm not sure what to do.

@madsrh any though?

**Comment by madsrh** [comment]
Orange text is **never** the answer :joy: 
Would a thicker dark border work as the default button indicator? My initial thought was gray just to avoid it stealing too much focus like in United.
![image](https://user-images.githubusercontent.com/3986894/38277680-8e020302-3799-11e8-91c2-1c886e5c3a2f.png)

...but it could be orange or green too 🤔

![s](https://user-images.githubusercontent.com/3986894/38277784-f0f79c88-3799-11e8-8110-05fa6642400e.gif)

**Comment by CDrummond** [comment]
The problem with the thick border is that you loose the shadow effect.
c
What about something more subtle? Kvantum on some styles draws a small rectangle in the bottom right corner of the default button:

![screenshot from 2018-04-03 23-09-05](https://user-images.githubusercontent.com/1141694/38278484-1c03b002-3794-11e8-8d81-f7773614959c.png)

**Comment by clobrano** [comment]
green (success-color) colored border.

![default-button-border1px](https://user-images.githubusercontent.com/2883614/39093607-4bd437c4-4622-11e8-8559-0b8155ad2b75.gif)

 You can see that there is a superposition with the orange selection. I tried also removing the orange from default button, but it looks weird when the window has other kind of widgets too

![default-button-border1px-no-outline](https://user-images.githubusercontent.com/2883614/39093629-cd1e80c8-4622-11e8-82cc-44a2187d4f37.gif)

Here with ash ($ash: #878787;) in place of green. Better not use darker colors to don't compromise the box-shadow
![default-button-border1px-ash](https://user-images.githubusercontent.com/2883614/39093664-81c05696-4623-11e8-9dfc-a1baf599209f.gif)

**Comment by madsrh** [comment]
Great work @clobrano 👍
The orange+green mix is weird to me and I agree with you on removing the orange selection. 

I think ash looks really good 😄 It's sublte, but a good solution. What do you think @CDrummond ?

**Comment by CDrummond** [comment]
I'm no designer - but the ash version looks good to me. Its subtle, but does give an indication without being in your face.

**Comment by clobrano** [comment]
And ash be :+1:

**Comment by clobrano** [comment]
Just one more thing. You might have noticed that I also changed selection ring style from continuous line to dashed, so that the superposition of border and selection ring itself is less strong. What do you think?

**Comment by madsrh** [comment]
👍 I think it's easier to understand than the solid border for UX

**Comment by Feichtmeier** [comment]
I like that. Because I was already about to report my dislike of the selection ring xD
At the moment the position looks almost like there is another layer on the button. With the dotted line this impression should vanish :grin: +1

**Comment by Feichtmeier** [comment]
Could we look at this black border one more time?
I think it looks a bit unfinished. Any other ideas @madsrh ? Maybe a green button?

**Comment by clobrano** [comment]
> Maybe a green button?

It will clash with suggested action if available in the windows. Default action is very similar to selected button, since it can move from one button to the next pressing tab.

**Comment by Feichtmeier** [comment]
How about a bold font?

**Comment by clobrano** [comment]
> How about a bold font?

Bold font will increase the label space, resulting in the button to expand if it's too small

> Edit: I've think this "default" button is also jumping around. Is this intended?

yes, see my comment above ;)

**Comment by Feichtmeier** [comment]
I think it is the combination of the dashed line with the black border that made me come up with all these annoying requests :) 
I wonder why has adwaita not these default button indicators Oo
![peek 2018-08-08 10-08](https://user-images.githubusercontent.com/15329494/43824727-10d51514-9af3-11e8-815b-c71d5fcc9cec.gif)
Maybe we can just remove it? :see_no_evil:

**Comment by clobrano** [comment]
>  Maybe we can just remove it? see_no_evil

I don't think it would be a good move. It shows what happen if the user press enter without touching anything before. I know it's a bit annoying if the user press tab instead, but it's useful in cases like below...

![image](https://user-images.githubusercontent.com/2883614/43824927-a1ac81a8-9af3-11e8-91ba-31c669745fb3.png)

...where I tabbed to move selection ring somewhere invisible, but if I do press enter, it's "save" button that is pressed

**Comment by clobrano** [comment]
> How about moving the dashed line back to the outer line then?

How would you remove the outline only if there is the default selector?

**Comment by CDrummond** [comment]
Simple suggestion - could a (light grey?) underline be added below the text? That would  be a subtle indicator.

**Comment by Feichtmeier** [comment]
Ah sorry bad writing skills:

Default indicator: Black solid border (now) -> Dashed $borders_color (idea)
Focus ring: Transparent orange dashed line with -3px margin (now) -> full orange or blue dashed line with 0 margin (idea =))

**Comment by clobrano** [comment]
> Focus ring: Transparent orange dashed line with -3px margin (now) -> full orange or blue dashed line with 0 margin (idea =))

I think it's a nice idea, I was exploring it yesterday a little. The problem is the radius that, once the focus ring is big as the button border, looks different than the one of the button :(

**Comment by Feichtmeier** [comment]
The current color looks again a bit like salmon :laughing: 

Could you point me to the code so I can play around too? :play_or_pause_button: =D

**Comment by clobrano** [comment]
This one I guess

https://github.com/ubuntu/yaru/blob/024cb92dd2aa911daf83cb74c69b39d5e834fd9b/gtk/src/gtk-3.0/_common.scss#L565

**Comment by Feichtmeier** [comment]
![peek 2018-08-08 11-35](https://user-images.githubusercontent.com/15329494/43829416-28cc99c4-9aff-11e8-96df-ddcc222bff5c.gif)

Orange text color for the default button
Orange dashed line with -1px (that's actually right on the border) for the focus ring

**Comment by clobrano** [comment]
Sure it's more evident than current black border, but I'm not convinced by

1. dashed selection ring over black button border
2. orange is still the color of selection, while default is more indication, but this is a lesser problem
