### ISSUE TITLE
Completed and remaining parts of progress bar in Transmission are the same colour

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#3079]
The progress in a progress bar in Transmission is not visible, because the "completed" and "incomplete" parts of the progress bar are the same colour. This only occurs for the selected item.

**Software that presents the issue**

Transmission 3.00-2 on Arch Linux

**Yaru version**

21.10.2 installed from the AUR on Arch Linux

**Screenshots**

Yaru:

![Peek 2021-10-01 22-13](https://user-images.githubusercontent.com/1044087/135618215-a81a89dc-aec2-4246-ac48-4931d878a4bb.gif)

Yaru dark:

![Peek 2021-10-01 22-14](https://user-images.githubusercontent.com/1044087/135618225-4e9d67f3-7405-42dc-a84c-19277d3668f1.gif)

**Upstream check**

Adwaita:

![Peek 2021-10-01 22-14_1](https://user-images.githubusercontent.com/1044087/135618232-d7dc4eb2-5cfd-4c1e-8d0a-ae5815070049.gif)

Adwaita dark:

![Peek 2021-10-01 22-15](https://user-images.githubusercontent.com/1044087/135618239-a719ab3d-8e1b-4b05-aef8-379676cc8359.gif)

**Comment by Jupi007** [comment]
Thanks for the report @chrisjbillington :)
I'll take a look.

**Comment by chrisjbillington** [comment]
Thanks for the quick fix!
