### ISSUE TITLE
The dock and the panel have different background colors and the dock is not transparent

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#3111]
![grafik](https://user-images.githubusercontent.com/15329494/136472361-a0b9931c-447c-4e7b-9525-de505607a2f3.png)

We tried to band-aid fix this in the cycle but it didn't really work out. 
I think this looks really unpolished and needs a fix.

@3v1n0 anything you could do here? Something changed in the dock code from 21.04 to 21.10 so the styling is not correctly applied anymore.

**Comment by Feichtmeier** [comment]
@3v1n0 happy new year :partying_face: 

It seems to me that the option "custom-theme-shrink" was previously not set to true OR could be overwritten by the scss in yaru. In either case we currently have no space between the app icons which makes the whole dock look to condensed. Playing around with this option you can see the difference especially when you hover on an app icon which is next to an active app icon:

![ya](https://user-images.githubusercontent.com/15329494/148033601-30c2e913-121e-4a06-92f7-25ffe7088979.gif)

**Comment by Initu** [comment]
Glad you'll have more customization options in the dock.  I know this is not the place for this but it would be great if you have the option to move the date to the right side like Pop OS 21.10

**Comment by Muqtxdir** [comment]
> Glad you'll have more customization options in the dock. I know this is not the place for this but it would be great if you have the option to move the date to the right side like Pop OS 21.10

if you like what you see in this screencast, perhaps you need to take a look at [`what-if? PPA`](https://launchpad.net/~muqtxdir-m/+archive/ubuntu/what-if) (_for **ubuntu-20.04** and **ubuntu-21.10**_). 

https://user-images.githubusercontent.com/54065734/148268299-e623f412-38ba-4d56-a161-6cc30a38a4c4.mp4
