### ISSUE TITLE
cannot upgrade yaru-cinnamon-theme-icon after upgrading to Ubuntu cinnamon 21.10

### ISSUE THREAD

**Issue by arjanvaneerden** [ubuntu/yaru#3143]
**Expected Behavior**
"sudo apt-get upgrade" should be able to upgrade yaru-cinnamon-theme-icon

**Actual Behavior**
After upgrading ubuntu cinnamon to the newest version (21.10), sudo apt upgrade dfailes at yaru-cinnamon-theme-icon

Installing yaru-theme-gtk by typing sudo apt install  yaru-theme-gtk did not help, so I removed that again.
 

**Steps to Reproduce the Problem**
1) Upgrade Ubuntu Cinnamon from 21.04 tot 21.10 
2) sudo apt update
3) sudo apt upgrade
Output _with translation_
....
Uitpakken van .../yaru-cinnamon-theme-icon_21.10.2_all.deb wordt voorbereid...
_Preparing extracting .../yaru-cinnamon-theme-icon_21.10.2_all.deb_
Bezig met uitpakken van yaru-cinnamon-theme-icon (21.10.2) over (21.04.3) ...
_Extracting yaru-cinnamon ......._
dpkg: fout bij verwerken van archief /var/cache/apt/archives/yaru-cinnamon-theme-icon_21.10.2_all.deb (--unpack):
 kan '/usr/share/icons/Yaru-Cinnamon/16x16/categories/applications-multimedia.png.dpkg-new' niet openen: Bestand of map bestaat niet
_dpkg: error with archive ....yaru-cinnamon-theme-icon...: **cannot open '/usr/share/icons/Yaru-Cinnamon/16x16/categories/applications-multimedia.png.dpkg-new': File or folder does not exist**_
Er is geen apport-verslag weggeschreven omdat de foutmelding een probleem op het lokale systeem signaleert.
                           Fouten gevonden tijdens verwerken van:
 /var/cache/apt/archives/yaru-cinnamon-theme-icon_21.10.2_all.deb
_We did not write a apport report, since the error sees a problem on the local system. Failure found during excecuting /var/cache/apt/archives/yaru-cinnamon-theme-icon_21.10.2_all.deb_
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Software that presents the issue**

Ubuntu Cinnamon 21.10

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

**Yaru version**
$ yaru-theme-icon
21.10.2
Maybe this is already the newest version? In that case: does anyone know how to exclude yaru-theme-icon from the apt-get upgrade process?

**Comment by arjanvaneerden** [comment]
Sorry, I did not know that. Thank you that you looked into that anyway. I tried it, but it gave (almost) exactly the same error message as earlier. So, although I copied your exact sentence, including the specified _--reinstall_, it outputs _The following packages will be upgraded._  

Thank you anyway, I found out that I just could set this package on _hold_ for now, so that other packages can be updated.

**Comment by ItzSwirlz** [comment]
Hey there. Yaru cinnamon is currently part of the ubuntucinnamon-environment package (it was moved). I thought this *might* cause issues but it would make everything easier so I did the change.

Maybe try uninstalling (and purging to remove the extra scraps) all of Yaru-Cinnamon, Including the ubuntucinnamon-environment because I believe that's a dependency, then reinstall all of it. Do it in a terminal in another DE so you don't break anything. Keep the issue open and let me know if you have any trouble

**Comment by Muqtxdir** [comment]
Hi @arjanvaneerden 

Thanks for taking your time and reporting the issue faced by you and as mentioned by @Jupi007  `yaru-cinnamon-theme-icon` is not part of `yaru-theme` packaging.

Please try to raise the issues related to `yaru-cinnamon-theme*` under their Github issue tracker.
