### ISSUE TITLE
hand2 cursor does not have visible fingers (after becoming black again)

### ISSUE THREAD

**Issue by juujuujj** [ubuntu/yaru#3159]
This was the thing that yoinked me out of having a good experience using Yaru cursors separately with black hands. If possible, revert the hands to the white state and swap the outline and fill colors for a quick resolve and rebuild the cursors into bitmaps.

**Comment by Muqtxdir** [comment]
Hi @juujuujj 

Thanks for taking out time to make a suggestion. Having white hand2 cursor was an inconsistency with the rest of the cursor-set's bitmaps, for which few times issues were opened here on github. I think @Benni3-1415 and @ubuntujaggers were involoved and looked into making it the same colors as pointer.

Also, the fingers are visible at all the sizes. Not sure to what problem you are having in this issue regarding fingers not being visible.
