### ISSUE TITLE
"Software & Updates" and "Software Update" icons are too similar.

### ISSUE THREAD

**Issue by luciotorre** [ubuntu/yaru#3216]
**Expected Behavior**

When trying to open the "Software Updater" app I type "update" in the search bar of gnome shell and icons come up. Ideally it would be easy to identify which icon i should click.

**Actual Behavior**

See attached screenshot. When one searches for "update" two icons appear which not only are very similar (both look like A's) but the clipping of the names makes it impossible to *know* without thinking which one one should click.

There are clues in the icons: the updater has a refresh like circle and the Software & Updates app has something that could be considered a toggle/slider. But this is very cryptic.

I don't know that the solution is a better icon. Maybe the solution also requires changing the names of the apps. Or unifying them. Or whatever. I just wanted to leave this here in case it is useful.

**Software that presents the issue**

"Software Updater" and "Software & Updates"

**Yaru version**

Package: yaru-theme-icon
Version: 21.10.2
Priority: optional
Section: misc
Source: yaru-theme
Origin: Ubuntu
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 117 MB
Homepage: https://community.ubuntu.com/c/desktop/theme-refresh
Task: ubuntu-desktop-minimal, ubuntu-desktop
Download-Size: 19.5 MB

**Screenshots**

![image](https://user-images.githubusercontent.com/469561/141003585-9ac38b72-5c77-4e84-998c-9daf147ce247.png)

**Comment by madsrh** [comment]
Hi @luciotorre 
Thanks for taking the time to report this 🙏 
Sadly, we're well aware of the issue, but haven't come up with a solution. You can read up on earlier ideas in these threads:
https://github.com/ubuntu/yaru/issues/1051
https://github.com/ubuntu/yaru/issues/2292
https://github.com/ubuntu/yaru/issues/1940
https://github.com/ubuntu/yaru/issues/863
https://github.com/ubuntu/yaru/issues/862

Best solution IMHO would be to create just a single application for everything related to updates, but I doubt that will happen.

**Comment by Muqtxdir** [comment]
This was addressed and re-drawn with PR: #3279
