### ISSUE TITLE
Text of selected item is barely visible (only contour)

### ISSUE THREAD

**Issue by fsabin** [ubuntu/yaru#3245]
**Expected Behavior**
Text of selected item is clearly visible

**Actual Behavior**
Text of selected item is barely visible (only contour)

**Steps to Reproduce the Problem**
LibreOffice:
- Open the Open the Styles and Formatting window and select any style
- Open the Set Paragraph Style combo box and select a style
- Open the Font Name combo box and select a font

Eclipse: Select an item from the Package Explorer.

**Software that presents the issue**
OS: Ubuntu 21.10

_LibreOffice, installed from www.libreoffice.org DEB .tar.gz files_
Version: 7.2.3.2 / LibreOffice Community
Build ID: d166454616c1632304285822f9c83ce2e660fd92
CPU threads: 4; OS: Linux 5.13; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Calc: threaded

_Eclipse IDE for Java Developers (includes Incubating components), installed from www.eclipse.org .tar.gz file_
Version: 2021-09 (4.21.0)
Build id: 20210910-1417

**Yaru version**
Package: yaru-theme-gtk
Version: 21.10.2

**Screenshots**
![LibreOffice_7 2 3 2_Style](https://user-images.githubusercontent.com/22217737/144235285-8b4d6f2a-8fbc-4ca3-bb31-47679dc3ff19.png)

![Eclipse_2021-09_Project](https://user-images.githubusercontent.com/22217737/144235432-e202f118-e9a2-483f-946a-9fed5c24f32f.png)

**Upstream check**
Problem does not occur in Adwaita.

**Comment by Jupi007** [comment]
I can confirm the issue.

But it is sadly non-fixable in its current state 😔
Those `treeview` seems hardly overwrite the text color. I tried everything, but it is impossible to redefine it.

The only solution is to remove the grey selected row tweak for `treeview`.
I'll make a PR.

**Comment by fsabin** [comment]
Hi @Jupi007,
your fast and prompt response is appreciated. Did you check also the Font Name and Set Paragraph Style combo box elements in LibreOffice? Do they also use a tree view?

**Comment by Jupi007** [comment]
You're welcome :)

Yes, it also fixes Font and Paragraph combos which are all using `treeview`.
