### ISSUE TITLE
Check box checked state barely visible

### ISSUE THREAD

**Issue by fsabin** [ubuntu/yaru#3254]
**Expected Behavior**
Check box checked state is clearly visible

**Actual Behavior**
Check box checked state barely visible

**Steps to Reproduce the Problem**
Start a freshly installed Google Chrome. The issue can be observed in the "Welcome to Google Chrome" dialog.
Delete ~/.cache/google-chrome and ~/.config/google-chrome to simulate a fresh install.

**Software that presents the issue**
OS: Ubuntu 21.10

Google Chrome, installed from https://www.google.com/chrome DEB file
Version 96.0.4664.45 (Official Build) (64-bit)

**Yaru version**
Package: yaru-theme-gtk
Version: 21.10.2

**Screenshots**
Ubuntu 21.10
![Screenshot from 2021-12-06 18-18-57](https://user-images.githubusercontent.com/22217737/144986693-2212cc34-7552-4bc6-bf63-e6273a205122.png)

Ubuntu 20.04.3
![Screenshot from 2021-12-06 17-07-24](https://user-images.githubusercontent.com/22217737/144986659-62d52d47-8ef1-451c-bb9f-2abc9cd52bd5.png)

**Upstream check**
Problem does not occur in Adwaita.

**Comment by Jupi007** [comment]
Hi @fsabin,
thanks for the report.

I can reproduce the bug but before #3247.
It looks that this PR solved the problem.

Screenshot using `master` on Ubuntu 21.04:

![Capture d’écran du 2021-12-07 10-24-57](https://user-images.githubusercontent.com/36476595/145002442-4a98f592-5220-47e0-845e-47a50a25e071.png)

**Comment by Jupi007** [comment]
Closed by #3247
