### ISSUE TITLE
Missing Sim icon (Phosh)

### ISSUE THREAD

**Issue by giovannicaligaris** [ubuntu/yaru#3257]
I have compiled the latest master and the SIM icon is not rendering correctly. it shows a square instead. Please check the images for Yaru and Adwaita.

<img src="https://user-images.githubusercontent.com/26255347/145443189-8b5334f6-a6ba-4cc2-9046-f30e6e6a2767.png" width=35% height=35%> <img src="https://user-images.githubusercontent.com/26255347/145443244-15704834-5323-4ade-9fdd-4a5486b8830b.png" width=35% height=35%>

<img src="https://user-images.githubusercontent.com/26255347/145443751-b094cf94-37e0-4e58-92a0-c1acd2b969f2.png" width=35% height=35%> <img src="https://user-images.githubusercontent.com/26255347/145443813-df3a18fc-fac6-4e3c-9864-14d23cecde27.png" width=35% height=35%>

**Comment by Muqtxdir** [comment]
Hi @giovannicaligaris 

Thanks for taking the time to report this issue. I'll look into this one.

**Comment by Jupi007** [comment]
Hi @giovannicaligaris
How can we reproduce this view?

**Comment by Muqtxdir** [comment]
> How can we reproduce this view?

from what i found, you can install phosh on ubuntu-21.10 with `sudo apt install phosh`  (_you should probably try phosh session in vm_)
