### ISSUE TITLE
Dark mode splash (Phosh)

### ISSUE THREAD

**Issue by giovannicaligaris** [ubuntu/yaru#3261]
When using the Yaru-dark theme the Splash on Phosh should be black, instead it defaults to white.

The white image is using Yaru-dark and the black one Adwaita Dark.

<img src="https://user-images.githubusercontent.com/26255347/145571629-be023b0b-b538-4256-b2d3-a47a44b16fd8.png" width=35% height=35%> <img src="https://user-images.githubusercontent.com/26255347/145571637-61b21a6b-9551-432e-b1d7-693f4234f9e6.png" width=35% height=35%>

**Comment by Muqtxdir** [comment]
i think for splash to be displayed correctly/properly, yaru would need to include phosh's-stylesheets using [`phosh's-stylesheets (adwaita)`](https://gitlab.gnome.org/World/Phosh/phosh/-/tree/main/src/stylesheet) as reference.

However I don't think phosh allows you to change it's shell-theme like GNOME-Shell allows you to change it (_via user-theme extension_).

**Comment by giovannicaligaris** [comment]
@Muqtxdir as far as I know, Phosh does not support user-themes. Just GTK themes and Icons

**Comment by Muqtxdir** [comment]
ok, @Jupi007 could you look into adding the phosh stylesheets into gtk3 build-process?

**Comment by giovannicaligaris** [comment]
Sorry to be annoying, but any progress on this?

**Comment by Jupi007** [comment]
Sorry, I totally forgotten this.
I'll do it very soon :)

**Comment by Jupi007** [comment]
Closing this because not fixable (see https://github.com/ubuntu/yaru/pull/3308#issuecomment-1013694160).

**Comment by elagost** [comment]
@giovannicaligaris mind if I ask how you got phosh to use dark splash screens at all? This seems to be the only evidence I've found of someone successfully doing this. Have you modified it yourself or set some gsetting or something?
