### ISSUE TITLE
Push to Debian

### ISSUE THREAD

**Issue by giovannicaligaris** [ubuntu/yaru#3270]
Now that most of the icons and stylesheet have been fixed for Phosh, is it possible to push it Debian Bookworm (Arm) so other Mobian users can install it?

**Comment by Jupi007** [comment]
I did take the time to import Phosh styling yet.
But I'll do it very soon if I found the time.

**Comment by Muqtxdir** [comment]
Hi @giovannicaligaris 

The debian-packaging is handled by folks from ubuntu-desktop and is done on launchpad. If anyone is interested into getting this as debian-package under debian repositories, they are more than welcome to volunteer for handling the packaging if we are made aware of the publishing of package.

Thanks!
