### ISSUE TITLE
Rework Software & Updates icon

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#3279]
![grafik](https://user-images.githubusercontent.com/15329494/147225520-fbaa12bb-e451-4014-a6ef-6a8965f78f40.png)

With the switch to orange the strong purple on the baseplate does not fit anymore.
However as discussed in https://github.com/ubuntu/yaru/pull/3265#issuecomment-993967478
and due to various feedback from users how indistinguishable the two icons are a rework would be nice. Eventually step away from the A-metaphor for this icon completely. 

Note: we discussed this several times and thought that the "great rework" of gnome software and how ubuntu manages its updates would come "soon" so this app would basically be included elsewhere. Since this never happened and eventually never will we need this rework.

**Comment by ubuntujaggers** [comment]
How about something like...

![image](https://user-images.githubusercontent.com/38893390/147247735-ec7e94c2-08c5-4d78-a94e-2470c010949b.png)

**Comment by Jupi007** [comment]
Very nice icon :+1:

**Comment by Feichtmeier** [comment]
Thank you for your time looks nice! Blue is fresh 
If we keep the A, could you increase the contrast between the baseplate and the A a bit? It currently looks a little bit like it is merging with the background

**Comment by ubuntujaggers** [comment]
![image](https://user-images.githubusercontent.com/38893390/147251244-1eb9ca2c-7270-4b1d-a989-ce8eb0404258.png)

??

**Comment by ubuntujaggers** [comment]
Also possibly helps with background/foreground if we remove the middle bits from the cog:

![image](https://user-images.githubusercontent.com/38893390/147252032-ebe6509e-e399-4283-aa36-c9e71d811eb9.png)

**Comment by Feichtmeier** [comment]
Really cool 👏 👍 I would love to go with this :)
