### ISSUE TITLE
Missing Icon: Keyboard Layout

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#3284]
When you click on 

![grafik](https://user-images.githubusercontent.com/15329494/147833345-62796623-3cba-4dfd-bd2c-7d0b6deeb9a7.png)
(sorry for german)

This window pops up with an icon in the dock which we do not have and is replaced with a generic keyboard symbolic icon
![Bildschirmfoto von 2021-12-31 17-59-09](https://user-images.githubusercontent.com/15329494/147833316-50ac48de-f6bc-49fb-9e70-e30f0d2f58e1.png)

In comparison here is the full color papirus icon
![Bildschirmfoto von 2021-12-31 17-58-56](https://user-images.githubusercontent.com/15329494/147833314-d865413f-e326-4397-acb0-07abb583748b.png)

**Comment by Jupi007** [comment]
I'll take a look at this.
