### ISSUE TITLE
Add exit, restart, shutdown and recent files icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3288]
Don't fear the exit, restart, shutdown and recent files folder icon. On Humanity's icons there are these colored icons and on Yaru the exit, restart and shutdown icons are only symbolic and the recent file folder icons don't.
![Captura de tela de 2022-01-03 20-34-36](https://user-images.githubusercontent.com/59381215/147999961-339fef99-91ba-41cc-a449-da9750077304.png)
I know that the focus of the project is for GNOME, but in MATE they are well sampled.

**Comment by ItzSwirlz** [comment]
Yeah. Can confirm cinnamon needs this. Those were the extra icons I was talking about in the Cinnamon PR
