### ISSUE TITLE
Add instructions how to build the .deb files into contributing.md

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#3321]
Apart from the manual build dependencies, `debhelper` and  `dh-migrations` seem to be needed to build the debian files.
@Muqtxdir told me that `sudo dpkg-buildpackage -b -uc -us` builds the debian files, however they were inaccessible for my current user (locked symbol) and were put outside of the yaru dir. Also 1k+ files were added to the git repo.
I've ran the command from the yaru dir root folder. But I guess this was wrong?

@Muqtxdir could you add instructions into contributing.md how to build the debian files? Thanks in advance

**Comment by Muqtxdir** [comment]
closed with: #3322
