### ISSUE TITLE
Shell popovers row MainAxisAligment

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#3334]
![grafik](https://user-images.githubusercontent.com/15329494/151552328-59f937a4-eef4-4975-ae90-09aaa5cf91a9.png)

The switch and the label are not on the same line :)

GNOME Shell 40.5
yaru theme from master :)

**Comment by Feichtmeier** [comment]
It's a known upstream issue (some of th ebullet points)
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4969
So we could just close it here and wait until it drops on the PRs?

**Comment by Jupi007** [comment]
I agree :+1:
