### ISSUE TITLE
Make icons for 3d model types and G-Code

### ISSUE THREAD

**Issue by ShadowOfPripyat** [ubuntu/yaru#3335]
**Icon Request**

I would like to have icons for 3D models like .stl or .obj since i use the Raspberry Pi for printing. Also for Ultimaker Cura Software because is very used in the 3D printing world.

**Software where the icon is missing**

- Name: Nautilus
- Version: 3.36.3
- OS version: Ubuntu 20.04.3

**Screenshots**

*Cura logo*
![image](https://user-images.githubusercontent.com/73404930/151654367-7231cdaa-bc46-4bd8-9a6f-aff43da71b70.png)

*G-Code and STL Examples*
![image](https://user-images.githubusercontent.com/73404930/151654438-6438b3e5-d35d-4ca8-b04a-a06ad35f1b65.png)

**Thanks a lot, i love Yaru icons** :D

**Comment by Jupi007** [comment]
Closed by  #3388
