### ISSUE TITLE
appearance: add accent colors for yaru-variants

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#3348]
hi,

In last week's [Indaba (`28 jan 2022`)](https://discourse.ubuntu.com/t/ubuntu-desktop-team-indaba-ama-january-28-2022-6pm-utc/26095) about themeing, @hellsworth made a suggestion to @Jupi007 that it would be nice to have an option to seamlessly switch between different accent-colors  from the `gnome-control-center` similar to how it is offered in **_elementaryOS6._** 

below is a showcase of an implementation for the above suggestion with **7** more colors to `gnome-control-center` - > `Appearance` panel.  Since [`ubuntu-22.04 won't ship with GTK-4/libadwaita based apps`](https://discourse.ubuntu.com/t/ubuntu-desktop-gnome-plans-for-the-incoming-lts/26156) I asked in the telegram group about having something like this for **ubuntu 22.04** and @elioqoshi suggested opening an issue for having a better discussion with others regarding whether to **_implement_** this or not?

#### accent-colors:
Ubuntu Orange: `#E95420` (_default_)
Aqua Blue: `#18b0b0`
Adwaita Blue: `#3584e4`
Leaf Green: `#0e8420`
Fuchsia Pink: `#c748ba`
Ubuntu Aubergine: `#77216f`
Crimson Red: `#c7162b`
Sunny Yellow: `#f4a100`

#### screenshot:
![Screenshot from 2022-02-05 16-46-50](https://user-images.githubusercontent.com/54065734/152639848-f137778c-1742-42d6-ad1c-a2c807df4075.png)

_edit: removed older screen-recording and added accent-colors list_ 
 cc: @kenvandine

**Comment by ItzSwirlz** [comment]
This would simplify things for all flavors; as long as accent colors for each flavor are made, one global yaru package would work

**Comment by hellsworth** [comment]
@seb128 @3v1n0 might have some thoughts about this :)

**Comment by elioqoshi** [comment]
@waynecrosby your input might be needed here as well.

My 2 cents: Great improvement I think many users will appreciate! I do think the default brand colors could be distinguished so they don't look like random accent colors but I am not sure what the best solution for that would be.

**Comment by 3v1n0** [comment]
I'd be ok with such solution! it's not far from what elementary is doing and to what upstream will probably ship.

I think it's still a good way to give users the ability to have some theme customization while preserving the main ubuntu/yaru aspects, so I'd be happy to review the code for this! :)

Not sure if @seb128 or @kenvandine have different opinions though.

**Comment by 3v1n0** [comment]
I'd be ok with such solution! it's not far from what elementary is doing and to what upstream will probably ship.

I think it's still a good way to give users the ability to have some theme customization while preserving the main ubuntu/yaru aspects, so I'd be happy to review the code for this! :)

Not sure if @seb128 or @kenvandine have different opinions though.

**Comment by seb128** [comment]
Sounds nice, +1 from me

**Comment by Feichtmeier** [comment]
Big fan ofc, too!

I agree with @elioqoshi , if we do not have a fully free colors slider like in windows, I would also use our/canonical/ubuntus main colors 

`#924D8B`
`#77216F`
`#C7162B`
`#E95420`
`#f99b11`
`#0e8420`
`#335280`

But probably we need to adjust some of them with lighten/darken to guarentee a good contrast in both light/dark themes

**Comment by Muqtxdir** [comment]
> I'd be ok with such solution! it's not far from what elementary is doing and to what upstream will probably ship.

> I think it's still a good way to give users the ability to have some theme customization while preserving the main ubuntu/yaru aspects, so I'd be happy to review the code for this! :)

> Sounds nice, +1 from me



Thanks for the @3v1n0 and @seb128  for the reply, should I do MR against the same `ubuntu-panel` branch? or should I wait until `ubuntu-41/42` branch lands on gitlab ?

> Big fan ofc, too!
I agree with @elioqoshi , if we do not have a fully free colors slider like in windows, I would also use our/canonical/ubuntus main colors agree with @elioqoshi , if we do not have a fully free colors slider like in windows, I would also use our/canonical/ubuntus main colors

I think It'd be better to maybe drift away a bit from this palette and include colors such as pink, slate, mint and relook at colors such as blue, green, red, yellow and purple as they personally look a bit dull and sometimes not that appealing.

**Comment by 3v1n0** [comment]
@Muqtxdir I've synchronized the ubuntu panel with what's currently in ubuntu few days ago, so that should be a good target.

I think you can already go, given that this will apply to the `ubuntu-panel` only that is quite independent from the rest. Also we won't take the 42 version (as it's going [gtk4](https://discourse.ubuntu.com/t/ubuntu-desktop-gnome-plans-for-the-incoming-lts/)).

**Comment by Muqtxdir** [comment]
ok, thanks for clarifying it

**Comment by Scotty-Trees** [comment]
@Muqtxdir Will this also add a different accent color to the gnome-shell theme aspect as well or will that always remain the same?

**Comment by waynecrosby** [comment]
@Muqtxdir @elioqoshi I think it looks great! The brand colours could do with being distinguished a bit more that the others I agree, I'll schedule some time to look at the colours. Are we thinking 8 is the ideal number of colour choices?

**Comment by Muqtxdir** [comment]
> @Muqtxdir Will this also add a different accent color to the gnome-shell theme aspect as well or will that always remain the same?
 
yes, but this would require few adjustments to the `gnome-shell` meson build part to account for flavour/variants as @clobrano mentioned that it currently doesn't do that and also add a yaru-patch to GNOME-Shell to respect Yaru's `gtk-theme` values

**Comment by 3v1n0** [comment]
I can handle the shell part if you want.

Il gio 3 feb 2022, 19:20 Muqtadir ***@***.***> ha scritto:

**Comment by Jupi007** [comment]
Yeah, the GS build system need to be reworked.
It should fit the way we do with `gtk`: each flavour in its folder, and a system of symlink.

**Comment by Muqtxdir** [comment]
> @Muqtxdir @elioqoshi I think it looks great! The brand colours could do with being distinguished a bit more that the others I agree, I'll schedule some time to look at the colours. Are we thinking 8 is the ideal number of colour choices?

hi @waynecrosby 

I think having 8 colors (_those being: Aqua, Blue, Green, Orange(default), Purple, Pink, Red and Yellow_) seems like a perfect balance.

**Comment by rafaelmartines** [comment]
Well if this merges to master branch and releases with 22.04, time to back to Ubuntu.

**Comment by elioqoshi** [comment]
I want to row back on this one quickly as I didn't realize what the impact of this will be upstream. I was under the impression this would be already available in some manner in GNOME, which is not the case. I really don't want us to do more changes downstream which app developers have to consider beyond what's available in GNOME. We should take into account how this affects the whole GNOME ecosystem instead of Ubuntu on its own. Do we have some upstream discussions about accent colors in GNOME we could contribute to? I don't want us to do things one way where app developers have to take into account Ubuntu special differences beyond GNOME.

**Comment by geminis3** [comment]
Awesome, +1 for accent colors

**Comment by Feichtmeier** [comment]
> I want to row back on this one quickly as I didn't realize what the impact of this will be upstream. I was under the impression this would be already available in some manner in GNOME, which is not the case. I really don't want us to do more changes downstream which app developers have to consider beyond what's available in GNOME. We should take into account how this affects the whole GNOME ecosystem instead of Ubuntu on its own. Do we have some upstream discussions about accent colors in GNOME we could contribute to? I don't want us to do things one way where app developers have to take into account Ubuntu special differences beyond GNOME.

I think there is a bit more information to be clarified.
First of all the recolouring API is not yet done upstream in libadwaita.
Secondly 22.04 won't ship with libadwaita because the level of polish and testing isn't reached yet. So what those colours mean is just a set of yaru themes for gtk3 with a predefined color. So instead of two Yaru themes (light/dark) there would be 16 Yaru themes (2*8). So this should really be not be working against anything upstream. As far as I've understood the Ubuntu desktop engineers correctly, as soon as the recolouring API lands in libadwaita and it's mature enough we will switch the Ubuntu themes to Adwaita but with using the recolouring API to provide adwaita with Ubuntu accent(s).

**Comment by elioqoshi** [comment]
I am not comfortable with that. It doesn't change much from the current Yaru behaviour but it creates expectations for app developers that this is a platform feature on GTK which every app should support while it's not a GTK thing. Having 8 colors mean that app developers would need to test their apps with 8 new combinations while I don't think this is responsible from us to expect that.

**Comment by neffscape** [comment]
This might be the best feature for 22.04. +1 for accent colors, but please stick to the ubuntu palette (or ubuntu flavour colors).

**Comment by zara1193** [comment]
> This might be the best feature for 22.04. +1 for accent colors, but please stick to the ubuntu palette (or ubuntu flavour colors).

+1 for this. The accent selector is a wonderful idea, but I'd really like to see, for example, the Ubuntu aubergine color (even though the lavender already included in the proposal screenshot looks good too.)

**Comment by kenvandine** [comment]
> I am not comfortable with that. It doesn't change much from the current Yaru behavior but it creates expectations for app developers that this is a platform feature on GTK which every app should support while it's not a GTK thing. Having 8 colors mean that app developers would need to test their apps with 8 new combinations while I don't think this is responsible from us to expect that.

After a great deal of thought on this, I disagree.  In a GTK3 world, app developers already have to deal with users with a thousand different themes, most of which are much lower quality than Yaru and Adwaita.  Added accent color selection to Yaru doesn't really change much from the app developer's point of view.  This also wouldn't affect apps that have opted into libadwaita.  Overall I think this will enhance the experience for 22.04 users, which are primarily using GTK3 apps.  I'd also hope that with the ability to customize the accent color for yaru, fewer users would choose to switch to other GTK themes that receive little to no testing.

I'd be in favor of shipping this in 22.04 and plan on collaborating with GNOME on a long term solution for 22.10 and beyond.

**Comment by Muqtxdir** [comment]
@3v1n0 I created MR on gitlab for `gnome-control-center`, please have a look at it :)

### screenshot:
| current: 22.04 LTS | MR for 22.04 LTS |
 | ------------- | ------------- |
| ![before2](https://user-images.githubusercontent.com/54065734/153202697-fc0d96f0-f20f-4289-af12-4c4927d7e5b8.png)  |  ![after](https://user-images.githubusercontent.com/54065734/153202794-1c3f4a54-df2a-42bf-a761-0acb46c7f5c3.png) |

**Comment by seb128** [comment]
reference the previous mentioned mp, https://gitlab.gnome.org/Community/Ubuntu/gnome-control-center/-/merge_requests/7

**Comment by BrainBlasted** [comment]
This is my perspective as an upstream contributor, but I would like to ask that you hold off for the reasons @elioqoshi mentioned. I plan to work on opt-in accent color support upstream, and:

* App developers targeting GNOME would be able to opt in
* I plan to submit it as part of xdg-desktop-portal, like the new dark style support. Applications from other desktops would then be able to support it, e.g. KDE applications or cross-platform applications.
* It will not require separate theme variants

There are discussions to be had with the design team about this of course, but in the meantime I think this will cause confusion. When downstreams make changes that aren't supported by upstream tooling and libraries, independent app developers get reports from confused users asking us why things are broken, or negative reviews on our apps. If you can wait a bit longer, I think we can get a solution that works for everyone in a cross-desktop way.

**Comment by neffscape** [comment]
I support the idea to implement this upstream for a future GNOME version
(hopefully 43). However 22.04 will still live in a GTk3 world, and being an
LTS, this version it's going to be around for several years. For this
reason I think this MR should be accepted anyway: it's a nice idea, it
works now and will make 22.04 a much more interesting release (and it's
going to age better in a world where future releases of GNOME will support
accent colors). Other platform such as Elementary already have accents
colors and developers are not complaining that much. So, please, don't
refuse this MR because a better version will come out in the future.


Il giorno mer 9 feb 2022 alle ore 22:35 Chris ***@***.***> ha
scritto:

**Comment by BrainBlasted** [comment]
> Other platform such as Elementary already have accents colors and developers are not complaining that much.

This is because of two things:

* The elementary AppCenter is curated, and users know that apps from outside of it may not support system themes and APIs. That expectation is built into the platform.

* App developers targeting elementary know that it's something they can support, but they also have the ability to opt out and use their own accent colors. That way if they want to support it, they know to test it and can do so easily. If they don't, they can simply test with their chosen accent color.

**Comment by kenvandine** [comment]
> There are discussions to be had with the design team about this of course, but in the meantime I think this will cause confusion. When downstreams make changes that aren't supported by upstream tooling and libraries, independent app developers get reports from confused users asking us why things are broken, or negative reviews on our apps. If you can wait a bit longer, I think we can get a solution that works for everyone in a cross-desktop way.

App developers using GTK3 aren't testing their apps against all the possible themes today, there are thousands of themes and users really do use them.  The app developer doesn't have any control over that in a gtk3 world.  There are users using Chicago95, we can't protect them from their own choices.  I agree going beyond the world of wild wild west themeing, we can certainly do much better, but this is the state of things right now and will be when we release 22.04.  I'd rather give users a feature they will love for the life of 22.04, which won't have any gtk4 apps by default.  I'd hope giving users a nice way to tweak just the accent colors, but sticking with Yaru they will have a much cleaner experience and not choose to install themes that aren't nearly as well supported.  

We will certainly look forward to collaborating on the longer term solution.

**Comment by aedelred** [comment]
Please do make this change. I feel that choice of light/dark and accent color should be standard on any user interface.

**Comment by Jupi007** [comment]
> Note 3: Should we have a gray version? Feels like one of the purples can be replaced with gray, as they appear very close to one another.

Grey is very problematic with Gtk3 (see #3245 for ex.).
I would prefer to doesn't ship it as accent.

**Comment by ItzSwirlz** [comment]
> > Note 3: Should we have a gray version? Feels like one of the purples can be replaced with gray, as they appear very close to one another.
> 
> Grey is very problematic with Gtk3 (see #3245 for ex.). I would prefer to doesn't ship it as accent.

Eventually we may want to bounce back to it as Budgie is gray (or we could go with a white I suppose)

**Comment by 3v1n0** [comment]
Thanks @lyubomir-popov for the analysis.

There are good options in your proposal, however I wonder if we can provide some more vivid colors, especially when it comes to green, purple and red (that currently we don't have anymore).

I definitely understand that the contrast on some background colors is hard to achieve.
At the same time I think that we can accept some lower contrast ratio, if we can provide some colors which try to stay closer to the yaru palette.

For example, using the colors that @elioqoshi proposed, I notice that we can have some good contrast (at least to my eyes, not sure if more scientific tools say something different) even keeping a _stronger_ green, red or aubergine:

![image](https://user-images.githubusercontent.com/345675/158293436-5d91115b-8b26-4fb6-bff4-398c613d52a8.png)
![image](https://user-images.githubusercontent.com/345675/158293464-116400d5-9f25-4874-baa3-efe0915a7744.png)
![image](https://user-images.githubusercontent.com/345675/158293490-debb0969-0cc5-4244-b8c2-f117afe968b9.png)

while I do agree that achieving a proper "yellow" is probably impossible.

Anyways, regarding the white on colored bg, not sure if tuning `$accent_fg_color` (or actually `$selected_fg_color`) could bring some better results, without sacrificing the accent color selection.

> Note 3: Should we have a gray version?

Usage of gray may also lead to problems when it comes to backdrop or disabled states, where we already used the gray for such cases. So I feel it may lead to some misunderstandings.

**Comment by varlesh** [comment]
What a wonderful method to nail Yaru and deprive users of other icon themes. Well done Ubuntu! Freedom of choice in all its glory...

**Comment by Feichtmeier** [comment]
> What a wonderful method to nail Yaru and deprive users of other icon themes. Well done Ubuntu! Freedom of choice in all its glory...

Drama aside, you can log into the gnome session where those things shouldn't happen

**Comment by sato96** [comment]
> @Jupi007 noted about the grey. I've included one muted colour, a low saturation beige, as I recall someone requesting a less energetic accent colour in one of the many issues on this subject.
> 
> @3v1n0 I just pushed an updated palette. PR [here](https://github.com/ubuntu/yaru/pull/3486)
> 
> > I wonder if we can provide some more vivid colors, especially when it comes to green, purple and red (that currently we don't have anymore
> 
> I've adjusted some of the colours to be more vivid while still within the required contrast ratios, including 2 greens, the purples, and a red:
> 
> ![image](https://user-images.githubusercontent.com/2741678/158431020-e1097582-ef78-4da0-b1b5-1a4e672d1c74.png)
> 
> (Is anyone realistically going to use the red? I have doubts)
> 
> > I think that we can accept some lower contrast ratio, if we can provide some colors which try to stay closer to the yaru palette
> 
> Accessibility requirements are far too often considered optional. They are there for good reason, and we should endeavor to work within the contrast ratios requirements.
> 
> Below a list of screenshots of all proposed colours in both the light and the dark themes: One thing concerns me - the default orange highlight applies very sparingly, e.g. not in tree views, file selector, the settings side bar etc. The new accent colours apply everywhere, which feels inconsistent.
> 
> ![image](https://user-images.githubusercontent.com/2741678/158425847-a237a0f9-bc6b-4765-b9d5-5f8715de295a.png) ![image](https://user-images.githubusercontent.com/2741678/158425896-1b244e42-598e-4adc-8a0a-2ba9d9e0a7c8.png) ![image](https://user-images.githubusercontent.com/2741678/158425921-373daf21-766f-4f70-a296-2293e09ddeb8.png) ![image](https://user-images.githubusercontent.com/2741678/158425953-2ad55fbe-cd3b-4706-aeee-3cee2d78edba.png) ![image](https://user-images.githubusercontent.com/2741678/158425982-b27c1600-1c5f-45a3-9e7b-12360191fd2d.png) ![image](https://user-images.githubusercontent.com/2741678/158426021-121ff4cd-9f49-47ad-aa77-e4418f313a9b.png) ![image](https://user-images.githubusercontent.com/2741678/158426044-a8e78692-4cd6-40e6-b66b-22d4a4c1119e.png) ![image](https://user-images.githubusercontent.com/2741678/158426073-c9a0d6c6-e1b1-4b8a-b7c2-8ae6d7d705fd.png) ![image](https://user-images.githubusercontent.com/2741678/158426105-30126b9d-94f7-418e-851a-e1b26bc2fb63.png) ![image](https://user-images.githubusercontent.com/2741678/158426140-4ef05612-3914-491b-b443-6133e85ac8fb.png) ![image](https://user-images.githubusercontent.com/2741678/158426164-5f2a939c-757e-49b5-baf0-2601023266dd.png) ![image](https://user-images.githubusercontent.com/2741678/158426191-e29e056d-211c-42c6-806d-584972aadcae.png) ![image](https://user-images.githubusercontent.com/2741678/158426213-adb7f872-69d0-488e-a2f5-50f3e3e532c2.png) ![image](https://user-images.githubusercontent.com/2741678/158426245-70d0b241-76d9-4ff3-8a16-c42de8a81a43.png)

Hi, looking at your screenshots i notice that you have yellow pallette, while i can't find it in my installation. I have 20.4.4 LTS installed. Can yellow be installed in future release?

**Comment by 3v1n0** [comment]
Yes, yellow has been just been [added](https://github.com/ubuntu/yaru/commit/28d8a64c95493bc1e2a50179f7e1be9f6ef2e2cb).

We won't support it in older releases (< 24.10) though.

**Comment by sato96** [comment]
> Yes, yellow has been just been [added](https://github.com/ubuntu/yaru/commit/28d8a64c95493bc1e2a50179f7e1be9f6ef2e2cb).
> 
> We won't support it in older releases (< 24.10) though.

Ok thank you! :)
