### ISSUE TITLE
Cinnamon theme improvements.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3393]
My suggestion for the cinnamon theme is:

- Menu with rounded corners 7px;

![Captura de tela de 2022-03-08 13-22-02](https://user-images.githubusercontent.com/59381215/157280364-7ab01738-9d83-4ddd-b2ea-c2e0d7358f8b.png)

Example as shown in the image above.

**Comment by Jupi007** [comment]
Hi @Initu-Castilhos,
these are good suggestions, thank you :)

We'll try to implement them.

**Comment by ItzSwirlz** [comment]
By the way, cinnamon should not be cinnamon-shell as I don't think that's how its referred to, but whatever you guys want
