### ISSUE TITLE
[gnome shell 42] Nautilus pathbar does not look good

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#3414]
[Ubuntu Jammy dev with latest proposed GS42+Mutter+Yaru updates]

Hi all,

I know it's quite early in Ubuntu's GS42 lifetime but anyway:
![image](https://user-images.githubusercontent.com/23138504/155691855-42eca7a3-5e98-44ff-8b54-0cd36177f0fd.png)

Adwaita's:
![image](https://user-images.githubusercontent.com/23138504/155692033-a915b52a-0d40-4b8e-a581-75607bfc8f2f.png)

I'm not using Yaru shell theme here.

**Comment by Jupi007** [comment]
Hi @fthx 
thanks for the report, we are working on here #3405

**Comment by Jupi007** [comment]
Closed by #3405
