### ISSUE TITLE
No coloring for gedit pach mode with yaru scheme

### ISSUE THREAD

**Issue by seb128** [ubuntu/yaru#3419]
Using yaru-themes 21.10.2 on Ubuntu, if you select the yaru color scheme in gedit and open a .patch the removed and added lines aren't colored which makes it quite difficult to read compared to classic color scheme

![yarupatch](https://user-images.githubusercontent.com/10974330/155751665-8f3e57dc-ff01-481f-b440-f6b93c7a0147.png)

**Comment by Muqtxdir** [comment]
hi @seb128 

does this look better compared to the one we have in 21.10?

| ubuntu-21.10 | proposed  |
| ------------------ | ------------- |
| ![beforre](https://user-images.githubusercontent.com/54065734/156143981-f467f773-8c9c-447c-909c-0b0de4ed4312.png) | ![new](https://user-images.githubusercontent.com/54065734/156144071-c25a8bcf-c0ae-403e-91db-26dc6fd53da6.png) |

**Comment by seb128** [comment]
Yes, much better, the coloring makes it obvious which lines are removed or added in the change

**Comment by Muqtxdir** [comment]
ok, I'll finish up with the dark-variant and I'll make PR then :)
