### ISSUE TITLE
Update cinnamon theme thumbnail.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3454]
Here are the updated thumbnails for cinnamon, just download the images.

![Yaru](https://user-images.githubusercontent.com/59381215/156944939-19e0f716-71d6-4398-9043-441fc92fd216.png)
![Yaru-dark](https://user-images.githubusercontent.com/59381215/156944952-cb599b48-d77d-4325-afcf-c8923bd00760.png)
![Yaru-Cinnamon](https://user-images.githubusercontent.com/59381215/156944961-9e197d4d-f326-4530-ab84-385ee2a66220.png)
![Yaru-Cinnamon-dark](https://user-images.githubusercontent.com/59381215/156944968-9f6f868e-6578-4cc2-8d76-62f934df445b.png)

**Comment by Jupi007** [comment]
Thanks a lot for the pics @Initu-Castilhos 
I'll make a PR to integrate them.
