### ISSUE TITLE
Add thumbnail in gtk theme.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3455]
Here is the thumbnail for the gtk-3 theme, just download the images.

![control](https://user-images.githubusercontent.com/59381215/156946605-06c26ed9-7f4c-48fb-b114-6865ca4de14c.png)
![control-dark](https://user-images.githubusercontent.com/59381215/156946608-3d480dac-1739-4d6b-bc9f-aa08cde74426.png)
![Captura de tela de 2022-03-06 20-27-29](https://user-images.githubusercontent.com/59381215/156946974-6edaeede-88ce-4882-b5ff-724ac8bb7e2c.png)
![Captura de tela de 2022-03-06 20-27-52](https://user-images.githubusercontent.com/59381215/156946978-31fb1395-4f97-40af-ab1e-d545a5efa77c.png)
Example as shown in the image above.

**Comment by Muqtxdir** [comment]
Hi @Initu-Castilhos,

what is the need for a screenshot? There's already relevant thumbnails provided in ubuntu's `gnome-control-center` appearance panel.

**Comment by Jupi007** [comment]
We miss the thumbnails for this:

![Capture d’écran du 2022-03-04 12-09-49](https://user-images.githubusercontent.com/36476595/157000571-6be793e9-875d-4ff2-aac6-f1a50528e8f6.png)

**Comment by Muqtxdir** [comment]
ok, so this all issues are for `cinnamon`. Although I don't think it's a good idea to have linux-mint icon used as application-drawer in screenshot. gives the wrong-idea that the theme will also use the same icon.

**Comment by Jupi007** [comment]
Oh, but I think the two last screenshots are only used to show us how it render with the thumbnails.
We should only add the two first ones.

**Comment by Jupi007** [comment]
Closed by #3459
