### ISSUE TITLE
Add thumbnail in metacity theme.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3456]
![metacity](https://user-images.githubusercontent.com/59381215/156947060-bab1e888-12d0-4e56-9a4d-3fffb1bd7c32.png)
![metacity-dark](https://user-images.githubusercontent.com/59381215/156947066-4202ef03-be61-40fb-82c7-b2ac940a718c.png)
Here are the thumbnails for the metacity theme. Just download the images.

**Comment by Jupi007** [comment]
Closed by #3459
