### ISSUE TITLE
Green battery icon during charge

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#3463]
Hi,

Running Jammy with Adwaita GS theme but Yaru icons.

I get a green battery icon when my laptop is plugged. Is that intended? 
IIRC, we had some such issues in the past with wifi icon.

![image](https://user-images.githubusercontent.com/23138504/157185830-629a230e-1b4b-4015-960c-361cd4b1cd47.png)

Sorry if it's intended or already committed.

**Comment by Muqtxdir** [comment]
Hi @fthx 

This change was made in the PR: #3243 to be in sync with Adwaita's-symbolics. If you are having any issues please share (_I hope it's nothing weird like the wifi icon_)

**Comment by fthx** [comment]
Hi!

Ok, I did not know we put now some color in GS.
:-)
Thanks for pointing this.
