### ISSUE TITLE
Add full icons for cinnamon.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3469]
If it is possible to add icons from cinnamon settings, that currently the icons are legacy as shown in the image below:
![Captura de tela de 2022-03-09 03-23-33](https://user-images.githubusercontent.com/59381215/157384821-17c14f62-6e8b-4ac3-9aaf-48d1fa205a39.png)

for this as shown in the image below:
![Captura de tela de 2022-03-09 03-23-50](https://user-images.githubusercontent.com/59381215/157384964-4f9ae889-24de-4154-9b16-626848cd27d1.png)
It has 50% of Yaru ready icons that can be used.

### Icon list:

- [ ]  cs-applets
- [ ]  cs-backgrounds
- [ ]  cs-blueman
- [ ]  cs-cat-admin
- [ ]  cs-cat-appearance
- [ ]  cs-cat-hardware
- [ ]  cs-prefs
- [ ]  cs-color
- [ ]  cs-date
- [ ]  cs-default-applications
- [ ]  cs-desklets
- [ ]  cs-desktop
- [ ]  cs-desktop-effects
- [ ]  cs-details
- [ ]  cs-display
- [ ]  cs-drivers
- [ ]  cs-extensions
- [ ]  cs-firewall
- [ ]  cs-fonts
- [ ]  cs-general
- [ ]  cs-input-method
- [ ]  cs-keyboard
- [ ]  cs-language
- [ ]  cs-login
- [ ]  cs-mouse
- [ ]  cs-network
- [ ]  cs-notifications
- [ ]  cs-online-accounts
- [ ]  cs-overview
- [ ]  cs-panel
- [ ]  cs-power
- [ ]  cs-printer
- [ ]  cs-privacy
- [ ]  cs-region
- [ ]  cs-screen
- [ ]  cs-screensaver
- [ ]  cs-sound
- [ ]  cs-sources
- [ ]  cs-startup-programs
- [ ]  cs-tablets
- [ ]  cs-themes
- [ ]  cs-tiling
- [ ]  cs-universal-access
- [ ]  cs-user
- [ ]  cs-windows
- [ ]  cs-workspaces
- [ ]  input-method

**Comment by ItzSwirlz** [comment]
Some icons can be recycled but yes, new icons would be needed for Cinnamon and to work with other DE's later down the road

**Comment by Muqtxdir** [comment]
> Some icons can be recycled but yes, new icons would be needed for Cinnamon and to work with other DE's later down the road

@ItzSwirlz rather than commenting about the scope/direction of icons if you are not contributing towards it, please for the hundreth-time in this repo I ask you to share the list of these fullcolor-icons. Just having a screenshot of missing-icons and not mentioning the related fullcolor-icons names would not help in making any effective progress by any means.

We are all volunteers here who are contributing on our free-time, so much of the time is spent on iterating or adding the new icons instead of wasting time investigating the icon-names that are used. Properly addressing the issue needs is the minimum effort expected from someone who wants to ships a variant of yaru in their distribution.

**Comment by Initu-Castilhos** [comment]
Sorry for the lack of technical information:
follow the list:
- cs-applets
- cs-backgrounds
- cs-bluetooth
- cs-cat-admin
- cs-cat-appearance
- cs-cat-hardware
- cs-prefs
- cs-color
- cs-date
- cs-default-applications
- cs-desklets
- cs-desktop
- cs-desktop-effects
- cs-details
- cs-display
- cs-drivers
- cs-extensions
- cs-firewall
- cs-fonts
- cs-general
- cs-input-method
- cs-keyboard
- cs-language
- cs-login
- cs-mouse
- cs-network
- cs-notifications
- cs-online-accounts
- cs-overview
- cs-panel
- cs-power
- cs-printer
- cs-privacy
- cs-region
- cs-screen
- cs-screensaver
- cs-sound
- cs-sources
- cs-startup-programs
- cs-tablets
- cs-themes
- cs-tiling
- cs-universal-access
- cs-user
- cs-windows
- cs-workspaces
- input-method

**Comment by ItzSwirlz** [comment]
> Sorry for the lack of technical information: follow the list:
> 
> _Moved in first message._

There's more  if you count the settings daemon stuff, but the icons listed in the symlinks work well enough. But I'm not skilled in icon creation, so I can't create these icons.
