### ISSUE TITLE
Wrong background-color in evolution mail view for html mails

### ISSUE THREAD

**Issue by origpumu** [ubuntu/yaru#3485]
**Expected Behavior**

HTML-mails in evolution should shown on white background in mailview also if I have choosen yaru dark in system settings.
Mails without a background color definition should not have a dark background. 

**Actual Behavior**

The text in some html-mails keeps black and the background a dark grey, so the user can't read texts properly.
textmails are shown correctly with light text color on dark background.
This behavior only seems to occur for mails that do not have a background color.

**Steps to Reproduce the Problem**

1. Set dark them in ubuntu preferences
2. open evolution mail
3. try to show a html mail

**System information**

- Shell version: GNOME Shell 41.3
- OS version: Ubuntu Jammy Jellyfish (development branch)
- Evolution version: evolution 3.43.3-1

**Yaru version**

Package: yaru-theme-gnome-shell
Version: 21.10.2

PlainText - Screenshot
![PlainTextMailsExample](https://user-images.githubusercontent.com/1561960/158351071-e4d3c414-810f-47bf-a860-4b49169ca7f3.png)

HTML-Mail Screenshot
![HTMLMailsExample](https://user-images.githubusercontent.com/1561960/158351140-4a8a8753-b8aa-488d-92a0-832f5ed1380c.png)

**Comment by Jupi007** [comment]
Hi @origpumu 
Thanks for the report.

Did you checked using the Adwaita theme?

`gsettings set org.gnome.desktop.interface gtk-theme Adwaita`

Then to revert Yaru-dark: `gsettings set org.gnome.desktop.interface gtk-theme Yaru-dark`

**Comment by origpumu** [comment]
Adwaita theme works as expected with bright background. Adwaita-dark shows the same wrong behavior like yaru-dark.

**Comment by Jupi007** [comment]
Thanks. We are based on Adwaita, so this is not a Yaru bug.
Imo, this is related to the **Evolution** stylesheet itself.

So, please open an issue at **Evolution** repository.
Once done, please also post the link here, so we can follow the discussion.
We could eventually add a temporary patch.

Thanks :)

**Comment by origpumu** [comment]
https://gitlab.gnome.org/GNOME/evolution/-/issues/1835

**Comment by Jupi007** [comment]
@origpumu As I see that the app developers fixed that, can I close this issue?

**Comment by origpumu** [comment]
Fixed in https://gitlab.gnome.org/GNOME/evolution/-/issues/1835
