### ISSUE TITLE
Use new ubuntu logo

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3495]
See: https://ubuntu.com/blog/a-new-look-for-the-circle-of-friends

**Comment by Muqtxdir** [comment]
@Jupi007 i think these two icons are the only ones that should be updated: 
- fullcolor: ubiquity
- scalable: start-here

**Comment by Jupi007** [comment]
Yes, thanks @Muqtxdir :)

**Comment by seb128** [comment]
Hey there, I'm adding the svg for some of the logos, the square version is the one to use for <= 32px according to design, let me know if you need anything else for the yaru update

![Ubuntu_Standard_32px_RGB](https://user-images.githubusercontent.com/10974330/159136434-8800423d-1f6f-466c-bff6-7f4054e14b8d.svg)

![Ubuntu_Standard_128px_RGB](https://user-images.githubusercontent.com/10974330/159136437-2dfbb6d1-d445-40c8-96cb-fcab35dc93e7.svg)

![Ubuntu-logo-2022_RGB](https://user-images.githubusercontent.com/10974330/159136446-da629c1f-56ce-47e1-a909-d237c3bc673b.svg)

**Comment by Jupi007** [comment]
Thanks a lot @seb128 :+1:
