### ISSUE TITLE
Software Center icon should be one colour only

### ISSUE THREAD

**Issue by lekegf** [ubuntu/yaru#3502]
Hi;
I noticed that Software Center icon (Snap Store as some call) now changes its colour according to the new system accent colour.
It doesn't make much sense to me changing its colour, since the chosen accent colour doesn't reflect anything within the interface of the program itself.
Besides, the colour should be universal, so it can be easily recognized in any Ubuntu installation independent of the accent colour defined by the user.
For those reasons, I suggest reverting the Software Center icon to an orange only.

**Comment by Jupi007** [comment]
Hi @lekegf,
thank you to have taking you time to write this issue.

I don't know for the others, but this is not my opinion :)
Imo, having such a large orange like this one when we change the accent color could be sad.
The feature of accented icons is nice and I think it is important to use it everywhere there is orange in an icon.

**Comment by rafaelmartines** [comment]
I disagree, should change the color of the App Center as well, to keep the consistency, otherwise I would remove the App Center icon from dock

**Comment by Muqtxdir** [comment]
I'm neutral on this, either one is fine with me. Since this requires opinion and feedback of others, ping: @ubuntu/yaru-team

**Comment by Feichtmeier** [comment]
I agree with the opening post. I don't think that an orange software centre icon clashs with the other colors. But I don't have a super strong opinion on this and it would probably not really hurt if we take the current approach

**Comment by madsrh** [comment]
I'll have to agree with @lekegf. The orange in the software center icon is not used as an accent color, it's Ubuntu branding, so it makes IMHO sense to keep it orange.

**Comment by rafaelmartines** [comment]
Sad, but since I realized that the name of the Ubuntu Sofware is actually Snap Store and to use flatpaks I need to download Gnome Software, I'll just remove the icon from dock post install 😌
