### ISSUE TITLE
Wrong in right-to-left(RTL) icon

### ISSUE THREAD

**Issue by eshagh79** [ubuntu/yaru#3506]
Hi, I noticed that one of the yaru icons is misspelled.
I saw this error in one of the plugins I use and first checked the plugin and realized that the problem is with the icon. This problem does not exist with other icons set like Adwaita.
The go-last-symbolic-rtl.svg icon has a problem.
https://github.com/ubuntu/yaru/icons/Yaru/scalable/actions/go-last-symbolic-rtl.svg

**Expected Behavior**

I expected the go-last-symbolic-rtl icon to point to the right like the go-last-rtl-symbolic icon.

**Actual Behavior**
The go-last-symbolic-rtl icon points to the left.

**Software that presents the issue**

I saw this problem in the Persian calendar extension
https://github.com/omid/Persian-Calendar-for-Gnome-Shell

**Yaru version**

Version: 21.10.2
on ubuntu 21.10

**Screenshots**
![نماگرفت از 2022-03-19 10-10-03](https://user-images.githubusercontent.com/52137191/159110558-ed28a971-9ef1-4bf8-890a-54b0588b6a3d.png)

**Comment by Jupi007** [comment]
Hi @eshagh79,
thanks for the report.
We'll fix that quickly.
