### ISSUE TITLE
System status change indicators like display brightness or volume are too rounded, with sliders overflowing

### ISSUE THREAD

**Issue by schuelermine** [ubuntu/yaru#3521]
**Expected Behavior**

An aesthetically pleasing volume indicator

**Actual Behavior**

The indicator had way rounded corners and the slider overlapped them.

**Steps to Reproduce the Problem**

**System information**

**Yaru version**

22.04.2

**Screenshots**

![Screenshot from 2022-03-20 13-36-07](https://user-images.githubusercontent.com/48802534/159162657-389c0f61-4a96-45c9-9d03-a171f14d7f28.png)

**Upstream check**

 

It doesn’t happen with Adwaita.

**Comment by Jupi007** [comment]
Hi @schuelermine,
it looks like you aren't using Gnome Shell 42.

This theme is based on the upstream GS42 theme and so is incompatible with any previous versions.

Closing this so.
