### ISSUE TITLE
Dark icon sets are now missing which breaks MATE and Unity panels

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu/yaru#3550]
@3v1n0 Earlier today [support for dark panel icons was added](https://github.com/ubuntu/yaru/pull/3538) to Yaru. Sadly, [this commit](https://github.com/ubuntu/yaru/commit/1d1673e7d86b375f3a254a2c8d22e8ef4312ef06) `-dark` icon sets for accent colors themes are no longer generated, breaking panel icons for MATE and Unity 😭

  * Every accent color variant must have a `-dark` icon set with an `index.theme` **that Inherits from Yark-dark**
  * `Yaru-mate-dark` has also regressed. **It should also inherit from Yark-dark.**

Please re-instate the `-dark` icons `index.theme` for each of the accent colours and MATE along with the appropriate inheritance.

cc: @Jupi007

**Comment by 3v1n0** [comment]
Soo... Isn't this enough?

```diff
diff --git a/icons/meson.build b/icons/meson.build
index 9045a044c..f2d7bcb5e 100644
--- a/icons/meson.build
+++ b/icons/meson.build
@@ -28,13 +65,17 @@ cleanup_rendered_icons_targets = []
 cleanup_rendered_icons_accented_targets = []
 
 foreach flavour: icon_flavors
+  is_dark = flavour == 'dark' or flavour.endswith('-dark')
   is_accent = enabled_accent_colors.contains(flavour)
-  if is_accent and not get_option('gtk')
+  base_flavour = is_dark ? flavour.split('-dark')[0] : flavour
+  is_dark_accent = is_dark and enabled_accent_colors.contains(base_flavour)
+
+  if (is_accent or is_dark_accent) and not get_option('gtk')
     warning('GTK is not enabled, so we won\'t be able to generate accent colors')
     continue
   endif
 
-  if is_accent or get_option(flavour)
+  if (is_accent or is_dark_accent) or get_option(flavour)
     is_flavour = flavour != 'default'
     suffix = is_flavour ? '-@0@'.format(flavour) : ''
     icon_dir = 'Yaru' + suffix
@@ -294,6 +335,20 @@ foreach flavour: icon_flavors
           generate_index_theme_args += ['--exclude-directory', ef]
         endforeach
 
+        if is_flavour
+          if is_dark
+              generate_index_theme_args += [
+              '--inherits', meson.project_name() + (base_flavour != '' ? '-' + base_flavour : '')
+            ]
+          endif
+
+          if is_dark and flavour != 'dark'
+            generate_index_theme_args += [
+              '--inherits', meson.project_name() + '-dark'
+            ]
+          endif
+        endif
+
         file = configure_file(
           output: tmp_name,
           command: [
@@ -302,7 +357,6 @@ foreach flavour: icon_flavors
             '--source-dir', meson.current_source_dir() / icon_dir,
             '--output-dir', '@OUTDIR@',
             '--output-name', '@OUTPUT@',
-            is_flavour ? ['--inherits', meson.project_name()] : [],
           ] + generate_index_theme_args,
         )
         have_file = true
```

**Comment by flexiondotorg** [comment]
Sadly not, as no -dark icon `index.theme` files are generated for the accent color themes:

![image](https://user-images.githubusercontent.com/304639/160232957-aaada1d3-ea45-4f98-82d8-46a68e92517d.png)

With the change you made:

✅ Yaru and Yaru-dark work
❌ Every -dark accent theme is broken, *completely*, **in GNOME**, MATE, Unity etc because the -dark theme `index.theme` references `IconTheme=Yaru-<accent>-dark` which doesn't exist.
❌ Yaru-mate-dark is broken because its icon `index.theme` says `Inherits=Yaru,Humanity,hicolor` which means **no MATE icons are present** and the dark color panel icons are used on a dark color panel.

See @Jupi007 pull request, as it preserves the dark/light color panel icons without duplicating them in every icon set 👍

- https://github.com/ubuntu/yaru/pull/3554

**Comment by 3v1n0** [comment]
Wait, that's weird... I do get the `Yaru-<accent>-dark` variant being generated:

```ini
[Icon Theme]
Name=Yaru-red-dark
Comment=A desktop adaptation of the Ubuntu mobile icons.
Inherits=Yaru-dark,Yaru-red,Humanity,hicolor
Example=folder
Directories=
```

**Comment by Jupi007** [comment]
@3v1n0 I don't think this `index.theme` works.
As `Yaru-dark` inherits from `Yaru`, this will erease the red accented icons.

**Comment by 3v1n0** [comment]
not sure how inheritance works here, whether is fully re-using the parent one, anyways, let me check further

**Comment by Jupi007** [comment]
Well, it first look at the icons in the theme itself, then in the first inherited theme, the second, etc.
The first icon matching the name is taken.

**Comment by Jupi007** [comment]
Well, it first look at the icons in the theme itself, then in the first inherited theme, the second, etc.
The first icon matching the name is taken.

That's why I added two panel icon themes, with no inherits and which only contains panel icons.

**Comment by 3v1n0** [comment]
> Btw, if you invert the inherits order (Yaru-red then Yaru-dark), the dark icons will also be ereased.

Ok, I see...

**Comment by Jupi007** [comment]
> > Btw, if you invert the inherits order (Yaru-red then Yaru-dark), the dark icons will also be ereased.
> 
> Ok, I see... 

Btw, of the previous btw, in that case red accented icons are preserved, but as the red icon theme inherits `Yaru` which have light panel icons, the `Yaru-dark` inherit of `Yaru-red-dark` is not used (and so it returns light panel icons).

**Comment by 3v1n0** [comment]
So, would something like this work instead?

https://github.com/3v1n0/yaru/tree/dark-icon-variants
