### ISSUE TITLE
Add missing accented icons

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3561]
- [x] **preferences-desktop-wallpaper**:

![Capture d’écran du 2022-03-25 16-49-19](https://user-images.githubusercontent.com/36476595/160157489-182735df-0791-4e38-8781-ea03417d5c43.png)

- [x] **audio-speaker-***:

![Capture d’écran du 2022-03-25 16-50-40](https://user-images.githubusercontent.com/36476595/160157584-f4880f9c-3240-4fc0-af08-69806ec7ee9d.png)

**Comment by 3v1n0** [comment]
I had the speaker ones done already, wasn't sure anything in ubuntu (GNOME) needed the desktop wallpaper preferences icon...

**Comment by Jupi007** [comment]
Well the Mate desktop will ship all those accent of Yaru, and Mate use this icon so I think we should add an accented version of this one.

**Comment by 3v1n0** [comment]
Ok, I've added it to #3562

**Comment by Jupi007** [comment]
Thanks a lot :)
