### ISSUE TITLE
mate: GTK apps use blue accent colours with Yaru-MATE-dark theme

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu/yaru#3575]
**Expected Behavior**

All GTK/GNOME apps should use the selected MATE accent colour.

**Actual Behavior**

Some GNOME apps, GNOME Maps & Clocks for example, always have a blue accent colour when Yaru-MATE-dark is selected. All other accent colours, dark and light, work correctly.

![image](https://user-images.githubusercontent.com/304639/160850302-72d2578d-c6e2-48a3-9f78-0b0467605535.png)

**Steps to Reproduce the Problem**

- Running Ubuntu MATE 22.04 beta
- Open GNOME Maps, it is pre-installed
- Select any Yaru-MATE-dark theme
- Select the location search box in the header-bar

**Software that presents the issue**

- Name: GNOME Maps
- Version: 42.0-1
- OS version: Ubuntu MATE 22.04 beta

**Yaru version**

- 22.04.3

**Comment by Jupi007** [comment]
It didn't noticed because I was on mobile, but this is `Adwaita` and not `Yaru` 🤔

**Comment by flexiondotorg** [comment]
@Jupi007 @Feichtmeier I've updated the bug report as only Yaru-MATE-dark/Yaru-dark is affected. Any chance you can look into this?

**Comment by Jupi007** [comment]
Sadly, I don't think it is related to Yaru itself.
I think it is Libhandy which is bugged with dark themes.
In fact, we also have a similar bug in Gnome. It's @Muqtxdir who noticed that.

Btw, is this problem also present after restarting the app or the system?

**Comment by flexiondotorg** [comment]
@Jupi007 It must be Yaru, specifically Yaru-MATE-dark related because all other Yaru themes (light and dark) work correctly.

**Comment by flexiondotorg** [comment]
And not just GTK4 related:

![image](https://user-images.githubusercontent.com/304639/161419843-ea86e69f-4858-4adf-9f8d-f21d88738645.png)

**Comment by Jupi007** [comment]
Looks like the theme is totally not applied, weird 🤔 

I'll try to setup a VM to see what's happening.

**Comment by Jupi007** [comment]
@flexiondotorg I installed a mate VM and I can reproduce your problem with the 'Yaru-MATE-dark' theme.
But I also installed Yaru from `master` sources, and the 'Yaru-mate-dark' theme work as expected.

So this isn't related to this repository imo.

**Comment by flexiondotorg** [comment]
Thanks for the feedback. I'll investigate what has happened to Yaru-MATE-dark.

**Comment by flexiondotorg** [comment]
This is an issue in `ubuntu-mate-artwork`.
