### ISSUE TITLE
Accessibility issue with appchooser

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3586]
The current style of selected row of the Gtk `appchooser` dialog is using the accent color:

![Capture d’écran du 2022-04-02 12-22-35](https://user-images.githubusercontent.com/36476595/161379004-43cd203f-dc21-4b82-99a0-9f28103929d4.png)

But it's imo a really bad thing in term of accessibility, because some app icons blend very bad with the accent color (like the `Rawtherapee` one in the screenshot).
It is even a regression regardless to Ubuntu 21.10, which was using grey selected row everywhere:

![Capture d’écran du 2022-04-02 12-24-18](https://user-images.githubusercontent.com/36476595/161379045-ba8139d0-0567-4960-99cc-32eb62605d76.png)

In fact we reverted this tweak because of issues with treeview in some apps like Libreoffice.
But in that case, we are able to target only this dialog, thanks to the `appchooser` css selector.
Imo, we should reuse the grey selected in the app chooser, because we can safely target it without any side effect.

This would solve this issue, which looks like an accessibility problem for me.

**Edit:** make the proposed change will also unify the look of the dialog with nautilus, which is already using grey selected row. So this is also a consistency issue.

**Comment by Jupi007** [comment]
Btw, there is the same problem with the `filechooser` dialog:

![Capture d’écran du 2022-04-02 12-34-51](https://user-images.githubusercontent.com/36476595/161379290-f166039f-6b32-4930-9c90-001836fc2def.png)

Same here, we can fix this by targetting `filechooser` selector, so no side effect.

**Comment by Feichtmeier** [comment]
I'm all for grayifying accent colour rows as long as we can (as you said) specifically target a ending amount of Windows with a selector

**Comment by popov895** [comment]
If the color of the selected item in the list is the same as the color of the switch, then the latter is almost invisible.

![Screenshot from 2022-04-18 09-31-45](https://user-images.githubusercontent.com/24252473/163791638-10f5cf64-1181-4eb8-9f83-6f2a0c09d831.png)

**Comment by Jupi007** [comment]
Hi @popov895,
thanks for your comment.
We're currently not planing to drop the colorful selected row.

So can you open a new issue for this problem, please?

**Comment by Jupi007** [comment]
I'm closing this.
We are not planing to change this for 22.04, and newer version of Ubuntu will ship Gtk4 apps, which will solve the problem.
