### ISSUE TITLE
Nautilus dark theme file selection renders images to be almost black

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#3599]
![image](https://user-images.githubusercontent.com/15329494/162588040-9726bf3e-e4b6-4664-95ea-a52142afbe67.png)

It doesn't happen with all images :shrug: 

But many images are almost black if you select them

**Comment by Jupi007** [comment]
And with Adwaita?

**Comment by Feichtmeier** [comment]
Okay Adwaita gets more and more hard to activate ^^  
here you go:

![image](https://user-images.githubusercontent.com/15329494/162588344-98036375-5948-47c7-82ea-664c8cbeb760.png)

I think it is better than with yaru. maybe something in the nautilus css code I've migrated that is not perfectly working out

**Comment by Jupi007** [comment]
Okay, thanks.
It looks indeed that the default theme is better than Yaru.

I'll try to take a look tomorrow.

**Comment by Feichtmeier** [comment]
If you didn't find it already, it's either this 
https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.0/apps/_nautilus.scss#L358

Or that

https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.0/apps/_nautilus.scss#L197-L202

I think :)

**Comment by Jupi007** [comment]
@Feichtmeier I finally found the time to look at this.

It looks it is related to the selected background color of the `.view`.
For example:

| White | Grey | Black |
| -------- | ------ | ------- |
| ![Capture d’écran du 2022-04-11 15-39-37](https://user-images.githubusercontent.com/36476595/162752332-b2e8473d-4b2b-4e6c-b1c8-bdfedce94544.png) | ![Capture d’écran du 2022-04-11 15-39-56](https://user-images.githubusercontent.com/36476595/162752369-ed2c160d-d199-413f-a0b2-594c56ab871c.png) | ![Capture d’écran du 2022-04-11 15-40-12](https://user-images.githubusercontent.com/36476595/162752394-c8e25b3c-33dd-4479-86ef-8c5cd1e3b4d0.png) |

You can see that the luminosity of the selected bg is impacting the luminosity of the image preview.
We can't select the image itself, so this can't be fixed unless we change the color used as `selected_bg_color` here.

**Comment by Feichtmeier** [comment]
Let's drop our modifications then. Better accent colour than a broken look.
Are you okay with this @madsrh ?

**Comment by Jupi007** [comment]
I don't think this will solve the problem, because it will still use `selected_bg_color`.
Or do you mean to use Adwaita blue?

**Comment by Jupi007** [comment]
@Feichtmeier I curently can't test this now because I'm not at home. But if you want I can do it this evening :)

**Comment by madsrh** [comment]
> Let's drop our modifications then. Better accent colour than a broken look.
Are you okay with this madsrh ?

@Feichtmeier Sorry, do you mean that the label background and thumbnail "overlay" is orange (like Adwaita is blue with blue)?

**Comment by Feichtmeier** [comment]
> @Feichtmeier I curently can't test this now because I'm not at home. But if you want I can do it this evening :)

If you have your dev env already, sure :) need to set it up first

@madsrh if it is like I think then yes, we would go back to the upstream selection : /

**Comment by Jupi007** [comment]
@Feichtmeier I found a solution 😋
I'll do a PR.

**Comment by madsrh** [comment]
> I'll do a PR

Could you add a screenshot or a gif? 😅

**Comment by Jupi007** [comment]
Well... I found a problem in my solution... 😅
But I'm trying another thing.

If it also not working, I'll just drop the tweak as @Feichtmeier suggested.
