### ISSUE TITLE
The default action button in dialogs is always green, regardless of the accent color

### ISSUE THREAD

**Issue by popov895** [ubuntu/yaru#3610]
Currently, the default action button in dialogs is always green, regardless of the accent color. IMO, it would be great if this button was colored in the accent color.

![Screenshot from 2022-04-18 09-23-27](https://user-images.githubusercontent.com/24252473/163791118-e560a83e-6259-439c-848a-7e1894a4b9dc.png)

![Screenshot from 2022-04-18 09-23-43](https://user-images.githubusercontent.com/24252473/163791147-076d453f-2591-4734-97b1-83b84f3515ef.png)

![Screenshot from 2022-04-18 09-23-55](https://user-images.githubusercontent.com/24252473/163791157-59d2bf4d-cce8-4040-a691-308efca22889.png)

**Comment by 3v1n0** [comment]
This was a feature on old yaru theme, TBH.

But, I've the feeling we should use accent color here when something that is not using the Orange color is selected...

**Comment by Muqtxdir** [comment]
hi @3v1n0 

are you suggesting to replace the suggested-action color from `$green` to `$selected_bg_color` like how upstream does?

**Comment by Jupi007** [comment]
That's sad because it is the last big Yaru tweak which remains, but I agree that this button should follow the accent color.
So it looks consistent with Gtk4.

**Comment by popov895** [comment]
Will this fix be available in Ubuntu 22.04?

**Comment by Jupi007** [comment]
Sadly, I don't think we can because it is a design change.

**Comment by popov895** [comment]
Anyway, thanks for your work!
