### ISSUE TITLE
The active switch is almost invisible in the selected list item

### ISSUE THREAD

**Issue by popov895** [ubuntu/yaru#3611]
Since Ubuntu 22.04, both the selected list item and the active switch use the accent color for the background. And as a consequence, the active switch is almost invisible in the selected list item.

![163791638-10f5cf64-1181-4eb8-9f83-6f2a0c09d831](https://user-images.githubusercontent.com/24252473/163871442-e2ddc4ce-1cac-43fb-b251-406c814d7bff.png)

**Comment by Jupi007** [comment]
I noticed another problem:

![Capture d’écran du 2022-05-06 11-11-23](https://user-images.githubusercontent.com/36476595/167107491-754904ed-3484-4cc8-8ca2-146d9d54f9cd.png)

The fix for all that will follow.

**Comment by popov895** [comment]
Looks like other controls are also affected:

![Screenshot from 2022-05-20 22-52-31](https://user-images.githubusercontent.com/24252473/169604607-ded5f08d-1817-4edc-9c95-c7cc3069aadd.png)

**Comment by Jupi007** [comment]
Indeed, thanks @popov895
