### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3617]
![Captura de tela de 2022-04-26 03-22-49](https://user-images.githubusercontent.com/59381215/165237574-cec55b8d-c7c5-424f-b770-92d85a96189e.png)

![Captura de tela de 2022-04-26 03-22-48](https://user-images.githubusercontent.com/59381215/165237433-1ce251e3-3bba-4443-9dab-1fa3be707d8e.png)

Has this bug when approaching mouse pointer in Yaru and Yaru-dark theme.

![Captura de tela de 2022-04-26 03-23-25](https://user-images.githubusercontent.com/59381215/165236299-c78556dc-17ca-49a0-b296-9f9ced5df31a.png)

In Adwaita theme is ok.
- Ubuntu 22.04
-  Cinnamon session

**Comment by ItzSwirlz** [comment]
Make sure when you build the theme you run the 'generate-symlinks' script first

**Comment by Jupi007** [comment]
I can reproduce the problem in the Gtk3-widget-factory.
We indeed surly miss an asset.

**Comment by ItzSwirlz** [comment]
> We indeed surly miss an asset.

is it a missing symlink or something else? I'm sure GNOME shell has some other slider button asset

**Comment by Initu-Castilhos** [comment]
> > Nós realmente sentimos falta de um ativo.
> 
> é um link simbólico ausente ou outra coisa? Tenho certeza de que o shell do GNOME tem algum outro recurso de botão deslizante

I think it's a problem with the installation.
