### ISSUE TITLE
Evolution - Mail text not visible using dark yaru theme

### ISSUE THREAD

**Issue by FreaxMATE** [ubuntu/yaru#3630]
**Expected Behavior**

When you select a dark yaru theme and open evolution you should still be able to read the text of your messages with a sufficient contrast.

**Actual Behavior**

The background turns dark but the fonts stays black. So in the end you cannot read the text:

**Steps to Reproduce the Problem**

1. Select a dark yaru theme
2. Open Evolution and select a message

**Software that presents the issue**

- Name: Evolution
- Version: 3.42.4
- OS version: Manjaro (up-to-date)

**Yaru version**

22.04.4

**Screenshots**

![Screenshot at 2022-05-04 17-32-07](https://user-images.githubusercontent.com/49864414/166716925-c251a10a-75bf-4366-9bdf-02c9ffb35714.png)

**Upstream check**

The issue does not happen with the light theme of course. Is there a dark Adwaita variant??
```
GTK_THEME=Adwaita-dark evolution
```
and others did not seem to work.

Probably here: https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.0/apps/_evolution.scss 😅
but I have no idea how to get the right names and the syntax right.

**Comment by Jupi007** [comment]
Hi @FreaxMATE,
thanks a lot for the report.

It looks like this is a bug in the app itself (see #3485).
I'm closing this issue so.

**Comment by FreaxMATE** [comment]
Thanks @Jupi007 

sorry I missed this.

**Comment by Jupi007** [comment]
No problem, don't worry :D
