### ISSUE TITLE
Yaru mimetypes not reflecting current O365 design

### ISSUE THREAD

**Issue by MarvinDjd** [ubuntu/yaru#3648]
It may be minor but Yaru shows for e.g. Word files still the "old" O2013 logo. Could they be changed to the new ones? [Current designs](https://commons.m.wikimedia.org/wiki/File:Office_365_app_logos.svg) ?

**Comment by Jupi007** [comment]
Hi @MarvinDjd,
thanks, I think it is a good idea.

Wdyt @Feichtmeier @Muqtxdir ?

**Comment by Muqtxdir** [comment]
@Jupi007 makes sense to update them, +1 from me
