### ISSUE TITLE
Please set gnome-console background color

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#3666]
GNOME Terminal has a purple background by default in Ubuntu. GNOME Console should do that too.

https://launchpad.net/bugs/1977769

@rastersoft recently patched GNOME Console in Ubuntu 22.10 to allow its background to be overridden in CSS.

See https://gitlab.gnome.org/GNOME/console/-/merge_requests/95 for details.

**Comment by Jupi007** [comment]
Hmm, GNOME Console is using Gtk4 and Libadwaita, indeed?
If so, we cannot do anything on our side, as Libadwaita is blocking theming.

**Comment by rastersoft** [comment]
There is an alternative: you can edit the Gnome Console CSS and change there the background color for the specific widget.

**Comment by jbicha** [comment]
> Hmm, GNOME Console is using Gtk4 and Libadwaita, indeed? If so, we cannot do anything on our side, as Libadwaita is blocking theming.

Ubuntu has patched libadwaita in Ubuntu 22.04 LTS and 22.10 to allow some degree of theming. So this request may be possible for Ubuntu.

Yes, this feature request is for GNOME Console 43 in Ubuntu 22.10 which uses GTK4 + libadwaita.

**Comment by Jupi007** [comment]
Hmm, but I don't think it is possible on the Yaru side. Our Gtk4 theme, which is currently based on Libadwaita, is not applied at all in those apps.
I think remember that the patch is only changing the accent color.

Maybe I'm wrong, but I think the only way to change the bg would be to overwrite it in Console css file itself.

**Comment by rastersoft** [comment]
There are two possibilities, then:

* add a custom patch to modify the Console CSS to set a different background color
* add a custom patch to Console to set the background color from a GSettings, and set the default value to the one desired by us.

**Comment by jbicha** [comment]
@3v1n0 What's your opinion on how to handle this?

**Comment by Muqtxdir** [comment]
how about a patch to `gnome-console` that checks if in `Ubuntu` session then make use of the aubergine-shade as background-color?
In this way you might not need to patch `gnome-console` to present the option to change/customize the background-color.

**Comment by Feichtmeier** [comment]
> GNOME Terminal has a purple background by default in Ubuntu. GNOME Console should do that too.
> 
> https://launchpad.net/bugs/1977769
> 
> @rastersoft recently patched GNOME Console in Ubuntu 22.10 to allow its background to be overridden in CSS.
> 
> See https://gitlab.gnome.org/GNOME/console/-/merge_requests/95 for details.

May I ask why exactly?
The whole desktop light when the light theme is selected
The whole desktop is dark when the dark theme is selected

Why should the terminal be an exception?
Light themes are good when your display sits in light surrounding
Dark themes are good sehen your display sits in dark surroundings

I've created a more detailed explanation in some years or months ago:

**Comment by Jupi007** [comment]
Closing this: we can't fix that from the yaru side.

**Comment by uRohan** [comment]
> GNOME Terminal has a purple background by default in Ubuntu. GNOME Console should do that too.
> 
> https://launchpad.net/bugs/1977769
> 
> [@rastersoft](https://github.com/rastersoft) recently patched GNOME Console in Ubuntu 22.10 to allow its background to be overridden in CSS.
> 
> See https://gitlab.gnome.org/GNOME/console/-/merge_requests/95 for details.

So, that's why I can't use the `Light Style` or `Follow System Style` options in GNOME Console on Ubuntu 24.04.

Is it possible to implement a light background color as an alternative to the current dark purple background, so that `Light Style` and `Follow System Style` will work as expected? Previously, I had to install GNOME Console on Ubuntu 22.04 to use these options because they wouldn't work in GNOME Terminal on the same version for the same reason.

It was quite strange to introduce this buggy behavior, where the `Light Style` and `Follow System Style` options don't work in GNOME Terminal, to a new application.

Sorry for necroposting, but I thought this issue might still be relevant.

**Comment by jbicha** [comment]
This issue isn't relevant since GNOME Console is no longer being considered to become a [default app](https://discourse.ubuntu.com/t/proposal-gnome-console-as-default-terminal-app/28309/27) for Ubuntu Desktop.

Ubuntu used to patch GNOME Console to change the background to purple but that has now been removed. GNOME Console does not officially support changing the background color and it's not the Ubuntu Desktop's team job to patch every terminal app to change it to purple. Notably, Ubuntu's patch did not provide any way for users to get the default behavior instead.

If you want a colorful background in a modern terminal app, I recommend Ptyxis available in Ubuntu 24.10 and newer. It has a purple background by default in Ubuntu but you can easily change the Palette to something else.

**Comment by uRohan** [comment]
> This issue isn't relevant since GNOME Console is no longer being considered to become a [default app](https://discourse.ubuntu.com/t/proposal-gnome-console-as-default-terminal-app/28309/27) for Ubuntu Desktop.
> 
> Ubuntu used to patch GNOME Console to change the background to purple but that has now been removed. GNOME Console does not officially support changing the background color and it's not the Ubuntu Desktop's team job to patch every terminal app to change it to purple. Notably, Ubuntu's patch did not provide any way for users to get the default behavior instead.
> 
> If you want a colorful background in a modern terminal app, I recommend Ptyxis available in Ubuntu 24.10 and newer. It has a purple background by default in Ubuntu but you can easily change the Palette to something else.

Sorry to bother you, and thank you for your time.
