### ISSUE TITLE
Missing close button for Java JDialog for dark theme

### ISSUE THREAD

**Issue by betaiotazeta** [ubuntu/yaru#3675]
Hello!
For a standard Java application, using Swing, the window button (command) "close" of a JDialog is present while using Yaru light theme but missing when using Yaru dark theme.
OS: Ubuntu Mate 22.04.
Package: yaru-theme-gtk
Version: 22.04.4
Thank you for your efforts!

![present](https://user-images.githubusercontent.com/37256316/184228917-eaea8508-6ed0-410e-8f86-b1993593637d.png)
![missing](https://user-images.githubusercontent.com/37256316/184229198-7a983b30-9bec-4460-8c6e-06e2759bb646.png)

**Comment by Jupi007** [comment]
Hi @betaiotazeta,
thanks for the report.

I'm not using Java, so can you provide an easy way to test this?
Thanks :)

**Note:** at first look, I think it is related to _metacity_, so ping @flexiondotorg

**Comment by betaiotazeta** [comment]
Hi @Jupi007, @flexiondotorg,

The easiest way to test would be to download my latest "click and run" app, but that would be inappropriate to suggest. So the following is a longer but more standard procedure:

Here is a code snippet that can be compiled into a simple tester:

```
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class YaruDialogTester {

    private static void createAndShowGUI() {
        JFrame frame = new JFrame("Main JFrame");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JButton button = new JButton("Click me!");
        button.setPreferredSize(new Dimension(500, 300));
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JDialog dialog = new JDialog(frame, true);
                dialog.setLocationRelativeTo(frame);
                dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                dialog.setTitle("JDialog");
                dialog.getContentPane().setLayout(new BorderLayout());
                JLabel label = new JLabel("Close me!", JLabel.CENTER);
                label.setPreferredSize(new Dimension(300, 200));
                dialog.getContentPane().add(label);
                dialog.pack();
                dialog.setVisible(true);
            }
        });
        frame.getContentPane().add(button, BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
}
```

It must be copied in a file named YaruDialogTester.java

You need Java Development Kit: sudo apt-get install default-jdk

Place the file in an empty folder, open a terminal and cd into it.

Compile by typing: javac YaruDialogTester.java

Run by typing: java YaruDialogTester

Observe the "close window button" appear and disappear when switching between light and dark themes.

**Comment by betaiotazeta** [comment]
Thank you @Jupi007, nice work!

**Comment by Jupi007** [comment]
You're welcome :)
