### ISSUE TITLE
No yellow color

### ISSUE THREAD

**Issue by MilutinMujovic** [ubuntu/yaru#3684]
Hello, as someone who generally uses yellow in theming, I am sad that there isn't a yellow color in the accent color selection.
Please add it as it is clearly missing. 

Thank you in advance! :)

**Comment by Jupi007** [comment]
Hi @MilutinMujovic 
Thanks to have taken the time to write this issue.
I personally think it is a good idea to add a yellow shade to our accents.
We'll discuss of that and maybe add it :)

**Comment by MilutinMujovic** [comment]
> Hi @MilutinMujovic Thanks to have taken the time to write this issue. I personally think it is a good idea to add a yellow shade to our accents. We'll discuss of that and maybe add it :)

Thank you very, very much! 
I know it's not a huge thing, but I really love your theme and yellow accents go so well with the dark mode. 
I don't know how complicated it is, but maybe sometimes in the future you could add the option for custom color via HEX. 

Once again, I really appreciate you taking the time to reply. 👍

**Comment by Muqtxdir** [comment]
from upstream with gnome 47 [ubuntu 24.10] onwards, we now have yellow :)

**Comment by LordMilutin** [comment]
> from upstream with gnome 47 [ubuntu 24.10] onwards, we now have yellow :)

That's great to hear. Finally we got justice for yellow! 😍
