### ISSUE TITLE
GNOME Shell 43 quick settings isn't themed correctly

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#3688]
**Expected Behavior**

GNOME Shell 43.beta added a new quick settings feature to the system status menu in the right side of the top bar.

It should display well.

**Actual Behavior**

![image](https://user-images.githubusercontent.com/876259/185807562-c47e2f19-be4b-4957-a1c0-7f37f62652e8.png)

**Steps to Reproduce the Problem**

1. I built mutter and gnome-shell from the Salsa ubuntu/master branches.
2. I edited `/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/metadata.json` to add add '43' to the supported lists.
3. I installed git master for yaru-theme
4. I logged out and logged back in.

**System information**
- Shell version: 43.beta
- Ubuntu version: Ubuntu 22.10

**Yaru version**

- 22.04.4-33-gffc680115

**Upstream check**

- This does not affect the default GNOME session

**Comment by Jupi007** [comment]
Hi @jbicha,
thanks a lot for trying this.

Can you instead use this wip PR #3676 which add GS43 support ?

**Comment by jbicha** [comment]
Yes, it's usable now with that pull request. I notice that it needs a dark mode icon.

![image](https://user-images.githubusercontent.com/876259/185812735-483a034d-badf-4553-aee1-fb10795b7054.png)

**Comment by Muqtxdir** [comment]
hi @jbicha 

please change the `gnome-shell-gresource` to `true` from `false` while building it, that way it'll pick the icon.
