### ISSUE TITLE
Edge resize cursor targets seem misaligned

### ISSUE THREAD

**Issue by komputerwiz** [ubuntu/yaru#3696]
When resizing windows or regions that use the edge resize cursors (`top_side`, `bottom_side`, `left_side`, `right_side` in **icons/src/cursors**), the mouse target—canonically positioned at the very tip of the default cursor—is positioned on the "outer" triangle rather than between the triangles, as the cursor's symmetry might suggest. This can make it difficult to position the cursor accurately, especially for small resize handles.

**OS/Desktop/Yaru version**

- Ubuntu 22.04.1 LTS (upgraded from Ubuntu 20.04)
- gnome-shell 42.2-0ubuntu0.2 (X11 Session)
- xorg 1:7.7+23ubuntu2
- yaru-theme-icon 22.04.4

**Screenshots**

The cursor target for Yaru's edge cursors is where the "outer" triangle is, but one might expect the target to be centered between the triangles. This makes it seem like the cursor gets "pulled in" towards the inside of the window/object being resized. In the screenshots below, the cursor target is centered as precisely as I could get on the window border for various programs (Gedit, GNOME Terminal, Visual Studio Code).

_Note: VS Code has its own custom window decoration that does not match exactly with the X11 window edge, which further exacerbates the "misaligned" appearance._

![Gedit (Yaru left edge resize)](https://user-images.githubusercontent.com/369238/186222494-a617813b-f003-4378-ae74-61756cbea5d5.png)
![GNOME Terminal (Yaru top edge resize)](https://user-images.githubusercontent.com/369238/186222501-fd9b6ab7-c7ba-4d49-bd1d-9364f5b7f43f.png)
![VS Code (right edge resize; Yaru)](https://user-images.githubusercontent.com/369238/186222504-3d40511a-2d2b-4a52-a56f-9d5ea3bfaaa1.png)

Here is an example of the "expected" positioning demonstrated in Nautilus with the horizontal resize cursor, which has a similar symmetrical appearance:

![Nautilus (Yaru horizontal resize)](https://user-images.githubusercontent.com/369238/186223518-382823f2-f7be-48f8-ac70-099b26950d35.png)

The cursor's target position near the "outer edge" of the cursor image makes sense based on how the DMZ-Black edge resize cursors look. Here is an example with Evolution:

![Evolution (DMZ-Black top edge resize)](https://user-images.githubusercontent.com/369238/186225254-45a4d689-0994-4707-8e26-8503f518de14.png)

**Comment by Jupi007** [comment]
Hi @komputerwiz 
thanks a lot for the report!

I can confirm the problem, and I'll try to fix it :)
I'll also try to backport this to 22.04.

**Comment by komputerwiz** [comment]
I'm glad I could do something to contribute!
I wish I could offer a pull request, but I have no experience with designing cursors. :slightly_smiling_face: 

Thanks for all the great work!
