### ISSUE TITLE
White text on orange background in GNOME 43 quick settings

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru#3716]
**Expected Behavior**

Nice and readable colors

**Actual Behavior**

Low contrast - white text on orange background

**Steps to Reproduce the Problem**

1. Run the latest Ubuntu 22.10 Kinetic Kudu
2. Open quick settings
3. Toggle some of the buttons on

**System information**

- Shell version: GNOME Shell 43.beta
- OS version: Ubuntu 22.10 Kinetic Kudu (development branch)

**Yaru version**

22.10.1

**Screenshots**

![image](https://user-images.githubusercontent.com/140617/187265126-ec3a72c6-c10e-41d7-a4ea-c235980b3845.png)

**Comment by Feichtmeier** [comment]
I agree. As a comparison here is the material 2 control panel from Android 12

![Screenshot_20220829-192413.png](https://user-images.githubusercontent.com/15329494/187266504-2931dbfa-6a7e-4e59-ae57-27769f044e59.png)

I don't think it looks much better but at least it doesn't burn your eyes.

We should either use dark text or do not use primary accent colour as full surface here. Maybe shades of gray?

**Comment by Jupi007** [comment]
I agree, this is too much.

Two solution: tone down the color, or use grey.
Use dark text does not work with orange (which has white as fg color)

**Comment by Jupi007** [comment]
I saw there is some colored icons (power mode), imo we should use grey here.
