### ISSUE TITLE
gnome-shell 42 quick settings shrunk (smaller) after 22.10.1 update

### ISSUE THREAD

**Issue by Scotty-Trees** [ubuntu/yaru#3726]
**Expected Behavior**

Using Gnome's Quick Settings in the top panel on the right to should display readable and easy to navigate access to wifi, bluetooth, night light, etc.

**Actual Behavior**

Yaru GTK theme got updated today from the [AUR](https://aur.archlinux.org/packages/yaru-gtk-theme) to v22.10.1 (previous version was 22.04.4 btw) and now when I access the Quick Settings menu, it is very very small, so small that is cuts off some of the names to the settings I'm trying to access. I assume this is due to a Quick Settings change to make way for Gnome 43, but I still just wanted to bring it to the teams attention just in case this was an unintended side-effect. 

**Steps to Reproduce the Problem**

Depending on your system specs, the steps might be hard to reproduce. Essentially I'm just clicking and viewing the Quick Settings while on the latest stable version of Yaru.I am on EndeavourOS using Gnome 42.4, I'll submit my full system specs in more detail below. Note: I have _not_ tested the yaru-gtk-theme-git package that is also in the AUR.

**System information**

- Shell version: ```GNOME Shell 42.4```
- OS version: 
```
LSB Version:	n/a
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling
```

**Yaru version**

22.10.1

**Screenshots**

Here's a screenshot to show how much smaller the Gnome Quick Settings Menu looks like:

![Screenshot from 2022-09-04 21-07-25](https://user-images.githubusercontent.com/45135187/188342749-648c15ef-0020-4f23-80d3-b047ec440048.png)

Here's a screenshot of the [Mpris Indicator button extension](https://extensions.gnome.org/extension/1379/mpris-indicator-button/):
 
![Screenshot from 2022-09-04 21-07-47](https://user-images.githubusercontent.com/45135187/188341751-2e3f048c-2754-4404-aa6e-f856201e96a5.png)

*For context, the following screenshots are from previous versions of Yaru not affected by the current issue*

On Yaru v22.04.4, here is an old screenshot I had showing how wide the Quick Settings menu is supposed to look:

![Screenshot from 2022-07-11 15-16-36](https://user-images.githubusercontent.com/45135187/188342863-5ae16fe1-dda8-4ec8-b4d3-0e08cbec214f.png)

Here below showing the Yaru v22.04.4 size of the [Mpris Indicator button extension](https://extensions.gnome.org/extension/1379/mpris-indicator-button/) (it simply shows your music players MPRIS in its own drop down) Notice how it's wide and legible to read easily compared to the screenshot of it above where it's very small and hard to read:

![Screenshot from 2022-04-28 14-01-59](https://user-images.githubusercontent.com/45135187/188342107-5241cfdc-3da5-43a6-ae18-62aafb3b1ebd.png)

Please let me know if I can provide any other information. Yaru is my favorite theme, I'm happy to use it, happy to test it and happy the devs put a lot of work into this, so please let me know what I can do to fix this issue. If this is strictly an upstream issue and I'll just have to wait until Gnome 43 is release, please let me know, thank you.

**System Information**

 ```
[scott@EndeavourOS ~]$ inxi -Fxxxza --no-host
System:
  Kernel: 5.19.6-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    parameters: initrd=\5f36d8c0aa64460e9be33539d6a364bd\5.19.6-arch1-1\intel-ucode.img
    initrd=\5f36d8c0aa64460e9be33539d6a364bd\5.19.6-arch1-1\initrd
    root=UUID=7bbebb61-b0bd-412c-8718-3e7c0cc5dc2b rw rootflags=subvol=@
    resume=UUID=7a05f1cc-8f0d-4e1b-a87b-d27813fc6377 loglevel=3 quiet
    nowatchdog nvme_load=YES nvidia-drm.modeset=1
  Desktop: GNOME v: 42.4 tk: GTK v: 3.24.34 wm: gnome-shell dm: GDM v: 42.0
    Distro: EndeavourOS base: Arch Linux
Machine:
  Type: Laptop System: Acer product: Aspire E5-576G v: V1.32
Info:
  Processes: 297 Uptime: 45m wakeups: 1 Memory: 15.51 GiB used: 2.84 GiB
  (18.3%) Init: systemd v: 251 default: graphical tool: systemctl
  Compilers: gcc: 12.2.0 Packages: 1223 pacman: 1153 lib: 329 flatpak: 70
  Shell: Bash v: 5.1.16 running-in: tilix inxi: 3.3.20
```

**Comment by jbicha** [comment]
Yes, Yaru 22.10.x is intended for the GNOME Shell 43.x only.

You need to use the 22.04.x series for GNOME Shell 42.x.

**Comment by Scotty-Trees** [comment]
All that beautiful work I put into that bug report too! Haha, no worries though, I had a sneaking suspicion that might be the case. Sorry to have bothered the team. Thank you kindly for the very quick reply back. I'll make my best attempts to downgrade my current package and hold off until the Gnome 43 release. Keep up the great work, it's very much appreciated!
