### ISSUE TITLE
Change datetime format

### ISSUE THREAD

**Issue by enghitalo** [ubuntu/yaru#3738]
![image](https://user-images.githubusercontent.com/63821277/192032539-90dcc0dc-f504-45f0-8751-1f6a504baf79.png)

Hi. I tried this comand, but this folder, apparently not exist more.

```bash
gsettings set com.canonical.indicator.datetime time-format custom

gsettings set com.canonical.indicator.datetime custom-time-format '%l:%M %p %A %B %d'
```
As I can see in dconfi app.
![image](https://user-images.githubusercontent.com/63821277/192033019-53ce2087-f635-4b1f-a9d2-44e968f6f1d5.png)

**Comment by Jupi007** [comment]
Hi @enghitalo,
thanks for having took the time to create this issue :)

Sadly, I don't think it is related to this repository, which is dedicated to all the Ubuntu's theme (gtk, gnome-shell, icons...).
We do not have any control on any gsettings stuff nor on the date time layout.

So sorry, but I need to close your issue.
