### ISSUE TITLE
Colour variants for cursor

### ISSUE THREAD

**Issue by hsbasu** [ubuntu/yaru#3745]
**Icon Request**
Colour variants for Yaru cursor theme.

We have colour variants for all other theme components except for cursor. Currently Yaru only provides a light/white and a black cursor. IMO it would be a worthy enhancement to the current themes.

**Screenshots**
May be something like [this](https://github.com/hsbasu/mamolinux-cursors) or Oxygen cursors.

@Jupi007 Mentioned for better reach.

**Comment by Jupi007** [comment]
Thanks but personally, I don't think it is a good idea to color the cursor.
I really like our neutral one, we discussed during a long time to reach the current state (please look at issue and pr with the "area: cursors" tag).

CC @Muqtxdir

**Comment by hsbasu** [comment]
> ... I really like our neutral one, we discussed during a long time to reach the current state (please look at issue and pr with the "area: cursors" tag).
>
Sorry @Jupi007. There are 10 closed issue with "area: cursors" tag. But I couldn't find any with the request of cursor colour variants.

**Comment by Jupi007** [comment]
Indeed, but in some of them we discussed of adding a touch of color :)
There was some very very long discussions about cursors 😅
And finally, we decided to have a neutral cursor (we progressively removed all colors).

But anyway, this would require an huge adaptation of all our build scripts and meson, and I really don't have enough time for this.

**Comment by hsbasu** [comment]
Ok. I'm closing this then.

**Comment by Jupi007** [comment]
Thanks for your understanding 🙂
And sorry.
