### ISSUE TITLE
Colour variants for cinnamon theme

### ISSUE THREAD

**Issue by hsbasu** [ubuntu/yaru#3754]
Currently, there are no colour variants for cinnamon. Are there any plan to create them?

If yes, @Jupi007 you can checkout [this one](https://github.com/hsbasu/sucharu/tree/master/cinnamon-shell). If there are no plans for adding the accent colours please close this issue.

**Comment by hsbasu** [comment]
Sure. But it'll take some time. I'm fully occupied with my PhD projects.

**Comment by Jupi007** [comment]
No problem, you have full time until the next ui freeze next year :)

**Comment by Initu-Castilhos** [comment]
Another solution is to change the accent color of the Cinnamon theme to ghaphite #666666 and for the Yaru-cinnamon theme the color #dd682a that is already available for compilation. There's an example of the theme I posted on Pling https://www.pling.com/p/1961261/

**Comment by hsbasu** [comment]
Hi @Jupi007  I have created the variants for cinnamon theme. But I am having troubles taking care of some of the assets. I'll push them to a branch. Can you help me out?

**Comment by Initu-Castilhos** [comment]
> Oi@Jupi007 Eu criei as variantes para o tema canela. Mas estou tendo problemas para cuidar de alguns dos ativos. Vou empurrá-los para um galho. Você pode me ajudar?

Yes, I can create the thumbnails or create the assets manually.

**Comment by Initu-Castilhos** [comment]
> Oi@Jupi007 Eu criei as variantes para o tema canela. Mas estou tendo problemas para cuidar de alguns dos ativos. Vou empurrá-los para um galho. Você pode me ajudar?

If you want, I can create the assets manually and post them here in .zip files, because I don't know how to create a pull.
