### ISSUE TITLE
Ubuntu logo in About section in gnome settings

### ISSUE THREAD

**Issue by iyorozuya** [ubuntu/yaru#3755]
- When gnome settings app window is small vertically
![image](https://user-images.githubusercontent.com/26306108/194774783-e98a2ab1-7515-4d4e-bf0d-3a273634d153.png)
This is how Ubuntu logo looks when About section window in gnome settings app is not vertically maximized, which I think looks fine.

- When gnome settings app window is maximized or it's window is vertical height is near to full
![image](https://user-images.githubusercontent.com/26306108/194774858-cdd8056d-2053-4300-9e1f-e3c30b1ee5dc.png)
This is how Ubuntu logo looks when About section window in gnome settings app is maximized. Ubuntu logo looks blurry in this case.

English is not my first language. Sorry for my bad English.

**Comment by Jupi007** [comment]
Hi @iyorozuya,
thanks for the time you took to write this issue :)

Sadly, this is not the correct repository to report this problem. Sorry.
I invite you to write the same one at the ubuntu gnome settings repository.

@Muqtxdir can you please, give the correct address to it? :)

**Comment by Muqtxdir** [comment]
Hi @iyorozuya,

As already mentioned by @Jupi007 this is not the repository for the settings app, however you can open an issue as bug under the `gnome-control-center` in launchpad and describe this bug. link: https://bugs.launchpad.net/ubuntu/+source/gnome-control-center
