### ISSUE TITLE
Incorrect accent color on calculator app

### ISSUE THREAD

**Issue by iyorozuya** [ubuntu/yaru#3756]
![image](https://user-images.githubusercontent.com/26306108/194811160-9eeea7f2-bca2-48c9-8594-9f87df2a481d.png)
I have applied blue accent color. You can see in calendar app that everything is in blue which is right. On the other hand, in case of calculator, the equals button has orange color background which doesn't match my accent color.

**Comment by Muqtxdir** [comment]
This is the expected behaviour, `gnome-calculator` makes use of `orange` color from the palette instead of using the `accent-color`.

It's a decision made by the calculator app-devs, as they wanted the equal symbol to resemble the color to the one used in their icon.

**Comment by iyorozuya** [comment]
Thanks for the quick reply. 
Since it is the expected behaviour, so I am closing this issue.

**Comment by Muqtxdir** [comment]
np, :)
