### ISSUE TITLE
User-trash use wrong design at 256x

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3761]
![Capture d’écran du 2022-10-16 16-26-19](https://user-images.githubusercontent.com/36476595/196041404-45bf71d7-681a-4538-909b-36ac9274eb74.png)

**Comment by vanvugt** [comment]
It's been a few months. Seems this issue is still present on lunar: https://launchpad.net/bugs/2008453

**Comment by Jupi007** [comment]
It is fixed in master, is there anything else we should do here?

**Comment by vanvugt** [comment]
I guess I'm just wondering if it's expected that lunar still doesn't have the fix. And whether this might be a different bug.

**Comment by Jupi007** [comment]
Weird. So no it is not expected.
Is lunar using the latest yaru fro master, or still from the previous release?

**Comment by vanvugt** [comment]
It's apparently missing #3762.

**Comment by Jupi007** [comment]
Okay, so it's just lunar yaru package who is outdated :)
Btw, is there anything we should do here to backport that to kinetic?
I just saw there's no kinetic branch.

**Comment by vanvugt** [comment]
Lunar is the only focus right now.
