### ISSUE TITLE
flatpak theme is broken

### ISSUE THREAD

**Issue by iaacornus** [ubuntu/yaru#3766]
**Expected Behavior**

I was expecting it to be consistent and be the same for the system and flatpak.

**Actual Behavior**

It produces something like this:

![Screenshot from 2022-11-07 04-58-40](https://user-images.githubusercontent.com/96870156/200194848-798e5624-d623-4798-be47-b675adaffa94.png)

![Screenshot from 2022-11-07 04-58-16](https://user-images.githubusercontent.com/96870156/200194850-5971566f-da83-4493-8292-c7e3a39eb860.png)

**Steps to Reproduce the Problem**

It is present on both procedures:

1. `flatpak install flathub org.gtk.Gtk3theme.Yaru-Purple` (version: 21.04, from: stable)
2. and `flatpak install flathub org.gtk.Gtk3theme.Yaru-Purple-Light` (version: 21.04, from: stable)

or even if you:

1. `sudo flatpak override --system --filesystem=$HOME/.themes`
2. `sudo flatpak override --system --filesystem=/usr/share/themes`
3. `sudo flatpak override --system --env=GTK_THEME=Yaru-purple`

**Software that presents the issue**

Almost all of the flatpak applications, in which either the theme is broken or it doesnt follow the theme.

**Yaru version**

22.10.3 for the system and 21.04 for the flatpak.

**Screenshots**

![Screenshot from 2022-11-07 04-58-40](https://user-images.githubusercontent.com/96870156/200194997-b369e42c-3cfa-4843-a416-48d0c022ac29.png)
![Screenshot from 2022-11-07 04-58-16](https://user-images.githubusercontent.com/96870156/200195000-af64b69a-7da0-441b-a3d6-10ed69aa6b48.png)
![Screenshot from 2022-11-07 05-08-06](https://user-images.githubusercontent.com/96870156/200195228-a633d3c0-a585-41be-ad57-f8acf251bd39.png)
![Screenshot from 2022-11-07 05-07-29](https://user-images.githubusercontent.com/96870156/200195232-c7f44bea-476f-4b13-9407-582a77433bba.png)
![Screenshot from 2022-11-07 05-07-35](https://user-images.githubusercontent.com/96870156/200195230-f2a9c4fb-9a96-4dca-bcd5-d94e83a3c5f6.png)

**More info**

I am on Fedora Silverblue 36 with Gnome 42.4, I installed Yaru via `rpm-ostree`, it works perfectly on system applications. As for flatpak, I tried to apply it with both of the methods I've given above (tried installing the flatpak package for yaru, doesn't work, then tried overriding the directories where they are located, also doesn't work). If there is any more info needed or help I would try my best to provide it. Thank you.

**Comment by Jupi007** [comment]
@Muqtxdir Can you look at this one?

**Comment by Muqtxdir** [comment]
hi @iaacornus 

could you tell what the application versions are that you provided in your screenshots?

**Comment by iaacornus** [comment]
they are (in order), gnome text editor, extensions, gnome clocks, gnome calculator, and gnome calendars, all are flatpak, there versions are:

43.0 for all, and 43.0.1 for the gnome calculator.

**Comment by Jupi007** [comment]
Well, this is (sadly) normal @iaacornus.
Libadwaita apps are not aim to be themed.
The Yaru Gtk4 theme is based on the pure Gtk4 one, which is incompatible with Libadwaita apps.

In early times of Gtk4/Libadwaita our theme was based on Libadwaita, but since these apps are blocking the theming feature, this makes no more sense, so we reverted to pure Gtk4.

So sorry, but this mean we can't fix your problem 😕
If you agree @Muqtxdir, I think we can close this issue.

**Comment by iaacornus** [comment]
understandable, thank you for responding, I'll close now the issue. Thank you.
