### ISSUE TITLE
appear gap between bar and window app after unlock screen

### ISSUE THREAD

**Issue by mantarimay** [ubuntu/yaru#3773]
appear gap between bar and window app after unlock screen. if i using adwaita theme gap did not appear.

**System information**
Distro:	openSUSE Tumbleweed 20221119 (GNOME Shell 43.1)

**Yaru version**
gnome-shell-theme-yaru 22.10.3+19~git20221118

**Screenshots**

[ss](https://imgur.com/uVeIp88)

**Comment by mantarimay** [comment]
@Jupi007 here gnome tweak settings [another ss](https://imgur.com/a/aeW4N6X)

**Comment by Jupi007** [comment]
Thanks @mantarimay, on this screenshot you are using yaru everywhere, but there's still a gap...
Maybe the yaru theme isn't used by GDM, and as Adwaita top bar is bigger, it creates a gap when lock/unlock 🤔
What do you think of this @Muqtxdir?

**Comment by Muqtxdir** [comment]
i think there was an issue someone discussed the height top-bar to be reverted to the upstream height, can't seem to remember which one was it.

although I'm not sure about this much of things in gs is not taken into account from the applied theme, so maybe maybe that's why this happens? If it's true then better to revert to upstream height

**Comment by Jupi007** [comment]
Just to be sure, @mantarimay which theme are you use on the login/lock screen?

**Comment by mantarimay** [comment]
@Jupi007 maybe i still using default theme adwaita. i don't understand change this part. 

should i change gdm theme too? or change height bar from yaru theme?

**Comment by Jupi007** [comment]
Imo, the best for you would be to use yaru on the login/lock screen too.
And if you want to check, if you see blue instead of orange on the login screen, it means that you're using Adwaita.

@Muqtxdir do you remember the way to change the GDM theme?

**Comment by mantarimay** [comment]
@Jupi007 i try change theme with this app [Login Manager Settings](https://github.com/realmazharhussain/gdm-settings) Thanks its fix it with using same theme in gnome and gdm.

**Comment by Jupi007** [comment]
I'm glad it worked 🙂
So I think we can close this.
