### ISSUE TITLE
Panel bug in default cinnamon theme.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3781]
When placing the mouse pointer on the apllet in the panel the color is dark in the Yaru theme, the dark variant is ok.
![Captura de tela de 2022-11-28 13-07-13](https://user-images.githubusercontent.com/59381215/204328883-db06a6fd-1216-4fa3-b5c9-1d3c3150b14e.png)
![Captura de tela de 2022-11-28 13-07-26](https://user-images.githubusercontent.com/59381215/204328924-162d7234-dca1-4a9d-9c10-5d77df654f49.png)

**Comment by Jupi007** [comment]
Hi @Initu-Castilhos 
thanks for the report.

I will try to fix that.
I just need to recreate a Cinnamon VM.

Just for information, which version of Cinnamon and Ubuntu are you using?

**Comment by Initu-Castilhos** [comment]
Cinnamon  5.4.12,  Linux Mint 21

**Comment by Initu-Castilhos** [comment]
Thanks!

**Comment by Jupi007** [comment]
You're welcome!

Please just leave the issue open, until the PR is merged.
It will be closed automatically 🙂
