### ISSUE TITLE
Change preferences-system icon

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3800]
Change the preferences-system icon to the gnome-tweaks icon to differentiate the preferences-desktop icon.
![Captura de tela de 2022-12-11 18-28-18](https://user-images.githubusercontent.com/59381215/206930471-62076b29-0d18-49b1-8be1-6dd6892aa3cc.png)
At the moment.

![Captura de tela de 2022-12-11 18-29-47](https://user-images.githubusercontent.com/59381215/206930499-cfa3cc82-fb23-4057-b1f9-a0a70a33b2dc.png)
Proposal.

**Comment by Jupi007** [comment]
That's a good idea 👍
