### ISSUE TITLE
New LibreOffice icons

### ISSUE THREAD

**Issue by fitojb** [ubuntu/yaru#3801]
At the LibreOffice Design team, we have created [new app- and file icons](https://github.com/LibreOffice/core/commit/b24dfa7ef93bc31ed9ccfb3e3472109bbd384b15) for the upcoming 7.5 release, which will be released in February 2023 and will be included in Ubuntu 23.04 Lunar. Please consider refreshing the Yaru-style icons to match. Since we don’t drink the “Please don’t theme our apps!” Kool-Aid, we encourage icon developers to be creative in theming our software :)

**Comment by Jupi007** [comment]
Hi @fitojb,
sorry for the late reply.
We are working one something for our LO icons which is closer to your new icon look 🙂

![Capture d’écran du 2023-02-19 17-29-45](https://user-images.githubusercontent.com/36476595/219961250-a38dce04-7e4a-4c46-9fe0-97da466e8623.png)
