### ISSUE TITLE
Selection-checked still use old checkmark

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3804]
![image](https://user-images.githubusercontent.com/36476595/207942974-febeae83-edfd-434c-8588-c61e17b502c0.png)

**Comment by jotterkain** [comment]
Can you please add some explanation ?

**Comment by Jupi007** [comment]
Please see: https://github.com/ubuntu/yaru_widgets.dart/pull/351, #3791, #3793 🙂
To be short, we replaced this checkmark by an even one in [yaru_widgets.dart](https://github.com/ubuntu/yaru_widgets.dart)

**Comment by jotterkain** [comment]
alright sir
