### ISSUE TITLE
Missing icons: Firefox ESR; ksystemlog

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [ubuntu/yaru#3807]
Just now I installed the icons via Linux Mint's repositories (using Mint 21.1 Cinnamon). The icons look lovely! However, icons seem to be missing for the following programs.

- Firefox extended support release ('ESR')
- ksystemlog

**To reproduce the problem**

Have Mint 21.1.
Install Firefox ESR (via [here](https://www.mozilla.org/en-GB/firefox/all/#product-desktop-esr)).
`sudo apt install ksystemlog`.
`sudo apt install yaru-theme-icon`.
Search Mint's menu for Firefox ESR and ksystemlog.

**Comment by madsrh** [comment]
Sorry for the late reply @LinuxOnTheDesktop 

The icons mentioned are not part of the Yaru icon theme. You could try some of the many derivative works like: https://github.com/Bonandry/yaru-plus

or Yaru Extended 

I'm closing this issue and hope this answer was helpful, although late 😅

**Comment by LinuxOnTheDesktop** [comment]
I add: the 'Mint-Y' versions of Yaru - versions that Linux Mint created, I take it - contain the two missing icons that I mentioned, However, those Mint-Y versions of the theme are more block-y (square) than the original ones and . .  I prefer the original ones.

@madsrh Thank you for your earlier reply. However: if the makers of Yaru want people to keep using the theme, then why do they not add missing icons - at least for relatively common applications?
