### ISSUE TITLE
Yaru-* icons have excessive shadow in their bottom right corner

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#3819]
Fixed for Yaru icons, but not Yaru-*, in https://github.com/ubuntu/yaru/pull/3674

**Expected Behaviour**
Yaru-* icons don't have excessive shadow in their bottom right corners.

**Actual Behaviour**
Yaru-* icons have excessive shadow in their bottom right corners, visible in GNOME Overview.

**Steps to Reproduce the Problem**
1. Change the icon theme to Yaru-bark
2. Open Nautilus
3. Press the Super key to show the Overview in GNOME
4. Observe the shadow of Nautilus icon.

**Yaru version**
```
$ apt show yaru-theme-icon 
Package: yaru-theme-icon
Version: 22.10.3-1
```

**Comment by Jupi007** [comment]
Thanks for the report @Amr-Ibra 
I'll take a look at that :)
