### ISSUE TITLE
LibreOffice Writer icon looks similar to the Files icon

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#3837]
**Expected Behavior**

**Actual Behavior**

The LibreOffice Writer icon looked so similar to the Files icon that I accidentally click on Writer instead of Files.

**Software that presents the issue**

- Ubuntu 23.04
- Yaru 22.10.3-1
- LibreOffice 4:7.5.1~rc2-0ubuntu1

**Screenshots**

![image](https://user-images.githubusercontent.com/876259/222546786-4729702b-0a5b-40b5-b0bc-4642993108fd.png)

See also this comparison screenshot:
https://twitter.com/omgubuntu/status/1629985245704355841

**Comment by Jupi007** [comment]
Hi @jbicha,
thanks for the report.

But it looks like you are using the Adwaita icon theme.
I'm using Yaru, and it looks like this currently:

![image](https://user-images.githubusercontent.com/36476595/222675224-4a78f174-d77d-47d4-9521-a407424e70ed.png)

Writer and files icons are really different in our pack.
So I close this issue, but feel free to ask more question here if needed 🙂

**Comment by jbicha** [comment]
It looks like my system is a bit broken. Thanks for checking and following up!

**Comment by Jupi007** [comment]
You're welcome 🙂
