### ISSUE TITLE
gs: process-working invisible in wifi submenu

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#3890]
ideally `process-working-symbolic` should be same color as text, but that's not the case in light theme: 

| light | dark|
|------ | ------ |
|![Screenshot from 2023-04-15 14-30-23](https://user-images.githubusercontent.com/54065734/232202883-9a3998ce-6f37-4a5f-bd4f-9a8138c880f0.png) | ![Screenshot from 2023-04-15 14-30-32](https://user-images.githubusercontent.com/54065734/232202895-a670df3f-00aa-4f55-be51-e895e656fd00.png) |

**Comment by Feichtmeier** [comment]
then it needs to be specified to not the panel, since our panel is always dark (which might be discussable at some point in the future) :) 
and nice find

**Comment by Jupi007** [comment]
Nice catch!
I'm sure this one will be annoying to fix 😅
I'll try to see what I can do.

**Comment by Feichtmeier** [comment]
Hm another idea would be to make it orange 🧡🍊

**Comment by Jupi007** [comment]
> Hm another idea would be to make it orange 🧡🍊 or primary colour

Hey, that's a really good idea!

**Comment by Jupi007** [comment]
> Are the primary colours possible with meson?

Yes, we can generate colour variant of all asset files.

**Comment by Muqtxdir** [comment]
now that we have light and dark variants of `process-working-symbolic` this is no longer an issue
