### ISSUE TITLE
win10系统无法进入U盘Ubuntu引导界面

### ISSUE THREAD

**Issue by Xbjzjzjzjzjb** [ubuntu/yaru#3902]
please help me
开机U盘是第一选项了

只有Windows10单系统，进不去ubuntu的U盘引导界面

开机按esc键位，ubuntu (faspeed P8-256G PLUS)无法被加载![image](https://github.com/ubuntu/yaru/assets/132755833/b28fd2b2-b641-4bcf-b1d2-fd98a7d06619)

**Comment by Xbjzjzjzjzjb** [comment]
![image](https://github.com/ubuntu/yaru/assets/132755833/61fa0eb0-e191-45c8-8d65-f2fdf11a3c8c)

**Comment by Xbjzjzjzjzjb** [comment]
就是这样按了根本进入不了ubuntu引导界面

**Comment by Muqtxdir** [comment]
hi @Xbjzjzjzjzjb 

this is not the correct repository for the issue you are trying to report about.
