### ISSUE TITLE
 Cinnamon-light theme colors issues.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#3922]
In the light version, the separator and the corner bar are clear and the accent color is orange in all variants.
![Captura de tela de 2023-06-17 12-53-04](https://github.com/ubuntu/yaru/assets/59381215/0391c15b-0c4a-441d-8559-d8ba56732a35)

It might be better to change the panel color to the titlebar color like Mint-Y's cinnamon theme.

**Comment by Jupi007** [comment]
@hsbasu Can you look at the broken accent color generation, please?

**Comment by hsbasu** [comment]
@Jupi007 Sure.

**Comment by hsbasu** [comment]
I think we already discussed this in the following comment.

    @Initu-Castilhos @Jupi007 I get it now. Those colours are coming from the sass files and are not using accent_bg_colour as their base. To modify those colours, the sass files need to be modified. I have cross checked all the colorizable assests are taking accent colour. I would suggest to have a separate commit for them.

_Originally posted by @hsbasu in https://github.com/ubuntu/yaru/issues/3842#issuecomment-1472643009_

**Comment by Jupi007** [comment]
Closed by #3925
