### ISSUE TITLE
Bluetooth icons not centered in indicator panel

### ISSUE THREAD

**Issue by richcarni** [ubuntu/yaru#3945]
**Expected Behavior**

Bluetooth icon spacing matches other icons in indicator panel. (Bluetooth icons in 22x22/panel to have a size of 22 x 22 px)

**Actual Behavior**

The bluetooth icon is set left, producing uneven spacing of my indicator icons (Bluetoth icons are 11 x 22 px)

**Steps to Reproduce the Problem**

Take a fresh install of Ubuntu MATE. If you click and hold on the bluetooth icon (panel, lower right) it will underline the icon and you can see the it is set slightly left

**Software that presents the issue**

mate-panel 1.26.2-1
ayatana-indicator-application 22.2.0-1
OS version: Ubuntu MATE 22.04.2

**Yaru version**

22.04.4

**Screenshots**

![image](https://github.com/ubuntu/yaru/assets/42241043/28306a79-3444-412c-a472-6d50377e18a1)

If I resize the icon(s) to 22 x 22, everything looks good:

![image](https://github.com/ubuntu/yaru/assets/42241043/ac264a71-dc70-472c-9758-b8a86c782f05)

**Comment by Jupi007** [comment]
Hi @richcarni and thanks for the report.
I checked our panel icons, and it looks like many ones doesn't fit a correct canvas size.
I'll try to fix that.

**Comment by Jupi007** [comment]
@richcarni Can you please test this branch (which targets 22.04): https://github.com/ubuntu/yaru/tree/issue3945/fix-panel-icons-canvas/jammy

**Comment by richcarni** [comment]
Thanks @Jupi007! 

I will test and report back

**Comment by richcarni** [comment]
@Jupi007, having trouble building/installing (I'm sure it's something silly on my end)...

The installed icons dir is missing panels (e.g. 22x22 only contains actions, apps. categories and legacy) - I can see it is in the src, but can't figure out why it isn't being installed?

I checked out the branch you linked above and ran meson build and sudo ninja install

**Comment by Jupi007** [comment]
@richcarni I saw you sent then removed a message.

Just in case you still need some help, the `ubuntu-unity` option in `meson_options` needs to be set to `true`.
Then you need to run `meson build --reconfigure` to take this into account.
And finally run `sudo ninja install`.

**Comment by richcarni** [comment]
Thanks for the assistance @Jupi007 - I did figure it out, hence deleted the message

The only icon I noticed an issue with was the bluetooth, and that looks good now

You're right that a number of other icons also aren't the correct size (or at least match their folder size)

My scan through all the panel folders found the following with non-square aspect ratios. I guess all the ones you fixed would also need their dark counterpart fixed. Not sure about the others

```
./Yaru/22x22/panel/language.svg:viewBox="0 0 23 22
./Yaru/22x22/panel/steam_tray_mono.svg:viewBox="0 0 256 259
./Yaru/22x22/panel/tray-new-im.svg:viewBox="0 0 20 22
./Yaru/22x22/panel/user-available-panel.svg:viewBox="0 0 20 22
./Yaru/22x22/panel/user-away-panel.svg:viewBox="0 0 20 22
./Yaru/22x22/panel/user-busy-panel.svg:viewBox="0 0 20 22
./Yaru/22x22/panel/user-idle-panel.svg:viewBox="0 0 20 22
./Yaru/22x22/panel/user-invisible-panel.svg:viewBox="0 0 20 22
./Yaru/22x22/panel/user-offline-panel.svg:viewBox="0 0 20 22
./Yaru/24x24/panel/steam_tray_mono.svg:viewBox="0 0 256 259
./Yaru-dark/22x22/panel/a11y.svg:viewBox="0 0 18 22
./Yaru-dark/22x22/panel/ac-adapter-symbolic.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/account-logged-in.svg:viewBox="0 0 18 22
./Yaru-dark/22x22/panel/bluetooth-active.svg:viewBox="0 0 11 22
./Yaru-dark/22x22/panel/bluetooth-disabled.svg:viewBox="0 0 11 22
./Yaru-dark/22x22/panel/bluetooth-paired.svg:viewBox="0 0 11 22
./Yaru-dark/22x22/panel/deluge-panel.svg:viewBox="0 0 11 22
./Yaru-dark/22x22/panel/gpm-primary-000.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/gpm-primary-020.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/gpm-primary-040.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/gpm-primary-060.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/gpm-primary-080.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/gpm-primary-100.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/gtk-dialog-authentication-panel.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/krb-expiring-ticket.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/krb-no-valid-ticket.svg:viewBox="0 0 14 22
./Yaru-dark/22x22/panel/language.svg:viewBox="0 0 23 22
./Yaru-dark/22x22/panel/network-receive.svg:viewBox="0 0 13 22
./Yaru-dark/22x22/panel/network-transmit-receive.svg:viewBox="0 0 13 22
./Yaru-dark/22x22/panel/network-transmit.svg:viewBox="0 0 13 22
./Yaru-dark/22x22/panel/nm-vpn-standalone-lock.svg:viewBox="0 0 18 22
./Yaru-dark/22x22/panel/steam_tray_mono.svg:viewBox="0 0 256 259
./Yaru-dark/22x22/panel/tray-new-im.svg:viewBox="0 0 20 22
./Yaru-dark/22x22/panel/user-available-panel.svg:viewBox="0 0 20 22
./Yaru-dark/22x22/panel/user-away-panel.svg:viewBox="0 0 20 22
./Yaru-dark/22x22/panel/user-busy-panel.svg:viewBox="0 0 20 22
./Yaru-dark/22x22/panel/user-idle-panel.svg:viewBox="0 0 20 22
./Yaru-dark/22x22/panel/user-invisible-panel.svg:viewBox="0 0 20 22
./Yaru-dark/22x22/panel/user-offline-panel.svg:viewBox="0 0 20 22
./Yaru-dark/24x24/panel/gpm-primary-000.svg:viewBox="0 0 17 24
./Yaru-dark/24x24/panel/gpm-primary-020.svg:viewBox="0 0 17 24
./Yaru-dark/24x24/panel/gpm-primary-040.svg:viewBox="0 0 17 24
./Yaru-dark/24x24/panel/gpm-primary-060.svg:viewBox="0 0 17 24
./Yaru-dark/24x24/panel/gpm-primary-080.svg:viewBox="0 0 17 24
./Yaru-dark/24x24/panel/gpm-primary-100.svg:viewBox="0 0 17 24
./Yaru-dark/24x24/panel/steam_tray_mono.svg:viewBox="0 0 256 259
```

**Comment by Jupi007** [comment]
Thanks a lot for the analysis @richcarni 
I fixed all the icons, and did two PRs one for `master` and a backport for 22.04.

Btw, can you fill a bug on Launchpad: https://bugs.launchpad.net/ubuntu/+source/yaru-theme
So we can backport the patch.

**Comment by richcarni** [comment]
Launchpad bug report: [https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/2029175](https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/2029175)

Thanks for your work on this, love the theme!

**Comment by Jupi007** [comment]
Thank you very much @richcarni
