### ISSUE TITLE
More folder categories

### ISSUE THREAD

**Issue by jrom99** [ubuntu/yaru#3946]
**Icon Request**

I'd like to request folders icons for games, personal, programming/coding, school, books and (web)sync categories. They are a nice way to improve Nautilus look!

For the sync folder icon, I saw that there is a `folder-dropbox` icon, but I think a general one may be easier to implement, since there are other syncing software available that create folders (megasync, onedrive...).

I use this script to change a folder icon, and it'd be really nice to have other categories to choose from.
```bash
gio set -t string "$SELECTED_FOLDER" metadata::custom-icon-name "folder-${SELECTED_TYPE}"
```

**Steps to locate the icon**

Not applicable.

**Software where the icon is missing**

- Name: Nautilus
- Version: GNOME nautilus 44.2.1
- OS version: Ubuntu 23.04

**Screenshots**

These are the general folder icons:

![image](https://github.com/ubuntu/yaru/assets/47498278/2e4512b6-0818-4c34-8a7d-555fdce1834e)

These are the other folders that I want icons to:

![image](https://github.com/ubuntu/yaru/assets/47498278/4fa1e345-e173-414a-8f1f-661b16800dbb)

**Comment by Jupi007** [comment]
Hi @jrom99,
Thank you for creating this issue.

Sadly, I don't think we'll be able to respond to your request.
I currently have very few time, and a lot of important things to do.

Adding all these new icons will take a lot of time and will make the maintenance job more complex. We already have a lot of folder icons, and each time a change is required, it is already a pain.

I hope you understand my position :)

CC @Feichtmeier @madsrh @Muqtxdir
