### ISSUE TITLE
`.sudo_as_admin_successful` and `core` icon is very low resolution

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#3948]
**Steps to Reproduce the Problem**
1. Open nautilus
2. Go to the user folder `/home/USER`
3. Observe the `.sudo_as_admin_successful` icon
![sudo_as_admin_successful](https://github.com/ubuntu/yaru/assets/45657128/25eeae9a-d451-4e52-b6fe-9c102c3836a7)
4. Go to the root folder `/`
5. Observe the `core` icon (same icon)
![core](https://github.com/ubuntu/yaru/assets/45657128/0f4a9b81-b222-4472-ac65-d5490dc7b4ad)

**Software that presents the issue**
- nautilus 44.2.1
- Debian testing

**Yaru version**
- yaru-theme-icon 23.04.4

**Comment by Jupi007** [comment]
Hi @Amr-Ibra,
thanks a lot for your report.

It looks like we miss the `application/x-zerosize` mimetype.
