### ISSUE TITLE
@coburn: I strenuously object to the gray LibreOffice-main icon

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#3952]
### Discussed in https://github.com/ubuntu/yaru/discussions/3941

<div type='discussions-op-text'>

<sup>Originally posted by **Coburn** July 13, 2023</sup>
I'm sure there is a rationale for the change of the LibreOffice-main icon from white to four shades of gray. But to me, it is ugly. My wife works at a copy center, and when we see a clean, white, pristine page with gray smudges, we know the toner is out of control. It says "dirty" to me, and "throw this away." The thought that goes through my mind when I see that icon is, "something is wrong." Probably because a grayed-out icon means just that. But when I see a white page, I think "creativity" and "blank slate." I remember what my mom said, "If it is to be, it is up to me," and "a blank page is a writer's canvas." A white page inspires me.

For now, I am going to hack the icon set and install it with the old icon, just for myself. Your other icons are great. I can't see using any other set. But could you please re-evaluate your design choices, and perhaps reserve the grayed-out icon for the pre-release? I know I would appreciate it. Thanks.
![libreoffice-main](https://github.com/ubuntu/yaru/assets/2658123/1089d638-6a39-4861-9d48-fc33961e29f7)
</div>

**Comment by Muqtxdir** [comment]
Id like to also add that on screens with lower-resolution and not great contrast, the icon may sometimes be hard to identify when in overview

**Comment by Jupi007** [comment]
I think you're right :)
I'll revert the white page.
