### ISSUE TITLE
Ubuntu camera [cheese]  problem 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [ubuntu/yaru#3958]
**Expected Behavior**

Whenever i open the camera  it first open for seconds  and then close automatically. 
I faced  lot's of issue in  this. I  login to the ubuntu22.04 through the dual boot.

**Comment by Jupi007** [comment]
Hi @Vikash-8090-Yadav 
I'm sorry but this repository is only related to the Yaru theme.
You should ask some support forum.
