### ISSUE TITLE
Thunderbird snap wont use yaru accents

### ISSUE THREAD

**Issue by capecrusader-121** [ubuntu/yaru#3976]
**Expected Behavior**

Get proper lovely orange accent of yaru within the thunderbird snap.
**Actual Behavior**

The app is full blueish and adwaita.
**Steps to Reproduce the Problem**

1) Install thunderbird snap latest/use yaru-theme.
2) Open the app and get your eyes washed up with adwaita blue instead of yaru orange.

**Software that presents the issue**

- Thunderbird Snap
- Version: Latest
- OS version: Ubuntu 22.04.1

**Yaru version**

 Version: 22.04.5

**Screenshots**

I would love to put but hey there is a privacy issue, i will later update if i can get a pic.  

**Upstream check**

Nope, nothing special same.

**Comment by Feichtmeier** [comment]
yep noticed the same. this is sadly not fixable here though :/ 

seb from the desktop team has opened an issue at thunderbird
https://discourse.ubuntu.com/t/thunderbird-supernova/36996/11
