### ISSUE TITLE
GS45 theme review

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3982]
I create this issue to track the problems and todo things of the GS theme.

### Wrong focus ring color - fixed by #3989

![Capture d’écran du 2023-09-05 10-01-19](https://github.com/ubuntu/yaru/assets/36476595/5d485a46-7041-4b19-a4b4-abdcc6c73027)

### Quick toggles are "eye burning"

![Capture d’écran du 2023-09-05 10-01-31](https://github.com/ubuntu/yaru/assets/36476595/909763ba-2ecb-45f3-802d-f3fc73b64f21)
![image](https://github.com/ubuntu/yaru/assets/36476595/ab66a952-3565-4490-ad56-45cd24d844ac)

### Revert top bar to upstream size - fixed by #3990

![Capture d’écran du 2023-09-05 10-02-05](https://github.com/ubuntu/yaru/assets/36476595/2a8403e1-5a4d-49b4-b337-271d8ce05157)

### Light theme inputs background is weird - fixed by #3994

![Capture d’écran du 2023-09-05 10-05-21](https://github.com/ubuntu/yaru/assets/36476595/43552087-082c-4e33-97fa-bb145cc6dcc7)

### Sound volume slider thumb border is cropped - fixed by #3992

![Capture d’écran du 2023-09-05 10-08-31](https://github.com/ubuntu/yaru/assets/36476595/f4e73c79-8bd3-44e4-924c-cbfe3afb80d4)

_BTW the track color isn't use the correct color shade, it looks toned down_ - fixed by #3993

**Comment by Feichtmeier** [comment]
I think also the inner border-radii of elements inside the shell popups were also too large compared to our yaru outer radius of the popups

**Comment by 3v1n0** [comment]
One more.... :)

![image](https://github.com/ubuntu/yaru/assets/345675/20865d93-2d3a-4ab4-91bc-4955a4edc996)

The extensions page on looking-glass is broken when using the light theme.

**Comment by Feichtmeier** [comment]
> One more.... :)
> 
> ![image](https://github.com/ubuntu/yaru/assets/345675/20865d93-2d3a-4ab4-91bc-4955a4edc996)
> 
> The extensions page on looking-glass is broken when using the light theme.

Classic! I don't know how often we've been to looking glass xD

**Comment by Jupi007** [comment]
@3v1n0 I created a PR: #4009

**Comment by fthx** [comment]
Hi all,

[Noble]

Bad switches circle alignment.
![image](https://github.com/ubuntu/yaru/assets/23138504/2cd9a976-41ee-436e-9b57-dc18355cbd47)

Bad selection alignment (here Firefox)
![image](https://github.com/ubuntu/yaru/assets/23138504/c359362b-625e-4f5d-a96a-9e428583e624)

(here Nautilus)
![image](https://github.com/ubuntu/yaru/assets/23138504/e56811f9-aa82-43cd-b34c-fd05b23866be)

**Comment by Jupi007** [comment]
@fthx Thanks for your comment.

On your first and last screenshots, the app is using Libadwaita, so we have no control over the theming.
But to be honest, I can't notice what is the problem for each of your screenshot 😅

Also, this issue is related to the Gnome Shell theme and not the Gtk one 🙂

**Comment by Jupi007** [comment]
Btw, I think we can close this issue.

**Comment by fthx** [comment]
Mmmh. Ok if I have to request this through GS gitlab or whatever, but there IS a problem. ;-)

First one. Here I use Noble with GNOME/Adwaita.
![image](https://github.com/ubuntu/yaru/assets/23138504/b126c2c2-0652-4fbb-ae4b-ea620a3f74ba)
The switch blue button is not very well centered but better than Yaru's orange one.

Second one. Firefox then Nautilus.
![image](https://github.com/ubuntu/yaru/assets/23138504/2a27e40b-d337-477b-b03a-192c36c4372c)
![image](https://github.com/ubuntu/yaru/assets/23138504/8b671209-330b-476b-a017-c40c0dbd4949)
The blue selection is centered, the / is not touching the border. That's not the case using Yaru.

**Comment by Feichtmeier** [comment]
firefox uses their own way to look up our theme, but it is def. not gtk4
some things come from gtk3 as far as I remember
the orange and the white thing could be an optical illusion. white inside bright orange is always problematic

**Comment by Jupi007** [comment]
Also, you are using a different font on your screenshots with Adwaita, Cantarell I suppose.
The "y" letter is clearly longer and the "/" is shorted using Cantarell compared to the Ubuntu font.

**Comment by fthx** [comment]
Yes I did remove my glasses and came very near by my screen and you're right, that's an optical illusion for both orange and blue. But I see it much less in blue.
For the selection too, you're right, GNOME session did not use my previous Ubuntu font!!
My bad.
So first one no issue.
Second one maybe Ubuntu fonts issue.

**Comment by Jupi007** [comment]
Also, you can see that the switch thumb is equidistant to each edge of 2px 🙂

![Capture d’écran du 2023-11-18 12-05-28](https://github.com/ubuntu/yaru/assets/36476595/3cc138cc-fd9d-4d25-8eea-d1a832059b73)

**Comment by fthx** [comment]
Yes that's what I saw at 2cm of my 27 inches screen :-).
