### ISSUE TITLE
Add icons cs-icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [ubuntu/yaru#4013]
Add icons to Cinnamon settings (cs-icons). There is this zip file for a sample.
[src.zip](https://github.com/ubuntu/yaru/files/13993000/src.zip)

Another example is this Ubuntu Cinnamon link on github.
https://github.com/ubuntucinnamon/ubuntucinnamon-environment

**Comment by hiirrxnn** [comment]
Can i work on this ?

**Comment by Initu-Castilhos** [comment]
> Posso trabalhar nisso?

The src files are ready, they just need to be inserted during installation

**Comment by Muqtxdir** [comment]
@hiirrxnn this issue is assigned to you now,

**Comment by hiirrxnn** [comment]
Can you elaborate on what exactly am i supposed to do ?
