### ISSUE TITLE
Ubuntu logo shifts vertically when the login screen appears

### ISSUE THREAD

**Issue by xnox** [ubuntu/yaru#4019]
**Expected Behavior**

gnome-shell login-dialog uses a logo at the bottom of the screen which is the same file as the one use by plymouth

I expect the logo to remain on screen in the same place.

**Actual Behavior**

Plymouth positions the logo 96% on the vertical screen:
```console
$ grep Watermark /usr/share/plymouth/themes/bgrt/bgrt.plymouth 
WatermarkHorizontalAlignment=.5
WatermarkVerticalAlignment=.96
```
yaru-themes positions the logo with margin 24px or 3em (depending on version)

https://github.com/ubuntu/yaru/blob/77d2d5ddedc00efd24f3bb2464efc689d6891b96/gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss#L40C1-L42C2

```css
.login-dialog-logo-bin {
  margin:3em 0;
}
```

**Steps to Reproduce the Problem**

when 3em is not 4% of the screen height the logo will shift on screen.

**System information**

Jammy & Mantic have this problem

**Yaru version**

Jammy & Mantic have this problem

**Screenshots**

I don't know how to make them of the login screen. It is possible to run plymouth emulator

**Upstream check**

It does happen with upstream themes, as by default gnome spinner theme does not use a watermark logo in plymouth, and we do. Upstream solution is to "fade-in" watermark logo only once the login screen appears to avoid trying to line up the two logos.

**How to fix it**

Plymouth doesn't know what 3em is, it knows display dimentions, and scaling, and calculates absolute position on screen at 96% of vertical space.

This is tricky, i've tried changing gnome-shell css to say something like 

```css
.login-dialog-logo-bin {
  margin:4% 0;
}
```
But that doesn't work, because it ends up as 0% as it seems like the login-dialog-logo-bin has no idea what the outer space size is, and thus fails to calculate 4%. In gnome-shell javascript I have also failed to calculate what the total screen size is for each display to position the logo right.

Another alternative is to literary patch the logo to have free transparent margin around it, and just place it at the bottom of the screen. But then every ubuntu flavour would have to do that if they use gnome-shell & plymouth.

Another alternative is to patch both gnome-shell and plymouth to maybe pad the logo based on the dimensions of the logo (i.e. 10% of the rendered scaled logo) which should be screen independent.

I am at a loss here, but happy to help with patching plymouth / gnome-shelll / yaru-themes to make it work.

**Comment by Feichtmeier** [comment]
Thanks @xnox 

@Muqtxdir I know I started the plymouth theme years ago but I think you polished it. Where is the current code at? 😆

**Comment by Muqtxdir** [comment]
hi @xnox 

I apologize for such a late reply. my personal preference here would be to have the same behavior as that of upstream as it would not require to maintain patch but if you feel the patches to plymouth and yaru-theme would be a better option, then I am fine with that approach as well.

**Comment by xnox** [comment]
> hi @xnox
> 
> I apologize for such a late reply. my personal preference here would be to have the same behavior as that of upstream as it would not require to maintain patch but if you feel the patches to plymouth and yaru-theme would be a better option, then I am fine with that approach as well.

there is no upstream behaviour to match here. In plymouth "upstream" they choose not to show logo on the bottom, and only make it fade in gdm on the bottom. Thus whichever placement of the distro logo on the bottom in gdm is, is what is "standard".

In our plymouth we do show distribution logo on the bottom & override gdm to not do fade-in and be in almost the same location.

But because said location is calculated differently there is jumping jitter in vertical placement of the logo between gdm and plymouth.

The two calculations are different, and I'm failing to figure out how I can match one calculation to the other, due to lack of CSS knowledge. (ie. change plymouth calculation, or change gdm3 and/or yaru css calculation, or change both of them).

**Comment by xnox** [comment]
With noble, I believe this is impossible to fix, as plymouth and gnome-shell have different opinions about the screen topology, scaling, fractional scaling, on per screen basis thus one can match it perfectly in like VM but not on any real laptop (anything modern with high dpi screens).

Instead I will move the plymouth logo out of the way as a bookmark, such that the transition is intentionally jumpy. This also means we can turn back on the stock upstream fade-in of the gnome login shell.

**Comment by xnox** [comment]
Fixed in plymouth via https://launchpad.net/ubuntu/+source/plymouth/24.004.60-1ubuntu2

But this now also means, that we can turn on "fade-in" of the watermark logo back on (stock gnome behaviour) too.

**Comment by vanvugt** [comment]
The Ubuntu bug for this is https://bugs.launchpad.net/bugs/1872594
