### ISSUE TITLE
White-on-white colors when editing a folder's name in the "Applications" screen

### ISSUE THREAD

**Issue by evacks** [ubuntu/yaru#4047]
**Expected Behavior**
While renaming an application folder the color of the folder's name while it's being edited and the background of the text field during the editing process should be easily distinguishable 

**Actual Behavior**

I tried to rename an application folder - initially the name was highlighted and displayed correctly but there was white-on-white contrast when I tried to edit the name

**Steps to Reproduce the Problem**

1. Click on "Show Apps" 
2. Select an applications folder and hit the "edit button"
3. Attempt to edit the name

**System information**

Shell version: 45.2
Ubuntu 23.10

**Yaru version**
Version: 23.10.0-0ubuntu2

**Screenshots**
![image](https://github.com/ubuntu/yaru/assets/106621171/61e09ea6-fed3-4ffb-90a5-3083dcb1ba03)

**Comment by Jupi007** [comment]
Hi @evacks and thanks for the report.
I can confirm the problem...

**Comment by Muqtxdir** [comment]
closing as this is not the case with the latest changes from `master`
