### ISSUE TITLE
Missing icon: GNOME Snapshot

### ISSUE THREAD

**Issue by vitalkanev** [ubuntu/yaru#4084]
**Icon Request**

We're missing icon for GNOME Snapshot, a new camera app that replaces Cheese in Nobel.

`/usr/share/applications/org.gnome.Snapshot.desktop` reports the following:
```
Icon=org.gnome.Snapshot
```

**Steps to locate the icon**

1. Install Ubuntu 24.04 LTS (I have a RC image from `20240422.1`) with Full Install option
2. Open the Applications menu
3. Look for "Camera" tile
4. Observe default icon

**Software where the icon is missing**

GNOME Snapshot (package `gnome-snapshot`) version `46.2-1ubuntu2`

As I said, installed by default.

**System Info**

`apt policy yaru-theme-icon` returns version `24.04.2-0ubuntu1`

`lsb_release -a` returns `Ubuntu 24.04 LTS`

**Screenshots**

![appgrid](https://github.com/ubuntu/yaru/assets/18398761/bbeb901d-9296-4b39-a3b1-549f048276d9)
![aboutbox](https://github.com/ubuntu/yaru/assets/18398761/f831842b-7017-48fd-bd7b-e816d96e65c3)

My icon suggestion (if there is gonna be an SRU or something): Symlink whatever Cheese uses to this icon

**Comment by ubuntujaggers** [comment]
Hi all,

We do have an icon that we could symlink:

![image](https://github.com/user-attachments/assets/a50b21cd-bb46-4dff-b421-d5531f56b424)

...unless anyone wants to rework the Yaru icon so it follows the design of the Gnome one more closely? I.e., a circular icon that focusses more on the lens?

**Comment by Muqtxdir** [comment]
closed with #4159
