### ISSUE TITLE
Setting theme to brown sets GTK theme & icon theme to blue

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#4107]
- gnome-control-center 1:47~beta-2ubuntu2
- gnome-shell 47~beta-1ubuntu2
- gsettings-desktop-schemas 47~beta-1ubuntu2
- libadwaita 1.6~beta-1ubuntu2
- xdg-desktop-portal-gnome 47~beta-1
- yaru-theme 24.10.1-0ubuntu
- Ubuntu 24.10

After installing all the above and logging out and back in…

1. Open the Settings app (gnome-control-center)
2. In the sidebar, click Appearance
3. Change the accent color to Brown
4. Open a terminal and run the following gsettings commands:

```
gsettings get org.gnome.desktop.interface accent-color
gsettings get org.gnome.desktop.interface gtk-theme
gsettings get org.gnome.desktop.interface icon-theme
```

What happens
----
I get these results when my color-scheme is set to dark (using the default doesn't really matter)

```
'brown'
'Yaru-blue-dark'
'Yaru-blue-dark'
```

What I expected
---
My theme is also set to the brown version of the GTK and icon themes

**Comment by 3v1n0** [comment]
Handled via portal changes.
