### ISSUE TITLE
My Initial Take on Gnome Software Icon

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#4156]
### Discussed in https://github.com/ubuntu/yaru/discussions/4155

<div type='discussions-op-text'>

<sup>Originally posted by **ochi12** November  9, 2024</sup>
This concept design is derived from the app-center icon.
I was supposed to put this to my ![YaruX](https://github.com/ochi12/YaruX) repo but I designed it to be a dependency for Yaru so there is no way I can override the default gnome-software icon without manually removing and replacing this icon in my Yaru install. 

One thing I can say is the old gnome-software logo generally look ugly(at least for me). I see it as a briefcase instead of a shopping bag.

I didn't started 16, 24, 32, 48 sizes and symbolic yet since I don't know yet if this will go anywhere

## NEW
![image](https://github.com/user-attachments/assets/6d20c118-30fc-446c-9251-eb388bdedf9e)

## CURRENT
![image](https://github.com/user-attachments/assets/79fb169e-74b2-43de-ac64-57d20da69386)

</div>

**Comment by Muqtxdir** [comment]
hi, I like it. looks good and similar to app center icon
