### ISSUE TITLE
Missing mimetype icon for Typst source files

### ISSUE THREAD

**Issue by t-rapp** [ubuntu/yaru#4180]
Currently source files for [Typst documents](https://github.com/typst/typst) use the generic text mimetype icon in Ubuntu. It would be nice to add distinct icons for these files to better tell them apart in file-manager applications.

Typst source files use the `*.typ` file extension, and are detected as mime-type "text/x-typst" (tested with Ubuntu 24.04.1).

**Comment by t-rapp** [comment]
![text-x-typst_256px](https://github.com/user-attachments/assets/e8072332-75d5-4928-b567-5be1f60d4f16)

This would be my proposed icon based on the "t" shape and color of the Typst logo. If that looks ok I can create a PR with the source SVG plus rendered PNGs.

**Comment by reknih** [comment]
Thank you for opening this PR, we at Typst would be delighted to have a default icon in Ubuntu!

Two remarks though:
- The MIME type we use for typst is `text/vnd.typst`. We do this to be consistent with [RFC 6838's section 3.2](https://datatracker.ietf.org/doc/html/rfc6838#section-3.2) on vendor subtrees. In particular, section 3.4 disallows the `x-` prefix for new MIME types. We use this across our web application.
- The `t` logotype does not look centered on the page. IMO it should be further on the left.

**Comment by Feichtmeier** [comment]
> ![text-x-typst_256px](https://github.com/user-attachments/assets/e8072332-75d5-4928-b567-5be1f60d4f16)
> 
> This would be my proposed icon based on the "t" shape and color of the Typst logo. If that looks ok I can create a PR with the source SVG plus rendered PNGs.

IMO its looking good 👍😊 
PR would be appreciated

**Comment by t-rapp** [comment]
@reknih: Thanks for joining the discussion and your positive feedback!

> The MIME type we use for typst is `text/vnd.typst`. We do this to be consistent with [RFC 6838's section 3.2](https://datatracker.ietf.org/doc/html/rfc6838#section-3.2) on vendor subtrees. In particular, section 3.4 disallows the `x-` prefix for new MIME types. We use this across our web application.

From what I can see other icons (like RAR) are registered for both mimetypes, with `x-` and `vnd.` prefixes, by using symlinks. So I will add a symlink "text/vnd.typst" additionally to "text/x-typst" for future compatibility. Note that the mimetype is already detected as "text/x-typst" on Ubuntu, not sure which upstream repo is responsible for that.

> The `t` logotype does not look centered on the page. IMO it should be further on the left.

The checkerboard-style overlay (which is part of the general icon theme style) should divide the four quadrants of the icon perfectly. My main template for logo positioning was the icon for [Vala source files](https://github.com/ubuntu/yaru/blob/master/icons/Yaru/256x256/mimetypes/text-x-vala.png).

**Comment by madsrh** [comment]
> The t logotype does not look centered on the page. IMO it should be further on the left.

+1

> The checkerboard-style overlay (which is part of the general icon theme style) should divide the four quadrants of the icon perfectly. My main template for logo positioning was the icon for [Vala source files](https://github.com/ubuntu/yaru/blob/master/icons/Yaru/256x256/mimetypes/text-x-vala.png).

There's a difference between mathematically centering the letter and what optically feels balanced. I'm +1 for nudging this a bit to the left. You can read more here: https://blog.kleinpixelagency.com/perfect-your-designs-with-imperfection-guide-to-optical-alignment-f76999b5d62d

**Comment by t-rapp** [comment]
Found out that Inkscape allows to determine the "Center of Mass" point of a path node using the "Extensions ▸ Visualize Path ▸Measure Path" dialog. Moved the letter to the left until that mass center point was left of the mathematical center. I did not move the checkerboard overlay, though. I think the overall alignment looks better now:

![text-x-typst_v2_256px](https://github.com/user-attachments/assets/0251f5d1-a28f-483c-84bd-38d58609e74a)

**Comment by madsrh** [comment]
@t-rapp 🥳 Looks great. 

A PR for this version would be much appreciated.

**Comment by ochi12** [comment]
> Found out that Inkscape allows to determine the "Center of Mass" point of a path node using the "Extensions ▸ Visualize Path ▸Measure Path" dialog. Moved the letter to the left until that mass center point was left of the mathematical center. I did not move the checkerboard overlay, though. I think the overall alignment looks better now:
> 
> ![text-x-typst_v2_256px](https://private-user-images.githubusercontent.com/20061583/395156468-0251f5d1-a28f-483c-84bd-38d58609e74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTI5NTksIm5iZiI6MTczNDA1MjY1OSwicGF0aCI6Ii8yMDA2MTU4My8zOTUxNTY0NjgtMDI1MWY1ZDEtYTI4Zi00ODNjLTg0YmQtMzhkNTg2MDllNzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAxMTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NDFkMDIxOGRiNDEwNTQ0MWQyNDk4MGVmNmI1NTVhZmM2ZmIxZTM4YTk0ZjJjMzMzZmU2NzNmOGE4ZDk3NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8FMWXd5u-4pf8nGbTAr5b2RjrZ9nOglXvNbIwbT82lE)

I think we need some optical compensation on this

**Comment by madsrh** [comment]
@ochi12 I know that there's no real guidelines, but I would prefer to keep the white background. We had [a discussion](https://github.com/ubuntu/yaru/discussions/3474) a long time ago. This is what we aim for:

Proprietary or branded formats can use the branding, including colour. 
Files that are primarily opened or viewed as text have a white backplate with subtle watermark (because we want the icon to resemble a page in a document).
