### ISSUE TITLE
Folder highlight in nautilus is too much

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/yaru#43]
Selected folders in Nautilus look red with the Suru icon theme.

**Comment by clobrano** [comment]
Mads opened a bug on Nautilus to support a better folder selection https://gitlab.gnome.org/GNOME/nautilus/issues/202. The good is that there is an experimental feature (selectable in settings) that improves a lot this experience

![image](https://user-images.githubusercontent.com/2883614/34866641-840f9870-f77d-11e7-92a4-0bc2776a7961.png)

**Comment by didrocks** [comment]
If it's only a gsettings key to change, we can do this in the ubuntu session without any problem.

**Comment by clobrano** [comment]
Yes! It's

gsettings set org.gnome.nautilus.preferences use-experimental-views true

**Comment by didrocks** [comment]
Ok, I've looked at the code that is enabled via this option. I'm not really confortable enabling this on the LTS on the default session (if we switch this theme by default) as the code is indeed still new, not really tested and quite different from what we tested on for long.
No worry to do that in the separate session though. Let me add a PR for this.

**Comment by madsrh** [comment]
The current design has a white overlay on hover that doesn't work well with textfiles and other bright icons. Perhaps the orange filename outline on hover could work?

The selected icon is still colored outside the icon. @godlyranchdressing would this be possible?
![image](https://user-images.githubusercontent.com/3986894/35128733-6790f672-fcb8-11e7-988d-9cfda95bd223.png)

**Comment by madsrh** [comment]
Like this - only with changes to the hover state:

![hover](https://user-images.githubusercontent.com/3986894/35306159-b653054c-009c-11e8-88f3-c7c4b4e7726c.gif)

As the issue title says, the colored icon is too much. Would it be be easy enough to spot the selected file without it? (it seems that icons on the 17.10 desktop works this way)

**Comment by didrocks** [comment]
+1 on not "oranging" the icon. I think as well that on some icons, the selected color overlay can render especially badly.

**Comment by madsrh** [comment]
@clobrano and @godlyranchdressing I see that Nautilus has changed as [suggested by Carlo](https://github.com/Ubuntu/gtk-communitheme/issues/43#issuecomment-357177917). Do you think we could give [the above a try](https://github.com/Ubuntu/gtk-communitheme/issues/43#issuecomment-359972944)? In the gif it's none, hover _(1 or 2px not sure)_, selected

**Comment by clobrano** [comment]
fixed by #173

**Comment by madsrh** [comment]
> I'm not really comfortable enabling this on the LTS on the default session

@didrocks With 18.10 not being an LTS, can we use the experimental view feature mentioned above? 😃

**Comment by madsrh** [comment]
Carlos Soriano writes:
> ...The new views won't be entirely ready for 3.30 and probably neither 3.32, so I recommend finding other solutions.

But that's fine if we can tweak the current a bit I would be very happy with that also. 
@clobrano could we try one of the following (imagine the cursor 🙄 ). I really don't think the icon should change **at all** - it still looks weird on white document icons.

Hover gray:
![hover](https://user-images.githubusercontent.com/3986894/39621109-d874396c-4f8d-11e8-9d05-0a7e1c4e62a5.gif)

Orange border:
![hover_orange](https://user-images.githubusercontent.com/3986894/39621120-e049af3c-4f8d-11e8-9176-3e65c5708ced.gif)

**Comment by clobrano** [comment]
I asked help on IRC, since I can't find how to trigger changes on hover only

**Comment by madsrh** [comment]
Sad 😢 Do you mean that there's no way of removing the icon hover or do you mean that there's no way to add the label hover? 

But basically you're saying that non of the above is possible?

**Comment by clobrano** [comment]
> But basically you're saying that non of the above is possible?

correct, on hover we can't do nothing

**Comment by madsrh** [comment]
@clobrano I know that there's some technical limitentations at play here, but would it be possible to remove the orange selection color here and add the only label like below?

![image](https://user-images.githubusercontent.com/3986894/72207862-e6350b80-349c-11ea-919e-b02ff2745034.png)

**Comment by clobrano** [comment]
Looking at the messages above, it seems that only hover was a problem. I'll try

**Comment by madsrh** [comment]
With that hope that this could be fixed before UI freeze for 20.04 🙏 👼

**Comment by clobrano** [comment]
I had a look at this already, but very rapid, and I couldn't find a solution :disappointed:
