### ISSUE TITLE
Maybe headerbar text buttons shouldn't be flat?

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/yaru#474]
This is the last time I'll bring this up. If we reach a consensus I'll drop it forever but I'm not a fan of the border around text buttons. I get the need for it, but it looks like something went wrong. So what if we excluded text buttons from being flat? In the mockup I used $hb_pathbar_bg to have them look consistent with the pathbar/stackswitcher buttons.

![finalboss](https://user-images.githubusercontent.com/27529229/40432337-73ef34ee-5e77-11e8-92bb-47a39217af3a.png)

Compared to the current:

![button-border](https://user-images.githubusercontent.com/27529229/40432686-43a6d340-5e78-11e8-99b9-a08e47a763e4.png)

**Comment by madsrh** [comment]
Yes +1 I suggested this a long time ago

**Comment by Feichtmeier** [comment]
Isn't the contrast between text-btns and image btns a bit harsh then?
What about using the border we have for text-btns for every btn instead?
Like a flat version of adwaita
![image](https://user-images.githubusercontent.com/15329494/40434311-654068be-5eae-11e8-8dca-6c3ce0e4cf30.png)

**Comment by Paz-it** [comment]
I'm with you about it @clobrano ! Make them all flat 3d...Lets squire the circle!!! :))
I think @Feichtmeier   is right in the middle. I tend to agree with him about it. 
Another mockup maybe will help to clarify.

**Comment by clobrano** [comment]
:D to be clear, I prefer them flat

**Comment by godlyranchdressing** [comment]
Flatter suggestion, basically [this](https://github.com/ubuntu/gtk-communitheme/issues/152#issuecomment-368325780) but with a border:

![flatter](https://user-images.githubusercontent.com/27529229/40436073-2363496c-5e80-11e8-91ec-d6361bb2a3ba.png)

```
.text-button:not(.suggested-action):not(.destructive-action) { 
    @each $state, $t in (all the buttons) {
        &#{$state} { @include button($t, $hb_pathbar_bg, $tc, $flat:true); border: 1px solid _border_color($hb_pathbar_bg) } 
    }
}
```

Also another example since the combination of buttons in Gedit (which IIRC was what prompted the decision to add the border?) is a little odd. The headerbar doesn't look that cluttered with every app:

![settings](https://user-images.githubusercontent.com/27529229/40440397-f38897f4-5e8b-11e8-87be-638395896456.png)

**Comment by clobrano** [comment]
My opinion is that these black borders give some kind of 3D effect as well, so I would prefer totally flat, since all the rest of buttons are flat

**Comment by madsrh** [comment]
> My opinion is that these black borders give some kind of 3D effect as well, so I would prefer totally flat, since all the rest of buttons are flat

**+1**

@godlyranchdressing is it because you want them to match the GDM buttons?

**Comment by Feichtmeier** [comment]
Maybe it's because I've been starring on the current btns for too long - but this ^ looks like the btns are toggled/pressed.

**Comment by DragoCubed** [comment]
Looks so much better! I really hope it changes to this

**Comment by godlyranchdressing** [comment]
@Feichtmeier yeah, I agree. That's why I put the borders. @madsrh?

Alternatively, we can make the button text color for headerbar buttons just a little darker. 

Or have the title text darker and the button text lighter (but then would that make the title look like a disabled button?).

![screenshot from 2018-06-14 12-39-48](https://user-images.githubusercontent.com/27529229/41426316-3e0b6a3a-6fd1-11e8-9be2-8ab46c7ef33b.png)
![screenshot from 2018-06-14 12-39-42](https://user-images.githubusercontent.com/27529229/41426317-3e219ab2-6fd1-11e8-8e26-8ce0203a98f0.png)

**Comment by madsrh** [comment]
You're back @godlyranchdressing! 🎉 😄 

I'm not sure what to think about this. Can I sit this one out? 😆

**Comment by Feichtmeier** [comment]
He's back! :clinking_glasses: 
Yet, I am really not a fan of this. I would rather leave it as it is. :crying_cat_face: I think the headerbar is very beautiful as it is.

**Comment by Feichtmeier** [comment]
There is one big advantage of the current solution: when the headerbar becomes crouded by icons that thing stay clean and easy for the eye. With a border or a background everyone becomes "busy" very fast

![image](https://user-images.githubusercontent.com/15329494/41440943-d01881a6-7030-11e8-9da0-ea94ffe9f731.png)

![image](https://user-images.githubusercontent.com/15329494/41440964-e31ee34e-7030-11e8-8bf8-5c80ba4d35f2.png)

![image](https://user-images.githubusercontent.com/15329494/41441086-72a13918-7031-11e8-9cc0-3fffa5d0b824.png)

**Comment by godlyranchdressing** [comment]
Those aren't text buttons like I'm proposing. I can't think of any GTK3 app off the top of my head where it gets that crowded with _text buttons_.

The border to me looks a little bit like a focus state, like when you press tab and a button gets keyboard focus.

**Comment by Feichtmeier** [comment]
@godlyranchdressing ah yes, sorry. Maybe it was too late yesterday.
Some of the text buttons already have the border though:
![image](https://user-images.githubusercontent.com/15329494/41456378-95688e84-7080-11e8-90a2-52e21921b042.png)
That are the "file operations" I guess?

**Comment by godlyranchdressing** [comment]
Yes, but you can also argue that the border makes the button look like it's focused on.

The one place where this really sticks out to me is in the save dialog:

![save_current](https://user-images.githubusercontent.com/27529229/41481241-3588be52-709f-11e8-8b2a-b45afaaacda1.png)
Compared to:
![save](https://user-images.githubusercontent.com/27529229/41481250-3ce97524-709f-11e8-9e7a-0ac117258d4a.png)

Also, both GNOME Builder and Gedit are iffy examples because they're two of the very few apps that have a mixture of both text and image buttons. The most common look would be the following where there's just one text button to the far left and one to the far right:

![select_current](https://user-images.githubusercontent.com/27529229/41481358-9ad47f76-709f-11e8-8d97-dfac41978444.png)
![bg](https://user-images.githubusercontent.com/27529229/41481359-9afbc626-709f-11e8-9454-b36fa0dd2f8c.png)

I think the keyboard focus look of the border gets even more prominent when one of the buttons is a suggested/destructive action.

But with the loss of the button's bottom highlight the dark buttons don't stick out much against the headerbar anyway so :man_shrugging: .

**Comment by Feichtmeier** [comment]
The shadow is back. I think my problem is that the stack switcher is light and pressed buttons are light. Therefore my brain can't understand that the lightness should indicate something different on text buttons. In the dark theme I tried the solution to darken the pressed buttons.

**Comment by clobrano** [comment]
> Yes, but you can also argue that the border makes the button look like it's focused on.

I am not sure to understand. Our standard hover effect is a change in color, so the solution you're proposing should look even more on focus than the borders.

**Comment by godlyranchdressing** [comment]
@clobrano currently, text buttons have a border to indicate that it's there and to make it look different from window titles, but by giving it a border, the button can be mistaken for a _flat text button having keyboard focus_. By making it look like a regular, non-flat button like I'm proposing, it'll look like a regular dark button.

**Comment by clobrano** [comment]
I understand now, I wasn't thinking about keyboard focus. However the selection ring is orange, I'm not sure there would be any problem

**Comment by clobrano** [comment]
How we would like to proceed with this? I think there is some kind of general agreement in favor of current headerbar buttons, isn't it @Feichtmeier, @madsrh?

If that so I think we can close this (which is silent since more than a month now)

**Comment by godlyranchdressing** [comment]
This is another "I won't sleep over it" issue, but should I just make a PR and we can test and provide feedback? It'll look like [this](https://user-images.githubusercontent.com/27529229/40432337-73ef34ee-5e77-11e8-92bb-47a39217af3a.png).

**Comment by Feichtmeier** [comment]
I am not a big fan of these leveled up buttons. I would say the the header bar and the flat buttons are already a real unique selling proposition of yaru. This is my honest opinion about that

**Comment by clobrano** [comment]
I am with @Feichtmeier. Probably flat headerbar button is the only thing we agreed upon since the beginning

**Comment by godlyranchdressing** [comment]
_I like the buttons flat too_, but the border doesn't look that good to me, sorry. I like the [dimmed buttons](https://github.com/godlyranchdressing/yaru/commit/16df7838cd9a5a7f6759c9691a8e7e2437f8f9da) a lot after using it for a while, hopefully it can be a compromise, but if we stick to the current style then :man_shrugging:

**Comment by clobrano** [comment]
No need to be sorry, maybe I am too accustomed now to current headerbar text-buttons. The idea is just to make them less visible possible, but since they're just text, which a little indication of their presence. I feel that changing background color or shadow box is less effective for this

**Comment by clobrano** [comment]
Just noted that these buttons will look like the current toggled image-buttons

![image](https://user-images.githubusercontent.com/2883614/43346610-13589d7e-91f2-11e8-8aae-ebcc23515e7f.png)

**Comment by Feichtmeier** [comment]
@godlyranchdressing made another PR as a solution for this missmatch, but I am still torn :)

**Comment by Feichtmeier** [comment]
Since we tried almost all possible solutions and still think the current one is the best of which we've tried yet, can we close this issue?
