### ISSUE TITLE
buttons in buttonbox not styled

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#482]
![image](https://user-images.githubusercontent.com/15329494/40566035-34263372-606f-11e8-915d-424e83da1260.png)

Glade uses a strange box for buttons which seems to be styled wrong - compared to other buttons.

Adwaita styles them exactly like normal buttons:
![image](https://user-images.githubusercontent.com/15329494/40566092-674e1044-606f-11e8-9ec3-bfbda8d781c2.png)

**Comment by Paz-it** [comment]
I don't have glade installed but It seems this kind of style is the same in logs : 
![screenshot from 2018-05-26 01-04-22](https://user-images.githubusercontent.com/37431503/40568073-0b7be126-6081-11e8-8e36-01f3d998fbee.png)
and in Adwaita : 
![screenshot from 2018-05-26 01-03-13](https://user-images.githubusercontent.com/37431503/40568091-29a5e7f0-6081-11e8-90ae-93edfca912ea.png)

**Comment by clobrano** [comment]
@Paz-it sorry I don't understand your comment. Logs seems fine in both communitheme and adwaita, which are the similarities with glade?

**Comment by Feichtmeier** [comment]
The problem is that we styled buttonbox.linked like the stackswicthers.

We did this because some apps use a buttonbox as a "fake" stackswitcher, for example gnome-software. (tbh I didn't find any other O.o but gnome-software has no styleclass for the buttonbox)

So this is rather problematic, because buttonboxes will be probably used more often in apps other than glade.

![image](https://user-images.githubusercontent.com/15329494/43683412-69e21d56-988b-11e8-96d6-3742bdeeb224.png)

We should unstyle the buttonbox.linked to look like normal buttons, but then we need a solution for gnome-software again.

They have a styleclass .toolbar-primary-buttons-software
So it's probably possible.

**Comment by Feichtmeier** [comment]
@madsrh 
Concerning glade:

That buttonbox with its open and save buttons. There is an arrow close to it.
Should I remove the border of this specific save/open buttons ( they have an ID *yay*) or should I add the border to the arrow buttons?

**Comment by clobrano** [comment]
So basically, are we going to have squared buttons in gnome-software headerbar?

**Comment by Feichtmeier** [comment]
Well I am working on emulating the stackswitcher. But we styled the buttonbox like a stackswitcher at the moment and that could become really problematic if more apps use that buttonbox :|

**Comment by Feichtmeier** [comment]
![peek 2018-08-05 11-48](https://user-images.githubusercontent.com/15329494/43684719-84db72f0-98a5-11e8-971a-e907c3ac513d.gif)

:see_no_evil: 

Well :man_shrugging: I can't say this would look bad, but somehow it doesn't look right. 
I think one of the reasons for this complex hierarchy instead of a stackswitcher could be that there are also the counter-labels for the update/install counts

**Comment by clobrano** [comment]
The orange underline is missing because it would bend at the corner?

**Comment by Feichtmeier** [comment]
Okay to sum it up:

- we have a very good style for stackswitchers! They are very often used and are in almost every "modern" / newer GNOME app - we should stick to this style for stackswitchers
- we found that gnome-software uses a similiar tooling in its headerbar named "buttonbox" (But it is made with different UI elements) so we styled it GLOBALLY the same way as stackswitchers. This is a problem, since NORMALLY buttonboxes can pop up everywhere since they are just that: a box for buttons
- gnome-software has not many individual style classes nor IDs, thus we are dependent on the global styling of buttonboxes


Options (@madsrh @luxamman please decide):
- Quick-and-dirty-solution: glade has a style class for its window 
![image](https://user-images.githubusercontent.com/15329494/43687498-58fc2360-98d6-11e8-8a3d-4d93ebadc7a9.png)

where we can follow its hierarchy and style the buttonbox individually and fix this issue for glade ONLY. If a buttonbox pops up anywhere else, we have the same problem again
- long term solution: remove the global buttonbox styling and end up with this:
https://user-images.githubusercontent.com/15329494/43684719-84db72f0-98a5-11e8-971a-e907c3ac513d.gif and live with the fact that it is a different UI element for a similiar solution (switching between UI layers/ stacks

**Comment by Feichtmeier** [comment]
I think it's a bit problematic now that we would then end up with 3 different button styles (not talking about true stackswitchers or the window controls) in the headerbar then

- regular headerbar buttons (no border, gray hover, black box shadow at the top)
- headerbar text.buttons (super subtle border (inkstone), black box shadow at the top)
![peek 2018-08-05 21-54](https://user-images.githubusercontent.com/15329494/43689406-788ca032-98fa-11e8-865e-f1d99ca0eb9b.gif)
- headerbar buttonbox buttons (super subtle border (inkstone), mixed box shadow at top)
![peek 2018-08-05 21-56](https://user-images.githubusercontent.com/15329494/43689409-80405eb8-98fa-11e8-82af-9120bf212c32.gif)


The difference between headerbar buttons and textbuttons is also discussed in aarons issue but we could maybe find a solution for everything here. (prbly dreaming :D but who knows?)

My brain hurts... too many options... halp pl0x

**Comment by clobrano** [comment]
What about this (no internal separation inside a buttonbox)?

![buttonbox-linked](https://user-images.githubusercontent.com/2883614/43690000-5ee1f71e-9903-11e8-9a37-e986b07c6e22.gif)

conceptually is similar to stackswitcher, which is a whole object, but styled as a headerbar button

**Comment by Feichtmeier** [comment]
@clobrano concerning the buttonbox in software I would prefer this indeed. But not for that "comboboxes" :thinking: 

On topic of the "great button problem" (the other issue would be prbly more fitting but maybe we can do it all in this one)
It's funny that I am trying to like the subtle inkstone border for all headerbar buttons (well, why not change my mind?):
![image](https://user-images.githubusercontent.com/15329494/43690092-bd2f9028-9904-11e8-9b26-d0fc0a7140c5.png)

**Comment by clobrano** [comment]
I believe that having a border for all icon makes the headerbar quite messy :(

**Comment by Feichtmeier** [comment]
Yes I am torn, too...
The current one looks very elegant and modern.
Yet, I remember my father didn't realize that those icons in the headerbar are something you can click :/

**Comment by Feichtmeier** [comment]
@clobrano even if we prbly keep the current headerbar, we would still need (imho) a solution for the different press effects

**Comment by clobrano** [comment]
> We now have a press effect for the buttons inside buttonboxes in the headerbar and one for "normal" buttons in the headerbar

No we don't. The press effect is the same, just the border is always visible

**Comment by Feichtmeier** [comment]
Hmmmm but there are situations where it is quiet visible, for example this one:

![image](https://user-images.githubusercontent.com/15329494/43708216-42463284-996a-11e8-852e-c1db8449d97f.png)

**Comment by Feichtmeier** [comment]
Okay - I understood, sorry for the slowness.

Yet it is a visual mismatch, don't you think? The normal button looks "harder" or "deeper" pressed

**Comment by clobrano** [comment]
> Yet it is a visual mismatch, don't you think? The normal button looks "harder" or "deeper" pressed

I agree on that. I'll try to come up with a generic solution

**Comment by Feichtmeier** [comment]
Nice! I think the idea to leave out the border between elements of the buttonbox is actually quiet good - changed my mind about that after using it a bit

**Comment by clobrano** [comment]
![image](https://user-images.githubusercontent.com/2883614/43709961-8b3e0c2e-996e-11e8-9dd0-8cfeed855e18.png)

**Comment by Feichtmeier** [comment]
Imho this looks good =D donnou what others say
