### ISSUE TITLE
Use suru icons in the GDM login

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#583]
The GDM login uses the wrong (probably Adwaita) icons for

- the default user icon
- all top panel icons (including the ones in the popup)

![virtualbox_cosmicdaily_20_08_2018_16_04_36](https://user-images.githubusercontent.com/15329494/44345327-52bbfe80-a493-11e8-8471-41d53efb0158.png)

AFTER logging in, the **lock**-screen uses the correct icons!

![image](https://user-images.githubusercontent.com/15329494/44347326-c9f39180-a497-11e8-9d39-3ccfa1b0a4d7.png)

Previously discussed here:
https://github.com/ubuntu/gnome-shell-communitheme/pull/56
https://github.com/ubuntu/gtk-communitheme/issues/129

**Comment by Feichtmeier** [comment]
@3v1n0 just checked out the Yaru theme in cosmic <3 Very great feeling to see it by default!

This issue with the wrong icons persists in 18.10 at the moment even with Yaru being the default theme.

**Comment by 3v1n0** [comment]
Ok, we can handle this in ubuntu-settings.

**Comment by Feichtmeier** [comment]
Great thank you!

**Comment by Feichtmeier** [comment]
@3v1n0 

Okay great - this is fixed now for 18.10:
![image](https://user-images.githubusercontent.com/15329494/44469748-76647d80-a628-11e8-950b-f7eded9f490f.png)

Thank you very much!
