### ISSUE TITLE
Flat shell pop-ups Vs 3D shell pop-ups

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#585]
Currently the dialogues and notifications have a bit more depths since they use a box shadow to symbolise the transcendence above the shell and a pressed effect for the buttons. (Leveled up, pressed down)
The shell pop-ups can't have the box shadow due to a gnome shell limitation unless we remove the box pointer (the arrow). 

To migrate https://github.com/ubuntu/gnome-shell-communitheme/issues/160 
and to not just silence the desire from @godlyranchdressing, I would like to have a  final discussion and hopefully a final decision about the general flat pop-ups (and within the buttons!!!) Vs 3d pop-ups (with 3d buttons).

What's your opinion on that @madsrh @luxamman @clobrano

**Comment by clobrano** [comment]
I confirm my preference on the bright border that "clear" button has in calendar view. I'm sorry I dedicated so little time to this and didn't come up with a test version with the same border in close/suspend/etc buttons

**Comment by Feichtmeier** [comment]
I am quiet happy with the shell to be honest. If you feel the same way we could close this, too @madsrh @clobrano

**Comment by clobrano** [comment]
Closing this then
