### ISSUE TITLE
Make ubuntu-dock progress bars themeable

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#586]
Current progress bars:

![39465272-b6fd1cbc-4d22-11e8-8c10-303b7cd9d52f](https://user-images.githubusercontent.com/15329494/39480765-7a9c7942-4d69-11e8-878f-b041d493113a.png)

There is currently no style class for the progress bars and its trough.
To color and style them like we did with the notification badges.

Waiting for @azzar1 for the implementation before being able to use any style class (which does not exist at the moment)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/43038387-51af5326-8d18-11e8-8aea-42f19148dac1.png)

Actually it is not only the color of the progress bar, there are also some very oldschool shadows and highlights. Does not fit at all to the gnome shell theme : /

**Comment by didrocks** [comment]
I guess the whole request is rather making it themeable.

**Comment by Feichtmeier** [comment]
https://github.com/micheleg/dash-to-dock/issues/747

There it is @didrocks :)

**Comment by clobrano** [comment]
Closing this, since the change is upstream side
