### ISSUE TITLE
Nautilus: Selected icon is dark in backdrop

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#603]
Like the lighttheme, there shouldn't be any change to the selected icon in backdrop.

![image](https://user-images.githubusercontent.com/3986894/42189666-b19e4a26-7e59-11e8-8739-3690121604cb.png)

**Comment by clobrano** [comment]
@Feichtmeier did you say you tried, but that wasn't doable or did I misunderstand?

**Comment by Feichtmeier** [comment]
I tried but failed : l maybe you succeed

**Comment by clobrano** [comment]
Closing this since it does not seems doable
