### ISSUE TITLE
[ Feature request ] Unity 7 shell theme

### ISSUE THREAD

**Issue by luispabon** [ubuntu/yaru#652]
As per title really. A lot of us don't want to jump to Gnome and still love and use Unity daily.

**Comment by Feichtmeier** [comment]
Hi! Though this is the wrong place to request this here is a short answer:
There is an unofficial, community made 18.04 unity iso and a whole thread about this on the Ubuntu community hub. But also until 16.04 it's supported until  2021 and gets kernel upgrades with every point release (and runs unity 7)
http://www.ubuntu.com/info/release-end-of-life
