### ISSUE TITLE
GTK theme of snap is renamed to Yaru 

### ISSUE THREAD

**Issue by galgalesh** [ubuntu/yaru#655]
The GTK theme name is changed to Yaru in the snap. Because of this, the Communitheme session on bionic now failovers to Adwaita since it can't find Communitheme gtk theme.

Is this a mistake or will the session catch up by the time we're stable?

**Comment by galgalesh** [comment]
I'm not certain why though.. The `snapcraft.yaml` seems to be correct and if I build the snap locally, I get Communitheme instead of Yaru.

**Comment by galgalesh** [comment]
The latest build of Communitheme snap according to Travis is 651, but the latest snap in edge is 652.

```
Pushing communitheme_0.1_all.snap [] 100%
Processing...|
Ready to release!
Revision 651 of 'communitheme' created.
```

```
channels:                   
  stable:    0.1 (644) 10MB -
  candidate: ↑              
  beta:      ↑              
  edge:      0.1 (652) 11MB -
installed:   0.1 (652) 11MB -
```

**Comment by galgalesh** [comment]
I found the issue, suru-icon-theme is still triggering travis builds xD

https://travis-ci.org/ubuntu/suru-icon-theme

**Comment by galgalesh** [comment]
I shut down the travis builds of `gnome-shell-communitheme`, `communitheme-sounds`, `communitheme-snap-helpers` and `suru-icon-theme` and triggered a rebuild of `yaru`. This is fixed now.

I don't find a way to remove these repos from travis, I just turned off these two toggles so the builds are never triggered again.

![image](https://user-images.githubusercontent.com/1492981/43270702-0db5ca7e-90f6-11e8-9c0a-e1685d41378c.png)

**Comment by didrocks** [comment]
Nice finding! Indeed, the deprecation notice I did this morning should have triggered that!
