### ISSUE TITLE
Installation from snap in 18.04 (bionic) doesn't do anything

### ISSUE THREAD

**Issue by alxgrtnstrngl** [ubuntu/yaru#656]
When I installed the snap using the instructions both `--stable` and `--edge` on Ubuntu 18.04 LTS nothing seems to happen. There's a communitheme folder in `/snap` but no xsessions or wayland-sessions are created even after several reboots. In order to get the theme to work I had to create symlinks from this `/snap` to `~/.themes` and manually change it in Tweak tool. 

The gnome-shell theme also looks odd, the font size and the padding is huge and doesn't match the screenshots I see on the wiki. Many of the icons aren't fully there. There are a lot of inconsistencies. 

The gdm3 theme is not changed either, it remains the default Ubuntu theme from 18.04 LTS.

Is there a way to do a reset of my settings and then try again? I've read that doing a fresh install fixes things. But that seems like a terrible solution and not worth it.

**Comment by clobrano** [comment]
Hi @alxgrtnstrngl, I am sorry for this problem. I'll try if I can reproduce it to help you better :+1:

**Comment by alxgrtnstrngl** [comment]
@clobrano Thank you! I tried reinstalling today but still the same issue.

**Comment by MylesJohnson** [comment]
I'm having the exact same issue as @alxgrtnstrngl for what its worth. I haven't tried a reinstall, but my symptoms match the original post.

**Comment by clobrano** [comment]
To reset, being a snap, it should be enough to uninstall the package

**Comment by alxgrtnstrngl** [comment]
I've tried reinstalling the snap several times and rebooting with no luck. I even reinstalled the `gtk-common-theme` snap and did it in different orders and it didn't work.

**Comment by Feichtmeier** [comment]
That's very strange. Just installed it this week on a fresh ubuntu install without a problem. 
I hope there are no settings mixed from the snap/ppa/meson installations?

**Comment by clobrano** [comment]
I've reinstalled again from 18.04.1, installed communitheme snap stable (that is just `snap install communitheme`) and this is the list of "communitheme" files under root. Could you double check if you have the same?
```
carlo@yaru:~$ find / -name *communitheme* 2>/dev/null
/run/systemd/units/invocation:snap-communitheme-699.mount
/usr/share/xsessions/ubuntu-communitheme-snap.desktop
/usr/share/wayland-sessions/ubuntu-communitheme-snap-wayland.desktop
/usr/share/icons/communitheme
/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/ubuntu-communitheme.css
/sys/fs/cgroup/pids/system.slice/snap-communitheme-699.mount
/sys/fs/cgroup/devices/system.slice/snap-communitheme-699.mount
/sys/fs/cgroup/systemd/system.slice/snap-communitheme-699.mount
/sys/fs/cgroup/unified/system.slice/snap-communitheme-699.mount
/snap/communitheme
/snap/communitheme/699/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/communitheme.css
/snap/communitheme/699/share/gnome-shell/modes/ubuntu-communitheme.json
/snap/communitheme/699/share/icons/communitheme
/snap/communitheme/699/share/sounds/communitheme
/snap/gtk-common-themes/319/share/icons/communitheme
/snap/gtk-common-themes/319/share/sounds/communitheme
/var/lib/snapd/snaps/communitheme_699.snap
/var/snap/communitheme
/home/carlo/.local/share/session_migration-ubuntu-communitheme-snap
/etc/systemd/system/snap-communitheme-699.mount
/etc/systemd/system/multi-user.target.wants/snap-communitheme-699.mount
```

**Comment by mpawlowski7** [comment]
hi,
I've similar problem after installing snap version when I already had apt version installed. After reboot I have only apt session visible during login. This is my output:

`mipw@mipw-X580VD:~$ find / -name *communitheme* 2>/dev/null
/sys/fs/cgroup/devices/system.slice/snap-communitheme-742.mount
/sys/fs/cgroup/pids/system.slice/snap-communitheme-742.mount
/sys/fs/cgroup/systemd/system.slice/snap-communitheme-742.mount
/sys/fs/cgroup/unified/system.slice/snap-communitheme-742.mount
/usr/share/gnome-shell/modes/ubuntu-communitheme.json
/usr/share/gnome-shell/theme/communitheme
/usr/share/glib-2.0/schemas/15_ubuntu-communitheme-session.gschema.override
/usr/share/wayland-sessions/ubuntu-communitheme.desktop
/usr/share/sounds/communitheme
/usr/share/xsessions/ubuntu-communitheme.desktop
/usr/share/xsessions/ubuntu-communitheme-xorg.desktop
/usr/share/doc/ubuntu-communitheme-session
/usr/share/doc/gtk-communitheme
/usr/share/doc/gnome-shell-communitheme
/usr/share/doc/communitheme-sounds
/var/snap/communitheme
/var/lib/apt/lists/ppa.launchpad.net_communitheme_ppa_ubuntu_dists_bionic_main_binary-amd64_Packages
/var/lib/apt/lists/ppa.launchpad.net_communitheme_ppa_ubuntu_dists_bionic_main_binary-i386_Packages
/var/lib/apt/lists/ppa.launchpad.net_communitheme_ppa_ubuntu_dists_bionic_main_i18n_Translation-en
/var/lib/apt/lists/ppa.launchpad.net_communitheme_ppa_ubuntu_dists_bionic_InRelease
/var/lib/snapd/snaps/communitheme_742.snap
/var/lib/dpkg/info/gtk-communitheme.md5sums
/var/lib/dpkg/info/communitheme-sounds.list
/var/lib/dpkg/info/communitheme-sounds.md5sums
/var/lib/dpkg/info/ubuntu-communitheme-session.postinst
/var/lib/dpkg/info/ubuntu-communitheme-session.md5sums
/var/lib/dpkg/info/ubuntu-communitheme-session.prerm
/var/lib/dpkg/info/ubuntu-communitheme-session.list
/var/lib/dpkg/info/gnome-shell-communitheme.md5sums
/var/lib/dpkg/info/gtk-communitheme.list
/var/lib/dpkg/info/gnome-shell-communitheme.list
/etc/apt/trusted.gpg.d/communitheme_ubuntu_ppa.gpg
/etc/apt/sources.list.d/communitheme-ubuntu-ppa-bionic.list
/etc/systemd/system/snap-communitheme-742.mount
/etc/systemd/system/multi-user.target.wants/snap-communitheme-742.mount
/home/mipw/.local/share/session_migration-ubuntu-communitheme
/home/mipw/.local/share/session_migration-ubuntu-communitheme-xorg
/home/mipw/snap/gnome-system-monitor/51/.local/share/icons/communitheme
/home/mipw/snap/gnome-calculator/180/.local/share/icons/communitheme
/snap/gtk-common-themes/629/share/icons/communitheme
/snap/gtk-common-themes/629/share/sounds/communitheme
/snap/gtk-common-themes/319/share/icons/communitheme
/snap/gtk-common-themes/319/share/sounds/communitheme
/snap/communitheme
/snap/communitheme/742/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/communitheme.css
/snap/communitheme/742/share/gnome-shell/modes/ubuntu-communitheme.json
/snap/communitheme/742/share/icons/communitheme
/snap/communitheme/742/share/sounds/communitheme
/run/systemd/units/invocation:snap-communitheme-742.mount
`
is there any way to force session migration to snap version? Thanks

**Comment by clobrano** [comment]
> I've similar problem after installing snap version when I already had apt version installed

you shouldn't mix ppa with snap.

Remove snap and then try `sudo apt purge communitheme` before reinstalling the snap

**Comment by Feichtmeier** [comment]
Let's close this. It's pretty clear that it comes from mixing PPA and snap. I installed the snap on at least 8 installations in the past weeks and everything works
