### ISSUE TITLE
gnome-shell: Ignoring length property that isn't a number at line 186, col 24

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#664]
/* Switches */
.toggle-switch {
  width: 65px;
  height: 22px;
  background-size: contain;
  background-position: right center; } <<<<<<

**Comment by clobrano** [comment]
This is probably due to a mistake I made merging a PR few minutes ago

**Comment by clobrano** [comment]
Actually it wasn't :D 
It seems that gnome-shell does not support background-position property :)
