### ISSUE TITLE
yaru on Ubuntu-Mate

### ISSUE THREAD

**Issue by Vittelius** [ubuntu/yaru#673]
On Ubuntu-Mate some panel-applets like the notification-area and the menu are themed dark while the panel-basecolour is much lighter, this leads to some weird visuals. Also there is no way to pick the theme for server-side window decorations.
![bildschirmfoto zu 2018-07-30 12-47-35](https://user-images.githubusercontent.com/3718818/43393493-adef2e14-93f7-11e8-9d86-f75c04adcd5b.png)

**Comment by Feichtmeier** [comment]
This theme is at the moment only for the gnome desktop, sorry. If we plan mate support some day we can reopen this. Thanks for reporting.
