### ISSUE TITLE
No non-snap deployment instructions

### ISSUE THREAD

**Issue by anatoli26** [ubuntu/yaru#678]
Hi,

I really like this theme and I'd like to deploy it on BSD systems with base GNOME. There is no snap support. What are the general steps to deploy this theme without snap, bird's eye view?

Thanks!

**Comment by clobrano** [comment]
I guess your best changes is 

https://github.com/ubuntu/yaru/blob/master/CONTRIBUTING.md#build-and-install-themes-from-source

closing this, since actually there are non-snap deployment instructions :)

**Comment by anatoli26** [comment]
Thanks, haven't seen it!
