### ISSUE TITLE
No Yaru session in 18.10 if installed from deb

### ISSUE THREAD

**Issue by gayanper** [ubuntu/yaru#681]
Installed yaru theme components including
- shell theme
- gtk theme
- sound theme
- icon theme
In ubuntu development release installation from the cosmic repo.

But they there is no option in thr session selection to get the yaru theme activated.

But as a workaround one could select the gtk, icon themes from tweak tool. But the shell theme is not shown in the shell theme list in the tweak tool either.

**Comment by clobrano** [comment]
Hi @gayanper, by development release you mean Cosmic Cattlefish 18.10?

I tried installing it in a VM, installed Yaru from Gnome Software (but it's the same as `sudo snap install communitheme`), at reboot I selected "Ubuntu with communitheme snap" and I found everything set up from Shell to GTK

**Comment by gayanper** [comment]
Hi @clobrano
Yes it is cosmic cattlefish 18.10.

I did installed the yaru-* packages from the apt repositories. Did went for the snap since the yaru  be the default theme in 18.10. since the packages were already there in apt repo i thought it will work in the same way as the snap version.

**Comment by clobrano** [comment]
The work to make it default is ongoing, not sure if apt packages are already ok for cosmic

**Comment by gayanper** [comment]
When i checked the installed files under gnome shell it seems like the css files were missing in the yaru theme folder. May be it's something we can checkup on.

**Comment by clobrano** [comment]
any chance you can try with snap?

**Comment by gayanper** [comment]
I tried snap when i was in 18.04, and it worked flawlessly. I hope its the same snap your suggesting me to install. i would prefer not to install the snap and try the apt approach which would be the default that will land in 18.10.

**Comment by clobrano** [comment]
Yes the snap is only one

**Comment by clobrano** [comment]
I'm going to install again in VM and install deb packages to see if I can reproduce that

**Comment by clobrano** [comment]
Sorry if I changed the title, but this looks more descriptive. I tested on VM and confirm that there's no way to select the yaru session and so the yaru gnome shell. However all the Gtk elements are available. In cosmic the transition is probably to be completed to let yaru be default.

**Comment by Feichtmeier** [comment]
Hi - I am pretty sure didier will do this differently.There will be simply the Ubuntu session once they put the code into the repo.

**Comment by clobrano** [comment]
I believe so as well. Can we close this?
