### ISSUE TITLE
Gedit selected treeview icon isn't white

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#686]
Selected treeview icon isn't white in Gedit. This is only in Bookmarks. Adwaita does the same. 

![image](https://user-images.githubusercontent.com/3986894/43612208-e4538746-96ab-11e8-8b1e-0f06bb5c4790.png)

I'm guessing that it's because the icons aren't colored on selection, and so we can't fix this or??? 

![image](https://user-images.githubusercontent.com/3986894/43613152-ac4cd020-96ae-11e8-86b2-06d047449e4c.png)

**Comment by Feichtmeier** [comment]
No they can't be colored -.- 
![screenshot from 2018-08-03 19-09-16](https://user-images.githubusercontent.com/15329494/43655909-c594318e-9750-11e8-9f68-81a567c761f5.png)

**Comment by madsrh** [comment]
Alrighty then...
