### ISSUE TITLE
Flatpak needs namespace change

### ISSUE THREAD

**Issue by Austinuity** [ubuntu/yaru#687]
Although the snap package is not being changed until 18.10, due to the way flatpaks handle theming, a namespace change is critical to the functioning of the flatpak version. It mirrors the name of the gtk theme set for system/nonflatpak apps, and as that is currently named yaru in the system while the package is named Communitheme, it does not currently apply itself to flatpak apps.

**Comment by taciturasa** [comment]
Haha uhh.... i used the wrong account, can this issue be closed and the other one left instead?
