### ISSUE TITLE
      Flatpak needs namespace change 

### ISSUE THREAD

**Issue by taciturasa** [ubuntu/yaru#688]
Although the snap package is not being changed until 18.10, due to the way flatpaks handle theming, a namespace change is critical to the functioning of the flatpak version. It mirrors the name of the gtk theme set for system/nonflatpak apps, and as that is currently named yaru in the system while the package is named Communitheme, it does not currently apply itself to flatpak apps.

**Comment by clobrano** [comment]
@taciturasa thanks to point this out. I don't know flatpak well enough, could you give me a hint about the actual change to be done?

**Comment by taciturasa** [comment]
Flatpak theming works by mirroring the name of the theme set for other apps to the name of the flatpak version, so most likely it needs to be changed so when it's built the theme name is changed to Yaru. failing that, the namespace on flathub itself might need to be switched over to yaru, as well.

**Comment by Feichtmeier** [comment]
Hey I think it would be better to re-open the old bug: https://github.com/ubuntu/yaru/issues/201
To get the right people into it for fixing this
