### ISSUE TITLE
Icon View Captions should be more subtle.

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [ubuntu/yaru#689]
![screenshot from 2018-08-03 13-20-00](https://user-images.githubusercontent.com/38913802/43627608-a2b48d48-9729-11e8-83fa-56759b015649.png)

Current
![screenshot from 2018-08-03 13-16-59-1](https://user-images.githubusercontent.com/38913802/43627769-470328d2-972a-11e8-8c8b-b8c2a0303ea8.png)

Desired (Based on Adwaita, Ambiance and others)
![screenshot from 2018-08-03 13-16-59](https://user-images.githubusercontent.com/38913802/43627768-469ed4e0-972a-11e8-803a-6839ddb31266.png)

Bonus Question:

This might not be strictly a communitheme issue, but maybe some of the ubuntu devs would know...
Since when did the default font size change from 10 to 11? IMO 11 doesn't fit well with the slick, thin theme.

Current
![screenshot from 2018-08-03 13-17-33](https://user-images.githubusercontent.com/38913802/43628156-ba781d9e-972b-11e8-93ec-2fc89a55a790.png)

Un-updated machine
![screenshot from 2018-08-03 12-59-35](https://user-images.githubusercontent.com/38913802/43628180-cb04443a-972b-11e8-8275-123d020c708a.png)

**Comment by Feichtmeier** [comment]
We changed that due to a bug in gnome shell where the overview labels are cut off with font yet to 11

**Comment by ReyLeonardAmorato** [comment]
Ok, so that explains it. How about the colours though, is that something we can do? or is it not in the spirit of Yaru?

**Comment by madsrh** [comment]
@ReyLeonardAmorato Nicely spotted with the colors!

@Feichtmeier IMO we should keep the size 10 and prioritize fixing it. Nothing [here ](https://github.com/ubuntu/yaru/issues/587)indicates that we were changing it back to 11 🤷‍♂️

**Comment by Feichtmeier** [comment]
I think this is already landed in 18.04.1
If this gets fixed upstream we could prbly change it again for 18.04.2

**Comment by Feichtmeier** [comment]
Sorry, the other issue can prbly be fixed :) I try to work on that

**Comment by ReyLeonardAmorato** [comment]
Great! Thank you :)

**Comment by Feichtmeier** [comment]
![screenshot from 2018-08-03 18-26-28](https://user-images.githubusercontent.com/15329494/43654278-f553cf0c-974a-11e8-9822-e11da7ca1f78.png)
![screenshot from 2018-08-03 18-27-34](https://user-images.githubusercontent.com/15329494/43654279-f5801742-974a-11e8-98c3-c22a8a85dd2b.png)
Is that ok?

**Comment by ReyLeonardAmorato** [comment]
Hello @Feichtmeier, I tried the snap pr and it's great, thank you! However, I noticed it was still a bit too dark. I don't want to sound unappreciative or bossy or anything but could we hack at it one more time? If that's not something you'd want to do, I understand.
![screenshot from 2018-08-04 13-40-10-1](https://user-images.githubusercontent.com/38913802/43673122-97fddb54-97ef-11e8-92fa-f030f48b4a8c.png)

**Comment by ReyLeonardAmorato** [comment]
Reason for my additional request is that with a directory with a lot of content, the secondary labels look too similar to the main label, at least on my display.

![screenshot from 2018-08-04 14-10-13](https://user-images.githubusercontent.com/38913802/43673160-2a455e42-97f0-11e8-950c-77b39eabcab4.png)

**Comment by Feichtmeier** [comment]
Ah you say lighten it more?
And no worries, you don't sound bossy :D you spotted the issue so why not improve it. Mads also agrees so everything is :+1:

**Comment by ReyLeonardAmorato** [comment]
Thank you!
