### ISSUE TITLE
Secondary icon text should be brighter to enhance readability

### ISSUE THREAD

**Issue by Eneen** [ubuntu/yaru#691]
Please take a look at screenshots:
This is (almost) current communitheme:
![zrzut ekranu z 2018-07-25 09-51-50](https://user-images.githubusercontent.com/25537418/43675859-6a800308-97e7-11e8-8bf8-186072ee1406.png)

...and this is Adwaita:
![zrzut ekranu z 2018-07-25 09-52-17](https://user-images.githubusercontent.com/25537418/43675862-71bc5b80-97e7-11e8-9eb6-c66bfc291c0c.png)

Secondary icon text is brighter, so file/folder names can be read quickly. I'm not sure how bright it should be though.

**Comment by madsrh** [comment]
@Eneen Hi, thanks for reporting. I'm going to close this because it's a duplicat of https://github.com/ubuntu/yaru/issues/689
