### ISSUE TITLE
Revert dialogues back to the upstream design

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#698]
The current dialogues are styled like "classic" dialogues or to look more "generic".

While we had a big discussion about this already (and even a poll) I want to be annoying again and propose that we should revert this styling back to look more like the upstream dialogues.

Pros:
- upstream designers had big discussions about this and it is definitely a design decision to reduce the dialogues on simply the buttons, we want to be as close to upstream as possible anywhere else (I don't want to count the upstream adaptions but they should be quiet numerous) so we could do this here, too
- LibreOffice was pretty proud about having native dialogues finally implemented and with styling them back to the generic look, we somehow "ruin" this milestone
- beside upstream decisions when you look to the dialogues as if you never seen a dialogue before (to reduce the bias) then it is pretty clear what you want to do: press this button OR press that button so there shouldn't be a dire need for a titlebar since you should answer to the questions the dialogue asks you and not drag him around (EDIT: dragin is still possible with CSD dialogues)
- opinion: the upstream dialogues look more "modern"/minimal designed
- the upstream design looks like the GNOME shell dialogues - and we use the light dialogues now in the shell - having a white gtk dialogue and a white shell dialogue could be more usable for the average user who doesn't care if it is GNOME Shell or a gtk window wanting him to proceed/click

Cons:
- Some people want to drag the dialogue around (EDIT: dragin is still possible with CSD dialogues)
- Yaru could like to be on par with the rest of dialogues outside of GNOME

@godlyranchdressing @madsrh @clobrano @luxamman

Sorry for opening this barrel again, but I think if we have the possibility to stick to upstream we should do this.

Current yaru gtk dialogues: 
![peek 2018-08-09 14-24](https://user-images.githubusercontent.com/15329494/43898741-0ca54e1c-9be0-11e8-8410-cc5ce53e8372.gif)
Adwaita gtk dialogues:
![peek 2018-08-09 14-14](https://user-images.githubusercontent.com/15329494/43898755-1625fc3e-9be0-11e8-9770-0d5055af4346.gif)
![peek 2018-08-09 14-28](https://user-images.githubusercontent.com/15329494/43898916-a0f5d622-9be0-11e8-8466-d298377fae75.gif)

Yaru Shell dialogues:
![peek 2018-08-09 14-26](https://user-images.githubusercontent.com/15329494/43898794-3b3fbc26-9be0-11e8-9a71-6d8958fe60c7.gif)

**Comment by clobrano** [comment]
> Some people want to drag the dialogue around

this might be the only showstopper, to me. Was really not possible to drag the upstream dialog, or was it just a lack of our implementation (e.g. we removed the titlebar at all)?

**Comment by Feichtmeier** [comment]
Yes, I think this is "by design". They want the the user answers to the dialogue. "Delete this email?" "Cancel". Otherwise there would be a third option "Drag me". :)
It also is on par with the general client side decoration behaviour that is also being used outside of GNOME (macos, chrome, firefox, even windows has CSD in some apps).

**Comment by Feichtmeier** [comment]
Edit: OH ho wait. Look you can still drag it:

**Comment by clobrano** [comment]
Yes, I remembered there was something due to an option to unlink the dialog from the window below plus we removing the titlebar.

**Comment by Paz-it** [comment]
I would prefer to keep the current. Can't believe you are going back to this loooong discussion again... 
![faint](https://user-images.githubusercontent.com/37431503/43910349-3ce8cbb0-9c05-11e8-8660-a09ac0dbd22c.gif)

**Comment by Feichtmeier** [comment]
Yes I am almost a necromancer - the reasons are listed above :) No need to repeat myself

**Comment by eaglersdeveloper** [comment]
Upstream dialogues really look more modern than current! I like they!

**Comment by Feichtmeier** [comment]
@clobrano the titlebar is still there in adwaita. They simply colored it like the BG and made it very thin. That's why you can still drag it

**Comment by clobrano** [comment]
I guess we need a mockup here "UI freeze is coming" :snowman:

**Comment by Feichtmeier** [comment]
We could start with the headerbar color. I am short on time this week would be great if you could tackle this :[

**Comment by madsrh** [comment]
> I guess we need a mockup here

Yeah, but what are we aiming for?

In random order here is:

- Shell style (Very consistent, but Didier had some issue with this) 
- Shell style but white #fff like [notifications](https://camo.githubusercontent.com/2d1b39d881854fc49eeccb1c4c2455ad0b13a18e/68747470733a2f2f692e696d6775722e636f6d2f395734756d424a2e6a7067) 
- Regular buttons with white background
- Adwaita (for reference) 
- Yaru shell (for reference) 

![image](https://user-images.githubusercontent.com/3986894/44096040-910317ae-9fda-11e8-98dc-dad01f39ac8a.png)
 
Other ideas? @clobrano @Feichtmeier @godlyranchdressing

**Comment by clobrano** [comment]
> Shell style but white #fff like notifications

I actually like this a lot (maybe because I don't like the other big buttons). What was the problem with shell style?

**Comment by madsrh** [comment]
I don't consider this an issue, but the problem was:

> I think that having them differentiated actually help: "is it something from the system or is it something specific to the app?"

https://github.com/ubuntu/yaru/issues/130#issuecomment-365586932

**Comment by Feichtmeier** [comment]
Thanks for the mock-ups.

I think this design is on purpose. Upstream wants the user not to care for if the "shell" or the applications wants his interaction.

This could also be a question of the target audience :) Sure, the classic linux user knows he is running gnome shell. But consider all the "new users" ubuntu recruits every day. Do they really know or want to know if it is GNOME Shell or a GTK application? :)

Focusing on the visuals, the mixed one, without a headerbar but with our button style, is already an improvement to the current one, in my opinion. A headerbar without a close button looks a little bit weird.

**Comment by clobrano** [comment]
> I think this design is on purpose. Upstream wants the user not to care for if the "shell" or the applications wants his interaction.

to remember that there's actually a modal dialog and a interaction dialog (at least on gtk3-demo). The first is similar to shell dialog, while the latter is similar to a normal gtk window

**Comment by clobrano** [comment]
![message-dialog-white](https://user-images.githubusercontent.com/2883614/44108782-ac555f00-9ffb-11e8-86ca-6dccd0c0aef5.gif)

**Comment by madsrh** [comment]
Looks good @clobrano 💪 Very clean

**Comment by Feichtmeier** [comment]
1) Maybe we need some days to think about this, I really like both full upstream and this

2) I see that those modal dialogues all miss padding at the bottom :) We could maybe fix this globally and remove it out of the ubiquity code in apps

**Comment by clobrano** [comment]
I made the PR so we can try it. I like it white, but don't want to mess up current balance :)

**Comment by clobrano** [comment]
This might even be a good situation to propose on the HUB, making it clear that we are just experimenting and that nothing is decided yet :)

**Comment by Paz-it** [comment]
OK. I like it white and asking the same question @madsrh  asked : 
 Are you sure you don't want to keep the shell buttons? :smiley: ...
So let's see how it evolve .. :curious:
