### ISSUE TITLE
Printer setting/ ink level scale color/thickness

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#699]
Not sure if it is a real issue  ... wdyt?
![screenshot from 2018-08-09 01-16-28](https://user-images.githubusercontent.com/37431503/43911765-f31cc0be-9c08-11e8-92e1-9ca5cd7f3fc4.png)

**Comment by Feichtmeier** [comment]
Could you post a comparison to the light theme?
And that's not suru you are using there, right? =) It's suru++? Because their symbolic icons have often the wrong color

**Comment by Paz-it** [comment]
@Feichtmeier Yes, Not Suru++ ( Orangin) So ignore the icons :) 
Here is the light version: 
![screenshot from 2018-08-09 21-21-29](https://user-images.githubusercontent.com/37431503/43918357-838c6214-9c1b-11e8-8d3f-e96bd168a402.png)

**Comment by madsrh** [comment]
Hmm, we use the dark borders so technically this is by-the-book, but I do think that the black border could be slightly more distinct from the ink bar.

Perhaps this is better?
![image](https://user-images.githubusercontent.com/3986894/43966784-1a11ddf2-9cc3-11e8-887f-f3669e90bbcc.png)

**Comment by eaglersdeveloper** [comment]
Then this "ink panel" should be applied also to the light theme.

**Comment by Feichtmeier** [comment]
I don't have printer which supports this kind of ink information so could anyone with one of those open the gtk inspector and tell us which style class / style ID it has? :)

**Comment by madsrh** [comment]
![image](https://user-images.githubusercontent.com/3986894/43975581-6c8de48e-9cde-11e8-8fe7-a78ec31d376d.png)

**Comment by Feichtmeier** [comment]
![photo_2018-08-11_10-31-53](https://user-images.githubusercontent.com/15329494/43989833-c83f3a6c-9d51-11e8-878c-908f7dd8c287.jpg)

**Comment by Paz-it** [comment]
Managed it :dancer: 
![screenshot from 2018-08-12 00-55-55](https://user-images.githubusercontent.com/37431503/43996424-ef7a3da6-9dca-11e8-8ef0-c004379002ed.png)

**Comment by clobrano** [comment]
What do we want to do with this ticket? Current state doesn't look bad actually

**Comment by Feichtmeier** [comment]
I think lightening the border would be nice, but I can not check it because I do not own such a printer : /

**Comment by Feichtmeier** [comment]
In the end, it just uses the border we use for the dark variant, so I would not call anything "broken" here.

The black bar is actually the black part of CMYK

**Comment by Paz-it** [comment]
I think @madsrh  did it already. His solution is very good.

**Comment by clobrano** [comment]
That was just a mockup. I have no printer to test this, could anyone show
the gtk inspector page with the classes? In the pictures above they're
always hidden

Il giorno ven 30 nov 2018, 22:15 Paz-it <notifications@github.com> ha
scritto:

**Comment by Paz-it** [comment]
@clobrano , I know It's just a  mockup :smile: 
What is hidden in my pictures above.
What exactly do you need to see in the gnome inspector?

**Comment by Feichtmeier** [comment]
name and style class and state
![image](https://user-images.githubusercontent.com/15329494/49390787-266a7c00-f72a-11e8-8e7d-48ee929b4c7a.png)

**Comment by madsrh** [comment]
Sorry @Feichtmeier but I'm not sure what I'm looking for here. Is this it?

![image](https://user-images.githubusercontent.com/3986894/50401090-23dcce80-078c-11e9-91ec-2462b847356d.png)

**Comment by clobrano** [comment]
@madsrh, sorry for the late reply. The screenshot is exactly what I meant, perfect

**Comment by clobrano** [comment]
unfortunately, I don't see any style class we can use to specify a different styling only for this widget. 

@madsrh, the mockup in [this comment](https://github.com/ubuntu/yaru/issues/699#issuecomment-412172215), did you make it changing the css or modifying the screenshot?

**Comment by madsrh** [comment]
> the mockup in this comment, did you make it changing the css or modifying the screenshot?

Sorry @clobrano this is GIMPed 😣 No CSS

**Comment by clobrano** [comment]
I feard that, so I think there's no way to do it. At least not to change only this occurence
