### ISSUE TITLE
Support for Unity7

### ISSUE THREAD

**Issue by khurshid-alam** [ubuntu/yaru#701]
Yaru gtk theme is missing unity specific [styles](https://wiki.ubuntu.com/Unity/Theming). For unity support take a look in Ambiance source 

https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/view/head:/Ambiance/gtk-3.20/apps/unity.css

Or at Numix source:
https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/apps/_unity.scss

[Styles](https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/files/head:/Ambiance/unity/) for window buttons (for unity-panel) and unity-launcher can also be provided in Yaru. But it is not mandatory.  

Thanks.

**Comment by Feichtmeier** [comment]
Hi @khurshid-alam thanks for the great links.

We come to can tackle this when there is some spare time - probably after 18.10 UI freeze

**Comment by madsrh** [comment]
> prio-low

but any code contributions are more than welcome @khurshid-alam 😉

**Comment by eaglersdeveloper** [comment]
> 18.10 UI freeze

When it will be?

**Comment by madsrh** [comment]
> When it will be?

One month from now 📆 

https://wiki.ubuntu.com/CosmicCuttlefish/ReleaseSchedule

**Comment by Feichtmeier** [comment]
Just a little update, I work on this atm - no promise that I succeed =)

![image](https://user-images.githubusercontent.com/15329494/48303484-f48b3e80-e50a-11e8-92b3-540130e33276.png)

Problematic is still that unity7 CSD patch : / if that one would be dropped, I think this could be quiet easy.
![image](https://user-images.githubusercontent.com/15329494/48303505-23091980-e50b-11e8-86fc-cfb7c517eba5.png)

**Comment by godlyranchdressing** [comment]
@Feichtmeier you should push and make a PR. I can help out with this one. I did it before, it's mostly the Unity 7 specific styling you'll need to grab from another theme and update to match Yaru. Then the SVG assets that Unity 7 looks for for the dash and elsewhere will need to be updated too.

**Comment by khurshid-alam** [comment]
I don't mind title-bar being dark for **Light** variant as well. Use `$headerbar_bg_color `for it and same for Panel. 

Unity doesn't really have a csd patch. It installs `gtk3-nocsd`. All it does is remove the close button from headerbar and put a tiitlebar above it. 

And, no, it can't be dropped.

**Comment by Feichtmeier** [comment]
Ohh! Great!:D

I am not with a pc ATM but I didn't do much yet. Only pasted the code from above into _apps.scss and changed the panel bg/colour to the shell panel colour and removed all that shadow and sunken effects. If you have time this evening just make another PR :D

**Comment by Feichtmeier** [comment]
Pushed the branch @godlyranchdressing

**Comment by fitojb** [comment]
FYI https://wiki.ubuntu.com/Unity/Theming

**Comment by godlyranchdressing** [comment]
I've done some work on this (the Unity panel looks fine), but for some reason not everything looks as it should. Padding and margins are all over the place and I just remembered that Unity might be using an older version of GTK3. Could that be the issue?

**Comment by luispabon** [comment]
You peeps made any further progress on this? :smile:

**Comment by luispabon** [comment]
Understood, and thank you :+1:

**Comment by Feichtmeier** [comment]
@khurshid-alam okay worked a bit on it and i could style everything except those incidcators, they stay gray, but also in ambiance, any tips?

![grafik](https://user-images.githubusercontent.com/15329494/64857577-37cfa580-d625-11e9-88b1-4af2df689fc5.png)
![grafik](https://user-images.githubusercontent.com/15329494/64857624-59309180-d625-11e9-9983-84c8eb6d5148.png)

**Comment by khurshid-alam** [comment]
@Feichtmeier 

Nice !

Which icon theme you are using ? You need to use ubuntu-mono-dark for dark panel.

**Comment by luispabon** [comment]
Maybe need to look at tweaking the top bar to choose the right icons in yaru, or adding to yaru the icons that are missing - these all look like fallback icons to me.

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/64860555-d06a2380-d62d-11e9-98c6-f341ee141a6e.png)
Yup the icon theme did the trick

Someone would have to draw "yaru title button assets" though.

**Comment by joaopauloalbq** [comment]
How should be:
![unity yaru](https://user-images.githubusercontent.com/9905202/81608598-eee71100-93ac-11ea-8c58-d70a1f3c631a.png)
