### ISSUE TITLE
Style Nautilus stop button on hover

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#706]
Releated to #705 🛑

This is what the hover effect currently looks like:
![image](https://user-images.githubusercontent.com/3986894/43982898-48916fbe-9cf8-11e8-9105-990db59cc5ce.png)

Upstream Adwaita: (I'm comparing to the Adwaita-dark because our background is dark too)
![image](https://user-images.githubusercontent.com/3986894/43982972-8a6970f8-9cf8-11e8-8443-ae9ef652514f.png)

Could we style this button similar to the round button in Widget factory:
![image](https://user-images.githubusercontent.com/3986894/43983141-4d975748-9cf9-11e8-90f8-3bbd2abc36d7.png)

A quick mockup:
![image](https://user-images.githubusercontent.com/3986894/43983162-664c6b66-9cf9-11e8-8482-fe9e069e0e18.png)

Or perhaps with some color, but this is a non-destructive action 🤷‍♂️ Anyway, just a suggestion because stop signs [are normally red](https://www.google.com/search?q=stop+button&safe=off&source=lnms&tbm=isch&sa=X&ved=0ahUKEwig452GwOPcAhWLNpoKHVRRAvgQ_AUICigB&biw=2021&bih=985)  
![image](https://user-images.githubusercontent.com/3986894/43983398-ac858166-9cfa-11e8-90de-423d1e8ec748.png)

**Comment by Feichtmeier** [comment]
If I would know how to trigger that stop button ? @madsrh

**Comment by Feichtmeier** [comment]
FIxed with https://github.com/ubuntu/yaru/pull/707
