### ISSUE TITLE
Record button icon barely visible

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#708]
first reported [here](https://github.com/ubuntu/yaru/issues/705#issuecomment-412237051)

In widget factory - the record button invisible:
![screenshot from 2018-08-11 03-12-08](https://user-images.githubusercontent.com/37431503/43986077-dfe6b5dc-9d15-11e8-9ec0-51244acd18c4.png)
Visible : 
![screenshot from 2018-08-11 03-12-44](https://user-images.githubusercontent.com/37431503/43986103-f90456d2-9d15-11e8-9b96-f98e81f7a385.png)

**Comment by clobrano** [comment]
I have come to conclusion that there isn't much we can actually do here. The two colors are simply too similar to be visible. Icon background is rectangular so we can't add some darker layer to highlight the icon, as well as there is no icon border to style.

I think we can close this safely, until such a combination appears on an application which is not a widget factory

**Comment by Paz-it** [comment]
From the inspector and "sound recorder app". the name of the icon is "media-record-symbolic"  so maybe it means icon is missing, something like "media-record-symbolic pressed" ?
![screenshot from 2018-08-13 00-13-32](https://user-images.githubusercontent.com/37431503/44006499-2c4be194-9e8e-11e8-869d-02d4b17a9fd1.png)
Not sure if you see it after closing though :smile:
