### ISSUE TITLE
Theme parsing error: gtk-dark.css:5479:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#709]
Probably due to some resent changes... :nerd_face:

**Comment by Feichtmeier** [comment]
Woops okay doing this later

**Comment by Paz-it** [comment]
There are places it's legit and in others it's not. I red something @didrocks said about it. Can't find it though... :woman_shrugging:

**Comment by clobrano** [comment]
> But that's strange... I think we use insensitive very often in drawing

probably in drawing.scss we use it as type name, but as pseudo-class just in one place. I'm going to fix this
