### ISSUE TITLE
Style GNOME Disks

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#714]
GNOME Disks uses the default selection color for the selected disk. In Yaru's case, that means we have a orange background with dark text over it. 

Current:
![image](https://user-images.githubusercontent.com/3986894/44059169-bf0bf6d2-9f50-11e8-9cf5-3a81b7433101.png)

And in backdrop:
![image](https://user-images.githubusercontent.com/3986894/44059841-ed5fe406-9f52-11e8-8b38-1c727154bc8c.png)

Can we change only the text color of the selected disk and keep the other ones dark?
![_2colors](https://user-images.githubusercontent.com/3986894/44059382-751a5fe0-9f51-11e8-9e98-cd72844adf07.jpg)

Another solution would be to use a brighter background (like gray) and add the orange selection border:
![_border](https://user-images.githubusercontent.com/3986894/44059406-90003b5e-9f51-11e8-9e7b-6b8d18ce75fb.jpg)

This is merely an enhancement, so If this issue is too much individual application styling, feel free to close it.

**Comment by Paz-it** [comment]
@madsrh , Just for competing to the dark : 
![screenshot from 2018-08-14 02-03-22](https://user-images.githubusercontent.com/37431503/44062817-b837c4ba-9f66-11e8-932c-3f1d96ee0754.png)
Hmm... The gray looks nice imo ..

**Comment by clobrano** [comment]
Selected disk background is decided in gnome-disks custom css, so we cannot change it.
About the label, is it true that in Ambiance the labels are white, however it looks like in Yaru (and Adwaita as well) it uses `@theme_fg_color` which is our `fg_color` that is `$inkstone`

**Comment by Feichtmeier** [comment]
I actually think, though gnome-disk-utility does not provide any style class or ID for these selected widgets, we could do the following "wildcard":

![peek 2018-09-18 11-34](https://user-images.githubusercontent.com/15329494/45678493-cc98e380-bb36-11e8-90b8-de6fe01c4bde.gif)

@clobrano 
Could you think of any negative effect for this? Replace "white" with "selected_fg_color" ofc

**Comment by clobrano** [comment]
With wild cards the risk is high, but we can try a PR
