### ISSUE TITLE
Some electron based applications use a white menu background color

### ISSUE THREAD

**Issue by otavioschwanck** [ubuntu/yaru#715]
![image](https://user-images.githubusercontent.com/9551316/44101377-b0dc5a26-9fbd-11e8-9da0-a432fad52797.png)

Atom and Visual Studio Code have a white toolbat, making very ugly to look.  

Other GTK 2 applications like franz, work nice:
![image](https://user-images.githubusercontent.com/9551316/44101435-ceeecb16-9fbd-11e8-9b3b-a50efe26abf8.png)

But, when try to change theme to adwaita, it have a black toolbar, even when i restart the application.
![image](https://user-images.githubusercontent.com/9551316/44101489-ec48d418-9fbd-11e8-8255-c4d83b58863c.png)

**Comment by Feichtmeier** [comment]
Hi thanks for reporting.

Both are based on electron, and are now using gtk3 =)
Just for the record! 

Doesn't reduce the fact that they have the wrong color ofc :)

**Comment by Paz-it** [comment]
That's an anomaly I see when on  communitheme snap with some applications. While trying to change theme some parts of communitheme are still present. It looks like a bug in snap session.
@otavioschwanck , are you seeing this issue using snap session?

**Comment by otavioschwanck** [comment]
@Paz-it yes, using snap session.  I'll try gnome session and Ubuntu session with XORG \ Wayland.  Report here soon.

**Comment by otavioschwanck** [comment]
@Paz-it same results in all sessions. 

New informations:
- On Arc Darker Theme, same result.  White Toolbar on Atom \ VSCode.  
- The ambiance theme is the only fine.  Black toolbar on VSCODE \ Atom and Franz.

Ambiance:
![image](https://user-images.githubusercontent.com/9551316/44106632-93eeac9e-9fcb-11e8-9f31-f3562558e3ad.png)

Arc Darker:
 
![image](https://user-images.githubusercontent.com/9551316/44106647-9dc24000-9fcb-11e8-9a52-b1909ca53a94.png)

i installed ubuntu 2 days ago.
In this two days, the VSCODE \ Atom bar are black on communittheme.  Today i upgraded my system and the bar is white.

**Comment by clobrano** [comment]
> Gtk2 apps included. While trying to change theme some parts of communitheme are still present

Have you tried rebooting Gnome shell? Those might be server side decorations that don't go away otherwise

**Comment by otavioschwanck** [comment]
@clobrano yes.  Rebooted gnome shell in every change using "r". Also rebooted the system too.

**Comment by clobrano** [comment]
@otavioschwanck Ok, @Paz-it you did the same?

**Comment by otavioschwanck** [comment]
I'm using a deb version of atom, vscode and franz.

**Comment by Paz-it** [comment]
>   
Yes,I did the same.

**Comment by Feichtmeier** [comment]
I don't understand this...

Electron uses GTK3 dialogues now. 
But is it possible that the menu is still styled with gtk2 styling? :thinking:

**Comment by skqnder** [comment]
Same here. Using communitheme snap, vscode (deb) shows a white menu bar.

![image](https://user-images.githubusercontent.com/11521400/44290703-d9919100-a271-11e8-925d-6193994190ea.png)

Not sure if it helps but the menu bar follows _Adwaita-dark_ theme.

![image](https://user-images.githubusercontent.com/11521400/44290739-0c3b8980-a272-11e8-9060-aace6e750108.png)

**Comment by clobrano** [comment]
> Both are based on electron, and are now using gtk3

@Feichtmeier when did this change happen? I remember electron apps where styled after gtk2

**Comment by Feichtmeier** [comment]
@clobrano some weeks ago

**Comment by clobrano** [comment]
Weird, because in #728 menu bar works like it's using GTK2 colors

**Comment by clobrano** [comment]
vscode uses the dark menubar when using yaru dark variant

**Comment by clobrano** [comment]
@otavioschwanck 

>VS Code in ElementaryOS after upgrade, changed the toolbar to the inverse color, like in communittheme. Maybe is a electron issue?

not sure if I understood. Who changed the toolbar?

**Comment by clobrano** [comment]
However, electron project opened a bug about this and there's a PR in progress, so I guess it's an upstream issue

https://github.com/electron/electron/issues/13381

**Comment by Feichtmeier** [comment]
I'd say let's close this here then? :) If it's handled upstream

**Comment by clobrano** [comment]
Fix has been merged https://github.com/electron/electron/pull/14785

**Comment by Feichtmeier** [comment]
@clobrano 
Funny random coincidence, this would be fixed by the jet menus =)
https://discourse.ubuntu.com/t/mockups-new-design-discussions/1898/311

**Comment by Feichtmeier** [comment]
Since the fix is in electron let's close it here
