### ISSUE TITLE
Black line in right-click menu in Thunderbird

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#718]
Yaru from stable snap

When I right click in Thunderbird to open menu, I see the horizontal line separator is "very black" :P 

Sample screenshot:
![zrzut ekranu z 2018-08-14 18-28-19](https://user-images.githubusercontent.com/1629120/44108091-3f799432-9ff1-11e8-8924-880aaaccbf0b.png)

**Comment by Feichtmeier** [comment]
Could you check if this also happens with the new thunderbird?
Maybe we are lucky and safe work and this does not occur there.

https://www.omgubuntu.co.uk/2018/08/thunderbird-60-release-features

**Comment by Feichtmeier** [comment]
Just checked it myself, the black line is not there:

![peek 2018-08-15 17-32](https://user-images.githubusercontent.com/15329494/44156831-3560ec00-a0b1-11e8-99d5-b7d2719dcdc8.gif)

Are you okay with closing this then?
The update should hit ubuntu in some weeks/months

**Comment by mivoligo** [comment]
Awesome. Feel free to close this issue.
