### ISSUE TITLE
No color on toggle for pop!os Do Not Disturb extension

### ISSUE THREAD

**Issue by taciturasa** [ubuntu/yaru#724]
What I tried: Using the pop!os Do Not Disturb gnome shell extension, which adds a do not disturb toggle to the notifications menu

What happened: The toggle has no background, no green for enabled or faded for disabled. Both states have the same transparent background, like this.

![screenshot from 2018-08-16 13-46-22](https://user-images.githubusercontent.com/18127936/44225185-ca6bef80-a15a-11e8-8563-0e3f59ade955.png)
![screenshot from 2018-08-16 13-46-08](https://user-images.githubusercontent.com/18127936/44225186-ca6bef80-a15a-11e8-9f87-9b945d18e7a6.png)

**Comment by Feichtmeier** [comment]
Hi @taciturasa 
Is this somehow related to this? : https://github.com/pop-os/pop/issues/185

Anyways, this extension is not even on the official extension site. 
Could you check how it behaves with other themes?

**Comment by taciturasa** [comment]
Nope, sorry to make you go through all this. Apparently it's a first install issue - need to get into the habit of restarting under Wayland.

I'll go ahead and close the issue.
