### ISSUE TITLE
Change progressbars color

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#726]
I don't know what this bar is called (CellRenderProgress?), but IMO the white looks a bit odd. It's also a bit unnecessary here because of the orange selection which makes it very obvious which column is selected. Maybe we could just leave it blue?

Current:
![image](https://user-images.githubusercontent.com/3986894/44225659-5ea37a00-a18e-11e8-8b8a-c157ed9ed759.png)

Mockup:
![image](https://user-images.githubusercontent.com/3986894/44225652-58150280-a18e-11e8-9f13-c44a1edc9480.png)

Or here using the text selection color:
![image](https://user-images.githubusercontent.com/3986894/44235924-9240cd00-a1ab-11e8-91b3-dc60f8101f46.png)

Is this perhaps the same type of bar that is found in Transmission?
![image](https://user-images.githubusercontent.com/3986894/44230243-e5f6ea80-a19a-11e8-8619-83adc69dc20a.png)

Which would look like this with blue:
![image](https://user-images.githubusercontent.com/3986894/44230237-e1323680-a19a-11e8-8bb7-7b223b4ade8d.png)

**Comment by Feichtmeier** [comment]
Hm, the blue is indeed better to see, yet when the orange and our blue collide it can become a bit heavy colored. 
But usability wise the blue is indeed better.

**Comment by Paz-it** [comment]
My question is whether there is a way not to color the "through" when selected?

**Comment by clobrano** [comment]
@madsrh sorry, could you tell me which application is that? :)

**Comment by madsrh** [comment]
> sorry, could you tell me which application is that? :)

That's actually the _gtk3-demo_ and the other one is (as I'm sure you know) Transmission

**Comment by clobrano** [comment]
Ah ok, the demo opened with a small window and didn't show the bars at the beginning :+1:

**Comment by clobrano** [comment]
Not a single chance, this is update-manager's code. `tag` is a weblink.

```
tag = self.buffer.create_tag(None, foreground="blue",
                                     underline=Pango.Underline.SINGLE)
```

**Comment by madsrh** [comment]
🤦‍♂️ 

Yeah, I noticed that all other themes have the same issue 🤷‍♂️ 

Do you have a link to the upstream project? We should create a bug.

**Comment by clobrano** [comment]
Here is the [upstream bug](https://bugs.launchpad.net/ubuntu/+source/update-manager/+bug/1788572)

**Comment by clobrano** [comment]
Sorry, this is the wrong issue :man_facepalming:
