### ISSUE TITLE
Application menu icon to big when remove it from top panel (on gnome-terminal)

### ISSUE THREAD

**Issue by otavioschwanck** [ubuntu/yaru#729]
On nautilus (ok):
![image](https://user-images.githubusercontent.com/9551316/44299289-759ab700-a2c9-11e8-88f3-3e6acad4283f.png)

On terminal:
![image](https://user-images.githubusercontent.com/9551316/44299292-7b909800-a2c9-11e8-8d8d-86012382920d.png)

When hover:
![image](https://user-images.githubusercontent.com/9551316/44299303-8a774a80-a2c9-11e8-9cbe-418c3d482d23.png)

in other icon themes this does not happen

**Comment by Feichtmeier** [comment]
![peek 2018-08-18 16-38](https://user-images.githubusercontent.com/15329494/44300311-1eb2d300-a305-11e8-9e9b-eb34eaba4f1f.gif)

Can't reproduce this?
Do you have the SUru icon theme selected?

**Comment by clobrano** [comment]
This looks like this bug https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1770507
