### ISSUE TITLE
Missing system tray icons of Some Application that is visible when logged in without communitheme

### ISSUE THREAD

**Issue by iam-i5h4n** [ubuntu/yaru#731]
## Expected Behavior

System tray icons should be visible completely. Like this:
![screenshot from 2018-08-20 14-54-19](https://user-images.githubusercontent.com/41895860/44330914-04563200-a48a-11e8-9652-8656f5110f00.png)

## Actual Behavior

System tray icon of Odrive (leftmost icon on the upper screenshot) is not visible in communitheme,but is visible when logged without commutheme.
![screenshot from 2018-08-20 14-55-07](https://user-images.githubusercontent.com/41895860/44331029-497a6400-a48a-11e8-81b4-6bca65b4958e.png)

## Steps to Reproduce the Problem

  1. Download Odrive google desktop client from here: https://liberodark.github.io/ODrive/
  2. Open the linux AppImage.
  3. Let the Application run in system tray.

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

 ```
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: didrocks
license:   unknown
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: today at 14:48 +06
channels:                   
  stable:    0.1 (742) 10MB -
  candidate: ↑              
  beta:      ↑              
  edge:      0.1 (756) 10MB -
installed:   0.1 (756) 10MB -
```
Note: Tried in both stable and edge channel, switching channels doesn't fix the issue.

**Comment by Feichtmeier** [comment]
@iam-i5h4n didn't know this google drive client exists =) Awesome!

Anyways, I bet they didn't merge the latest Electron changes yet.
@didrocks tackled this upstream and made every electron indicator look up for both the normal ubuntu gnome session and t he communitheme session. It is already fixed for Skype, Discord and so on which are all electron built. 
So you should open an issue on that repo and request to merge the latest electron :)

Closing this since I am 99% sure about this
