### ISSUE TITLE
Change link color in changelog view in updater

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#740]
Is there any chance that we can change this?

The light theme we can live with, but in the dark theme the link text is almost impossible to read:

![image](https://user-images.githubusercontent.com/3986894/44487018-6f079900-a655-11e8-977f-d085a904902d.png)

![image](https://user-images.githubusercontent.com/3986894/44486978-58614200-a655-11e8-9e5b-08e550416d20.png)

**Comment by clobrano** [comment]
Not a single chance, this is update-manager's code. `tag` is a weblink.

```
tag = self.buffer.create_tag(None, foreground="blue",
                                     underline=Pango.Underline.SINGLE)
```

Here is the [upstream bug](https://bugs.launchpad.net/ubuntu/+source/update-manager/+bug/1788572)

**Comment by clobrano** [comment]
I am closing this, since once the upstream bug will be solved, update-manager will use our link colors which are nice for both light and dark variants.
