### ISSUE TITLE
OSD icons' vertical position inside the panel

### ISSUE THREAD

**Issue by skqnder** [ubuntu/yaru#742]
This _issue_ isn't exactly related to Yaru, but I believe it can be fixed independently of upstream.
When enabling/disabling sound and brightness using keyboard shortcuts, the icons look like they jump up and down:

![peek 2018-08-23 12-47](https://user-images.githubusercontent.com/11521400/44529670-9194c300-a6e4-11e8-8427-d4d8487ff276.gif)![peek 2018-08-23 12-48](https://user-images.githubusercontent.com/11521400/44529696-a07b7580-a6e4-11e8-8338-a584c691f99a.gif)

I think it is better if the icons stay in the same position while changing state. Something like the touchpad icon:

![peek 2018-08-23 15-00](https://user-images.githubusercontent.com/11521400/44530043-76768300-a6e5-11e8-97d3-7a7b65731bb7.gif)

If the icons can't be repositioned, could this be fixed with a little transparent space at the bottom of the "disabled" icons to compensate for the progressbar?

**Comment by clobrano** [comment]
Hi @skqnder, thanks for reporting this and contributing to Yaru.

> This issue isn't exactly related to Yaru, but I believe it can be fixed independently of upstream.

This could  be probably done, but upstream should fix this as well and we would just duplicate the work, so I believe this should be reported upstream instead. If you need help for this, or you just can't do it, let us now!

closing this

**Comment by skqnder** [comment]
Duplicated the issue upstream [#506](https://gitlab.gnome.org/GNOME/gnome-shell/issues/506).
