### ISSUE TITLE
Insensitive borders does not look insensitive 

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#746]
It's a bit odd that the insensitive spinbutton border is darker than the active one - IMO it makes it look active. 

Current:
![image](https://user-images.githubusercontent.com/3986894/44681687-9c7f8880-aa41-11e8-8f6b-b880ce518952.png)

If I switch the borders (dark border on active and gray border on insensitive)
![image](https://user-images.githubusercontent.com/3986894/44684243-dbfda300-aa48-11e8-8522-e8bf4b3cc530.png)

Here's the current (for reference):
![image](https://user-images.githubusercontent.com/3986894/44683841-ad32fd00-aa47-11e8-9867-7a8354a09149.png)

Perhaps doing something like this?
![image](https://user-images.githubusercontent.com/3986894/44683546-f33b9100-aa46-11e8-80d6-f5a07b0a933d.png)

This is just extending the already used border color from the dropdown arrow:
![image](https://user-images.githubusercontent.com/3986894/44683704-52010a80-aa47-11e8-9ae0-6fdfcdbc4fd3.png)

I also tried a brighter border, but that didn't work: 🗑 
![image](https://user-images.githubusercontent.com/3986894/44683778-85dc3000-aa47-11e8-98e2-5acdb5f82375.png)

@Feichtmeier ?

Also shouldn't the background be transparent like with the switches? Or is it fine because radios have a lighter background too 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/3986894/44681857-1b74c100-aa42-11e8-88e5-cc2f977eaef0.png)

---
EDIT: sorry if I tweaked the main post, but let's keep a list of the changes here ;)

## spinbutton insensitive
- [ ] border be the same color as insensitive button
- [ ] (vertical) number box border be the same color as insensitive button

## entries insensitive
- [ ] border be the same color as insensitive button (see comboboxes)

~## radio/check and switch insensitive~ see  #763
~- [ ] (unchecked) background be a lighter version of normal radio/check and not transparent~

**Comment by ya-d** [comment]
I have this on my list too. Vertical insensitive spin buttons currently even have a mixed style for their borders.

<img width="124" alt="spinbutton vertical insensitive" src="https://user-images.githubusercontent.com/30781876/44684144-8f19cc80-aa48-11e8-8954-924025386bc4.png">

I would vote for Mads suggestion of more subtle border color which would also match insensitive buttons.

<img width="155" alt="dark_buttons" src="https://user-images.githubusercontent.com/30781876/44684225-d30cd180-aa48-11e8-8459-e39be1413e12.png">

> Also shouldn't the background be transparent like with the switches? Or is it fine because radios have a lighter background too 🤷‍♂️

Thats consistent with the regular theme at least. And with combo boxes where the entry field is lighter than the button.

--

Am I ok to add some more (very, very) minor dark theme glitches/observations here? I'm happy to open separate issues if you prefer... I don't include screenshots for now, but can be checked with widget factory easily.

* The button hover effect looks a little bit too harsh (too black) to me. (discussion)
* The "close tab" button has a different hover effect for dark (darker text color + grey background) and regular (only different text color) theme variant.
* To match the styling of the non-dark theme, the background of tab bars should be darker (like window background).

**Comment by Feichtmeier** [comment]
I don't thin that we should make the switches bg transparent.

The insensitive border is indeed to dark! I'll fix this

**Comment by ya-d** [comment]
The point was that insensitive switches and buttons are "transparent" (bg color) while spin buttons and entry fields are a bit lighter than that. That's the same for the regular theme though.

**Comment by ya-d** [comment]
I just noticed that the regular theme also uses two different colors for the insensitive states. They are used for the exact same places but the difference is much more subtle than in the dark variant.

**Comment by Feichtmeier** [comment]
Yes would be great if we could put 1 change request in 1 issue <.<
I already lost everything beside the border color for insensitive elements which is really too dark

**Comment by clobrano** [comment]
I am in favor of current insensitive radio/check. It comes from a specific design and it's the only widget which is pure white when active. I would suggest to do the insensitive spinbuttons the same as radio/check

**Comment by Feichtmeier** [comment]
No that's fine here the tilte fits :)

**Comment by madsrh** [comment]
Okay, so following @clobrano's suggestion of using a lighter border, here are some "real world" mockup:
I'm surprised, but I actually really like this 😊 Especially [comparing to the current](https://user-images.githubusercontent.com/3986894/44943566-b9f97d00-adc8-11e8-8879-624a45fe3c0c.png). 

NOTE: Insensitive elements have transparent background
![image](https://user-images.githubusercontent.com/3986894/44943566-b9f97d00-adc8-11e8-8879-624a45fe3c0c.png)


![image](https://user-images.githubusercontent.com/3986894/44943536-62f3a800-adc8-11e8-904e-048503930a01.png)

![image](https://user-images.githubusercontent.com/3986894/44943540-74d54b00-adc8-11e8-9de7-f56121a0ee84.png)

**Comment by Feichtmeier** [comment]
To understand you correctly: additionally to tabs you also want disabled elements to have the bright border?

**Comment by clobrano** [comment]
What about comboboxes with button and entries? Button would have dark border and entries light one

**Comment by madsrh** [comment]
> What about comboboxes with button and entries?

![image](https://user-images.githubusercontent.com/3986894/44944475-a43f8400-add7-11e8-9625-3831484cd7b2.png)

> Button would have dark border and entries light one

Buttons would/should, like "Otto" below/above also use light borders:
![image](https://user-images.githubusercontent.com/3986894/44944480-fa142c00-add7-11e8-83c0-12776af7c83b.png)

@Feichtmeier might be right that we should revisit this aften FF, but I sense your scepticism 😉 I hope you can at least agree with me, that what we currently have is a bit confusing 😕 

Bordercolors for insensitive elements:
![image](https://user-images.githubusercontent.com/3986894/44944596-0c8f6500-adda-11e8-85d1-90b962a62b29.png)

**Comment by madsrh** [comment]
Just to clarify: Initially I created this issue to remove #202020 and #222222 (see above). Any change would definitely require a lot of testing. 

IMO there's two options:
1. Light border (as seen above)
2. Semi dark borders like #2e2e2e 

The mockup below looks a bit odd with the light border, but again, it's hard to know how this feels in the real
![image](https://user-images.githubusercontent.com/3986894/44945041-8840e000-ade1-11e8-90a8-3de7866a4d0e.png)

![image](https://user-images.githubusercontent.com/3986894/44945044-8f67ee00-ade1-11e8-8f26-ce3edeb48783.png)

**Comment by clobrano** [comment]
Press effect sure doesn't work with bright borders buttons. This is why I am working on notebook tabs borders in order to keep buttons and entries as they are now

**Comment by clobrano** [comment]
Why don't we just use #2e2e2e for insensitive borders in buttons and entries? Radio and check are already different in normal state, so it doesn't feel wrong if they differ in insensitive and backdrop too

**Comment by clobrano** [comment]
Alright, I updated todos, let's keep this bug for fixes, and eventually we'll work on improvement in another bug/discussion

**Comment by madsrh** [comment]
Reopening this issue because disabled toggle switches borders weren't changed (still too dark / should match spinbutton)

![image](https://user-images.githubusercontent.com/3986894/45267900-1ae21e80-b475-11e8-8183-ef1b13912fa8.png)

**Comment by clobrano** [comment]
I forgot, sorry

**Comment by clobrano** [comment]
> (still too dark / should match spinbutton)

like spinbutton or like radio/check?

**Comment by madsrh** [comment]
Doesn't it make most sense with the spinbutton? I was looking at your PR here https://github.com/ubuntu/yaru/pull/764

**Comment by clobrano** [comment]
Normal

![image](https://user-images.githubusercontent.com/2883614/45283824-31bd5b00-b4df-11e8-86c5-6307c096c4ff.png)


Backdrop
![image](https://user-images.githubusercontent.com/2883614/45283957-8d87e400-b4df-11e8-94bf-0755a9f6fad9.png)

**Comment by madsrh** [comment]
😄 I just finished some mockups. 

Seems dark, but it's hard to say without trying it. IMO the light one seems too bright 🤷‍♂️ 

It's funny the with the light theme, we style the toggle VERY subtle and radio and spinbuttons the same.

![image](https://user-images.githubusercontent.com/3986894/45283636-b22f8c00-b4de-11e8-860d-aed992e80361.png)

![image](https://user-images.githubusercontent.com/3986894/45284192-2585cd80-b4e0-11e8-94c6-d5a8eb6c1d7e.png)

**Comment by Feichtmeier** [comment]
I still agree on the initial issue - this dark border is too dark.

But... could you double check where that insensitive border is being used in common? Or wasn't it somehow connected to borders edge? I have some bad memory about this border's strange using places but I could be wrong :thinking:
