### ISSUE TITLE
Cursor theme: switch from black to white background for "watch" spinner – distracting?

### ISSUE THREAD

**Issue by ya-d** [ubuntu/yaru#751]
I noticed that Yaru uses a black cursor theme derived from DMZ-Black but than uses a "watch" spinner on a *white* background (à la DMZ-White). I found this switch to be a bit distracting but I'm not yet sure if its really an issue or just noticeable because its uncommon. Is there a specific reasoning behind this decision?

**Comment by Feichtmeier** [comment]
Hi, we use an untouched fork of the suru repo

He originally had a black spinner BUT with no blue at all. We really liked Mads blue spinner but liked the overall finish of the suru cursor so we went full suru. Snwh accepted our desire for a blue spinner and that's his interpretation now.
I don't think that it is really a consistency issue here. If you feel like it's really need to change it you can ask this on the suru upstream repo
