### ISSUE TITLE
Tab implementation slightly differs for regular and dark theme

### ISSUE THREAD

**Issue by ya-d** [ubuntu/yaru#754]
Just an observation, I'm not sure if this is an oversight or if there is good reason to it. 

* The "close tab" button has a different hover effect for dark (lighter text color + grey background) and regular (only different text color) theme variant.
* Tab bars in dark theme share the background with their "content"/widget part while in the regular theme they use the background color of the window.

![tabs dark](https://user-images.githubusercontent.com/30781876/44750349-67dd0100-ab15-11e8-8308-77f264443f15.png)
![tabs regular](https://user-images.githubusercontent.com/30781876/44750350-68759780-ab15-11e8-97a1-b830de28c4b7.png)

**Comment by ya-d** [comment]
The equivalent hover effect for the light theme would be grey of of course (like it is in menus for example).

**Comment by clobrano** [comment]
Of course, but grey doesn't look as good as the brighter color in dark variant I think

**Comment by clobrano** [comment]
Closing this
