### ISSUE TITLE
Radio/checkboxes fine tuning

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#763]
Dark theme:
- [ ] Add hover effect to uncheck radio/checkboxes
- [ ] Remove background for insensitive radio/checkboxes
- [ ] Remove background for insensitive radio/checkboxes in backdrop

Light theme:
- [ ] Remove background for insensitive unchecked radio/checkboxes _(a victim of consistency)_

@clobrano @Feichtmeier are you +1 ? Screenshot?

**Comment by clobrano** [comment]
I think that consistency shouldn't backfire from one variant to the other. If we like current light as it is, let's keep it.

**Comment by madsrh** [comment]
> I think that consistency shouldn't backfire from one variant to the other. If we like current light as it is, let's keep it.

Maybe I was a bit strong worded. I'm fine with both, but want to push for that _insensitive = transparent background_ - it's a very subtle change.

A gif for comparison:
![background](https://user-images.githubusercontent.com/3986894/44945650-56824600-adee-11e8-8e9c-414122d330ea.gif)

**Comment by Feichtmeier** [comment]
If it doesn't have any negative impact, and check boxes are mostly drawn upon the correct background (one thing that would be problematic is if the transparent check box is placed upon a transparent background ) we could test this at least :+1: :)
