### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by letheed** [ubuntu/yaru#775]
I wanted to give some user feedback on the theme, I've only started using it recently, but wasn't sure where was more appropriate. Feel free to close this after discussion.

### Separators
* **GTK** Separators in menus are barely visible at all. Separators in the sidebar of Nautilus or in gnome-shell menus for example have a lot more contrast. I think it would be helpful in long menus if they were a bit darker. No need for full black lines, but just a bit more visual support.
* **Gnome Shell** The padding around separators is really large. They take as much room as an actual entry. And a lot of menus have only one entry between separators. I don't actually know if that can be tweaked but all this empty space feels unpleasant and wasted, and it's incoherent with GTK menus and how other separators look. Case in point: the VSCode menu is almost twice bigger than necessary:
![capture d ecran de 2018-09-03 18-23-00](https://user-images.githubusercontent.com/5330692/44996308-81fc6080-afa7-11e8-8702-5abb43bd7610.png)

### Fonts
* **Interface:** The new interface font size (10) is a tad too small for my taste. Now I'm a bit split on that. I've often found the old default of 11 was too big. But I worry that not everyone using Ubuntu is going to be comfortable reading size 10 all day, depending on their screen and sight. I guess it's an issue with the Ubuntu font directly (that 10 be a bit small but 11 be too big). I wear glasses and my eyes tire easily, so I've personally settled on 10.5, which seems to keep the height of 11 but makes it thinner, removing the impression of bold that 11 has, and shrinking width. I guess trying 10 for one release could be useful. If people find it too small, some will speak up. I don't know if fractional values would be appropriate for an OS default.
* **Window title:** Bold 11 is good.
* **Monospace** is 13, which is way too big. The matching font for Ubuntu Regular 10 is Ubuntu Mono Regular 11. Like before I find this a tad too small so I've matched the interface's 10.5 with 11.5 for Mono. I think it should at the very least be dropped to 12. It was too big even before.
* **Document:** I'm not sure which applications make use of it. The default font in Libre Office is Liberation Serif 12. Ubuntu Regular 10.5 is close enough so I've set it to that. 11, the current default, is bigger, though not a lot. 10 might be too small again.
* **Gnome Shell:** Font appears really big compared with the rest of the interface. Seems to be size 12. It could probably be dropped to 11, like window titles, so as to not stand out so much from the rest of the interface.

### Gnome Shell
Gnome shell seems to use a lot of screen space by default. That's not yaru's fault, but I'd like the shell theme to be a bit more conservative where it can regarding consumed space. I've mentioned separators above because they seemed like one obvious culprit to me. Here's a gnome-shell menu vs a menu in Firefox:
![capture du 2018-09-03 18-46-23](https://user-images.githubusercontent.com/5330692/44996834-78c0c300-afaa-11e8-8afa-bec56703f371.png)
Without going as far as making it as dense, I think there is room for some improvement.

Other example, the calendar/music/weather/notification menu.

![capture d ecran de 2018-09-03 19-08-04](https://user-images.githubusercontent.com/5330692/44997219-069dad80-afad-11e8-952a-5ba9669d3dbe.png)

Lots of padding all around. Lots of bold fonts. The space below the days of the week and around the month selector seems unnecessarily large. Can anything be done regarding the always empty area below the weather report?

I won't list more, the same general critique seem to apply all around in the gnome-shell interface. It's very flat and lacking in visual support with too much empty space. I was hoping that Yaru might be able to remedy *some* of that, though I don't know how much can be tweaked.

### Colors
They work really great as focus colors. Both in the top bar and in the calendar above, the orange works really well. The only criticism that I have is that they are a bit too bright when using them as background colors. White text in particular takes on some of the color which makes it less defined, and a bit harder to read. Bright saturated colors can also be a bit difficult to stare at in big quantities. E.g. in the sidebars of nautilus or the settings app).

![capture d ecran de 2018-09-03 19-46-52](https://user-images.githubusercontent.com/5330692/44998032-9abe4380-afb2-11e8-98ba-9a22539f2ccc.png)

Another example with the green color and a comparison with a Github button. Github uses a similar green but has a much thicker font. The text appears more white and well defined all around.

![capture d ecran de 2018-09-03 19-47-07](https://user-images.githubusercontent.com/5330692/44998035-9eea6100-afb2-11e8-9c74-7ff24de41a3b.png)

Don't get me wrong, I like the colors. They're great for buttons, focus, etc. But they're always used in small quantities in those cases, and don't affect legibility. I don't know what the best fix would be. Color palette declinations, some text shadow, ...

## Last words

Now I don't want this to sound like just a long rant so I'll finish on more positive notes. Overall I enjoy the theme. I've read the design documents. It's obvious a lot of thought and consideration went into it's design, and it manages to look modern even without going fully flat (eg. for tabs). It's going to be a great update from Ambiance.

For icons I'll stick to La Capitaine though. Nothing looks even remotely as good, and when it comes to folder icons, there is such a thing as *too much* orange on my desktop...

**Comment by Feichtmeier** [comment]
We can take a look at gnome shell padding and margin. But probably after 18.10 release. Thanks for the feedback.

Would be cool if you could open a concrete issue with the gnome shell padding. It's pretty upstream at the moment and it's tricky because the same styling is used in different places. 
Just be very concrete in that issue. I close this issue here after you opened the new one. Best regards and thanks for reporting

**Comment by Paz-it** [comment]
Thanks a lot for taking the time to give such a thorough feedback from an end user point of view, @letheed  . I personally find the selected fonts a bit tiresome without a text shadow.  A light from above and a dark shadow below will help a lot to make the fonts pop and much more clear. So I'll join @Feichtmeier request to open a separate issues for those two (Gnome-shell Padding and text-shadow on selected fonts).   I wear glasses as well and also play with fonts sizes for better visibility, Text-shadow on selected white fonts can really help.

**Comment by madsrh** [comment]
> Thanks a lot for taking the time to give such a thorough feedback from an end user point of view, @letheed

+1 😄 

> Gnome Shell The padding around separators is really large. They take as much room as an actual entry. And a lot of menus have only one entry between separators. I don't actually know if that can be tweaked but all this empty space feels unpleasant and wasted, and it's incoherent with GTK menus and how other separators look. 

I agree that it looks odd next to the GTK menus. I think we already discussed this (on the hub maybe?), but here we follow upstream and their reason for the spacing is for menus to be touch friendly (tablet, phone,...).
IMHO this effort is half baked since, as you mentioned, the GTK menus aren't optimized for touch 🤷‍♂️ 
 
![image](https://user-images.githubusercontent.com/3986894/45075783-8c724380-b0e8-11e8-817c-3558a894aad7.png)


> The space below the days of the week and around the month selector seems unnecessarily large. 

Again we follow upstream here. Everything is in a grid, so moving the days further down will just look unbalanced to me. Here is a very inaccurate mockups:
![image](https://user-images.githubusercontent.com/3986894/45075593-e45c7a80-b0e7-11e8-804b-513260856d2a.png)

> Can anything be done regarding the always empty area below the weather report?

I think the height of the popup is fixed. @Feichtmeier will know 😉 
![image](https://user-images.githubusercontent.com/3986894/45076239-ef180f00-b0e9-11e8-9655-eab926cac2bd.png)

> Another example with the green color and a comparison with a Github button. Github uses a similar green but has a much thicker font. The text appears more white and well defined all around.

I think the current font weight is fine, but I guess is would bring more focus to the text
![peek 2018-09-05 00-03](https://user-images.githubusercontent.com/3986894/45076649-3bb01a00-b0eb-11e8-8c2d-c2d4e9404d77.gif)

However, I don't think the same applies to the sidebar. It looks much better that selected and unselected entries have the same weight IMO.

![bold](https://user-images.githubusercontent.com/3986894/45077745-44eeb600-b0ee-11e8-8cd7-43022c6fef98.gif)

**Comment by Paz-it** [comment]
> However, I don't think the same applies to the sidebar. It looks much better that selected and unselected entries have the same weight IMO.
I agree with you, @madsrh  . I think in your muck-up the green button text looks better when you changed the font-weight, at least for my eye site. without it it looks blurred a bit, like blending into the green color.
