### ISSUE TITLE
Terminal scrollbar extends out of window under Wayland

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/yaru#777]
## Expected Behavior

Scrollbar of GNOME terminal should be within window.

## Actual Behavior

Scrollbar seems to extend 1pix to the right and 1 pix to the bottom of the window. See screenshot:
![terminal-sbar](https://user-images.githubusercontent.com/1141694/45076689-f7208080-b0e2-11e8-9d50-b98437e68076.png)

## Steps to Reproduce the Problem

  1. Use Wayland session
  2. Start GNOME terminal

## Specifications

I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

```
r19-54-g69c8db4a
```

Software that presents the issue:
- Name: GNOME Terminal
- Version: 3.28.2

**Comment by CDrummond** [comment]
Hmmm... Sorry for the noise, this appears to be **only** with the default Ubuntu Wayland session - not Communitheme/Yaru wayland.

**Comment by febcrash** [comment]
Same problem on ubuntu 18.10 (Cosmic) on Wayland session
![2018-10-24_11-25](https://user-images.githubusercontent.com/5707986/47566869-3b830c80-d92d-11e8-87ca-76f9ef5d2a41.png)

**Comment by Feichtmeier** [comment]
@febcrash could you install gnome-session and see if this happens too? Best regards

**Comment by Feichtmeier** [comment]
Just checked that in 18.10 GNOME Wayland session with adwaita theme and this also happens there, thus I am closing this here:
![image](https://user-images.githubusercontent.com/15329494/49389715-42205300-f727-11e8-8985-361a51f18fb5.png)
