### ISSUE TITLE
GTK Separators in menus are barely visible

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#778]
From issue #775 

> GTK Separators in menus are barely visible at all. Separators in the sidebar of Nautilus or in gnome-shell menus for example have a lot more contrast. I think it would be helpful in long menus if they were a bit darker. No need for full black lines, but just a bit more visual support.

Gif (Current vs. darker):
![lines](https://user-images.githubusercontent.com/3986894/45077112-9c8c2200-b0ec-11e8-9091-e60d6073046c.gif)

Perhaps just match this one:
![image](https://user-images.githubusercontent.com/3986894/45077147-b6c60000-b0ec-11e8-9138-2a533d322ac7.png)

Thanks @letheed

**Comment by Feichtmeier** [comment]
I must admit that I prefer subtle separators. Imho dark borders make an element look a bit old. Especially if you are playing with tones of gray.
But your mock-up is maybe a better fit. Maybe a little bit less dark.

**Comment by Feichtmeier** [comment]
@madsrh 

How about this:

![image](https://user-images.githubusercontent.com/15329494/45088811-71b0c680-b10a-11e8-9573-2e9806008305.png)

![image](https://user-images.githubusercontent.com/15329494/45088839-8e4cfe80-b10a-11e8-8314-8f95a08d7893.png)

Or maybe a little less than this but still darker than current:

![image](https://user-images.githubusercontent.com/15329494/45088893-b3da0800-b10a-11e8-8876-587ab1504cde.png)

![image](https://user-images.githubusercontent.com/15329494/45088925-cd7b4f80-b10a-11e8-9410-14d3484014d3.png)

**Comment by madsrh** [comment]
> Or maybe a little less than this but still darker than current:

This one looks good to me 👍
