### ISSUE TITLE
Wrong text color for selected labels in Nautilus

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#781]
The **text 25 Jul 0 Items** shouldn't be gray. Perhaps white or a semi transpartent like #f4c1b6

![image](https://user-images.githubusercontent.com/3986894/45089790-9e1a1200-b10d-11e8-9a8f-1a41f1f0f0b5.png)

![image](https://user-images.githubusercontent.com/3986894/45089636-146a4480-b10d-11e8-9251-fe11f6f35678.png)

**Comment by Feichtmeier** [comment]
Like this?

![image](https://user-images.githubusercontent.com/15329494/45089889-efc29c80-b10d-11e8-9efd-583e10a0a6b7.png)
