### ISSUE TITLE
Popover and context menu borders differ & dark popovers are hard to see

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#783]
Currently we have two colors used here
$borders_color for the popover
transparentized(black,0.5) for th context menus

In the light theme it's perfectly visible, also because the drop shadow can be seen (because it's a dark shadow on a light bg :| ):
![image](https://user-images.githubusercontent.com/15329494/45091385-88f3b200-b112-11e8-90ad-b563b88cfd17.png)

The dark version on the other side is hardly visible on the darkest color (base color):
![image](https://user-images.githubusercontent.com/15329494/45091476-de2fc380-b112-11e8-8809-15a0f4816b57.png)

On the bg_color in nautilus you can see it because the menu color for the dark variant is quiet dark
![image](https://user-images.githubusercontent.com/15329494/45091557-25b64f80-b113-11e8-883a-3d39ca402343.png)
But still it could be a bit hard for the eyes. Also the buttons are much lighter than the bg

We have also a **different** border for the context menu in light/dark :man_shrugging: 
which uses some transparent color, which I am not sure if this is the most perfect fit :thinking: 
This is how the context menu border would look on the dark theme:
![image](https://user-images.githubusercontent.com/15329494/45091853-f6541280-b113-11e8-89ea-c133d1b83670.png)
I think this is too dark. Especially on "real" apps:
![image](https://user-images.githubusercontent.com/15329494/45091882-1683d180-b114-11e8-8641-5eccd1788757.png)

But what about just using $borders_color for both light/dark popover+context menus?
We then would need to brighten up the menu color for the dark theme I think. 

@madsrh  and ideas which would a) unify the look and the code and b) looks good but also easy for the eyes ?

I post some ideas soon  also

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/45092650-6ebbd300-b116-11e8-8d4c-c4c6fe368351.png)

This would use border color for both popovers and context menu but here I brightened the menu color relative to the background instead of darkening it

**Comment by madsrh** [comment]
IMHO I think there's too little contrast (too similar) between the menu background and the window background, in your [examples ](https://user-images.githubusercontent.com/15329494/45092650-6ebbd300-b116-11e8-8d4c-c4c6fe368351.png) [above](https://user-images.githubusercontent.com/15329494/45092720-9c088100-b116-11e8-9910-2d85276bbae6.png).

> here I brightened the menu color relative to the background instead of darkening it

How about making it even brighter - just a bit? That would, in my mind, also fit with the _things in the background become darker and things in front brighter_ metaphor we worked with earlier. So the popover actually pop 😄 

![image](https://user-images.githubusercontent.com/3986894/45117786-dbef5880-b156-11e8-956f-0bfb30f08767.png)


![image](https://user-images.githubusercontent.com/3986894/45117311-8797a900-b155-11e8-81df-44abeeea1ed1.png)

**Comment by Feichtmeier** [comment]
Okay i'll do that good idea

**Comment by 3v1n0** [comment]
Mh, I agree this is quite an issue... 

Personally, I'd prefer to have an inverted behavior for the regular mode too (as Ambiance was), so using dark context-menus everywhere, unless the menubar is light.

Is this something that could be reconsidered or the discussion on this is over?

**Comment by Feichtmeier** [comment]
Sure - but I'd like to postpone such a change for the time after 18.10. (if the others agree)
Since our light menus have a proper shadow, the usability is still very high.
One positive effect would be, that then both the shell popovers and the gtk popovers/context menus/menus would have a dark tone.

Personally I like both versions and with the shadows I don't see much of an issue with the light ones (except firefox... but that's more of a firefox theming issue and how firefox does not properly suck up the gtk code correctly)

**Comment by madsrh** [comment]
> I'd prefer to have an inverted behavior for the regular mode too...

That would definitely make the stand out from the background, but IMHO it doesn't look good. I think the current popovers for the light theme, so pretty well defined.

A quick mockup:

![image](https://user-images.githubusercontent.com/3986894/45359405-b9cd5e80-b5cc-11e8-8e58-601475cee287.png)

**Comment by 3v1n0** [comment]
Well, maybe because I'm used to the ambiance style, but I personally like this.

At least for non-standalone menus (i.e. for those child of headerbar or menubars or anything else dark) is nice.

**Comment by Feichtmeier** [comment]
We could talk about the idea to provide three themes: light, dark and mixed.

I plan a bigger code-review of the drawing file anyways, so I could implement a third variant in drawing and colors without touching common
