### ISSUE TITLE
Current Nautilus new-tabs - some thoutghs 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#786]
After taking some time to get used to the recent tabs change, I must say that all notebooks looks fantastic but one. Maybe it's only me but something bothers me in Nautilus appearance. 
Some examples : 
![screenshot from 2018-09-06 09-07-34](https://user-images.githubusercontent.com/37431503/45139209-ab8bd680-b1b7-11e8-8ce0-8a7e30549d95.png)
![screenshot from 2018-09-06 09-13-55](https://user-images.githubusercontent.com/37431503/45139242-c6f6e180-b1b7-11e8-900e-3dedcb540a5b.png)

I have a radical idea - What if we change the path-bar to look like text-buttons color-wise and behaviour-wise as well?  ![faint](https://user-images.githubusercontent.com/37431503/45139493-98c5d180-b1b8-11e8-8b69-51068ef1846f.gif)

**Comment by clobrano** [comment]
Could you explain better what's the issue?

**Comment by Feichtmeier** [comment]
I think pazit is talking about this picture:
![screenshot from 2018-09-06 09-07-34](https://user-images.githubusercontent.com/37431503/45139209-ab8bd680-b1b7-11e8-8ce0-8a7e30549d95.png)

Where the overall color composition COULD look a bit weird. If you look from top to bottom you have several color layers which MIGHT let you question which elements belongs to which layer/container. I don't have this feeling but I can understand where she is coming from

**Comment by Feichtmeier** [comment]
I don't think that recoloring the pathbar would have a positive impact.

This is only a "problem" in the dark theme by the way. The light theme does not have it, because the headerbar is colored completly different than the window rest of the window:
![image](https://user-images.githubusercontent.com/15329494/45150686-bbfa7c00-b1cc-11e8-81ef-c12f00131adf.png)

**Comment by Feichtmeier** [comment]
![screenshot-20180906120611-832x642](https://user-images.githubusercontent.com/15329494/45151022-830ed700-b1cd-11e8-841f-57ef64f71177.png)

In the light theme the layers are pretty clear. I think now my brain nailed what pazit wanted to say, am I correct, @Paz-it ?

**Comment by Paz-it** [comment]
Right to the point @Feichtmeier  ! 
Thanks!

**Comment by Feichtmeier** [comment]
I would leave this open for @clobrano to decide and to implement. I can live with the current solution and the complexity of the apps styling makes me fear I could introduce more mistakes before UI freeze.
I'll focus on things I am sure it works without mistakes until then

**Comment by clobrano** [comment]
I'll try

**Comment by clobrano** [comment]
I made some tests. Considering that this is current state
![image](https://user-images.githubusercontent.com/2883614/45232906-678cf480-b2d1-11e8-9230-3999f006db2d.png)

I think we can't have a good solution that would be the same for all the notebooks.

While for Nautilus and Gedit, this could be a good change (I made some more changes in gedit to make the sidebar exactly the same as nautilus and the same as its status bar)...

![image](https://user-images.githubusercontent.com/2883614/45234307-9ad18280-b2d5-11e8-93d0-ac023198c7df.png)
![image](https://user-images.githubusercontent.com/2883614/45234324-a755db00-b2d5-11e8-99ac-4347a218b353.png)

... this wouldn't work for terminal
![image](https://user-images.githubusercontent.com/2883614/45234394-d79d7980-b2d5-11e8-9f93-724fb421b3b3.png)

that will stay as it is now

Here is widget factory for reference

![image](https://user-images.githubusercontent.com/2883614/45234528-4975c300-b2d6-11e8-9812-ad9e894e0f2d.png)

To me, the effect is less pleasant in notebooks like the ones in widget factory, however it might be actually tidier on Nautilus and Gedit (which are among the most used applications) 


what are your thoughts?

**Comment by Feichtmeier** [comment]
I like it.
I noticed one minor issue:
![image](https://user-images.githubusercontent.com/15329494/45234886-5f37b800-b2d7-11e8-846e-7a42502c7ec5.png)
The border is ending 1 or 2 pixels too early.
Could this be fixed by using an inset box-shadow for tabs inset of a border?

**Comment by clobrano** [comment]
I think it's just round

**Comment by Paz-it** [comment]
+1 for changing only Nautilus and Gedit. All other notebooks looks perfectly good as is.
Well done @clobrano .
