### ISSUE TITLE
Infobar buttons

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#789]
Currently the buttons are normal buttons on a purple or yellow background.

This regular styling includes a border and a shadow, which looks a bit fuzzy on the heavy color:
![peek 2018-09-06 15-23](https://user-images.githubusercontent.com/15329494/45160112-e78b5f80-b1e8-11e8-88c0-5f6c434bc747.gif)

I made some local changes which uses the flat button styling we use in the selection bar and headerbar also for this infobar:
![peek 2018-09-06 15-25](https://user-images.githubusercontent.com/15329494/45160181-173a6780-b1e9-11e8-9404-fa49033ff1ec.gif)

I think this looks a bit "sharper"
![image](https://user-images.githubusercontent.com/15329494/45160255-481a9c80-b1e9-11e8-863f-9d691173b41b.png)

Also purple:
![image](https://user-images.githubusercontent.com/15329494/45160271-55378b80-b1e9-11e8-8772-df1eb9071b3f.png)

![peek 2018-09-06 15-27](https://user-images.githubusercontent.com/15329494/45160316-726c5a00-b1e9-11e8-926b-c43e3c15a7f2.gif)

@madsrh @clobrano do you like it?

**Comment by clobrano** [comment]
I wonder if this way we'd have the same problem as with text-buttons, for which we needed a bright border

**Comment by Feichtmeier** [comment]
Okay I try with a soft white border

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/45163372-9ed7a480-b1f0-11e8-8742-cf1d70310fe1.png)
![image](https://user-images.githubusercontent.com/15329494/45163406-ad25c080-b1f0-11e8-8181-bdbe58c89c61.png)

![peek 2018-09-06 16-20](https://user-images.githubusercontent.com/15329494/45163512-d8101480-b1f0-11e8-8667-0375cd9cf9f9.gif)

I'd prefer it without the border :man_shrugging:

**Comment by clobrano** [comment]
I don't like it with the border as well, but without any indication is just a label with no indication that can be clicked. Maybe better as it is now

**Comment by madsrh** [comment]
> Maybe better as it is now

+1 

I prefer the current too. Without any border look too lose IMO

**Comment by Feichtmeier** [comment]
If you like the white buttons, let's try it with this colour but flat, without the shadow which looks very fuzzy at the edges when it touches the purple/yellow, okay?

**Comment by madsrh** [comment]
With Travis CI back online, you can just create a PR, but atm I'm skeptical.
Do you remember the old issue where we changes it to regular buttons?
