### ISSUE TITLE
Can I have questions for Gtk Sharp 2 / 3 with OpenTK / OpenGl.net

### ISSUE THREAD

**Issue by sourceskyboxer** [ubuntu/yaru#802]
Hello everyone, 
Does Ubuntu Yaru support Gtk Sharp 2 / 3 with OpenTK / OpenGL.net? I hope it works completely.  Since Ubuntu 18.04 has negative bad bug like amdgpu-disabled.  I am very hesitating because Ubuntu 18.04 kills if Mono program ( Gtk-Sharp 2 or 3 with OpenTK or OpenGL.net via GLWidget ) . Like Unity3D maybe for linux versions or WaveEngine's VisualEditor crashed since Ubuntu 18.04 because it looks like if doesn't work.  But i already check libgtk-2 and libgtk-3 runtimes are installed.

What does it mean? Must I need recompile Gtk-Sharp from github and it works sure? Please tell yes or no if i should recompile from github and it works sure, right?

Or it has common bug if you have amdgpu display graphic card than Ubuntu 18.04 forces OpenTK or OpenGL.net's GraphicsContext.

How does it work with Ubuntu 18.04 and Yaru and Mono apps with gui?

Thanks for try and check if mono / net development  ( C#, F# and Visual Basic )
Please care us for C# programmers/coders

**Comment by sourceskyboxer** [comment]
Why close?????? Thank you your bad. I am mad now. I think you ignore me because you hurt C#, F# and Basic coders right. You are trolling to me. I am unhappy now.

**Comment by sourceskyboxer** [comment]
Hallo @Feichtmeier Du bist stur wieso hast du mich nicht zu informieren.

Ich dachte dass Gtk Sharp 2.12.45 von linux-packaging-GtkSharp2 und GtkSharp 3.22.8 from GtkSharpkit/GtkSharp muss ich neu kompilieren und Ich habe geschafft. Es liegt kein Problem. Danke, Trottel! :+1: 

Und ich habe manuell umgestellt:
Für Gtk Sharp 2.12.45 ( Linux-Packaging-GtkSharp2 ) muss ich GLWidget von GLWidgetTest 
Für Gtk Sharp 3.22.8 ( GtkSharpKit/GtkSHarp ) muss ich GLWidget von OpenTK's Development von MyGet aber ich trenne falsche GtkSharp3 von MyGet weil sie inkompatible ist und bei Ubuntu 18.04 absturzt und verzichtet wurde.

Ich habe Bonus Fix Juhuu Ich will stabilierte Versionen für Ubuntu 18.04 und Yaru veröffentlichen.

**Comment by Feichtmeier** [comment]
This is the wrong repo. Bye

**Comment by sourceskyboxer** [comment]
What? Do you understand my German? Is it wrong? No I mean for Ubuntu Yaru too If you play WaveEngine's VisualEditor than it happens. Bye
