### ISSUE TITLE
Small enhancement for Evolution

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#804]
A **very** small application specific enhancement, once again for Evolution. Look at the focus ring here:

![image](https://user-images.githubusercontent.com/3986894/45269008-78329b80-b486-11e8-951a-a0a595d26022.png)

This is also a problem in Adwaita, so perhaps it would be better to fix this upstream 🤷‍♂️ Anyway, seems like an easy fix:

`.vertical { padding-left: 1px; padding-right: 1px; }`

**Comment by godlyranchdressing** [comment]
Hey @madsrh, where do you go to get this dialog window? :sweat_smile:

**Comment by madsrh** [comment]
It's the welcome wizard: 😉 

![peek 2018-10-08 22-57](https://user-images.githubusercontent.com/3986894/46649422-4a319b80-cb99-11e8-8ecd-628e7173fa16.gif)
