### ISSUE TITLE
Atom windows options are white

### ISSUE THREAD

**Issue by Kinrre** [ubuntu/yaru#805]
## Expected Behavior
I use Atom as my personal text editor. It has a black appearance so I expect that the windows options (file, edit, view...) they will have a black appearance.

## Actual Behavior
The windows options are white.

## Steps to Reproduce the Problem
Open Atom.

## Specifications
Yaru Installed by snap.

## Software that presents the issue:
- Name: Atom
- Version: 12.8.0

![captura de pantalla de 2018-09-10 01-03-14](https://user-images.githubusercontent.com/37559188/45269866-5ab8fe00-b495-11e8-904d-b3eef560f67e.png)

**Comment by Feichtmeier** [comment]
Hi thanks for reporting
I think this issue is already covered by this one https://github.com/ubuntu/yaru/issues/715

**Comment by clobrano** [comment]
Closing as duplicate
