### ISSUE TITLE
ISO File icon

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#808]
@eaglersdeveloper could you please open this PR https://github.com/snwh/suru-icon-theme/pull/76
in our repo? :) We would love to use that icon since suru is missing it

![image](https://user-images.githubusercontent.com/15329494/45312609-d1550a80-b52c-11e8-83c2-dd2961ab893c.png)

**Comment by eaglersdeveloper** [comment]
OK, tomorrow.

**Comment by Feichtmeier** [comment]
hmmmm thursday is UI freeze, so if you are short on time, please tell me and I try to make the two PRs @eaglersdeveloper
