### ISSUE TITLE
Native gtk2, QGtkStyle and java swing gtk2 differ

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#822]
There are **native** gtk2 apps like Gimp and inkscape.  We are pretty much done with those and the theming should be the way-to-go for all other toolkits which suck up the gtk2 style:

![image](https://user-images.githubusercontent.com/15329494/45442965-b963bf00-b6c3-11e8-8753-52068c3ff1d3.png)

We also have **qt apps** like virtualbox or vlc which use the gtk2 theming via qt5-style-plugins and QT_QPA_PLATFORMTHEME=gtk2 (https://discourse.ubuntu.com/t/call-for-testing-communitheme-qt/6375) but these apps look a bit different than the native gtk2 apps:

- [ ] the menubar has no orange underline
![image](https://user-images.githubusercontent.com/15329494/45443052-f2039880-b6c3-11e8-8971-bb6ebff7ecfd.png)

- [ ] buttons are a bit "cut" at the edges 
![image](https://user-images.githubusercontent.com/15329494/45443110-15c6de80-b6c4-11e8-83ef-b23d603a196f.png)

- [ ] checkboxes and radio buttons are cut at the edges
![image](https://user-images.githubusercontent.com/15329494/45443266-748c5800-b6c4-11e8-8010-b0840e219cc8.png)

Then we also have **java swing applications** who can use the gtk2 styling like intellij IDEs (intellij IDEA, phpstorm... android studio...)

- [ ] The orange underline for menu items is missing
- [ ] the menu has a strange second layer and 
- [ ] selected labels are colored black in the backdrop:
![image](https://user-images.githubusercontent.com/15329494/45443561-5e32cc00-b6c5-11e8-8ba7-eafdb32343d3.png)

Until we found someone with gtk2 expertise who can fix this, let's keep it in this gathering issue.
@flexiondotorg maybe you could find some time until 19.4 for this

The awkward part is, that native gtk2 apps are pretty much legacy "soon" (gimp + inscape both have gtk3 branches) but Qt and Java swing will probably remain for many years.

**Comment by Feichtmeier** [comment]
All issues do not happen with ambiance

Would be great if one could study the difference of the gtk2 files:
https://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/view/head:/Ambiance/gtk-2.0/gtkrc

--> Regarding the color of the Java Swing menus, there must be some "second" color used for menus. When trying https://github.com/ubuntu/yaru/tree/gtk_jet_menus it had the "eluding effect" with the center of the menus being still white, but the outer region of the menus being $jet

**Comment by Feichtmeier** [comment]
@Paz-it @clobrano could you look into the java swing issue while working on the gtk-dark theme? I think there is a second layer on the menus. You can test it when you install intellij IDEA from within gnome-software

**Comment by Feichtmeier** [comment]
Np, I think it would be a good opportunity to identify this second layer because only the little stripes between the menu"rows" have the correct dark colour, the rest of white. I just wonder why ambiance has it right even with black menus

**Comment by clobrano** [comment]
Just installed intellij-idea-community snap and it seems to use a totally custom theme

![image](https://user-images.githubusercontent.com/2883614/49513674-1077cb00-f892-11e8-91b6-b55b6a15081b.png)

**Comment by Feichtmeier** [comment]
Yes set in the options :)

**Comment by Feichtmeier** [comment]
Oh wow! They removed the GTK support out of the options :O 
Must be an update from the past 5 days 
![image](https://user-images.githubusercontent.com/15329494/49514020-14f0b380-f893-11e8-8fc2-54c0983fcc13.png)

**Comment by Paz-it** [comment]
Saw it only now, sorry! 
The first thing I saw in Ambiance gtkrc is  from L125 to L148 
 style "dark"
{
	color["bg_color_dark"] 	= "#3c3b37"
	color["fg_color_dark"] 	= "#dfdbd2"
	color["selected_fg_color_dark"] = "#ffffff"

	fg[NORMAL]        = @fg_color_dark
	fg[PRELIGHT]	  = shade (1.15, @fg_color_dark)
	fg[ACTIVE]	  = @fg_color_dark
	fg[SELECTED]	  = @selected_fg_color_dark
	fg[INSENSITIVE]	  = shade (0.5, @fg_color_dark)
  
	bg[NORMAL]        = @bg_color_dark
	bg[ACTIVE]	  = shade (0.8, @bg_color_dark)
	bg[SELECTED]      = @selected_bg_color
	bg[PRELIGHT]      = shade (1.0, "#4D4C48")
	style "dark"
{
	color["bg_color_dark"] 	= "#3c3b37"
	color["fg_color_dark"] 	= "#dfdbd2"
	color["selected_fg_color_dark"] = "#ffffff"

	fg[NORMAL]        = @fg_color_dark
	fg[PRELIGHT]	  = shade (1.15, @fg_color_dark)
	fg[ACTIVE]	  = @fg_color_dark
	fg[SELECTED]	  = @selected_fg_color_dark
	fg[INSENSITIVE]	  = shade (0.5, @fg_color_dark)
  
	bg[NORMAL]        = @bg_color_dark
	bg[ACTIVE]	  = shade (0.8, @bg_color_dark)
	bg[SELECTED]      = @selected_bg_color
	bg[PRELIGHT]      = shade (1.0, "#4D4C48")
	bg[INSENSITIVE]   = shade (0.85, @bg_color_dark)
  	
	text[NORMAL]      = @fg_color_dark
	text[PRELIGHT]	  = shade (1.15, @fg_color_dark)
	text[SELECTED]	  = @selected_fg_color_dark
	text[ACTIVE]      = @fg_color_dark
	text[INSENSITIVE] = mix (0.5, @bg_color, @bg_color_dark)
}bg[INSENSITIVE]   = shade (0.85, @bg_color_dark)
  	
	text[NORMAL]      = @fg_color_dark
	text[PRELIGHT]	  = shade (1.15, @fg_color_dark)
	text[SELECTED]	  = @selected_fg_color_dark
	text[ACTIVE]      = @fg_color_dark
	text[INSENSITIVE] = mix (0.5, @bg_color, @bg_color_dark)
}

Might be not the only one. I'll check it some more when I have time latter...
But at least it's a clue to start with.

**Comment by fitojb** [comment]
Note that the Ambiance/Radiance GTK+2 themes use the Murrine engine, so its code isn’t directly portable to Yaru, which relies on PNG assets.

**Comment by Feichtmeier** [comment]
Ahhhha! Thank you @fitojb
That's the kind of information I didn't have.

**Comment by Feichtmeier** [comment]
Android studio and intellij removed the gtk2 support. For me it would be okay to close this, feel free to re-open.
