### ISSUE TITLE
default button in filechoser has the wrong color

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#823]
![image](https://user-images.githubusercontent.com/15329494/45457238-4b80bd00-b6ee-11e8-9ef6-e4f1df7c6d1b.png)

I don't know if this is a regression, or if the snap is not correctly updated on my host.
please double check @madsrh @clobrano 
I was so sure that I fixed this for the header bar with https://github.com/ubuntu/yaru/pull/798

This screenshot is from telegram. I wonder why it doesnt have borders in the filechoser.
Like other apps

:cry:

**Comment by madsrh** [comment]
I can confirm this for Telegram 😣 but didn't (yet) come across this in other applications

**Comment by clobrano** [comment]
I still can't find other applications with the same problem
