### ISSUE TITLE
Gnome shell font-family fallbacks to a not installed font

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#824]
As seen in #794, in gnome shell, font-family has Cantarell as second font in the list, however fonts-cantarell is not installed by default. I believe we should choose a different font for fallback.

**Comment by clobrano** [comment]
Since this change might affect the font used in other use cases, I think this should target next release

**Comment by clobrano** [comment]
Otherwise, we can just remove Cantarell from font-family list. Since it is not installed by default, that should not have any visible effect. @didrocks what do you think? Is something that can pass during UI freeze or better wait next cycle?

**Comment by Paz-it** [comment]
@clobrano , Maybe you can just change the order : 
-font-family: Ubuntu, Cantarell, Sans-Serif;
+font-family: Ubuntu, Sans-Serif, Cantarell;

**Comment by clobrano** [comment]
*sans-serif* is a category of fonts, it used at the end of the list to say "ok, if none of the above fonts is installed, use whatever sans-serif font is available"

**Comment by clobrano** [comment]
> But if we change the order, I think it will be the same as if we remove it from the list.

This is correct, so why keep it?

**Comment by clobrano** [comment]
It is not safer if it's the same :smile:

I am not proposing to remove anything from the system, also because cantarell is not in the system already. We just continue to not use it if someone install it later.

**Comment by didrocks** [comment]
I'm unsure what we are trying to solve here. Do we want to prevent people to use Cantarell when removing the ubuntu font and installing it?
It just sounds some additional diff, but as it's a no-op, I would tend to say that we should stay close to upstream, then the merge operation is just about adding our ubuntu font in front of the list.

Does that sound crazy or am I missing anything?

**Comment by clobrano** [comment]
> adding our ubuntu font in front of the list.

It's already this way. We have, in this order, Ubuntu, cantarell, sans-serif

The "issue" is that by default, cantarell isn't installed, so when a character is missing we fall back to sans-serif, but if someone installs cantarell we fall back to that instead. This is most visible in the clock widget on lock screen (see #794). 

I was just wondering whether it made sense to have in font-family list a font which isn't installed by default. 

A possible better solution is the one proposed by @eagledeveloper, open a bug to ubuntu-font for the missing character

**Comment by didrocks** [comment]
> A possible better solution is the one proposed by @eaglersdeveloper, open a bug to ubuntu-font for the missing character

I think that's the way to go, here we are talking about a font not installed by default. So I don't think this is much visible and we shouldn't add churn around it, preventing people who want to use the GNOME font to do it easily.

**Comment by clobrano** [comment]
It exists already :D 
https://bugs.launchpad.net/ubuntu-font-family/+bug/1678569

closing this then
