### ISSUE TITLE
Firefox dowload progress bar almost invisible

### ISSUE THREAD

**Issue by lwbt** [ubuntu/yaru#828]
## Expected Behavior

Monitoring the progress of a download in Firefox with the progress bar being clearly visible.

## Actual Behavior

![https://i.imgur.com/ViydVwI.png](https://i.imgur.com/ViydVwI.png)

The progress bar has the same color as the highlighted selection becoming almost invisible, particularly during the last percentage steps of a download.

## Steps to Reproduce the Problem

  1. Start a download in Firefox
  1. Go to the library → Downloads to check the progress

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

```
$ snap info communitheme
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 7 days ago, at 01:21 CEST
channels:                    
  stable:    0.1 (961)  10MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1168) 17MB -
installed:   0.1 (961)  10MB -
```

Software that presents the issue:
- Name: Package: firefox
- Version: 62.0+build2-0ubuntu0.18.04.4

**Comment by madsrh** [comment]
Hi lwbt
Thanks for taking the time to report this bug 👍

I agree that the progressbar isn't visible in your screenshot, but sadly this is a result of missing GTK support in Firefox. 
I'm not sure what options we have here - the best solution would definitely be for Firefox to add full GTK support.

**Comment by Feichtmeier** [comment]
We could consider to remove the firefox "blue" modification and try to get it working with firefox to "suck up" the correct GtkTextView.selection styling + GtkEntry.selection styling
@madsrh opinions?

**Comment by Feichtmeier** [comment]
So I could make the accent color orange again (including text, until they fixed that):
![screenshot-20181203184629-700x537](https://user-images.githubusercontent.com/15329494/49391645-8a8e3f80-f72c-11e8-8ec9-c4c39cacf584.png)
![image](https://user-images.githubusercontent.com/15329494/49391733-c923fa00-f72c-11e8-9d85-f59dde5b2384.png)


However,... this would not make the progressbar more visible on the selected row.
:face_with_head_bandage:

**Comment by Feichtmeier** [comment]
Same issue with adwaita gtk theme

**Comment by Feichtmeier** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1511868
