### ISSUE TITLE
Make new suru icon style for the installer

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/yaru#837]
The ubuntu installer has still the old icon:

![immagine](https://user-images.githubusercontent.com/345675/45741392-bdc63580-bbf7-11e8-8315-863319452928.png)

This is out of context when running the installer.

**Comment by Feichtmeier** [comment]
This is not exactly the application but is uses the same icon:
https://github.com/ubuntu/yaru/issues/821
I will update that issue to cover this application, too and close this one :)
