### ISSUE TITLE
gtk2 radio button has the wrong check sign

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#843]
Here is the check sign in gtk2, used in both light and dark theme

![screenshot from 2018-09-20 22-44-49](https://user-images.githubusercontent.com/2883614/45846035-f9135200-bd26-11e8-9b89-e674f4d4f027.png)

here is the one used in GTK3

![screenshot from 2018-09-20 22-46-25](https://user-images.githubusercontent.com/2883614/45846060-0cbeb880-bd27-11e8-8401-de67f6011854.png)

**Comment by Paz-it** [comment]
You have correct ones in my folder. Just need to recolor them.

**Comment by clobrano** [comment]
Awesome, thanks!
