### ISSUE TITLE
Inconsistent focus rings, dashed vs. solid

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#844]
yaru-theme-* 18.10.4, Ubuntu Cosmic

Some buttons, menus, and tabs have a dashed focus ring…

![button focus dashed](https://user-images.githubusercontent.com/19801137/45882040-d9227380-bda4-11e8-880f-ad355dd31767.png) ![button focus dashed dark](https://user-images.githubusercontent.com/19801137/45882041-d9227380-bda4-11e8-9da8-035cef8eb70d.png)

…while other buttons, and all text fields, have a solid focus ring.

![button focus solid](https://user-images.githubusercontent.com/19801137/45882042-d9227380-bda4-11e8-858f-c0486e21037f.png)
![focus ring for text field in firefox](https://user-images.githubusercontent.com/19801137/45882076-f1928e00-bda4-11e8-97d8-b9113304e852.png)

It’s not clear whether this is deliberate, but it looks inconsistent.

In the forum, [frederik-f wrote](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1752):
> This one comes from a limitation in gnome-shell. A dashed focus ring is not possible there. So either we change the gtk focus ring to be solid, or we leave it as it is. There are several differences between gnome shell and the gtk theme which we accepted as a design limitation and/or a possibility to divide the the shell from the apps. :man_shrugging:

However:

- That does not explain why the focus rings for text fields and buttons are inconsistent within the same window.
  ![focus for menu vs text field](https://user-images.githubusercontent.com/19801137/45882044-d9227380-bda4-11e8-90c2-b4da94ddebc8.gif)

- [The wiki explains that for sliders](https://github.com/ubuntu/yaru/wiki/%233-GTK-Theme-Design#gtkscale), “we had to use circles for the knob, because Gnome Shell does not support squ[ir]cles. Although this limitation only applies to the shell, we wanted the same style in both GTK and the shell.” That is solid logic — and it applies much more to focus rings than it does to sliders, because focus rings are seen much more often.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by Feichtmeier** [comment]
@matthewpaulthomas
In gtk3 apps:

All entries havea solid focus ring (including those with +/- buttons in them)
All other elements have a dashed focus ring

In the shell only a solid ring is possible


Firefox URL bar is not themeable
So either everything becomes orange again, including the text selection (they only suck up one colour and then set it as an accent colour) or live with the blue URL bar
Again Firefox is a mess when it comes to theming. Since we knew this we opened the issue in their side.

**Comment by Feichtmeier** [comment]
We need to link the old discussions in here

**Comment by clobrano** [comment]
One more detail. We went for dash focus ring because, above all on buttons, makes the UI lighter according to our point of view (above all on buttons)

**Comment by clobrano** [comment]
> That does not explain why the focus rings for text fields and buttons are inconsistent within the same window.

good point. Entries can have dashed focus ring

**Comment by clobrano** [comment]
What do you think about solid focus for buttons?

![focus-ring-solid](https://user-images.githubusercontent.com/2883614/46861282-a05d4380-ce12-11e8-9a1f-6120ef8336a0.gif)

**Comment by clobrano** [comment]
This is a "side effect"

![image](https://user-images.githubusercontent.com/2883614/46861835-e23ab980-ce13-11e8-8e4b-51b17c9726bf.png)

**Comment by matthewpaulthomas** [comment]
> What do you think about solid focus for buttons?

Looks good to me.

**Comment by clobrano** [comment]
thanks @matthewpaulthomas, however I later observed (just forgot to update this bug, sorry), that other widgets have a dashed focus ring (e.g. check/radio buttons, sliders), where the solid focus ring will be really heavy. Basically, only entries have the solid one.

**Comment by Feichtmeier** [comment]
We could also consider a blue focus ring for all elements in shell and gtk theme (even for green and red buttons)  :man_shrugging: 
At least try it one time before 19.4

**Comment by clobrano** [comment]
Sure it is, I am curious to see how this fits with both headerbar's color and success/destructive ones

**Comment by clobrano** [comment]
I suggest to keep it as it is on our side and investigate if there's something we can do upstream to remove the limitation. What do you think?

**Comment by Feichtmeier** [comment]
The merge closed it :D sorry

**Comment by clobrano** [comment]
I think we can actually close it now, there is nothing we can do here to improve it
