### ISSUE TITLE
Icon missing in Libreoffice snap for in app menu

### ISSUE THREAD

**Issue by sumeetaras** [ubuntu/yaru#848]
## Expected Behavior

The Applications menu should show the correct icon.

## Actual Behavior

No icon is seen. (See top right)
![libreoffice](https://user-images.githubusercontent.com/10984081/45893070-1b918380-bd98-11e8-9a55-7d408f7aa42a.png)

## Steps to Reproduce the Problem
1. Open Tweaks. 
2. Go to 'Top Bar'.
3. Toggle 'Application Menu' to off.
4. Open Libreoffice Writer snap.

Thanks!

**Comment by Feichtmeier** [comment]
HI thanks for reporting issues

This only happens in yaru?

**Comment by sumeetaras** [comment]
Good point. I hadn't checked  other themes. Turns out I see this other themes too (tried with Ambiance and Adwaita).

**Comment by Feichtmeier** [comment]
Okay :D 
This is really a bigger issue - could you be so kind and open this issue on the LO bug tracker? 
If so you could also close this one here :)

**Comment by sumeetaras** [comment]
As suggested, I have created a bug report here: https://bugs.documentfoundation.org/show_bug.cgi?id=120035

Closing this issue here.

**Comment by fitojb** [comment]
Note that this behavior is bound to improve as the app menu is going to be removed in GNOME 3.32. See [bug 119996](https://bugs.documentfoundation.org/show_bug.cgi?id=119996).
