### ISSUE TITLE
in inactive disabled dark switch the knob is not visible

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#850]
## Expected Behavior
knob should be distinguishable from the background

## Actual Behavior
knob background and borders have the same color as switch background and so it is not visible
## Steps to Reproduce the Problem

  1. select dark variant (e.g. prefer dark variant in gtk3 configuration)
  2. open tweaks > desktop view
  3. enable icons on desktop and then switch on "Home" icon
  4. disable icons on desktop: "Home" switch will still be switched on, but disabled

![image](https://user-images.githubusercontent.com/2883614/45917703-c62ea280-be7b-11e8-8800-1f379f864743.png)

## Specifications

    `$ git describe`
    r22-10-g940c5102

**Comment by Paz-it** [comment]
I can reproduce it.

**Comment by clobrano** [comment]
I would try the same as checked radio buttons

**Comment by clobrano** [comment]
![switch-insens-dark](https://user-images.githubusercontent.com/2883614/45929846-b4bac880-bf57-11e8-81a5-4f01873542e0.gif)
