### ISSUE TITLE
Active tab label inexplicably lower than inactive tab labels

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#854]
yaru-theme-* 18.10.4, Ubuntu Cosmic

An active tab label is 1px lower than inactive tab labels.

![tab label alignment](https://user-images.githubusercontent.com/19801137/45929355-5e925900-bf48-11e8-87ff-9b3feed3533a.png)

![tab label alignment in settings](https://user-images.githubusercontent.com/19801137/45929405-060f8b80-bf49-11e8-8a86-1f469a97be73.png)

Maybe this is intentional, but there’s nothing visible to indicate that it is intentional.

What should happen: either
- the labels are lined up exactly, or
- inactive tabs have visible borders, so that you can see the whole active tab is lower than the inactive ones.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by clobrano** [comment]
> Maybe this is intentional, but there’s nothing visible to indicate that it is intentional.

Not intentional. I believe it is just the bold type that changes the font size and then the position of the label

**Comment by Feichtmeier** [comment]
Yes the bold increases the size of the label
