### ISSUE TITLE
Rhythmbox icon is not recognizable

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#859]
yaru-theme-* 18.10.4, Ubuntu Cosmic

If you’ve used Rhythmbox frequently before, perhaps in previous versions of Ubuntu, you might remember the unusual colour scheme of the previous icon:

![193px-rhythmbox_logo svg](https://user-images.githubusercontent.com/19801137/45930476-c3ee4600-bf58-11e8-81f7-c37416d45723.png)

But if you haven’t, or don’t, then the the new Rhythmbox icon looks like nothing so much as a big yellow eye.

![icon for rhythmbox](https://user-images.githubusercontent.com/19801137/45930454-6fe36180-bf58-11e8-9e3f-68d0c33429e7.png)

Apart from the callback to the previous icon’s colors, there’s practically nothing to suggest that the new icon is a speaker:
- It’s an unusual shape — and since all other icons are the same shape, it’s not obviously a physical object at all. There is no visibility of any other side, and no shadow on, or reflection of, the surface the speaker is on, while the previous icon had all three. (If those are all unavoidable limitations of the icon style, then the other design aspects need to work that much harder.)
- It’s an unusual set of colors: [speakers with white bodies seldom have yellow cones](https://duckduckgo.com/?q=white+loudspeaker&t=canonical&iax=images&ia=images), and [speakers with yellow cones seldom have white bodies](https://duckduckgo.com/?q=speaker+%22yellow+cone%22&t=canonical&iax=images&iar=images&ia=images).
- Now that the dustcap is black, its pointed shape is barely visible.
- There are no visible screws, no nameplate, and no cable.
- There are no sound waves, like the previous icon, or music notes.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by Feichtmeier** [comment]
To be honest, all icons are something abstract
So by this logic we could probably scrap 50% of all icons

To give you a little history of how this happened:
- ubuntu still does not want to ship the default gnome music player which is in fact gnome-music and had suru icon since day1 since it is a generic app and thus coverd by "music-app.svg"
- I tried to convince the ubuntu community of using gnome-music instead but the feedback was rather mixed
- I asked @snwh to provide a rhythmbox icon so we don't have to use this super old icon

Please open this issue on @snwh repo since this icon is drawn by him (as 95% of the icons)

**Comment by matthewpaulthomas** [comment]
Abstract-or-not is a scale, rather than a binary. Sometimes being more abstract can make things more recognizable: for example, sound waves and music notes aren’t visible in reality, but adding an abstract representation of one or both would help.

If Rhythmbox is using the same icon as gnome-music, then switching to gnome-music wouldn’t alter this issue at all, right?

I’m sorry I was scheduled to review the theme so late. As requested, I’ve reported this as [suru-icon-theme#90](https://github.com/snwh/suru-icon-theme/issues/90).

**Comment by Feichtmeier** [comment]
Closing this here as you reported it upstream
