### ISSUE TITLE
No way to guess icons of Language Support vs. Software & Updates

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#861]
yaru-theme-* 18.10.4, Ubuntu Cosmic

The icons for Language Support and Software & Updates Settings are both globes, one containing a world map, the other against a background of a world map.

![icons for language support and software updates settings](https://user-images.githubusercontent.com/19801137/45940653-2afc1100-bfd2-11e8-93f4-448d49b4f191.png)

If you asked 100 people to guess which was which, the answers would be similar to tossing a coin. There is nothing more language-y about the Language Support icon, and nothing more software-ish about the Software & Updates Settings icon.

One way of making the Language Support icon more obvious would be including glyphs from different alphabets, maybe instead of the globe.

One way of making the Software & Updates Settings icon more obvious would be basing it on a combination of the Software Updater icon plus the Settings cogwheel. If so, it may be best to resolve #862 before addressing this issue.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by Feichtmeier** [comment]
Agreed.
Yet, as long as we want to work with snwh this is the wrong repo. Since those icons are made by him.
Or we decide to go fully independent from his repo, which could also have some other positive side effects, like a positive working atmosphere and control over what's happening much like we have it with our theme and sound theme

**Comment by didrocks** [comment]
I guess we should try to first convince Sam to get the fixes we need. Then, is there is disagreement, for some icons, we can diverge, as already explained.

**Comment by matthewpaulthomas** [comment]
Now reported as [suru-icon-theme#92](https://github.com/snwh/suru-icon-theme/issues/92).

**Comment by Feichtmeier** [comment]
Fixed upstream

Todo
- [ ] merge this into Yaru

**Comment by Feichtmeier** [comment]
Icon branch is ready, waiting for 25.10 to put this into master
God this is a long time, sure about this @didrocks ? :D

**Comment by Feichtmeier** [comment]
No it's okay. Good time to pause then :)
