### ISSUE TITLE
Ubuntu Software and Software Updater icons differ only in color

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#862]
yaru-theme-* 18.10.4, Ubuntu Cosmic

The icons for Ubuntu Software and Software Updater appear to be identical except for their color scheme.

![icons for ubuntu software and software updater](https://user-images.githubusercontent.com/19801137/45940824-1409ee80-bfd3-11e8-9fb5-ac330871bc26.png)

This makes it impractical to guess which is which. And if you are color-blind, it may also be difficult to tell which is which even if you know the difference.

If the “A” is supposed to represent applications, then perhaps the Software Updater icon should not consist of that motif, because it provides updates for all software, not just apps.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by matthewpaulthomas** [comment]
Now reported as [suru-icon-theme#91](https://github.com/snwh/suru-icon-theme/issues/91).

**Comment by meetdilip** [comment]
We can use a simple icon for software updater. 

![update](https://user-images.githubusercontent.com/6965443/46242811-a69ef900-c3ea-11e8-9604-2a6f91824737.png)

**Comment by meetdilip** [comment]
If you want it more inclined towards an app,

![update 1x](https://user-images.githubusercontent.com/6965443/46242884-828fe780-c3eb-11e8-9eec-dd2f38356a7c.png)

**Comment by Feichtmeier** [comment]
Closing this here as you reported it upstream
