### ISSUE TITLE
Folders differ in aspect ratio for Files app icon vs. directory icons

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#864]
yaru-theme-* 18.10.4, Ubuntu Cosmic

The “Files” app icon contains a folder, where the solid part (not including shadows) is 32px ✕ 28px, giving an aspect ratio of about 1.14.

In Files windows, however, at the default zoom level, a folder icon has a solid part of (84px ✕ 78px, giving an aspect ratio of about 1.08.

![icons for folders](https://user-images.githubusercontent.com/19801137/45941453-220d3e80-bfd6-11e8-80f8-7d4b2ad52036.png)

This is noticeably inconsistent. The app icon looks more realistic, at least for a folder that would contain A4 or US Letter paper.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by matthewpaulthomas** [comment]
Now reported upstream as [suru-icon-theme#96](https://github.com/snwh/suru-icon-theme/issues/96).

**Comment by Feichtmeier** [comment]
Closing this here as you reported it upstream
