### ISSUE TITLE
Downloads symbol differs in aspect ratio for sidebar vs. folder icon

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#865]
yaru-theme-* 18.10.4, Ubuntu Cosmic

In the Files sidebar, the Downloads icon is an arrow pointing at a line. The combined visible symbol is 12px ✕ 15px, giving an aspect ratio of 0.8.

In the Downloads folder icon itself, a similar arrow pointing at a line appears, but it looks squashed or stretched in comparison: it’s 22px ✕ 38px, giving an aspect ratio of about 0.58.

![icons for downloads](https://user-images.githubusercontent.com/19801137/45941677-3ef64180-bfd7-11e8-94e3-9c0f07f96d00.png)

This may be partly because the folder icons as a whole have been stretched (#864). But even if that can’t be fixed for some reason, the downloads symbol inside the folder could still be fixed.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by matthewpaulthomas** [comment]
Now reported upstream as [suru-icon-theme#97](https://github.com/snwh/suru-icon-theme/issues/97).

**Comment by Feichtmeier** [comment]
Closing this here as you reported it upstream
