### ISSUE TITLE
Different kinds of Trash / Rubbish Bin in Desktop vs. sidebar

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#868]
yaru-theme-* 18.10.4, Ubuntu Cosmic

On the Desktop, the Trash / Rubbish Bin is a recycle bin, with a logo and without a lid, like you’d find in an office.

In the Files sidebar, the Trash / Rubbish Bin is an Oscar-the-Grouch-style grooved garbage can, with a lid with a handle, and something sitting in front of it. (A rubbish bag?)

![icons for rubbish bin](https://user-images.githubusercontent.com/19801137/45950282-0c5c4100-bff7-11e8-86c4-821b89610731.png)

Obviously the icon in the sidebar needs to be simpler and more symbolic than the one on the Desktop, to fit in with the other sidebar icons. However, it needn’t be a completely different kind of bin altogether.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by meetdilip** [comment]
Most icon themes have different icons depending on the screen size. Mainly because a single icon might not work on all sizes. The only option I can see is to use the symbolic icon on the sidebar on the desktop, which is more of a real-life icon.

**Comment by matthewpaulthomas** [comment]
I’m sorry I can’t work out what you’re suggesting, but I think there are three options:
- change the sidebar trash icon to a recycle bin, like the desktop one
- change the desktop trash icon to a grooved garbage can, like the sidebar one
- change both of them to a different kind of bin — for example, a swing-top bin, a wire wastebasket, or a plastic recycle bin.

(This is a case where the rounded rectangle shape is quite unhelpful. Trash cans / rubbish bins have few recognizable features except for their shapes. For portable bins of any sort, that shape is nearly always tapered — narrower at the bottom than the top — so that they’re stackable.)

**Comment by matthewpaulthomas** [comment]
Now reported upstream as [suru-icon-theme#98](https://github.com/snwh/suru-icon-theme/issues/98).

**Comment by Feichtmeier** [comment]
Closing this here as you reported it upstream
