### ISSUE TITLE
Volume icons are a mixture of symbolic and app-style

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#869]
yaru-theme-* 18.10.4, Ubuntu Cosmic

1\. Connect to a large office’s wi-fi.
2\. In the Files sidebar, click “Other Locations”.

What you see: something like this.

![icons for volumes](https://user-images.githubusercontent.com/19801137/45950532-16327400-bff8-11e8-9a71-265c40b9e589.png)

What you should see: All the volume icons are of the same style.

This might just be two missing icons.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by Feichtmeier** [comment]
Just for the record, I think this should be the correct icon for network drives
![image](https://user-images.githubusercontent.com/15329494/48252949-6168e080-e406-11e8-8e6e-18c956d3330e.png)
(see webdav mount)

**Comment by Feichtmeier** [comment]
Ah I misunderstood

So for clarification, these are the symbolic icons for places and devices:
https://github.com/ubuntujaggers/yaru
https://github.com/ubuntujaggers/yaru

So I guess we need that symbolic globe also for "windows-network" and the harddisk icon for the harddisk icon, is that what you meant, @matthewpaulthomas ?

**Comment by matthewpaulthomas** [comment]
The opposite, actually! This is the main pane, not the sidebar. The sidebar always uses symbolic icons, and — except for this bug — it’s the _only_ place I’ve seen symbolic filesystem icons. So it looks like some non-symbolic icons that are missing.

**Comment by Feichtmeier** [comment]
Ahhh! Lol - that's a weird screenshot! :D
Thanks for your response! I'll try to fix it

**Comment by ubuntujaggers** [comment]
Okay, I've been trying to work out what's going on with the plug on the folder.

I **think** Suru generates icons by taking a symbol from source-symbolic.svg, colouring it, and putting it on a folder.  Certainly, the music folder icon, home folder icon, etc., looks like that's happening.  @Feichtmeier, does that fit with your understanding of the script and folder icons?  I think the answer is for me to make a symbol for "network" and add it to source-symbolic.svg with that name...?  It could be a monochrome glyph of an ethernet socket.

**Comment by ubuntujaggers** [comment]
Maybe the server stack icon could take the same shape as the trashcan and other "tall" Suru icons.  Attempt #1:

![image](https://user-images.githubusercontent.com/38893390/48974043-348f0d00-f045-11e8-96c6-ad88ca15ab2d.png)

Looks a bit cheap...

**Comment by Feichtmeier** [comment]
I think this is how it works but didn't dig into it. But just provide the icons and I do the rest :D
I think this looks not cheap. I like it no idea what others think

**Comment by ubuntujaggers** [comment]
> I think this is how it works but didn't dig into it. But just provide the icons and I do the rest :D
> I think this looks not cheap. I like it no idea what others think

I think it looks better than a completely non-Suru icon as a fallback, if you all like it I can do a PR  :)

**Comment by Feichtmeier** [comment]
Yes! I like both, let's wait for @mads and @clobrano if they like it

**Comment by clobrano** [comment]
I like to keep the special icon for network server and use the glyph for the network folder :+1:

**Comment by Feichtmeier** [comment]
@ubuntujaggers not to hurry you but to clear out an eventual wrong communication I did with all those "icons missing"
You would "only" need to provide the two icons (server + network folder) and I do the symlinking for you :smiley_cat: 
Because there are really a lot of those icons who use either of the two in humanity

**Comment by ubuntujaggers** [comment]
Okay, super, I'll square this one off today as well  👍 

Network folder will mean adding/naming a new glyph on the symbolic source file, last time I was just changing one.  I'll call it "network" unless anyone knows it should be called something different?

**Comment by ubuntujaggers** [comment]
One more question: am I doing "network-server" (the full colour server icon) in "places" or "devices"?  Ready to PR as soon as I know...

**Comment by Feichtmeier** [comment]
I'd say places, because the symbolic is also in places

![image](https://user-images.githubusercontent.com/15329494/49879218-d4acaa80-fe29-11e8-9e46-5e8dfff09585.png)

**Comment by Feichtmeier** [comment]
Fixed
