### ISSUE TITLE
Tweaks icon doesn't respect switch proportions

### ISSUE THREAD

**Issue by ya-d** [ubuntu/yaru#872]
_I'll add one more to the icon theme issues. Although Tweaks is not among the default apps, Yaru still provides an icon for it._

The Suru icon for Tweaks uses switches as a visual metaphor. Those switches are styled like in the Yaru GTK theme but use different proportions which makes them seem distorted. The icon should follow the actual proportions in Yaru.

<img width="63" alt="suru tweaks" src="https://user-images.githubusercontent.com/30781876/46038215-c55f7000-c10a-11e8-928a-033273ae85a4.png"> <img width="64" alt="yaru gtk switches" src="https://user-images.githubusercontent.com/30781876/46038216-c55f7000-c10a-11e8-89a1-2a503468bdda.png">

**Comment by clobrano** [comment]
Honestly, it's the first time I actually recognize that Tweaks has switches similar to Yaru's :smile:

**Comment by meetdilip** [comment]
What I am seeing above are icons for 2 different apps ?

**Comment by clobrano** [comment]
@meetdilip nope, first one is Tweak icon, while the latter is a screenshoot of UI

**Comment by meetdilip** [comment]
What change do you want to see ?

**Comment by Feichtmeier** [comment]
I think being on par with the Suru icon guidlines is much more important here.
It is an icon, it does not need to look 100% like what it is representing. 
Currently the space between the edges and the pictogram are perfect, when  the form factor would be changed the icon wouldn't look even anymore. Don't know how @madsrh @clobrano  feel about this, but for me this would make things worse than it is now. :man_shrugging: 
Thus, I'm for closing this.

**Comment by clobrano** [comment]
I agree with you, we can close this, unless Mads has a different opinion

**Comment by madsrh** [comment]
Closing this issue because the icon is just that - an icon, not a screenshot.
