### ISSUE TITLE
Missing padding in popover

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#881]
Add padding for popover under Printer settings here:

![_1](https://user-images.githubusercontent.com/3986894/46316557-cd1e8900-c5d0-11e8-9595-9b7401a3f0a6.jpg)

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/46317075-466aab80-c5d2-11e8-86ec-7c80dd96aa30.png)
