### ISSUE TITLE
Sliders have a fuzzy border in the dark theme

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#885]
![screenshot-20181002231434-51x36](https://user-images.githubusercontent.com/15329494/46377587-45e91800-c699-11e8-8cdb-2d49e4a49302.png)

![image](https://user-images.githubusercontent.com/15329494/46377651-76c94d00-c699-11e8-984e-f95661292a22.png)

Possible solutions:
- remove the border
- make the border same color as the knob

**Comment by clobrano** [comment]
Using the same color of the knob makes this weird effect

![image](https://user-images.githubusercontent.com/2883614/46799076-15b60f00-cd54-11e8-8678-9e970538bc06.png)

Better transparent I believe
![image](https://user-images.githubusercontent.com/2883614/46799134-3aaa8200-cd54-11e8-96da-7007c539fba0.png)

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru/issues/909
