### ISSUE TITLE
Yaru theme not properly applied to login screen

### ISSUE THREAD

**Issue by marconallo** [ubuntu/yaru#887]
## Expected Behavior
to see yaru login screen

## Actual Behavior

old theme login screen

## Steps to Reproduce the Problem
![20181003_182845](https://user-images.githubusercontent.com/1822446/46424837-7c2aa400-c73a-11e8-8fe7-886d17fe05a5.jpg)

  1. Turn on PC
  1. Wait for login screen
 

## Specifications
I'm on Ubuntu 18.10 beta, with last version of yaru theme installed (18.10.5)

Thanks,
Marco

**Comment by Feichtmeier** [comment]
@3v1n0 @didrocks any idea why this could happen?
We didn't touch the GDM code

**Comment by 3v1n0** [comment]
This was an upgrade? Have the settings been "hacked" a bit in the past?

**Comment by Feichtmeier** [comment]
No we didn't touch the GDM code since ... two months?

Or do you mean @marconallo

**Comment by marconallo** [comment]
@3v1n0 Yes, an upgrade from Ubuntu 18.04. Sincerely I don't remember any hack on GDM theme in the past. If I can do something to verify this, please give me some instructions

**Comment by 3v1n0** [comment]
Try to run `sudo -u gdm env XDG_CURRENT_DESKTOP=GNOME-Greeter HOME=/var/lib/gdm3 gsettings get org.gnome.desktop.interface gtk-theme`

**Comment by marconallo** [comment]
<pre><font color="#8AE234"><b>marco@latitude</b></font>:<font color="#729FCF"><b>~</b></font>$ sudo -u gdm env XDG_CURRENT_DESKTOP=GNOME-Greeter HOME=/var/lib/gdm3 gsettings get org.gnome.desktop.interface gtk-theme
&apos;Yaru&apos;
</pre>

**Comment by Feichtmeier** [comment]
Used a cosmic VM different times, never ran into this issue. Thus closing this, as this can't be fixed by Yaru with CSS anyways
