### ISSUE TITLE
GtkButtons active/pressed styling

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#889]
GtkButtons currently have the following styling:

Normal - 1 level above main layer
![image](https://user-images.githubusercontent.com/15329494/46479754-13056800-c7f0-11e8-9350-5b11ba664b13.png)
Active - 1 level below main layer
![image](https://user-images.githubusercontent.com/15329494/46479821-40eaac80-c7f0-11e8-8e12-2e6090551cec.png)
So we press the button 2 layers/levels down

Do we really need that black top border?
Since the normal buttons are already "1 level above" the window layer, meaning 1 bit closer to the user if there would be a z-axis, wouldn't a press effect, that simply presses the button down TO THE layer of the rest enough?
Which would look like this:

Normal - 1 level above main layer
![image](https://user-images.githubusercontent.com/15329494/46479754-13056800-c7f0-11e8-9350-5b11ba664b13.png)
Active - on the main layer
![image](https://user-images.githubusercontent.com/15329494/46480143-e867df00-c7f0-11e8-88d3-1a7f42e621db.png)
Now we would press the button 1 layer/level down

@madsrh @clobrano ?

Post 18.10 discussion ofc :)

**Comment by Paz-it** [comment]
I'll appreciate it to be left as is. it helps me when I get that extra feedback for pressed  btn.

**Comment by madsrh** [comment]
I'm in doubt here 🤔 It looks better for sure, but with the current design I really like the extra usability - it's just obvious. We could (as we do with everything else) test it and see how it feels 🤷‍♂️

**Comment by clobrano** [comment]
I agree with Mads, I like the 3d effect for usability

**Comment by Feichtmeier** [comment]
How about lightening the top border a bit? When in clashes with the left and right borders it looks like there is a pixel missing

**Comment by clobrano** [comment]
I think it helps when there are disabled buttons around, but we can try to tweak it

**Comment by godlyranchdressing** [comment]
I think it's perfect as is, it's very obvious and for some reason, really satisfying to look at for me.

To help with the sharpness, maybe a box-shadow on top might help refine the top corners? I can't test it right now but just an idea.

**Comment by Feichtmeier** [comment]
We could try to lower the darkness of the top border so the difference between the border and the top border is less leveling. Otherwise just close it. I think everyone beside me is liking it no use from my point of view to stress this any further =)
