### ISSUE TITLE
Support GTK shipped in xenial to improve snap experience

### ISSUE THREAD

**Issue by kenvandine** [ubuntu/yaru#893]
GTK broke ABI for themes in 3.20, xenial shipped with 3.19.  Yaru doesn't support GTK versions prior to the ABI break.  Snaps built with GTK from xenial (most snaps) are not themed properly with Yaru.  Ambiance ships both gtk-3.20 and gtk-3.0 directories, including support for <= 3.20 as well as > 3.20.  I've snapped gtk3-widget-factory as part of the gtk-3-test snap (edge channel), built with GTK from xenial.  This can be used to see what Yaru looks like on 18.10 with a snap.

I think Yaru should be able to build a variant for < 3.20 by using a snapshot of Adwaita from before the ABI break as well as with the latest Adwaita and ship the resulting builds in separate directories.

**Comment by Feichtmeier** [comment]
> Snaps built with GTK from xenial (most snaps) are not themed properly with Yaru.

Could you clarify this? :) I am not sure if I got this right : (
Are you asking for theme support for snaps installed in 16.04? Or are you saying that some apps are built with some gtk parts that come from 16.04/ gtk-3.20 even if installed in 18.04?

**Comment by kenvandine** [comment]
To support snaps running on 18.10 and 18.04 but built with GTK from 16.04

**Comment by Feichtmeier** [comment]
Ah okay thank you for the clarification! :)

**Comment by kenvandine** [comment]
I think this is something @jhenstridge can work on, it will greatly improve the snap experience for 18.10 users.

**Comment by Feichtmeier** [comment]
I think it's fixed with https://github.com/ubuntu/yaru/pull/935
Closing this. Feel free to reopen if I'm wrong
