### ISSUE TITLE
Tweaks : list menu gets unreacheable items (Wayland only)

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#898]
Running Ubuntu 18.10 GNOME session with Yaru GTK theme and Adwaita icons.

**Adwaita** (expected behaviour)

![image](https://user-images.githubusercontent.com/23138504/46581517-610dac00-ca3a-11e8-8173-5d41519cbbb6.png)

**Yaru** (out of screen list + no up arrow to reach items)

![image](https://user-images.githubusercontent.com/23138504/46581532-91554a80-ca3a-11e8-9274-886cdd0d05da.png)

Dash to panel does not interfere here (tested). Running X there is no issue.

**Comment by fthx** [comment]
**Running X** (... and I realized that printing the screen was not as easy as running Wayland, I had to use the app with 5 seconds delay because the keyboard magic key does not work !) :

![image](https://user-images.githubusercontent.com/23138504/46585512-23c51080-ca72-11e8-9d80-73041f94c5e1.png)

**Comment by clobrano** [comment]
Installed Cosmic yesterday in a VM, I cannot reproduce the issue

![screenshot from 2018-10-09 19-25-21](https://user-images.githubusercontent.com/2883614/46686747-61a07100-cbf9-11e8-821c-f9fbc20e65fc.png)

**Comment by fthx** [comment]
Maybe : 
https://gitlab.gnome.org/GNOME/mutter/issues/332
did the trick, not Yaru-related anyway.

**Comment by clobrano** [comment]
I imagined it wasn't yaru related since it was without our session and reproducible with other themes. 
Thanks for testing ;)
