### ISSUE TITLE
Popover content doesn't fit inside popover

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#911]
From the daily build of Cosmic:

Steps to recreate:
1. Open Nautilus
2. Click the search icon
3. Click the dropdown arrow
4. Click "Select dates"

![image](https://user-images.githubusercontent.com/3986894/46835847-a110be00-cdaf-11e8-9857-ef0b3a945518.png)

**Comment by clobrano** [comment]
is this reproducible in yaru only?

**Comment by madsrh** [comment]
Ahhh, sorry. I remember now that this is an issue with X - Wayland is fine so I'm closing this 😄 

Sorry for the noise 🔕
