### ISSUE TITLE
Flatpak Gtk apps use Adwaita icons instead of Yaru/Suru icons

### ISSUE THREAD

**Issue by Ads20000** [ubuntu/yaru#913]
## Expected Behavior

Use the FilesMaster 3.30.0-7de42f4 Flatpak with Yaru with no theming problems.

## Actual Behavior

The lines in the window buttons and hamburger menus are too thick in both snaps and Flatpaks (see below for screenshots).

## Steps to Reproduce the Problem

1. `sudo apt install flatpak`
2. `flatpak remote-add --from gnome-apps-nightly https://sdk.gnome.org/gnome-apps-nightly.flatpakrepo`
3. `flatpak install gnome-apps-nightly org.gnome.NautilusMaster`
4. `flatpak run org.gnome.NautilusMaster`
5. See that the lines are too thick.
6. `snap install gnome-clocks`
7. `snap run gnome-clocks`
8. See that the lines are too thick.
9. `snap install gnome-characters`
10. `snap run gnome-characters`
11.  See that the lines are too thick
12. `snap install mailspring`
13. `snap run mailspring`
14. See that the lines are not too thick
15. `/usr/bin/nautilus`
16. See that the lines are not too thick

## Specifications

```
$ snap info communitheme
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: 6 days ago, at 18:54 BST
channels:                    
  stable:    0.1 (1273) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1275) 17MB -
installed:   0.1 (1275) 17MB -

$ snap version
snap    2.35.5
snapd   2.35.5
series  16
ubuntu  18.04
kernel  4.15.0-36-generic

$ snap info core
tracking:     beta
refresh-date: today at 09:42 BST
installed:   16-2.35.5                   (5742) 92MB core
```

Software that presents the issue:
- Name: FilesMaster
- Version: 3.30.0-7de42f4
- Format: Flatpak

![screenshot from 2018-10-16 15-14-18](https://user-images.githubusercontent.com/3178485/47023014-a4f96300-d156-11e8-9b68-13a2dc160360.png)

- Name: GNOME Clocks
- Version: 3.26.1 (78, `stable`)
- Format: snap

![screenshot from 2018-10-16 15-14-42](https://user-images.githubusercontent.com/3178485/47023048-b9d5f680-d156-11e8-96c2-7cb561a43969.png)

- Name: GNOME Characters
- Version: 3.29.91 (124, `stable`)
- Format: snap

![screenshot from 2018-10-16 15-15-06](https://user-images.githubusercontent.com/3178485/47023087-d1ad7a80-d156-11e8-8025-9b6897667daf.png)

Software that doesn't present the issue:
- Name: Mailspring
- Version: 1.4.2 (244, `stable`)
- Format: snap
![screenshot from 2018-10-16 15-17-21](https://user-images.githubusercontent.com/3178485/47023305-4ed8ef80-d157-11e8-9e4d-56b2e11830a4.png)

- Name: Files
- Version: 3.26.4
- Format: Deb
![screenshot from 2018-10-16 15-24-10](https://user-images.githubusercontent.com/3178485/47023421-8e074080-d157-11e8-879b-c4296428a77b.png)

**Comment by clobrano** [comment]
I believe this is related to  #915 , Yaru flatpak version does not provide the icons. I am unsure how to handle this, there is nothing we can do in this repository to fix this issue, so it is probably the wrong place to open the ticket, however even in the correct repository (https://github.com/flathub/org.gtk.Gtk3theme.Yaru) I don't know if icon management is possible

**Comment by Ads20000** [comment]
The bug applies to the GNOME Clocks snap as well?

**Comment by clobrano** [comment]
> The bug applies to the GNOME Clocks snap as well?

#915 doesn't. It seems, as you said, that all snaps do not get the right headerbar icons

**Comment by Feichtmeier** [comment]
Yup those are adwaita icons

**Comment by Feichtmeier** [comment]
Closing this as we can't fix this from our side. It's a flatpak thing sadly

**Comment by TingPing** [comment]
Flatpak just passes in host icons. I guess Yaru doesn't install them into `/usr/share/icons`?

**Comment by Ads20000** [comment]
Flatpak say they can't see how this is a Flatpak issue @Feichtmeier, could you please explain to them how it is a Flatpak issue?

**Comment by Feichtmeier** [comment]
I set up a PopOS VM and see how flatpaks behave there, since they use their own themes and icons, too =)

**Comment by Ads20000** [comment]
The bug doesn't seem to be reproducible (not even on my own system) so I have closed it.
