### ISSUE TITLE
The FilesMaster Flatpak is using the wrong icons

### ISSUE THREAD

**Issue by Ads20000** [ubuntu/yaru#915]
## Expected Behavior

Use the FilesMaster 3.30.0-7de42f4 Flatpak with Yaru with no theming problems.

## Actual Behavior

The icons are wrong (e.g. the folders are the wrong colour, the sidebar icons are 'filled in').

![screenshot from 2018-10-16 14-47-13](https://user-images.githubusercontent.com/3178485/47022258-07516400-d155-11e8-91f8-f068b5051d58.png)

## Steps to Reproduce the Problem

1. `sudo apt install flatpak`
2. `flatpak remote-add --from gnome-apps-nightly https://sdk.gnome.org/gnome-apps-nightly.flatpakrepo`
3. `flatpak install gnome-apps-nightly org.gnome.NautilusMaster`
4. `flatpak run org.gnome.NautilusMaster`

## Specifications

```
$ snap info communitheme
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: 6 days ago, at 18:54 BST
channels:                    
  stable:    0.1 (1273) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1275) 17MB -
installed:   0.1 (1275) 17MB -

$ snap version
snap    2.35.5
snapd   2.35.5
series  16
ubuntu  18.04
kernel  4.15.0-36-generic

$ snap info core
tracking:     beta
refresh-date: today at 09:42 BST
installed:   16-2.35.5                   (5742) 92MB core
```

Software that presents the issue:
- Name: FilesMaster
- Version: 3.30.0-7de42f4

**Comment by Feichtmeier** [comment]
Uhm that's the same issue add the other one.
Again, it is the adwaita icon theme.
So I keep this one opened until we have clarification on this.

**Comment by Feichtmeier** [comment]
Closing this as I have reopened the last one were the flatpak repo is linked too makes stuff easier. Thanks for reporting
