### ISSUE TITLE
Spacing off in Nautilus search options

### ISSUE THREAD

**Issue by tristan957** [ubuntu/yaru#916]
## Expected Behavior

See some UI spacing

## Actual Behavior

Not enough spacing between radio buttons and text labels

![image](https://user-images.githubusercontent.com/11936772/47059031-31267d00-d18d-11e8-94b7-59f19e4110f2.png)

## Steps to Reproduce the Problem

  1. Open nautilus
  2. Open search
  3. Click search drop down
  4. Click When

## Specifications

Running Solus, theme from repo

version: 18.10.4

Software that presents the issue:
- Name: Nautilus
- Version: 3.26.4

If you all don't support 3.26, I understand

**Comment by tristan957** [comment]
This is Tilix

![image](https://user-images.githubusercontent.com/11936772/47059463-148b4480-d18f-11e8-9495-543af1d14f7e.png)

**Comment by madsrh** [comment]
Hi. Thanks for taking the time to report this 👍 The spacing issue in Nautilus is already fixed here: https://github.com/ubuntu/yaru/pull/900

**Comment by tristan957** [comment]
Will this be in the next release?

Sorry for reporting again
