### ISSUE TITLE
Pinentry window getting fallback theming

### ISSUE THREAD

**Issue by tristan957** [ubuntu/yaru#918]
## Expected Behavior

When using pinentry for GPG, the window should use GTK theme.

## Actual Behavior

![image](https://user-images.githubusercontent.com/11936772/47126833-0d783b00-d250-11e8-8de9-af384845c3c7.png)

## Steps to Reproduce the Problem

  1. Commit using GPG

## Specifications

Yaru 18.10.4

Software that presents the issue:
- Name: Pinentry

**Comment by clobrano** [comment]
Same behavior for WPS suite

**Comment by tristan957** [comment]
I guess this a GTK2 bug in the dark theme that I have been reading about. Also affecting HexChat

**Comment by clobrano** [comment]
@tristan957, interesting, could you share where you read that?

**Comment by tristan957** [comment]
https://github.com/ubuntu/yaru/pull/852

https://community.ubuntu.com/t/yaru-dark-variant/7936/3

are these not related?

**Comment by tristan957** [comment]
I guess a bug is not the right term. More like like of assets in the GTK2 side of Yaru

**Comment by clobrano** [comment]
> are these not related?

Only if pinetry uses the dark variant

**Comment by clobrano** [comment]
Hexchat does not look affected to me

![image](https://user-images.githubusercontent.com/2883614/47602901-38e3ee00-d9e5-11e8-9c7c-e0fd1ad30429.png)

**Comment by Feichtmeier** [comment]
@tristan957 does this still happen?

**Comment by tristan957** [comment]
This is now fixed
