### ISSUE TITLE
Add official White Theme variant

### ISSUE THREAD

**Issue by ricjcs** [ubuntu/yaru#919]
Currently there is the Light and Dark variant.
it would be interesting a white version.

The theme would have the White Header Bar, would be Inspired by the old Radience theme, but more modern. Many people like the minimalism and elegance of a white theme, and it blends nicely with icones and orange accents.

There would be 3 variants of Yaru: Light (default), Dark and White

**Comment by dimztimz** [comment]
i'd like to see a yaru theme with light window frames too.

**Comment by Feichtmeier** [comment]
I like it too.

If the additional code is maintainable we could consider to add this. However, don't except it to happen.

**Comment by godlyranchdressing** [comment]
Something kind of like this?

![yaru-white-mockup](https://user-images.githubusercontent.com/27529229/47607460-25895080-d9ee-11e8-9a35-a7b172568eb0.png)

It'll mostly be the headerbar buttons and menubars to deal with but making a mockup is easier than actually doing it so, I might take some time.

**Comment by ricjcs** [comment]
@godlyranchdressing: Yes! I liked very much!
I also thought the headerbar like this:
![shiro](https://user-images.githubusercontent.com/11923491/47608611-49698800-da28-11e8-830b-63653535e4e5.png)
(https://github.com/dimoFeeld/shiro)

But your mockup is very beautiful.

**Comment by dimztimz** [comment]
I prefer the @godlyranchdressing mockup. It makes a clear separation of what is the main content and what is the header. I don't like the all white variation of @ricjcs.

For reference, see how macOS and the white Radiance theme look.

**Comment by taciturasa** [comment]
> Something kind of like this?
> 
> ![yaru-white-mockup](https://user-images.githubusercontent.com/27529229/47607460-25895080-d9ee-11e8-9a35-a7b172568eb0.png)
> 
> It'll mostly be the headerbar buttons and menubars to deal with but making a mockup is easier than actually doing it so, I might take some time.

I love this! I wouldn't go for the outlines for all buttons though - imo it should be the same border logic (grouped buttons and text buttons have a border, regular buttons do not when not hovered or active ) used in the hybrid and dark themes, for consistency/appeal :) There was also a mockup someone did I think on the discourse thread where they used a more translucent effect on the close button, so it was a bit lighter, and I thought it was a cool effect. With what I just said about consistency, though, implementing it might be a bit hypocritical

**Comment by godlyranchdressing** [comment]
@taciturasa to be honest, I forgot that the buttons were supposed to be flat till you pointed out. There is already a "light" stackswitcher in save dialogs:

![lightswitcher](https://user-images.githubusercontent.com/27529229/47675717-08d94e00-db91-11e8-95bf-d661a610b88c.png)

But I'm not too big a fan of the gray on the headerbar. The headerbar is already a grayish color and the double gray seemed to bring down the design, while the white stackswitcher seemed more friendly. The stackswitcher I'd like to keep hovering with a shadow, as well as entries as, in contrast to the sunken look done in the dark/regular theme.

Just my thoughts as well. It's best we iron out these issues sooner rather than later anyway.

**Comment by Feichtmeier** [comment]
This looks awesome. Let's get some ideas to implement this "smart" even that big stack of PRs is merged

**Comment by godlyranchdressing** [comment]
@Feichtmeier yeah, I was thinking about. Especially if we'll need to have this support GTK 3.18 as well.

**Comment by Feichtmeier** [comment]
Hm, the screenshot you posted looks really good. But I don't know how we should handle a third $variant without messing up the code & easy upstream down-merge-ability : /
I would rather use a fork and change the light theme to have a light headerbar

**Comment by godlyranchdressing** [comment]
@Feichtmeier I'll be honest, I don't know where to start with the logistics of it all but once it's set up I can take over and then we can tweak till we're content.

**Comment by clobrano** [comment]
I believe we're on the same page. I do not want to look like I don't like a new variation, but we're already managing too many things here. Feel free to fork Yaru (according to its license) :+1:

**Comment by rinaldus** [comment]
> Something kind of like this?
> 
> ![yaru-white-mockup](https://user-images.githubusercontent.com/27529229/47607460-25895080-d9ee-11e8-9a35-a7b172568eb0.png)
> 
> It'll mostly be the headerbar buttons and menubars to deal with but making a mockup is easier than actually doing it so, I might take some time.

Where can I download it? It looks super!
