### ISSUE TITLE
Search icon in files looks blurry in files

### ISSUE THREAD

**Issue by sumeetaras** [ubuntu/yaru#920]
## Expected Behavior
Icon should be clear.
Open Files app on Ubuntu 18.04 with communitheme snap.

## Actual Behavior
The search icon looks blurry.
![screen](https://user-images.githubusercontent.com/10984081/47172203-cf732980-d2d8-11e8-9873-9222b7df0c7c.png)

Here is the icon with Adwaita. Looks much clearer
![adwaita](https://user-images.githubusercontent.com/10984081/47172218-dac65500-d2d8-11e8-8af4-256eccea3740.png)

## Steps to Reproduce the Problem
Open Files app on Ubuntu 18.04 with communitheme snap. Observe the search icon

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

    $ snap info communitheme
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
More information is available at
https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 8 days ago, at 20:39 EDT
channels:                    
  stable:    0.1 (1273) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1275) 17MB -
  installed:   0.1 (1273) 17MB -

Thanks!

**Comment by sumeetaras** [comment]
Yes. It is just the search icon. Could it be my display resolution? I am using a QHD display.

**Comment by clobrano** [comment]
Really not sure about that and I can not reproduce this issue in my display with normal resolution :)
I believe @snwh knows best

**Comment by Feichtmeier** [comment]
@sumeetaras thanks for opening this issue. Could you please open this upstream? I close this here, best regards
