### ISSUE TITLE
Icons for Shotwell and GNOME Photos are the same

### ISSUE THREAD

**Issue by phako** [ubuntu/yaru#923]
## Expected Behavior

Different apps should be easily distinguishable

(What you were trying to do)
Starting Shotwell. 

## Actual Behavior
While browsing the app overview, I noticed that Shotwell and GNOME Photos have the same icon

## Specifications

ii  yaru-theme-gnome-shell                                      18.10.6                                     all          Yaru GNOME Shell desktop theme from the Ubuntu Community
ii  yaru-theme-gtk                                              18.10.6                                     all          Yaru GTK theme from the Ubuntu Community
ii  yaru-theme-icon                                             18.10.6                                     all          Yaru icon theme from the Ubuntu Community
ii  yaru-theme-sound                                            18.10.6                                     all          Yaru sound theme from the Ubuntu Community

Software that presents the issue:
- Name: GNOME Shell (for showing the overview), GNOME Photos, Shotwell
- Version: Whatever is in Ubuntu 18.10

**Comment by Feichtmeier** [comment]
@ubuntujaggers
Could you try to make a dedicated shotwell icon?
I think snwh is not interested in this upstream so maybe you can try something for yaru?
I once made that symlinks for suru because I thought it's better than "nothing" :man_shrugging:

**Comment by debarshiray** [comment]
> I once made that symlinks for suru because I thought it's
> better than "nothing"

How about just using the applications' original upstream icon?

**Comment by jbicha** [comment]
@Feichtmeier by the way, phako is the upstream Shotwell developer.

There is a concern about both apps using the same icon because the apps do different things and there are quite a few people who have both installed.

There is a proposal to switch to Photos by default in a future Ubuntu release, which will mean that upgraders will have both apps installed and it's important for users to be able to distinguish them.

I believe the symlink was added at the same time for Rhythmbox/GNOME Music, but Rhythmbox got its own icon 2 weeks later.

**Comment by ubuntujaggers** [comment]
@Feichtmeier @phako 

Is the upstream icon the image that appears at the top left of http://yorba.org/shotwell/help/?

![image](https://user-images.githubusercontent.com/38893390/47259350-6211f500-d4a0-11e8-81c1-a941fca00b35.png)

If so, I could try to do something very faithful that merely has a softer Suru-style drop shadow and sets the design on top of a Suru squircle?  Would everyone be happy with that?

**Comment by Feichtmeier** [comment]
I am not a fan of putting things ontop of the squircle. I think that suru idea works better when the whole icon is the squircle

**Comment by Feichtmeier** [comment]
Sounds like a very good idea to me! :)

**Comment by ubuntujaggers** [comment]
The most faithful thing to do would be to simply reconfigure the existing polaroid and "mask" it into the Suru polaroid template.  Most people who know the app would quickly recognise it as a Suru icon for Shotwell:

![image](https://user-images.githubusercontent.com/38893390/47269476-f7bb8c00-d555-11e8-9a8a-2d7cb6e55d80.png)

![image](https://user-images.githubusercontent.com/38893390/47269480-043fe480-d556-11e8-9185-1b5e95d742b8.png)

But we'd need the blessing of the artist to do this (the metadata for the svg says "proprietary", so unless that was an oversight, it's not creative commons).

Alternatively, for greater consistency with Suru, we could have something more stylised/simple.

**Comment by phako** [comment]
You can safely assume CC-BY-SA. Proprietary is wrong. sorry. See https://bugzilla.gnome.org/show_bug.cgi?id=717326 which suggests BY-SA or LGPLv3

**Comment by Feichtmeier** [comment]
@phako any chance we could either improve your upstream icon or change the pictogram we would use inside the Suru shape? 
Imho it could use some improvements.

**Comment by Feichtmeier** [comment]
@phako 
Thanks for the authorization and the issue report! 
I think the best for your app and this project would be if we would only take the pictogram and put it into the "squricle" like @ubuntujaggers  suggested. 

I am not an icon designer, so maybe @ubuntujaggers has an idea to make the pictogram itself a little bit less "glossy" and less "busy" and a bit flatter without losing it's current characteristic motive?

**Comment by ubuntujaggers** [comment]
I posted a comment and I think it vanished. Yes, I can have a go at that.

Should have also added: I think the scene with the tree is a great SVG, but @feichtmeier is right that it's drawn in a different style, so I see it as a case of trying to make it a bit more consistent with the Suru icons without making it unrecognisable. Hope I can manage it lol.

**Comment by ubuntujaggers** [comment]
Okay @Feichtmeier and @phako - here's attempt no. 1.

![image](https://user-images.githubusercontent.com/38893390/47317578-da63ec00-d641-11e8-92bd-51f0a5de5632.png)

![image](https://user-images.githubusercontent.com/38893390/47317602-ebacf880-d641-11e8-81c4-791c54db1a2e.png)

I've made the following adjustments to try to slightly "Suru-fy" the Shotwell design, while keeping it recognisable for people who know the app and not reinventing the wheel:

- I've got a flatter, more simple version of the graphic including a straight horizon;
- I've taken colours from the Suru palette;
- In place of the original element at the top right of the background, which was part of a transparent circle split in two, I have a Suru "fold" which lightens the same area in a less dramatic way;
- In an attempt to follow other Suru icons, the graphic is redrawn at smaller sizes to align with pixel boundaries and remove detail that's no longer visible.  The largest tree is traced closely from the original, and the smaller trees approximate the same shape with less detail.

I wouldn't call any of these changes "improvements" by any stretch  :)  (in fact, judged as a standalone svg it's the opposite) - but I hope it looks crisp on the Ubuntu launcher and blends in reasonably well with the rest of the Suru icons.

**Comment by Feichtmeier** [comment]
Really nice improvement points!

One last idea: could we try a bit more "friendly" tree which would also look more like "paper"/origami?
( [here is an example](https://media.gettyimages.com/photos/many-christmas-tree-over-light-green-paper-background-origami-made-picture-id499482050) )

**Comment by ubuntujaggers** [comment]
I can certainly try some different trees  :)  I did have a few early attempts at doing a more "Suru" tree made of flat polygons.  Paper tree designs tend to represent trees with leaves using triangles or ovals, which would be a more radical departure from the source design.

One possibility might be to make a bare tree out of polygons which approximate the shape, like Japanese origami.  An example would be the arms and legs of this monkey, where the joints of the limbs are made from folding the paper over: https://pngtree.com/freepng/cartoon-handwritten-origami-monkey_2921403.html.  It might be possible to make a paper-looking tree branch using two or three similar flat shapes.  I'll have a play in Inkscape  :)

**Comment by ubuntujaggers** [comment]
First attempt at an origami tree - the three smallest sizes definitely need more work:

![image](https://user-images.githubusercontent.com/38893390/47388887-44949380-d70b-11e8-87f8-ffc0496694a8.png)

![image](https://user-images.githubusercontent.com/38893390/47388910-4fe7bf00-d70b-11e8-86d5-5f9a5235c6f3.png)

**Comment by clobrano** [comment]
Nice work :+1: 
what do you think about using the same bright line used to separate two branches for underlining where the origami folds?

**Comment by ubuntujaggers** [comment]
I tried the same brightness but it made the tree look like a diagram or line drawing rather than an object...  what do you think of this, which adds extra edging to the other folds, but not as bright for all of them:

![newest origami shotwell](https://user-images.githubusercontent.com/38893390/47432295-bf09f580-d795-11e8-9cab-f95f0653486f.png)

...?

**Comment by clobrano** [comment]
It looks good. In the end, I might be too picky, at a normal size, these details would be hard to see anyway

**Comment by Feichtmeier** [comment]
It looks great to me!

**Comment by ubuntujaggers** [comment]
Super - I've done a bit of work on the smaller sizes - this is what it looks like now:

![image](https://user-images.githubusercontent.com/38893390/47437359-52e0bf00-d7a0-11e8-89ba-655bc372d28b.png)

![image](https://user-images.githubusercontent.com/38893390/47437423-77d53200-d7a0-11e8-822a-34701da8f4f1.png)

If this one is ready, can I commit it to the fork I used for the other icons (which I still have on my laptop)?

**Comment by Feichtmeier** [comment]
Yes, I merge it to the icon update branch then (it is on hold until some more weeks but then gets merged into master)

**Comment by phako** [comment]
That looks nice!

**Comment by ubuntujaggers** [comment]
Brilliant - for apps like this I think it's great when we can get a thumbs up from the upstream app developer  :)

**Comment by jbicha** [comment]
@phako Because of Ubuntu UI Freeze, I think we don't intend to change these icons for Ubuntu 18.10 so this will just be for 19.04 and later releases. Is that going to be a problem for you?

**Comment by ubuntujaggers** [comment]
@Feichtmeier 

I pushed it, it's now there in my fork: https://github.com/ubuntujaggers/yaru/blob/master/icons/src/fullcolor/apps/shotwell.svg

**Comment by taciturasa** [comment]
@ubuntujaggers You're getting really good at more suru-y icons. This looks beautiful!

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru/pull/901
