### ISSUE TITLE
Drive icons on desktop use symbolic icons

### ISSUE THREAD

**Issue by Exalm** [ubuntu/yaru#926]
## Expected Behavior

Icons should be fullcolor.

## Actual Behavior

Icons are symbolic.

## Steps to Reproduce the Problem

  1. Install Ubuntu
  2. Close "Welcome to Ubuntu" dialog
  3. Look at the desktop

## Specifications

Default Ubuntu 18.10 image.

```
ii  yaru-theme-icon                            18.10.6                                    all          Yaru icon theme from the Ubuntu Community
```

![screenshot from 2018-10-20 23-31-55](https://user-images.githubusercontent.com/1510457/47259268-8d8fe200-d496-11e8-9be7-c06755012d19.png)

**Comment by clobrano** [comment]
@Exalm, thanks for reporting this, an upstream bug is already opened https://github.com/snwh/suru-icon-theme/issues/101
