### ISSUE TITLE
Many icons are missing in high contrast mode

### ISSUE THREAD

**Issue by Exalm** [ubuntu/yaru#927]
## Expected Behavior

Every app has a proper symbolic icon for high contrast mode.

## Actual Behavior

Characters and Logs are missing an icon.

Amazon, Calculator, Remmina, Software & Updates, Startup Disk Creator, System Monitor, Thunderbird, Ubuntu Software are using fullcolor icons, in some cases different from default.

LibreOffice, Software Updater, Startup Applications and Transmission are using deprecated HighContrast icons.

## Steps to Reproduce the Problem

  1. Settings → Universal Access → High Contrast
  2. Show Applications

## Specifications

Default Ubuntu 18.10 image.

![screenshot from 2018-10-20 23-53-00](https://user-images.githubusercontent.com/1510457/47259473-6c7cc080-d499-11e8-9a6f-55ef8d6a1476.png)

![screenshot from 2018-10-20 23-53-07](https://user-images.githubusercontent.com/1510457/47259476-71417480-d499-11e8-9e12-8b122f265495.png)

![screenshot from 2018-10-20 23-53-10](https://user-images.githubusercontent.com/1510457/47259481-77375580-d499-11e8-8eee-53cec2026b1a.png)

**Comment by Feichtmeier** [comment]
Looks like all "ubuntu specific" apps/.desktop files are the problem and/or snaps.
I don't think that this is a yaru topic tbh

**Comment by Exalm** [comment]
Where exactly? I always get lost on launchpad tbh

**Comment by clobrano** [comment]
+1 closing this, those icons are not related to Yaru

**Comment by Feichtmeier** [comment]
@Exalm I think it should be ubuntu-themes on launchpad :) thanks for opening issues, we close this now here

**Comment by Exalm** [comment]
Ok, https://bugs.launchpad.net/ubuntu-themes/+bug/1799440
