### ISSUE TITLE
Dash to dock notification counter has wrong color

### ISSUE THREAD

**Issue by clobrano** [ubuntu/yaru#928]
## Expected Behavior
notification counter is green

## Actual Behavior
the notification counter is red with green border
![screenshot from 2018-10-22 12-32-01](https://user-images.githubusercontent.com/2883614/47288702-79afc180-d5f7-11e8-8276-026633cc3834.png)

## Specifications
on Yaru master

**Comment by Feichtmeier** [comment]
I had this problem once when I fiddled around with the dash to dock configs. The result were that I needed to reinstall Ubuntu, because I lacked the skills to undo what I did :)

Is this on a fresh installation?

**Comment by clobrano** [comment]
So, it is probably due to the fact I reinstalled Yaru from source?
If that so, and nobody can reproduce this, I'll close the bug

**Comment by Feichtmeier** [comment]
Let me check on my VM first

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/47293168-a66cd480-d609-11e8-951c-264240f29ab1.png)

I have the dock and panel transparency difference (which is new, right?) but the color of the badge is correct :thinking:

**Comment by clobrano** [comment]
Yep, on bionic at least the dock is more transparent. In cosmic is it ok, right?

**Comment by Feichtmeier** [comment]
Oh no :( fresh cosmic VM and it happens here as well :(
![image](https://user-images.githubusercontent.com/15329494/47357785-09bd3c00-d6c8-11e8-8ac7-d42cf104557b.png)

Imho this is a really high prio, since those green badges are kind of iconic for the whole look

**Comment by Feichtmeier** [comment]
When one uncomments the styling of the notification badge inside Ubuntu-dock/stylesheet.css the red badge overlay is gone.
So we could make a pull request at the Ubuntu dock repo or any other ideas? @didrocks @clobrano

**Comment by clobrano** [comment]
I'd like to have a better understanding of the issue, first. I'll check it
again this afternoon, then I can ask upstream, they're always very
supportive

Il mer 24 ott 2018, 12:11 Feichtmeier <notifications@github.com> ha scritto:

**Comment by Feichtmeier** [comment]
Okay great!
Best would be if we wouldn't use that second CSS file at all (I think this is how it was before?). To have full control over the theming

**Comment by clobrano** [comment]
I understand, but ad usual, it can be installed in other OS, I think

Il mer 24 ott 2018, 13:00 Feichtmeier <notifications@github.com> ha scritto:

**Comment by clobrano** [comment]
> Best would be if we wouldn't use that second CSS file at all (I think this is how it was before?). To have full control over the theming

We have the control. When installed from source (but for sure also when installed otherwise), an empty file `yaru.css` is created in the dash-to-dock extension folder (`/usr/share/...`) by the script `install-dock-override`. This should let the main css file override dock's one.
However, as you said, only removing the conflicting styling in dock our style is applied, probably there's something wrong in dock's mechanism

**Comment by clobrano** [comment]
https://github.com/micheleg/dash-to-dock/issues/824

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru/pull/934
