### ISSUE TITLE
Yaru's theming for slider-widget doesn't draw a track at all when GTKAdjustment isn't provided, which makes it hard to interpret slider position in Firefox

### ISSUE THREAD

**Issue by dholbert** [ubuntu/yaru#930]
## Expected Behavior
Yaru's slider-widget should have a clearly visible track, to make it clear what percentage the "thumb" represents.

## Actual Behavior
Yaru's themed slider-widget doesn't have a track visible at all -- it just shows the thumb, with no reference for how far it is in the range.

## Steps to Reproduce the Problem

  1. View this URL in Firefox, in Ubuntu with Yaru theme: `data:text/html,<input type="range">`, or this JSFiddle: https://jsfiddle.net/e1s57u0z/

This just renders a detached floating white circle, without it being obvious that it's a slider on a track.
If I switch theme to e.g. "Adwaita", then I get a slider widget with a clearly-visible track.

## Specifications
Note: I didn't manually install Yaru -- it's just the theme that was there by default, in Ubuntu 18.10.  Here's what `$ snap info communitheme` says:
````
snap-id: Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
channels:                    
  stable:    0.1 (1273) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1287) 17MB -
````

**Comment by dholbert** [comment]
Screenshot with Yaru (showing the issue):
![image](https://user-images.githubusercontent.com/426803/47462963-bca99a80-d799-11e8-88c2-0b6f818ff2f3.png)
Screenshot with Adwaita (showing how it should ideally look, roughly):
![image](https://user-images.githubusercontent.com/426803/47462993-d0ed9780-d799-11e8-97b3-b1292403372d.png)

**Comment by clobrano** [comment]
Hi @dholbert, thanks for reporting this.
Here is how GTK applications render the slider

![image](https://user-images.githubusercontent.com/2883614/47463194-ce189400-d7e5-11e8-92ac-92703530a0ed.png)

there's something wrong in how Firefox render this for sure, even on Adwaita the rendering is incomplete. This is how it should be

![image](https://user-images.githubusercontent.com/2883614/47463240-f0121680-d7e5-11e8-8a9d-da348f607d62.png)

**Comment by dholbert** [comment]
Thanks for the response!  Hmm, @karlt do you know what might be going on here? I'll file a Mozilla widget:gtk bug I suppose.

**Comment by dholbert** [comment]
@clobrano do you know if there's a convenient way I can see how a non-Firefox GTK application renders the widget? (Is there a demo app I can compile+run, or is there an app you're aware of that has these sliders? I'm not super-familiar with GTK development or else I could probably spin up my own hello-world code quickly.)

**Comment by clobrano** [comment]
@dholbert gtk-3-examples package is what you're looking for. It provides both a gtk3-widget-factory demo application with most of the widgets and a gtk3-demo with a collection of examples with code

    $ sudo apt install gtk-3-examples

**Comment by clobrano** [comment]
Epiphany draws it correctly (as I expected, being the Gnome web browser :smile: )

![screenshot from 2018-10-24 23-50-40](https://user-images.githubusercontent.com/2883614/47463847-b3471f00-d7e7-11e8-904f-fbb2729e972d.png)

**Comment by clobrano** [comment]
closing this then, since it's a Firefox problem

**Comment by dholbert** [comment]
Thanks for your help!  I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1501858 on this in Firefox.

My shot-in-the-dark guess right now is that maybe we (Firefox) are asking GTK for some "degraded/colorless" version of the widget (since even in Adwaita where we get a track, it's colorless in Firefox), and maybe that version of the widget isn't complete in Yaru...

Anyway, I'll add additional info here if we find anything that needs doing on the Yaru end when we're sorting this out on the Firefox side. Thanks again for the helpful responses here.

**Comment by clobrano** [comment]
> My shot-in-the-dark guess right now is that maybe we (Firefox) are asking GTK for some "degraded/colorless"

we had/have many problem in how Firefox decides what to take and what not from the theme

> Anyway, I'll add additional info here if we find anything that needs doing on the Yaru end when we're sorting this out on the Firefox side.

Yes please, and thank you

**Comment by dholbert** [comment]
OK, I've got a standalone GTK program that draws a grayscale track/trough with Adwaita, but does not draw the track/trough in Yaru -- I'll post that here shortly. Hoping it might be helpful in tracking down what's missing here...

**Comment by dholbert** [comment]
.c file:
````c
#include <gtk/gtk.h>

GtkWidget *
do_scale (GtkWidget *do_widget)
{
  static GtkWidget *window = NULL;

  if (!window)
    {
      GtkBuilder *builder;

      builder = gtk_builder_new_from_file ("/tmp/scale.ui");
      gtk_builder_connect_signals (builder, NULL);
      window = GTK_WIDGET (gtk_builder_get_object (builder, "window1"));

      gtk_window_set_screen (GTK_WINDOW (window),
                             gtk_widget_get_screen (do_widget));
      g_signal_connect (window, "destroy",
                        G_CALLBACK (gtk_widget_destroyed), &window);

      g_object_unref (builder);
    }

  if (!gtk_widget_get_visible (window))
    gtk_widget_show_all (window);
  else
    gtk_widget_destroy (window);


  return window;
}
int
main(int argc, char **argv)
{
    GtkWidget *window;

    gtk_init(&argc, &argv);
    window = do_scale(NULL);
    g_signal_connect(window, "destroy", G_CALLBACK(gtk_main_quit), NULL);
    gtk_main();
    return 0;
}
````

.ui file (which the above C program expects to live at `/tmp/scale.ui`:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <!-- The following is reduced from "gtk3-demo"-provided source code
       for slider.ui -->
  <!-- Some of the following is probably unnecessary. -->
  <object class="GtkWindow" id="window1">
    <property name="title" translatable="yes">Scales</property>
    <property name="border-width" translatable="yes">20</property>
    <child>
      <object class="GtkGrid" id="grid1">
        <property name="visible">1</property>
        <property name="row-spacing">10</property>
        <property name="column-spacing">10</property>
        <child>
          <object class="GtkLabel">
            <property name="visible">1</property>
            <property name="label">Horizontal line:</property>
            <property name="xalign">0</property>
          </object>
          <packing>
            <property name="left_attach">0</property>
            <property name="top_attach">0</property>
          </packing>
        </child>
        <child>
          <object class="GtkScale">
            <property name="visible">1</property>
            <property name="can_focus">1</property>
            <property name="width-request">200</property>
            <property name="draw_value">0</property>
            <property name="hexpand">1</property>
          </object>
          <packing>
            <property name="left_attach">1</property>
            <property name="top_attach">0</property>
          </packing>
        </child>
      </object>
    </child>
  </object>
</interface>
````

Compile with the following command (which produces an executable called `scale-demo`:
````bash
gcc `pkg-config --cflags gtk+-3.0` /tmp/scale.c `pkg-config --libs gtk+-3.0` -o scale-demo
````

The resulting `scale-demo` program doesn't show any track at all when I've got the Yaru theme applied, vs. it does show a horizontal track when I've got the Adwaita theme applied.

@clobrano is there anything you can glean from that?

**Comment by dholbert** [comment]
The key thing that determines whether Yaru paints the pretty colorful version vs. nothing-at-all seems to be the `adjustment` object.  If I edit the .ui file to add the following as the first child of `<interface>`...
````xml
  <object class="GtkAdjustment" id="adjustment1">
    <property name="upper">4</property>
    <property name="value">2</property>
  </object>
````
...and add this inside the `<object class="GtkScale">` tag:
````xml
            <property name="adjustment">adjustment1</property>
````
...then the demo program will draw a pretty track + thumb like the one that @clobrano [screenshotted above](https://github.com/ubuntu/yaru/issues/930#issuecomment-432837681).

Without this adjustment property, Adwaita still draws a dummy track (with no thumb), whereas Yaru draws nothing.

I'm pretty sure Firefox draws the track and the thumb as separate components, so we are probably doing something like this to draw a "dummy" track (and caching that rendering), and that results in nothing-being-drawn in the Yaru theme, as we can see here with this demo program.

**Comment by dholbert** [comment]
Screenshot of demo program with vs. without GtkAdjustment, under Yaru:
![image](https://user-images.githubusercontent.com/426803/47466505-524b2700-d7a6-11e8-9afb-123fac9dcb3c.png)

Screenshot of demo program with vs. without GTKAdjustment, under Adwaita:
![image](https://user-images.githubusercontent.com/426803/47466513-6000ac80-d7a6-11e8-8a84-ea8c0e8d548c.png)

**Comment by dholbert** [comment]
@clobrano given that we've got a minimal GTK-program testcase that reproduces what seems to be a Yaru-specific issue here, do you think this merits reopening/investigation?

**Comment by clobrano** [comment]
The difference is because Yaru does not define (intentionally) a track border, which is the only thing drawn in adwaita. If I add a red border in yaru, this is the result of your code

![image](https://user-images.githubusercontent.com/2883614/47481998-9e917800-d835-11e8-9de4-e133fb48aa47.png)

We removed the borders to give the slider a modern look

this is Yaru now
![image](https://user-images.githubusercontent.com/2883614/47482193-1e1f4700-d836-11e8-987a-e85061baf04d.png)

this is Yaru with such border
![image](https://user-images.githubusercontent.com/2883614/47482156-047dff80-d836-11e8-89b5-cc5370b80308.png)

I am no GTK expert, is there a reason to remove a property that is suggested in a official gtk example?
Otherwise, since this guideline is working, I don't see the reason to change current version.

**Comment by dholbert** [comment]
> I am no GTK expert, is there a reason to remove a property that is suggested in an official gtk example?

In Firefox's case, I think it's because we draws the track and the thumb as completely separate entities, so we don't necessarily know the `value` when we draw the track (which is why we end up with an un-colorful track, I think).

I wonder if there are any GTK requirements/guidelines on how a slider is supposed to look when the `value` is unspecified? That's really the only property that I have to remove from the official GTK example, in order for it to draw nothing in Yaru.

**Comment by dholbert** [comment]
Actually/equivalently, I can trigger the problem by tweaking the official GTK example to use an `upper` and `value` that are both equal to 0.  (These properties [both default to 0](https://developer.gnome.org/gtk3/stable/GtkAdjustment.html#GtkAdjustment--upper), too, incidentally, which is presumably why leaving them out vs. specifying them as 0 have the same result.)

So it doesn't seem like my GTK testcase is triggering undefined/edge-case behavior, really -- rather, it's triggering a version of the default behavior, and it seems reasonable to expect that *something* should be drawn in this values-at-their-defaults scenario.

**Comment by dholbert** [comment]
Here's a screenshot of the stock GTK "scale" demo app from `gtk3-demo`, with the .ui file simply edited to set `value` and `upper` to 0, in the `GtkAdjustment` sections (and to reiterate, 0 is the default value for those properties, so this isn't quite as crazy as it sounds)

With Yaru:
![screenshot of Yaru](https://user-images.githubusercontent.com/426803/47523212-57fb4800-d84c-11e8-8c2d-f096a2a160bb.png)

...vs. with Adwaita:
![screenshot of Adwaita](https://user-images.githubusercontent.com/426803/47523341-a7da0f00-d84c-11e8-9927-0ea8db14c15f.png)

**Comment by clobrano** [comment]
>  In Firefox's case, I think it's because we represent & draw the track and the thumb as completely separate entities, so we don't necessarily know the value when we draw the track (which is why we end up with an un-colorful track, I think).

remember that Epiphany drawn your example correctly, so I believe this is Fireox fault

> and to reiterate, 0 is the default value for those properties, so this isn't quite as crazy as it sounds

I played a little with Yaru's slider and I saw we can mimic Adwaita's behavior imposing a min-height of 2px in scale, however what's the real improvement? In your example the interface look still broken in Adwaita too, nobody should ship an interface like that and nobody actually does, I've never seen such use case in a real application.

**Comment by dholbert** [comment]
> remember that Epiphany draws your example correctly, so I believe this is Firefox fault

Sure -- Firefox is admittedly doing something a bit weird, Frankenstein'ing the widget together by drawing a "dummy track" first and then a manually-positioned thumb on top of it.

The real question here is whether Firefox's trick for getting a "dummy track" is something that should be expected to work or not.

> what's the real improvement? In your example the interface looks broken in Adwaita too, nobody should ship an interface like that and nobody actually does, I've never seen such use case in a real application.

In my example with upper==value==lower, Adwaita draws a line with no thumb, which to me is precisely what you'd expect to see for a range of length 0 (there is no range, hence there is no place where it'd make sense to put the thumb; still, there's an visual representation of an inactive slider widget).

RE use-cases in real applications, how about this: any application that uses sliders whose ranges are determined by unknown-in-advance / user-provided data?  Some sort of charting app with slider widget for each column, for example.  In that scenario, if the user-provided data happens to all be equal in a given column (which gives a widget whose `lower` and `upper` are equal), it'd be nice for the theme to draw some sort of inactive slider widget, rather than drawing nothing at all.  That seems to be what Adwaita is doing, whereas Yaru is drawing nothing in that scenario.

**Comment by clobrano** [comment]
> The real question here is whether Firefox's trick for getting a "dummy track" is something that should be expected to work or not.

From a GTK point of view, a scale is actually made of two different widget, the "trough" and the "slider".
However, having only one of them is just a broken widget to me

> In my example with upper==value==lower, Adwaita draws a line with no thumb, which to me is precisely what you'd expect to see for a range of length 0 (there is no range, hence there is no place where it'd make sense to put the thumb; still, there's an visual representation of an inactive slider widget).

I would agree with you (hardly, but...) from a developer perspective, however consider the user perspective, or, more important, a first user.
Imagine a random person opening the tool and see this undefined widget, be it an empty space or just a line with a label. What is he/she supposed to do? It doesn't make any sense, since he/she isn't supposed to know that it will be a scale once loaded the data.
Wouldn't be a better approach to not show anything, not even the "dummy track" if there is not enought knowledge to do it?

**Comment by dholbert** [comment]
> From a GTK point of view, a scale is actually made of two different widget, the "trough" and the "slider".

Right, but there are well-defined cases where it's impossible to pick a good position for the slider. For example, when lower==upper.

> Imagine a random person opening the tool and see this undefined widget, be it an empty space or just a line with a label. What is he/she supposed to do?

They're supposed to infer (partly from context elsewhere in the app, e.g. values displayed nearby to summarize the range of data) that there's a 0-length range, and that that's why they get a useful slider for every other column of data and can pick between different values, but cannot do so for this column of data.

One other possible use-case: a volume-control app which has controls for all the possible fancy audio channels (left,right,rear-left, rear-right,subwoofer,etc), which gets the ranges of these channels from the OS and which may find that a channel does not exist.  The app may choose to hide that channel, but perhaps it could also choose to show the channel in a "disabled" state, which in part would have lower==upper==0 (or with an unspecified GTKAdjustment object, which has the same effect).  In that scenario, an empty trough seems more useful to display than nothingness.

Also: I found a reference to this in the [GTK documentation](https://developer.gnome.org/gtk3/stable/GtkScale.html#GtkScale.description), which I think agrees with my expectation:
> Note that using the same upper and lower bounds for the GtkScale (through the GtkRange methods) will **hide the slider itself**. This is useful for applications that want to show an undeterminate value on the scale, without changing the layout of the application (such as movie or music players).

(emphasis added) -- the expectation is that the scale should still draw, specifically with the slider (the thumb) hidden (i.e. the trough should draw)

**Comment by dholbert** [comment]
Thanks for the action on this!  I'd like to test the fix, but I'm not sure how.  Help would be appreciated!

I ran the `snap install` command from #942 (modified from `snap refresh` command there), and I did `sudo apt remove yaru-theme-gtk` for good measure to get rid of any apt-provided Yaru theming, but now yaru simply doesn't show up in my `gnome-tweaks` application-theme dropdown (nor does "communitheme").

I searched a bit and [found some (maybe-out-of-date) instructions](https://www.omgubuntu.co.uk/2018/02/install-the-new-ubuntu-theme) about adding `ppa:communitheme/ppa` and installing `ubuntu-communitheme-session` from that PPA, but I got blocked there as well, because the PPA gives me an error when I add it:
````
Err:10 http://ppa.launchpad.net/communitheme/ppa/ubuntu cosmic Release        
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/communitheme/ppa/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
````
Plus, I don't see `ubuntu-communitheme-session` listed at https://launchpad.net/~communitheme/+archive/ubuntu/ppa/+packages so I don't think the package exists anymore.

What are the current best-practices for getting the snap-provided theme actually active on Ubuntu 18.10 these days?

**Comment by dholbert** [comment]
Aha, I think I sorted it out -- looks like I need to `apt install communitheme-snap-session`. Testing now...

**Comment by dholbert** [comment]
Yup, this seems fixed with the yaru snap from #942! I tested with my sample .c program here, as well as in Firefox with my testcases from comment 0, which look like this now:
![image](https://user-images.githubusercontent.com/426803/48279784-76457400-e406-11e8-9a3f-1549c5eab673.png)


Thanks again for the fix here.  Looking forward to seeing this Yaru update make it out to the stock `yaru-theme-gtk` Ubuntu package.

**Comment by dholbert** [comment]
@clobrano: do you have a guess about when this might make it to the stock Ubuntu 18.10 version of Yaru?  (Do we need to do anything to make that happen, e.g. file a bug on launchpad to get this backported or something like that?)

**Comment by clobrano** [comment]
Hi @dholbert, yes on already released Ubuntu versions there's a procedure to follow https://wiki.ubuntu.com/StableReleaseUpdates
