### ISSUE TITLE
Terminal scrollbar extends out of window under Wayland 

### ISSUE THREAD

**Issue by febcrash** [ubuntu/yaru#936]
Same problem https://github.com/ubuntu/yaru/issues/777 on ubuntu 18.10 (Cosmic) on Wayland session
![2018-10-24_11-25](https://user-images.githubusercontent.com/5707986/47567036-c06e2600-d92d-11e8-9d4b-7a6ec0c32a9f.png)

**Comment by clobrano** [comment]
Thanks @febcrash to report this, I'll reopen #777 and close this
