### ISSUE TITLE
Authentication dialog title uses Adwaita styling

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/yaru#937]
## Expected Behavior

Authentication dialog title color should be using the same font color and font weight as other dialog titles, see an example in the shutdown dialog. #3B3B3B font color, font weight isn't bold:

![shut](https://user-images.githubusercontent.com/27529229/47581261-e8a25880-d91e-11e8-8cb1-75dd406a15d9.jpg)

## Actual Behavior

Authentication dialog titles look like they do in Adwaita: lighter font color, bold font. This is probably the fallback styling, unless you explictly define how something looks for the Shell, the element always falls back to Adwaita styling.

![aut](https://user-images.githubusercontent.com/27529229/47581238-daecd300-d91e-11e8-988f-ebe4e92a4bb5.jpg)

## Steps to Reproduce the Problem

Open a program that requires authentication (gparted, etc.) or try to install a program from the software center

**Comment by clobrano** [comment]
![image](https://user-images.githubusercontent.com/2883614/47602613-a857de80-d9e1-11e8-9a3a-d5b0ba60e6b4.png)

I am not 100% sure, but in my system the authentication pop up looks Yaru-ish

**Comment by eaglersdeveloper** [comment]
I think the problem in header's color.

**Comment by eaglersdeveloper** [comment]
The shutdown dialog, on the contrary, doesn't looks in Yaru style.

**Comment by clobrano** [comment]
In my system, the shutdown dialog is like the one we have in the wiki

![image](https://user-images.githubusercontent.com/2883614/47603804-34bdcd80-d9f1-11e8-9768-008d6275ff0d.png)

however, while taking screenshots something weird happend, the shutdown dialog changed from Yaru to Adwaita style. It happened just once though

**Comment by eaglersdeveloper** [comment]
This is hardly related to the theme. This is the glitch of Shell.

**Comment by eaglersdeveloper** [comment]
I meant not only the background color, but header and button style.

![2018-10-27 09-09-21](https://user-images.githubusercontent.com/40228953/47606462-ed513480-da24-11e8-93f7-6f226f18f3be.png)

In GTK's MessageDialog font weight of header is bold and button style different.

**Comment by clobrano** [comment]
> This is hardly related to the theme. This is the glitch of Shell.

That's understood, this is why didrock might be interested.

However, if I got it right, the point of this ticket is not the difference
between our gtk and shell theme, which is wanted.

Il sab 27 ott 2018, 18:16 Eaglers <notifications@github.com> ha scritto:

**Comment by eaglersdeveloper** [comment]
It turns out that the background color is different.
MessageDialog has a dazzling white background (`#FFFFFF`)
The Shell's dialog has an almost white background (`#F4F4F4`)

**Comment by eaglersdeveloper** [comment]
I will create an issue.

**Comment by clobrano** [comment]
Have you manage to reproduce this issue?

Il sab 27 ott 2018, 18:29 Eaglers <notifications@github.com> ha scritto:

**Comment by eaglersdeveloper** [comment]
What did you do?

**Comment by godlyranchdressing** [comment]
It seems hardcoded. I did everything I could think of and still nothing. There's no unused relevant class in polkitAgent.js either.

![ijadofp](https://user-images.githubusercontent.com/27529229/47606821-654c3a00-d9e6-11e8-9b89-6bc7deed4498.png)

**Comment by clobrano** [comment]
Ok, the problem was also me reading the bug description on a small screen and missing that the subject was the dialog **title**. Sorry for the noise

**Comment by clobrano** [comment]
How does it look this way?

(below the auth dialog, there is a screenshot of shutdown dialog for comparison)

![image](https://user-images.githubusercontent.com/2883614/47615018-78740e00-daa9-11e8-98ff-21f50ff54370.png)

**Comment by godlyranchdressing** [comment]
That looks good. That's what I was trying to get it to look like. Is that a mockup though, or is that how it looks on your system? (I'm still on 3.28)

**Comment by clobrano** [comment]
It's the real system. I modified the `.message-dialog-title` class. I am
about to open a PR only with that, and another one for the background color
