### ISSUE TITLE
Shell dialogs are different from MessageDialog

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#938]
**We need to make Shell's dialogs similar to MessageDialog.**

This is GTK's MessageDialog:

![2018-10-27 09-09-21](https://user-images.githubusercontent.com/40228953/47606698-d8c26b80-da27-11e8-8766-19d84765692a.png)

This is Shell's PolicyKit dialog;

![](https://user-images.githubusercontent.com/2883614/47602613-a857de80-d9e1-11e8-9a3a-d5b0ba60e6b4.png)

This is Shell's shutdown dialog:

![](https://user-images.githubusercontent.com/2883614/47603804-34bdcd80-d9f1-11e8-9768-008d6275ff0d.png)

Differences:

- [ ] **Button style**
- [x] **Background color**
MessageDialog has a dazzling white background (`#FFFFFF`)
Shell's dialog has an almost white background (`#F4F4F4`)
- [ ] **Headline**
In MessageDialog it is a bit bigger.
In shutdown dialog headline has normal font weight (in MessageDialog font weight is bold).

**Comment by godlyranchdressing** [comment]
@clobrano including the background color difference? I did note that they looked different, but I wouldn't have guessed that it was a different background color. Maybe that could be changed and leave everything else the same?

**Comment by clobrano** [comment]
It's slightly different indeed. On shell the color is #FAFAFA with some transparency.
We can have exactly the same color only removing the transparency, which I'm unsure we should do it, moreover when shell dialogs appear the all interface becomes darker, so having a more brilliant white might disturb a little. I tried it a little and I am not 100% sure already. I can propose a PR so you all can have a look
