### ISSUE TITLE
Volume icon in gnome-shell is different in normal vs hover states

### ISSUE THREAD

**Issue by alice-mkh** [ubuntu/yaru#939]
Default Ubuntu 18.10 image.

![normal](https://user-images.githubusercontent.com/1510457/47615246-81aeac00-daa4-11e8-9211-86fd36ab6de6.png)
![hover](https://user-images.githubusercontent.com/1510457/47615247-81aeac00-daa4-11e8-9db3-1365e32834b7.png)
![active](https://user-images.githubusercontent.com/1510457/47615248-82474280-daa4-11e8-9e76-60764df633df.png)

**Comment by clobrano** [comment]
Hi @Exalm, thank you for taking time to help us.

I must admit that I saw this problem during the last years from time to time, independently from the theme used. We should investigate more.

**Comment by clobrano** [comment]
@madsrh, if I remember correctly, you had the same issue. Can you reproduce it or is it gone?
