### ISSUE TITLE
Libre Office opens files with the all black background once in a while (similar to #350)

### ISSUE THREAD

**Issue by barrel0luck** [ubuntu/yaru#943]
## Expected Behavior
Libre Office expected default look.

## Actual Behavior
Libre Office opens with the background all black. Similar to issue #350.
I'm not sure what the trigger is, this doesn't happen every time, only once in a blue moon. The issue persists after it has been triggered until system restart (which is the annoying bit about the issue).

## Steps to Reproduce the Problem

  1. I don't know. After opening the files many times or extended usage of the desktop in general - not sure what the trigger is unfortunately.

## Specifications

Ubuntu 18.04

    `$ snap info communitheme`
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 21 days ago, at 14:54 IST
channels:                    
  stable:    0.1 (1273) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1290) 17MB -
installed:   0.1 (1273) 17MB -

Software that presents the issue:
Name: Libre Office:
Version: 6.1.3.2
Build ID: libreoffice-6.1.3.2-snap1

**Comment by barrel0luck** [comment]
I forgot to mention that this happens with the Libre Office 6.1.2.1 snap app on Ubuntu 18.04.

**Comment by clobrano** [comment]
Hi @barrel0luck, thanks for helping us. I edited your message to focus on the important contents.

**Comment by barrel0luck** [comment]
I realized I've made a mistake in the version number of LibreOffice (I'm sorry the Software Centre is just too confusing at times). I've edited both my replies to correct that.

**Comment by clobrano** [comment]
I am still unable to reproduce this even just once

**Comment by Feichtmeier** [comment]
@barrel0luck could you please test is this also happens with the .Deb version of libre office and check both Deb and snap with adwaita?
I am quiet sure that we can't do anything about this here in this repo and this smells like some snap issue to me

**Comment by barrel0luck** [comment]
So this happened again. As I said before, it is highly unpredictable. Here's the screenshot. So far this has not happened with the deb version. I'm not sure where to post this issue.
![screenshot from 2019-02-15 11-29-52](https://user-images.githubusercontent.com/44344748/52854246-c9217c80-3115-11e9-8fcc-c6500549eb5f.png)

**Comment by Feichtmeier** [comment]
On the snap craft forum :)
