### ISSUE TITLE
The topbar and the dock turn dark (as they do for maximised windows) when the window is very close, but not touching the top bar. (Not sure if this is expected).

### ISSUE THREAD

**Issue by barrel0luck** [ubuntu/yaru#944]
Thank you for contributing to **Yaru**, the next Ubuntu default Theme made by the community.

If you found a bug please consider to fill below information, this will help us to understand the problem and we don't bother you with other questions :)

If you're filing an issue for a missing icon, look for **Icon Request** section below.

Thanks a lot!

------ ISSUE TEMPLATE starts HERE ------
## Expected Behavior
Topbar and dock should not change color when the window is not touching either nor is maximised.
(What you were trying to do)

## Actual Behavior
The topbar and the dock turn dark. (DISCLAIMER: Maybe this is expected behavior and I'm wrong.)
(What happened instead)
![screenshot-20181031113510-1688x175](https://user-images.githubusercontent.com/44344748/47785635-35ac7300-dd01-11e8-9cc0-de6ed8e25be8.png)
## Steps to Reproduce the Problem

  1. Take any window very close (but not touching) to the topbar or dock until the color changes and release the window. The dark color of the topbar and dock remains.
  1.
  1.

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

    `$ snap info communitheme`
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 21 days ago, at 14:54 IST
channels:                    
  stable:    0.1 (1273) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1290) 17MB -
installed:   0.1 (1273) 17MB -

I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

Software that presents the issue:
- Name:
- Version:

## Icon Request

If you're filing an issue for a missing icon provide the following in your request:

- If it is an application, the file name of the icon used (can be found in the `Icon=` field in an app's `.desktop` file)
- If it is a file type icon, such as "JSON icon" please include its media type (can be found in a file's Properties dialog, e.g. `text/x-css`)
- If possible provide a screenshot, link-to, or copy of a related icon or logo.

Thanks!

**Comment by clobrano** [comment]
This is expected indeed :)
