### ISSUE TITLE
touch screen caret is stretched horizontally

### ISSUE THREAD

**Issue by jhenstridge** [ubuntu/yaru#945]
## Expected Behavior

The caret shown in response to touch screen action in an entry widget should be displayed without distortion.

## Actual Behavior

The caret is stretched horizontally:

![image](https://user-images.githubusercontent.com/12724165/47835699-41229b80-dde0-11e8-83d8-133f65ab15b4.png)

It seems that GTK expects the image asset used for the caret to have the same dimensions as the `text-select-start` and `text-select-end` assets (which is the case for Adwaita).  We're using the `slider-horz-scale-has-marks-above` asset as the caret, which is somewhat narrower.

## Steps to Reproduce the Problem

  1. Run `GTK_DEBUG=touchscreen gtk3-widget-factory` (or any other GTK app) so the mouse is treated like touch screen input.
  1. Use the mouse to position the caret in one of the text entries with the overlay 

## Specifications

This is with `yaru-theme-gtk` version 18.10.6.

**Comment by clobrano** [comment]
I tried to change both the `slider-horz-scale-has-marks-above` then `text-select-{start,end}`, but the widget is always distorted.  Changing `slider-horz-scale-has-marks-above`, moreover, creates issues in other places where it's used (it looks smaller, as expected in fact). 
Could it be a gtk rendering issue? :eyes:

**Comment by jhenstridge** [comment]
From what I can tell, the sizing is controlled by these properties:

    -GtkWidget-text-handle-width: 20;
    -GtkWidget-text-handle-height: 24;

This is used both for the touchscreen caret and selection start/end markers.  All three assets have the same dimensions in Adwaita, so there is no rendering problem.  Yaru's caret is narrower, so we see the distortion.

Without a GTK change, I think the only fix would be to use a caret image with some transparent pixels to match the dimensions of the other images

**Comment by clobrano** [comment]
> Without a GTK change, I think the only fix would be to use a caret image with some transparent pixels to match the dimensions of the other images

I have already tried that, and I didn't seem to work

**Comment by clobrano** [comment]
I've found another way to solve it :+1:
