### ISSUE TITLE
Style GNOME Clocks

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#947]
GNOME Clocks [will be a default application in Ubuntu 19.04 Disco Dingo](https://www.omgubuntu.co.uk/2018/11/ubuntu-19-04-release-features):

![default](https://user-images.githubusercontent.com/40228953/47960718-ac56b280-e018-11e8-97c6-51f76aebee79.png)

 ---

### World Clock
Style of "World Clock" corresponds to the outdated skeuomorphism:

![2018-11-04 10-01-26-2](https://user-images.githubusercontent.com/40228953/47960796-a1505200-e019-11e8-87bd-9b2a30e47395.png)

Backgrounds are in `/usr/share/gnome-clocks/images/`

![default](https://user-images.githubusercontent.com/40228953/47960825-3a7f6880-e01a-11e8-916f-fb735a27ee7b.png)

I created pictures in Yaru style:

![2018-11-04 10-12-39](https://user-images.githubusercontent.com/40228953/47960842-9518c480-e01a-11e8-962e-d9459cf16d84.png)

It remains to remove the additional background:

![2018-11-04 10-01-26-3](https://user-images.githubusercontent.com/40228953/47960957-65b68780-e01b-11e8-8400-1efd2b1c4e27.png)

**Issue will be supplemented...**

**Comment by clobrano** [comment]
If it's only about the pictures in background, I prefer the original ones

**Comment by Feichtmeier** [comment]
Hmmm... I can't say that there is anything wrong with that backgrounds. It's a very subtle. Also... with all that "evil Yaru is changing the app design"-talk I don't think this would be a very smart move

**Comment by eaglersdeveloper** [comment]
In part, I agree with you. But on the other hand, it would be nice if GNOME applications were in Yaru Design style.

**Comment by eaglersdeveloper** [comment]
I have got rid of the additional background and increase font. It remains to change the pictures.

![2018-11-05 12-09-47](https://user-images.githubusercontent.com/40228953/47986332-d6ca6d80-e0f5-11e8-9738-1214ce6963a0.png)

**Comment by clobrano** [comment]
Sorry, but honestly I don't see it as a bug

**Comment by Feichtmeier** [comment]
Me neither. It looks pretty neutral to me. It's just a background after all.
If @madsrh agrees I would rather close this (for now).

**Comment by godlyranchdressing** [comment]
Interesting idea, but I don't think it's possible to override the images like that through a theme.

**Comment by madsrh** [comment]
> If @madsrh agrees I would rather close this (for now).

Alright, I'll close this issue for now @eaglersdeveloper 

If you simply don't like the design, I would suggest that you create a beautiful mockup and post it upstream
