### ISSUE TITLE
Dark Theme issues

### ISSUE THREAD

**Issue by leoheck** [ubuntu/yaru#948]
Hi, Is there any workaround for the dark theme on any of these aps?

Inkscape 
![image](https://user-images.githubusercontent.com/1277920/47974034-b61afd00-e08e-11e8-9d9d-7398d03b5596.png)

Freecad
![image](https://user-images.githubusercontent.com/1277920/47974048-c59a4600-e08e-11e8-8ded-3e9c5e26a3e5.png)

Kicad
![image](https://user-images.githubusercontent.com/1277920/47974054-caf79080-e08e-11e8-856e-f7c0d7be4afd.png)

**Comment by Feichtmeier** [comment]
Gtk2 Dark theme is WIP and not merged yet! :)

**Comment by clobrano** [comment]
> Gtk2 Dark theme is WIP and not merged yet! :)

kind of :smile: 

It's been released in Cosmic without GTK2 support and removal was not accepted as SRU, so the best chance would be to complete GTK2 support and try to add that with SRU

**Comment by Feichtmeier** [comment]
Okay, so we'll keep this one opened?

**Comment by clobrano** [comment]
Yes, it will be fixed with gtk2 dark release

**Comment by leoheck** [comment]
Cool! Do we have any schedule or required tasks to finish it?

**Comment by leoheck** [comment]
Why I was unsubscribed from this thread?

**Comment by leoheck** [comment]
Relates to https://github.com/ubuntu/yaru/issues/654

**Comment by madsrh** [comment]
Hi @leoheck 

> Do we have any schedule or required tasks to finish it?

I'm sure you've already found it, but here's the PR (https://github.com/ubuntu/yaru/pull/852).

**Comment by Feichtmeier** [comment]
Yes for some gnome apps this is as easy as 1 click (gnome builder, gnome Todo, lutris) 
I think for libre office its not possible

**Comment by Eskander** [comment]
> Also, is it possible to set dark/light themes for a specific application?

You can set the `GTK_THEME` env variable in the app's `.desktop` file. For examle:
`GTK_THEME=Yaru gedit` or `GTK_THEME=Yaru-dark gedit` will set the app's theme accordingly.

**Comment by clobrano** [comment]
closed by #852
