### ISSUE TITLE
Sound theme: Change message-new-email

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#950]
Use `message-new-instant` instead of `message-new-email`

It sounds louder, so an user will notice a notification.
In addition, I see no reason to use a separate sound for mail.

**Comment by clobrano** [comment]
>  In addition, I see no reason to use a separate sound for mail.

to distinguish different notification?

**Comment by eaglersdeveloper** [comment]
And I see no reason to distinguish different notification.

**Comment by clobrano** [comment]
One might be interested in reading emails and discard istant messaging

**Comment by clobrano** [comment]
I am just against this change since it is not really necessary and reduces the usability IMO, but I'm not the only one in the team :D 
@madsrh, @Feichtmeier what do you think?

**Comment by Feichtmeier** [comment]
> Use `message-new-instant` instead of `message-new-email`
> 
> It sounds louder, so an user will notice a notification.
> In addition, I see no reason to use a separate sound for mail.

If one sound is much less loud than the other then it is a valid issue and I think @madsrh  can address it. But just removing one sound and replacing it with a different one makes 0 sense to me neither, sorry.

**Comment by eaglersdeveloper** [comment]
No need to distinguish between a sound of a mail notification from other notifications.
No one does this on any other OS.

**Comment by Feichtmeier** [comment]
But does vanilla gnome do it?

And sorry but my android DOES differentiate between those sounds by default :) do you can't say all OS so it just to justify your imagination about how it should be. It's a pretty up to date Android

**Comment by eaglersdeveloper** [comment]
My Android doesn't distinguish notifications 😕

**Comment by madsrh** [comment]
> My Android doesn't distinguish notifications

My One+6 does ;)

The sound are dillibertly distinguishable, so this is IMO a "won't fix" issue. 

As @Feichtmeier said we can fix the sound level. It's that something we should look into? I haven't noticed it

**Comment by madsrh** [comment]
> ...and isn't well suited for mail notification

Why? I fail to see how it is unsuited for mail notification. I've been using it here for almost a year now and I don't see any issue 🤷‍♂️ 

We could change the **audio-volume-change** to something like [this (1)](https://www.dropbox.com/s/gkdcbp05o37qdhq/audio-level_1.wav) or [this (2)](https://www.dropbox.com/s/dz70t8mqjk61cw1/audio-level_2.wav)?

**Comment by Feichtmeier** [comment]
I'd prefer (2)

**Comment by eaglersdeveloper** [comment]
I prefer re-record message-new-email. Notification should bring joy, but now it brings sadness. Why not twice repeat a note on which message-new-instant ends?

**Comment by madsrh** [comment]
> Notification should bring joy, but now it brings sadness.

Okay, I think we can agree that we disagree here. The notifications really don't bring me sadness. 

You have raised a valid point with _message-new-email_ and _audio-volume-change_ being too similar, and I will create a separate issue for that later, but I will not use the same sound for two different notifications. 
If no one else is +1 for the "sadness", I'll close this issue.
