### ISSUE TITLE
Icons not picked up by Pixel Saver extension

### ISSUE THREAD

**Issue by keunes** [ubuntu/yaru#951]
Dear Yaru developers. First of all: thank you so much for this wonderful piece of work!

I just did a fresh install of Ubuntu 18.04, and installed the Yaru snap. Being used to Unity, I missed the vertical spacial efficiency. To make improve the situation, I installed the GNOME SHELL [Pixel Saver extension](https://extensions.gnome.org/extension/723/pixel-saver/).

For many apps, this is a great improvement. However, unfortunately, it seems that the extension doesn't pick up the minimise/maximise/close buttons part of Yaru (or any other theme apparently).
![screenshot from 2018-11-05 20-44-30](https://user-images.githubusercontent.com/11229646/48022642-fbe1cf00-e13b-11e8-8895-7a1798936879.png)

While I realise there's a [problem in the extension](https://github.com/deadalnix/pixel-saver/issues/132), would there be anything you could do to (help) make Yaru & Pixel Saver look awesome together?

**Comment by godlyranchdressing** [comment]
Hi. Sure, that'll be pretty easy to do. I already made a PR that'll lend support for Yaru: deadalnix/pixel-saver/pull/183

**Comment by keunes** [comment]
Wow, thank you for the superfast response and action! I hope your PR gets merged :)
