### ISSUE TITLE
Remmina's popover menu items have no bg color change on hover

### ISSUE THREAD

**Issue by godlyranchdressing** [ubuntu/yaru#955]
## Expected Behavior

The background color of menu items should darken when hovered on.

## Actual Behavior

Background color doesn't change.

![remmina](https://user-images.githubusercontent.com/27529229/48138622-179fbf00-e27b-11e8-90d3-1d260e3b4f79.gif)

## Steps to Reproduce the Problem

  1. Open Remmina
  2. Hover over an item in the popover menu

**Comment by Feichtmeier** [comment]
A very similar hierarchy can be found in gnome disks
![peek 2018-11-23 17-47](https://user-images.githubusercontent.com/15329494/48954003-0e377780-ef48-11e8-80a5-9092ecc2f1ba.gif)
But it is styled correctly here :thinking: 
It is 
button .popup.toggle

**Comment by godlyranchdressing** [comment]
@Feichtmeier Yeah. I've been trying to fix this every now and then but I have no idea what's the source of the issue. :man_shrugging:

**Comment by Feichtmeier** [comment]
Maybe it is due to our transparent hover color? 
I think adwaita has an opaque hover bg, right? :thinking:

**Comment by monday15** [comment]
Remmina not happy about transition usage in menuitem.
https://github.com/nana-4/materia-theme/issues/300

**Comment by godlyranchdressing** [comment]
@monday15 So that's why. Thanks for your help. I guess this means we'll have to remove the transition for menu items. :disappointed: 

@Feichtmeier what do you think? I know there's a newer version of Remmina that uses a headerbar, I wonder if it works fine there.

**Comment by clobrano** [comment]
Let's see if it works first. If it does and the effect is minimal, I'd say we can go with that. Otherwise, we really want to drop a nice effect for only one application bug?

**Comment by godlyranchdressing** [comment]
@clobrano I tested it by removing the transition (line 2278) and Remmina works fine now. I am biased as I use Remmina fairly often with new projects and stuff, but with the transition being only slightly noticeable I'm leaning towards removing it.

**Comment by clobrano** [comment]
@godlyranchdressing, if the difference is minimal, I'd say it's ok to fix remmina

**Comment by antenore** [comment]
@godlyranchdressing this has been fixed in Remmina, if you want you can bring back the transition effect.

**Comment by clobrano** [comment]
@atenore, when will the version with the fix be released?

**Comment by antenore** [comment]
Already released upstream.. 1.3.2

**Comment by clobrano** [comment]
I installed 1.3.2 from PPA and reverted Yaru's workaround, but the problem seems still there...

**Comment by antenore** [comment]
@clobrano damn it's not what I've been told.
I'll investigate further.

**Comment by Feichtmeier** [comment]
Oh I copied the glade file like you mentioned on the gitlab and then reintroduced the menu transition to my local Yaru meson installation and the issue was not there, is there any difference between the current PPA code and the glade file you told me to use on the gitlab issue?

**Comment by antenore** [comment]
Normally not, I'll check.. It could be i screwed up with some commits.

**Comment by antenore** [comment]
@Feichtmeier , @clobrano I've verified and the glade file is correct, so if it doesn't work the issue is somewhere else, but I don't know how to fix it (yet).
