### ISSUE TITLE
Missing padding in 'Startup Applications' list

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#959]
A minor enhancement: This is from Tweaks, so if this issue is too application specific (since we don't ship Tweaks by default), feel free to close it 😃 

![image](https://user-images.githubusercontent.com/3986894/48221039-3a23fc00-e391-11e8-98ec-18e6a2d7a0a1.png)

And it should look like:
![image](https://user-images.githubusercontent.com/3986894/48221374-2dec6e80-e392-11e8-9695-8f24d608c610.png)

**Comment by Feichtmeier** [comment]
That double border looks also very stage

**Comment by clobrano** [comment]
This window looks terrible :(

**Comment by Feichtmeier** [comment]
Hmhm it looks the same with adwaita
![image](https://user-images.githubusercontent.com/15329494/48251888-6c6e4180-e403-11e8-88e9-b2a79116399a.png)

Maybe we should summon @jbicha in here, who is the maintainer/main contributor of tweaks, right*
_throws pokeball_
_a wild @jbicha appears_
:smile:

**Comment by madsrh** [comment]
Yes, padding-left for the app label and padding-right for the "running" label 😉

**Comment by Feichtmeier** [comment]
Hmhm he doesn't appear.
How about we close this here and open in on the tweaks gitlab repo instead? Since it looks more like an upstream issue to me and not dependent on the theme

**Comment by jbicha** [comment]
Yes, feel free to close this bug and report it to Tweaks instead.
