### ISSUE TITLE
GNOME Disks corrupted drive text is unreadable when selected

### ISSUE THREAD

**Issue by dawidpotocki** [ubuntu/yaru#960]
## Actual behavior

Text for "corrupted" drives is red, and when is selected isn't really readable.
![before selecting drive](https://user-images.githubusercontent.com/38681822/48242550-8b3ef900-e440-11e8-9936-575a64c0f13f.png)
![after selecting drive](https://user-images.githubusercontent.com/38681822/48242551-8bd78f80-e440-11e8-8dbd-c50ce75db43f.png)

## Proposed behavior

![proposed](https://user-images.githubusercontent.com/38681822/48244285-ea553b80-e449-11e8-9e29-a46def8a39ac.png)

## Steps to Reproduce the Problem

  1. Open GNOME Disks
  2. Click on corrupted drive

## Specifications

Default Yaru from 18.10 LiveCD.

Software that presents the issue:
- Name: GNOME Disks
- Version: 3.30.1

**Comment by madsrh** [comment]
Uhhh, we didn't have a corrupted drive when testing, so thanks for reporting this dawidpotocki

Any ideas @Feichtmeier ?

**Comment by Feichtmeier** [comment]
I'll check when I have a corrupted drive :D

**Comment by clobrano** [comment]
@dawidpotocki please do not fix your drive yet :smile: , we need you to fix it :wink: 

Could you please take the same screenshot with Adwaita, for comparison?

Thank you

**Comment by dawidpotocki** [comment]
I nearly though that I won't be able to make GNOME Disks to show my drive as broken :P. But there you go:

![screenshot from 2018-11-09 12-28-49](https://user-images.githubusercontent.com/38681822/48262670-50f94a00-e488-11e8-811c-28e814b60ca9.png)
![screenshot from 2018-11-09 12-28-52](https://user-images.githubusercontent.com/38681822/48262671-5191e080-e488-11e8-8688-14c04073d425.png)

Adwaita doesn't also seem to do it nicely.

Please tell me how I can help with that :).

**Comment by clobrano** [comment]
The label color is hardcoded in several places, e.g. here

    /* Otherwise, if last self-test failed, return that for the one-liner */
    if (g_str_has_prefix (udisks_drive_ata_get_smart_selftest_status (ata), "error"))
    {
      /* TODO: once https://bugzilla.gnome.org/show_bug.cgi?id=657194 is resolved, use that instead
       * of hard-coding the color
       */
      ret = g_strdup_printf ("<span foreground=\"#ff0000\"><b>%s</b></span>",
                             _("SELF-TEST FAILED"));
      warn = TRUE;
      goto out;
    }

and it's hard to see if gnome-disk add any special label to this item, because it a row inside a tree_view and gtk-inspector doesn't show it

**Comment by madsrh** [comment]
Hardcoding red on blue is really a poor choice - very hard to red.

**Comment by clobrano** [comment]
They knew it. There is a comment that reminds to a bug requesting to get the style from the theme. However the bug is now "RESOLVED OBSOLETE", so I don't know (yet) if this can be fixed or not

**Comment by clobrano** [comment]
I double checked in source code and could not find any special class for this warning message. I am afraid we can't do nothing, so I close this now
