### ISSUE TITLE
Suggestion : port nautilus ambiance side bar

### ISSUE THREAD

**Issue by PhieF** [ubuntu/yaru#963]
Hi

In latest Ambiance style, nautilus left bar was quite beautiful and I was wondering if it was possible to get the same kind of theme on Yaru 

Something like that

![capture d ecran du 2018-11-11 17 25 21](https://user-images.githubusercontent.com/26841885/48315533-db03f880-e5d7-11e8-988d-96e444ba5b86.png)

Thanks for your (beautiful) work ! :)

**Comment by clobrano** [comment]
I agree with @madsrh. Other than in Nautilus, this sidebar color is shared with other elements, which won't look good with this color, on the other side having this color only Nautilus sidebar would break our consistency
