### ISSUE TITLE
Provide a yaru mate theme

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#970]
Todo:
- [x] Create Metacity theme
- [x] Stylize GNOME Panel
- [x] Stylize MATE Panel
- [x] Stylize MATE Terminal

**Comment by Feichtmeier** [comment]
I am curious: do you plan to fix this or shall we fix this? :)

**Comment by Feichtmeier** [comment]
@eaglersdeveloper once more: do you plan to fix this or do you expect us to fix this? If the latter I have to say that we target the default ubuntu installation. Anything else, gnome-session, classic session, unity7 session is not the target of this project. We have limited time and the one we have should be put into the Ubuntu default session, IMHO

**Comment by clobrano** [comment]
> We have limited time and the one we have should be put into the Ubuntu default session, IMHO

Adding label "help-wanted" to clarify this

**Comment by eaglersdeveloper** [comment]
Good news! I have installed MATE and created Metacity theme.
But I need to do something to finish.

![Снимок экрана в 2019-05-30 20-36-39](https://user-images.githubusercontent.com/40228953/58648390-a6108680-831a-11e9-9f03-20789310b1d6.png)

**Comment by eaglersdeveloper** [comment]
Also we need to stylize MATE Panel.

**Comment by Feichtmeier** [comment]
@eaglersdeveloper 

After the recent upstream refresh, we received a metacity theme for free ;)

![Screenshot from 2019-08-20 16-35-24](https://user-images.githubusercontent.com/15329494/63356836-c0319200-c368-11e9-8019-a3c9dde68f17.png)
![Screenshot from 2019-08-20 16-35-03](https://user-images.githubusercontent.com/15329494/63356837-c0319200-c368-11e9-9a92-8ae1c243f2e3.png)
![Screenshot from 2019-08-20 16-34-29](https://user-images.githubusercontent.com/15329494/63356838-c0ca2880-c368-11e9-94a5-cb2e92f0cbae.png)

So I checked your first two check marks.
Personally I still don't feel like creating a mate theme inside yaru though

**Comment by Feichtmeier** [comment]
With the current master, and exchanging all accent colors with #87a556 yaru looks like this:
![image](https://user-images.githubusercontent.com/15329494/68289232-0f44b480-0086-11ea-93c2-9a2f65ac4414.png)
![image](https://user-images.githubusercontent.com/15329494/68289260-1966b300-0086-11ea-9bfc-da20c719507e.png)
![image](https://user-images.githubusercontent.com/15329494/68289293-27b4cf00-0086-11ea-887d-84ef78d63419.png)
![image](https://user-images.githubusercontent.com/15329494/68289329-34392780-0086-11ea-8372-6a254c95a5a0.png)

**Comment by flexiondotorg** [comment]
I love this! :heart:

**Comment by madsrh** [comment]
Any news here regarding the work @clobrano has been doing with the new build?

**Comment by clobrano** [comment]
The work is in review. I think we should wait until @didrocks has some more time to review it (after feature freeze)

**Comment by Feichtmeier** [comment]
provided in https://github.com/ubuntu/yaru/tree/hirsute/mate
