### ISSUE TITLE
@clobrano Very well done :clap:

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#974]
Tested it and I have two major issues: 
1. The toolbar_menu  
2. The menu_color
I believe it will be better that the toolbar menu will have the same color as the bg. that way it will remain at the same color when in fallback state :
current:
![screenshot from 2018-11-19 00-35-00](https://user-images.githubusercontent.com/37431503/48679347-aa9ff980-eb97-11e8-9773-e18e05e9f3ca.png)
My suggestion: 
![screenshot from 2018-11-19 00-43-52](https://user-images.githubusercontent.com/37431503/48679356-df13b580-eb97-11e8-94fc-625c465a4051.png)
I wish we could go back to a darker menu (both gtk3/gtk2). Not only because it is beautiful, main reason is better contrast and in gtk2 it compensate for the lucking of shadow for the menus.
Example:
![2018-11-19-012526_1920x1080_scrot](https://user-images.githubusercontent.com/37431503/48679568-ab865a80-eb9a-11e8-9c41-1e3cc6c4b7f4.png)

_Originally posted by @Paz-it in https://github.com/ubuntu/yaru/pull/852#issuecomment-439736027_

**Comment by clobrano** [comment]
Thanks! However, I believe that a bug is not the right place to discuss this, since there's the PR open :D
Let's discuss there.
