### ISSUE TITLE
Dark theme entries border-top could be too dark

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#975]
![image](https://user-images.githubusercontent.com/15329494/48717078-f941a800-ec18-11e8-80bd-a06ff9037c07.png)

Comparing to

![image](https://user-images.githubusercontent.com/15329494/48717110-0a8ab480-ec19-11e8-958c-27a14113dd99.png)

**Comment by clobrano** [comment]
> @madsrh @clobrano click on the images otherwise you can't see it that clearly

it's clear even without clicking on it. We should tweak the color according to the variant
