### ISSUE TITLE
Missing styling for Nautilus filter labels

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#983]
I'm not even sure this is an issue at all, but IMO there's too many lines and perhaps adding a bit of color would be nice 🎨 

### Adwaita:
![image](https://user-images.githubusercontent.com/3986894/48923639-abdf6800-eeb0-11e8-9f3e-cde18adfddb0.png)

### Yaru:
![image](https://user-images.githubusercontent.com/3986894/48923642-b863c080-eeb0-11e8-8e69-3722be3a8ee1.png)

### Mockup:
![image](https://user-images.githubusercontent.com/3986894/48923808-075e2580-eeb2-11e8-97df-673a1ef06e10.png)

**Comment by Feichtmeier** [comment]
Definitely needs work!
I wonder if the .close style class can be styled without a border for all style classes? Because tabs should have none, app notifications should have none. I wonder if we have a single . close that needs the border? @clobrano

**Comment by Feichtmeier** [comment]
Hm Maybe this way 
![image](https://user-images.githubusercontent.com/15329494/48939199-bf6fea80-ef13-11e8-84a1-039a690aebce.png)

**Comment by clobrano** [comment]
> Definitely needs work!
> I wonder if the .close style class can be styled without a border globally? Because tabs should have none, app notifications should have none. I wonder if we have a single . close that needs the border? @clobrano

Probably only the Terminal tabs, but you're right, better set it only when needed if there is only one place.

Orange doesn't look the best choice for these labels

**Comment by Feichtmeier** [comment]
WHat about this
![image](https://user-images.githubusercontent.com/15329494/48941570-4c1ea680-ef1c-11e8-98d1-4ae05830f1e0.png)
?

**Comment by Feichtmeier** [comment]
Or what about this? 
![image](https://user-images.githubusercontent.com/15329494/48941808-4ecdcb80-ef1d-11e8-9583-ded7f466d1ab.png)
@madsrh @clobrano

**Comment by madsrh** [comment]
This looks really good @Feichtmeier 
I wonder if the plain white text is a bit too much 🤷‍♂️  It's a bit hard to tell from this image.
![image](https://user-images.githubusercontent.com/3986894/48942038-1bd80780-ef1e-11e8-98c7-26dff34e0e29.png)

**Comment by Feichtmeier** [comment]
What do you mean with too much? :D

**Comment by madsrh** [comment]
Do mind the noise, maybe it's just me. I was thinking the text color maybe should be slightly more gray. IDK

![image](https://user-images.githubusercontent.com/3986894/48942284-25ae3a80-ef1f-11e8-9fd2-efa2198d5bb1.png)
![image](https://user-images.githubusercontent.com/3986894/48942282-234be080-ef1f-11e8-989a-a436ce72a181.png)

**Comment by Feichtmeier** [comment]
Like this
![image](https://user-images.githubusercontent.com/15329494/48942719-01ebf400-ef21-11e8-929b-9364e23ee8b9.png)
? @madsrh

**Comment by Feichtmeier** [comment]
Or like this
![image](https://user-images.githubusercontent.com/15329494/48942809-5000f780-ef21-11e8-9102-376c5cddd364.png)

**Comment by madsrh** [comment]
Do they look deactivated? Perhaps it's a bad idea

**Comment by Feichtmeier** [comment]
No idea! I am bad with colors! (not that I am color blind or anything... but maybe a bit too fast "ok works") You tell me! :D

**Comment by Feichtmeier** [comment]
it's only "fixed" for 3.30+
I (doesnt mean there isnt any) did not find a way to theme it for 3.26 :man_shrugging: 
@madsrh hope that is okay for you :)
