### ISSUE TITLE
Spinner is good only on white backgrounds

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#984]
Originally reported by @mymike00 in [CanonicalLtd/desktop-design#112](https://github.com/CanonicalLtd/desktop-design/issues/112):
> the [spinner](https://github.com/CanonicalLtd/desktop-design/blob/master/Toolkit%20%26%20Patterns/Theme/Progress/spinner.svg) icon can be only used on white background due to the three white shapes that spin on the orange ring.
>
> The spinner should have 3 orange shapes with no shapes between them, so transparent space, in order to show the color of the background where we would like to place that icon

**Comment by Feichtmeier** [comment]
HI @matthewpaulthomas 
this is our current spinner
![peek 2018-11-23 10-35](https://user-images.githubusercontent.com/15329494/48936538-82075f00-ef0b-11e8-8a8c-84fc8db0e595.gif)

**Comment by madsrh** [comment]
I'm closing this issue because it's unrelated to Yaru ;)

[This](https://github.com/ubports/qqc2-suru-style/issues/4) is the issue:
![image](https://user-images.githubusercontent.com/1218443/40132062-0885a5f2-593c-11e8-8c6c-16bebf40045b.gif)

@matthewpaulthomas feel free to reopen if I'm mistaken!

**Comment by matthewpaulthomas** [comment]
🤦 Sorry, I didn’t check that the issue was still valid before copying it over.

**Comment by mymike00** [comment]
@Feichtmeier 
> this is our current spinner
> ![peek 2018-11-23 10-35](https://user-images.githubusercontent.com/15329494/48936538-82075f00-ef0b-11e8-8a8c-84fc8db0e595.gif)

oh, it's a pity you don't use anymore this [spinner](https://github.com/CanonicalLtd/desktop-design/blob/master/Toolkit%20%26%20Patterns/Theme/Progress/spinner.svg), it's really gorgeous!
