### ISSUE TITLE
Context menu radio and checkbox icons are low-res

### ISSUE THREAD

**Issue by arty-name** [ubuntu/yaru#987]
## Expected Behavior

I want the built-in Yaru icons to look consistently nice on HiDPI even in the context menu

## Actual Behavior

The icons for checkbox and for radio-button are blurry in the context menu.

## Steps to Reproduce the Problem

  1. Set 200% scaling for the monitor
  1. Start gedit
  1. Click Menu -> Tools

## Specifications

```
$ snap info communitheme
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   GPL-3.0
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will
  become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme on
  Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select
  the "Ubuntu with communitheme snap" session from the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id: Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
channels:                          
  stable:    0.1 (1273) 17MB - 
  candidate: ↑                 
  beta:      ↑                 
  edge:      0.1 (1346) 18MB - 
```
Here’s how the checkbox looks in Yaru
![blurry-checkbox](https://user-images.githubusercontent.com/133055/48968702-7ee79e00-eff3-11e8-971d-0426f020b02f.png)

And here’s an example of a sharper checkbox in Adwaita
![sharp-checkbox](https://user-images.githubusercontent.com/133055/48968703-7ee79e00-eff3-11e8-978b-b28eaeca9703.png)

**Comment by Feichtmeier** [comment]
Did we miss to include the @2 asset here?

**Comment by arty-name** [comment]
If it helps I only see `check-symbolic.symbolic.png` in `/snap/gtk-common-themes/818/share/themes/Yaru/gtk-3.20/assets`

**Comment by clobrano** [comment]
It's possible, let me check

**Comment by clobrano** [comment]
I take back partially :) Adwaita svg works fine in Yaru, that gave me the right hint to fix it
