### ISSUE TITLE
Yaru on Ubuntu Unity 18.04

### ISSUE THREAD

**Issue by dontknowcris** [ubuntu/yaru#991]
Hey guys, what's up?
Can anyone tell me how to use yaru theme on unity desktop (ubuntu 18.04) with lightdm?
After I installed the snap package I cannot find the theme on unity tweak tool

**Comment by clobrano** [comment]
Hi @dontknowcris, 

thank you for your interest in Yaru ;)
The theme is dedicated to Gnome GTK/Shell right now. I our spare time we might to porting it to Unity (see #701), but there is no release date for this yet.
