### ISSUE TITLE
Migrate icons from ubuntu-mono-dark+humanity to Yaru

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#993]
- [ ] include ubuntu-mono-dark+Humanity icons inside the yaru icon theme by moving the icons (easy)

- [ ] exchange all ubuntu-mono-dark+Humanity icons with new icons (hard)

Reasoning: in the long term ubuntu would like to get rid of humanity/ubuntu-mono-dark but currently they are needed because suru/yaru icons are incomplete.

See https://github.com/snwh/suru-icon-theme/issues/82
And https://discourse.ubuntu.com/t/yaru-icons-for-emblems-actions-etc/8650

If we succeed, we should contribute the outcome to upstream Suru

To be clear, talking about these icons:
![screenshot from 2018-11-30 12-30-51](https://user-images.githubusercontent.com/15329494/49286906-da0a0c80-f49b-11e8-88a3-74bc3f2a349a.png)

**Comment by Paz-it** [comment]
Not needed IMHO. You have the inherit switch in the icons index anyway and if ubuntu decide to remove it they will have to change the inherit to a different icon theme. 
These icons as complete as they are already outdated . If you do that I'm afraid someone will decide to keep them forever  ![faint](https://user-images.githubusercontent.com/37431503/49317631-eaeb6a00-f4fd-11e8-8ab0-8d5192cb6ba6.gif)

**Comment by Feichtmeier** [comment]
I did not understand one sentence.

**Comment by Paz-it** [comment]
WOW, Really? - OK. I'll try again :   
In Yaru-Icons index.theme you can see that line that mention
Inherits=Humanity,hicolor
As long as Ubuntu installing them as part of the OS, Yaru-icons theme will fallback to those icons. 
Therefore I said, there is no need to add them to Yaru.
Now, Is it more clear? :thinking:  
If and when Ubuntu will decide to remove them, "THE INHERIT" will be an issue to be decided. I may not see the logic beyond your Idea, and maybe I missed something?

**Comment by eaglersdeveloper** [comment]
Migrate the icons and remove the word "Humanity". That's all. 🤷‍♂️

**Comment by meetdilip** [comment]
How many of them are there ? Is there a zip file available ?

**Comment by Feichtmeier** [comment]
I bet somewhere on launchpad.
I'll check later but you can see them in /usr/share/icons :)
I'd say over hundred if you count both status and actions

**Comment by Feichtmeier** [comment]
Most of the status icons should be covered by Suru though

**Comment by Feichtmeier** [comment]
@Paz-it

> If and when Ubuntu will decide to remove them, "THE INHERITS" will be an issue to be decided. I may not see the logic beyond your Idea, and maybe I missed something?

Yes exactly. As written in the opening post Ubuntu wants to get rid of this package _in the longer term_
That's the reason
+
Suru misses a lot of those icons which is the reason Suru inherits humanity which inherits Ubuntu-mono-dark

As far as I understood @didrocks correctly when we talked about cursors on the hub it is also a performance factor of the system jumps through all that directories

**Comment by Paz-it** [comment]
I'm afraid it's not so easy as you think. If you will not select carefully the icons you want to move to Yaru and then edit the index.theme accordingly. To move them in-mass will create a bigger functionality issues.

**Comment by Paz-it** [comment]
I didn't say no one removes them... I said should not be removed UNTIL Suru icons are ready.
I red the opening post, again, including the links you referred to, which one of them is my request and concern about the same issue. You said Ubuntu wants to remove them in the LONG RUN. Is it an open phrase or there is a time-tag added to it?   - I do agree we have a challenge in hand here but I'm not sure the solution you offer is optimal.

**Comment by ubuntujaggers** [comment]
Hi @Feichtmeier, do these icons need squircles or is it a different sort of icon that just needs to match the palette, gradients, drop shadow styling, etc.?

**Comment by Feichtmeier** [comment]
I'd say that they need to look like the symbolic icons in suru but with color
I will schedule some time to give you a list of the icons in the next days
But first I will migrate the humanity/ubuntu-mono-dark icons over to yaru icons

**Comment by Feichtmeier** [comment]
I think it was a bad idea to open this issue. Planing stuff likes this better goes to our project site :)
