### ISSUE TITLE
Unable to install Communitheme on Xubuntu 18.04 LTS

### ISSUE THREAD

**Issue by riyaadazad** [ubuntu/yaru#996]
## Expected Behavior

Attemped to install and _activate/use_ the Communitheme (Yaru) snap on Xubuntu 18.04. 

## Actual Behavior

Installed the snap successfully without any errors, but do not know how to activate it (it is not in the Appearance Settings window).

## Steps to Reproduce the Problem

  1. Download and Install Xubuntu 18.04 (accept all defaults)
  2. Run `sudo apt install snapd` to install Snap
  3. Run `sudo snap install communitheme` to install Communitheme
  4. Restart/reboot machine
  5. Continue to login (At login screen, the only session options are _Xfce Session_ and _Xubuntu Session_)
  6. Click on the Whisker Menu, then choose _All Settings_ 
  7. Click on _Appearance_ (but do not find "Yaru" or "Communitheme"

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

    `$ snap info communitheme`
    `name: communitheme`
    `summary: The next Ubuntu theme built by the community.`
    `publisher: Didier Roche (didrocks)`
    `license: unset`
    `description: | Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme on Ubuntu 18.04 LTS. To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select the "Ubuntu with communitheme snap" session from the login screen. More information is available at https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.`
     `snap-id: [don't know if this is sensitive so I have omitted it]`
     `tracking: stable`
     `refresh-date: today at 07:06 EST`
     `channels: **stable: 0.1 (1364) 18MB - <** | candidate: ^ | beta: ^ | edge: 0.1 (1373) 18MB - | installed: 0.1 (1364) 18MB -` 

Software that presents the issue:
- Name: Communitheme
- Version: 0.1

Thanks!

**Comment by clobrano** [comment]
Hi @riyaadazad,

thank you for the contribution. Yaru is a Gnome Theme, therefore it does not support Xfce

**Comment by riyaadazad** [comment]
Okay, thank you, @clobrano.
